'use strict';

// This archive never accepts a customer identity from the browser. Firebase
// verifies the bearer token before any Firestore connection or Shopify read.
// Stored dialogue is untrusted text, not a source of purchase/product facts.
const crypto = require('node:crypto');
const setBuilder = require('../../brites-concierge-set-builder.js');
const LIMITS = Object.freeze({bodyBytes:65536,chunks:12,messages:12,messageChars:2000,readPage:20,scan:100,clearBatch:200,syncMs:60000,authCacheMs:50000,requestMinute:20});
const CUSTOMER_QUERY = `query ConciergeCustomer($query:String!){customers(first:5,query:$query){nodes{id defaultEmailAddress{emailAddress}} pageInfo{hasNextPage}}}`;
const PURCHASE_QUERY = `query ConciergePurchases($id:ID!){customer(id:$id){id orders(first:10,reverse:true,sortKey:PROCESSED_AT,query:"financial_status:paid"){nodes{displayFinancialStatus processedAt cancelledAt test lineItems(first:20){nodes{title currentQuantity product{id handle} variant{id}} pageInfo{hasNextPage}}}pageInfo{hasNextPage}}}}`;
const hash = value => crypto.createHash('sha256').update(String(value)).digest('hex');
const plain = value => value && typeof value==='object' && !Array.isArray(value);
function failure(status,message,extra={}){const error=Error(message);error.status=status;error.extra=extra;return error;}
function namespace(env){const value=env.BRITES_GROWTH_NAMESPACE||'Brites_Growth_Sandbox';if(!/^Brites_Growth_(Sandbox|Live)$/.test(value))throw failure(503,'Customer memory is not configured.');return value;}
function scrub(value,max=2000){return String(value??'').replace(/\u0000/g,'').replace(/\b(?:password|passwd|passcode|api[_ -]?key|access[_ -]?token|refresh[_ -]?token|secret|credential)\s*(?:is|[:=])\s*(?:"[^"]*"|'[^']*'|[^\s,;]+)/gi,'[private credential]').replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,'[private email]').replace(/\bBearer\s+[^\s]+/gi,'[private token]').replace(/\b(?:sk-|AIza|eyJ)[A-Za-z0-9_.-]{15,}/g,'[private token]').replace(/(?:\+?\d[\d ().-]{7,}\d)/g,'[private number]').replace(/https?:\/\/[^\s]+/gi,url=>{try{const u=new URL(url);return u.origin+u.pathname;}catch{return '[private link]';}}).trim().slice(0,max);}
function preferences(input){const out={};if(!plain(input))return out;for(const key of ['occasion','recipient','relationship','style','metal','material','color','colour','category','meaning','theme','intent'])if(typeof input[key]==='string')out[key]=scrub(input[key],key==='intent'?300:120);for(const key of ['currency','budgetCurrency'])if(/^[A-Z]{3}$/.test(input[key]||''))out[key]=input[key];for(const key of ['budget','maxPrice'])if(typeof input[key]==='number'&&Number.isFinite(input[key])&&input[key]>=0&&input[key]<=100000)out[key]=input[key];for(const [key,allowed]of Object.entries({voicePace:['normal','slow','brisk'],voiceDetail:['brief','expanded'],suggestions:['ask','welcome','off']}))if(allowed.includes(input[key]))out[key]=input[key];return out;}
function draftRequest(body){
  if(body.consent!==true)throw failure(403,'Choose to save customer memory before using saved sets.');
  if(typeof body.generation!=='string'||!/^[A-Za-z0-9_.-]{1,96}$/.test(body.generation))throw failure(400,'Use the current customer memory generation.');
  if(body.action==='draft-read'){if(body.id!=null&&(typeof body.id!=='string'||!/^[A-Za-z0-9_.-]{1,96}$/.test(body.id)))throw failure(400,'Choose a valid saved set.');return body;}
  if(!Number.isSafeInteger(body.expectedVersion)||body.expectedVersion<0||body.expectedVersion>1000000000)throw failure(400,'Use the current saved-set version.');
  if(body.action==='draft-save'){const draft=setBuilder.sanitizeDraftHints(body.draft);if(!draft)throw failure(400,'Save a bounded set of exact public product choices.');return {...body,draft};}
  if(typeof body.id!=='string'||!/^[A-Za-z0-9_.-]{1,96}$/.test(body.id))throw failure(400,'Choose a valid saved set.');return body;
}
function chunk(input,now){
  if(!plain(input)||typeof input.id!=='string'||!/^[A-Za-z0-9_.-]{1,96}$/.test(input.id)||!['conversation','browse'].includes(input.kind))throw failure(400,'Send valid archive chunks.');
  if(!Number.isSafeInteger(input.at)||input.at<946684800000||input.at>now+60000)throw failure(400,'Send a valid archive timestamp.');
  const rows=input.messages==null?[]:input.messages;if(!Array.isArray(rows)||rows.length>LIMITS.messages||rows.some(row=>!plain(row)||!['user','assistant'].includes(row.role)||typeof row.content!=='string'||row.content.length>LIMITS.messageChars))throw failure(400,'Send bounded conversation messages.');
  const handles=input.handles==null?[]:input.handles;if(!Array.isArray(handles)||handles.length>12||handles.some(handle=>typeof handle!=='string'||!/^[a-z0-9_-]{1,180}$/.test(handle)))throw failure(400,'Send valid public product handles.');
  const messages=rows.map(row=>({role:row.role,content:scrub(row.content)})).filter(row=>row.content);
  if(input.kind==='conversation'&&!messages.length)throw failure(400,'A conversation chunk needs a message.');
  return {id:input.id,kind:input.kind,at:input.at,messages,handles:[...new Set(handles)],pageKind:['product','collection','catalogue'].includes(input.pageKind)?input.pageKind:null,preferences:preferences(input.preferences)};
}
function publicChunk(value){return {id:value.id,kind:value.kind,at:value.at,messages:(value.messages||[]).map(row=>({role:row.role,content:row.content})),handles:value.handles||[],pageKind:value.pageKind||null,preferences:preferences(value.preferences)};}
function relevance(value,query){const tokens=[...new Set(scrub(query,300).toLowerCase().match(/[\p{L}\p{N}-]{2,}/gu)||[])].slice(0,20);if(!tokens.length)return 0;const text=[...(value.messages||[]).map(row=>row.content),...(value.handles||[]),...Object.values(value.preferences||{})].join(' ').toLowerCase();return tokens.reduce((score,token)=>score+(text.includes(token)?1:0),0);}
function cursorEncode(value){return Buffer.from(JSON.stringify(value)).toString('base64url');}
function cursorDecode(value,scope,generation,query){if(!value)return {after:null,ceiling:null,offset:0};try{if(typeof value!=='string'||value.length>1000)throw Error();const parsed=JSON.parse(Buffer.from(value,'base64url').toString()),key=/^\d{16}_[a-f0-9]{32}$/;if(parsed.scope!==scope||parsed.generation!==generation||parsed.query!==hash(query)||parsed.after!=null&&!key.test(parsed.after)||parsed.ceiling!=null&&!key.test(parsed.ceiling)||!Number.isInteger(parsed.offset)||parsed.offset<0||parsed.offset>LIMITS.scan)throw Error();return parsed;}catch{throw failure(400,'Use a current archive cursor.');}}

// A separate named Firebase app avoids firebaseAdmin.js's Storage CORS write
// during cold start. These are the same existing service-account credentials.
function makeAuth(env){const admin=require('firebase-admin');if(!env.FIREBASE_PROJECT_ID||!env.FIREBASE_CLIENT_EMAIL||!env.FIREBASE_PRIVATE_KEY)throw failure(503,'Customer memory is not configured.');const name='brites-concierge-memory-'+hash(env.FIREBASE_PROJECT_ID).slice(0,12);let app=admin.apps.find(row=>row.name===name);if(!app)app=admin.initializeApp({credential:admin.credential.cert({projectId:env.FIREBASE_PROJECT_ID,clientEmail:env.FIREBASE_CLIENT_EMAIL,privateKey:env.FIREBASE_PRIVATE_KEY.replace(/\\n/g,'\n')})},name);return app.auth();}
function makeDb(env){const {Firestore}=require('@google-cloud/firestore');return new Firestore({projectId:env.FIREBASE_PROJECT_ID,credentials:{client_email:env.FIREBASE_CLIENT_EMAIL,private_key:env.FIREBASE_PRIVATE_KEY.replace(/\\n/g,'\n')}});}
function createIdentityVerifier({auth,now=Date.now}){
  const cache=new Map(),rates=new Map();
  // A guest's existing studio handoff changes Firebase's provider to custom;
  // that transfer alone does not identify a customer or authorize an archive.
  return async token=>{if(typeof token!=='string'||!token||token.length>10000)throw failure(401,'Sign in to save customer memory.');const key=hash(token),time=now(),cached=cache.get(key);let decoded;if(cached&&cached.until>time)decoded=cached.decoded;else{try{decoded=await auth.verifyIdToken(token,true);}catch{throw failure(401,'Sign in again to use customer memory.');}if(typeof decoded?.uid!=='string'||!decoded.uid||decoded.uid.length>128||decoded.firebase?.sign_in_provider==='anonymous'||decoded.handoff===true&&(typeof decoded.email!=='string'||!decoded.email.trim()))throw failure(401,'Sign in to save customer memory.');cache.set(key,{decoded,until:Math.min(time+LIMITS.authCacheMs,Number(decoded.exp||0)*1000||time+LIMITS.authCacheMs)});}
    const scope=hash(decoded.uid),old=rates.get(scope),rate=old&&old.until>time?old:{calls:0,until:time+60000};if(rate.calls>=LIMITS.requestMinute)throw failure(429,'Please wait a minute before checking memory again.',{retryAfterMs:Math.max(1000,rate.until-time)});rate.calls++;rates.set(scope,rate);if(cache.size>500)for(const [id,row]of cache)if(row.until<=time)cache.delete(id);if(rates.size>500)for(const [id,row]of rates)if(row.until<=time)rates.delete(id);
    // Firebase's standard claim describes this token's actual email. The
    // legacy custom emailVerified boolean is not bound to a particular email
    // and must not grant purchase access after an account email change.
    return {uid:decoded.uid,scope,emailVerified:decoded.email_verified===true,email:typeof decoded.email==='string'?decoded.email.trim().toLowerCase():null};};
}
function createShopifyPurchaseReader({env,fetch=globalThis.fetch,now=Date.now}){
  let access=null,expires=0;
  const configured=()=>/^[a-z0-9-]+\.myshopify\.com$/.test(env.SHOPIFY_STORE||'')&&!!env.SHOPIFY_CLIENT_ID&&!!env.SHOPIFY_CLIENT_SECRET;
  async function token(){if(access&&now()<expires-60000)return access;const response=await fetch('https://'+env.SHOPIFY_STORE+'/admin/oauth/access_token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({grant_type:'client_credentials',client_id:env.SHOPIFY_CLIENT_ID,client_secret:env.SHOPIFY_CLIENT_SECRET}),redirect:'error',signal:AbortSignal.timeout(10000)});const data=await response.json();if(!response.ok||typeof data.access_token!=='string'||!data.access_token)throw failure(503,'Purchase history could not be verified.');access=data.access_token;expires=now()+Math.min(86400,Number(data.expires_in)||86400)*1000;return access;}
  async function query(document,variables){const response=await fetch('https://'+env.SHOPIFY_STORE+'/admin/api/2026-07/graphql.json',{method:'POST',headers:{'Content-Type':'application/json','X-Shopify-Access-Token':await token()},body:JSON.stringify({query:document,variables}),redirect:'error',signal:AbortSignal.timeout(12000)});const data=await response.json();if(!response.ok||data.errors?.length||!data.data)throw failure(503,'Purchase history could not be verified.');return data.data;}
  return async identity=>{
    const base={items:[],checkedAt:now(),source:'shopify_paid_orders',limited:true};
    if(!identity.emailVerified||!identity.email||identity.email.length>254||!/^[-a-z0-9.!#$%&'*+/=?^_`{|}~]+@[-a-z0-9.]+\.[a-z]{2,}$/i.test(identity.email))return {...base,status:'unverified',reason:'verified_email_required'};
    if(!configured())return {...base,status:'unavailable',reason:'shopify_not_configured'};
    try{const found=await query(CUSTOMER_QUERY,{query:'email:'+JSON.stringify(identity.email)}),rows=found.customers?.nodes||[],matches=rows.filter(row=>row.defaultEmailAddress?.emailAddress?.trim().toLowerCase()===identity.email);if(matches.length!==1||found.customers?.pageInfo?.hasNextPage)return {...base,status:matches.length||found.customers?.pageInfo?.hasNextPage?'unverified':'none',reason:matches.length||found.customers?.pageInfo?.hasNextPage?'customer_identity_ambiguous':'no_exact_customer'};const customer=matches[0];if(!/^gid:\/\/shopify\/Customer\/\d+$/.test(customer.id||''))return {...base,status:'unverified',reason:'customer_identity_unverified'};
      const data=await query(PURCHASE_QUERY,{id:customer.id});if(data.customer?.id!==customer.id||!data.customer.orders||!Array.isArray(data.customer.orders.nodes))return {...base,status:'unavailable',reason:'order_history_unverified'};
      const items=[];for(const order of data.customer.orders.nodes.slice(0,10)){if(order.displayFinancialStatus!=='PAID'||order.cancelledAt||order.test!==false||!Number.isFinite(Date.parse(order.processedAt)))continue;for(const line of (order.lineItems?.nodes||[]).slice(0,20)){const quantity=Number(line.currentQuantity),product=line.product;if(!Number.isInteger(quantity)||quantity<=0||quantity>10000||!/^gid:\/\/shopify\/Product\/\d+$/.test(product?.id||'')||!/^[a-z0-9_-]{1,180}$/.test(product?.handle||''))continue;items.push({productId:product.id,variantId:/^gid:\/\/shopify\/ProductVariant\/\d+$/.test(line.variant?.id||'')?line.variant.id:null,title:scrub(line.title,300),handle:product.handle,quantity,purchasedAt:order.processedAt});if(items.length>=60)break;}if(items.length>=60)break;}
      return {...base,status:items.length?'verified':'none',items};
    }catch{return {...base,status:'unavailable',reason:'shopify_read_unavailable'};}
  };
}

function createMemoryService({db,env={},now=Date.now,readPurchases}){
  const ns=namespace(env),collection=db.collection(ns+'_ConciergeCustomers'),control=db.collection(ns+'_State').doc('control'),usage=()=>db.collection(ns+'_Usage').doc(new Date(now()).toISOString().slice(0,10));
  const customer=identity=>collection.doc(identity.scope||hash(identity.uid));
  // Conservative estimated costs, explicitly recorded as estimates. No paid
  // summarization, vector index or per-turn archive rewrite is performed.
  async function reserve(action){const estimate=['sync','draft-save'].includes(action)?0.001:['clear','draft-clear'].includes(action)?0.003:0.0005,ref=usage();await db.runTransaction(async tx=>{const controls=await tx.get(control),previous=await tx.get(ref),settings=controls.exists?controls.data():{},data=previous.exists?previous.data():{};if(settings.conciergeMemoryEnabled===false)throw failure(503,'Customer memory is paused.');const configured=Number(settings.aiDailyUsdCap??1),specific=Number(settings.conciergeMemoryDailyUsdCap??configured),cap=Math.min(configured,specific);if(!Number.isFinite(cap)||cap<=0||Number(data.spentUsd||0)+Number(data.reservedUsd||0)+estimate>cap)throw failure(429,'Customer memory has reached its daily allowance.',{retryAfterMs:3600000});tx.set(ref,{...data,spentUsd:Number(data.spentUsd||0)+estimate,memoryEstimatedUsd:Number(data.memoryEstimatedUsd||0)+estimate,memoryCalls:Number(data.memoryCalls||0)+1,memoryCostBasis:'conservative_firestore_estimate',at:now()});});}
  async function metadata(ref){const snapshot=await ref.get();return snapshot.exists?snapshot.data():{generation:'0',lastSyncAt:null};}
  async function currentGeneration(ref,generation){const current=await metadata(ref);if((current.generation||'0')!==generation)throw failure(409,'The saved archive was cleared. Start a fresh archive.',{resetRequired:true,generation:current.generation||'0'});}
  async function sync(identity,body){const input=body.chunks;if(!Array.isArray(input)||input.length<1||input.length>LIMITS.chunks)throw failure(400,'Send 1–12 archive chunks.');const normalized=input.map(value=>chunk(value,now()));if(new Set(normalized.map(value=>value.id)).size!==normalized.length)throw failure(400,'Archive chunk IDs must be unique.');await reserve('sync');const ref=customer(identity);return db.runTransaction(async tx=>{const snapshot=await tx.get(ref),meta=snapshot.exists?snapshot.data():{},generation=meta.generation||'0';if((body.generation||'0')!==generation)throw failure(409,'The saved archive was cleared. Start a fresh archive.',{resetRequired:true,generation});const chunks=ref.collection('Archive_'+generation),refs=normalized.map(value=>chunks.doc(hash(value.id))),existing=await Promise.all(refs.map(row=>tx.get(row))),newRows=normalized.filter((value,index)=>!existing[index].exists);if(!newRows.length)return {ok:true,generation,saved:0,duplicates:normalized.length,syncAfterMs:LIMITS.syncMs};if(meta.lastSyncAt!=null&&now()-meta.lastSyncAt<LIMITS.syncMs)throw failure(429,'Saved memory syncs once a minute.',{retryAfterMs:LIMITS.syncMs-(now()-meta.lastSyncAt)});for(let i=0;i<normalized.length;i++)if(!existing[i].exists)tx.set(refs[i],{...normalized[i],sortKey:String(Math.floor(normalized[i].at)).padStart(16,'0')+'_'+hash(normalized[i].id).slice(0,32),receivedAt:now()});tx.set(ref,{...meta,schema:1,generation,lastSyncAt:now(),chunkCount:Number(meta.chunkCount||0)+newRows.length});return {ok:true,generation,saved:newRows.length,duplicates:normalized.length-newRows.length,syncAfterMs:LIMITS.syncMs};});}
  async function read(identity,body){const query=typeof body.query==='string'?scrub(body.query,300):'';if(typeof body.query==='string'&&body.query.length>300)throw failure(400,'Use a shorter history search.');const limit=body.limit==null?12:Number(body.limit);if(!Number.isInteger(limit)||limit<1||limit>LIMITS.readPage)throw failure(400,'Read 1–20 history chunks at a time.');await reserve('read');const ref=customer(identity),meta=await metadata(ref),generation=meta.generation||'0',scope=identity.scope||hash(identity.uid),cursor=cursorDecode(body.cursor,scope,generation,query);let scan=ref.collection('Archive_'+generation).orderBy('sortKey','desc');if(cursor.ceiling)scan=scan.where('sortKey','<=',cursor.ceiling);if(cursor.after)scan=scan.startAfter(cursor.after);const count=query?LIMITS.scan:limit,snapshot=await scan.limit(count+1).get(),all=snapshot.docs.slice(0,count).map(row=>row.data()),ranked=all.map(value=>({...publicChunk(value),relevance:query?relevance(value,query):0})).filter(value=>!query||value.relevance>0).sort((a,b)=>query?b.relevance-a.relevance||b.at-a.at||a.id.localeCompare(b.id):0),out=ranked.slice(cursor.offset,cursor.offset+limit),last=all[all.length-1],ceiling=cursor.ceiling||all[0]?.sortKey||null;let nextCursor=null;if(cursor.offset+limit<ranked.length)nextCursor=cursorEncode({scope,generation,query:hash(query),after:cursor.after,ceiling,offset:cursor.offset+limit});else if(snapshot.docs.length>count&&last)nextCursor=cursorEncode({scope,generation,query:hash(query),after:last.sortKey,ceiling,offset:0});const merged={};for(const value of all.slice().reverse())Object.assign(merged,preferences(value.preferences));await currentGeneration(ref,generation);return {ok:true,generation,chunks:out,nextCursor,preferences:merged,bounded:true,source:'authenticated_archive'};}
  async function purchases(identity){if(!identity.emailVerified)return {ok:true,purchases:{status:'unverified',items:[],checkedAt:now(),source:'shopify_paid_orders',limited:true,reason:'verified_email_required'}};await reserve('purchases');return {ok:true,purchases:await readPurchases(identity)};}
  function draftGeneration(meta,body){const generation=meta.generation||'0';if(body.generation!==generation)throw failure(409,'The saved archive was cleared. Start a fresh archive.',{resetRequired:true,generation});return generation;}
  function draftVersion(meta,body){const version=Number.isSafeInteger(meta.setDraftVersion)?meta.setDraftVersion:0;if(body.expectedVersion!==version)throw failure(409,'The saved set changed in another tab. Review its current version.',{conflictRequired:true,version});return version;}
  function publicDraft(value,version){const draft=setBuilder.sanitizeDraftHints(value?.draft);return draft?{draft,version,updatedAt:Number.isSafeInteger(value.updatedAt)?value.updatedAt:null}:null;}
  async function draftRead(identity,input){const body=draftRequest({...input,action:'draft-read'});await reserve('draft-read');const ref=customer(identity),meta=await metadata(ref),generation=draftGeneration(meta,body),version=Number.isSafeInteger(meta.setDraftVersion)?meta.setDraftVersion:0,ids=(Array.isArray(meta.setDraftIds)?meta.setDraftIds:[]).filter(id=>typeof id==='string'&&/^[A-Za-z0-9_.-]{1,96}$/.test(id)).slice(0,setBuilder.LIMITS.drafts),selected=body.id?ids.filter(id=>id===body.id):ids,collection=ref.collection('SetDrafts_'+generation),snapshots=await Promise.all(selected.map(id=>collection.doc(hash(id)).get()));const drafts=snapshots.map(snapshot=>snapshot.exists?publicDraft(snapshot.data(),version):null).filter(Boolean).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)||a.draft.id.localeCompare(b.draft.id));await currentGeneration(ref,generation);const latest=await metadata(ref);draftGeneration(latest,body);if((latest.setDraftVersion||0)!==version)throw failure(409,'The saved set changed while it was being read. Check again.',{conflictRequired:true,version:latest.setDraftVersion||0});return {ok:true,generation,version,drafts,bounded:true,source:'authenticated_set_drafts',requiresFreshCheck:true};}
  async function draftSave(identity,input){const body=draftRequest({...input,action:'draft-save'}),draft=body.draft;await reserve('draft-save');const ref=customer(identity);return db.runTransaction(async tx=>{const snapshot=await tx.get(ref),meta=snapshot.exists?snapshot.data():{},generation=draftGeneration(meta,body),version=draftVersion(meta,body),ids=(Array.isArray(meta.setDraftIds)?meta.setDraftIds:[]).slice(0,setBuilder.LIMITS.drafts),target=ref.collection('SetDrafts_'+generation).doc(hash(draft.id)),previous=await tx.get(target),fingerprint=hash(JSON.stringify(draft));if(previous.exists&&previous.data().fingerprint===fingerprint)return {ok:true,generation,version,...publicDraft(previous.data(),version),duplicate:true,syncAfterMs:LIMITS.syncMs};if(!ids.includes(draft.id)&&ids.length>=setBuilder.LIMITS.drafts)throw failure(409,'Keep up to five saved sets. Forget one before saving another.',{draftLimit:true});if(meta.lastDraftWriteAt!=null&&now()-meta.lastDraftWriteAt<LIMITS.syncMs)throw failure(429,'Saved sets sync once a minute.',{retryAfterMs:LIMITS.syncMs-(now()-meta.lastDraftWriteAt)});const updatedAt=now(),nextVersion=version+1;tx.set(target,{schema:1,draft,fingerprint,updatedAt});tx.set(ref,{...meta,schema:1,generation,setDraftIds:[...new Set([...ids,draft.id])],setDraftVersion:nextVersion,lastDraftWriteAt:updatedAt});return {ok:true,generation,draft,version:nextVersion,updatedAt,syncAfterMs:LIMITS.syncMs,requiresFreshCheck:true};});}
  async function draftClear(identity,input){const body=draftRequest({...input,action:'draft-clear'});await reserve('draft-clear');const ref=customer(identity);return db.runTransaction(async tx=>{const snapshot=await tx.get(ref),meta=snapshot.exists?snapshot.data():{},generation=draftGeneration(meta,body),version=draftVersion(meta,body),ids=(Array.isArray(meta.setDraftIds)?meta.setDraftIds:[]).slice(0,setBuilder.LIMITS.drafts);if(!ids.includes(body.id))return {ok:true,generation,version,cleared:true,id:body.id};if(meta.lastDraftWriteAt!=null&&now()-meta.lastDraftWriteAt<LIMITS.syncMs)throw failure(429,'Saved sets sync once a minute.',{retryAfterMs:LIMITS.syncMs-(now()-meta.lastDraftWriteAt)});tx.delete(ref.collection('SetDrafts_'+generation).doc(hash(body.id)));tx.set(ref,{...meta,setDraftIds:ids.filter(id=>id!==body.id),setDraftVersion:version+1,lastDraftWriteAt:now()});return {ok:true,generation,version:version+1,cleared:true,id:body.id,syncAfterMs:LIMITS.syncMs};});}
  async function clear(identity,body){await reserve('clear');const ref=customer(identity);let generation,cleanup;await db.runTransaction(async tx=>{const snapshot=await tx.get(ref),meta=snapshot.exists?snapshot.data():{};if(body.cleanup===true){generation=meta.generation||'0';if(body.generation!==generation)throw failure(409,'Use the current archive generation.',{resetRequired:true,generation});cleanup=Array.isArray(meta.cleanupGenerations)?meta.cleanupGenerations:[];}else{generation=crypto.randomUUID();cleanup=[...new Set([...(Array.isArray(meta.cleanupGenerations)?meta.cleanupGenerations:[]),meta.generation||'0'])];tx.set(ref,{schema:1,generation,lastSyncAt:null,chunkCount:0,clearedAt:now(),cleanupGenerations:cleanup,cleanupPending:true});}});const target=cleanup[0];if(target){const snapshot=await ref.collection('Archive_'+target).limit(LIMITS.clearBatch).get(),drafts=await ref.collection('SetDrafts_'+target).limit(setBuilder.LIMITS.drafts+1).get();if(snapshot.docs.length||drafts.docs.length){const batch=db.batch();for(const doc of [...snapshot.docs,...drafts.docs])batch.delete(doc.ref);await batch.commit();}if(snapshot.docs.length<LIMITS.clearBatch&&drafts.docs.length<setBuilder.LIMITS.drafts+1)cleanup=cleanup.filter(value=>value!==target);}await db.runTransaction(async tx=>{const snapshot=await tx.get(ref),meta=snapshot.data()||{};if(meta.generation===generation)tx.set(ref,{cleanupGenerations:cleanup,cleanupPending:!!cleanup.length},{merge:true});});return {ok:true,cleared:true,generation,cleanupPending:!!cleanup.length};}
  async function execute(identity,body){if(!identity?.uid)throw failure(401,'Sign in to use customer memory.');if(body.action==='sync')return sync(identity,body);if(body.action==='read')return read(identity,body);if(body.action==='purchases')return purchases(identity);if(body.action==='clear')return clear(identity,body);if(body.action==='draft-read')return draftRead(identity,body);if(body.action==='draft-save')return draftSave(identity,body);if(body.action==='draft-clear')return draftClear(identity,body);throw failure(400,'Choose a supported memory action.');}
  return {execute,sync,read,purchases,clear,draftRead,draftSave,draftClear};
}
function createRequestHandler({env={},now=Date.now,auth,db,readPurchases,fetch=globalThis.fetch}={}){
  let verifier,service;
  return async req=>{const origin=req.headers.get('Origin'),allowed=!origin||['https://britesjewelry.com','https://www.britesjewelry.com',new URL(req.url).origin].includes(origin),headers={'Content-Type':'application/json','Cache-Control':'no-store','Vary':'Origin',...(origin&&allowed?{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'POST, OPTIONS'}:{})},json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers});if(!allowed)return json({error:'Customer memory is available from the shop and its preview.'},403);if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return json({error:'Use POST.'},405);
    try{const bearer=/^Bearer\s+(.+)$/i.exec(req.headers.get('Authorization')||'');if(!bearer)throw failure(401,'Sign in to use customer memory.');if(Number(req.headers.get('Content-Length'))>LIMITS.bodyBytes)throw failure(413,'That archive batch is too large.');const raw=await req.text();if(Buffer.byteLength(raw,'utf8')>LIMITS.bodyBytes)throw failure(413,'That archive batch is too large.');let body;try{body=JSON.parse(raw);}catch{throw failure(400,'Send a valid memory request.');}if(!plain(body)||!['sync','read','purchases','clear','draft-read','draft-save','draft-clear'].includes(body.action))throw failure(400,'Choose a supported memory action.');if(body.action.startsWith('draft-'))body=draftRequest(body);verifier=verifier||createIdentityVerifier({auth:auth||makeAuth(env),now});const identity=await verifier(bearer[1].trim());service=service||createMemoryService({db:db||makeDb(env),env,now,readPurchases:readPurchases||createShopifyPurchaseReader({env,fetch,now})});return json(await service.execute(identity,body));}catch(error){const status=Number(error.status)||503;return json({error:status===503?'Customer memory could not be checked just now.':error.message,...error.extra},status);}
  };
}
module.exports={LIMITS,CUSTOMER_QUERY,PURCHASE_QUERY,namespace,scrub,preferences,chunk,relevance,draftRequest,createIdentityVerifier,createShopifyPurchaseReader,createMemoryService,createRequestHandler};
