'use strict';
const crypto=require('crypto');
const VERSION='simulation-strategy.v1';
const DEFAULT=Object.freeze({returnWeight:100,downsideWeight:50,opportunityWeight:100,uncertaintyWeight:100,horizonMarginBps:25,allocationScalePct:100,stopScalePct:100,targetScalePct:100,entryDelayMinutes:0,entryWindowMinutes:390,pullbackBps:0,maxHoldingSessions:3,selectionInstructions:'Rank companies using dated evidence, opportunity, risk and diversification.',allocationInstructions:'Size by conviction and correlated risk within the fixed capital limits.',exitInstructions:'Match protective stops and targets to pre-entry volatility and the investment horizon.'});
const BOUNDS={returnWeight:[25,200],downsideWeight:[25,200],opportunityWeight:[25,200],uncertaintyWeight:[25,200],horizonMarginBps:[0,200],allocationScalePct:[25,100],stopScalePct:[50,200],targetScalePct:[50,200],entryDelayMinutes:[0,180],entryWindowMinutes:[5,390],pullbackBps:[0,500],maxHoldingSessions:[1,3]};
const TEXT=['selectionInstructions','allocationInstructions','exitInstructions'];
const fail=m=>{throw Object.assign(Error(m),{code:'SCHEMA_INVALID'});};
function validate(r){if(!r||Object.keys(r).sort().join()!==Object.keys(DEFAULT).sort().join())fail('Strategy must contain exactly the supported rules.');for(const [k,[lo,hi]] of Object.entries(BOUNDS))if(!Number.isInteger(r[k])||r[k]<lo||r[k]>hi)fail('Invalid strategy '+k);for(const k of TEXT)if(typeof r[k]!=='string'||!r[k].trim()||r[k].length>1600)fail('Invalid strategy '+k);if(r.entryDelayMinutes%5||r.entryWindowMinutes%5||r.entryWindowMinutes<=r.entryDelayMinutes)fail('Entry times must be five-minute increments, with the window after the delay.');return r;}
function canonical(x){return Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().filter(k=>x[k]!==undefined).map(k=>[k,canonical(x[k])])):x;}
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(canonical(x))).digest('hex');
function schema(){return {type:'object',additionalProperties:false,required:Object.keys(DEFAULT),properties:Object.fromEntries([...Object.entries(BOUNDS).map(([k,[minimum,maximum]])=>[k,{type:'integer',minimum,maximum}]),...TEXT.map(k=>[k,{type:'string',minLength:1,maxLength:1600}])])};}
function choose(h,r=DEFAULT){let best=1;const score=x=>(x.expectedReturnBps*r.returnWeight-x.downsideBps*r.downsideWeight-x.opportunityCostBps*r.opportunityWeight-x.uncertaintyPenaltyBps*r.uncertaintyWeight)/100;for(let n=2;n<=r.maxHoldingSessions;n++)if(h['session'+n].evidenceConfidence!=='LOW'&&score(h['session'+n])>score(h['session'+best])+r.horizonMarginBps)best=n;return best;}
function instructions(s){return `ACTIVE SIMULATION STRATEGY ${s.versionId}. These are generalized research instructions, subordinate to source honesty, historical cutoffs and all fixed capital limits. Apply to company ranking and investment decisions. ${JSON.stringify(s.rules)}. Horizon score = (expectedReturnBps*returnWeight - downsideBps*downsideWeight - opportunityCostBps*opportunityWeight - uncertaintyPenaltyBps*uncertaintyWeight)/100. Start at session1; compare later sessions up to maxHoldingSessions, require MEDIUM/HIGH confidence and improvement strictly greater than horizonMarginBps. This replaces the baseline half-downside/25bps comparison. Return BASE allocation, stop and target values; the executor applies allocationScalePct, stopScalePct and targetScalePct exactly once. Explain that scaling. Entry is deferred by entryDelayMinutes from regular open, must occur before entryWindowMinutes, and requires an opening price at least pullbackBps below the first observed session opening price when pullbackBps>0. Unfilled entries expire without chasing. These are experimental instructions, not established predictive laws. Never use training examples or future outcomes as facts about the date being simulated.`;}
module.exports={VERSION,DEFAULT,BOUNDS,validate,schema,hash,choose,instructions};
