// Read-only context and complete, paginated Shopify image galleries for Ad Design.
// Identity comes from current Google resources, reviewed drafts, exact offer IDs
// or a Shopify lookup for an exact owned destination handle; never title similarity.
// Shopify queries validated 2026-09-10 against Admin GraphQL (product/MediaImage).
const str=(v,n=400)=>String(v==null?'':v).trim().slice(0,n);
function productId(raw){const m=String(raw||'').match(/^(?:gid:\/\/shopify\/Product\/)?(\d+)$/);return m?m[1]:null;}
function offerParts(raw){const m=String(raw||'').match(/^shopify_([^_]+)_(\d+)_(\d+)$/i);return m?{itemId:String(raw),market:m[1],productId:m[2],variantId:m[3]}:null;}
function sourceUrl(raw,image=false){try{const u=new URL(String(raw||''));if(u.protocol!=='https:'||u.username||u.password)return null;const allowed=image?['britesjewelry.com','www.britesjewelry.com','cdn.shopify.com']:['britesjewelry.com','www.britesjewelry.com'];return allowed.includes(u.hostname)?u.toString():null;}catch(_){return null;}}
function destination(raw){const url=sourceUrl(raw);if(!url)return null;const u=new URL(url),p=u.pathname.match(/\/(?:collections\/[^/]+\/)?products\/([a-zA-Z0-9_-]+)\/?$/),c=u.pathname.match(/^\/collections\/([a-zA-Z0-9_-]+)\/?$/);return p?{kind:'product',handle:p[1],url}:c?{kind:'collection',handle:c[1],url}:{kind:'page',url};}
const literal=JSON.stringify;
function createAdDesignContext(D){
  const now=()=>D.now?D.now():Date.now();
  async function query(code,deadline){const ms=Math.max(1,Math.min(9000,(deadline||now()+9000)-now()));if(ms<100)throw new Error('The gallery reached its request time allowance. Load the remaining photos to continue.');let timer;try{return await Promise.race([D.shopifyGql(code),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('Shopify image lookup timed out.')),ms);})]);}finally{clearTimeout(timer);}}
  async function loadProductImages({productId:id,after=null,all=false,deadline=null}={}){
    id=productId(id);if(!id)throw new Error('An exact Shopify product ID is required.');
    const finish=deadline||now()+20000,images=[],seen=new Set(),cursors=new Set();let cursor=after,product=null,hasMore=false,nextCursor=null,pages=0,warnings=[];
    do {
      if(cursor&&cursors.has(cursor))throw new Error('Shopify repeated an image cursor; remaining gallery pages need a retry.');if(cursor)cursors.add(cursor);
      let data;try{data=await query(`query AdDesignProductImages { product(id: ${literal('gid://shopify/Product/'+id)}) { id title handle description onlineStoreUrl media(first: 100${cursor?', after: '+literal(cursor):''}, query: "media_type:IMAGE", sortKey: POSITION) { nodes { id alt ... on MediaImage { image { url width height } } } pageInfo { hasNextPage endCursor } } } }`,finish);}catch(error){if(!product)throw error;hasMore=true;nextCursor=cursor;warnings.push(str(error.message,250));break;}
      const p=data&&data.product;if(!p||productId(p.id)!==id)throw new Error('This exact Shopify product was not found in the connected store.');
      if(!product)product={id:p.id,title:str(p.title,250),handle:str(p.handle,160),description:str(p.description,12000),url:sourceUrl(p.onlineStoreUrl)||(/^[a-zA-Z0-9_-]+$/.test(p.handle||'')?'https://britesjewelry.com/products/'+encodeURIComponent(p.handle):null)};
      if(!product.url)throw new Error('This product has no verified Brites destination.');
      for(const node of p.media&&p.media.nodes||[]){const image=node.image||{},url=sourceUrl(image.url,true);if(!url){warnings.push('One product-media item did not expose a supported ready image URL.');continue;}const key=String(node.id||url);if(seen.has(key))continue;seen.add(key);images.push({id:key,url,alt:str(node.alt,400),width:Number(image.width)||null,height:Number(image.height)||null,productId:p.id,source:'Shopify product media'});}
      const info=p.media&&p.media.pageInfo||{};hasMore=!!info.hasNextPage;nextCursor=hasMore?info.endCursor||null:null;pages++;
      if(hasMore&&!nextCursor)throw new Error('Shopify returned more product photos without a pagination cursor.');
      if(!all||!hasMore)break;
      cursor=nextCursor;
      if(now()+1500>=finish){warnings.push('More photos are available; continue this product’s gallery.');break;}
    }while(hasMore);
    return {...product,images,complete:!hasMore,hasMore,nextCursor,imagesReturned:images.length,pages,warnings,checkedAt:now(),source:'Shopify product media, including variant-associated images'};
  }
  async function loadContext(input={}){
    const started=now(),deadline=started+22000,warnings=[],itemIds=new Set(),ids=new Set(),productSources=new Map();let groups=[],campaignId=null,approvalId=null,sourceVersion=null,snapshotHash=null,snapshot=null,handle=null,approval=null,approvalPayloadHash=null,generationAllowed=false;const destinationProducts=new Map(),approvedSourceIds=new Set();
    let range=input.range||null;if(!range&&D.reportContext&&D.validatedRange){const r=await D.reportContext();range={...D.validatedRange({start:input.start,end:input.end},r.accountToday,30),timeZone:r.accountTimezone,currency:r.budgetCurrency};}
    const addOffer=x=>{const o=offerParts(x);if(o){itemIds.add(o.itemId);ids.add(o.productId);productSources.set(o.productId,'Exact Merchant offer ID');}else if(x)warnings.push('An unrecognized offer ID could not be matched to a Shopify product.');};
    const cleanGroups=rows=>(rows||[]).map((g,i)=>({key:str(g.key||'g'+i,100),ref:str(g.ref,250),name:str(g.name||'Ad '+(i+1),200),channel:g.channel,url:sourceUrl(g.url),keywords:(g.keywords||[]).map(k=>str(typeof k==='string'?k:k.text,100)).filter(Boolean),original:g.original||{},itemIds:g.itemIds||[],productIds:(g.productIds||[]).map(productId).filter(Boolean)})).filter(g=>['pmax','search'].includes(g.channel)&&g.ref&&g.url);
    if(input.approvalId){approvalId=String(input.approvalId);if(!/^[A-Za-z0-9_-]{1,120}$/.test(approvalId))throw new Error('Invalid approval reference.');if(!D.fb())throw new Error('Approval storage is unavailable.');const doc=await D.fb().db.collection(D.COL.approvals).doc(approvalId).get();if(!doc.exists)throw new Error('The selected approval was not found.');approval=doc.data();if(!['PENDING','APPROVED'].includes(approval.status))throw new Error('Only an unpublished approval can be opened for design.');const p=approval.payload||{},meta=p.meta||{};approvalPayloadHash=D.creativeHash?D.creativeHash(p):null;for(const source of meta.sourceProducts||[]){const id=productId(source.id||source.productId);if(id)approvedSourceIds.add(id);}campaignId=str(meta.existingCampaignId||p.versionGuard&&p.versionGuard.campaignId||input.campaignId);handle=str(meta.handle||p.finalCollection||input.handle,160)||null;
      for(const id of [...(p.itemIds||[]),...(meta.itemIds||[]),...(meta.assetGroups||[]).flatMap(g=>g.itemIds||[])])addOffer(id);
      try{groups=cleanGroups(D.creativeGroups(approval));}catch(e){if(!campaignId)throw e;}
      generationAllowed=true;
    } else if(input.campaignId){campaignId=String(input.campaignId);}
    if(campaignId){if(!/^\d+$/.test(campaignId))throw new Error('Invalid campaign reference.');if(input.campaignId&&String(input.campaignId)!==campaignId)throw new Error('The selected approval belongs to another campaign.');const guard=approval&&approval.payload&&approval.payload.versionGuard||{};const verified=await D.verifiedBasis({campaignId,expectedVersion:guard.expectedVersion||input.expectedVersion,snapshotHash:guard.snapshotHash||input.snapshotHash});snapshot=verified.snapshot;sourceVersion=verified.version;snapshotHash=verified.snapshotHash;const c=snapshot.components||{};
      if(!groups.length){if(snapshot.channel==='SEARCH')groups=cleanGroups((c.searchAds||[]).map(a=>({key:'ad-'+String(a.resourceName).split('/').pop(),ref:a.resourceName,name:'Search ad '+String(a.resourceName).split('/').pop(),channel:'search',url:(a.finalUrls||[])[0],keywords:(c.keywords||[]).filter(k=>k.adGroup===a.adGroup&&!k.negative&&k.status==='ENABLED').map(k=>(k.keyword||{}).text),original:a.responsiveSearchAd||{}})));
        else if(snapshot.channel==='PERFORMANCE_MAX')groups=cleanGroups((c.assetGroups||[]).map(g=>{const links=(c.assetLinks||[]).filter(a=>a.assetGroup===g.resourceName),field=t=>links.filter(a=>a.fieldType===t&&a.text).map(a=>a.text);return {key:'asset-group-'+String(g.resourceName).split('/').pop(),ref:g.resourceName,name:g.name,channel:'pmax',url:(g.finalUrls||[])[0],keywords:[],original:{headlines:field('HEADLINE'),longHeadlines:field('LONG_HEADLINE'),descriptions:field('DESCRIPTION')},itemIds:(c.listingGroups||[]).filter(l=>l.assetGroup===g.resourceName&&l.type==='UNIT_INCLUDED').map(l=>((l.caseValue||{}).productItemId||{}).value).filter(Boolean)};}));}
      for(const g of groups){(g.itemIds||[]).forEach(addOffer);if(!g.itemIds.length){const matching=(c.listingGroups||[]).filter(l=>l.assetGroup===g.ref&&l.type==='UNIT_INCLUDED').map(l=>((l.caseValue||{}).productItemId||{}).value).filter(Boolean);g.itemIds=matching;matching.forEach(addOffer);}g.productIds=[...new Set([...(g.productIds||[]),...(g.itemIds||[]).map(offerParts).filter(Boolean).map(x=>x.productId)])];}generationAllowed=true;
    }
    if(!campaignId&&!approvalId){handle=str(input.handle,160)||null;if(handle&&!/^[a-zA-Z0-9_-]+$/.test(handle))throw new Error('Invalid collection handle.');(input.itemIds||[]).slice(0,60).forEach(addOffer);if(itemIds.size){const url=handle?'https://britesjewelry.com/collections/'+encodeURIComponent(handle):sourceUrl(input.url);if(!url)throw new Error('Select the intended Brites destination for this product opportunity.');groups=cleanGroups([{key:'opportunity',ref:'opportunity:'+handle,name:str(input.name||handle||'Product opportunity',200),channel:'pmax',url,keywords:input.searchThemes||[],original:{},itemIds:[...itemIds]}]);generationAllowed=true;}
      else if(handle)warnings.push('Browse this collection’s photos; choose an exact product offer before generating a new product ad.');
    }
    if(input.groupRef){const group=groups.find(g=>g.ref===String(input.groupRef));if(!group)throw new Error('This ad group is not part of the selected campaign or approval.');groups=[group];ids.clear();productSources.clear();itemIds.clear();(group.itemIds||[]).forEach(addOffer);}
    // Resolve exact destination handles, never search titles or infer product IDs.
    const destinations=[...new Map(groups.map(g=>destination(g.url)).filter(Boolean).map(d=>[d.url,d])).values()];
    if(handle&&!destinations.some(d=>d.kind==='collection'&&d.handle===handle))destinations.push({kind:'collection',handle,url:'https://britesjewelry.com/collections/'+handle});
    const galleryBrowse=[];
    for(const d of destinations){if(now()+1500>=deadline){warnings.push('Destination product lookup reached the time allowance.');break;}try{
      if(d.kind==='product'){const data=await query(`query AdDesignProductHandle { productByHandle(handle: ${literal(d.handle)}) { id title handle } }`,deadline),p=data&&data.productByHandle,id=p&&productId(p.id);if(id){ids.add(id);productSources.set(id,'Exact ad destination product');destinationProducts.set(d.url,new Set([id]));}else warnings.push('The destination product was not found in Shopify.');}
      else if(d.kind==='collection'&&(!groups.length||groups.some(g=>g.url===d.url&&!g.itemIds.length))){const data=await query(`query AdDesignCollectionProducts { collectionByHandle(handle: ${literal(d.handle)}) { id title products(first: 12, sortKey: BEST_SELLING) { nodes { id title handle } pageInfo { hasNextPage endCursor } } } }`,deadline),conn=data&&data.collectionByHandle&&data.collectionByHandle.products;if(conn){for(const p of conn.nodes||[]){const id=productId(p.id);if(id){ids.add(id);productSources.set(id,'Product in exact destination collection');}}destinationProducts.set(d.url,new Set((conn.nodes||[]).map(p=>productId(p.id)).filter(Boolean)));galleryBrowse.push({handle:d.handle,hasMore:!!(conn.pageInfo||{}).hasNextPage,nextCursor:(conn.pageInfo||{}).endCursor||null});}else warnings.push('The destination collection was not found in Shopify.');}
    }catch(e){warnings.push(str(e.message,250));}}
    const serviceGroups=groups.filter(g=>{const d=destination(g.url);return d&&d.kind==='page'&&!g.itemIds.length;});
    for(const id of approvedSourceIds){if(serviceGroups.length){ids.add(id);productSources.set(id,'Verified product source recorded in the existing approval');serviceGroups.forEach(g=>g.productIds.push(id));}}
    for(const raw of (input.productIds||[]).slice(0,24)){const id=productId(raw);if(!id)throw new Error('Product selections must use exact Shopify IDs.');
      const known=ids.has(id);if(!known&&!serviceGroups.length)throw new Error('The selected product is outside this ad’s verified offer or destination scope. Choose a product from the matching gallery.');
      if(!known&&serviceGroups.length){ids.add(id);productSources.set(id,'Explicit product selected for the existing service destination; Shopify identity verified below');serviceGroups.forEach(g=>g.productIds.push(id));}
    }
    if(!groups.length&&handle)groups=[{key:'browse',ref:'browse:'+handle,name:handle,channel:'pmax',url:'https://britesjewelry.com/collections/'+handle,keywords:[],original:{},itemIds:[]}];
    for(const g of groups){const byDestination=destinationProducts.get(g.url)||new Set();g.productIds=g.itemIds.length?[...new Set(g.itemIds.map(offerParts).filter(Boolean).map(x=>x.productId))]:[...new Set([...(g.productIds||[]),...byDestination])];}
    if(ids.size>24){warnings.push('The opening gallery covers 24 selected products. Select an exact remaining product ID to load its photos.');}
    const products=[];const pending=[...ids].slice(0,24);let index=0;
    async function worker(){while(index<pending.length){const id=pending[index++],offers=[...itemIds].map(offerParts).filter(o=>o&&o.productId===id);try{const p=await loadProductImages({productId:id,all:true,deadline});products.push({...p,identitySource:productSources.get(id),eligibleGroupRefs:groups.filter(g=>(g.productIds||[]).includes(id)).map(g=>g.ref),itemId:offers[0]&&offers[0].itemId||null,offerIds:offers.map(o=>o.itemId),variantId:offers[0]&&offers[0].variantId||null});}catch(e){products.push({id:'gid://shopify/Product/'+id,title:'Product '+id,images:[],complete:false,hasMore:true,nextCursor:null,error:str(e.message,250),identitySource:productSources.get(id),eligibleGroupRefs:groups.filter(g=>(g.productIds||[]).includes(id)).map(g=>g.ref),itemId:offers[0]&&offers[0].itemId||null,offerIds:offers.map(o=>o.itemId)});warnings.push('Product '+id+': '+str(e.message,200));}}}
    await Promise.all([worker(),worker(),worker()]);
    products.sort((a,b)=>pending.indexOf(productId(a.id))-pending.indexOf(productId(b.id)));
    if(!groups.length)throw new Error('No supported existing ad or reviewed opportunity context was found.');
    const context={campaignId:campaignId||null,approvalId,approvalPayloadHash,handle,budget:input.budget==null?null:Number(input.budget),dailyBudget:input.dailyBudget==null?null:Number(input.dailyBudget),feedLabel:input.feedLabel||null,searchThemes:Array.isArray(input.searchThemes)?input.searchThemes.slice(0,25):[],days:input.days==null?null:Number(input.days),countries:Array.isArray(input.countries)?input.countries.slice(0,20):[],startDate:input.startDate||null,endDate:input.endDate||null,itemIds:[...itemIds],groups,range,generationAllowed,requiresOfferSelection:!generationAllowed,source:'Current provider state and Shopify product media',warnings,galleryBrowse,partial:products.some(p=>!p.complete),checkedAt:now()};
    return {context,products,sourceVersion,snapshotHash,snapshot,approvalStatus:approval&&approval.status||null};
  }
  return {loadContext,loadProductImages};
}
module.exports={createAdDesignContext,productId,offerParts,sourceUrl,destination};
