(function(global){'use strict';
  const node=(tag,value,cls)=>{const n=document.createElement(tag);if(value!=null)n.textContent=String(value);if(cls)n.className=cls;return n;};
  function safeLink(raw){try{const u=new URL(raw);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}}
  function productId(value){const raw=String(value||'').trim();return /^gid:\/\/shopify\/Product\/\d+$/.test(raw)?raw:/^\d+$/.test(raw)?'gid://shopify/Product/'+raw:null;}
  function selectDossier(result,product){const id=productId(product.productId);return (result?.dossiers||[]).find(d=>productId(d.productId)===id&&id&&(!product.handle||d.handle===product.handle)&&['approved','draft'].includes(d.status))||null;}
  function sourceLinks(dossier,ids){return (ids||[]).map(id=>(dossier.sources||[]).find(s=>s.id===id)).filter(s=>s&&safeLink(s.url));}
  function selectProductIssues(result,product){const id=productId(product.productId),records=(result.productIssues||[]).filter(record=>id&&productId(record.productId)===id);return {productId:id,issues:records.flatMap(record=>Array.isArray(record.issues)?record.issues:[])};}
  function issueHolds(record){const open=(record?.issues||[]).filter(issue=>issue&&issue.status!=='resolved'),blocks=new Set(open.flatMap(issue=>Array.isArray(issue.blocks)?issue.blocks:[]));if(open.some(issue=>['identity','style','options','material','matching'].includes(issue.kind))){blocks.add('recommendation');blocks.add('cart');}if(open.some(issue=>['history','content'].includes(issue.kind)))blocks.add('meaning');return {recommendationHold:blocks.has('recommendation'),cartHold:blocks.has('cart'),meaningHold:blocks.has('meaning')};}
  function briefFor(dossier,title,issues=null,issueState='available'){const held=issueHolds(issues).recommendationHold||issueState!=='available'||dossier.status!=='approved';return [title,held?'CORRECTIVE RESEARCH ONLY · Keep these hypotheses out of automatic ad promotion until product issues and evidence are resolved.':'Product advertising test brief','Product: '+dossier.handle,'Research status: '+dossier.status,...(issues?.issues||[]).filter(issue=>issue.status!=='resolved').map(issue=>'Open product issue · '+issue.kind+': '+issue.detail),'Research recommendations (hypotheses):',...(dossier.recommendations||[]).map(r=>r.channel+': '+r.action+'\nMeasure: '+r.measure+'\nSources: '+sourceLinks(dossier,r.sourceIds).map(s=>s.url).join(', '))].join('\n\n');}
  function renderDemand(parent,entry){
    if(!entry?.evidence){parent.appendChild(node('p','No saved demand check for this exact product yet.','sub'));return;}
    const evidence=entry.evidence,metric=value=>value==null||!Number.isFinite(Number(value))?'unavailable':String(Number(value)),shopping=evidence.shopping||{},t=shopping.totals||{};
    parent.append(node('span',entry.state==='current'?'Current saved demand evidence':'Stale saved evidence · review before using','tag '+(entry.state==='current'?'approved':'draft')),node('p','Checked '+new Date(evidence.at).toLocaleString()+' · '+(evidence.range||'Reporting period unavailable'),'status'));
    if(evidence.payloadBounds?.state==='detail_sampled'){const labels={shoppingRows:'Shopping rows',searchTerms:'Search terms',pmaxTerms:'PMax terms',targetCriteria:'targeting criteria',adDestinationUrls:'destination URL examples',plannerSearchMatches:'Planner/Search matches',plannerCampaignMatches:'Planner/campaign matches'},omitted=Object.entries(evidence.payloadBounds.omittedDetails||{}).filter(([,n])=>Number.isFinite(Number(n))&&Number(n)>0).map(([name,n])=>Number(n)+' '+(labels[name]||'detail examples'));parent.appendChild(node('p','Saved detail samples omit '+omitted.join(', ')+'. Provider coverage and Shopping totals were checked before sampling.','status'));}
    parent.appendChild(node('p','Shopping evidence: exact product and catalogue variant offers. Reported conversions are unvalidated; their values do not establish revenue or profit.','sub'));
    if(evidence.sources?.shopping?.state==='unavailable')parent.appendChild(node('p','Shopping outcomes are unavailable: '+(evidence.sources.shopping.error||'The report could not be checked.'),'status'));
    else{parent.append(node('p','Impressions: '+metric(t.impressions)+' · Clicks: '+metric(t.clicks)+' · Reported conversions (unvalidated): '+metric(t.reportedConversions)),node('p','Reported spend: '+metric(t.cost)+(evidence.currency?' '+evidence.currency:' · account currency unavailable'),'sub'));if(evidence.sources?.shopping?.truncated)parent.appendChild(node('p','The Shopping report reached its row bound. Complete totals remain unavailable.','status'));}
    parent.appendChild(node('p','Search terms: '+(evidence.search?.terms?.length||0)+' reported rows in currently aligned product ad groups. Historical product attribution remains unverified.','sub'));
    if(evidence.sources?.searchTerms?.state==='unavailable')parent.appendChild(node('p','Search-term outcomes are unavailable.','status'));
    (evidence.search?.terms||[]).slice(0,6).forEach(term=>parent.appendChild(node('p',term.text+' · clicks '+metric(term.clicks)+' · reported conversions '+metric(term.reportedConversions),'sub')));
    parent.appendChild(node('p','PMax terms: campaign context only; these terms do not establish an individual product sale.','sub'));
    const planner=evidence.planner||{};parent.appendChild(node('h4','Keyword Planner market evidence'));
    if(planner.state!=='available')parent.appendChild(node('p','Planner '+(planner.state||'unavailable')+': '+(planner.reason||'A saved market check has not completed.'),'status'));
    else{const codes=(planner.market?.countries||[]).map(country=>country.code||country.id),pooled=planner.market?.pooled===true,hypothesis=planner.market?.languageBasis==='research_hypothesis_from_verified_own_storefront';parent.appendChild(node('p',(pooled?'Pooled observed country targets: ':'Observed country targets: ')+codes.join(', ')+'. Market estimates do not reproduce location exclusions.'+(pooled?' Volumes are pooled; country-specific demand or performance is not inferred.':''),'sub'));
      if(hypothesis){parent.appendChild(node('p',(planner.market.languageName||'The storefront language')+' is a research-language hypothesis supported by the own storefront HTML language tag. Actual campaign language targeting remains unknown.','status'));const source=safeLink(planner.market.languageSource?.finalUrl);if(source){const link=node('a','Storefront language source');link.href=source;link.target='_blank';link.rel='noopener';parent.appendChild(link);}}
      else parent.appendChild(node('p','Observed campaign language constant '+planner.market?.languageId+'.','sub'));
      (planner.keywords||[]).forEach(keyword=>parent.appendChild(node('p',keyword.text+' · '+(pooled?'pooled ':'')+'average monthly searches '+metric(keyword.averageMonthlySearches)+' · competition '+(keyword.competition||'unavailable'),'sub')));}
    parent.appendChild(node('p','Unreported terms or missing Planner values do not establish zero demand.','status'));
  }
  function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(Boolean))rows.push(row);if(!rows.length)return [];const headers=rows.shift().map(h=>h.replace(/^\uFEFF/,'').trim());return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])));}
  async function mount(root,opts={}){
    const workspace=node('main',null,'workspace');root.replaceChildren(workspace);let data=null,filter='',selected=null,detailRequest=0;
    const header=node('header'),intro=node('div');intro.append(node('span','Shared product knowledge','eyebrow'),node('h1','Research that reaches the buyer'),node('p','Product evidence, competitor offers and recommendations for ads, buyer searches and the gift concierge.','sub'));
    const controls=node('div',null,'controls'),refresh=node('button','Refresh progress','btn'),preview=node('a','Open gift concierge','btn');refresh.type='button';preview.href=opts.conciergeUrl||'/concierge-sandbox.html';preview.target='_blank';preview.rel='noopener';controls.append(refresh,preview);header.append(intro,controls);workspace.appendChild(header);
    let key='';if(!opts.request){try{key=sessionStorage.getItem('brites-growth-key')||'';}catch(e){}}
    async function request(op,payload){if(opts.request)return opts.request(op,payload);const r=await fetch('/api/growth/'+op,{method:payload?'POST':'GET',headers:{'Content-Type':'application/json','X-Growth-Key':key},...(payload?{body:JSON.stringify(payload)}:{})});const v=await r.json();if(!r.ok)throw Object.assign(Error(v.error||'Request failed.'),{status:r.status});return v;}
    const auth=node('form',null,'box auth'),pass=node('input');pass.type='password';pass.autocomplete='off';pass.placeholder='Operator access key';pass.setAttribute('aria-label','Operator access key');const sign=node('button','Open workspace','btn primary');sign.type='submit';auth.append(node('h2','Private research workspace'),node('p','Use the sandbox operator key to see saved research and sales evidence.','sub'),pass,sign);auth.hidden=!!opts.request;workspace.appendChild(auth);
    const status=node('div','','status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');workspace.appendChild(status);const content=node('div');workspace.appendChild(content);
    const detail=node('article',null,'box dossier'),rows=node('div',null,'rows');detail.setAttribute('aria-label','Selected product research');
    function links(parent,dossier,ids){const sources=sourceLinks(dossier,ids);if(!sources.length)return;const p=node('p',null,'status');sources.forEach((s,i)=>{if(i)p.append(' · ');const a=node('a',s.title||s.id);a.href=safeLink(s.url);a.target='_blank';a.rel='noopener noreferrer';p.appendChild(a);});parent.appendChild(p);}
    function renderRows(){rows.replaceChildren();(data?.queue||[]).filter(r=>r.rank<=100&&(!filter||[r.title,r.handle,r.sku,r.theme].join(' ').toLowerCase().includes(filter))).forEach(r=>{const b=node('button',null,'row'+(r.id===selected?' active':''));b.type='button';b.setAttribute('aria-pressed',String(r.id===selected));b.append(node('b',r.rank+'. '+r.title),node('small',r.handle||'Live product match pending'),node('span',String(r.status||'pending').replace(/_/g,' '),'tag '+(r.status||'pending')));b.onclick=()=>show(r);rows.appendChild(b);});if(!rows.childElementCount)rows.appendChild(node('p',filter?'No products match this search.':'No ranked products are loaded yet.','empty'));}
    async function show(r){
      selected=r.id;const seq=++detailRequest;renderRows();detail.replaceChildren(node('span',r.theme||'Product research','eyebrow'),node('h2',r.title));
      if(!productId(r.productId)){detail.appendChild(node('p','An exact live product and variant match is still required. Similar products remain candidates.','empty'));return;}
      const pending=node('p','Reading saved product research…','status');detail.appendChild(pending);
      try{
        const result=await request('research?ids='+encodeURIComponent(productId(r.productId)));if(seq!==detailRequest||selected!==r.id)return;pending.remove();const dossier=selectDossier(result,r),issues=selectProductIssues(result,r),holds=issueHolds(issues),issueState=result.productIssueState||(Array.isArray(result.productIssues)?'available':'unavailable'),held=holds.recommendationHold||issueState!=='available';
        const openIssues=issues.issues.filter(issue=>issue.status!=='resolved');
        if(openIssues.length){detail.append(node('h3','Known product issues'),node('p',holds.recommendationHold?'Ad recommendation and cart hold · correction research remains available.':holds.meaningHold?'Meaning/history hold · review the sourced content before using it.':'Product review required.','error'));openIssues.forEach(issue=>{const box=node('div',null,'recommendation');box.append(node('b',issue.kind+' · open'),node('p',issue.detail));(issue.evidence||[]).forEach(e=>{if(e.text)box.appendChild(node('p',e.text,'sub'));const url=safeLink(e.url);if(url){const a=node('a','Reviewed issue source');a.href=url;a.target='_blank';a.rel='noopener noreferrer';box.appendChild(a);}});detail.appendChild(box);});}
        if(issueState!=='available')detail.appendChild(node('p','Product issue checks are unavailable. Research stays visible; its notes remain held out of automatic ad promotion.','status'));
        if(!dossier){detail.appendChild(node('p','Matched to the live catalogue. Approved research for this exact product is not available yet; deep competitor and buyer research is queued.','empty'));return;}
        detail.append(node('span',dossier.status==='approved'?'Approved research':'Partial research · needs more evidence','tag '+dossier.status),node('p','Last saved '+new Date(dossier.savedAt).toLocaleString(),'status'));
        if(dossier.status!=='approved')detail.appendChild(node('p','This dossier is still being completed. Its recommendations are held out of automated ad-design evidence until validation approves it.','status'));
        detail.appendChild(node('h3','Product facts with cited sources'));
        if(!(dossier.facts||[]).length)detail.appendChild(node('p','Product facts have not been saved in this dossier yet.','sub'));
        (dossier.facts||[]).forEach(f=>{detail.append(node('p',f.claim),node('blockquote',f.quote));links(detail,dossier,f.sourceIds);});
        detail.appendChild(node('h3','Buyer intent and search relevance'));
        if(!(dossier.buyerIntents||[]).length)detail.appendChild(node('p','Buyer-intent research is still pending.','sub'));
        (dossier.buyerIntents||[]).forEach(intent=>{const b=node('div',null,'recommendation');if(typeof intent==='string')b.appendChild(node('p',intent));else{const title=intent.intent||intent.query||intent.label||intent.theme||'Buyer hypothesis';b.append(node('b',title),node('p',intent.approach||intent.rationale||intent.observation||intent.description||''));if(intent.keywords?.length)b.appendChild(node('p','Search phrases: '+intent.keywords.join(', ')));links(b,dossier,intent.sourceIds);}detail.appendChild(b);});
        detail.appendChild(node('h3','Competitor offers'));
        if(!(dossier.competitors||[]).length)detail.appendChild(node('p','Inspected competitor offers are still pending.','sub'));
        (dossier.competitors||[]).forEach(c=>{const b=node('div',null,'recommendation'),url=safeLink(c.url);if(url){const a=node('a',c.name);a.href=url;a.target='_blank';a.rel='noopener noreferrer';b.appendChild(a);}else b.appendChild(node('b',c.name));let price='Price not verified';if(c.price!=null&&Number.isFinite(Number(c.price))&&/^[A-Z]{3}$/.test(c.currency||''))price=new Intl.NumberFormat('en',{style:'currency',currency:c.currency}).format(c.price)+' '+c.currency;b.append(node('p',price),node('p','Ad spending: '+(c.spend?.status||'unknown'),'status'),node('p',c.observation||''));if(c.spend?.status==='estimate')b.appendChild(node('p','Estimate method: '+c.spend.method+' · Assumptions: '+(c.spend.assumptions||[]).join('; '),'status'));links(b,dossier,c.sourceIds);detail.appendChild(b);});
        detail.appendChild(node('h3','Recommendations to test'));
        if(!(dossier.recommendations||[]).length)detail.appendChild(node('p','Actionable test recommendations are still pending.','sub'));
        (dossier.recommendations||[]).forEach(rec=>{const b=node('div',null,'recommendation');b.append(node('b',rec.channel+' · hypothesis'),node('p',rec.action),node('p','Measure: '+rec.measure,'sub'));links(b,dossier,rec.sourceIds);detail.appendChild(b);});
        if((dossier.recommendations||[]).length&&global.navigator?.clipboard?.writeText){const corrective=held||dossier.status!=='approved',copy=node('button',corrective?'Copy corrective research notes':'Copy product test brief','btn');copy.type='button';copy.onclick=async()=>{try{await global.navigator.clipboard.writeText(briefFor(dossier,r.title,issues,issueState));copy.textContent=corrective?'Corrective notes copied':'Test brief copied';}catch{copy.textContent='Clipboard unavailable';}};detail.appendChild(copy);}
        detail.appendChild(node('h3','Meanings and stories'));
        if(!(dossier.meanings||[]).length)detail.appendChild(node('p','Sourced meanings or history are not available for this piece yet.','sub'));
        (dossier.meanings||[]).forEach(m=>{detail.append(node('p',m.text),node('p',m.context+' · interpretation','status'));links(detail,dossier,m.sourceIds);});
        detail.appendChild(node('h3','Inspected sources'));
        (dossier.sources||[]).forEach(s=>{const p=node('p'),url=safeLink(s.url);if(url){const a=node('a',s.title);a.href=url;a.target='_blank';a.rel='noopener noreferrer';p.appendChild(a);}else p.appendChild(node('span',s.title));p.appendChild(node('small',' · '+new Date(s.checkedAt).toLocaleDateString()));detail.appendChild(p);});
        (dossier.validation?.warnings||[]).forEach(w=>detail.appendChild(node('p',w,'status')));
        const demandBox=node('section',null,'recommendation');demandBox.append(node('h3','Saved demand and advertising outcomes'),node('p','Reading saved demand evidence…','status'));detail.appendChild(demandBox);
        try{const saved=await request('demand?ids='+encodeURIComponent(productId(r.productId)));if(seq!==detailRequest||selected!==r.id)return;const entry=(saved.products||[]).find(product=>productId(product.productId)===productId(r.productId));demandBox.replaceChildren(node('h3','Saved demand and advertising outcomes'));renderDemand(demandBox,entry);}catch(error){if(seq===detailRequest&&selected===r.id){demandBox.replaceChildren(node('h3','Saved demand and advertising outcomes'),node('p','Saved demand evidence is unavailable: '+error.message,'status'));}}
      }catch(e){if(seq===detailRequest&&selected===r.id){pending.remove();detail.appendChild(node('p',e.message,'error'));}}
    }
    function render(){
      content.replaceChildren();const metrics=node('div',null,'metrics');[['Ranked entries',data.counts?.ranked],['Live product matches',data.counts?.matched],['Completed ranked entries',data.counts?.complete],['Approved dossiers',data.counts?.approvedDossiers]].forEach(([label,count])=>{const card=node('div',null,'metric');card.append(node('strong',String(count??0)),node('span',label));metrics.appendChild(card);});content.appendChild(metrics);
      const layout=node('div',null,'layout'),queue=node('section',null,'box queue'),head=node('div',null,'queue-head'),search=node('input');search.placeholder='Find a product, theme or SKU';search.setAttribute('aria-label','Filter research queue');search.value=filter;search.oninput=()=>{filter=search.value.toLowerCase();renderRows();};head.append(node('h2','Product queue'),search);queue.append(head,rows);layout.append(queue,detail);content.appendChild(layout);
      const selectedRow=(data.queue||[]).find(r=>r.id===selected);if(selectedRow)show(selectedRow);else{selected=null;++detailRequest;detail.replaceChildren(node('h2','Choose a product'),node('p','See the evidence behind its advertising, search and concierge recommendations.','empty'));renderRows();}
      const blockers=node('section',null,'box blockers');blockers.appendChild(node('h2','Work requiring access'));if(!(data.blockers||[]).length)blockers.appendChild(node('p','No recorded access blockers.','sub'));(data.blockers||[]).forEach(b=>{const a=node('article');a.append(node('b',b.task),node('p',b.detail),node('span',b.status,'tag'));blockers.appendChild(a);});content.appendChild(blockers);
      if(!opts.request){const tools=node('div',null,'controls'),importFile=node('input');importFile.type='file';importFile.accept='.csv';importFile.setAttribute('aria-label','Import ranked products CSV');importFile.onchange=async()=>{if(!importFile.files?.[0])return;try{const csv=parseCsv(await importFile.files[0].text());await request('import',{rows:csv.slice(0,100).map(r=>({rank:Number(r.Rank),title:r['Item Name']||r.Title,sku:r.SKU,handle:r.Handle,orders:Number(r.Orders||r['Number of Orders']),theme:r.Theme}))});await load();}catch(e){status.textContent=e.message;}};tools.append(node('span','Import top products:','status'),importFile);content.appendChild(tools);}
    }
    async function load(){refresh.disabled=true;status.textContent='Reading saved progress…';try{data=await request('status');auth.hidden=true;render();status.textContent='Updated '+new Date(data.at).toLocaleString()+'. '+(data.control?.catalogueComplete?'Full catalogue mirror loaded.':'Live catalogue mirror is progressing.');}catch(e){if(e.status===401){auth.hidden=!!opts.request;content.replaceChildren();++detailRequest;}status.textContent=e.message;}finally{refresh.disabled=false;}}
    auth.onsubmit=async e=>{e.preventDefault();key=pass.value.trim();pass.value='';try{sessionStorage.setItem('brites-growth-key',key);}catch(x){}await load();};refresh.onclick=load;if(opts.request||key)await load();else{status.textContent='Sign in to see private progress.';refresh.disabled=true;}
    return {refresh:load};
  }
  global.BritesGrowth={mount,parseCsv,productId,selectDossier,selectProductIssues,issueHolds,briefFor,safeLink};if(document.querySelector('#growth-root'))mount(document.querySelector('#growth-root'));
})(window);
