(function(root){
  'use strict';
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const key=g=>g.campaignId+'|'+g.ref;
  function photoHtml(url,label='',width=320){
    let u;try{u=new URL(url);if(u.protocol!=='https:')return '<span class="bg-photo is-empty" aria-hidden="true"></span>';}catch{return '<span class="bg-photo is-empty" aria-hidden="true"></span>';}
    const original=u.href,cors=['cdn.shopify.com','storage.googleapis.com','firebasestorage.googleapis.com'].includes(u.hostname)||u.hostname.endsWith('.storage.googleapis.com');
    if(u.hostname==='cdn.shopify.com'){u.searchParams.set('width',String(width));u.searchParams.delete('height');u.searchParams.delete('crop');}
    return '<span class="bg-photo"><img'+(cors?' crossorigin="anonymous"':'')+' src="'+esc(u.href)+'" data-bg-original="'+esc(original)+'" alt="'+esc(label)+'" loading="lazy"><span hidden>Image unavailable</span></span>';
  }
  function wirePhotos(){host.querySelectorAll('[data-bg-original]').forEach(img=>{img.onerror=()=>{if(img.src!==img.dataset.bgOriginal){img.src=img.dataset.bgOriginal;return;}img.hidden=true;img.nextElementSibling.hidden=false;};img.onload=()=>{img.hidden=false;img.nextElementSibling.hidden=true;};});}
  function approvalRefs(a){const p=a.payload||{},out=[p.meta?.sourceGroupRef,...(p.meta?.groupRefs||[]),p.adDesign?.settings?.groupRef,p.adDesign?.groupRef];for(const x of p.versionChange?.changes||[])out.push(x.target);for(const g of p.meta?.assetGroups||[])out.push(g.ref);for(const op of p.mutateOperations||[]){for(const v of Object.values(op)){const r=v.create||v.update||{};out.push(r.assetGroup,r.adGroup);const ref=v.remove||r.resourceName;if(typeof ref==='string'){let m=ref.match(/^(customers\/\d+\/)(assetGroupAssets|adGroupAds|adGroupCriteria|adGroupAssets)\/(\d+)/);if(m)out.push(m[1]+(m[2]==='assetGroupAssets'?'assetGroups':'adGroups')+'/'+m[3]);}}}return [...new Set(out.filter(Boolean))];}
  function matchesApproval(a,g){const refs=approvalRefs(a);return refs.includes(g.ref)||(g.creativeRefs||[]).some(r=>refs.includes(r));}
  const state={index:null,detail:null,selected:null,query:'',campaign:'',tab:'overview',loading:false,error:'',seq:0,start:'',end:'',closed:new Set(),expanded:new Set(),listScroll:0,designing:null,activating:false};
  let options,host,history=[],activePlace=null,replaying=false;
  const number=v=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
  // A currency's own symbol (CA$ for Canadian dollars), so account-currency figures are never read as the Overview's USD.
  function symbol(c){try{return new Intl.NumberFormat('en-US',{style:'currency',currency:c}).formatToParts(0).find(p=>p.type==='currency').value;}catch{return c?c+' ':'';}}
  const cash=(v,c)=>v==null||!Number.isFinite(Number(v))?'—':(Number(v)<0?'−':'')+symbol(c)+Math.abs(Number(v)).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
  const chip=(label,kind='')=>'<span class="bg-chip '+kind+'">'+esc(label)+'</span>';
  const button=(action,label,primary=false,disabled=false)=>'<button type="button" class="btn '+(primary?'gold':'ghost')+' sm" data-bg-action="'+action+'"'+(disabled?' disabled':'')+'>'+label+'</button>';
  const spin='<span class="bg-spin" aria-hidden="true"></span>';
  const MON=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],day=s=>{const p=String(s||'').split('-');return p.length===3?MON[+p[1]-1]+' '+(+p[2]):'';};
  const rangeText=(a,b)=>a&&b?day(a)+(a.slice(0,4)!==b.slice(0,4)?', '+a.slice(0,4):'')+' – '+day(b)+', '+b.slice(0,4):'';
  const zoneText=z=>z?String(z).split('/').pop().replace(/_/g,' ')+' time':'';
  // Figures match the Overview's campaign rows when Google's report converts them: the same currency (daily rates)
  // and the Overview's conversion basis. Otherwise they stay in the account currency by ad-click date, and the scope says so.
  const basisNow=()=>options&&typeof options.basis==='function'&&options.basis()==='click'?'click':'conversion';
  function fig(row,listing){if(!row||!row.metrics)return null;const r=row.report;if(!r)return row.metrics;const x=listing||basisNow()==='click'?r.click:r.conversion;return x||{...r.click,conversions:null,value:null};}
  const moneyOf=(groups,fallback)=>(groups.find(g=>g&&g.report)||{}).report?.currency||fallback||'';
  const basisOf=groups=>'Conversions by '+(groups.some(g=>g&&g.report)&&basisNow()==='conversion'?'conversion date':'ad-click date');
  const scopeText=(r,groups)=>[rangeText(r.range.start,r.range.end),zoneText(r.timeZone),moneyOf(groups,r.currency),basisOf(groups)].filter(Boolean).join(' · ');
  // Reload sits beside the time the figures were read, so it is not mistaken for the console's live-pull Refresh.
  const stamp=r=>r&&r.checkedAt?'Updated '+new Date(r.checkedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'';
  const reloadLink='<span aria-hidden="true">·</span><button type="button" class="bg-link" data-bg-action="refresh">Reload</button>';
  const missingNote='<p class="bg-alert" role="status">Google did not return some figures for this range; they show as —. Reload to try again.</p>';
  const gaps=groups=>groups.some(g=>{const f=fig(g);return !f||f.conversions==null;});
  const kind=g=>g.channel==='pmax'?'Asset group':g.channel==='display'?'Display ad group':'Ad group';
  const TABS={overview:'Overview',targeting:'Keywords',messaging:'Messaging',designs:'Designs & research',changes:'Approvals'};
  const tabName=(g,t)=>t==='targeting'&&g&&g.channel==='pmax'?'Search themes':TABS[t]||'Overview';
  // One status vocabulary with the rest of the console (Overview uses the same labels and badge colours).
  const PRIMARY={ELIGIBLE:['Serving','b-on'],LEARNING:['Learning','b-learn'],LIMITED:['Limited','b-warn'],PAUSED:['Paused','b-pause'],PENDING:['Scheduled','b-learn'],ENDED:['Ended','b-pause'],MISCONFIGURED:['Misconfigured','b-bad'],NOT_ELIGIBLE:['Not eligible','b-bad'],REMOVED:['Removed','b-pause']};
  const badge=(s,title)=>s?'<span class="badge2 bg-badge '+s[1]+'"'+(title||s[2]?' title="'+esc(title||s[2])+'"':'')+'>'+esc(s[0])+'</span>':'';
  // Google's reasons for a group that is not serving, in plain words: "Campaign ended", never NOT_ELIGIBLE.
  const REASON={CAMPAIGN_ENDED:'Campaign ended',CAMPAIGN_PAUSED:'Campaign paused',CAMPAIGN_PENDING:'Campaign not started',CAMPAIGN_REMOVED:'Campaign removed',CAMPAIGN_DRAFT:'Campaign draft',ASSET_GROUP_PAUSED:'Paused',AD_GROUP_PAUSED:'Paused',ASSET_GROUP_REMOVED:'Removed',AD_GROUP_REMOVED:'Removed',ASSET_GROUP_DISAPPROVED:'Disapproved',ASSET_GROUP_UNDER_REVIEW:'Under review',ASSET_GROUP_LIMITED:'Limited',AD_GROUP_INCOMPLETE:'Incomplete',NO_KEYWORDS:'No keywords',KEYWORDS_PAUSED:'Keywords paused',NO_AD_GROUP_ADS:'No ads',AD_GROUP_ADS_PAUSED:'Ads paused',HAS_ADS_DISAPPROVED:'Ads disapproved',HAS_ADS_LIMITED_BY_POLICY:'Ads limited by policy',MOST_ADS_UNDER_REVIEW:'Ads under review',AD_GROUP_PAUSED_DUE_TO_LOW_ACTIVITY:'Paused for low activity'};
  const tone=r=>/DISAPPROVED|INCOMPLETE|^NO_/.test(r)?'b-bad':/LIMITED/.test(r)?'b-warn':/PENDING|DRAFT|REVIEW/.test(r)?'b-learn':'b-pause';
  function campaignState(id,status){if(status==='REMOVED')return ['Removed','b-pause'];if(status!=='ENABLED')return ['Paused','b-pause'];const c=((options&&options.dashboard&&options.dashboard())?.lastMetrics||[]).find(x=>String(x.id)===String(id));if(c&&PRIMARY[c.primaryStatus])return PRIMARY[c.primaryStatus];
    // Without the Overview's campaign status, the groups' reasons still show an ended or unstarted campaign.
    const why=(state.index?.groups||[]).filter(g=>g.campaignId===String(id)).flatMap(g=>g.primaryStatusReasons||[]);return why.includes('CAMPAIGN_ENDED')?PRIMARY.ENDED:why.includes('CAMPAIGN_PENDING')?PRIMARY.PENDING:['Enabled','b-learn'];}
  const serving=s=>['Serving','Learning','Limited','Enabled'].includes(s[0]);
  // A group under a paused or ended campaign inherits that state; repeating it on every row is noise.
  function groupState(g,inTree){const c=campaignState(g.campaignId,g.campaignStatus);if(g.status==='PAUSED')return ['Paused','b-pause'];if(g.status==='REMOVED'||g.historicalOnly)return inTree&&c[0]==='Removed'?null:['Removed','b-pause'];if(!serving(c))return inTree?null:['Campaign '+c[0].toLowerCase(),c[1]];const why=g.primaryStatus==='ELIGIBLE'?[]:(g.primaryStatusReasons||[]).filter(r=>REASON[r]);return why.length?[REASON[why[0]],tone(why[0]),why.length>1?why.map(r=>REASON[r]).join(' · '):'']:PRIMARY[g.primaryStatus]||['Enabled','b-learn'];}
  // Phone columns are narrow: amounts from 100 drop their cents and six-figure values shorten (CA$176.6K). Wider layouts show every digit.
  function compact(v,c,money){const n=Math.abs(Number(v)),sign=Number(v)<0?'−':'';if(n>=100000)return sign+(money?symbol(c):'')+new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n);return money&&n>=100?sign+symbol(c)+Math.round(n).toLocaleString('en-US'):'';}
  const COLS=[['spend','Spend',true],['clicks','Clicks'],['conversions','Conv.'],['value','Conv. value',true]];
  function cells(m,currency,pending){return '<span class="bg-cells">'+COLS.map(([k,label,money])=>{if(pending)return '<span class="bg-cell is-pending" data-label="'+esc(label)+'"><span class="vh">'+esc(label)+' loading</span><i aria-hidden="true"></i></span>';const v=m?m[k]:null,na=v==null,zero=!na&&Number(v)===0,text=money?cash(v,currency):number(v),brief=na?'':compact(v,currency,money);return '<span class="bg-cell'+(na?' is-na':zero?' is-zero':'')+'" data-label="'+esc(label)+'"'+(na?' title="Not reported for this range"':'')+'><span class="vh">'+esc(label)+' </span>'+(brief?'<span class="bg-full">'+text+'</span><span class="bg-brief">'+brief+'</span>':text)+'</span>';}).join('')+'</span>';}
  const zeroes=()=>({impressions:0,clicks:0,spend:0,conversions:0,value:0});
  const sum=rows=>rows.reduce((t,m)=>{for(const k in t)t[k]=t[k]==null||m&&m[k]===null?null:t[k]+Number(m&&m[k]||0);return t;},zeroes());
  const total=groups=>groups.some(g=>!fig(g))?null:sum(groups.map(g=>fig(g)));
  const spendOf=x=>(x.report?fig(x):x.metrics)?.spend||0,bySpend=(a,b)=>spendOf(b)-spendOf(a);
  // Listing figures are the exact-offer rows of the group report. After a successful report a missing row is a true zero.
  function offerMetrics(g,itemIds){if(!Array.isArray(g&&g.listingMetrics))return null;const ids=new Set((itemIds||[]).map(x=>String(x).toLowerCase())),rows=g.listingMetrics.filter(x=>ids.has(String(x.itemId).toLowerCase()));return g.report&&rows.some(x=>!x.report)?null:sum(rows.map(x=>fig(x,true)));}
  const offerProduct=id=>(String(id).match(/^shopify_[^_]+_(\d+)_\d+$/i)||[])[1]||null;
  // The exact offers this group serves for one product (all of the product's offers when the filter is broader).
  // Several offers of one listing are its variants, or one variant sold in several markets.
  function offerText(ids){const n=(ids||[]).length;if(n<2)return '';const markets=new Set(ids.map(x=>String(x).split('_')[1]?.toLowerCase()));return n+(markets.size>1?' offers in '+markets.size+' markets':' variants');}
  function groupOffers(group,p){const pid=String(p.id||'').split('/').pop(),mine=(group.mapping?.itemIds||[]).filter(x=>offerProduct(x)===pid);return mine.length?mine:p.offerIds||[];}
  function listings(g){const rows=new Map();for(const o of g.listings||(g.mapping?.itemIds||[]).map(itemId=>({itemId,productId:offerProduct(itemId)}))){const id=o.productId||o.itemId,r=rows.get(id)||{id,productId:o.productId,title:null,imageUrl:null,itemIds:[],notes:[]};r.itemIds.push(o.itemId);r.title=r.title||o.title||null;r.imageUrl=r.imageUrl||o.imageUrl||null;const note=o.inFeed===false?'Not in Merchant feed':o.status==='NOT_ELIGIBLE'?'Not eligible':o.availability==='OUT_OF_STOCK'?'Out of stock':o.status==='ELIGIBLE_LIMITED'?'Limited':null;if(note&&!r.notes.includes(note))r.notes.push(note);rows.set(id,r);}return [...rows.values()].map(r=>({...r,metrics:offerMetrics(g,r.itemIds)})).sort((a,b)=>bySpend(a,b)||String(a.title||'').localeCompare(String(b.title||'')));}
  // Some feed titles arrive with a broken dash (" â " for " – "); show the intended character.
  const tidy=t=>String(t||'').replace(/\sâ(?:€[“”])?\s/g,' – ').replace(/â€™/g,'’').trim();
  // Merchant titles carry variant and keyword tails ("Name, Gift, … / 16 inch / None"); the full title stays in the tooltip.
  function shortTitle(t){t=tidy(t);const head=t.split(/,\s|\s[/|–—-]\s/)[0].trim();return head.length>=12&&head.length<t.length?head:t;}
  const listingName=r=>r.title?shortTitle(r.title):'Product '+(r.productId||r.id);
  function pageLabel(url){let p='';try{p=new URL(url).pathname.replace(/\/+$/,'');}catch{return 'Landing page';}const c=p.match(/^\/collections\/([^/]+)$/),s=p.match(/^\/pages\/([^/]+)$/),item=p.match(/\/products\/([^/]+)$/);return c?'Collection · '+c[1].replace(/-/g,' '):s?'Page · '+s[1].replace(/-/g,' '):item?'Product page · '+item[1].replace(/-/g,' '):!p?'Home page':'Page · '+p;}
  const scopeOf=g=>{const m=g.mapping||{};return m.status==='unavailable'?'unknown':m.scope||((m.itemIds||[]).length||(m.handles||[]).length?'listings':(m.urls||[]).length?'page':'none');};
  function advertises(g){const m=g.mapping||{},scope=scopeOf(g);if(m.status==='historical'&&scope!=='listings')return '';if(scope==='unknown')return 'Listing link unavailable';if(scope==='page')return pageLabel(m.landing||(m.urls||[])[0]);if(scope==='feed')return 'Feed filter, not exact listings';if(scope!=='listings')return 'No ad destination';const n=g.channel==='pmax'?(m.productIds||[]).length:(m.handles||[]).length;if(n!==1)return n+' listings';const one=g.channel==='pmax'?listings(g)[0]:null;return one&&one.title?listingName(one):g.channel==='pmax'?'1 listing':String(m.handles[0]).replace(/-/g,' ');}
  function compactName(g){return advertises(g);}
  function metricCards(g,currency){const m=fig(g);return '<div class="bg-metrics">'+[['Spend',cash(m?.spend,currency)],['Clicks',number(m?.clicks)],['Conversions',number(m?.conversions)],['Conv. value',cash(m?.value,currency)],['Impressions',number(m?.impressions)],['CTR',m?(m.impressions?number(m.clicks/m.impressions*100)+'%':'—'):'—']].map(([l,v])=>'<div'+(v==='—'?' class="is-na"':'')+'><b>'+v+'</b><span>'+l+'</span></div>').join('')+'</div>';}
  function selected(){return state.index?.groups.find(g=>key(g)===state.selected)||null;}
  function selection(){const g=selected();return g?{...g,creativeRefs:(state.detail?.copy||[]).map(a=>a.ref)}:null;}
  function place(view){return {view:view||options.currentView(),selected:state.selected,campaign:state.campaign,query:state.query,tab:state.tab,detail:state.detail};}
  function remember(view){const p=place(view),id=x=>x&&[x.view,x.selected,x.campaign,x.tab].join('|');if(!replaying&&activePlace&&id(activePlace)!==id(p)){history.push(activePlace);if(history.length>40)history.shift();}activePlace=p;}
  function back(){const p=history.pop();if(!p)return;const moved=p.selected!==state.selected;replaying=true;state.selected=p.selected;state.campaign=p.campaign;state.query=p.query;state.tab=p.tab;state.detail=p.detail;++state.seq;state.loading=false;activePlace=p;persist();if(moved)options.changed();options.go(p.view);render();chrome(p.view);replaying=false;if(!p.selected)restoreList();else if(!state.detail&&selected())choose(selected(),p.tab);}
  const VIEWS={groups:'Products & groups',command:'Overview',sales:'Sales',approvals:'Approvals',bench:'Opportunities',controls:'Controls'};
  // Back names where it goes, so it is never a guess.
  function backLabel(p){if(!p)return '';if(p.view!=='groups')return VIEWS[p.view]||'Back';const g=state.index?.groups.find(x=>key(x)===p.selected);if(g)return activePlace&&activePlace.view==='groups'&&activePlace.selected===p.selected?tabName(g,p.tab):g.name;if(p.campaign)return state.index?.groups.find(x=>x.campaignId===p.campaign)?.campaignName||'Products & groups';return 'Products & groups';}
  function chrome(view){if(!document.getElementById('groupContext'))return;remember(view);drawContext(view);}
  // Where you are and the way back. In Products & groups it is the start of the toolbar row, so it costs no height;
  // elsewhere (Approvals scoped to a group, Back from another tab) it is the thin bar under the top bar.
  function drawContext(view){
    const bar=document.getElementById('groupContext');if(!bar)return;const g=selected(),v=view||options.currentView(),prev=history[history.length-1],box=v==='groups'?host&&host.querySelector('[data-bg-context-slot]'):bar;
    if(v==='groups'){bar.hidden=true;bar.innerHTML='';}if(!box)return;
    let trail='';
    // The campaign filter already names a chosen campaign; the trail is for an open group.
    if(v==='groups'&&g)trail='<button type="button" data-bg-home>Products &amp; groups</button><span aria-hidden="true">›</span><button type="button" data-bg-campaign-back>'+esc(g.campaignName)+'</button><span aria-hidden="true">›</span><span aria-current="page">'+esc(g.name)+'</span>';
    else if(v==='approvals'&&g)trail='<span>Showing approvals for</span><button type="button" data-bg-context>'+esc(g.name)+'</button><span aria-hidden="true">·</span><button type="button" data-bg-clear-scope>Show all</button>';
    // Back is left out when a link or tab beside it already goes to the same place, or when only the list's filter changed.
    const same=!!prev&&(v==='groups'&&prev.view==='groups'&&(!prev.selected&&(!g||!prev.campaign||prev.campaign===g.campaignId)||!!g&&prev.selected===state.selected)||v==='approvals'&&!!g&&prev.view==='groups'&&prev.selected===state.selected),showBack=!!prev&&!same;
    box.hidden=!trail&&!showBack;
    box.innerHTML=(showBack?'<button type="button" class="bg-back" data-bg-history-back>‹ '+esc(backLabel(prev))+'</button>':'')+(trail?'<nav class="bg-breadcrumbs" aria-label="'+(v==='groups'?'Breadcrumb':'Approval scope')+'">'+trail+'</nav>':'');
    const on=(sel,fn)=>{const el=box.querySelector(sel);if(el)el.onclick=fn;};
    on('[data-bg-history-back]',back);
    on('[data-bg-home]',()=>{state.selected=null;state.detail=null;state.campaign='';++state.seq;state.loading=false;persist();options.changed();options.go('groups');render();chrome('groups');restoreList();});
    on('[data-bg-campaign-back]',()=>{state.selected=null;state.detail=null;state.campaign=g.campaignId;state.closed.delete(g.campaignId);++state.seq;state.loading=false;persist();options.changed();options.go('groups');render();chrome('groups');});
    on('[data-bg-context]',()=>{options.go('groups');chrome('groups');});
    on('[data-bg-clear-scope]',()=>{state.selected=null;state.detail=null;persist();options.changed();chrome();});
  }
  function restoreList(){const y=state.listScroll;if(y&&typeof root.scrollTo==='function')(root.requestAnimationFrame||setTimeout)(()=>root.scrollTo(0,y));}
  function persist(){try{sessionStorage.setItem('brites.group',state.selected||'');}catch{}}
  function load(force=false){const run=fetchIndex(force);state.inflight=run;return run;}
  async function fetchIndex(force){const seq=++state.seq,previous=state.index&&state.index.range;state.loading=true;state.error='';state.detail=null;render();try{const r=await options.api('adGroups',{start:state.start||undefined,end:state.end||undefined,force,reportingTree:true,listings:true});if(seq!==state.seq)return;if(!r||r.error||r.ok===false)throw Error(r?.error||'Groups could not be loaded.');state.index=r;state.start=r.range.start;state.end=r.range.end;if(state.selected&&!r.groups.some(g=>key(g)===state.selected&&!g.historicalOnly)){state.selected=null;state.detail=null;persist();options.changed();}if(selected())await loadDetail(selected(),seq);}catch(e){if(seq===state.seq){state.error=e.message;
    // Figures on screen must match the dates on screen: keep the last loaded range when a new one fails.
    if(previous&&(state.start!==previous.start||state.end!==previous.end)){state.error='Results for '+rangeText(state.start,state.end)+' could not be loaded: '+e.message+' Still showing '+rangeText(previous.start,previous.end)+'.';state.start=previous.start;state.end=previous.end;}}}finally{if(seq===state.seq){state.loading=false;render();chrome();}}}
  async function loadDetail(g,seq){state.detail=null;const r=await options.api('adGroupDetail',{campaignId:g.campaignId,groupRef:g.ref,start:state.start,end:state.end,reportingTree:true});if(seq!==state.seq||state.selected!==key(g))return;if(!r||r.error||r.ok===false)throw Error(r?.error||'The group could not be opened.');state.detail=r;options.changed();}
  async function choose(g,tab){if(!state.selected&&typeof root.scrollY==='number')state.listScroll=root.scrollY;state.selected=key(g);state.tab=tab||'overview';state.detail=null;state.loading=true;state.error='';persist();options.changed();const seq=++state.seq;render();chrome();try{await loadDetail(g,seq);}catch(e){if(seq===state.seq)state.error=e.message;}finally{if(seq===state.seq){state.loading=false;render();chrome();}}}
  function visible(){const q=state.query.trim().toLowerCase();return (state.index?.groups||[]).filter(g=>(!state.campaign||g.campaignId===state.campaign)&&(!q||[g.name,g.campaignName,advertises(g),...listings(g).map(r=>r.title||'')].join(' ').toLowerCase().includes(q)));}
  function toggle(type,id,panel,open,name,sub){return '<button type="button" class="bg-toggle" data-bg-toggle="'+type+'" data-bg-id="'+esc(id)+'" aria-expanded="'+open+'" aria-controls="'+esc(panel)+'"><span class="bg-chev" aria-hidden="true"></span><span class="bg-name"><b title="'+esc(name)+'">'+esc(name)+'</b><small>'+esc(sub)+'</small></span></button>';}
  function leaf(name,sub,title,photo,status,metrics,currency,pending){return '<div class="bg-line bg-leaf"><span class="bg-name bg-listing">'+photo+'<span><b title="'+esc(title||name)+'">'+esc(name)+'</b>'+(sub?'<small>'+sub+'</small>':'')+'</span></span><span class="bg-state">'+status+'</span>'+(metrics===false?'<span class="bg-cells"></span>':cells(metrics,currency,pending))+'<span class="bg-act"></span></div>';}
  // What each group serves, one level down: its listings with their own figures, or the page it advertises.
  const clickNote=g=>g.report&&basisNow()==='conversion'?' Listing conversions are by ad-click date.':'';
  function panel(g,rows,currency,pending){const m=g.mapping||{},scope=scopeOf(g);let html='';
    const leaves=()=>rows.map(r=>leaf(listingName(r),esc(offerText(r.itemIds)),tidy(r.title),'<span class="bg-thumb">'+photoHtml(r.imageUrl,listingName(r),96)+'</span>',r.notes.map(n=>badge([n,n==='Out of stock'||n==='Limited'?'b-warn':'b-bad'])).join(''),r.metrics,currency,pending)).join('');
    // A removed group is history: what it showed in these dates and why it is still listed, nothing to open or design.
    if(g.historicalOnly)return (scope==='listings'&&g.channel==='pmax'?leaves():'')+'<p class="bg-note">'+esc(m.reason||'Removed from Google.')+'</p>';
    if(scope==='listings'&&g.channel==='pmax')html+=leaves()+'<p class="bg-note">'+(Array.isArray(g.listingMetrics)?'Listing figures count ads that showed that listing. The group total also includes ads without one.'+clickNote(g):'Listing figures are unavailable for this range.')+'</p>';
    else if(scope==='listings')html+=(m.urls||[]).filter(u=>/\/products\//.test(u)).map(u=>leaf(String((u.match(/\/products\/([^/?#]+)/)||[])[1]||'Listing').replace(/-/g,' '),'<a href="'+esc(u)+'" target="_blank" rel="noopener">View listing ↗</a>','', '<span class="bg-thumb"><span class="bg-photo is-empty" aria-hidden="true"></span></span>','',false)).join('')+'<p class="bg-note">Search reports figures per ad group, not per listing.</p>';
    else if(scope==='page'){const url=m.landing||(m.urls||[])[0];html+=leaf(pageLabel(url),url?'<a href="'+esc(url)+'" target="_blank" rel="noopener">'+esc(url.replace(/^https:\/\//,''))+' ↗</a>':'','','<span class="bg-thumb is-page" aria-hidden="true"></span>','',false)+'<p class="bg-note">'+esc(g.channel==='pmax'?'No product listings: this asset group advertises its landing page.':'No single product listing: ads lead to this page.')+'</p>';}
    else html+='<p class="bg-note">'+esc(scope==='unknown'?'The listing link is unavailable in this report. Refresh to retry.':m.reason||'No ad destination was returned for this group.')+'</p>';
    if(g.channel!=='display'){const busy=state.designing===key(g);html+='<div class="bg-panel-foot"><button type="button" class="btn ghost sm" data-bg-design-direct="'+esc(key(g))+'"'+(busy?' disabled':'')+'>'+(busy?spin+'Opening design…':'Design ad')+'</button></div>';}
    return html;}
  function groupRow(g,currency,pending,q){const k=key(g),rows=listings(g),open=state.expanded.has(k)||!!q&&rows.some(r=>String(r.title||'').toLowerCase().includes(q)),id='bg-g-'+g.id;return '<div class="bg-group'+(open?' is-open':'')+'" data-bg-group="'+esc(k)+'"><div class="bg-line bg-group-line">'+toggle('group',k,id,open,g.name,[kind(g),advertises(g)].filter(Boolean).join(' · '))+'<span class="bg-state">'+badge(groupState(g,true))+'</span>'+cells(fig(g),currency,pending)+'<span class="bg-act">'+(g.historicalOnly?'':'<button type="button" class="btn ghost sm" data-bg-open="'+esc(k)+'">Open</button>')+'</span></div><div class="bg-collapse" id="'+esc(id)+'"><div class="bg-collapse-inner">'+panel(g,rows,currency,pending)+'</div></div></div>';}
  function table(){
    const r=state.index,all=r?.groups||[],shown=visible(),currency=moneyOf(all,r?.currency),pending=state.loading,q=state.query.trim().toLowerCase();
    if(!r)return state.loading?'<div class="bg-tree is-skeleton" aria-hidden="true">'+[46,34,40,28,36].map(w=>'<div class="bg-line"><span class="bg-bone" style="width:'+w+'%"></span></div>').join('')+'</div>':'<p class="bg-empty">'+(state.error?'Live groups are unavailable. Open Saved workspaces to continue editing.':'No groups are loaded yet.')+'</p>';
    if(!shown.length)return '<p class="bg-empty">'+(all.length?'No campaign, group or listing matches this filter.':'No campaigns or groups were returned for this range.')+'</p>';
    // Serving campaigns first, then paused or ended ones, then removed ones kept for their figures.
    const rank=c=>{const s=campaignState(c.id,c.status);return s[0]==='Removed'?2:serving(s)?0:1;};
    const campaigns=[...new Map(shown.map(g=>[g.campaignId,g])).values()].map(c=>{const members=all.filter(g=>g.campaignId===c.campaignId);return {id:c.campaignId,name:c.campaignName,status:c.campaignStatus,channel:c.channel,members,groups:shown.filter(g=>g.campaignId===c.campaignId).sort((a,b)=>bySpend(a,b)||a.name.localeCompare(b.name)),metrics:total(members)};}).sort((a,b)=>rank(a)-rank(b)||bySpend(a,b)||a.name.localeCompare(b.name));
    return '<div class="bg-tree"'+(pending?' aria-busy="true"':'')+'><div class="bg-line bg-head" aria-hidden="true"><span>Campaign › group › listing</span><span>Status</span>'+COLS.map(([,label])=>'<span>'+esc(label)+'</span>').join('')+'<span></span></div>'+campaigns.map(c=>{const open=!state.closed.has(c.id),id='bg-c-'+c.id,n=c.members.length,gone=c.members.filter(g=>g.historicalOnly).length,unit=c.channel==='pmax'?'asset group':'ad group';return '<section class="bg-campaign'+(open?' is-open':'')+'" data-bg-campaign-id="'+esc(c.id)+'"><div class="bg-line bg-camp-line">'+toggle('campaign',c.id,id,open,c.name,(c.channel==='pmax'?'Performance Max':c.channel==='display'?'Display':'Search')+' · '+(c.groups.length<n?c.groups.length+' of ':'')+n+' '+unit+(n===1?'':'s')+(gone&&c.status!=='REMOVED'?' · '+gone+' removed':''))+'<span class="bg-state">'+badge(campaignState(c.id,c.status))+'</span>'+cells(c.metrics,currency,pending)+'<span class="bg-act"></span></div><div class="bg-collapse" id="'+esc(id)+'"><div class="bg-collapse-inner">'+c.groups.map(g=>groupRow(g,currency,pending,q)).join('')+'</div></div></section>';}).join('')+'</div>';}
  function verifiedProductUrl(p){try{const u=new URL(p.url);return p.title&&!/^Product \d+$/i.test(p.title)&&u.protocol==='https:'&&!u.username&&!u.password&&['britesjewelry.com','www.britesjewelry.com'].includes(u.hostname)&&/\/(?:collections\/[^/]+\/)?products\/([a-zA-Z0-9_-]+)\/?$/.test(u.pathname)?u.href:null;}catch{return null;}}
  function productRows(d,withMetrics){const g=selected()||d.group,figures=withMetrics&&d.group.channel==='pmax',scope=scopeOf(g),landing=g.mapping?.landing||(g.mapping?.urls||[])[0];if(!d.products.length&&scope==='page')return '<div class="bg-products"><article class="bg-landing"><span class="bg-thumb is-page" aria-hidden="true"></span><div><b>'+esc(pageLabel(landing))+'</b>'+(landing?'<a href="'+esc(landing)+'" target="_blank" rel="noopener">'+esc(String(landing).replace(/^https:\/\//,''))+' ↗</a>':'')+'<small>'+esc(g.channel==='pmax'?'No product listings: this asset group advertises its landing page.':'No single product listing: ads lead to this page.')+'</small></div></article></div>';
    // Busiest listing first when the report has figures per listing; the header names each figure column.
    const rows=d.products.map(p=>({p,offers:groupOffers(d.group,p)}));if(figures)rows.forEach(r=>r.m=offerMetrics(d.group,r.offers)),rows.sort((a,b)=>(b.m?.spend||0)-(a.m?.spend||0));
    return '<div class="bg-products'+(figures?' has-metrics':'')+'">'+(figures&&rows.length?'<div class="bg-products-head" aria-hidden="true"><span></span><span>Listing</span>'+COLS.map(([,label])=>'<span>'+esc(label)+'</span>').join('')+'<span></span></div>':'')+rows.map(({p,offers,m})=>{const url=verifiedProductUrl(p),full=tidy(p.title);return '<article>'+photoHtml(p.image,full)+'<div><b title="'+esc(full)+'">'+esc(shortTitle(p.title))+'</b>'+(d.group.channel==='pmax'&&offerText(offers)?'<small>'+esc(offerText(offers))+'</small>':'')+(url?'<a href="'+esc(url)+'" target="_blank" rel="noopener">View listing ↗</a>':'<small>Restore this product’s verified title and listing before designing.</small>')+'</div>'+(figures?cells(m,moneyOf([d.group],d.currency),false):'')+'<button class="btn ghost sm"'+(url?' data-bg-design="'+esc(p.id)+'"':' disabled')+'>Design &amp; research</button></article>';}).join('')+(!d.products.length?'<p class="bg-empty">'+esc(scope==='feed'?'This group serves products through a feed filter, not exact listings.':'No verified product listing is linked.')+'</p>':'')+'</div>'+(figures&&d.products.length?'<p class="bg-note bg-note-flat">'+(Array.isArray(d.group.listingMetrics)?'Listing figures count ads that showed that listing; the group total also includes ads without one.'+clickNote(d.group):'Listing figures are unavailable for this range.')+'</p>':'');}
  function detailHtml(){const d=state.detail,g=selected();if(!g)return '';let html='<div class="bg-detail-head"><div><h2>'+esc(g.name)+'</h2><span>'+esc(g.campaignName)+' · '+esc(kind(g))+' · ID '+esc(g.id)+'</span></div>'+badge(groupState(g,false))+'</div>';
    if(!d)return html+(state.error?'<p class="bg-empty">Group details are unavailable.</p>':'<p class="bg-wait" role="status">'+spin+'Opening '+esc(g.name)+': listings, messaging and search themes…</p>');
    html+='<div class="bg-tabs" role="tablist">'+[['overview','Overview'],['targeting',g.channel==='pmax'?'Search themes':'Keywords'],['messaging','Messaging'],['designs','Designs & research'],['changes','Approvals']].map(([id,label])=>'<button role="tab" aria-selected="'+(state.tab===id)+'" data-bg-tab="'+id+'">'+label+'</button>').join('')+'</div>';
    if(state.tab==='overview'){const split=(d.splitProposals||[]).find(p=>p.status!=='APPLIED')||(d.splitProposals||[]).find(p=>p.status==='APPLIED');if(split){const done=d.group.status==='PAUSED'&&split.publication?.groups.every(x=>state.index.groups.find(g=>g.ref===x.ref)?.status==='ENABLED');html+='<div class="bg-notice"><div><b>'+esc(done?'Products separated':split.status==='APPLIED'?'Product groups created':'Product split saved')+'</b><p>'+esc(done?'The product groups are enabled.':split.status==='APPLIED'?'Review the switch from the shared group to the product groups.':'Complete each product’s creative in Approvals.')+'</p></div>'+(!done?button(split.status==='APPLIED'?'activate':'approvals',split.status==='APPLIED'?(state.activating?spin+'Preparing switch…':'Review switch'):'Review split',true,state.activating):'')+'</div>';}html+='<div class="bg-report-label"><span>'+esc(scopeText(d,[d.group]))+'</span>'+reloadLink+'</div>'+metricCards(d.group,moneyOf([d.group],d.currency))+(gaps([d.group])?missingNote:'');
      // Only a shared product pool is a split decision; pages, feed filters and unavailable links are explained, not flagged.
      if(g.mapping.status==='unavailable')html+='<div class="bg-notice"><div><b>Listing link unavailable</b><p>'+esc(g.mapping.reason||'Live product mapping is unavailable.')+' Refresh to retry.</p></div></div>';
      else if(d.group.mapping.status==='mixed'&&!split)html+='<div class="bg-notice"><div><b>These listings share one '+esc(kind(g).toLowerCase())+'</b><p>'+esc(d.group.mapping.reason||'Multiple product listings share this group.')+' Separate groups give each listing its own messaging, images and results.</p></div>'+button('split','Review product split',true,!d.splitAvailable)+'</div>'+(d.splitReason?'<details class="bg-more"'+(!d.splitAvailable?' open':'')+'><summary>Why the split is unavailable</summary><p>'+esc(d.splitReason)+'</p></details>':'');
      html+='<h3 class="bg-section">'+esc(scopeOf(g)==='page'?'Landing page':'Listings')+'</h3>'+productRows(d,true);}
    if(state.tab==='targeting'){html+='<div class="bg-report-label">'+(g.channel==='pmax'?'Search themes guide Google; they do not restrict reach.':'Keywords belong to this ad group. Campaign negatives apply across its groups.')+'</div><div class="bg-keywords">'+d.keywords.map(k=>chip(k.text+(k.negative?' · Negative':'')+(k.matchType?' · '+k.matchType:'')+(k.status&&k.status!=='ENABLED'?' · '+k.status:''))).join('')+'</div>'+(!d.keywords.length?'<p class="bg-empty">'+(d.keywordStatus==='unavailable'?'Google search themes are temporarily unavailable.':'No '+(g.channel==='pmax'?'search themes':'keywords')+' were returned for this group.')+'</p>':'')+button('workspace','Research this group',true,!d.creativeRef);}
    if(state.tab==='messaging'){html+=d.copy.map(a=>'<article class="bg-copy"><header><b>'+esc(a.name)+'</b>'+chip(a.status||'Current Google copy')+'</header>'+[['Headlines',a.headlines],['Long headlines',a.longHeadlines],['Descriptions',a.descriptions]].filter(([,rows])=>rows?.length).map(([label,rows])=>'<h4>'+label+'</h4><ul>'+rows.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>').join('')+'<button type="button" class="btn ghost sm" data-bg-copy="'+esc(a.ref)+'">Edit messaging</button></article>').join('')+(!d.copy.length?'<p class="bg-empty">No editable ad copy was returned for this group.</p>':'');}
    if(state.tab==='designs'){html+=productRows(d,false)+'<details class="bg-more"><summary>Current Google images · '+d.images.length+'</summary><div class="bg-images">'+d.images.map(a=>'<a href="'+esc(a.url)+'" target="_blank" rel="noopener">'+photoHtml(a.url,a.fieldType)+'</a>').join('')+'</div></details>';}
    if(state.tab==='changes'){const pending=(options.dashboard()?.pending||[]).filter(a=>matchesApproval(a,selection()));html+='<div class="bg-changes">'+pending.map(a=>'<article><b>'+esc(a.summary||a.type)+'</b>'+chip(a.status||'Pending')+'</article>').join('')+(!pending.length?'<p class="bg-empty">No pending changes for this group.</p>':'')+button('approvals','Open Approvals',true)+'</div>';}
    if(d.warnings.length)html+='<details class="bg-more"><summary>Data coverage · '+d.warnings.length+'</summary>'+d.warnings.map(w=>'<p>'+esc(w)+'</p>').join('')+'</details>';return html;
  }
  async function savedWorkspaces(){
    const panel=document.createElement('dialog');panel.className='bg-split';
    panel.innerHTML='<h2>Saved ad workspaces</h2><p>Open saved artwork and messaging. Google publication still requires a fresh verification.</p><input type="search" aria-label="Find a saved workspace" placeholder="Find a saved workspace"><div data-bg-saved-list></div><p role="status"></p><div>'+button('more','Load more')+button('close','Close')+'</div>';
    document.body.appendChild(panel);panel.showModal();let rows=[],after=null,closed=false;
    const status=panel.querySelector('[role=status]'),more=panel.querySelector('[data-bg-action=more]'),list=panel.querySelector('[data-bg-saved-list]'),search=panel.querySelector('input');
    const draw=()=>{const term=search.value.toLowerCase();list.innerHTML=rows.filter(w=>[w.name,w.productId,w.campaignId].join(' ').toLowerCase().includes(term)).sort((a,b)=>Number(b.updatedAt||0)-Number(a.updatedAt||0)).map(w=>'<article><b>'+esc(w.name)+'</b><p>'+esc((w.productId||'').split('/').pop())+(w.sourceVersion?' · Version '+esc(w.sourceVersion):'')+(w.updatedAt?' · '+esc(new Date(w.updatedAt).toLocaleString()):'')+'</p><button type="button" class="btn ghost sm" data-bg-saved="'+esc(w.workspaceId)+'">Open saved workspace</button></article>').join('');list.querySelectorAll('[data-bg-saved]').forEach(b=>b.onclick=async()=>{const workspaceId=b.dataset.bgSaved;closed=true;panel.close();panel.remove();await options.design({workspaceId});});};
    const loadPage=async()=>{more.disabled=true;status.innerHTML=spin+'Loading saved workspaces…';try{const r=await options.api('adDesignSavedWorkspaces',after?{after}:{});if(closed)return;if(!r||r.error||r.ok===false)throw Error(r?.error||'Saved workspaces could not be loaded.');rows=[...new Map([...rows,...r.workspaces].map(w=>[w.workspaceId,w])).values()];after=r.nextCursor||null;draw();status.textContent=rows.length+' saved workspace'+(rows.length===1?'':'s')+(after?' · Load more to see the next page.':'');more.hidden=!after;}catch(e){if(!closed)status.textContent=e.message;}finally{more.disabled=false;}};
    search.oninput=draw;more.onclick=loadPage;panel.querySelector('[data-bg-action=close]').onclick=()=>{closed=true;panel.close();panel.remove();};panel.oncancel=()=>{closed=true;panel.remove();};await loadPage();
  }
  function render(){if(!host)return;const g=selected(),r=state.index,campaigns=[...new Map((r?.groups||[]).map(g=>[g.campaignId,g.campaignName+(g.campaignStatus==='REMOVED'?' (removed)':'')]))],today=(options.dashboard&&options.dashboard()?.accountToday)||r?.range?.end||'';
    host.innerHTML='<div class="bg-toolbar"><div class="bg-context" data-bg-context-slot hidden></div>'+(!g?'<input data-bg-search type="search" placeholder="Find a campaign, group or listing" aria-label="Find a campaign, group or listing" value="'+esc(state.query)+'"><select data-bg-campaign aria-label="Campaign"><option value="">All campaigns</option>'+campaigns.map(([id,name])=>'<option value="'+esc(id)+'"'+(state.campaign===id?' selected':'')+'>'+esc(name)+'</option>').join('')+'</select>':'')+'<span class="bg-dates"><label>From <input type="date" data-bg-start value="'+esc(state.start)+'"'+(state.end?' max="'+esc(state.end)+'"':'')+(!state.start?' disabled':'')+'></label><label>To <input type="date" data-bg-end value="'+esc(state.end)+'"'+(state.start?' min="'+esc(state.start)+'"':'')+(today?' max="'+esc(today)+'"':'')+(!state.end?' disabled':'')+'></label></span>'+button('saved','Saved workspaces')+'</div>'+(state.error?'<p class="bg-error" role="alert">'+esc(state.error)+'</p>':'')+(!g?(state.loading?'<p class="bg-wait" role="status">'+spin+esc((r?'Refreshing':'Loading')+' campaigns, groups and listings'+(state.start&&state.end?' for '+rangeText(state.start,state.end):'')+'…')+'</p>':r?'<p class="bg-scope"><span>'+esc([scopeText(r,r.groups),stamp(r)].filter(Boolean).join(' · '))+'</span>'+reloadLink+'</p>'+(gaps(r.groups)?missingNote:''):''):'')+(g?detailHtml():table())+(!g&&r?.warnings.length?'<details class="bg-more"><summary>Data coverage · '+r.warnings.length+'</summary>'+r.warnings.map(w=>'<p>'+esc(w)+'</p>').join('')+'</details>':'');wire();wirePhotos();drawContext(options.currentView());}
  async function designDirect(g){if(!g||state.designing)return;state.designing=key(g);state.error='';render();try{const d=await options.api('adGroupDetail',{campaignId:g.campaignId,groupRef:g.ref,start:state.start,end:state.end,reportingTree:true});if(!d||d.error||!d.creativeRef)throw Error(d?.error||'This group has no editable ad.');await options.design({campaignId:g.campaignId,groupRef:d.creativeRef,productId:d.products[0]?.id,range:d.range,returnLabel:'Products & groups'});}catch(e){state.error=e.message;}finally{state.designing=null;render();}}
  async function openWorkspace(productId,creativeRef){const d=state.detail,g=selected();if(!d||!g)return;await options.design({campaignId:g.campaignId,groupRef:creativeRef||d.creativeRef,productId:productId||d.products[0]?.id,productIds:productId?[productId]:undefined,range:d.range,returnLabel:g.name});}
  // The table shows the names and states the draft gives Google (same naming as draftSplit in googleAdsGroups.js).
  async function split(){const d=state.detail;if(!d?.splitAvailable)return;const pmax=d.group.channel==='pmax',panel=document.createElement('dialog');panel.className='bg-split';panel.innerHTML='<h2>One group per listing</h2><p>'+esc(d.group.name)+' · '+esc(d.group.campaignName)+'</p><table><thead><tr><th>New '+(pmax?'asset group':'ad group')+'</th><th>Serves</th><th>Starts</th></tr></thead><tbody>'+d.products.map(p=>{const n=groupOffers(d.group,p).length;return '<tr><td>'+esc(('Product · '+p.title).slice(0,128))+'</td><td>'+esc(pmax?(n===1?'1 Merchant offer':n+' Merchant offers'):'Its listing page')+'</td><td>Paused</td></tr>';}).join('')+'</tbody></table><p>Each new group gets its own '+(pmax?'messaging, search themes, images':'ad, exact keywords')+' and listing URL. The current group keeps running and the campaign budget stays the same. The exact changes go to Approvals for review before Google receives them.</p><div>'+button('cancel','Cancel')+button('prepare','Prepare split',true)+'</div><p data-bg-split-status role="status"></p>';document.body.appendChild(panel);panel.showModal();let open=true;const close=()=>{open=false;panel.close();panel.remove();};panel.oncancel=()=>{open=false;panel.remove();};panel.querySelector('[data-bg-action=cancel]').onclick=close;panel.querySelector('[data-bg-action=prepare]').onclick=async function(){this.disabled=true;const status=panel.querySelector('[data-bg-split-status]');status.innerHTML=spin+'Preparing separate product groups…';try{const r=await options.api('draftAdGroupSplit',{campaignId:d.group.campaignId,groupRef:d.group.ref,expectedVersion:d.sourceVersion,snapshotHash:d.snapshotHash});if(!r||r.error||r.ok===false)throw Error(r?.error||'The split could not be prepared.');const stay=!open;if(open)close();await options.reload();if(!stay)options.go('approvals');options.toast(stay?'Split saved in Approvals. Review each product’s creative before creating the paused groups.':'Split saved. Review each product’s creative before creating the paused groups.',true);}catch(e){if(open){status.textContent=e.message;this.disabled=false;}else options.toast(e.message,false);}};}
  async function activate(){const d=state.detail,split=(d?.splitProposals||[]).find(p=>p.status==='APPLIED');if(!split||state.activating)return;state.activating=true;state.error='';render();try{const r=await options.api('draftAdGroupActivation',{splitId:split.id});if(!r||r.error||r.ok===false)throw Error(r?.error||'The switch could not be prepared.');await options.reload();options.go('approvals');options.toast('Review the group switch in Approvals. Traffic has not changed.',true);}catch(e){state.error=e.message;}finally{state.activating=false;render();}}
  function flip(b){const type=b.dataset.bgToggle,id=b.dataset.bgId,box=b.closest(type==='campaign'?'.bg-campaign':'.bg-group'),open=!box.classList.contains('is-open');box.classList.toggle('is-open',open);b.setAttribute('aria-expanded',String(open));if(type==='campaign'){if(open)state.closed.delete(id);else state.closed.add(id);}else if(open)state.expanded.add(id);else state.expanded.delete(id);}
  function wire(){host.querySelectorAll('[data-bg-toggle]').forEach(b=>b.onclick=()=>flip(b));host.querySelectorAll('.bg-camp-line,.bg-group-line').forEach(line=>line.onclick=e=>{if(!e.target.closest('button,a,input,select,label'))line.querySelector('[data-bg-toggle]').click();});host.querySelectorAll('[data-bg-design-direct]').forEach(b=>b.onclick=()=>designDirect(state.index.groups.find(g=>key(g)===b.dataset.bgDesignDirect)));host.querySelectorAll('[data-bg-start],[data-bg-end]').forEach(input=>input.onchange=()=>{const start=host.querySelector('[data-bg-start]').value,end=host.querySelector('[data-bg-end]').value,bad=!start||!end||start>end;if(input.setCustomValidity){input.setCustomValidity(bad?'Choose a start date on or before the end date.':'');if(bad&&input.reportValidity)input.reportValidity();}if(bad)return;state.start=start;state.end=end;load(true);});host.querySelectorAll('[data-bg-action]').forEach(b=>{b.onclick=()=>{const a=b.dataset.bgAction;if(a==='saved')savedWorkspaces();if(a==='refresh'){const start=host.querySelector('[data-bg-start]').value,end=host.querySelector('[data-bg-end]').value;if(start&&end&&start<=end){state.start=start;state.end=end;}load(true);}if(a==='workspace')openWorkspace();if(a==='split')split();if(a==='activate')activate();if(a==='approvals')options.go('approvals');};});host.querySelectorAll('[data-bg-open]').forEach(b=>b.onclick=()=>choose(state.index.groups.find(g=>key(g)===b.dataset.bgOpen)));host.querySelectorAll('[data-bg-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.bgTab;render();chrome();});host.querySelectorAll('[data-bg-design]').forEach(b=>b.onclick=()=>openWorkspace(b.dataset.bgDesign));host.querySelectorAll('[data-bg-copy]').forEach(b=>b.onclick=()=>openWorkspace(null,b.dataset.bgCopy));const search=host.querySelector('[data-bg-search]');if(search)search.oninput=()=>{state.query=search.value;const start=search.selectionStart;render();const restored=host.querySelector('[data-bg-search]');restored.focus();restored.setSelectionRange(start,start);};const campaign=host.querySelector('[data-bg-campaign]');if(campaign)campaign.onchange=()=>{state.campaign=campaign.value;if(state.campaign)state.closed.delete(state.campaign);render();chrome();};}
  function init(config){options=config;host=document.getElementById('v-groups');try{state.selected=sessionStorage.getItem('brites.group')||null;}catch{}chrome();}
  function show(){if(!state.index&&!state.loading)load();else{render();chrome('groups');}}
  function removeCampaign(id){id=String(id);++state.seq;state.loading=false;if(state.index)state.index.groups=state.index.groups.filter(g=>g.campaignId!==id);if(state.campaign===id)state.campaign='';if(state.selected?.startsWith(id+'|')){state.selected=null;state.detail=null;}history=history.filter(p=>p.campaign!==id&&!p.selected?.startsWith(id+'|'));if(activePlace&&(activePlace.campaign===id||activePlace.selected?.startsWith(id+'|')))activePlace=null;persist();if(host){render();chrome();}}
  root.BritesGroups={init,show,chrome,removeCampaign,openGroup:async function(campaignId,ref){const from=activePlace;options.go('groups');if(!state.index)await(state.inflight||load());const g=state.index?.groups.find(g=>g.campaignId===String(campaignId)&&g.ref===ref);if(!g)return;
    // A removed group has no detail to open; show it expanded in its campaign instead.
    if(g.historicalOnly){state.selected=null;state.detail=null;state.campaign=g.campaignId;state.closed.delete(g.campaignId);state.expanded.add(key(g));persist();render();chrome('groups');return;}
    // The list passed on the way is not a stop for Back, which returns to where the group was opened from.
    if(from&&activePlace!==from){const i=history.lastIndexOf(from);if(i>=0)history.length=i;activePlace=from;}await choose(g);},browseCampaign:function(id){state.selected=null;state.detail=null;state.campaign=String(id);state.closed.delete(String(id));persist();options.go('groups');if(state.index)render();},selection,matchesApproval,approvalRefs,refresh:()=>load(true),state};
  if(typeof module==='object')module.exports={matchesApproval,approvalRefs,metricCards,listings,advertises,shortTitle,compactName};
})(typeof window==='object'?window:globalThis);
