(function(root){
  'use strict';
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const key=g=>g.campaignId+'|'+g.ref;
  function photoHtml(url,label=''){
    let u;try{u=new URL(url);if(u.protocol!=='https:')return '';}catch{return '';}
    const original=u.href,cors=['cdn.shopify.com','storage.googleapis.com','firebasestorage.googleapis.com'].includes(u.hostname)||u.hostname.endsWith('.storage.googleapis.com');
    if(u.hostname==='cdn.shopify.com'){u.searchParams.set('width','320');u.searchParams.delete('height');u.searchParams.delete('crop');}
    return '<span class="bg-photo"><img'+(cors?' crossorigin="anonymous"':'')+' src="'+esc(u.href)+'" data-bg-original="'+esc(original)+'" alt="'+esc(label)+'" loading="lazy"><span hidden>Image unavailable</span></span>';
  }
  function wirePhotos(){host.querySelectorAll('[data-bg-original]').forEach(img=>{img.onerror=()=>{if(img.src!==img.dataset.bgOriginal){img.src=img.dataset.bgOriginal;return;}img.hidden=true;img.nextElementSibling.hidden=false;};img.onload=()=>{img.hidden=false;img.nextElementSibling.hidden=true;};});}
  function approvalRefs(a){const p=a.payload||{},out=[p.meta?.sourceGroupRef,...(p.meta?.groupRefs||[]),p.adDesign?.settings?.groupRef,p.adDesign?.groupRef];for(const x of p.versionChange?.changes||[])out.push(x.target);for(const g of p.meta?.assetGroups||[])out.push(g.ref);for(const op of p.mutateOperations||[]){for(const v of Object.values(op)){const r=v.create||v.update||{};out.push(r.assetGroup,r.adGroup);const ref=v.remove||r.resourceName;if(typeof ref==='string'){let m=ref.match(/^(customers\/\d+\/)(assetGroupAssets|adGroupAds|adGroupCriteria|adGroupAssets)\/(\d+)/);if(m)out.push(m[1]+(m[2]==='assetGroupAssets'?'assetGroups':'adGroups')+'/'+m[3]);}}}return [...new Set(out.filter(Boolean))];}
  function matchesApproval(a,g){const refs=approvalRefs(a);return refs.includes(g.ref)||(g.creativeRefs||[]).some(r=>refs.includes(r));}
  const state={index:null,detail:null,selected:null,query:'',campaign:'',tab:'overview',loading:false,error:'',seq:0,start:'',end:''};
  let options,host,history=[],activePlace=null,replaying=false;
  const number=v=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
  const cash=(v,c)=>v==null?'—':c+' '+number(v);
  const chip=(label,kind='')=>'<span class="bg-chip '+kind+'">'+esc(label)+'</span>';
  const button=(action,label,primary=false,disabled=false)=>'<button type="button" class="btn '+(primary?'gold':'ghost')+' sm" data-bg-action="'+action+'"'+(disabled?' disabled':'')+'>'+label+'</button>';
  function compactName(g){return g.mapping.productIds.length===1?'Product '+g.mapping.productIds[0]:g.mapping.handles.length===1?g.mapping.handles[0].replace(/-/g,' '):g.mapping.status==='mixed'?Math.max(g.mapping.productIds.length,g.mapping.handles.length)+' linked products':'Product link needs review';}
  function metricCards(g,currency){const m=g.metrics;return '<div class="bg-metrics">'+[['Spend',cash(m?.spend,currency)],['Clicks',number(m?.clicks)],['Conversions',number(m?.conversions)],['Conversion value',cash(m?.value,currency)],['Views',number(m?.impressions)],['CTR',m?(m.impressions?number(m.clicks/m.impressions*100)+'%':'—'):'—']].map(([l,v])=>'<div><b>'+v+'</b><span>'+l+'</span></div>').join('')+'</div>';}
  function selected(){return state.index?.groups.find(g=>key(g)===state.selected)||null;}
  function selection(){const g=selected();return g?{...g,creativeRefs:(state.detail?.copy||[]).map(a=>a.ref)}:null;}
  function place(view){return {view:view||options.currentView(),selected:state.selected,campaign:state.campaign,query:state.query,tab:state.tab,detail:state.detail};}
  function remember(view){const p=place(view),id=x=>x&&[x.view,x.selected,x.campaign,x.tab].join('|');if(!replaying&&activePlace&&id(activePlace)!==id(p)){history.push(activePlace);if(history.length>40)history.shift();}activePlace=p;}
  function back(){const p=history.pop();if(!p)return;replaying=true;state.selected=p.selected;state.campaign=p.campaign;state.query=p.query;state.tab=p.tab;state.detail=p.detail;++state.seq;state.loading=false;activePlace=p;persist();options.go(p.view);render();chrome(p.view);replaying=false;}
  function chrome(view){
    const bar=document.getElementById('groupContext');if(!bar)return;remember(view);const g=selected(),v=view||options.currentView(),scope={groups:'Products & groups',command:'Account overview',sales:'Store sales',approvals:'Approvals',bench:'Opportunities',controls:'Controls'}[v]||'Account';
    bar.innerHTML='<nav class="bg-breadcrumbs" aria-label="Breadcrumb"><button type="button" data-bg-history-back'+(!history.length?' disabled':'')+' aria-label="Go back">‹ Back</button><button type="button" data-bg-home>Products &amp; groups</button>'+(g?'<span aria-hidden="true">/</span><button type="button" data-bg-campaign-back>'+esc(g.campaignName)+'</button><span aria-hidden="true">/</span><button type="button" data-bg-context>'+esc(g.name)+'</button>':state.campaign?'<span aria-hidden="true">/</span><span>'+esc(state.index?.groups.find(x=>x.campaignId===state.campaign)?.campaignName||'Campaign')+'</span>':'')+(v!=='groups'?'<span aria-hidden="true">/</span><span aria-current="page">'+esc(scope)+'</span>':g?'<span aria-hidden="true">/</span><span aria-current="page">'+esc({overview:'Overview',targeting:g.channel==='pmax'?'Search themes':'Keywords',messaging:'Messaging',designs:'Designs',changes:'Approvals'}[state.tab])+'</span>':'')+'</nav>';
    bar.querySelector('[data-bg-history-back]').onclick=back;bar.querySelector('[data-bg-home]').onclick=()=>{state.selected=null;state.detail=null;state.campaign='';persist();options.changed();options.go('groups');render();chrome('groups');};const campaign=bar.querySelector('[data-bg-campaign-back]');if(campaign)campaign.onclick=()=>{state.selected=null;state.detail=null;state.campaign=g.campaignId;persist();options.changed();options.go('groups');render();chrome('groups');};const group=bar.querySelector('[data-bg-context]');if(group)group.onclick=()=>{options.go('groups');chrome('groups');};
  }
  function persist(){try{sessionStorage.setItem('brites.group',state.selected||'');}catch{}}
  async function load(force=false){const seq=++state.seq;state.loading=true;state.error='';state.detail=null;if(state.index)state.index={...state.index,groups:state.index.groups.map(g=>({...g,metrics:null}))};render();try{const r=await options.api('adGroups',{start:state.start||undefined,end:state.end||undefined,force});if(seq!==state.seq)return;if(!r||r.error||r.ok===false)throw Error(r?.error||'Groups could not be loaded.');state.index=r;state.start=r.range.start;state.end=r.range.end;if(state.selected&&!r.groups.some(g=>key(g)===state.selected)){state.selected=null;state.detail=null;persist();}if(selected())await loadDetail(selected(),seq);}catch(e){if(seq===state.seq)state.error=e.message;}finally{if(seq===state.seq){state.loading=false;render();chrome();}}}
  async function loadDetail(g,seq){state.detail=null;const r=await options.api('adGroupDetail',{campaignId:g.campaignId,groupRef:g.ref,start:state.start,end:state.end});if(seq!==state.seq||state.selected!==key(g))return;if(!r||r.error||r.ok===false)throw Error(r?.error||'The group could not be opened.');state.detail=r;options.changed();}
  async function choose(g){state.selected=key(g);state.tab='overview';state.detail=null;state.loading=true;state.error='';persist();const seq=++state.seq;render();chrome();try{await loadDetail(g,seq);}catch(e){if(seq===state.seq)state.error=e.message;}finally{if(seq===state.seq){state.loading=false;render();chrome();}}}
  function table(){const groups=(state.index?.groups||[]).filter(g=>(!state.campaign||g.campaignId===state.campaign)&&(!state.query||[g.name,g.campaignName,compactName(g)].join(' ').toLowerCase().includes(state.query.toLowerCase())));return '<div class="bg-table-wrap"><table class="bg-table"><thead><tr><th>Product / group</th><th>Campaign</th><th>Status</th><th>Spend</th><th>Conversions</th><th></th></tr></thead><tbody>'+groups.map(g=>'<tr><td><b>'+esc(g.name)+'</b><small>'+esc(compactName(g))+'</small>'+(g.mapping.status!=='focused'?chip(g.mapping.status==='mixed'?'Shared product pool':'Check product link','attention'):'')+'</td><td>'+esc(g.campaignName)+'<small>'+esc(g.channel==='pmax'?'PMax · asset group':'Search · ad group')+'</small></td><td>'+chip(g.serving,g.campaignStatus==='ENABLED'&&g.status==='ENABLED'&&g.primaryStatus==='ELIGIBLE'?'live':'')+'</td><td>'+cash(g.metrics?.spend,state.index.currency)+'</td><td>'+number(g.metrics?.conversions)+'</td><td><button type="button" class="btn ghost sm" data-bg-open="'+esc(key(g))+'">Open</button><button type="button" class="btn gold sm" data-bg-design-direct="'+esc(key(g))+'"'+(state.designing===key(g)?' disabled':'')+'>'+(state.designing===key(g)?'Opening…':'Design Ad')+'</button></td></tr>').join('')+'</tbody></table>'+(!groups.length?'<p class="bg-empty">'+(state.index?'No groups match.':'Loading groups…')+'</p>':'')+'</div>';}
  function productRows(d){return '<div class="bg-products">'+d.products.map(p=>'<article>'+photoHtml(p.image,p.title)+'<div><b>'+esc(p.title)+'</b><small>'+esc(p.offerIds.length+' Merchant offers')+'</small><a href="'+esc(p.url)+'" target="_blank" rel="noopener">View listing ↗</a></div><button class="btn ghost sm" data-bg-design="'+esc(p.id)+'">Design &amp; research</button></article>').join('')+(!d.products.length?'<p class="bg-empty">No verified product listing is linked.</p>':'')+'</div>';}
  function detailHtml(){const d=state.detail,g=selected();if(!g)return '';let html='<div class="bg-detail-head">'+button('back','← Groups')+'<div><h2>'+esc(g.name)+'</h2><span>'+esc(g.campaignName)+' · '+esc(g.channel==='pmax'?'PMax asset group':'Search ad group')+' '+esc(g.id)+'</span></div>'+chip(g.serving)+'</div>';
    if(!d)return html+'<p class="bg-empty">'+(state.error?'Group details are unavailable.':'Loading product links and group content…')+'</p>';
    html+='<div class="bg-tabs" role="tablist">'+[['overview','Overview'],['targeting',g.channel==='pmax'?'Search themes':'Keywords'],['messaging','Messaging'],['designs','Designs & research'],['changes','Approvals']].map(([id,label])=>'<button role="tab" aria-selected="'+(state.tab===id)+'" data-bg-tab="'+id+'">'+label+'</button>').join('')+'</div>';
    if(state.tab==='overview'){const split=(d.splitProposals||[]).find(p=>p.status!=='APPLIED')||(d.splitProposals||[]).find(p=>p.status==='APPLIED');if(split){const done=d.group.status==='PAUSED'&&split.publication?.groups.every(x=>state.index.groups.find(g=>g.ref===x.ref)?.status==='ENABLED');html+='<div class="bg-notice"><div><b>'+esc(done?'Products separated':split.status==='APPLIED'?'Product groups created':'Product split saved')+'</b><p>'+esc(done?'The product groups are enabled.':split.status==='APPLIED'?'Review the switch from the shared group to the product groups.':'Complete each product’s creative in Approvals.')+'</p></div>'+(!done?button(split.status==='APPLIED'?'activate':'approvals',split.status==='APPLIED'?'Review switch':'Review split',true):'')+'</div>';}html+='<div class="bg-report-label">Group results · '+esc(d.range.start+' → '+d.range.end)+' · '+esc(d.basis)+' · '+esc(d.currency)+'</div>'+metricCards(d.group,d.currency);if(d.group.mapping.status!=='focused'&&!split)html+='<div class="bg-notice"><div><b>'+esc(d.group.mapping.status==='mixed'?'These products share one creative pool':'Product link needs review')+'</b><p>'+esc(d.group.mapping.reason||'The exact product selection is not verified.')+'</p></div>'+button('split','Review product split',true,!d.splitAvailable)+'</div>'+(d.splitReason?'<details class="bg-more"><summary>Product selection details</summary><p>'+esc(d.splitReason)+'</p></details>':'');html+=productRows(d);}
    if(state.tab==='targeting'){html+='<div class="bg-report-label">'+(g.channel==='pmax'?'Search themes guide Google; they do not restrict reach.':'Keywords belong to this ad group. Campaign negatives apply across its groups.')+'</div><div class="bg-keywords">'+d.keywords.map(k=>chip(k.text+(k.negative?' · Negative':'')+(k.matchType?' · '+k.matchType:'')+(k.status&&k.status!=='ENABLED'?' · '+k.status:''))).join('')+'</div>'+(!d.keywords.length?'<p class="bg-empty">'+(d.keywordStatus==='unavailable'?'Google search themes are temporarily unavailable.':'No '+(g.channel==='pmax'?'search themes':'keywords')+' were returned for this group.')+'</p>':'')+button('workspace','Research this group',true,!d.creativeRef);}
    if(state.tab==='messaging'){html+=d.copy.map(a=>'<article class="bg-copy"><header><b>'+esc(a.name)+'</b>'+chip(a.status||'Current Google copy')+'</header>'+[['Headlines',a.headlines],['Long headlines',a.longHeadlines],['Descriptions',a.descriptions]].filter(([,rows])=>rows?.length).map(([label,rows])=>'<h4>'+label+'</h4><ul>'+rows.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>').join('')+'<button type="button" class="btn ghost sm" data-bg-copy="'+esc(a.ref)+'">Edit messaging</button></article>').join('');}
    if(state.tab==='designs'){html+=productRows(d)+'<details class="bg-more"><summary>Current Google images · '+d.images.length+'</summary><div class="bg-images">'+d.images.map(a=>'<a href="'+esc(a.url)+'" target="_blank" rel="noopener">'+photoHtml(a.url,a.fieldType)+'</a>').join('')+'</div></details>';}
    if(state.tab==='changes'){const pending=(options.dashboard()?.pending||[]).filter(a=>matchesApproval(a,selection()));html+='<div class="bg-changes">'+pending.map(a=>'<article><b>'+esc(a.summary||a.type)+'</b>'+chip(a.status||'Pending')+'</article>').join('')+(!pending.length?'<p class="bg-empty">No pending changes for this group.</p>':'')+button('approvals','Open Approvals',true)+'</div>';}
    if(d.warnings.length)html+='<details class="bg-more"><summary>Data coverage · '+d.warnings.length+'</summary>'+d.warnings.map(w=>'<p>'+esc(w)+'</p>').join('')+'</details>';return html;
  }
  function render(){if(!host)return;const g=selected(),r=state.index,campaigns=[...new Map((r?.groups||[]).map(g=>[g.campaignId,g.campaignName]))];
    host.innerHTML='<div class="bg-toolbar">'+(!g?'<input data-bg-search type="search" placeholder="Find a product or group" aria-label="Find a product or group" value="'+esc(state.query)+'"><select data-bg-campaign aria-label="Campaign"><option value="">All campaigns</option>'+campaigns.map(([id,name])=>'<option value="'+esc(id)+'"'+(state.campaign===id?' selected':'')+'>'+esc(name)+'</option>').join('')+'</select>':'')+'<label>From <input type="date" data-bg-start value="'+esc(state.start)+'"></label><label>To <input type="date" data-bg-end value="'+esc(state.end)+'"></label>'+button('refresh',state.loading?'Loading…':'Refresh',false,state.loading)+'</div>'+(state.error?'<p class="bg-error" role="alert">'+esc(state.error)+'</p>':'')+(state.loading?'<progress class="bg-progress" aria-label="Loading group data"></progress>':'')+(g?detailHtml():table())+(!g&&r?.warnings.length?'<details class="bg-more"><summary>Data coverage · '+r.warnings.length+'</summary>'+r.warnings.map(w=>'<p>'+esc(w)+'</p>').join('')+'</details>':'')+(!g&&r?'<div class="bg-report-label">Group results · '+esc(r.basis)+' · '+esc(r.currency)+' · '+esc(r.timeZone)+'</div>':'');wire();wirePhotos();}
  async function designDirect(g){if(!g||state.designing)return;state.designing=key(g);state.error='';render();try{const d=await options.api('adGroupDetail',{campaignId:g.campaignId,groupRef:g.ref,start:state.start,end:state.end});if(!d||d.error||!d.creativeRef)throw Error(d?.error||'This group has no editable ad.');await options.design({campaignId:g.campaignId,groupRef:d.creativeRef,productId:d.products[0]?.id,range:d.range,returnLabel:'Products & groups'});}catch(e){state.error=e.message;}finally{state.designing=null;render();}}
  async function openWorkspace(productId,creativeRef){const d=state.detail,g=selected();if(!d||!g)return;await options.design({campaignId:g.campaignId,groupRef:creativeRef||d.creativeRef,productId:productId||d.products[0]?.id,productIds:productId?[productId]:undefined,range:d.range,returnLabel:g.name});}
  async function split(){const d=state.detail;if(!d?.splitAvailable)return;const panel=document.createElement('dialog');panel.className='bg-split';panel.innerHTML='<h2>One group per product</h2><p>Review '+esc(d.group.name)+'</p><table><thead><tr><th>New group</th><th>Products</th><th>Starts</th></tr></thead><tbody>'+d.products.map(p=>'<tr><td>'+esc(p.title)+'</td><td>One listing</td><td>Paused</td></tr>').join('')+'</tbody></table><p>Each group gets its own messaging, themes, images and listing URL. The current group stays running. The campaign budget stays the same.</p><div>'+button('cancel','Cancel')+button('prepare','Prepare split',true)+'</div><p data-bg-split-status role="status"></p>';document.body.appendChild(panel);panel.showModal();panel.querySelector('[data-bg-action=cancel]').onclick=()=>{panel.close();panel.remove();};panel.querySelector('[data-bg-action=prepare]').onclick=async function(){this.disabled=true;const status=panel.querySelector('[data-bg-split-status]');status.textContent='Preparing separate product groups…';try{const r=await options.api('draftAdGroupSplit',{campaignId:d.group.campaignId,groupRef:d.group.ref,expectedVersion:d.sourceVersion,snapshotHash:d.snapshotHash});if(!r||r.error||r.ok===false)throw Error(r?.error||'The split could not be prepared.');panel.close();panel.remove();await options.reload();options.go('approvals');options.toast('Split saved. Review each product’s creative before creating the paused groups.',true);}catch(e){status.textContent=e.message;this.disabled=false;}};}
  async function activate(){const d=state.detail,split=(d?.splitProposals||[]).find(p=>p.status==='APPLIED');if(!split)return;state.loading=true;render();try{const r=await options.api('draftAdGroupActivation',{splitId:split.id});if(!r||r.error||r.ok===false)throw Error(r?.error||'The switch could not be prepared.');await options.reload();options.go('approvals');options.toast('Review the group switch in Approvals. Traffic has not changed.',true);}catch(e){state.error=e.message;}finally{state.loading=false;render();}}
  function wire(){host.querySelectorAll('[data-bg-design-direct]').forEach(b=>b.onclick=()=>designDirect(state.index.groups.find(g=>key(g)===b.dataset.bgDesignDirect)));host.querySelectorAll('[data-bg-start],[data-bg-end]').forEach(input=>input.onchange=()=>{state.start=host.querySelector('[data-bg-start]').value;state.end=host.querySelector('[data-bg-end]').value;load(true);});host.querySelectorAll('[data-bg-action]').forEach(b=>{b.onclick=()=>{const a=b.dataset.bgAction;if(a==='refresh'){state.start=host.querySelector('[data-bg-start]').value;state.end=host.querySelector('[data-bg-end]').value;load(true);}if(a==='back'){state.selected=null;state.detail=null;++state.seq;state.loading=false;persist();options.changed();render();chrome();}if(a==='workspace')openWorkspace();if(a==='split')split();if(a==='activate')activate();if(a==='approvals')options.go('approvals');};});host.querySelectorAll('[data-bg-open]').forEach(b=>b.onclick=()=>choose(state.index.groups.find(g=>key(g)===b.dataset.bgOpen)));host.querySelectorAll('[data-bg-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.bgTab;render();chrome();});host.querySelectorAll('[data-bg-design]').forEach(b=>b.onclick=()=>openWorkspace(b.dataset.bgDesign));host.querySelectorAll('[data-bg-copy]').forEach(b=>b.onclick=()=>openWorkspace(null,b.dataset.bgCopy));const search=host.querySelector('[data-bg-search]');if(search)search.oninput=()=>{state.query=search.value;const start=search.selectionStart;render();const restored=host.querySelector('[data-bg-search]');restored.focus();restored.setSelectionRange(start,start);};const campaign=host.querySelector('[data-bg-campaign]');if(campaign)campaign.onchange=()=>{state.campaign=campaign.value;render();};}
  function init(config){options=config;host=document.getElementById('v-groups');try{state.selected=sessionStorage.getItem('brites.group')||null;}catch{}chrome();}
  function show(){if(!state.index&&!state.loading)load();else{render();chrome('groups');}}
  root.BritesGroups={init,show,chrome,openGroup:async function(campaignId,ref){options.go('groups');if(!state.index)await load();const g=state.index?.groups.find(g=>g.campaignId===String(campaignId)&&g.ref===ref);if(g)await choose(g);},browseCampaign:function(id){state.selected=null;state.detail=null;state.campaign=String(id);persist();options.go('groups');if(state.index)render();},selection,matchesApproval,approvalRefs,refresh:()=>load(true),state};
  if(typeof module==='object')module.exports={matchesApproval,approvalRefs,metricCards};
})(typeof window==='object'?window:globalThis);
