const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),editor=require(root+'/brites-ad-editor.js');
let checks=0;const check=(v,m)=>{assert.ok(v,m);checks++};
const original={version:'7.4.0',objects:[{type:'Group',left:80,top:40,scaleX:1,scaleY:1,objects:[{type:'Image',sourceKey:'source_1',src:'https://expired.example/image',crossOrigin:'anonymous'},{type:'Textbox',text:'Duck necklace',fontFamily:'Georgia'}]}]};
const saved=editor.withoutUrls(original);check(!JSON.stringify(saved).includes('expired.example'),'editable document keeps source keys rather than expiring image URLs');
const restored=editor.withSources(saved,[{id:'source_1',url:'https://saved.example/fresh'}]);check(restored.objects[0].objects[0].src==='https://saved.example/fresh','images nested in groups receive refreshed source URLs');
assert.throws(()=>editor.withSources(saved,[]),/original image/);checks++;
const wide=editor.adapt(saved,{width:400,height:400},{width:800,height:400});check(wide.objects[0].left===160&&wide.objects[0].scaleX===wide.objects[0].scaleY,'new artboards preserve object proportions');check(saved.objects[0].left===80,'resizing does not mutate the original artboard');
check(editor.formats.filter(f=>f.category==='Master artwork').length===3&&editor.formats.some(f=>f.width===320&&f.height===50)&&editor.formats.some(f=>f.width===300&&f.height===600),'all three master ratios and mobile/desktop display sizes are available');
check(editor.imageCors('https://cdn.shopify.com/photo.jpg')&&editor.imageCors('https://storage.googleapis.com/bucket/photo.png')&&!editor.imageCors('https://cdn.shopify.com.example.test/photo.jpg'),'editor thumbnails use anonymous CORS only for supported image origins');
const board={width:2048,height:2048},rect=(left,top,width=100,height=80)=>({left,top,width,height});
let snap=editor.snapBounds(rect(174,270),[rect(177,70,333)],board,1);check(snap.dx===3&&snap.guides.some(g=>g.label==='Layer edge'),'nearest layer edge wins without accumulating multiple corrections');
snap=editor.snapBounds(rect(477,280),[],{width:1000,height:800},1);check(snap.dx===0,'outside the screen-pixel tolerance does not attract a layer');
snap=editor.snapBounds(rect(444,280),[],{width:1000,height:800},1);check(snap.dx===6,'canvas centers align with object centers');
snap=editor.snapBounds(rect(174,270),[rect(187,70,333)],board,.5);check(snap.dx===13,'zoomed-out snap tolerance is consistent in screen pixels');
snap=editor.snapBounds(rect(174,270),[rect(187,70,333)],board,2);check(snap.dx===0,'zooming in does not retain an oversized scene-pixel attraction radius');
snap=editor.snapBounds(rect(290,210),[rect(137,210),rect(449,210)],board,1);check(snap.dx===3&&snap.guides.some(g=>g.kind==='spacing'&&g.segments.every(([a,b])=>b-a===56)),'equal gaps are measured between neighboring layers');
snap=editor.snapBounds(rect(103,278),[],board,1);check(Math.abs(snap.dx+.6)<.001&&snap.guides.some(g=>g.label==='Safe margin'),'visible safe margins are real snap targets');
(async()=>{
  // Optional DOM/canvas integration harness. It executes the actual Fabric build,
  // editor controls and raster export using a test DOM, without accessing Google.
  if(process.env.BRITES_EDITOR_DOM_RUNTIME){
    const {JSDOM,VirtualConsole}=require(path.join(process.env.BRITES_EDITOR_DOM_RUNTIME,'jsdom'));const virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',error=>{if(!error.message.includes('Could not load img'))console.error(error);});
    const dom=new JSDOM('<!doctype html><body></body>',{virtualConsole,pretendToBeVisual:true,runScripts:'outside-only',resources:'usable',url:'https://example.test'}),w=dom.window;
    w.ResizeObserver=class{observe(){}disconnect(){}};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.confirm=()=>true;w.HTMLAnchorElement.prototype.click=function(){};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};Object.defineProperty(w.crypto,'subtle',{value:require('node:crypto').webcrypto.subtle});
    w.eval(fs.readFileSync(root+'/vendor/fabric-7.4.0.min.js','utf8'));w.eval(fs.readFileSync(root+'/brites-ad-editor.js','utf8'));
    const requests=[],docs=new Map(),exports=[],sharp=require('sharp');const photoUrl='data:image/png;base64,'+(await sharp({create:{width:2300,height:1700,channels:3,background:'#ab8348'}}).png().toBuffer()).toString('base64');const photo={id:'source_photo',width:2300,height:1700,url:photoUrl,title:'Duck original'};
    const request=async(action,input)=>{requests.push({action,input});const key=input.device+'|'+input.artboard?.key;if(action==='adDesignEditorState')return {ok:true,design:docs.get(key)||null,sources:[photo],exports:[],designs:[]};if(action==='adDesignEditorSource')return {ok:true,...photo};if(action==='saveAdDesignEditor'){const record={...input,revision:(docs.get(key)?.revision||0)+1,id:key};docs.set(key,record);return{ok:true,revision:record.revision};}if(action==='exportAdDesignEditor'){exports.push(input);return{ok:true,url:'https://example.test/art.jpg',format:input.format,bytes:Buffer.from(input.dataBase64,'base64').length,quality:100};}throw Error('Unexpected request '+action);};
    const e=await w.BritesAdEditor.open({title:'Duck Necklace',productId:'11',groupRef:'group',destination:'https://example.test/duck',deviceLinked:true,format:'square',photos:[{key:'photo',title:'Duck original',label:'Original photo',url:photoUrl,productId:'11',source:{kind:'product',productId:'11',imageId:'original'}}],copy:{headlines:['A Little Duck, All Yours'],descriptions:['Discover your own duck necklace.']},request});
    check(e.canvas.getObjects().length>=3,'template creates real editable typography and a CTA');check(e.device==='shared','desktop and mobile share artwork by default');
    const preserved=e.document();e.canvas.clear();e.setZoom(1);const reference=new w.fabric.Rect({left:177,top:70,width:333,height:70,strokeWidth:0}),moving=e.button('Shop now',{left:173,top:277},{width:120,height:45});e.canvas.add(reference,moving);e.canvas.setActiveObject(moving);e.canvas.fire('object:moving',{target:moving,e:{}});check(Math.abs(moving.getBoundingRect().left-177)<.001&&e.q('.bae-snap-guides line'),'real grouped button snaps to another layer and renders live SVG guides');
    check(!JSON.stringify(e.document()).includes('bae-snap-guides'),'live guides never enter the saved artwork');e.canvas.fire('mouse:up');check(!e.q('.bae-snap-guides').children.length,'guides clear immediately when the pointer is released');
    moving.set({left:174,top:277});moving.setCoords();e.canvas.fire('object:moving',{target:moving,e:{ctrlKey:true}});check(moving.left===174&&!e.q('.bae-snap-guides').children.length,'Ctrl/Cmd bypasses snapping while dragging');
    e.snap=false;e.canvas.fire('object:moving',{target:moving,e:{}});check(moving.left===174,'turning Snap off preserves free movement');e.snap=true;
    const other=e.button('Second',{left:400,top:500},{width:120,height:45});e.canvas.add(other);e.canvas.setActiveObject(new w.fabric.ActiveSelection([moving,other],{canvas:e.canvas}));const selection=e.canvas.getActiveObject(),beforeDistance=other.getXY().subtract(moving.getXY());e.canvas.fire('object:moving',{target:selection,e:{}});check(Math.abs(selection.getBoundingRect().left-177)<.001&&other.getXY().subtract(moving.getXY()).eq(beforeDistance),'multi-selection snaps as one unit without changing internal spacing');
    await e.restore(preserved);e.canvas.discardActiveObject();
    const thumb=w.document.createElement('img');thumb.src='data:image/png;base64,aW52YWxpZA==';e.dialog.appendChild(thumb);e.bindPhotoImage(thumb,{url:photoUrl,title:'Fallback photo'});await thumb.onerror();check(thumb.src===photoUrl,'a failed thumbnail automatically retries the original photo');thumb.remove();
    const image=e.canvas.getObjects().find(o=>o.type==='image');check(image&&image.getElement().naturalWidth===2300,'real original photo loads into the canvas at full pixel resolution');e.canvas.setActiveObject(image);e.property(image,'fx_brightness','.1','range');e.property(image,'sourceWidth',String(image.width-200),'number');e.property(image,'cropX','100','number');e.changed();check(image.filters.length===1&&image.cropX===100,'photo effects and crop operate on the actual original image');
    await e.action('add-text');const t=e.canvas.getActiveObject();e.property(t,'text','A thoughtful duck gift','text');e.property(t,'fontSize','74','number');e.property(t,'textFill','#884422','color');e.changed();check(t.text==='A thoughtful duck gift'&&t.fontSize===74&&t.fill==='#884422','text controls affect actual Fabric objects');
    await e.action('duplicate');check(e.canvas.getActiveObject().text===t.text&&e.canvas.getObjects().filter(o=>o.text===t.text).length===2,'duplicate retains text formatting');await e.action('undo');check(e.canvas.getObjects().filter(o=>o.text===t.text).length===1,'undo restores the prior layer document');await e.action('redo');check(e.canvas.getObjects().filter(o=>o.text===t.text).length===2,'redo restores the duplicated layer');
    await e.action('add-button');let button=e.canvas.getActiveObject();e.property(button,'text','Choose your charm','text');e.property(button,'fill','#113355','color');e.property(button,'radius','18','number');check(button.getObjects()[1].text==='Choose your charm'&&button.getObjects()[0].fill==='#113355','button label, fill and corners update the composed CTA');const buttonFont=button.getObjects()[1].fontSize;e.property(button,'widthPixels','800','number');check(button.getObjects()[1].fontSize===buttonFont&&button.getObjects()[0].width===800,'button width reflows its label without stretching the font');
    e.canvas.discardActiveObject();const selected=e.canvas.getObjects().slice(-2);e.canvas.setActiveObject(new w.fabric.ActiveSelection(selected,{canvas:e.canvas}));await e.action('group');check(e.canvas.getActiveObject().getObjects().length===2,'selected layers form an editable group');await e.action('ungroup');check(!e.canvas.getActiveObject(),'ungroup restores individual layers');
    await e.action('save');check(docs.has('shared|square')&&!JSON.stringify(docs.get('shared|square')).includes('expired.example'),'editable artwork is saved by device and size');
    await e.switchBoard('display_300x250','mobile');check(e.board.width===300&&e.device==='mobile','mobile display artboard is independent');check(e.drafts.has('shared|square|2048|2048'),'original artboard is retained while editing another size');
    e.exportPanel();e.q('[data-export-format]').value='jpeg';e.q('[data-export-optimize]').checked=false;await e.q('[data-export-do]').onclick();check(exports.length===1,'export sends an actual composed raster');const meta=await sharp(Buffer.from(exports[0].dataBase64,'base64')).metadata();check(meta.width===300&&meta.height===250,'export uses exact artboard pixels independent of preview zoom');
    await e.switchBoard('square','shared');check(e.canvas.getObjects().some(o=>o.text==='A thoughtful duck gift'),'returning to the master artboard restores its own text');
    const realRequest=e.options.request,parts=new Map(),payload=Buffer.alloc(5*1024*1024,123).toString('base64');let retries=0,completed=false;
    e.options.request=async(action,input)=>{if(action!=='exportAdDesignEditor')return realRequest(action,input);if(input.phase==='start'){check(input.bytes===5*1024*1024&&/^[a-f0-9]{64}$/.test(input.sha256),'large export begins with exact byte length and SHA-256');return {ok:true,uploadId:'upload',chunkBytes:1536*1024};}if(input.phase==='chunk'){if(input.index===1&&!retries++)throw Error('Temporary connection loss');parts.set(input.index,input.dataBase64);return {ok:true};}if(input.phase==='complete'){completed=true;return {ok:true,url:'https://example.test/large.png'};}throw Error('Large export must not use a single request');};
    await e.uploadExport(payload,'png',false);check(completed&&retries===2&&[...parts].sort((a,b)=>a[0]-b[0]).map(p=>p[1]).join('')===payload,'large PNG upload retries a failed part and preserves every original byte');check([...parts.values()].every(p=>p.length<=2*1024*1024),'each upload stays safely below the function request limit');e.options.request=realRequest;
    check(e.filename('json').endsWith('.json'),'recovery files have the correct editable JSON extension');
    await e.action('save');await e.dispose();dom.window.close();
  }
  console.log('PASS '+checks+' professional editor source, layout, save and export checks');
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
