const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),editor=require(root+'/brites-ad-editor.js');
// Every failed check is also recorded: a check inside a request fake throws into editor code that may catch it,
// so the suite asserts afterwards that nothing failed there.
let checks=0;const failed=[];const check=(v,m)=>{if(!v)failed.push(m);assert.ok(v,m);checks++};
{const source=fs.readFileSync(root+'/brites-ad-editor.js','utf8');check(!/confirm\(/.test(source)&&!/[✦\u{1F512}]/u.test(source),'the editor asks in place (no confirm()) and shows no decorative star or lock glyphs');}
const review=editor.reviewSummary({rubric:'complete-ad-v1',score:93.2,scores:{messaging:94,layout:89,relevance:95,visualAppeal:95,productRecognition:95},issues:['Tall formats leave empty margins.']});
check(review.tone==='green'&&review.score===93.2&&review.complete,'saved set score remains exact and green at target');
check(review.categories.length===5&&review.synopsis==='Focus on layout.'&&review.suggestions.length===1,'review provides concise category feedback and relevant suggestions');
check(editor.reviewSummary({score:91.9}).tone==='orange'&&editor.reviewSummary({score:79}).tone==='red','score colors distinguish below-target and low reviews');
check(editor.reviewSummary(null).score===null&&editor.reviewSummary(null).tone==='neutral','missing review does not appear as zero or a passing score');
check(editor.reviewSummary({score:84},97).synopsis.includes('needs changes'),'legacy score cannot imply passing categories');
check(editor.reviewSummary({score:0}).score===0,'valid zero score remains visible');
check(!editor.reviewSummary({rubric:'product-detail-v1',score:95}).complete,'earlier photograph score is not labeled a complete set review');
const original={version:'7.4.0',objects:[{type:'Group',left:80,top:40,scaleX:1,scaleY:1,objects:[{type:'Image',sourceKey:'source_1',src:'https://expired.example/image',crossOrigin:'anonymous'},{type:'Textbox',text:'Duck necklace',fontFamily:'Georgia'}]}]};
const saved=editor.withoutUrls(original);check(!JSON.stringify(saved).includes('expired.example'),'editable document keeps source keys rather than expiring image URLs');
const restored=editor.withSources(saved,[{id:'source_1',url:'https://saved.example/fresh'}]);check(restored.objects[0].objects[0].src==='https://saved.example/fresh','images nested in groups receive refreshed source URLs');
assert.throws(()=>editor.withSources(saved,[]),/original image/);checks++;
const wide=editor.adapt(saved,{width:400,height:400},{width:800,height:400});check(wide.objects[0].left===160&&wide.objects[0].scaleX===wide.objects[0].scaleY,'new artboards preserve object proportions');check(saved.objects[0].left===80,'resizing does not mutate the original artboard');
check(editor.formats.filter(f=>f.category==='Master artwork').length===3&&editor.formats.some(f=>f.width===320&&f.height===50)&&editor.formats.some(f=>f.width===300&&f.height===600),'all three master ratios and mobile/desktop display sizes are available');
check(editor.imageCors('https://cdn.shopify.com/photo.jpg')&&editor.imageCors('https://storage.googleapis.com/bucket/photo.png')&&!editor.imageCors('https://cdn.shopify.com.example.test/photo.jpg'),'editor thumbnails use anonymous CORS only for supported image origins');
const board={width:2048,height:2048},rect=(left,top,width=100,height=80)=>({left,top,width,height});
let snap=editor.snapBounds(rect(174,270),[rect(177,70,333)],board,1);check(snap.dx===3&&snap.guides.some(g=>g.label==='Layer edge'),'nearest layer edge wins without accumulating multiple corrections');
snap=editor.snapBounds(rect(477,280),[],{width:1000,height:800},1);check(snap.dx===0,'outside the screen-pixel tolerance does not attract a layer');
snap=editor.snapBounds(rect(444,280),[],{width:1000,height:800},1);check(snap.dx===6,'canvas centers align with object centers');
snap=editor.snapBounds(rect(174,270),[rect(187,70,333)],board,.5);check(snap.dx===13,'zoomed-out snap tolerance is consistent in screen pixels');
snap=editor.snapBounds(rect(174,270),[rect(187,70,333)],board,2);check(snap.dx===0,'zooming in does not retain an oversized scene-pixel attraction radius');
snap=editor.snapBounds(rect(290,210),[rect(137,210),rect(449,210)],board,1);check(snap.dx===3&&snap.guides.some(g=>g.kind==='spacing'&&g.segments.every(([a,b])=>b-a===56)),'equal gaps are measured between neighboring layers');
snap=editor.snapBounds(rect(103,278),[],board,1);check(Math.abs(snap.dx+.6)<.001&&snap.guides.some(g=>g.label==='Safe margin'),'visible safe margins are real snap targets');
const cropBounds={width:1200,height:900},cropBox={x:200,y:200,width:400,height:300};
for(const ratio of [0,1,1.91,.8])for(const handle of ['nw','n','ne','e','se','s','sw','w','move'])for(const delta of [-2000,30,2000]){
 const start=editor.cropFit(cropBox,cropBounds,ratio),r=editor.cropResize(start,handle,delta,-delta,cropBounds,ratio);
 assert(r.x>=0&&r.y>=0&&r.width>0&&r.height>0&&r.x+r.width<=1200.00001&&r.y+r.height<=900.00001,handle+' stays inside original pixels');
 if(ratio)assert(Math.abs(r.width/r.height-ratio)<.00001,handle+' preserves its selected ratio');
}
check(true,'all eight crop handles and movement preserve source bounds and locked ratios');
assert.deepEqual(editor.cropResize(cropBox,'se',120,80,cropBounds),{x:200,y:200,width:520,height:380});checks++;
(async()=>{
  // Optional DOM/canvas integration harness. It executes the actual Fabric build,
  // editor controls and raster export using a test DOM, without accessing Google.
  if(process.env.BRITES_EDITOR_DOM_RUNTIME){
    const {JSDOM,VirtualConsole}=require(path.join(process.env.BRITES_EDITOR_DOM_RUNTIME,'jsdom'));const virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',error=>{if(!error.message.includes('Could not load img'))console.error(error);});
    const dom=new JSDOM('<!doctype html><body></body>',{virtualConsole,pretendToBeVisual:true,runScripts:'outside-only',resources:'usable',url:'https://example.test'}),w=dom.window;
    const observers=[];w.ResizeObserver=class{constructor(callback){this.callback=callback;this.targets=[];observers.push(this);}observe(target){this.targets.push(target);}disconnect(){this.targets=[];}};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.confirm=()=>true;w.HTMLAnchorElement.prototype.click=function(){};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};Object.defineProperty(w.crypto,'subtle',{value:require('node:crypto').webcrypto.subtle});
    w.eval(fs.readFileSync(root+'/vendor/fabric-7.4.0.min.js','utf8'));w.eval(fs.readFileSync(root+'/brites-ad-editor.js','utf8'));
    const requests=[],docs=new Map(),copies=new Map(),exports=[],sharp=require('sharp');const photoUrl='data:image/png;base64,'+(await sharp({create:{width:2300,height:1700,channels:3,background:'#ab8348'}}).png().toBuffer()).toString('base64');const photo={id:'source_photo',width:2300,height:1700,url:photoUrl,title:'Duck original'};
    // No AI design is ever started through this fake, so the server's answer to an AI status read (one artboard with its
    // original, or the whole set's review) is the idle state. A request the fake does not answer fails the suite at the end.
    const unanswered=[],aiStatusReads=[];
    const request=async(action,input)=>{requests.push({action,input});const key=input.device+'|'+input.artboard?.key;if(action==='adDesignEditorAIStatus'&&!input.jobId&&!input.activeAttempt&&(input.allSizes||input.artboard)){aiStatusReads.push(input.allSizes?'set':'artboard');check(input.productId==='11'&&input.groupRef==='group','AI status reads stay on this product and ad group');return {ok:true,jobId:null,phase:'idle',result:null};}if(action==='adDesignEditorState')return {ok:true,design:docs.get(key)||null,sources:[photo],exports:[],designs:[]};if(action==='adDesignEditorSource')return {ok:true,...photo};if(action==='saveAdDesignEditor'){const record={...input,revision:(docs.get(key)?.revision||0)+1,id:key};docs.set(key,record);return{ok:true,revision:record.revision};}if(action==='adDesignSavedDesigns')return {ok:true,savedDesigns:[...copies.values()]};if(action==='openAdDesignSavedDesign')return {ok:true,design:copies.get(input.id),sources:[photo]};if(action==='deleteAdDesignSavedDesign'){copies.delete(input.id);return {ok:true};}if(action==='exportAdDesignEditor'){if(input.saveDesignId)copies.set(input.saveDesignId,{...docs.get(key),id:input.saveDesignId,url:photoUrl,thumbnailUrl:photoUrl,createdAt:Date.now()});else exports.push(input);return{ok:true,url:'https://example.test/art.jpg',format:input.format,bytes:Buffer.from(input.dataBase64,'base64').length,quality:100};}unanswered.push(action);throw Error('Unexpected request '+action);};
    const e=await w.BritesAdEditor.open({title:'Duck Necklace',productId:'11',groupRef:'group',destination:'https://example.test/duck',deviceLinked:true,format:'square',photos:[{key:'photo',title:'Duck original',label:'Original photo',url:photoUrl,productId:'11',source:{kind:'product',productId:'11',imageId:'original'}}],copy:{headlines:['A Little Duck, All Yours'],descriptions:['Discover your own duck necklace.']},request});
    const previewCount=w.document.querySelectorAll('dialog').length,previewOriginal=JSON.stringify(e.document()),previewImages=await w.BritesAdEditor.previewSaved({design:{document:e.document(),artboard:e.board,device:'shared'},sources:[photo]});
    check(Object.keys(previewImages).length===6&&Object.values(previewImages).every(p=>p.url.startsWith('data:image/png;base64,')),'saved preview renders all device and master aspect ratios');check(w.document.querySelectorAll('dialog').length===previewCount&&JSON.stringify(e.document())===previewOriginal,'rendering saved previews never opens or changes an editor');
    const reviewFeedback=e.aiFeedback({mode:'design',error:'Short error',quality:{score:94,pass:false,productFaithful:false,mobileReadable:true,issues:['Ring changed','<unsafe> complete finding']}});check(reviewFeedback.includes('94/100')&&reviewFeedback.includes('complete finding')&&reviewFeedback.includes('&lt;unsafe&gt;')&&reviewFeedback.includes(' open'),'failed quality score and complete escaped findings remain visible');
    check(e.canvas.getObjects().length>=3,'template creates real editable typography and a CTA');check(e.device==='shared','desktop and mobile share artwork by default');
    const preserved=e.document();e.canvas.clear();e.setZoom(1);const reference=new w.fabric.Rect({left:177,top:70,width:333,height:70,strokeWidth:0}),moving=e.button('Shop now',{left:173,top:277},{width:120,height:45});e.canvas.add(reference,moving);e.canvas.setActiveObject(moving);e.canvas.fire('object:moving',{target:moving,e:{}});check(Math.abs(moving.getBoundingRect().left-177)<.001&&e.q('.bae-snap-guides line'),'real grouped button snaps to another layer and renders live SVG guides');
    check(!JSON.stringify(e.document()).includes('bae-snap-guides'),'live guides never enter the saved artwork');e.canvas.fire('mouse:up');check(!e.q('.bae-snap-guides').children.length,'guides clear immediately when the pointer is released');
    moving.set({left:174,top:277});moving.setCoords();e.canvas.fire('object:moving',{target:moving,e:{ctrlKey:true}});check(moving.left===174&&!e.q('.bae-snap-guides').children.length,'Ctrl/Cmd bypasses snapping while dragging');
    e.snap=false;e.canvas.fire('object:moving',{target:moving,e:{}});check(moving.left===174,'turning Snap off preserves free movement');e.snap=true;
    const other=e.button('Second',{left:400,top:500},{width:120,height:45});e.canvas.add(other);e.canvas.setActiveObject(new w.fabric.ActiveSelection([moving,other],{canvas:e.canvas}));const selection=e.canvas.getActiveObject(),beforeDistance=other.getXY().subtract(moving.getXY());e.canvas.fire('object:moving',{target:selection,e:{}});check(Math.abs(selection.getBoundingRect().left-177)<.001&&other.getXY().subtract(moving.getXY()).eq(beforeDistance),'multi-selection snaps as one unit without changing internal spacing');
    await e.restore(preserved);e.canvas.discardActiveObject();
    const thumb=w.document.createElement('img');thumb.src='data:image/png;base64,aW52YWxpZA==';e.dialog.appendChild(thumb);e.bindPhotoImage(thumb,{url:photoUrl,title:'Fallback photo'});await thumb.onerror();check(thumb.src===photoUrl,'a failed thumbnail automatically retries the original photo');thumb.remove();
    const image=e.canvas.getObjects().find(o=>o.type==='image');check(image&&image.getElement().naturalWidth===2300,'real original photo loads into the canvas at full pixel resolution');e.canvas.setActiveObject(image);e.property(image,'fx_brightness','.1','range');e.property(image,'sourceWidth',String(image.width-200),'number');e.property(image,'cropX','100','number');e.changed();check(image.filters.length===1&&image.cropX===100,'photo effects and crop operate on the actual original image');
    const tick=()=>new Promise(resolve=>setTimeout(resolve,10));
    await tick();check(aiStatusReads.includes('artboard')&&aiStatusReads.includes('set')&&e.q('[data-review-score]').title.startsWith('Last saved review'),'opening the editor reads its AI state and the saved set review, both idle, with no load error');
    const cropPromise=w.BritesAdEditor.crop({url:photoUrl,ratioKey:'free',rect:{x:.1,y:.1,width:.5,height:.5}}),crop=w.document.querySelector('.bc-dialog'),stage=crop.querySelector('.bc-stage'),cropSelection=crop.querySelector('.bc-selection');
    stage.getBoundingClientRect=()=>({left:0,top:0,width:230,height:170});
    for(let tries=0;crop.querySelector('[data-crop-apply]').disabled&&tries<100;tries++)await tick();
    check(!crop.querySelector('[data-crop-apply]').disabled&&crop.querySelectorAll('[data-crop-handle]').length===8,'crop opens with the original image and eight usable resize handles');
    const pointer=(target,type,x,y)=>stage['on'+type]({target,button:0,pointerId:1,clientX:x,clientY:y,preventDefault(){}});
    pointer(cropSelection,'pointerdown',40,40);pointer(stage,'pointermove',60,50);pointer(stage,'pointerup',60,50);
    check(Math.abs(parseFloat(cropSelection.style.left)-(430/2300*100))<.001,'dragging the crop selection moves it in original image pixels');
    pointer(crop.querySelector('[data-crop-handle=se]'),'pointerdown',150,100);pointer(stage,'pointermove',170,110);pointer(stage,'pointerup',170,110);
    check(Math.abs(parseFloat(cropSelection.style.width)-(1350/2300*100))<.001,'corner resize changes the selected source region without moving the image');
    const ratioControl=crop.querySelector('[data-crop-ratio]');ratioControl.value='portrait';ratioControl.dispatchEvent(new w.Event('change',{bubbles:true}));cropSelection.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',shiftKey:true,bubbles:true}));crop.querySelector('[data-crop-apply]').click();
    const cropResult=await cropPromise;check(Math.abs(cropResult.pixels.width/cropResult.pixels.height-1638/2048)<.00001&&cropResult.ratioKey==='portrait'&&!w.document.querySelector('.bc-dialog'),'Apply returns the exact selected ratio and closes the crop');
    image.set({angle:24,flipX:true});const pixel={x:700,y:650},pixelPosition=o=>w.fabric.util.transformPoint(new w.fabric.Point(pixel.x-o.cropX-o.width/2,pixel.y-o.cropY-o.height/2),o.calcTransformMatrix()),beforeCrop=pixelPosition(image);w.BritesAdEditor.cropLayer(image,cropResult.rect,w.fabric);const afterCrop=pixelPosition(image);
    check(beforeCrop.distanceFrom(afterCrop)<.00001&&image.angle===24&&image.flipX,'cropping a rotated or flipped layer retains its scale and the scene position of original pixels');
    const beforeCancel=JSON.stringify(e.document()),cancelled=w.BritesAdEditor.crop({url:photoUrl});w.document.querySelector('[data-crop-cancel]').click();check(await cancelled===null&&JSON.stringify(e.document())===beforeCancel,'Cancel leaves every editable layer unchanged');
    // Inside the editor the crop replaces the canvas as a view, never a pop-up on the editor; Escape, Back and Cancel return to Crop.
    e.canvas.setActiveObject(image);e.renderInspector();const cropButton=e.q('[data-action="photo-crop"]'),cropView=e.q('.bae-view'),dialogsBeforeCrop=w.document.querySelectorAll('dialog').length,beforeViewCrop=JSON.stringify(e.document());cropButton.focus();
    let viewCrop=e.action('photo-crop',cropButton),inlineCrop=cropView.querySelector('.bc-inline');
    check(inlineCrop&&!cropView.hidden&&cropView.classList.contains('bae-view-fill')&&e.q('[data-view-title]').textContent==='Crop'&&!w.document.querySelector('.bc-dialog')&&w.document.querySelectorAll('dialog').length===dialogsBeforeCrop&&!e.busy&&w.document.activeElement===e.q('[data-action="view-back"]'),'in the editor Crop opens as a view in place of the canvas, with Back to editor focused and the editor not busy');
    check(!inlineCrop.querySelector('.bc-toolbar b')&&inlineCrop.querySelector('.bc-toolbar label').textContent.startsWith('Aspect ratio')&&[...inlineCrop.querySelectorAll('.bc-toolbar button')].map(b=>b.textContent).join('|')==='Reset|Cancel|Apply crop'&&inlineCrop.querySelectorAll('[data-crop-handle]').length===8&&inlineCrop.querySelector('.bc-message').textContent==='Loading image…'&&inlineCrop.querySelector('.bc-message').hasAttribute('data-loading'),'the crop view keeps every crop control and its wording, and shows a spinner while the photo loads');
    const toolCss=w.document.getElementById('britesEditorStyles').textContent;check(toolCss.includes('.bae-view .bc-toolbar label{flex-direction:row;color:inherit}')&&toolCss.includes('@media(max-width:620px){.bae-view .bc-toolbar{display:grid;')&&toolCss.includes('grid-template-areas:"ratio ratio reset" "size cancel apply"'),'inside the editor the crop toolbar keeps its own look and, on phones, fits in two rows with Apply crop in view');
    // The floating status notice: its dismiss button is a 32 px target, and on desktop the notice sits over the canvas column
    // (the right column's width plus its 18 px inset from the right, and no wider than that column), clear of the side panels' text.
    const columns=[...toolCss.matchAll(/\.bae-work\{(?:display:grid;)?grid-template-columns:(\d+)px minmax\(\d+px,1fr\) (\d+)px/g)].map(m=>[+m[1],+m[2]]),anchors=[...toolCss.matchAll(/@media\(min-width:781px\)((?: and \(max-width:1100px\))?)\{\.bae:not\(\.bae-viewing\)>\.bae-status\{right:(\d+)px;max-width:min\(620px,calc\(100% - (\d+)px\)\)\}\}/g)].map(m=>[!!m[1],+m[2],+m[3]]);
    check(toolCss.includes('.bae-status [data-action=dismiss-status]{min-width:32px;min-height:32px}')&&e.dialog.querySelector('.bae-status [data-action="dismiss-status"]'),'the status notice can be dismissed with a 32 px target');
    check(columns.length===2&&anchors.length===2&&[[false,columns[0]],[true,columns[1]]].every(([narrow,[left,right]])=>anchors.some(a=>a[0]===narrow&&a[1]===right+18&&a[2]===left+right+36)),'on desktop the status notice floats over the canvas column, clear of the photo and property panels');
    // On phones the photo and property panels open as drawers down the editor and the notice floats at its foot: while the
    // notice shows, the editor keeps room for it (8 px clear of it) and an open drawer ends above that room, so the notice
    // never covers a drawer's last lines. The drawer takes the room at once and eases back down when the notice hides.
    const note=e.q('.bae-status'),noteWatch=observers.find(o=>o.targets.includes(note)),noteRoom=()=>e.dialog.style.getPropertyValue('--bae-status-space'),noteWasHidden=note.hidden;
    note.getClientRects=()=>note.hidden?[]:[{}];note.getBoundingClientRect=()=>({top:700,bottom:780});e.dialog.getBoundingClientRect=()=>({top:0,bottom:844});
    note.hidden=false;noteWatch?.callback([]);const roomShown=noteRoom();note.hidden=true;noteWatch?.callback([]);const roomHidden=noteRoom();
    note.hidden=noteWasHidden;delete note.getClientRects;delete note.getBoundingClientRect;delete e.dialog.getBoundingClientRect;
    const drawerBottoms=[...toolCss.matchAll(/\.bae\[data-panel=photos\] \.bae-left,\.bae\[data-panel=properties\] \.bae-right\{[^}]*?bottom:([^;}]+)/g)].map(m=>m[1]);
    check(noteWatch&&roomShown==='152px'&&roomHidden==='0px'&&drawerBottoms.at(-1)==='var(--bae-status-space,0px)','on phones an open photo or property drawer ends 8 px above the status notice while it shows, and at the foot again once it hides');
    check(toolCss.includes('bottom:var(--bae-status-space,0px);transition:bottom .2s cubic-bezier(.2,.7,.3,1)}.bae:has(>.bae-status:not([hidden])) .bae-left,.bae:has(>.bae-status:not([hidden])) .bae-right{transition:none}}@media(prefers-reduced-motion:reduce){.bae[data-panel] .bae-left,.bae[data-panel] .bae-right{transition:none}}'),'the drawer makes room for the notice at once and eases back down when it hides, with no motion under reduced motion');
    e.dialog.dispatchEvent(new w.Event('cancel',{cancelable:true}));await viewCrop;check(cropView.hidden&&!inlineCrop.isConnected&&!cropView.classList.contains('bae-view-fill')&&!e.dialog.classList.contains('bae-viewing')&&!e.disposed&&w.document.activeElement===cropButton&&JSON.stringify(e.document())===beforeViewCrop,'Escape leaves the photo uncropped and returns to the Crop button');
    viewCrop=e.action('photo-crop',cropButton);e.q('[data-action="view-back"]').click();await viewCrop;check(cropView.hidden&&!e.q('.bc-inline')&&w.document.activeElement===cropButton&&JSON.stringify(e.document())===beforeViewCrop,'Back to editor leaves the crop the same way');
    viewCrop=e.action('photo-crop',cropButton);e.q('.bc-inline [data-crop-cancel]').click();await viewCrop;check(cropView.hidden&&w.document.activeElement===cropButton&&JSON.stringify(e.document())===beforeViewCrop,'Cancel in the crop view returns to the canvas unchanged');
    viewCrop=e.action('photo-crop',cropButton);inlineCrop=e.q('.bc-inline');const applyInView=inlineCrop.querySelector('[data-crop-apply]');for(let tries=0;applyInView.disabled&&tries<100;tries++)await tick();
    const ratioInView=inlineCrop.querySelector('[data-crop-ratio]');ratioInView.value='square';ratioInView.dispatchEvent(new w.Event('change',{bubbles:true}));applyInView.click();await viewCrop;
    check(Math.abs(image.width/image.height-1)<.01&&cropView.hidden&&!e.dialog.classList.contains('bae-viewing')&&e.q('[data-status]').textContent==='Crop applied.'&&w.document.activeElement===e.q('[data-action="photo-crop"]'),'Apply crop in the view crops the layer, returns to the canvas and focuses Crop again');
    await e.action('add-text');const t=e.canvas.getActiveObject();e.property(t,'text','A thoughtful duck gift','text');e.property(t,'fontSize','74','number');e.property(t,'textFill','#884422','color');e.changed();check(t.text==='A thoughtful duck gift'&&t.fontSize===74&&t.fill==='#884422','text controls affect actual Fabric objects');
    await e.action('duplicate');check(e.canvas.getActiveObject().text===t.text&&e.canvas.getObjects().filter(o=>o.text===t.text).length===2,'duplicate retains text formatting');await e.action('undo');check(e.canvas.getObjects().filter(o=>o.text===t.text).length===1,'undo restores the prior layer document');await e.action('redo');check(e.canvas.getObjects().filter(o=>o.text===t.text).length===2,'redo restores the duplicated layer');
    await e.action('add-button');let button=e.canvas.getActiveObject();e.property(button,'text','Choose your charm','text');e.property(button,'fill','#113355','color');e.property(button,'radius','18','number');check(button.getObjects()[1].text==='Choose your charm'&&button.getObjects()[0].fill==='#113355','button label, fill and corners update the composed CTA');const buttonFont=button.getObjects()[1].fontSize;e.property(button,'widthPixels','800','number');check(button.getObjects()[1].fontSize===buttonFont&&button.getObjects()[0].width===800,'button width reflows its label without stretching the font');
    e.canvas.discardActiveObject();const selected=e.canvas.getObjects().slice(-2);e.canvas.setActiveObject(new w.fabric.ActiveSelection(selected,{canvas:e.canvas}));await e.action('group');check(e.canvas.getActiveObject().getObjects().length===2,'selected layers form an editable group');await e.action('ungroup');check(!e.canvas.getActiveObject(),'ungroup restores individual layers');
    await e.action('save');const firstCopy=[...copies.keys()][0];await e.action('save');check(copies.size===2&&e.savedCopies.length===2,'each Save Design creates a new visible copy');check(docs.has('shared|square')&&!JSON.stringify(docs.get('shared|square')).includes('expired.example'),'editable artwork is saved by device and size');
    await e.switchBoard('display_300x250','mobile');check(e.board.width===300&&e.device==='mobile','mobile display artboard is independent');check(e.drafts.has('shared|square|2048|2048'),'original artboard is retained while editing another size');
    e.exportPanel();e.q('[data-export-format]').value='jpeg';e.q('[data-export-optimize]').checked=false;await e.q('[data-export-do]').onclick();check(exports.length===1,'export sends an actual composed raster');const meta=await sharp(Buffer.from(exports[0].dataBase64,'base64')).metadata();check(meta.width===300&&meta.height===250,'export uses exact artboard pixels independent of preview zoom');
    await e.switchBoard('square','shared');check(e.canvas.getObjects().some(o=>o.text==='A thoughtful duck gift'),'returning to the master artboard restores its own text');
    const realRequest=e.options.request,parts=new Map(),payload=Buffer.alloc(5*1024*1024,123).toString('base64');let retries=0,completed=false;
    e.options.request=async(action,input)=>{if(action!=='exportAdDesignEditor')return realRequest(action,input);if(input.phase==='start'){check(input.bytes===5*1024*1024&&/^[a-f0-9]{64}$/.test(input.sha256),'large export begins with exact byte length and SHA-256');return {ok:true,uploadId:'upload',chunkBytes:1536*1024};}if(input.phase==='chunk'){if(input.index===1&&!retries++)throw Error('Temporary connection loss');parts.set(input.index,input.dataBase64);return {ok:true};}if(input.phase==='complete'){completed=true;return {ok:true,url:'https://example.test/large.png'};}throw Error('Large export must not use a single request');};
    await e.uploadExport(payload,'png',false);check(completed&&retries===2&&[...parts].sort((a,b)=>a[0]-b[0]).map(p=>p[1]).join('')===payload,'large PNG upload retries a failed part and preserves every original byte');check([...parts.values()].every(p=>p.length<=2*1024*1024),'each upload stays safely below the function request limit');e.options.request=realRequest;
    e.canvas.discardActiveObject();const beforeRecovery=e.document(),capture=JSON.parse(JSON.stringify(beforeRecovery));
    const edited=e.canvas.getObjects().find(o=>'text'in o);edited.set('text','My newer draft');e.markDirty();e.snapshot();const newer=JSON.stringify(e.document());
    const reviewed=JSON.parse(JSON.stringify(capture));reviewed.objects.find(o=>'text'in o).text='Reviewed necklace';
    const recoveredRun={key:e.key(),scope:e.input(),original:capture,fingerprint:JSON.stringify(capture),mode:'design',jobId:'saved-reviewed',result:{document:reviewed,productId:'11',groupRef:'group',device:e.device,artboard:{...e.board},sources:[photo]},error:'Different draft'};
    e.aiRuns.set(e.key(),recoveredRun);const beforeRequests=requests.length;
    await assert.rejects(()=>e.applyAI(recoveredRun),/different draft/i);check(JSON.stringify(e.document())===newer,'automatic apply still protects newer artwork');
    check(e.aiFeedback(recoveredRun).includes('ai-restore-apply')&&e.aiFeedback(recoveredRun).includes('Use reviewed design'),'conflict offers a direct saved-result recovery action');
    await e.action('ai-restore-apply');check(recoveredRun.applied&&e.canvas.getObjects().some(o=>o.text==='Reviewed necklace'),'explicit recovery applies the already-reviewed result');check(requests.length===beforeRequests,'recovery never generates or reviews again');
    await e.action('undo');check(JSON.stringify(e.document())===newer,'one Undo restores the newer draft instead of the old capture');
    e.canvas.getObjects().find(o=>'text'in o).locked=true;const lockedDraft=JSON.stringify(e.document());await assert.rejects(()=>e.restoreCapturedAI(true),/Unlock/);check(JSON.stringify(e.document())===lockedDraft,'recovery preserves newly locked layers');
    e.aiRuns.delete(e.key());await e.restore(beforeRecovery);e.snapshot();
    const liveBoard=e.board,liveScope=JSON.stringify(e.input()),liveArtwork=JSON.stringify(e.document()),loadFonts=e.loadFonts,oldEngine=w.BritesAdResponsive;
    let stableDuringProof=true;
    e.loadFonts=async function(doc){await Promise.resolve();stableDuringProof&&=this.board===liveBoard&&JSON.stringify(this.input())===liveScope;return loadFonts.call(this,doc);};
    w.BritesAdResponsive={layoutVersion:1,variants:[]};
    const proofDoc=e.document(),tinyDoc=JSON.parse(JSON.stringify(proofDoc));for(const o of tinyDoc.objects){o.left*=.04;o.top*=.04;o.scaleX*=.04;o.scaleY*=.04;}
    const proofs=await e.renderAIProofs({artboard:{...liveBoard},device:e.device,document:proofDoc,sources:[photo],responsive:{layoutVersion:1,variants:[{key:'tiny',device:'mobile',width:300,height:100}],documents:[{key:'tiny',device:'mobile',width:300,height:100,document:tinyDoc}]}});
    check(proofs.length===2&&stableDuringProof&&JSON.stringify(e.document())===liveArtwork,'asynchronous size proofs never change the active editor scope or artwork');
    e.loadFonts=loadFonts;w.BritesAdResponsive=oldEngine;
    const reorder=v=>Array.isArray(v)?v.map(reorder):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).reverse().map(k=>[k,reorder(v[k])])):v;
    const orderedCapture=e.document(),orderedRun={...recoveredRun,original:reorder(orderedCapture),fingerprint:JSON.stringify(reorder(orderedCapture)),applied:false};
    await e.applyAI(orderedRun);check(e.canvas.getObjects().some(o=>o.text==='Reviewed necklace'),'storage property reordering does not falsely reject an unchanged draft');
    await e.restore(beforeRecovery);e.snapshot();
    check(e.q('[data-action="ai-review-proofs"]').textContent==='Preview all sizes','persistent gallery button is outside transient AI feedback');
    await w.BritesAdEditor.openAllSizes({scope:{workspaceId:'test',productId:'11',groupRef:'group'},request:async(action,input)=>{check(action==='adDesignEditorAIStatus'&&input.includeReview&&input.allSizes,'standalone gallery only reads saved review');return {reviewProofs:[{key:'desktop_square',url:photoUrl,width:2048,height:2048}]};}});
    const gallery=w.document.querySelector('dialog[aria-label="Reviewed ad layouts"]');check(!!gallery&&gallery.querySelectorAll('figure').length===1,'main-window preview opens the gallery without another editor');
    const editorCss=w.document.getElementById('britesEditorStyles').textContent;check(gallery.classList.contains('bae-sheet')&&e.dialog.matches('dialog.bae')&&editorCss.includes('dialog.bae[open],dialog.bae-sheet[open]{animation:baeIn .2s ease-out}')&&editorCss.includes('@media(prefers-reduced-motion:reduce){dialog.bae[open],dialog.bae-sheet[open]{animation:none}}'),'the editor and All ad sizes dialogs ease in over 200 ms, with no motion when reduced motion is requested');
    const phone=editorCss.slice(editorCss.indexOf('@media(max-width:780px){.bae-header{position:relative'));check(/\.bae-header\{position:relative;grid-template-columns:minmax\(0,1fr\);height:auto/.test(phone)&&phone.includes('.bae-actions{flex-wrap:nowrap')&&phone.includes('.bae-actions [data-action=close]{position:absolute')&&phone.includes('.bae-toolbar button,.bae-toolbar select{min-height:32px;min-width:32px}')&&phone.includes('.bae-toolbar label:has(input[type=checkbox]){min-height:32px}'),'on phones the actions sit in one row under the name, Done stays in reach and toolbar controls are 32 px touch targets');gallery.querySelector('[data-close]').click();
    // Below 1000 px the actions use their short names, so the name field keeps the free width and phones keep one row of actions.
    check(editorCss.includes('@media(max-width:1000px){.bae-long{display:none}.bae-cap{text-transform:capitalize}}')&&e.q('[data-action="ai-review-proofs"] .bae-long').textContent==='Preview '&&e.q('[data-action="save"]').textContent==='Save Design'&&e.q('[data-action="save"] .bae-long').textContent===' Design'&&e.q('[data-action="export-panel"]').textContent==='Export artwork'&&e.q('[data-action="export-panel"] .bae-long').textContent===' artwork','narrow screens read All sizes, Save and Export; wide screens keep the full names');
    const previousEngine=w.BritesAdResponsive,previousBrands=w.BritesBrandAssets;w.BritesAdResponsive=require(root+'/brites-ad-responsive');w.BritesBrandAssets=require(root+'/brites-brand-assets');const legacyActions=[];
    const scene=w.document.createElement('canvas');scene.width=400;scene.height=210;const context=scene.getContext('2d');context.fillStyle='#fffaf2';context.fillRect(0,0,400,210);context.fillStyle='#aa7010';context.fillRect(260,50,70,120);context.fillStyle='#cc8566';context.fillRect(370,0,30,30);
    const legacyPhoto={id:'legacy_photo',url:scene.toDataURL(),width:400,height:210},legacyDesign={artboard:{key:'landscape',width:400,height:210},device:'shared',document:{background:'#fffaf2',objects:[{type:'Image',sourceKey:'legacy_photo',width:400,height:210,left:0,top:0},{type:'Textbox',editorRole:'headline',text:'Sweet on\nPeach Charm',left:20,top:30,width:180,fontSize:28,fontFamily:'Georgia',fill:'#34281e'}]}};
    const recipe=await e.savedResponsiveRecipe({design:legacyDesign,sources:[legacyPhoto]});check(recipe.plan.style.preserveSavedStyle&&recipe.plan.style.headlineWeight==='400','saved design keeps its original regular headline weight');check(recipe.image.focus.x>.6&&recipe.image.focus.x<.67&&recipe.image.focus.width>.17&&recipe.image.focus.width<.23,'legacy focal detection selects the whole isolated product and excludes edge scenery');
    const tower=w.BritesAdResponsive.document(recipe.plan,recipe.image,{key:'display_160x600',width:160,height:600},'desktop'),towerPhoto=tower.objects.find(o=>o.editorRole==='photo'),towerTitle=tower.objects.find(o=>o.editorRole==='headline');
    check(towerTitle.text==='Peach Charm'&&towerTitle.fontSize>=16,'legacy narrow layouts select concise messaging at readable size');
    const f=recipe.image.focus;check(towerPhoto.cropX<=f.x*400&&towerPhoto.cropX+towerPhoto.width>=(f.x+f.width)*400,'narrow crop keeps the entire detected product width');
    const frozen=JSON.stringify(legacyDesign);await w.BritesAdEditor.previewSaved({design:legacyDesign,sources:[legacyPhoto]});check(JSON.stringify(legacyDesign)===frozen,'master preview reflow preserves the saved original');

    await w.BritesAdEditor.openAllSizes({scope:{workspaceId:'test',productId:'11',groupRef:'group',savedDesignId:'legacy'},request:async(action,input)=>{legacyActions.push(action);if(action==='adDesignEditorAIStatus')return {ok:true,reviewProofs:[]};assert.equal(action,'openAdDesignSavedDesign');assert.equal(input.id,'legacy');return {design:{device:'shared',artboard:{key:'square',width:2048,height:2048},document:beforeRecovery},sources:[photo]};}});
    const legacyGallery=w.document.querySelector('dialog[aria-label="Saved ad layouts"]');check(legacyGallery?.querySelectorAll('figure').length===27,'older saved artwork previews every size without stored review proofs');check(legacyGallery.textContent.includes('not a new AI review')&&legacyActions.length===1,'legacy preview is labeled honestly and makes no generation requests');legacyGallery.querySelector('[data-close]').click();w.BritesAdResponsive=previousEngine;w.BritesBrandAssets=previousBrands;
    // The review also reads each saved set's fresh evaluation; with none started the server answers {ok:true,phase:'idle'}.
    const reviewRequest=e.options.request,evaluationReads=[];e.options.request=async(action,input)=>{if(action==='adDesignMotionStatus')return {quality:{rubric:'complete-ad-v2',score:94,scores:{messaging:96,layout:92,relevance:94,visualAppeal:94,productRecognition:94},issues:[]},qualityTarget:92};if(action==='adEvaluationStatus'){evaluationReads.push(input.kind);check(['static','animated'].includes(input.kind)&&input.productId==='11'&&input.groupRef==='group'&&!input.requestId,'the review only reads the fresh evaluation of the saved '+input.kind+' ads, for this product and group');return {ok:true,phase:'idle'};}check(action==='adDesignEditorAIStatus'&&input.allSizes,'score button reads the complete saved set without generation');return {quality:{rubric:'complete-ad-v1',score:93.2,scores:{layout:89,messaging:94},issues:['<img src=x onerror=alert(1)> Tiny text in portrait.']},qualityTarget:92};};
    await e.refreshReviewScore();check(e.q('[data-review-score]').textContent==='Set review · 93.2/100','overall set score is visible without opening the popup');
    e.busy=true;await e.action('review-summary');check(e.busy,'reading review does not interrupt an active design task');e.busy=false;const reviewPanel=e.q('.bae-view section[aria-label="Ad set review"]');check(reviewPanel&&reviewPanel.textContent.includes('Animated ads')&&reviewPanel.textContent.includes('94/100')&&reviewPanel.textContent.includes('Layout')&&reviewPanel.textContent.includes('Suggestions'),'review shows category scores and short suggestions');check(!reviewPanel.querySelector('img')&&reviewPanel.textContent.includes('Later edits'),'review safely escapes issue text and distinguishes later edits');
    assert.deepEqual(failed,[],'no check failed inside the review fake (the review catches request errors)');check(evaluationReads.sort().join()==='animated,static'&&!/could not load/i.test(reviewPanel.textContent),'the review reads the fresh evaluation of both saved sets and shows no load error');
    check(!w.document.querySelector('dialog[aria-label="Ad set review"]')&&e.dialog.classList.contains('bae-viewing')&&e.q('[data-view-title]').textContent==='Ad set review'&&!reviewPanel.querySelector('[data-close]'),'inside the editor the review replaces the canvas instead of opening a pop-up on it');
    e.q('[data-action="view-back"]').click();await tick();check(e.q('.bae-view').hidden&&!e.dialog.classList.contains('bae-viewing')&&!e.q('.bae-view section'),'Back to editor returns to the canvas');e.options.request=reviewRequest;
    // Every ad size opens inside the editor in place of the canvas; Escape returns to it and to the button that opened them.
    const sizesRequest=e.options.request,sizesButton=e.q('[data-action="ai-review-proofs"]');e.options.request=async(action,input)=>action==='adDesignEditorAIStatus'?{reviewProofs:[{key:'desktop_square',url:photoUrl,width:2048,height:2048}]}:sizesRequest(action,input);
    sizesButton.focus();await e.action('ai-review-proofs',sizesButton);const sizesView=e.q('.bae-view');
    check(!sizesView.hidden&&e.dialog.classList.contains('bae-viewing')&&e.q('[data-view-title]').textContent==='Reviewed ad layouts'&&sizesView.querySelectorAll('figure').length===1&&!w.document.querySelector('dialog.bae-sheet')&&w.document.activeElement===e.q('[data-action="view-back"]'),'Preview all sizes replaces the canvas inside the editor, with Back to editor focused');
    const layersBeforeKey=e.canvas.getObjects().length;e.canvas.setActiveObject(e.canvas.getObjects()[0]);e.q('[data-action="view-back"]').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Delete',bubbles:true}));check(e.canvas.getObjects().length===layersBeforeKey,'editing keys do nothing to the hidden artwork while a view is open');e.canvas.discardActiveObject();
    e.dialog.dispatchEvent(new w.Event('cancel',{cancelable:true}));check(sizesView.hidden&&!e.disposed&&!e.dialog.classList.contains('bae-viewing')&&w.document.activeElement===sizesButton,'Escape returns to the canvas and the button that opened the sizes; the editor stays open');e.options.request=sizesRequest;
    // The AI Design choice also opens as a view inside the editor; Cancel, Escape and Back leave without starting anything.
    w.eval(fs.readFileSync(root+'/brites-ad-motion.js','utf8'));const startAI=e.startAI,aiStarts=[];e.startAI=async mode=>{aiStarts.push([mode,e.includeAnimation]);};e.canvas.discardActiveObject();e.renderInspector();
    const aiButton=e.q('[data-action="ai-design"]'),aiView=e.q('.bae-view'),dialogsBeforeAI=w.document.querySelectorAll('dialog').length;aiButton.focus();let choosing=e.action('ai-design',aiButton);const chooser=aiView.querySelector('.bam-option-dialog');
    check(chooser&&!aiView.hidden&&e.q('[data-view-title]').textContent==='What should AI Design create?'&&!chooser.querySelector('h2')&&w.document.querySelectorAll('dialog').length===dialogsBeforeAI&&[...chooser.querySelectorAll('label')].map(l=>l.firstChild.nextSibling.textContent.trim()).join('|')==='Static image ads|Static + animated ads'&&chooser.textContent.includes('about US$3.04')&&chooser.querySelector('p').textContent==='Jewelry identity stays consistent. Mobile layouts receive priority.'&&[...chooser.querySelectorAll('button')].map(b=>b.textContent).join('|')==='Cancel|Start AI Design'&&w.document.activeElement===e.q('[data-action="view-back"]'),'AI Design asks what to create inside the editor with the same wording, not in a pop-up');
    chooser.querySelector('[data-cancel]').click();await choosing;check(aiView.hidden&&!chooser.isConnected&&!aiStarts.length&&w.document.activeElement===aiButton,'Cancel returns to the AI Design button without starting anything');
    choosing=e.action('ai-design',aiButton);e.dialog.dispatchEvent(new w.Event('cancel',{cancelable:true}));await choosing;check(aiView.hidden&&!e.disposed&&!aiStarts.length&&w.document.activeElement===aiButton,'Escape leaves the AI Design choice and keeps the editor open');
    choosing=e.action('ai-design',aiButton);e.q('[data-action="view-back"]').click();await choosing;check(aiView.hidden&&!aiStarts.length&&w.document.activeElement===aiButton,'Back to editor leaves the AI Design choice the same way');
    choosing=e.action('ai-design',aiButton);e.q('.bae-view [value="animated"]').checked=true;e.busy=true;e.q('.bae-view [data-start]').click();await tick();const waitedForSave=aiView.hidden&&!aiStarts.length;e.busy=false;await choosing;check(waitedForSave&&!e.dialog.classList.contains('bae-viewing')&&aiStarts.length===1&&aiStarts[0][0]==='design'&&aiStarts[0][1]===true,'Start AI Design returns to the canvas and starts the chosen static + animated design once a running save has finished');
    e.startAI=startAI;
    check(e.filename('json').endsWith('.json'),'recovery files have the correct editable JSON extension');
    // Yes/no questions open in place under the control that asked; the browser's confirm() is never used.
    const nativeConfirm=w.confirm,layerCount=e.canvas.getObjects().length;w.confirm=()=>{throw Error('The editor must ask in place, not with a browser pop-up');};e.canvas.discardActiveObject();e.renderInspector();
    e.q('[data-template="blank"]').click();await tick();let asked=e.q('.askInline');
    check(layerCount>0&&asked&&asked.querySelector('.ieQ').textContent==='Clear this artboard? Undo will restore its layers.'&&asked.querySelector('[data-ask="yes"]').textContent==='Clear artboard'&&asked.previousElementSibling===e.q('[data-template="blank"]').closest('.bae-tool-buttons')&&e.canvas.getObjects().length===layerCount&&!e.busy,'Blank asks in place under the composition buttons and changes nothing until answered');
    asked.querySelector('[data-ask="no"]').click();await tick();check(!e.q('.askInline')&&e.canvas.getObjects().length===layerCount,'Cancel keeps every layer');
    e.q('[data-template="editorial"]').click();await tick();asked=e.q('.askInline');check(asked&&asked.querySelector('.ieQ').textContent==='Apply this template to the current artboard? Undo will restore the previous design.'&&asked.querySelector('[data-ask="yes"]').textContent==='Apply template','a template over existing layers asks with the same wording');asked.querySelector('[data-ask="no"]').click();await tick();
    e.status('The artwork could not be saved.','error');e.q('[data-close-unsaved]').click();await tick();asked=e.q('.bae-status>.askInline');
    check(asked&&asked.querySelector('.ieQ').textContent==='Close without saving these editor changes?'&&asked.querySelector('.ieNote').textContent==='Previously saved designs stay available.'&&!e.disposed,'Close without saving asks inside the status bar');
    asked.querySelector('[data-ask="no"]').click();await tick();check(!e.disposed&&!e.q('.askInline'),'Cancel keeps the editor open');e.q('[data-action="dismiss-status"]').click();
    e.tab='layers';e.renderLeft();check(/^(Lock|Unlock)$/.test(e.q('[data-lock-layer]').textContent)&&/^(Hide|Show)$/.test(e.q('[data-visible-layer]').textContent),'layer controls say Hide or Show and Lock or Unlock in words');e.tab='photos';e.renderLeft();w.confirm=nativeConfirm;
    await e.openSavedDesign(firstCopy);check(e.canvas.getObjects().some(o=>o.type==='group'&&o.getObjects().some(x=>x.text==='Choose your charm')),'saved design reopens with editable button layers');await e.action('save');e.startAI=async mode=>{aiStarts.push([mode]);};const startsBeforeClose=aiStarts.length,pendingChoice=e.action('ai-design');await e.dispose();check(await pendingChoice===undefined&&aiStarts.length===startsBeforeClose&&!w.document.querySelector('.bam-option-dialog'),'closing the editor ends an open AI Design choice without starting it');
    check(!unanswered.length,'the editor fake answered every request it received (unanswered: '+(unanswered.join(', ')||'none')+')');dom.window.close();
  }
  assert.deepEqual(failed,[],'every check passed, including checks inside request fakes whose errors the editor catches');
  console.log('PASS '+checks+' professional editor source, layout, save and export checks');
  require('./suite-guard.cjs').done();
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});

const identityIssue='Exact-product integrity needs correction: '+ 'The attachment geometry drifts. '.repeat(12);
const identityReview=editor.reviewSummary({score:94,pass:false,issues:[identityIssue]});
check(identityReview.issues[0]===identityIssue.trim(),'review retains complete identity findings');
check(identityReview.suggestions[0].includes('Replace the inaccurate source footage'),'identity failures are not misrepresented as crop fixes');
