const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),sharp=require('sharp');
const {requestBody,outputVideo,createGeminiVideo,MODEL}=require('../../netlify/functions/googleAdsGeminiVideo');
const {createMotionService,renderVariants}=require('../../netlify/functions/googleAdsAdMotion');
const fixture=path.join(__dirname,'ad-design-workflow.cjs'),source=fs.readFileSync(fixture,'utf8').split('(async()=>{const e=await setup();')[0];
const ctx=vm.createContext({require:require('node:module').createRequire(fixture),__dirname,process,Buffer,console,Date,setTimeout,clearTimeout});vm.runInContext(source+'\nglobalThis.mem=memory;',ctx);
let n=0;function ok(v,m){assert(v,m);n++;}
async function setup(){const f=ctx.mem(),ref=f.db.collection('Workspace').doc('design_test'),scope={productId:'p',groupRef:'g'},id='eai_'+'a'.repeat(40),jpeg=await sharp({create:{width:100,height:100,channels:3,background:'#b69b74'}}).jpeg().toBuffer();
 await ref.set({settings:scope,editorAI:{id},context:{groups:[{ref:'g'}]}});const e=ref.collection('editorAIJobs').doc(id);await e.set({scope,phase:'ready',createdAt:1});await e.collection('data').doc('request').set({sources:[{asset:{path:'photo'}}]});await e.collection('data').doc('result').set({responsive:{plan:{nativeCopy:{headlines:['Pendant']},layouts:[]}},sources:[{asset:{path:'photo'},width:100,height:100}]});
 const blobs=new Map(),calls={create:0,download:0,review:0,render:0},D={fb:()=>f,context:async()=>({ref,w:(await ref.get()).data(),products:[{id:'p',title:'Pendant',url:'https://example.test/p'}]}),loadAsset:async()=>jpeg,videoRequest:async(route,method,body)=>{if(method==='POST'){calls.create++;ok(body.model===MODEL&&body.background&&body.response_format.aspect_ratio,'exact Gemini interaction request');return {id:'v1_'+calls.create,status:'completed',steps:[{type:'model_output',content:[{type:'video',uri:'https://storage.googleapis.com/video.mp4'}]}]};}throw Error('Unexpected polling of completed result');},videoContent:async()=>{calls.download++;return Buffer.from('mp4')},saveVideo:async(id,b,key,info)=>{blobs.set(key,b);return {path:key,hash:key,...info}},loadVideo:async a=>blobs.get(a.path),signVideo:async a=>'https://example.test/'+a.path,renderVariants:async(b,orientation)=>{calls.render++;return ['mobile','desktop'].flatMap(device=>['portrait','square','landscape'].filter(format=>(format==='square'?(device==='mobile'?'portrait':'landscape'):format)===orientation).map(format=>({key:device+'_'+format,device,format,width:720,height:720,seconds:10,bytes:b,frames:[jpeg,jpeg,jpeg]})))},reviewImages:async()=>{calls.review++;return {productFaithful:true,pass:true,score:92,issues:[]}}};return {f,ref,D,calls,scope,id,service:createMotionService(D)};
}
(async()=>{
 const body=requestBody(Buffer.from('image'),'Exact jewelry, subtle camera movement','portrait');ok(body.model==='gemini-omni-1.1-flash'&&body.response_format.aspect_ratio==='9:16','requested model and ratio');ok(!('seconds'in body)&&!('input_reference'in body),'no OpenAI video parameters sent to Gemini');ok(outputVideo({steps:[{type:'user_input',content:[{type:'video',data:'wrong'}]},{type:'model_output',content:[{type:'video',data:'right'}]}]}).data==='right','only generated video returned');
 let sent=0;const provider=createGeminiVideo({apiKey:'fixture',fetch:async(url,opts)=>{sent++;ok(opts.headers['x-goog-api-key']==='fixture'&&!url.includes('fixture'),'key kept in header');return {ok:true,json:async()=>({id:'v1_1'}),headers:{get:()=>null}}}});await provider.request('interactions','POST',body);await assert.rejects(()=>provider.content({uri:'https://attacker.test/video'}),/unsupported/);ok(sent===1,'no credentials or fetch to untrusted download host');
 const e=await setup(),start=await e.service.start({workspaceId:'design_test',...e.scope});const result=await e.service.run({workspaceId:'design_test',jobId:start.jobId});ok(result.ok,'complete motion pipeline '+result.error);const status=await e.service.status({workspaceId:'design_test',...e.scope});ok(status.phase==='ready'&&status.variants.length===6,'six previews saved');ok(e.calls.create===2&&e.calls.render===2&&e.calls.review===1,'two paid masters reused six ways');await e.service.run({workspaceId:'design_test',jobId:start.jobId});ok(e.calls.create===2,'completed job never charges twice');
 const u=await setup();u.D.videoRequest=async()=>{u.calls.create++;throw Error('unknown network outcome')};const us=await u.service.start({workspaceId:'design_test',...u.scope});await u.service.run({workspaceId:'design_test',jobId:us.jobId});await u.service.run({workspaceId:'design_test',jobId:us.jobId});ok(u.calls.create===1,'unknown paid request never repeated');
 const nav=await setup(),ns=await nav.service.start({workspaceId:'design_test',...nav.scope});await nav.ref.update({settings:{productId:'other',groupRef:'other'}});ok((await nav.service.run({workspaceId:'design_test',jobId:ns.jobId})).ok,'navigation does not stop original animation');await assert.rejects(()=>nav.service.status({workspaceId:'design_test',productId:'other',groupRef:'other',jobId:ns.jobId}),/another product/);n++;
 console.log('PASS '+n+' Gemini request, durable generation, device variants and recovery checks');
})().catch(e=>{console.error(e.stack);process.exitCode=1});
