const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),sharp=require('sharp');
const {requestBody,outputVideo,createGeminiVideo,MODEL}=require('../../netlify/functions/googleAdsGeminiVideo');
const {createMotionService,renderVariants}=require('../../netlify/functions/googleAdsAdMotion');
const fixture=path.join(__dirname,'ad-design-workflow.cjs'),source=fs.readFileSync(fixture,'utf8').split('(async()=>{const e=await setup();')[0];
const ctx=vm.createContext({require:require('node:module').createRequire(fixture),__dirname,process,Buffer,console,Date,setTimeout,clearTimeout});vm.runInContext(source+'\nglobalThis.mem=memory;',ctx);
let n=0;function ok(v,m){assert(v,m);n++;}
async function setup(){const f=ctx.mem(),ref=f.db.collection('Workspace').doc('design_test'),scope={productId:'p',groupRef:'g'},id='eai_'+'a'.repeat(40),jpeg=await sharp({create:{width:100,height:100,channels:3,background:'#b69b74'}}).jpeg().toBuffer();
 await ref.set({settings:scope,editorAI:{id},context:{groups:[{ref:'g'}]}});const e=ref.collection('editorAIJobs').doc(id);await e.set({scope,phase:'ready',createdAt:1});await e.collection('data').doc('request').set({sources:[{asset:{path:'photo'}}]});await e.collection('data').doc('result').set({responsive:{plan:{nativeCopy:{headlines:['Pendant','A personal touch']},layouts:[]}},sources:[{asset:{path:'photo'},width:100,height:100}]});
 const direction=Object.fromEntries(['rationale','setting','props','lighting','opening','middle','ending','portrait','landscape','identity','limitations'].map(k=>[k,'Verified '+k]));
 const blobs=new Map(),calls={create:0,download:0,review:0,render:0},D={fb:()=>f,context:async()=>({ref,w:(await ref.get()).data(),products:[{id:'p',title:'Pendant',url:'https://example.test/p'}]}),loadAsset:async()=>jpeg,sampleMotionFrames:async()=>[],planMotion:async request=>{if(request.text.format.name==='brites_motion_treatment'){const brief=request.input[0].content;
   ok(brief.includes('Choose a fresh product-specific scene')&&brief.includes('never overpower it')&&brief.includes('exact colour and finish of the catalog reference'),'motion planning keeps the charm dominant and its metal faithful');
   ok(/ONE CAMERA IDEA, NAMED IN camera/.test(brief)&&/rack focus/.test(brief)&&/Never a plain push-in, a zoom out or a highlight pass/.test(brief),'the treatment must choose a distinct cinematic approach per piece');
   ok((brief.match(/^RULE \d+ - /gm)||[]).length===8&&/These film rules override any conflicting guidance above/.test(brief),'the treatment brief reads as numbered rules that override earlier guidance');
   ok(/It never orbits, spins, rotates or turns the jewelry/.test(brief)&&!/gentle orbit/.test(brief)&&!/crane-like rise/.test(brief),'no planned camera move may require inventing an unseen part of the piece');
   ok(/RULE 1 - THE PIECE IS NEVER ALTERED\. This outranks every other rule/.test(brief)&&/No re-modelling in three dimensions/.test(brief)&&/no added bail, stone or chain/.test(brief),'the treatment is told the piece may never be altered');
   ok(/148 pixels wide/.test(brief)&&/with messaging beside it about 40 pixels clear/.test(brief),'the treatment reserves the smaller wordmark with messaging beside it');
   ok(/RULE 2 - THE LOOK IS BRIGHT AND CHEERFUL/.test(brief)&&/Never dark, dim, moody, overcast or gloomy/.test(brief)&&/Subordinate does not mean washed out/.test(brief),'the treatment must plan a bright, cheerful, vibrant scene');
   ok(/Decide per piece/.test(brief)&&/Most films carry no model at all/.test(brief),'a worn moment is case specific, never the house style');
   ok(request.text.format.schema.required.includes('camera'),'the saved treatment records its camera approach');}return {output_text:JSON.stringify(request.text.format.name==='video_product_bounds'?{portrait:{bounds:[.35,.48,.3,.24],complete:true,confidence:.99,note:'fixture'},landscape:{bounds:[.6,.25,.25,.5],complete:true,confidence:.99,note:'fixture'}}:direction)};},videoRequest:async(route,method,body)=>{if(method==='POST'){calls.create++;const prompt=body.input.map(v=>v.text||'').join(' ');
   ok(/warm yellow gold stays warm, rich, luminous gold/.test(prompt)&&/Never silver, white, grey, green-tinted, chalky or desaturated/.test(prompt),'video generation is told to hold the exact gold of the reference');
   ok(/RULE 1 - NEVER ALTER THE JEWELRY\. This outranks every other line here/.test(prompt),'not altering the piece is stated first as the overriding rule');
   ok(/No re-modelling in three dimensions\. No rotating, turning, tilting or flipping\. No edge, side or back the reference does not show/.test(prompt),'re-modelling and rotating the piece are forbidden outright');
   ok(/No thickened, bevelled, rounded, smoothed or re-cut edges\. No redrawn engraving\. No added loop, bail, stone or chain/.test(prompt),'edges, engraving and added parts are protected');
   ok(/^RULE \d+ - /m.test(prompt)&&(prompt.match(/^RULE \d+ - /gm)||[]).length===5,'the film prompt reads as short numbered rules rather than one dense block');
   ok(/hold the piece still and move the scene instead/.test(prompt),'a camera idea never justifies inventing part of the piece');
   ok(/RULE 2 - BRIGHT AND CHEERFUL/.test(prompt)&&/Never dark, dim, moody, overcast, gloomy or heavy with shadow/.test(prompt),'the film is required to be bright and cheerful, never gloomy');
   ok(/Never grey, muddy, hazy, foggy, misty, bloomed or milky/.test(prompt)&&/Never quiet it by draining its colour or going dark/.test(prompt),'the scene stays subordinate through craft, not by washing it out or darkening it');
   ok(/Perform the camera approach named in the treatment, not a generic push-in or zoom/.test(prompt)&&/never orbit, spin, rotate or turn the jewelry itself/.test(prompt),'the camera moves through the scene and never around the piece');
   ok(/composed onto the finished film afterwards in a soft, pale, neutral wash/.test(prompt)&&!/Coordinate every shot with these actual overlay colours/.test(prompt),'the brand palette is described, never handed over as colour codes');ok(body.model===MODEL&&body.background&&body.response_format.aspect_ratio,'exact Gemini interaction request');return {id:'v1_'+calls.create,status:'completed',steps:[{type:'model_output',content:[{type:'video',uri:'https://storage.googleapis.com/video.mp4'}]}]};}throw Error('Unexpected polling of completed result');},videoContent:async()=>{calls.download++;return Buffer.from('mp4')},saveVideo:async(id,b,key,info)=>{blobs.set(key,b);return {path:key,hash:key,...info}},loadVideo:async a=>blobs.get(a.path),signVideo:async a=>'https://example.test/'+a.path,renderVariants:async(b,orientation,plan)=>{calls.render++;return ['mobile','desktop'].flatMap(device=>['portrait','square','landscape'].filter(format=>(!plan?.pipelineVersion||device===(format==='landscape'?'desktop':'mobile'))).filter(format=>(format==='square'?(plan?.squareMaster||(device==='mobile'?'portrait':'landscape')):format)===orientation).map(format=>({key:device+'_'+format,device,format,width:720,height:720,seconds:10,bytes:b,frames:[jpeg,jpeg,jpeg]})))},reviewImages:async()=>{calls.review++;return {productFaithful:true,mobileReadable:true,pass:true,score:98,issues:[]}}};return {f,ref,D,calls,scope,id,service:createMotionService(D)};
}
(async()=>{
 const body=requestBody(Buffer.from('image'),'Exact jewelry, subtle camera movement','portrait');ok(body.model==='gemini-omni-1.1-flash'&&body.response_format.aspect_ratio==='9:16','requested model and ratio');ok(!('seconds'in body)&&!('input_reference'in body),'no OpenAI video parameters sent to Gemini');ok(outputVideo({steps:[{type:'user_input',content:[{type:'video',data:'wrong'}]},{type:'model_output',content:[{type:'video',data:'right'}]}]}).data==='right','only generated video returned');
 let sent=0;const provider=createGeminiVideo({apiKey:'fixture',fetch:async(url,opts)=>{sent++;ok(opts.headers['x-goog-api-key']==='fixture'&&!url.includes('fixture'),'key kept in header');return {ok:true,json:async()=>({id:'v1_1'}),headers:{get:()=>null}}}});await provider.request('interactions','POST',body);await assert.rejects(()=>provider.content({uri:'https://attacker.test/video'}),/unsupported/);ok(sent===1,'no credentials or fetch to untrusted download host');
 const e=await setup(),start=await e.service.start({workspaceId:'design_test',...e.scope});const result=await e.service.run({workspaceId:'design_test',jobId:start.jobId});ok(result.ok,'complete motion pipeline '+result.error);const status=await e.service.status({workspaceId:'design_test',...e.scope});ok(status.phase==='ready'&&status.variants.length===3,'three previews saved');ok(e.calls.create===2&&e.calls.render===2&&e.calls.review===1,'two paid masters reused across three ratios');await e.service.run({workspaceId:'design_test',jobId:start.jobId});ok(e.calls.create===2,'completed job never charges twice');
 const truncated=await setup(),ts=await truncated.service.start({workspaceId:'design_test',...truncated.scope}),tr=truncated.ref.collection('motionJobs').doc(ts.jobId);
 await tr.update({phase:'failed',inFlight:{key:'direction',requestId:'old'},leaseUntil:0});
 await tr.collection('receipts').doc('direction').set({response:{status:'incomplete',incomplete_details:{reason:'max_output_tokens'}},at:1});
 await truncated.service.start({workspaceId:'design_test',...truncated.scope,resumeJobId:ts.jobId});
 ok(!(await tr.collection('receipts').doc('direction').get()).exists,'explicit resume removes only the truncated active receipt');
 ok((await tr.collection('receipts').get()).docs.length===1,'truncated paid receipt is archived');
 ok(truncated.calls.create===0,'resume itself does not charge');
 ok((await tr.get()).data().inFlight===null,'new text step can run without reusing incomplete response');
 for(const key of ['quality','layout']){
  const x=await setup(),a=await x.service.start({workspaceId:'design_test',...x.scope}),r=x.ref.collection('motionJobs').doc(a.jobId);
  await r.update({phase:'needs_attention',inFlight:{key,requestId:'saved'},compositionBlocked:key==='layout',leaseUntil:0});
  await r.collection('receipts').doc(key).set({response:{status:'incomplete',incomplete_details:{reason:'max_output_tokens'}}});
  ok((await x.service.status({workspaceId:'design_test',...x.scope})).canResume,'confirmed truncated '+key+' offers resume');
  await x.service.start({workspaceId:'design_test',...x.scope,resumeJobId:a.jobId});
  ok(!(await r.collection('receipts').doc(key).get()).exists,'truncated '+key+' receipt is archived instead of reused');
 }
 const discardCase=await setup(),ds=await discardCase.service.start({workspaceId:'design_test',...discardCase.scope}),dr=discardCase.ref.collection('motionJobs').doc(ds.jobId);
 await dr.update({phase:'needs_attention',inFlight:{requestId:'unknown-paid-request'},masters:{portrait:{id:'saved-video'}}});
 const discardInput={workspaceId:'design_test',...discardCase.scope,discardJobId:ds.jobId,confirmDiscard:true};
 await assert.rejects(()=>discardCase.service.start({...discardInput,confirmDiscard:false}),/Confirm/);
 await assert.rejects(()=>discardCase.service.start({...discardInput,productId:'other'}),/another product/);
 await discardCase.service.start(discardInput);await discardCase.service.start(discardInput);
 const discarded=(await dr.get()).data();ok(discarded.resetAt&&discarded.phase==='cancelled'&&discarded.masters.portrait.id==='saved-video'&&discarded.inFlight.requestId==='unknown-paid-request','discard releases attempt while preserving paid evidence');
 const fresh=await discardCase.service.start({workspaceId:'design_test',...discardCase.scope});
 ok(fresh.jobId!==ds.jobId&&(await discardCase.service.start({workspaceId:'design_test',...discardCase.scope})).jobId===fresh.jobId,'fresh job after discard is distinct and idempotent');
 ok(discardCase.calls.create===0,'discard and new job reservation never call the video provider');
 const pinned=await setup(),authority=await sharp({create:{width:100,height:100,channels:3,background:'#ff0000'}}).jpeg().toBuffer(),requestRef=pinned.ref.collection('editorAIJobs').doc(pinned.id).collection('data').doc('request');
 await requestRef.set({sources:[{asset:{path:'earlier-generated-scene'}}],identitySources:[{asset:{path:'verified-catalog-photo'}}]});const oldLoad=pinned.D.loadAsset;pinned.D.loadAsset=async asset=>asset.path==='verified-catalog-photo'?authority:oldLoad(asset);
 const pinnedRequest=pinned.D.videoRequest;pinned.D.videoRequest=async(route,method,body)=>{if(method==='POST'){const {data}=await sharp(Buffer.from(body.input[0].data,'base64')).raw().toBuffer({resolveWithObject:true});ok(data[0]>240&&data[1]<20,'video generation uses original catalog identity pixels');}return pinnedRequest(route,method,body);};
 pinned.D.reviewImages=async source=>{ok(source.equals(authority),'animation review uses pinned catalog pixels instead of earlier generated artwork');return {productFaithful:true,mobileReadable:true,pass:true,score:98,issues:[]};};
 const pinnedStart=await pinned.service.start({workspaceId:'design_test',...pinned.scope});ok((await pinned.service.run({workspaceId:'design_test',jobId:pinnedStart.jobId})).ok,'catalog identity survives the complete animation pipeline');ok((await requestRef.get()).data().sources[0].asset.path==='earlier-generated-scene','original editor context remains unchanged');
 const low=await setup();low.D.reviewImages=async()=>({pass:true,productFaithful:true,mobileReadable:true,score:96,issues:['Mobile framing needs refinement']});const lowStart=await low.service.start({workspaceId:'design_test',...low.scope});const lowRun=await low.service.run({workspaceId:'design_test',jobId:lowStart.jobId});ok(lowRun.ok,'subtarget films remain available to preview');const lowStatus=await low.service.status({workspaceId:'design_test',...low.scope});ok(lowStatus.variants.length===3&&!lowStatus.qualityTargetMet&&lowStatus.canRepair,'subtarget films remain saved with an honest target status');
 const u=await setup();u.D.videoRequest=async()=>{u.calls.create++;throw Error('unknown network outcome')};const us=await u.service.start({workspaceId:'design_test',...u.scope});await u.service.run({workspaceId:'design_test',jobId:us.jobId});await u.service.run({workspaceId:'design_test',jobId:us.jobId});ok(u.calls.create===1,'unknown paid request never repeated');
 const nav=await setup(),ns=await nav.service.start({workspaceId:'design_test',...nav.scope});await nav.ref.update({settings:{productId:'other',groupRef:'other'}});ok((await nav.service.run({workspaceId:'design_test',jobId:ns.jobId})).ok,'navigation does not stop original animation');await assert.rejects(()=>nav.service.status({workspaceId:'design_test',productId:'other',groupRef:'other',jobId:ns.jobId}),/another product/);n++;
 const rejected=await setup();rejected.D.reviewImages=async()=>({productFaithful:true,pass:false,issues:['Product obscured in mobile crop']});const rejectedStart=await rejected.service.start({workspaceId:'design_test',...rejected.scope});const rejectedRun=await rejected.service.run({workspaceId:'design_test',jobId:rejectedStart.jobId});ok(rejectedRun.ok&&(await rejected.service.status({workspaceId:'design_test',...rejected.scope})).phase==='ready','quality findings do not block preview access');
 const failed=await rejected.service.status({workspaceId:'design_test',...rejected.scope}),parentBefore=JSON.stringify((await rejected.ref.collection('motionJobs').doc(failed.jobId).get()).data());
 ok(failed.canRepair&&failed.repairReviewHash,'failed review exposes a bound repair choice');await assert.rejects(()=>rejected.service.start({workspaceId:'design_test',...rejected.scope,repairOf:failed.jobId,repairReviewHash:'stale'}),/review changed/);n++;
 const repairInput={workspaceId:'design_test',...rejected.scope,repairOf:failed.jobId,repairReviewHash:failed.repairReviewHash},repair=await rejected.service.start(repairInput),repeated=await rejected.service.start(repairInput);ok(repair.jobId===repeated.jobId&&rejected.calls.create===2,'repeated repair approval creates one durable job without charging');
 ok(JSON.stringify((await rejected.ref.collection('motionJobs').doc(failed.jobId).get()).data())===parentBefore,'repair preserves original clips, review and paid history');
 rejected.D.reviewImages=async()=>({productFaithful:true,mobileReadable:true,pass:true,score:98,issues:[]});ok((await rejected.service.run({workspaceId:'design_test',jobId:repair.jobId})).ok,'repair can pass a fresh quality review');ok(rejected.calls.create===4,'one repair generates exactly two additional masters');await rejected.service.run({workspaceId:'design_test',jobId:repair.jobId});ok(rejected.calls.create===4,'completed repair never charges twice');
 const repairStatus=await rejected.service.status({workspaceId:'design_test',...rejected.scope,jobId:repair.jobId});ok(repairStatus.repairOf===failed.jobId&&!repairStatus.canRepair&&repairStatus.variants.length===3,'repaired job stays linked to original and cannot trigger unbounded retries');
 const repairedRef=rejected.ref.collection('motionJobs').doc(repair.jobId);await repairedRef.update({phase:'needs_attention',quality:{pass:false,issues:['Still failed']}});const second=await rejected.service.status({workspaceId:'design_test',...rejected.scope,jobId:repair.jobId});await assert.rejects(()=>rejected.service.start({...repairInput,repairOf:repair.jobId,repairReviewHash:second.repairReviewHash}),/bounded repair/);n++;
 ok(second.canPhotoMotion,'failed generated repair offers photograph motion');
 const photoInput={workspaceId:'design_test',...rejected.scope,photoMotionOf:repair.jobId,repairReviewHash:second.repairReviewHash};
 await assert.rejects(()=>rejected.service.start({...photoInput,repairReviewHash:'stale'}),/review changed/);n++;
 await assert.rejects(()=>rejected.service.start({...photoInput,productId:'other'}),/another product/);n++;
 const beforePhoto=JSON.stringify((await repairedRef.get()).data()),photoStart=await rejected.service.start(photoInput);
 ok((await rejected.service.start(photoInput)).jobId===photoStart.jobId,'photograph approval is idempotent');
 ok((await rejected.service.start({workspaceId:'design_test',...rejected.scope,resumeJobId:photoStart.jobId})).jobId===photoStart.jobId,'resume selects the exact photograph job instead of the original paid generation');
 await assert.rejects(()=>rejected.service.start({workspaceId:'design_test',...rejected.scope,resumeJobId:repair.jobId}),/reviewed correction/);n++;
 rejected.D.reviewImages=async()=>{rejected.calls.review++;return {productFaithful:true,mobileReadable:true,pass:true,score:98,issues:[],estimatedUsd:.18};};
 ok((await rejected.service.run({workspaceId:'design_test',jobId:photoStart.jobId})).ok,'photograph pipeline renders and reviews saved stills');
 const photoStatus=await rejected.service.status({workspaceId:'design_test',...rejected.scope,jobId:photoStart.jobId});
 ok(photoStatus.variants.length===3&&photoStatus.motionMode==='photograph'&&photoStatus.estimatedUsd===.18,'three photograph variants report only the actual review estimate');
 ok(rejected.calls.create===4&&rejected.calls.download===4,'photograph motion makes no video generation or provider download requests');
 ok(!photoStatus.canRepair&&!photoStatus.canPhotoMotion,'completed photograph does not offer another paid repair');
 await rejected.service.run({workspaceId:'design_test',jobId:photoStart.jobId});
 ok(rejected.calls.create===4&&JSON.stringify((await repairedRef.get()).data())===beforePhoto,'repeat execution preserves previous videos and costs');
 const photoRef=rejected.ref.collection('motionJobs').doc(photoStart.jobId);await photoRef.update({phase:'needs_attention',quality:{pass:false,productFaithful:true,score:72,issues:['Too much empty space']}});
 const widePhoto=await rejected.service.status({workspaceId:'design_test',...rejected.scope,jobId:photoStart.jobId});ok(widePhoto.canPhotoMotion&&!widePhoto.canRepair,'failed photograph framing offers one crop correction without generative repair');
 const closeInput={workspaceId:'design_test',...rejected.scope,photoMotionOf:photoStart.jobId,repairReviewHash:widePhoto.repairReviewHash},closeStart=await rejected.service.start(closeInput);
 ok((await rejected.service.start(closeInput)).jobId===closeStart.jobId,'closer framing is idempotent');
 ok((await rejected.service.run({workspaceId:'design_test',jobId:closeStart.jobId})).ok&&rejected.calls.create===4,'closer framing does not call the video provider');
 const closeRef=rejected.ref.collection('motionJobs').doc(closeStart.jobId);await closeRef.update({phase:'needs_attention',quality:{pass:false,score:80,issues:['Still needs art direction']}});
 const closeStatus=await rejected.service.status({workspaceId:'design_test',...rejected.scope,jobId:closeStart.jobId});ok(closeStatus.motionMode==='photograph-close'&&!closeStatus.canPhotoMotion&&!closeStatus.canRepair,'failed closer crops cannot launch an unbounded retry chain');
 await assert.rejects(()=>rejected.service.start({...closeInput,photoMotionOf:closeStart.jobId,repairReviewHash:closeStatus.repairReviewHash}),/completed animation review/);n++;
 const current=await setup(),prior=await setup();await current.ref.update({context:{campaignId:'42',groups:[{ref:'g'}]}});await prior.ref.update({context:{campaignId:'42',groups:[{ref:'g'}]}});
 const oldStart=await prior.service.start({workspaceId:'design_test',...prior.scope});await prior.service.run({workspaceId:'design_test',jobId:oldStart.jobId});
 current.D.relatedContexts=async()=>[{ref:prior.ref,w:(await prior.ref.get()).data()}];
 const recovered=await current.service.status({workspaceId:'new_version',...current.scope});
 ok(recovered.jobId===oldStart.jobId&&recovered.workspaceId==='design_test'&&recovered.fromEarlierVersion&&recovered.variants.length===3,'new ad version reads paid films from their original owning workspace');
 ok(current.calls.create===0&&current.calls.review===0,'recovering a previous-version animation makes no paid requests');
 const priorDoc=(await prior.ref.get()).data();
 for(const patch of [{context:{campaignId:'other'}},{settings:{productId:'other',groupRef:'g'}},{settings:{productId:'p',groupRef:'other'}},{archivedAt:1}]){
  await prior.ref.set({...priorDoc,...patch});ok((await current.service.status({workspaceId:'new_version',...current.scope})).phase==='idle','other campaign, product, group or archived workspace cannot supply a film');
 }
 await prior.ref.set(priorDoc);ok((await current.service.status({workspaceId:'new_version',...current.scope,jobId:oldStart.jobId})).phase==='idle','explicit missing job IDs are not silently redirected to another workspace');
 const {JSDOM}=require('jsdom'),dom=new JSDOM('<div id="motion"></div>',{runScripts:'outside-only',url:'https://example.test'}),win=dom.window,requests=[];
 win.HTMLDialogElement.prototype.showModal=function(){this.open=true;};win.HTMLDialogElement.prototype.close=function(){this.open=false;};win.setTimeout=()=>0;win.eval(fs.readFileSync(path.join(__dirname,'../../brites-ad-motion.js'),'utf8'));
 win.BritesAdMotion.mount(win.document.getElementById('motion'),{scope:{workspaceId:'new_version',...current.scope},request:async(action,payload)=>{requests.push({action,payload});return {...recovered,canRepair:true,quality:{pass:false,score:77,issues:['Preserve the exact leaf']},repairReviewHash:'review'};}});
 await new Promise(resolve=>setImmediate(resolve));
 ok(win.document.querySelector('video').getAttribute('crossorigin')==='anonymous','saved animation player requests CORS before loading the video');
 ok(win.document.querySelector('[data-detail]').textContent.includes('earlier ad version'),'animation provenance is visible to the operator');
 ok(!win.document.querySelector('button[data-device]')&&!win.document.querySelector('[data-photo-motion]'),'redundant device and photograph controls removed');ok(win.document.querySelector('[data-generate]').textContent==='Re-run animation'&&!win.document.querySelector('[data-generate]').disabled,'prominent rerun remains available after review');win.document.querySelector('[data-generate]').click();await [...win.document.querySelectorAll('dialog button')].find(b=>b.textContent==='Re-run animation').onclick();
 ok(requests.find(r=>r.action==='startAdDesignMotion').payload.workspaceId==='design_test','repair addresses the original saved job rather than the new version');
 ok(requests.filter(r=>r.action==='adDesignMotionStatus').every(r=>r.payload.workspaceId==='new_version'),'status remains bound to the currently selected product workspace');
 const preview=await win.BritesAdMotion.openAllSizes({scope:current.scope,request:async()=>recovered,status:recovered});ok(preview.querySelectorAll('video').length===3,'all-size preview includes precisely the three relevant ratios');preview.remove();
 ok(win.document.querySelector('progress').hidden,'completed review hides the active progress bar');
 const parentRef=e.ref.collection('motionJobs').doc(start.jobId);await parentRef.update({renderVersion:2});const old=await e.service.status({workspaceId:'design_test',...e.scope});ok(old.canRecompose,'legacy captions can be updated from saved masters');const before=JSON.stringify((await parentRef.get()).data());
 const input={workspaceId:'design_test',...e.scope,recomposeOf:start.jobId,repairReviewHash:old.repairReviewHash};const composed=await e.service.start(input);await e.service.run({workspaceId:'design_test',jobId:composed.jobId});ok(e.calls.create===2&&e.calls.download===2,'caption repair never regenerates or redownloads masters');ok(JSON.stringify((await parentRef.get()).data())===before,'caption repair preserves the original job');ok((await e.service.start(input)).jobId===composed.jobId,'caption retry is idempotent');
 const composedStatus=await e.service.status({workspaceId:'design_test',...e.scope,jobId:composed.jobId});ok(!composedStatus.canRecompose,'current captions do not offer redundant correction');
 const rerunInput={workspaceId:'design_test',...e.scope,rerunOf:composed.jobId,repairReviewHash:composedStatus.repairReviewHash};const rerun=await e.service.start(rerunInput);ok((await e.service.start(rerunInput)).jobId===rerun.jobId,'explicit rerun is idempotent per saved generation');await e.service.run({workspaceId:'design_test',jobId:rerun.jobId});ok(e.calls.create===4,'explicit rerun creates exactly two new masters');
 const unclear=await setup(),unclearPlan=unclear.D.planMotion;unclear.D.planMotion=async r=>r.text.format.name==='video_product_bounds'?{output_text:JSON.stringify({portrait:{bounds:[.3,.3,.2,.2],complete:false,confidence:.6,note:'occluded'}})}:unclearPlan(r);
 const unclearJob=await unclear.service.start({workspaceId:'design_test',...unclear.scope});await unclear.service.run({workspaceId:'design_test',jobId:unclearJob.jobId});const unclearState=await unclear.service.status({workspaceId:'design_test',...unclear.scope});ok(unclearState.phase==='ready'&&unclearState.variants.length===3&&unclearState.compositionNotes.length>=1&&unclear.calls.review===1,'unsure framing never stops the film: the directed region protects the jewelry, the note reaches the review');
 ok((await unclear.service.start({workspaceId:'design_test',...unclear.scope,rerunOf:unclearJob.jobId,repairReviewHash:unclearState.repairReviewHash})).queued,'explicit rerun remains available after an assumed framing');
 // Targeted fixes from the review: only the named film, captions or message change.
 const fx=await setup(),fxPlan=fx.D.planMotion;let copyFixes=0;fx.D.planMotion=async r=>r.text?.format?.name==='brites_motion_copy_fix'?(copyFixes++,{output_text:JSON.stringify({headline:'For the foodie who has everything',shortHeadline:'Pendant',description:'Gift-ready',cta:'Shop now',rationale:'specific hook'})}):fxPlan(r);
 fx.D.reviewImages=async(source,files,brief)=>{fx.calls.review++;fx.lastBrief=brief;return {pass:false,productFaithful:true,mobileReadable:true,score:85,scores:{messaging:90,layout:85,relevance:100,visualAppeal:90,productRecognition:100},categoryReviews:{messaging:{summary:'',deductions:[{points:10,reason:'Generic hook',evidence:'mobile_portrait at 0.3s',correction:'Rewrite the opening line as a specific gift hook',kind:'required',formats:['mobile_portrait']}]},layout:{summary:'',deductions:[{points:15,reason:'Caption too small',evidence:'mobile_square at 3.5s',correction:'Enlarge the caption',kind:'required',formats:['mobile_square']}]},visualAppeal:{summary:'',deductions:[{points:10,reason:'Flat lighting',evidence:'desktop_landscape frames',correction:'Add a travelling reflection across the metal',kind:'optional',formats:['desktop_landscape']}]},relevance:{summary:'',deductions:[]},productRecognition:{summary:'',deductions:[]}},issues:[]};};
 const fxStart=await fx.service.start({workspaceId:'design_test',...fx.scope});await fx.service.run({workspaceId:'design_test',jobId:fxStart.jobId});const fxState=await fx.service.status({workspaceId:'design_test',...fx.scope});
 ok(fxState.phase==='ready'&&fxState.canFix&&fxState.fixOptions.length===3,'every reviewed deduction offers one targeted fix');
 const byKind=Object.fromEntries(fxState.fixOptions.map(o=>[o.kind,o]));ok(byKind.copy?.category==='messaging'&&byKind.caption?.formats.join()==='mobile_square'&&byKind.master?.orientation==='landscape'&&byKind.master.estimatedUsd>1&&byKind.master.estimatedUsd<1.1,'copy, caption and single-film fixes are classified with honest scope and cost');
 await assert.rejects(()=>fx.service.start({workspaceId:'design_test',...fx.scope,fixOf:fxStart.jobId,repairReviewHash:'stale',fix:{category:'layout',index:0}}),/review changed/);n++;
 const captionFix={workspaceId:'design_test',...fx.scope,fixOf:fxStart.jobId,repairReviewHash:fxState.repairReviewHash,fix:{category:'layout',index:0}},cf=await fx.service.start(captionFix);
 ok(cf.queued&&(await fx.service.start(captionFix)).jobId===cf.jobId&&cf.jobId!==fxStart.jobId,'caption fix is a distinct, idempotent job');
 const beforeCaption={...fx.calls};ok((await fx.service.run({workspaceId:'design_test',jobId:cf.jobId})).ok,'caption fix completes');
 const cfState=await fx.service.status({workspaceId:'design_test',...fx.scope,jobId:cf.jobId});
 ok(cfState.phase==='ready'&&cfState.fixOf===fxStart.jobId&&cfState.variants.length===3&&fx.calls.create===beforeCaption.create&&fx.calls.download===beforeCaption.download&&fx.calls.review===beforeCaption.review+1,'caption fix re-composes without any new film or download and re-reviews the set');
 ok(cfState.variants.filter(v=>v.key!=='mobile_square').every(v=>fxState.variants.some(o=>o.key===v.key&&o.asset.hash===v.asset.hash)),'unaffected films keep their exact saved bytes');
 ok(fx.lastBrief.targetedFix?.formats.join()==='mobile_square'&&fx.lastBrief.fixNote,'the review is told which format was corrected');
 ok(cfState.estimatedUsd===0&&(await fx.ref.collection('motionJobs').doc(cf.jobId).get()).data().captionHints.square.preferBand,'caption fix costs nothing and records its hint');
 const masterFix={workspaceId:'design_test',...fx.scope,fixOf:fxStart.jobId,repairReviewHash:fxState.repairReviewHash,fix:{category:'visualAppeal',index:0}},mf=await fx.service.start(masterFix),beforeMaster={...fx.calls};
 ok((await fx.service.run({workspaceId:'design_test',jobId:mf.jobId})).ok,'master fix completes');const mfState=await fx.service.status({workspaceId:'design_test',...fx.scope,jobId:mf.jobId});
 ok(fx.calls.create===beforeMaster.create+1&&mfState.variants.length===3&&mfState.variants.find(v=>v.key==='mobile_portrait').asset.hash===fxState.variants.find(v=>v.key==='mobile_portrait').asset.hash,'master fix regenerates exactly one film and keeps the portrait film');
 ok(Math.abs(mfState.estimatedUsd-1.015)<.01,'master fix reports one film of video cost');
 const copyFix={workspaceId:'design_test',...fx.scope,fixOf:fxStart.jobId,repairReviewHash:fxState.repairReviewHash,fix:{category:'messaging',index:0}},cpf=await fx.service.start(copyFix),beforeCopy={...fx.calls};
 ok((await fx.service.run({workspaceId:'design_test',jobId:cpf.jobId})).ok,'copy fix completes');const cpfState=await fx.service.status({workspaceId:'design_test',...fx.scope,jobId:cpf.jobId}),cpfJob=(await fx.ref.collection('motionJobs').doc(cpf.jobId).get()).data();
 ok(copyFixes===1&&fx.calls.create===beforeCopy.create&&cpfState.variants.length===3&&cpfJob.plan.copy.headline==='For the foodie who has everything'&&cpfJob.copyFixed,'copy fix revises the message once and re-composes every format without new video');
 await fx.service.run({workspaceId:'design_test',jobId:cpf.jobId});ok(copyFixes===1&&fx.calls.create===beforeCopy.create,'completed fixes never charge twice');
 ok((await fx.service.status({workspaceId:'design_test',...fx.scope})).jobId===cpf.jobId,'the latest fix becomes the current animation');
 // Nothing the video model could render as text is ever put in front of it.
 {
  const motion=require('../../netlify/functions/googleAdsAdMotion');
  const keys=['rationale','setting','props','lighting','opening','middle','ending','portrait','landscape','identity','limitations'];
  const poisoned=Object.fromEntries(keys.map(k=>[k,'clean '+k]));
  poisoned.setting='Riverbank graded #58695F with Open Sans titles reading "Crocodile Charm Pendant" at 44px and 148 pixels of margin';
  poisoned.camera='Rack focus onto the piece';
  const job={title:'Crocodile Charm Pendant',plan:{style:{background:'#eef1ec',ink:'#252729',accent:'#a67c35',headlineFont:'Georgia',bodyFont:'Open Sans'},copy:{headline:'Crocodile Charm Pendant',cta:'Shop now'},nativeCopy:{headlines:['Gift-ready packaging included.']}},creativeDirection:poisoned};
  const prompt=motion.motionPrompt(job,'portrait','');
  ok(!/#[0-9a-fA-F]{3,8}/.test(prompt),'no colour code reaches the video model, even via the treatment');
  ok(!/Georgia|Open Sans/.test(prompt),'no font name reaches the video model, even via the treatment');
  ok(!/Gift-ready packaging/.test(prompt),'no saved ad copy reaches the video model, even via the treatment');
  ok(!/Crocodile|Pendant|Brites/i.test(prompt),'the product name and brand never reach the video model, which renders names it is given');
  ok(/Every surface in frame is blank/.test(prompt)&&/A film containing any glyph is rejected outright/.test(prompt),'the scene is defined positively as textless, not only forbidden text');
  ok(/The scenery reaches all four edges/.test(prompt)&&/No black bars, no letterboxing, no pillarboxing, no vignette/.test(prompt),'the footage may never frame itself with bars or a border');
  ok(!/\d+\s?(?:px|pixels)/.test(prompt),'no pixel specification reaches the video model, even via the treatment');
  ok(/no lettering anywhere, at any size, in focus or blurred/.test(prompt),'the film is told its frames carry no lettering at all');
  ok(/flat, laser-cut sheet metal about as thick as a credit card/.test(prompt)&&/one fortieth of the charm's length/.test(prompt)&&/engraving is cut into the metal/.test(prompt),'the film is given a measurable thinness and engraving cut into the metal');
  ok(/RULE 3 - ONE CONTINUOUS TAKE/.test(prompt)&&/No cuts, no jump cuts, no dissolves/.test(prompt),'the film must be one unbroken take');
  ok(/It is not the first frame/.test(prompt)&&/identical from the first frame to the last/.test(prompt),'the reference photo is never the opening frame and the piece is whole throughout');
  ok(motion.scrubDirection({title:'Crocodile Charm Pendant',plan:{},creativeDirection:Object.fromEntries(keys.map(k=>[k,'The Crocodile Charm Pendant by Brites on a stone']))},'portrait').setting==='The piece by the brand on a stone','the product name is swapped for a neutral word rather than left as a renderable token');
  const payload=JSON.stringify(motion.motionRequest(job).input[1].content);
  ok(!/#eef1ec|#252729|Georgia|Open Sans/.test(payload),'the treatment is not shown the palette, fonts or layout spec either');
 }

 // A film re-reads the operator's framing at generation time, so a crop applied
 // after the static ad was designed reaches the video without re-buying scenes.
 const refresh=await setup(),editorRequest=refresh.ref.collection('editorAIJobs').doc(refresh.id).collection('data').doc('request');
 await editorRequest.set({sources:[{asset:{path:'photo'}}],identitySources:[{id:'pinned',asset:{path:'uncropped-original'},width:1024,height:1024}]});
 let identityCalls=0;
 refresh.D.identityFor=async(workspaceId,jobId)=>{identityCalls++;assert.equal(jobId,refresh.id);return [{id:'pinned',asset:{path:'operator-crop'},width:600,height:500,framedFrom:'pinned',frame:{x:200,y:300,width:600,height:500}}];};
 const savedRequest=JSON.stringify((await editorRequest.get()).data());
 const freshFilm=await refresh.service.start({workspaceId:'design_test',...refresh.scope});
 ok((await refresh.ref.collection('motionJobs').doc(freshFilm.jobId).get()).data().originalSources[0].asset.path==='operator-crop'&&identityCalls===1,'a new film references the operator crop instead of the reference pinned earlier');
 ok(JSON.stringify((await editorRequest.get()).data())===savedRequest,'re-resolving never rewrites the static job, so its paid results stand');
 await refresh.service.run({workspaceId:'design_test',jobId:freshFilm.jobId});
 const finished=await refresh.service.status({workspaceId:'design_test',...refresh.scope});
 await refresh.ref.collection('motionJobs').doc(freshFilm.jobId).update({originalSources:[{id:'pinned',asset:{path:'uncropped-original'}}]});
 const reframedRerun=await refresh.service.start({workspaceId:'design_test',...refresh.scope,rerunOf:freshFilm.jobId,repairReviewHash:finished.repairReviewHash});
 ok((await refresh.ref.collection('motionJobs').doc(reframedRerun.jobId).get()).data().originalSources[0].asset.path==='operator-crop','a re-run re-reads the framing instead of cloning a stale reference');
 const safe=await setup();
 await safe.ref.collection('editorAIJobs').doc(safe.id).collection('data').doc('request').set({sources:[{asset:{path:'photo'}}],identitySources:[{id:'pinned',asset:{path:'pinned-original'}}]});
 safe.D.identityFor=async()=>{throw Error('identity service unavailable')};
 const safeJob=await safe.service.start({workspaceId:'design_test',...safe.scope});
 ok((await safe.ref.collection('motionJobs').doc(safeJob.jobId).get()).data().originalSources[0].asset.path==='pinned-original','an unavailable resolver falls back to the pinned reference rather than stopping the film');

 win.close();console.log('PASS '+n+' Gemini request, durable generation, device variants and recovery checks');
})().catch(e=>{console.error(e.stack);process.exitCode=1});

