const assert=require('node:assert/strict');
const fs=require('fs');
const vm=require('vm');
const root=process.argv[2]||require('node:path').resolve(__dirname,'../..');
const {makeAnalysisEngine,exactPlan,imageUrl,MODEL,compactEvidence,buildEvidencePackage}=require(root+'/netlify/functions/googleAdsAdAnalysis');
let checks=0;function ok(v,m){assert.ok(v,m);checks++;}function eq(a,b,m){assert.deepEqual(a,b,m);checks++;}
const engineText=fs.readFileSync(root+'/netlify/functions/googleAdsAutopilot.js','utf8');
const copyCode=engineText.slice(engineText.indexOf('function _copyValid('),engineText.indexOf('function _creativeGroups('));
const copyValid=vm.runInNewContext(copyCode+';_copyValid',{brandSafe:t=>!String(t).includes('unsafe')});
const clone=x=>JSON.parse(JSON.stringify(x));
const before={headlines:[{text:'Dainty Charm Necklace'},{text:'Handcrafted Jewelry'},{text:'Meaningful Gift'}],descriptions:[{text:'Discover a charm necklace for everyday moments.'},{text:'Explore handcrafted jewelry from Brites.'}]};
const snapshot={schema:1,campaignId:'42',channel:'search',complete:true,components:{searchAds:[{resourceName:'customers/9/ads/11',status:'ENABLED',finalUrls:['https://britesjewelry.com/products/charm'],responsiveSearchAd:before}],keywords:[{resourceName:'customers/9/adGroupCriteria/8~1',status:'ENABLED',negative:false,keyword:{text:'charm necklace',matchType:'EXACT'}}],assetGroups:[],assetLinks:[]}};
const recommendation={title:'Make the product clearer',reason:'Reported query intent is for charm necklaces; describe the product directly.',evidenceIds:['performance'],lessonIds:[],changes:[{kind:'rsa_copy',target:'customers/9/ads/11',value:'',headlines:['Charm Necklace Gifts','Handcrafted Charm Jewelry','Discover Brites Jewelry'],descriptions:['Explore meaningful charm necklaces for everyday moments.','Find a charm necklace in the Brites collection.']}]};
const ai={summary:'The existing campaign has enough activity for a focused copy test; effects remain uncertain.',findings:[{title:'Product intent',detail:'The recorded search intent relates to charm necklaces.',evidenceIds:['performance']}],recommendations:[recommendation],limitations:['This is a proposed test, not a promise of uplift.']};
function fixture(options={}){
 const docs=new Map(Object.entries(options.docs||{}).map(([k,v])=>[k,clone(v)]));let chain=Promise.resolve(),paid=0,guardCalls=0;
 function ref(path){return {path,get:async()=>({exists:docs.has(path),data:()=>clone(docs.get(path))}),set:async v=>docs.set(path,clone(v)),update:async v=>{if(!docs.has(path))throw Error('missing doc '+path);docs.set(path,{...docs.get(path),...clone(v)});},collection:n=>({doc:id=>ref(path+'/'+n+'/'+id)})};}
 let failApproval=!!options.failApproval;
 const db={collection:n=>({doc:id=>ref(n+'/'+id)}),runTransaction:fn=>{const run=chain.then(()=>fn({get:r=>r.get(),set:(r,v)=>{if(r.path.startsWith('approvals/')&&failApproval){failApproval=false;throw Error('Transient draft save failure');}docs.set(r.path,clone(v));},update:(r,v)=>docs.set(r.path,{...docs.get(r.path),...clone(v)})}));chain=run.catch(()=>{});return run;}};
 const D={fb:()=>({db,FV:{serverTimestamp:()=>123}}),COL:{state:'state',approvals:'approvals'},CID:'9',env:{OPENAI_API_KEY:'test-do-not-send'},control:async()=>({creativeBudgetUsd:options.budget??8}),reportContext:async()=>({accountToday:'2026-09-10',accountTimezone:'America/Toronto',budgetCurrency:'CAD'}),validatedRange:({start,end})=>({start:start||'2026-08-12',end:end||'2026-09-10'}),verifiedBasis:async args=>{guardCalls++;if(options.staleAt&&guardCalls>=options.staleAt)throw Error('Campaign version changed.');if(args.expectedVersion!=null&&args.expectedVersion!==3)throw Error('Campaign version changed.');if(args.snapshotHash&&args.snapshotHash!=='hash-3')throw Error('Snapshot changed.');return {campaignId:'42',version:3,snapshotHash:'hash-3',snapshot:options.snapshot||snapshot};},dailyStats:async()=>options.stats||({ok:true,campaigns:[{id:'42',name:'Charm',totals:{clicks:120,conv:6,convCd:5,cost:90,costNative:120},series:[]}],products:[],keywords:[],assetGroups:[],channelTotals:{},currency:'USD',breakdownCurrency:'CAD',breakdownBasis:'click',cdAvailable:true,warnings:[],coverage:{}}),campaignImprovement:async()=>options.improvement||({ok:true,summary:{},currentState:{},timeline:[],learning:{lessons:[]},evidence:{}}),conversionHealth:async()=>({validated:true,healthy:true}),gaql:async q=>{if(options.onGaql)await options.onGaql(q);return q.includes('FROM asset_group_asset')?(options.assetRows||[]):[];},merchantProducts:async()=>options.merchant||[],storeSalesEvidence:async()=>options.storeSales||({available:false}),creativeFetch:async()=>'<html>A real charm necklace from Brites.</html>',copyValid,invalidateImprovement:()=>{},fetch:async(url,opts)=>{paid++;if(options.onFetch)await options.onFetch(url,opts);if(options.providerError)throw Error('Network result unknown');return {ok:true,json:async()=>({id:'response-1',status:'completed',model:MODEL,usage:{input_tokens:1000,output_tokens:800},output:[{content:[{type:'output_text',text:JSON.stringify(options.ai||ai)}]}]})};}};
 return {D,api:makeAnalysisEngine(D),docs,paid:()=>paid,guardCalls:()=>guardCalls};
}
function expandEvidence(packet) {
 const expand=v=>{
  if(!v||typeof v!=='object')return v;
  if(Array.isArray(v))return v.map(expand);
  if(Object.hasOwn(v,'$string'))return packet.strings[v.$string];
  if(Object.hasOwn(v,'$value'))return expand(packet.values[v.$value]);
  if(Object.hasOwn(v,'$object'))return Object.fromEntries(v.$object.map(([k,x])=>[k,expand(x)]));
  if(Object.hasOwn(v,'$table'))return v.$table.rows.map(row=>{const record={};v.$table.columns.forEach((path,i)=>{if(row[i]&&row[i].$absent===true)return;let target=record;for(const key of path.slice(0,-1)){if(!Object.hasOwn(target,key))Object.defineProperty(target,key,{value:{},enumerable:true,writable:true});target=target[key];}Object.defineProperty(target,path.at(-1),{value:expand(row[i]),enumerable:true,writable:true});});return record;});
  return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,expand(x)]));
 };
 return expand(packet.data);
}
function archivedJob(f,id){const job=f.docs.get('state/adAnalysis-'+id),manifest=job.evidenceArchive;return JSON.parse(manifest.chunks.map(key=>f.docs.get('state/adAnalysis-'+id+'/evidence/'+key).text).join(''));}
(async()=>{
 const e=[{id:'performance',status:'available'}];
 let plan=exactPlan(snapshot,[recommendation],e,'9',copyValid);
 eq(plan.operations.length,1,'one in-place ad update');eq(plan.operations[0].adOperation.update.resourceName,'customers/9/ads/11');ok(!plan.operations.some(o=>o.adGroupAdOperation),'no new ad');eq(plan.changes[0].before.headlines,before.headlines,'exact before image');
 eq(exactPlan(snapshot,[{...recommendation,changes:[{...recommendation.changes[0],target:'customers/9/ads/999'}]}],e,'9',copyValid).operations.length,0,'unknown ad blocked');
 eq(exactPlan(snapshot,[{...recommendation,evidenceIds:['invented']}],e,'9',copyValid).operations.length,0,'unsupported evidence blocked');
 eq(exactPlan(snapshot,[recommendation],[{id:'performance',status:'unavailable'}],'9',copyValid).operations.length,0,'unavailable evidence blocked');
 eq(exactPlan(snapshot,[{...recommendation,changes:[{...recommendation.changes[0],headlines:['Too short']}]}],e,'9',copyValid).operations.length,0,'provider minima enforced');
 let pinned=clone(snapshot);pinned.components.searchAds[0].responsiveSearchAd.headlines[0].pinnedField='HEADLINE_1';eq(exactPlan(pinned,[recommendation],e,'9',copyValid).operations.length,0,'pins cannot disappear');
 let malicious=clone(recommendation);malicious.changes=[{kind:'keyword_status',target:'customers/9/adGroupCriteria/8~1',value:'REMOVED'}];eq(exactPlan(snapshot,[malicious],e,'9',copyValid).operations.length,0,'keyword removal forbidden');malicious.changes[0].value='PAUSED';eq(exactPlan(snapshot,[malicious],e,'9',copyValid).operations[0].adGroupCriterionOperation.update.status,'PAUSED');
 let pm=clone(snapshot);pm.components.assetGroups=[{resourceName:'customers/9/assetGroups/1',status:'ENABLED',finalUrls:['https://britesjewelry.com/collections/charms']},{resourceName:'customers/9/assetGroups/2',status:'ENABLED',finalUrls:['https://britesjewelry.com/collections/charms']}];pm.components.assetLinks=[{resourceName:'customers/9/assetGroupAssets/1~1~1',assetGroup:'customers/9/assetGroups/1',asset:'customers/9/assets/1',fieldType:'MARKETING_IMAGE',imageUrl:'https://tpc.googlesyndication.com/one.jpg'},{resourceName:'customers/9/assetGroupAssets/2~2~1',assetGroup:'customers/9/assetGroups/2',asset:'customers/9/assets/2',fieldType:'MARKETING_IMAGE',imageUrl:'https://tpc.googlesyndication.com/two.jpg'}];
 let imageRec={...recommendation,changes:[{kind:'pmax_image',target:pm.components.assetLinks[0].resourceName,value:'customers/9/assets/2'}]};plan=exactPlan(pm,[imageRec],e,'9',copyValid);eq(plan.operations.length,2,'same-field existing-image swap');eq(plan.operations[1].assetGroupAssetOperation.create.assetGroup,'customers/9/assetGroups/1','group identity retained');pm.components.assetGroups[1].finalUrls=['https://britesjewelry.com/products/different'];eq(exactPlan(pm,[imageRec],e,'9',copyValid).operations.length,0,'wrong product destination blocked');pm.components.assetGroups[1].finalUrls=pm.components.assetGroups[0].finalUrls;pm.components.listingGroups=[{assetGroup:'customers/9/assetGroups/1',type:'UNIT_INCLUDED',caseValue:{productItemId:{value:'productA'}}},{assetGroup:'customers/9/assetGroups/2',type:'UNIT_INCLUDED',caseValue:{productItemId:{value:'productB'}}}];eq(exactPlan(pm,[imageRec],e,'9',copyValid).operations.length,0,'different Merchant product scope blocked');pm.components.listingGroups=[];pm.components.assetLinks[1].fieldType='SQUARE_MARKETING_IMAGE';eq(exactPlan(pm,[imageRec],e,'9',copyValid).operations.length,0,'wrong aspect-role blocked');
 eq(imageUrl('https://evil.example/image.jpg'),null);eq(imageUrl('https://google.com.evil.test/image'),null);eq(imageUrl('https://user:pass@google.com/image'),null);ok(imageUrl('https://lh3.googleusercontent.com/photo'));
 let f=fixture();let job=await f.api.beginAnalyzeAd({campaignId:'42',expectedVersion:3,snapshotHash:'hash-3'});eq(f.paid(),0,'enqueue is free');eq(job.sourceVersion,3);eq(job.range.currency,'CAD');
 let duplicate=await f.api.beginAnalyzeAd({campaignId:'42',expectedVersion:3,snapshotHash:'hash-3'});eq(duplicate.analysisId,job.analysisId,'same version/range deduped');ok(duplicate.reused);eq((await f.api.analyzeAdStatus({campaignId:'42'})).analysisId,job.analysisId,'latest lookup read-only');
 let results=await Promise.all([f.api.runAnalyzeAd({analysisId:job.analysisId}),f.api.runAnalyzeAd({analysisId:job.analysisId})]);eq(f.paid(),1,'duplicate workers one paid request');let status=await f.api.analyzeAdStatus({analysisId:job.analysisId});eq(status.status,'ready');ok(status.approvalId);let approval=f.docs.get('approvals/'+status.approvalId);eq(approval.type,'adAnalysisUpdate');eq(approval.status,'PENDING','never auto approved');eq(approval.payload.versionGuard,{campaignId:'42',expectedVersion:3,snapshotHash:'hash-3'});eq(approval.payload.versionChange.proposedVersion,4);eq(status.usage.output_tokens,800);eq(approval.payload.meta.budgetCurrency,'CAD');ok(status.result.evidence.some(e=>e.id==='catalog'&&e.status==='unavailable'),'missing research never called checked');
 await f.api.runAnalyzeAd({analysisId:job.analysisId});eq(f.paid(),1,'completed jobs never rerun');
 f=fixture({providerError:true});job=await f.api.beginAnalyzeAd({campaignId:'42'});await f.api.runAnalyzeAd({analysisId:job.analysisId});status=await f.api.analyzeAdStatus({analysisId:job.analysisId});eq(status.status,'needs_reconciliation');ok(!status.canRetry);await f.api.beginAnalyzeAd({campaignId:'42',retry:true});await f.api.runAnalyzeAd({analysisId:job.analysisId});eq(f.paid(),1,'unknown paid result not repeated');eq([...f.docs.keys()].filter(k=>k.startsWith('approvals/')).length,0);
 f=fixture({budget:0});job=await f.api.beginAnalyzeAd({campaignId:'42'});await f.api.runAnalyzeAd({analysisId:job.analysisId});eq(f.paid(),0,'zero allowance blocks before spending');status=await f.api.analyzeAdStatus({analysisId:job.analysisId});eq(status.status,'failed');ok(status.canRetry,'safe pre-request retry');
 f=fixture({staleAt:2});job=await f.api.beginAnalyzeAd({campaignId:'42'});await f.api.runAnalyzeAd({analysisId:job.analysisId});eq(f.paid(),0,'stale start blocks spend');eq((await f.api.analyzeAdStatus({analysisId:job.analysisId})).status,'stale');
 f=fixture({staleAt:3});job=await f.api.beginAnalyzeAd({campaignId:'42'});await f.api.runAnalyzeAd({analysisId:job.analysisId});eq(f.paid(),1);eq([...f.docs.keys()].filter(k=>k.startsWith('approvals/')).length,0,'change during research prevents stale approval');
 f=fixture({ai:{...ai,recommendations:[]}});job=await f.api.beginAnalyzeAd({campaignId:'42'});await f.api.runAnalyzeAd({analysisId:job.analysisId});status=await f.api.analyzeAdStatus({analysisId:job.analysisId});eq(status.status,'no_changes');eq(status.approvalId,null,'honest no change outcome');
 f=fixture();job=await f.api.beginAnalyzeAd({campaignId:'42'});const key='state/adAnalysis-'+job.analysisId;f.docs.set(key,{...f.docs.get(key),status:'running',leaseUntil:1,leaseOwner:'old',modelDispatched:false});status=await f.api.analyzeAdStatus({analysisId:job.analysisId});ok(status.canRetry,'expired free worker recoverable');let retry=await f.api.beginAnalyzeAd({campaignId:'42',retry:true});eq(retry.status,'queued');await f.api.runAnalyzeAd({analysisId:job.analysisId});eq(f.paid(),1);
 f=fixture({stats:{ok:true,campaigns:[{id:'999'}]}});job=await f.api.beginAnalyzeAd({campaignId:'42'});await f.api.runAnalyzeAd({analysisId:job.analysisId});eq(f.paid(),0,'wrong campaign report blocks paid analysis');
 f=fixture({onFetch:async(url,opts)=>{eq(url,'https://api.openai.com/v1/responses');let body=JSON.parse(opts.body);eq(body.model,MODEL);eq(body.reasoning.effort,'high');eq(body.text.format.type,'json_schema');eq(body.store,false);ok(!body.tools,'no unbounded external research');ok(body.max_output_tokens<=8000);}});job=await f.api.beginAnalyzeAd({campaignId:'42'});await f.api.runAnalyzeAd({analysisId:job.analysisId});
 f=fixture({failApproval:true});job=await f.api.beginAnalyzeAd({campaignId:'42'});await f.api.runAnalyzeAd({analysisId:job.analysisId});status=await f.api.analyzeAdStatus({analysisId:job.analysisId});eq(status.status,'failed');ok(status.canRetry,'saved model output can resume');eq(f.paid(),1);await f.api.beginAnalyzeAd({campaignId:'42',retry:true});await f.api.runAnalyzeAd({analysisId:job.analysisId});status=await f.api.analyzeAdStatus({analysisId:job.analysisId});eq(status.status,'ready');eq(f.paid(),1,'resumed drafting does not repeat paid request');eq(status.providerModel,MODEL);
 const pmaxSnapshot={...snapshot,channel:'PERFORMANCE_MAX'};f=fixture({snapshot:pmaxSnapshot,assetRows:[{asset:{resourceName:'customers/9/assets/1',imageAsset:{fullSize:{url:'https://tpc.googlesyndication.com/test.jpg'}}},assetGroupAsset:{resourceName:'customers/9/assetGroupAssets/1~1~1',fieldType:'MARKETING_IMAGE'},metrics:{impressions:'10',clicks:'2'}}]});job=await f.api.beginAnalyzeAd({campaignId:'42'});await f.api.runAnalyzeAd({analysisId:job.analysisId});status=await f.api.analyzeAdStatus({analysisId:job.analysisId});eq(status.result.images[0].metrics.conversions,null,'missing asset conversions never zero');eq(status.result.images[0].range.basis,'click','asset date basis explicit');ok(status.result.images[0].limitation.includes('do not add'),'repeated credit caveat');
 // The original 110 kB rejection was unrelated to reporting range. Repeated
 // store/product/monthly evidence must fit without deleting the tail of reports.
 const repeated='A verified product identity with a precise immutable source and reporting currency. '.repeat(4);
 const sourceRows=Array.from({length:160},(_,i)=>({itemId:'shopify_US_'+(1000+i)+'_'+(2000+i),storeProductId:'gid://shopify/Product/'+(1000+i),title:'Charm '+i,impressions:120+i,clicks:4+i,conversions:i===159?3:null,conversionValue:i===159?441:0,currency:'USD',basis:'click',matchExplanation:repeated}));
 const raw={rows:sourceRows,again:sourceRows,emptyRecords:[{},...sourceRows.slice(0,5)],odd:[{a:null,b:0,empty:{},n:{x:1},long:repeated},{a:0,n:{x:2},long:repeated},{a:3,n:{y:0},long:repeated}],literal:{$value:0},literal2:{$absent:true},literal3:{$table:{columns:['a']}}};
 const compact=compactEvidence(raw);eq(expandEvidence(compact),raw,'lossless records preserve IDs, all rows, null/zero/missing fields and literal marker keys');ok(JSON.stringify(compact).length<JSON.stringify(raw).length*.5,'large repeated payload is materially smaller');
 const largeStats={ok:true,campaigns:[{id:'42',name:'Charm',totals:{clicks:120,conv:6,convCd:5,cost:90,costNative:120},series:[]}],products:sourceRows,keywords:[],assetGroups:[],channelTotals:{},currency:'USD',breakdownCurrency:'CAD',breakdownBasis:'click',cdAvailable:true,warnings:[],coverage:{productReportComplete:true}};
 const largeAssets=Array.from({length:220},(_,i)=>({asset:{resourceName:'customers/9/assets/'+i,textAsset:{text:'A true handcrafted charm'}},assetGroupAsset:{resourceName:'customers/9/assetGroupAssets/1~'+i+'~2',assetGroup:'customers/9/assetGroups/1',fieldType:'HEADLINE',primaryStatus:'ELIGIBLE'},metrics:{impressions:String(100+i),clicks:String(i),costMicros:String(i*1000000),conversions:i===219?'7':'0',conversionsValue:'120'}}));
 const timeline=Array.from({length:20},(_,i)=>({id:'change-'+i,date:'2026-09-'+String(i+1).padStart(2,'0'),comparison:{status:'observed',before:{clicks:i,conversions:1},after:{clicks:i+2,conversions:2},causal:false},lessons:repeated}));
 const sales={available:true,source:'Shopify order log and Merchant Center reports',periods:{days30:{orders:3,revenue:441,currency:'USD'},days90:{orders:4,revenue:553,currency:'USD'}},products:sourceRows.map(p=>({itemId:p.itemId,productId:p.storeProductId,title:p.title,days30:[{orders:1,revenue:30,attribution:'organic'}],days90:[{orders:2,revenue:60,attribution:'organic'}],monthly:[{month:'2026-08',orders:1,revenue:30}]})),seasonality:{days:365,months:Array.from({length:12},(_,i)=>({month:'2025-'+String(i+1).padStart(2,'0'),orders:i,revenue:i*30})),complete:false,limitation:'Incomplete observation year, not proven recurring seasonal demand'},merchant:{days30:{totals:{clicks:1,conversions:3,value:441},attributionBasis:'Merchant free listings'},days90:{totals:{clicks:10,conversions:4,value:553},attributionBasis:'Merchant free listings'}}};
 let captured;
 f=fixture({snapshot:{...snapshot,channel:'pmax'},stats:largeStats,assetRows:largeAssets,improvement:{ok:true,summary:{},currentState:{},timeline,learning:{lessons:[]},evidence:{}},storeSales:sales,docs:{'state/productSales':{byId:{1159:{productId:'1159',orders:3,revenue:441},9999:{productId:'9999',orders:10000,privateCatalogNote:'Outside selected campaign'}}},'state/collectionProfiles':{list:[{handle:'unrelated',topProducts:[{productId:'9999'}]},{handle:'charms',topProducts:[{productId:'1159'}]}]}},onFetch:async(url,opts)=>{
   const instruction=JSON.parse(opts.body).input[0].content[0].text;captured=expandEvidence(JSON.parse(instruction.split('EVIDENCE PACKAGE:\n')[1]));
   ok([...f.docs.keys()].some(k=>k.includes('/evidence/')),'complete evidence archive is durable before paid dispatch');ok(instruction.includes('counts where conversions exceed clicks'),'inconsistent clicks and conversions cannot drive invented rates');
 }});
 job=await f.api.beginAnalyzeAd({campaignId:'42'});const oversizedKey='state/adAnalysis-'+job.analysisId;
 f.docs.set(oversizedKey,{...f.docs.get(oversizedKey),status:'failed',error:'The complete evidence package exceeds the analysis allowance. A smaller reporting range is required; no paid request was sent.',modelDispatched:false});
 const sameRange=clone(job.range);await f.api.beginAnalyzeAd({campaignId:'42',retry:true});await f.api.runAnalyzeAd({analysisId:job.analysisId});
 status=await f.api.analyzeAdStatus({analysisId:job.analysisId});eq(status.status,'ready','previous size-failed job succeeds at unchanged range');eq(status.range,sameRange,'reporting range is retained');eq(f.paid(),1,'one mocked paid request after structural compression');
 eq(captured.snapshot,{...snapshot,channel:'pmax'},'authoritative editable snapshot unmodified');eq(captured.performance.products,sourceRows,'all 160 product rows reach Astra, including selected tail');eq(captured.assetOutcomes,largeAssets,'all 220 returned assets retained');eq(captured.history.timeline,timeline,'all 20 dated changes retained');eq(captured.storeSales,sales,'sales periods, seasonal observations and non-comparable counts retained exactly');
 eq(captured.catalog.find(x=>x.source==='productSales').byId,{'1159':{productId:'1159',orders:3,revenue:441}},'Shopify GID matches exact catalog product beyond old row cap');
 eq(status.result.evidenceCoverage.products,{returned:160,included:160});eq(status.result.evidenceCoverage.assets,{returned:220,included:220});ok(status.result.evidenceCoverage.sourceBytes>110000,'regression payload exceeds old hard limit');
 ok(status.result.evidenceArchive.chunks.length>1,'large complete evidence is split across documents');
 const archived=archivedJob(f,job.analysisId);eq(archived.sources.storeSales,sales,'full immutable archive keeps original sales source');eq(archived.sources.catalog.find(x=>x.source==='productSales').byId['9999'].privateCatalogNote,'Outside selected campaign','unrelated catalog evidence remains available in archive with explicit prompt exclusion');eq(archived.snapshot,{...snapshot,channel:'pmax'});eq(expandEvidence(archived.modelEvidence),captured,'archive binds exact request evidence');
 ok([...f.docs.values()].every(v=>Buffer.byteLength(JSON.stringify(v),'utf8')<950000),'each saved job or evidence chunk stays below Firestore document limit');ok(!Object.hasOwn(f.docs.get(oversizedKey).collected,'images'),'image report is not duplicated inside saved job');
 f=fixture({failApproval:true});job=await f.api.beginAnalyzeAd({campaignId:'42'});await f.api.runAnalyzeAd({analysisId:job.analysisId});
 const saved=f.docs.get('state/adAnalysis-'+job.analysisId),chunkKey='state/adAnalysis-'+job.analysisId+'/evidence/'+saved.evidenceArchive.chunks[0];
 f.docs.set(chunkKey,{...f.docs.get(chunkKey),text:f.docs.get(chunkKey).text+' '});
 await f.api.beginAnalyzeAd({campaignId:'42',retry:true});await f.api.runAnalyzeAd({analysisId:job.analysisId});
 eq(f.paid(),1,'damaged archive never repeats the paid request');eq((await f.api.analyzeAdStatus({analysisId:job.analysisId})).status,'failed','archive digest protects exact saved evidence on resume');eq([...f.docs.keys()].filter(k=>k.startsWith('approvals/')).length,0,'damaged archive cannot produce a review draft');
 console.log('Analyze Ad lifecycle and exact operation checks passed: '+checks);
})().catch(e=>{console.error(e);process.exit(1)});
