const assert=require('assert/strict'),fs=require('fs'),path=require('path'),brands=require('../../brites-brand-assets'),engine=require('../../brites-ad-responsive'),research=require('../../netlify/functions/googleAdsAdDesignResearch');
const {plan}=require('./ad-responsive.cjs');
for(const a of brands.assets){assert.equal(Buffer.compare(Buffer.from(brands.dataUrl(a.id).split(',')[1],'base64'),fs.readFileSync(path.resolve(__dirname,'../../assets/brites-brand',a.file))),0);assert(a.crop.x+a.crop.width<=a.width&&a.crop.y+a.crop.height<=a.height);}
assert.equal(brands.get('../../private'),undefined);assert.throws(()=>brands.dataUrl('unapproved'));
for(const b of engine.boards.filter(b=>engine.family(b)==='banner')){const d=engine.document(plan,{id:'photo',width:1000,height:1000,focus:{x:.4,y:.3,width:.2,height:.4}},b,'mobile'),brand=d.objects.find(o=>o.sourceKey==='brites_brand_icon'),name=d.objects.find(o=>o.editorRole==='headline'),text=d.objects.find(o=>o.editorRole==='brand'&&o.type==='Textbox');assert(brand&&name&&text);assert(brand.height*brand.scaleY>=32);assert(text.fontSize>=12&&name.fontSize>=16);assert(!d.objects.some(o=>o.editorRole==='button'));}
const evidence={hash:'test',sourceBindings:{landingUrl:'https://britesjewelry.com/products/peach'},sources:[{id:'product:11',status:'available',data:{title:'Peach Charm'}}],warnings:[]},request={productId:'11',groupRef:'g',mode:'design',artboard:{width:320,height:100},document:{objects:[{id:'photo',type:'Image',sourceKey:'photo',left:0,top:0,width:50,height:100,scaleX:1,scaleY:1,editorRole:'photo'}]}};
const output={productId:'11',groupRef:'g',rationale:'Prioritize the official brand',background:'',backgroundEnd:'',changes:[],additions:[{id:'ai_official_logo',type:'brand-wide',updates:[]}],removeLayerIds:[],layerOrder:[],alternatives:[],factClaims:[],sourceIds:['product:11'],limitations:[]};
const result=research.applyEditorPlan({output,request,evidence,sources:[{id:'photo',width:50,height:100}]});assert(result.document.objects.some(o=>o.sourceKey==='brites_brand_wide'&&o.editorRole==='brand'));
assert.throws(()=>research.applyEditorPlan({output:{...output,additions:[{id:'ai_arbitrary',type:'remote-image',updates:[]}]},request,evidence,sources:[]}),/unsupported/);
console.log('PASS official assets, bounded logo additions, exact source bytes and mobile brand/product priority');
