const path=require('path'),REPO=path.resolve(__dirname,'../..');
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(path.join(REPO,'brites-adwords.html'),'utf8');
for(const [,js] of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new Function(js);
function pick(name){const re=new RegExp('^(?:async )?function '+name+'\\(','m'),m=re.exec(html);assert(m,name);const rest=html.slice(m.index),next=/\n(?:async )?function \w+\(/.exec(rest);return next?rest.slice(0,next.index):rest;}
const nodes={};function node(id){return nodes[id]||(nodes[id]={id,innerHTML:'',textContent:'',style:{},dataset:{},open:false,querySelector:()=>null,querySelectorAll:()=>[],showModal(){this.open=true;},close(){this.open=false;}});}
['searchPerformance','existingProductCampaigns','studioPerformance','performanceDialog','performanceBody','performanceTitle','v-bench','scanAudit'].forEach(node);node('v-bench').dataset.lane='product';
const ctx={console,Date,Number,String,Object,Array,Math,Intl,JSON,Set,Map,isFinite,Promise,setTimeout,clearTimeout,DASH:{accountTimezone:'America/Toronto',budgetCurrency:'CAD',lastMetrics:[]},STUDIO_GROWTH:null,PB:null,_pbError:'',_pbLoading:false,convBasis:'conversion',SCAN_AUDIT:null,OPP_RECONCILIATION:null,RESEARCH_STATUS:{pmax:{status:'ready'}},PMAXAT:null,OPPSAT:null,OPP_LAST_ERROR:null,PMAXERR:null,OPP_SCANNING:false,document:{getElementById:id=>nodes[id]||null,querySelector:()=>null},navigator:{},$:sel=>node(sel.replace(/^#/,'')),esc:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money:n=>'$'+Number(n||0).toFixed(2),timeago:()=> '1m',campDates:c=>({s:c.startDate,e:c.endDate}),statusBadge:c=>'<span>'+c.status+'</span>',pbEligible:l=>l.eligible===true&&l.evidenceVerified===true,pbLessonChannels:l=>l.channels||[],lineChart:()=>'<svg aria-label="daily"></svg>',fmtDayShort:x=>x,renderCommand:()=>{},renderFeed:()=>{},toast:()=>{},api:async()=>({ok:true})};
vm.createContext(ctx);for(const name of ['rpYmd','rpParse'])vm.runInContext(pick(name),ctx);
vm.runInContext(html.slice(html.indexOf('/* Each channel owns'),html.indexOf('function pmaxProductChoices(')),ctx);
for(const name of ['currentResearchChannel','researchState','friendlyResearchError','researchCheckChannel','auditTime','auditStatus','renderScanAudit'])vm.runInContext(pick(name),ctx);
const realRender=ctx.renderGrowthPerformance;let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS',name);}
(async()=>{
await test('all three lanes expose independent native presets and custom inputs',()=>{ctx.renderGrowthPerformance();for(const [lane,id] of [['search','searchPerformance'],['product','existingProductCampaigns'],['studio','studioPerformance']]){assert.match(node(id).innerHTML,new RegExp('data-perf-controls="'+lane+'"'));assert.match(node(id).innerHTML,/type="date"/);assert.match(node(id).innerHTML,/Custom dates/);}});
await test('account-local preset ranges include exact inclusive day count',()=>{const r=ctx.performanceRange({preset:'14d'});assert.equal((Date.parse(r.end)-Date.parse(r.start))/86400000+1,14);assert.equal(r.end,ctx.performanceToday());});
await test('custom ranges reject malformed, reversed, future and overlong dates',()=>{for(const r of [{start:'2026-02-30',end:'2026-03-01'},{start:'2026-02-02',end:'2026-02-01'},{start:'2099-01-01',end:'2099-01-02'},{start:'2024-01-01',end:'2026-01-01'}])assert(ctx.performanceValidRange(r));assert.equal(ctx.performanceValidRange({start:'2026-08-01',end:'2026-08-31'}),'');});
const c1={id:'1',name:'Product fixture',channel:'PERFORMANCE_MAX',status:'ENABLED',cost:9999,value:9999,conv:99,budget:28};ctx.DASH.lastMetrics=[c1,{id:'2',name:'BA · design-studio-pmax',channel:'PERFORMANCE_MAX',status:'PAUSED'},{id:'3',channel:'SEARCH',name:'Search fixture',status:'ENABLED'}];
await test('dashboard values never appear as selected-range metrics',()=>{ctx.renderGrowthPerformance('product');assert(!node('existingProductCampaigns').innerHTML.includes('9999'));assert(!node('existingProductCampaigns').innerHTML.includes('99</b>'));});
await test('Studio campaigns are excluded from the Product ads lane',()=>{assert.equal(ctx.existingProductCampaigns().length,1);assert.equal(ctx.performanceCampaigns('studio').length,1);});
await test('no-traffic metadata is not manufactured as zero conversion performance',()=>{assert.match(ctx.performanceCards(c1,null),/<b>—<\/b>/);assert(!ctx.performanceCards(c1,null).includes('$0.00'));});
await test('missing conversion-date data never falls back to click-date values',()=>{ctx.convBasis='conversion';const d={cdAvailable:false,currency:'CAD'};assert.equal(ctx.performanceMetric(c1,'conv',d),null);const text=ctx.performanceCards(c1,d);assert(!text.includes('99</b>'));assert.match(text,/CAD/);ctx.convBasis='click';assert.equal(ctx.performanceMetric(c1,'conv',d),99);ctx.convBasis='conversion';});
await test('date changes clear old values and stale async responses cannot win',async()=>{let pending=[];ctx.api=(_,r)=>new Promise(resolve=>pending.push({r,resolve}));const st=ctx.GROWTH_PERF.product;st.range={preset:'custom',start:'2026-08-01',end:'2026-08-02'};let p1=ctx.loadGrowthPerformance('product',true);assert.equal(st.data,null);st.range={preset:'custom',start:'2026-08-05',end:'2026-08-06'};let p2=ctx.loadGrowthPerformance('product',true);pending[1].resolve({ok:true,range:pending[1].r,snapshot:[{...c1,cost:22,convCd:1,valueCd:33}],currency:'USD',budgetCurrency:'CAD',cdAvailable:true});await p2;pending[0].resolve({ok:true,range:pending[0].r,snapshot:[{...c1,cost:111}]});await p1;assert.equal(st.data.snapshot[0].cost,22);assert.match(node('existingProductCampaigns').innerHTML,/2026-08-05 → 2026-08-06/);assert(!node('existingProductCampaigns').innerHTML.includes('$111.00'));});
await test('one lane date changes preserve other lane date selection',()=>{assert.equal(ctx.GROWTH_PERF.search.range.preset,'14d');assert.equal(ctx.GROWTH_PERF.studio.range.preset,'14d');});
await test('backend errors preserve selected range and hide all old totals',async()=>{ctx.api=async()=>({ok:false,error:'Provider unavailable'});await ctx.loadGrowthPerformance('product',true);assert.equal(ctx.GROWTH_PERF.product.data,null);assert.equal(ctx.GROWTH_PERF.product.range.start,'2026-08-05');assert.match(node('existingProductCampaigns').innerHTML,/Provider unavailable/);assert(!node('existingProductCampaigns').innerHTML.includes('$9999'));});
await test('backend mismatched report dates cannot be presented',async()=>{ctx.api=async()=>({ok:true,range:{start:'2026-08-01',end:'2026-08-02'},snapshot:[]});await ctx.loadGrowthPerformance('product',true);assert.match(ctx.GROWTH_PERF.product.error,/do not match/);});
await test('historically active removed campaigns are included in selected-range totals',()=>{ctx.GROWTH_PERF.product.data={snapshot:[{...c1,cost:10,convCd:1,valueCd:20},{...c1,id:'4',status:'REMOVED',historicalOnly:true,cost:5,convCd:1,valueCd:10}],currency:'USD'};const rows=ctx.performanceCampaigns('product');assert.equal(rows.length,2);assert.equal(ctx.performanceSummary(rows,ctx.GROWTH_PERF.product.data).cost,15);});
await test('View performance opens dialog without changing selected tab or navigation',()=>{let called=0;const orig=ctx.loadPerformanceDialog;ctx.loadPerformanceDialog=()=>called++;ctx.viewOpportunityCampaign('1','product');assert.equal(node('performanceDialog').open,true);assert.equal(node('v-bench').dataset.lane,'product');assert.equal(ctx.PERF_DIALOG.range.start,'2026-08-05');assert.equal(called,1);ctx.closePerformanceDialog();assert.equal(node('performanceDialog').open,false);assert.equal(ctx.PERF_DIALOG,null);ctx.loadPerformanceDialog=orig;});
await test('dialog requests only chosen campaign and uses same date interval',async()=>{const calls=[];ctx.PERF_DIALOG={id:'1',lane:'product',name:'Product fixture',range:{preset:'custom',start:'2026-08-01',end:'2026-08-02'}};ctx.api=async(a,r)=>{calls.push([a,r]);return a==='dailyStats'?{ok:true,range:r,campaigns:[{id:'1',name:'Product fixture',totals:{cost:2,convCd:1,valueCd:4},series:[]}],currency:'USD',cdAvailable:true}:{ok:true,currentVersion:1,versions:[{version:1,baseline:true,summary:'First observed version'}]};};await ctx.loadPerformanceDialog();const req=calls.find(x=>x[0]==='dailyStats')[1];assert.equal(req.campaignId,'1');assert.equal(req.start,'2026-08-01');assert.match(node('performanceBody').innerHTML,/\$2.00/);assert.match(node('performanceBody').innerHTML,/First observed version/);});
await test('version warnings show last recorded state and category summaries',()=>{let text=ctx.campaignVersionsHtml({warnings:['Images could not be observed'],currentVersion:2,versions:[{version:2,summary:'Updated',changes:[{categories:['Keywords','Images'],summary:'Two updates'}]}]});assert.match(text,/Images could not be observed/);assert.match(text,/Last recorded/);assert.match(text,/Keywords, Images/);assert(!text.includes('>Current<'));});
await test('first observed baseline is labelled without inventing old edits',()=>{assert.match(ctx.campaignVersionsHtml({currentVersion:1,versions:[{version:1,baseline:true}]}),/First observed version/);});
await test('campaign learning only shows guidance with matching recorded campaign use',()=>{ctx.PB={lessons:[{id:'match',rule:'Matched evidence',usage:{records:[{campaignId:'1'}]}},{id:'other',rule:'Unrelated evidence',usage:{records:[{campaignId:'99'}]}}]};let text=ctx.growthLearningHtml('product','1');assert.match(text,/Matched evidence/);assert(!text.includes('Unrelated evidence'));});
await test('research omits empty request payloads and never checks skipped sources',()=>{ctx.SCAN_AUDIT={checks:[{id:'pmax_merchant_catalogue',status:'skipped',label:'Product feed',meta:{}},{id:'pmax_store_signals',status:'ok',label:'Store signals',meta:[]}]};ctx.renderScanAudit();const text=node('scanAudit').innerHTML;assert(!text.includes('Request details'));assert.match(text,/Not verified/);});
await test('partial source failures stay visible in research detail',()=>{ctx.SCAN_AUDIT.checks.push({id:'pmax_paid_product_reporting',label:'Paid product history',status:'warning',error:'503 unavailable'});ctx.renderScanAudit();assert.match(node('scanAudit').innerHTML,/Paid product history/);assert.match(node('scanAudit').innerHTML,/Request details/);assert.match(node('scanAudit').innerHTML,/Partial data/);});
await test('Command Center has no 14d shortcut or cumulative-snapshot daily chart',()=>{const a=pick('cmdApplyRange'),render=pick('renderCommand');assert(!a.includes('val.preset==="14d"'));assert(!render.includes('DASH.metricsSeries'));assert(!render.includes('cmdMetrics||DASH.lastMetrics'));assert.match(a,/cmdRangeSeq/);assert.match(pick('loadDailyStats'),/_dailySeq/);});
await test('Command Center removed campaigns retain read-only schedules and budgets',()=>{assert.match(pick('campaignTable'),/historicalSchedule/);assert.match(pick('campaignTable'),/historicalBudget/);});
console.log(`${passed} focused UI behavior checks passed.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
