const assert=require('node:assert/strict');
const gate=require('../../netlify/functions/googleAdsVersionReview');
const clone=v=>JSON.parse(JSON.stringify(v));
const c='customers/123/', campaign=c+'campaigns/100', group=c+'adGroups/200', ad=c+'ads/300', link=c+'adGroupAds/200~300', assetGroup=c+'assetGroups/400', asset=c+'assets/500', assetLink=c+'assetGroupAssets/400~500~HEADLINE', keyword=c+'adGroupCriteria/200~600';
const base={schema:1,campaignId:'100',channel:'SEARCH',complete:true,components:{searchAds:[{resourceName:ad,adGroupAdResourceName:link,adGroup:group}],keywords:[{resourceName:keyword,adGroup:group,status:'ENABLED',negative:false,keyword:{text:'silver necklace',matchType:'PHRASE'}}],campaignNegatives:[{resourceName:c+'campaignCriteria/100~700',campaign,negative:true,keyword:{text:'free',matchType:'EXACT'}}],assetGroups:[{resourceName:assetGroup}],assetLinks:[{resourceName:assetLink,assetGroup,asset,fieldType:'HEADLINE'}],listingGroups:[{resourceName:c+'assetGroupListingGroupFilters/400~800',assetGroup}]}};
function item(ops,type='adAnalysisUpdate'){return {type,payload:{versionGuard:{campaignId:'100',expectedVersion:2,snapshotHash:'a'.repeat(64)},versionChange:{campaignId:'100',sourceVersion:2,proposedVersion:3,...(type==='adVersionRestore'?{restoredFromVersion:1}:{})},mutateOperations:ops}};}
const rsa=()=>({adOperation:{update:{resourceName:ad,responsiveSearchAd:{headlines:[{text:'Handmade silver necklaces'}]}},updateMask:'responsive_search_ad.headlines'}});
let passed=0;
function good(name,run){assert.doesNotThrow(run,name);passed++;}
function bad(name,run,pattern){assert.throws(run,pattern,name);passed++;}
const check=(x,s=base,t)=>gate.assertVersionOperationScope(x,s,'123',t);
good('existing Search ad stays in its group',()=>check(item([rsa()])));
const cross=rsa();cross.adOperation.update.resourceName=c+'ads/999';
bad('same account, different campaign ad is rejected',()=>check(item([cross])),/outside this campaign/);
const otherAccount=rsa();otherAccount.adOperation.update.resourceName='customers/987/ads/300';
bad('cross-account resource is rejected',()=>check(item([otherAccount])),/different Google Ads account/);
const unsafe=rsa();unsafe.adOperation.updateMask='status';
bad('unreviewed ad field mask is rejected',()=>check(item([unsafe])),/mask exceeds/);
const extra=rsa();extra.adOperation.update.trackingUrlTemplate='https://elsewhere.test';
bad('extra ad field cannot be smuggled',()=>check(item([extra])),/fields outside/);
const merchant=item([rsa()]);merchant.payload.merchantPatch={};
bad('Merchant publication cannot enter Google path',()=>gate.validateVersionApproval(merchant,'123'),/Direct Merchant publication is not supported/);
bad('new ad identity is forbidden',()=>check(item([{adGroupAdOperation:{create:{adGroup:group,ad:{}}}}])),/preserve the existing/);
good('pause existing keyword',()=>check(item([{adGroupCriterionOperation:{update:{resourceName:keyword,status:'PAUSED'},updateMask:'status'}}])));
bad('different ad group keyword rejected',()=>check(item([{adGroupCriterionOperation:{update:{resourceName:c+'adGroupCriteria/201~600',status:'PAUSED'},updateMask:'status'}}])),/outside this campaign/);
bad('positive keyword must be paused',()=>check(item([{adGroupCriterionOperation:{remove:keyword}}])),/must be paused/);
good('restore removes original negative safely',()=>check(item([{campaignCriterionOperation:{remove:c+'campaignCriteria/100~700'}}],'adVersionRestore'),base,base));
bad('cross-campaign negative rejected',()=>check(item([{campaignCriterionOperation:{remove:c+'campaignCriteria/999~700'}}],'adVersionRestore'),base,base),/outside this campaign/);
bad('restore requires archived target snapshot',()=>check(item([rsa()],'adVersionRestore')),/original saved restoration/);
const foreignTarget=clone(base);foreignTarget.campaignId='999';
bad('another campaign cannot serve as restore target',()=>check(item([rsa()],'adVersionRestore'),base,foreignTarget),/original saved restoration/);
const temp=c+'assets/-970000';
const textOps=[{assetOperation:{create:{resourceName:temp,textAsset:{text:'Handmade charm necklaces'}}}},{assetGroupAssetOperation:{remove:assetLink}},{assetGroupAssetOperation:{create:{assetGroup,asset:temp,fieldType:'HEADLINE'}}}];
good('replace text asset while keeping asset group',()=>check(item(textOps)));
const foreignGroup=clone(textOps);foreignGroup[2].assetGroupAssetOperation.create.assetGroup=c+'assetGroups/999';
bad('asset cannot attach to unrelated group',()=>check(item(foreignGroup)),/outside this campaign/);
bad('unattached new asset rejected',()=>check(item([textOps[0]])),/without a reviewed campaign attachment/);
const duplicate=clone(textOps);duplicate.unshift(textOps[0]);
bad('duplicate temporary asset identity rejected',()=>check(item(duplicate)),/unique temporary identity/);
bad('existing asset rewrite forbidden',()=>check(item([{assetOperation:{update:{resourceName:asset,textAsset:{text:'Rewrite'}}}}])),/cannot be rewritten/);
const archived=clone(base),oldAsset=c+'assets/501';archived.components.assetLinks[0].asset=oldAsset;
const restoreLink=[{assetGroupAssetOperation:{create:{assetGroup,asset:oldAsset,fieldType:'HEADLINE'}}}];
good('previous version asset can return',()=>check(item(restoreLink,'adVersionRestore'),base,archived));
bad('unverified previous asset rejected',()=>check(item(restoreLink,'adVersionRestore'),base,base),/not in the current campaign/);
bad('analysis cannot create arbitrary criteria',()=>check(item([{adGroupCriterionOperation:{create:{adGroup:group,status:'ENABLED',negative:false,keyword:{text:'charm',matchType:'EXACT'}}}}])),/cannot create new keyword/);
const filterTemp=c+'assetGroupListingGroupFilters/400~-800001';
const filterOps=[{assetGroupListingGroupFilterOperation:{remove:c+'assetGroupListingGroupFilters/400~800'}},{assetGroupListingGroupFilterOperation:{create:{resourceName:filterTemp,assetGroup,type:'UNIT_INCLUDED',listingSource:'SHOPPING'}}}];
good('restore existing product-group identity',()=>check(item(filterOps,'adVersionRestore'),base,base));
bad('analysis cannot modify product selection directly',()=>check(item(filterOps)),/require a saved restoration/);
const wrongParent=clone(filterOps);wrongParent[1].assetGroupListingGroupFilterOperation.create.parentListingGroupFilter=c+'assetGroupListingGroupFilters/999~800';
bad('product filter parent must belong to same group',()=>check(item(wrongParent,'adVersionRestore'),base,base),/parent belongs/);
const incomplete=clone(base);incomplete.complete=false;
bad('partial source snapshot rejected',()=>check(item([rsa()]),incomplete),/Complete settings/);
bad('out-of-snapshot extension mutation rejected',()=>check(item([{campaignAssetOperation:{remove:c+'campaignAssets/100~500~SITELINK'}}])),/not covered by the saved/);
const wrongVersion=item([rsa()]);wrongVersion.payload.versionChange.sourceVersion=1;
bad('version badge cannot hide a different source',()=>check(wrongVersion),/does not match/);
const jump=item([rsa()]);jump.payload.versionChange.proposedVersion=4;
bad('one approval cannot skip version numbers',()=>check(jump),/does not match/);
console.log(passed+' version-scope checks passed');
