'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {pathToFileURL}=require('node:url'),{JSDOM}=require('jsdom');
const projection=require('../../netlify/functions/googleAdsAdDesignResearch');
const root=path.resolve(__dirname,'../..'),version='a'.repeat(64),id='gid://shopify/Product/10';
function fixture(fetch){const dom=new JSDOM('<main id="fixture"></main>',{url:'https://sandbox.invalid/'});vm.runInNewContext(fs.readFileSync(path.join(root,'brites-growth.js'),'utf8'),{window:dom.window,document:dom.window.document,sessionStorage:dom.window.sessionStorage,fetch,URL});return {dom,ui:dom.window.BritesGrowth,root:dom.window.document.getElementById('fixture')};}
function evidence(){const now=Date.now(),product={id,productId:id,handle:'fixture-bunny',dossierVersion:version,title:'Fixture bunny',rank:1,status:'complete'};
const dossier={schema:1,productId:id,handle:product.handle,status:'approved',version,currentDossierVersion:version,savedAt:now,sources:[{id:'shop',url:'https://example.com/fixture',title:'Fixture source',excerpt:'Simulated fixture facts.',reviewed:true,checkedAt:now}],facts:[],meanings:[],competitors:[],buyerIntents:['Fixture gift intent'],recommendations:[{channel:'keywords',basis:'hypothesis',action:'Test fixture gift intent.',measure:'Qualified visits.',sourceIds:['shop'],keywords:['fixture gift']},{channel:'negatives',basis:'hypothesis',action:'Review template intent.',measure:'Search-term relevance.',sourceIds:['shop'],negativeKeywords:['free template']}]};
const packet=projection.projectRecommendations(dossier,new Set(['shop'])).operatorReviewPacket;return {product,dossier,result:{dossiers:[dossier],productIssueState:'available',productIssues:[],operatorReviews:[{productId:id,handle:product.handle,dossierVersion:version,state:'pending_operator_review',operatorReviewPacket:packet}]}};}
const clone=value=>JSON.parse(JSON.stringify(value));
test('review projection and renderer expose immutable IDs, full version, citations and separated terms without apply controls',()=>{const f=fixture(),e=evidence(),p=f.ui.operatorReviewFor(e.result,e.product,e.dossier);assert.ok(p);f.ui.renderOperatorReview(f.root,e.result,e.product,e.dossier);assert.ok(f.root.textContent.includes(version));for(const c of p.candidates)assert.ok(f.root.textContent.includes(c.candidateId));assert.match(f.root.textContent,/Positive keyword hypotheses/);assert.match(f.root.textContent,/Negative keyword hypotheses/);assert.match(f.root.textContent,/No provider, campaign or budget writes/);assert.match(f.root.textContent,/No automatic activation/);assert.equal(f.root.querySelectorAll('button,input,form').length,0);assert.ok(f.root.querySelector('a[href="https://example.com/fixture"]'));f.dom.window.close();});
test('all identity, version, source, approval, issue and no-write failures withhold the entire packet',()=>{const f=fixture();const mutations=[
e=>e.product.dossierVersion='b'.repeat(64),e=>e.dossier.status='draft',e=>e.dossier.proposalOnly=true,e=>e.dossier.savedAt=Date.now()+120000,e=>e.result.productIssueState='unavailable',e=>e.result.productIssues=[{productId:id,issues:[{kind:'material',status:'open'}]}],e=>e.result.productIssues=[{productId:id,issues:[{kind:'history',status:'open'}]}],e=>e.dossier.sources[0].reviewed=false,e=>e.dossier.sources[0].checkedAt=Date.now()-31*86400000,e=>e.dossier.sources[0].url='javascript:alert(1)',e=>e.result.operatorReviews[0].state='held',e=>delete e.result.operatorReviews[0].operatorReviewPacket,
...['productId','handle','dossierVersion','state','providerWrites','campaignWrites','budgetWrites','automaticActivation'].map(field=>e=>e.result.operatorReviews[0].operatorReviewPacket[field]=field.endsWith('Writes')||field==='automaticActivation'?true:'foreign'),
e=>e.result.operatorReviews[0].operatorReviewPacket.candidates[0].sourceIds=['missing'],e=>e.result.operatorReviews[0].operatorReviewPacket.candidates[0].action='Different action',e=>e.result.operatorReviews[0].operatorReviewPacket.candidates[0].channel='concierge',e=>e.result.operatorReviews[0].operatorReviewPacket.candidateIds.push('rec_'+'9'.repeat(24)),e=>e.result.operatorReviews[0].operatorReviewPacket.positiveKeywords[0].candidateIds=[],e=>e.result.operatorReviews[0].operatorReviewPacket.positiveKeywords[0].sourceIds=[],e=>e.result.operatorReviews[0].operatorReviewPacket.negativeKeywords=[]];
for(const change of mutations){const e=clone(evidence());change(e);assert.equal(f.ui.operatorReviewFor(e.result,e.product,e.dossier),null);}f.dom.window.close();});
test('Unicode/whitespace positive-negative conflicts and duplicate candidates cannot enter review',()=>{const f=fixture(),e=evidence(),p=e.result.operatorReviews[0].operatorReviewPacket;e.dossier.recommendations[1].negativeKeywords=['ＦＩＸＴＵＲＥ   gift'];p.candidates[1].negativeKeywords=['ＦＩＸＴＵＲＥ   gift'];p.negativeKeywords[0].term='ＦＩＸＴＵＲＥ   gift';assert.equal(f.ui.operatorReviewFor(e.result,e.product,e.dossier),null);const d=evidence();d.result.operatorReviews[0].operatorReviewPacket.candidates[1].candidateId=d.result.operatorReviews[0].operatorReviewPacket.candidates[0].candidateId;assert.equal(f.ui.operatorReviewFor(d.result,d.product,d.dossier),null);f.dom.window.close();});
test('missing or held packet never turns raw recommendations into a review queue',()=>{const f=fixture(),e=evidence();delete e.result.operatorReviews;f.ui.renderOperatorReview(f.root,e.result,e.product,e.dossier);assert.match(f.root.textContent,/Review packet held or unavailable/);assert.ok(!f.root.textContent.includes(e.dossier.recommendations[0].action));assert.equal(f.root.querySelector('code'),null);f.dom.window.close();});
async function endpoint(){let source=fs.readFileSync(path.join(root,'netlify/functions/britesGrowthAds.js'),'utf8');for(const name of ['_britesGrowth.js','_britesGrowthDemand.js'])source=source.replace("'./"+name+"'",JSON.stringify(pathToFileURL(path.join(root,'netlify/functions',name)).href));return import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));}
test('bridge derives read-only packets only from current live identity and cleared private issue evidence without loading Ads engine',async()=>{const {createHandler}=await endpoint();let e=evidence(),loads=0,issues=[],issueFailure=false,product={id,handle:e.product.handle};const handler=createHandler({environment:()=>({BRITES_GROWTH_SANDBOX:'1',BRITES_GROWTH_ADMIN_KEY:'fixture-key'}),loadReviewProjection:async()=>projection,loadEngine:async()=>{loads++;throw Error('Provider engine must not run');},researchService:()=>({research:async()=>[e.dossier],getProduct:async()=>product,productIssues:async()=>{if(issueFailure)throw Error('Private details');return issues;}})});
const read=async()=>{const r=await handler(new Request('https://sandbox.invalid/api/growth-ads',{method:'POST',headers:{'X-Growth-Key':'fixture-key'},body:JSON.stringify({action:'growthResearchDossiers',productIds:['10']})}));assert.equal(r.status,200);return r.json();};
assert.equal((await read()).operatorReviews[0].state,'pending_operator_review');product={id,handle:'wrong-handle'};assert.equal((await read()).operatorReviews[0].state,'unavailable');product={id,handle:e.product.handle};e.dossier.sources[0].reviewed=false;assert.equal((await read()).operatorReviews[0].state,'unavailable');e=evidence();issues=[{productId:id,issues:[{kind:'material',status:'open'}]}];const held=await read();assert.equal(held.operatorReviews[0].state,'held');assert.equal(held.operatorReviews[0].operatorReviewPacket,undefined);issues=[];issueFailure=true;assert.equal((await read()).operatorReviews[0].state,'held');assert.equal(loads,0);});
test('mounted Ads research view reads a packet alongside dossier data and withholds it after version mismatch',async()=>{const f=fixture(),e=evidence();let scenario='ready',writes=0;e.product.id='rank-001';await f.ui.mount(f.root,{request:async op=>{if(op==='status')return {at:Date.now(),queue:[e.product],counts:{},control:{},blockers:[]};if(op.startsWith('research?')){const result=clone(e.result);if(scenario==='stale')result.operatorReviews[0].operatorReviewPacket.dossierVersion='b'.repeat(64);return result;}if(op.startsWith('demand?'))return {products:[]};writes++;throw Error('Unexpected write operation');}});await f.root.querySelector('.row').onclick();assert.match(f.root.textContent,/Pending operator review · hypotheses/);assert.ok(f.root.textContent.includes(version));scenario='stale';await f.root.querySelector('.row').onclick();assert.match(f.root.textContent,/Review packet held or unavailable/);assert.ok(!f.root.textContent.includes('rec_'));assert.equal(writes,0);assert.ok(![...f.root.querySelectorAll('button')].some(button=>/^(apply|approve|activate|publish)/i.test(button.textContent)));f.dom.window.close();});
test('standalone authenticated workspace requests current packets from the protected bridge and never falls back to packetless core research',async()=>{const e=evidence(),calls=[];let fail=false;e.product.id='rank-001';const f=fixture(async(url,options)=>{calls.push({url,options});if(url==='/api/growth/status')return {ok:true,json:async()=>({at:Date.now(),queue:[e.product],counts:{},control:{},blockers:[]})};if(url==='/api/growth-ads')return fail?{ok:false,status:503,json:async()=>({error:'Review unavailable.'})}:{ok:true,json:async()=>clone(e.result)};if(url.startsWith('/api/growth/demand?'))return {ok:true,json:async()=>({products:[]})};throw Error('Unexpected transport '+url);});f.dom.window.sessionStorage.setItem('brites-growth-key','fixture-private-key');await f.ui.mount(f.root);await f.root.querySelector('.row').onclick();assert.match(f.root.textContent,/Pending operator review · hypotheses/);const read=calls.find(call=>call.url==='/api/growth-ads');assert.equal(read.options.method,'POST');assert.equal(read.options.credentials,'same-origin');assert.equal(read.options.headers['X-Growth-Key'],'fixture-private-key');assert.deepEqual(JSON.parse(read.options.body),{action:'growthResearchDossiers',productIds:[id]});assert.ok(!calls.some(call=>call.url.startsWith('/api/growth/research?')));assert.equal(calls.find(call=>call.url==='/api/growth/status').options.method,'GET');assert.equal(calls.find(call=>call.url.startsWith('/api/growth/demand?')).options.method,'GET');fail=true;await f.root.querySelector('.row').onclick();assert.match(f.root.textContent,/Review unavailable/);assert.ok(!f.root.textContent.includes('rec_'));assert.ok(!calls.some(call=>call.url.startsWith('/api/growth/research?')));assert.ok(!f.root.textContent.includes('fixture-private-key'));f.dom.window.close();});
