'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {JSDOM}=require('jsdom');
const projection=require('../../netlify/functions/googleAdsAdDesignResearch');
const readOnly=require('../../netlify/functions/_britesGrowthAdsReadOnly');
const NOW=Date.now(),ID='gid://shopify/Product/21',VERSION='b'.repeat(64);
function dossier(){return {productId:ID,handle:'source-bound-star',status:'approved',version:VERSION,currentDossierVersion:VERSION,savedAt:NOW,evidenceHolds:{},sources:[{id:'shop',url:'https://example.com/star',title:'Star source',excerpt:'A reviewed source revision.',reviewed:true,checkedAt:NOW}],recommendations:[{channel:'keywords',basis:'hypothesis',action:'Test star gift intent.',measure:'Qualified visits.',sourceIds:['shop'],keywords:['star gift']}],buyerIntents:['star gift'],facts:[],meanings:[],competitors:[]};}
function packet(value){return readOnly.bindOperatorPacketSources(projection.projectRecommendations(value,new Set(['shop']),NOW),value).operatorReviewPacket;}
function ui(){const dom=new JSDOM('<div></div>',{url:'https://sandbox.invalid'}),context=vm.createContext(dom.window);vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../brites-growth.js'),'utf8'),context);return {dom,api:dom.window.BritesGrowth};}
function evidence(value,p){return {product:{productId:ID,handle:value.handle,dossierVersion:VERSION},result:{productIssueState:'available',productIssues:[],operatorReviewBindingRequired:true,operatorReviews:[{productId:ID,handle:value.handle,dossierVersion:VERSION,state:'pending_operator_review',operatorReviewPacket:p}]}};}
test('server packet is bound to exact reviewed source revision and its complete packet fingerprint',()=>{const value=dossier(),p=packet(value);assert.equal(p.sourceBindingSchema,1);assert.equal(p.sourceVersionBound,true);assert.match(p.packetVersion,/^[a-f0-9]{64}$/);assert.equal(p.sourceBindings.length,1);assert.equal(p.sourceBindings[0].excerpt,value.sources[0].excerpt);assert.equal(readOnly.operatorPacketHasExactSourceBindings(p,value),true);const changed=dossier();changed.sources[0].excerpt='A later reviewed source revision.';assert.equal(readOnly.operatorPacketHasExactSourceBindings(p,changed),false);const tampered=structuredClone(p);tampered.candidates[0].action='Different action';assert.equal(readOnly.operatorPacketHasExactSourceBindings(tampered,value),false);});
test('operator UI fails closed when the required source revision no longer matches',()=>{const value=dossier(),p=packet(value),{dom,api}=ui(),e=evidence(value,p);assert.ok(api.operatorReviewFor(e.result,e.product,value,NOW));value.sources[0].title='Changed source title';assert.equal(api.operatorReviewFor(e.result,e.product,value,NOW),null);dom.window.close();});
test('operator UI fails closed when a required binding is stripped',()=>{const value=dossier(),p=packet(value),{dom,api}=ui(),e=evidence(value,p);delete p.sourceBindings;assert.equal(api.operatorReviewFor(e.result,e.product,value,NOW),null);dom.window.close();});
