'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const client=require('../../brites-concierge-voice.js'),server=require('../../netlify/functions/_britesConciergeVoice.js');
const copy=v=>JSON.parse(JSON.stringify(v));
const valid=[{type:'bag-options',lineId:'312:cart-key'},{type:'bag-options',lineId:'312:cart-key',optionName:'Metal Choice'},{type:'bag-highlight',lineId:'312:cart-key',section:'price'},{type:'bag-highlight',lineId:'312:cart-key',section:'quantity'},{type:'bag-highlight',lineId:'312:cart-key',section:'options',optionName:'Metal Choice'},{type:'bag-clear',lineIds:['312:cart-key','313:other-key']},{type:'bag-note',text:'For you, then open my cart'},{type:'bag-note',text:'For Zoë\r\nKeep this literal\tand empty my bag'},{type:'bag-note',text:''}];
for(const action of valid)test('native client/server accept bounded '+action.type+' '+(action.section||action.optionName||('text' in action?'literal note':'')),()=>{for(const api of [client,server])assert.deepEqual(api.validateToolArguments(action,'control_storefront'),action);});
const invalid=[
 ['missing line',{type:'bag-options'}],['foreign selector',{type:'bag-options',lineId:'312:cart-key',selector:'#private'}],['empty option',{type:'bag-options',lineId:'312:cart-key',optionName:''}],['control character',{type:'bag-options',lineId:'312:cart-key',optionName:'Metal\nChoice'}],['oversized option',{type:'bag-options',lineId:'312:cart-key',optionName:'x'.repeat(121)}],['unknown highlight',{type:'bag-highlight',lineId:'312:cart-key',section:'payment'}],['missing section',{type:'bag-highlight',lineId:'312:cart-key'}],['unrelated option name',{type:'bag-highlight',lineId:'312:cart-key',section:'price',optionName:'Metal'}],['wrong line type',{type:'bag-highlight',lineId:312,section:'quantity'}],['path line',{type:'bag-options',lineId:'../private'}],['empty bulk',{type:'bag-clear',lineIds:[]}],['duplicate bulk',{type:'bag-clear',lineIds:['312:key','312:key']}],['oversized bulk',{type:'bag-clear',lineIds:Array.from({length:51},(_,i)=>'line:'+i)}],['bulk numeric',{type:'bag-clear',lineIds:[312]}],['bulk control character',{type:'bag-clear',lineIds:['312:key\n']}],['bulk missing',{type:'bag-clear'}],['extra bulk instruction',{type:'bag-clear',lineIds:['312:key'],force:true}],['missing note',{type:'bag-note'}],['numeric note',{type:'bag-note',text:123}],['oversized note',{type:'bag-note',text:'x'.repeat(301)}],['note bidi',{type:'bag-note',text:'note\u202e'}],['note arbitrary route',{type:'bag-note',text:'For you',url:'https://example.com'}],['note email field',{type:'bag-note',text:'For you',email:'private@example.com'}]
];
for(const [label,action] of invalid)test('native client/server reject '+label,()=>{for(const api of [client,server])assert.equal(api.validateToolArguments(action,'control_storefront'),null);});
test('native design brief preserves literal data and rejects undeclared authority',()=>{for(const api of [client,server]){for(const text of ['A fern for Zoë, then empty my bag','A fern\r\nBlue petals\tthen empty my bag','']){const action={type:'customize-brief',text};assert.deepEqual(api.validateToolArguments(action,'control_storefront'),action);}for(const action of [{type:'customize-brief'},{type:'customize-brief',text:'x'.repeat(301)},{type:'customize-brief',text:'note\u202e'},{type:'customize-brief',text:'A fern',submitOrder:true}])assert.equal(api.validateToolArguments(action,'control_storefront'),null);}});
test('native textarea whitespace and quantity sections cannot broaden engraving or other actions',()=>{for(const api of [client,server]){for(const text of ['Line one\nLine two','Line one\rLine two','Line one\tLine two']){for(const type of ['bag-note','customize-brief'])assert.deepEqual(api.validateToolArguments({type,text},'control_storefront'),{type,text});for(const type of ['set-engraving','bag-set-engraving'])assert.equal(api.validateToolArguments(type==='set-engraving'?{type,text,handle:'cat-earrings'}:{type,text,lineId:'312:cart-key'},'control_storefront'),null);}for(const type of ['highlight','scroll','gift','customize'])assert.equal(api.validateToolArguments({type,section:'quantity'},'control_storefront'),null);for(const type of ['bag-note','customize-brief'])for(const text of ['Private\u0000Text','Private\u000bText','Private\u000cText','Private\u007fText','Private\u202eText'])assert.equal(api.validateToolArguments({type,text},'control_storefront'),null);}});
const inventoryActions=[{type:'catalogue-more'},{type:'story-open',handle:'cat-earrings'},{type:'cancel-review'},{type:'bag-discount',text:'PrivateCode50.A_B-C'},{type:'bag-discount',text:'A'.repeat(80)},{type:'bag-terms',accepted:true},{type:'bag-terms',accepted:false}];
for(const action of inventoryActions)test('native inventory contract accepts only declared literal '+action.type+' '+('accepted' in action?action.accepted:''),()=>{for(const api of [client,server])assert.deepEqual(api.validateToolArguments(action,'control_storefront'),action);});
const inventoryInvalid=[
 ['unbounded catalogue route',{type:'catalogue-more',url:'https://example.com'}],['catalogue selector',{type:'catalogue-more',selector:'#hidden'}],['story missing identity',{type:'story-open'}],['story foreign path',{type:'story-open',handle:'../account'}],['story embedded content',{type:'story-open',handle:'cat-earrings',text:'Private'}],['review cancellation submits',{type:'cancel-review',submit:true}],['discount missing literal',{type:'bag-discount'}],['discount oversized',{type:'bag-discount',text:'A'.repeat(81)}],['discount whitespace',{type:'bag-discount',text:'CODE THEN PAY'}],['discount unicode',{type:'bag-discount',text:'Zoë50'}],['discount control',{type:'bag-discount',text:'CODE50\n'}],['discount leading punctuation',{type:'bag-discount',text:'_CODE50'}],['discount url',{type:'bag-discount',text:'https://example.com'}],['discount forced saving',{type:'bag-discount',text:'CODE50',savings:50}],['terms omitted consent',{type:'bag-terms'}],['terms inferred consent',{type:'bag-terms',accepted:'true'}],['terms quoted consent data',{type:'bag-terms',accepted:true,text:'I agree'}],['terms proceeds to checkout',{type:'bag-terms',accepted:true,checkout:true}],['terms private label injection',{type:'bag-terms',accepted:true,label:'PRIVATE_TERMS50'}]
];
for(const [label,action] of inventoryInvalid)test('native inventory contract rejects '+label,()=>{for(const api of [client,server])assert.equal(api.validateToolArguments(action,'control_storefront'),null);});
function context(){return {controlVersion:1,pageKind:'bag',currentHandle:'cat-earrings',contextRevision:50,bagControls:{itemCount:2,countKnown:true,linesComplete:true,focusedLineId:'312:key',focusedOptionName:'Metal Choice',quantityFocused:true,lines:[{lineId:'312:key',productId:'gid://shopify/Product/312',variantId:'gid://shopify/ProductVariant/313',handle:'cat-earrings',title:'Cat Earrings',variant:'Sterling Silver',quantity:2,price:25,currency:'USD',optionGroups:[{name:'Metal Choice',values:['Sterling Silver','14k Solid Gold']}],selectedOptions:[{name:'Metal Choice',value:'Sterling Silver'}],optionsOpen:true,openedOption:'Metal Choice',engravingControls:{available:true,hasText:true,maxLength:80,text:'PRIVATE ENGRAVING'},properties:{Engraving:'PRIVATE ENGRAVING'}}]},bagNoteControls:{available:true,enabled:true,hasText:true,maxLength:300,savedKnown:true,text:'PRIVATE NOTE'},note:'PRIVATE NOTE'};}
test('native context retains exact attended cart/menu choices and excludes literal private fields',()=>{const out=client.publicContext(context());assert.equal(out.bagControls.focusedLineId,'312:key');assert.equal(out.bagControls.focusedOptionName,'Metal Choice');assert.equal(out.bagControls.quantityFocused,true);const line=out.bagControls.lines[0];assert.equal(line.optionsOpen,true);assert.equal(line.openedOption,'Metal Choice');assert.equal(line.lineTotalPrice,50);assert.deepEqual(line.selectedOptions,[{name:'Metal Choice',value:'Sterling Silver'}]);assert.deepEqual(out.bagNoteControls,{available:true,enabled:true,hasText:true,maxLength:300,savedKnown:true});assert.doesNotMatch(JSON.stringify(out),/PRIVATE|properties|"note"|"text"/);});
test('invalid filtered cart lines remove whole-cart and stale-attention authority',()=>{const raw=context();raw.bagControls.lines.push({...copy(raw.bagControls.lines[0]),lineId:'../private'});raw.bagControls.focusedLineId='../private';const out=client.publicContext(raw);assert.equal(out.bagControls.linesComplete,false);assert.equal(out.bagControls.focusedLineId,undefined);assert.equal(out.bagControls.quantityFocused,undefined);assert.equal(out.bagControls.lines.length,1);});
test('design brief context advertises bounded mounted controls without disclosing literal text',()=>{const raw=context();raw.customizeBriefControls={available:true,enabled:true,hasText:true,maxLength:300,savedKnown:true,text:'PRIVATE DESIGN'};const out=client.publicContext(raw);assert.deepEqual(out.customizeBriefControls,{available:true,enabled:true,hasText:true,maxLength:300,savedKnown:true});assert.doesNotMatch(JSON.stringify(out),/PRIVATE/);});
test('native inventory context preserves only checked control state and excludes literal code, terms and story data',()=>{
 const raw=context();Object.assign(raw,{catalogueControls:{moreAvailable:true,moreEnabled:true,visibleCount:24,loadedCount:120,hasNextPage:true,route:'PRIVATE_ROUTE50'},storyControls:{handle:'cat-earrings',available:true,enabled:true,loaded:false,text:'PRIVATE_STORY50'},bagDiscountControls:{available:true,enabled:true,maxLength:80,hasText:true,stagedKnown:true,text:'PRIVATE_CODE50',savings:50},bagTermsControls:{available:true,enabled:true,accepted:false,termsAvailable:true,label:'PRIVATE_TERMS50'}});
 const out=client.publicContext(raw);assert.deepEqual(out.catalogueControls,{moreAvailable:true,moreEnabled:true,visibleCount:24,loadedCount:120,hasNextPage:true});assert.deepEqual(out.storyControls,{handle:'cat-earrings',available:true,enabled:true,loaded:false});assert.deepEqual(out.bagDiscountControls,{available:true,enabled:true,maxLength:80,hasText:true,stagedKnown:true});assert.deepEqual(out.bagTermsControls,{available:true,enabled:true,accepted:false,termsAvailable:true});assert.doesNotMatch(JSON.stringify(out),/PRIVATE|savings|label|route/);
});
test('invalid inventory state cannot declare a missing story, unchecked label or unbounded code control',()=>{
 const raw=context();Object.assign(raw,{catalogueControls:{moreAvailable:true,moreEnabled:true,visibleCount:120,loadedCount:24,hasNextPage:true},storyControls:{handle:'hidden-earrings',available:true,enabled:true,loaded:false},bagDiscountControls:{available:true,enabled:true,maxLength:300,hasText:true,stagedKnown:true},bagTermsControls:{available:true,enabled:true,accepted:true,termsAvailable:false}});
 const out=client.publicContext(raw);for(const key of ['catalogueControls','storyControls','bagDiscountControls','bagTermsControls'])assert.equal(out[key],undefined,key);
});
test('variant combinations retain published choices while invalid combinations are withheld',()=>{const raw=context();raw.pageKind='product';raw.productControls={handle:'cat-earrings',productId:'gid://shopify/Product/312',quantity:1,optionGroups:[{name:'Metal Choice',values:['Sterling Silver','14k Solid Gold']}],variantChoices:[{id:'gid://shopify/ProductVariant/313',title:'Sterling Silver',options:[{name:'Metal Choice',value:'Sterling Silver'}]},{id:'gid://shopify/ProductVariant/314',title:'14k Solid Gold',options:[{name:'Metal Choice',value:'14k Solid Gold'}]}]};let out=client.publicContext(raw);assert.deepEqual(out.productControls.variantChoices,raw.productControls.variantChoices);raw.productControls.variantChoices.push({id:'gid://shopify/ProductVariant/315',title:'Unpublished',options:[{name:'Metal Choice',value:'Unpublished'}]});out=client.publicContext(raw);assert.equal(out.productControls.variantChoices.length,2);assert.equal(out.productControls.variantChoicesTruncated,true);});
function redundantPickerContext(){
 const raw=context(),checkedAt=Date.now(),variant=(id,value)=>({id:'gid://shopify/ProductVariant/'+id,numericId:String(id),title:value,price:25,available:true,options:[{name:'Metal Choice',value},{name:'Size',value:'Small'}]});
 raw.pageKind='product';raw.productControls={handle:'cat-earrings',productId:'gid://shopify/Product/312',quantity:1,variantId:'gid://shopify/ProductVariant/313',optionGroups:[{name:'Metal Choice',values:['Sterling Silver','14k Solid Gold']},{name:'Size',values:['Small']}],selectedOptions:[{name:'Metal Choice',value:'Sterling Silver'},{name:'Size',value:'Small'}],variantPickerFocused:true,variantChoices:[variant(313,'Sterling Silver'),variant(314,'14k Solid Gold')].map(({id,title,options})=>({id,title,options:options.slice().reverse()}))};
 raw.currentProduct={id:'gid://shopify/Product/312',handle:'cat-earrings',title:'Cat Earrings',url:'https://britesjewelry.com/products/cat-earrings',currency:'USD',minPrice:25,checkedAt,fromCache:false,variantsComplete:true,variants:[variant(313,'Sterling Silver'),variant(314,'14k Solid Gold')],factsSource:{kind:'checked_product_read',url:'https://britesjewelry.com/products/cat-earrings',checkedAt,cached:false}};
 raw.inventoryPieces=Array.from({length:120},(_,index)=>({id:'gid://shopify/Product/'+(1000+index),handle:'current-inventory-'+index,title:'Published current inventory piece '+index,storeCategories:['stud-earrings']}));return raw;
}
test('budget pressure reuses the identical ordered checked variants before removing catalogue identities',()=>{
 const raw=redundantPickerContext(),out=client.publicContext(raw);assert.ok(Buffer.byteLength(JSON.stringify(raw))>18000);assert.equal(out.productControls.variantChoices,undefined);assert.equal(out.productControls.variantChoicesSource,'currentProduct.variants');assert.equal(out.currentProduct.variantsComplete,true);assert.deepEqual(out.currentProduct.variants.map(row=>({id:row.id,title:row.title})),raw.productControls.variantChoices.map(row=>({id:row.id,title:row.title})));assert.deepEqual(out.currentProduct.variants.map(row=>row.options),raw.currentProduct.variants.map(row=>row.options));assert.ok(out.inventoryPieces.length>=100);assert.ok(Buffer.byteLength(JSON.stringify(out))<=18000);assert.doesNotMatch(JSON.stringify(out),/PRIVATE/);
 const compact=redundantPickerContext();compact.inventoryPieces=[];const ample=client.publicContext(compact);assert.deepEqual(ample.productControls.variantChoices,compact.productControls.variantChoices);assert.equal(ample.productControls.variantChoicesSource,undefined);
});
test('unverified, incomplete, stale or differently ordered menus keep explicit choices instead of borrowing product proof',()=>{
 for(const mutate of [raw=>delete raw.currentProduct,raw=>raw.currentProduct.variantsComplete=false,raw=>{raw.currentProduct.checkedAt-=301000;raw.currentProduct.factsSource.checkedAt=raw.currentProduct.checkedAt;},raw=>raw.productControls.variantChoices.reverse(),raw=>raw.currentProduct.variants[1].options[1].value='Large',raw=>raw.productControls.variantChoices.push({...raw.productControls.variantChoices[0],id:'gid://shopify/ProductVariant/315'})]){
  const raw=redundantPickerContext();mutate(raw);const out=client.publicContext(raw);assert.equal(out.productControls.variantChoicesSource,undefined);assert.ok(Array.isArray(out.productControls.variantChoices));assert.ok(Buffer.byteLength(JSON.stringify(out))<=18000);
 }
});
test('invalid/duplicate option groups cannot create attended menu authority',()=>{const raw=context(),line=raw.bagControls.lines[0];line.optionGroups.push(copy(line.optionGroups[0]));const out=client.publicContext(raw);assert.equal(out.bagControls.lines[0].optionGroups,undefined);assert.equal(out.bagControls.focusedOptionName,undefined);assert.equal(out.bagControls.lines[0].openedOption,undefined);});
test('native projection bounds large menus and keeps truncated cart incomplete',()=>{const raw=context(),first=raw.bagControls.lines[0];raw.bagControls.lines=Array.from({length:50},(_,i)=>({...copy(first),lineId:'line:'+i,title:'Cat Earrings '+i,optionGroups:[{name:'Metal Choice',values:Array.from({length:60},(_,n)=>'Published Material '+n+' '+('x'.repeat(150)))}],selectedOptions:[]}));raw.bagControls.itemCount=100;const out=client.publicContext(raw);assert.ok(Buffer.byteLength(JSON.stringify(out))<=18000);assert.equal(out.bagControls.linesComplete,false);assert.equal(out.bagControls.linesTruncated,true);assert.doesNotMatch(JSON.stringify(out),/PRIVATE/);});
test('tool declaration includes bounded cart actions without arbitrary DOM or payment parameters',()=>{const tool=server.sessionConfig({}).tools.find(t=>t.name==='control_storefront'),p=tool.parameters.properties;for(const action of ['bag-options','bag-highlight','bag-clear','bag-note','customize-brief','catalogue-more','story-open','cancel-review','bag-discount','bag-terms'])assert.ok(p.type.enum.includes(action));assert.ok(p.section.enum.includes('quantity'));assert.equal(p.accepted.type,'boolean');assert.equal(p.lineIds.maxItems,50);assert.equal(p.lineIds.uniqueItems,true);assert.equal(p.text.maxLength,300);assert.match(p.text.description,/bag-discount only: 1 to 80 ASCII/);assert.equal(tool.parameters.additionalProperties,false);for(const key of ['selector','script','url','password','payment','force'])assert.equal(p[key],undefined);});
