'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom'),Shopify=require('../../brites-shopify-storefront-adapter.js');
const clone=value=>JSON.parse(JSON.stringify(value)),settle=async()=>{for(let i=0;i<4;i++)await new Promise(setImmediate);};
function product(){const variants=[];for(const metal of ['Silver','Gold'])for(const length of ['16 inches','18 inches'])variants.push({id:'gid://shopify/ProductVariant/'+(5001+variants.length),title:metal+' / '+length,price:40+variants.length*10,available:true,availabilityKnown:true,options:[{name:'Metal',value:metal},{name:'Length',value:length}]});return {id:'gid://shopify/Product/500',handle:'fern-necklace',title:'Fern Necklace',type:'Necklace',description:'Published fern necklace.',url:'https://britesjewelry.com/products/fern-necklace',currency:'USD',variantsComplete:true,options:[{name:'Metal',values:['Silver','Gold']},{name:'Length',values:['16 inches','18 inches']}],variants};}
function sandbox(t,{saved,cart=false,onFetch}={}){
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',error=>errors.push(error));const dom=new JSDOM(fs.readFileSync(require.resolve('../../concierge-sandbox.html'),'utf8'),{url:'https://preview.example/concierge-sandbox.html'+(cart?'?cart=1':''),runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document,p=product(),requests=[],scrolls=[];
 delete d.body.dataset.catalogueSeed;delete d.body.dataset.inventoryPreload;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=function(){scrolls.push(this);};w.scrollTo=()=>{};if(saved)for(const [key,value]of saved)w.sessionStorage.setItem(key,value);
 w.fetch=async(url,init={})=>{requests.push({url,init});const handled=await onFetch?.({url,init,p,w,d});if(handled)return handled;return {ok:true,json:async()=>url.includes('/product?')?{live:true,checkedAt:Date.now(),product:clone(p)}:url.includes('storefront-services')?{guidance:{},offers:{items:[]}}:{live:true,checkedAt:Date.now(),products:[clone(p)],pageInfo:{hasNextPage:false,endCursor:null}}};};w.eval(fs.readFileSync(require.resolve('../../concierge-sandbox.js'),'utf8'));t.after(()=>w.close());
 return {w,d,p,requests,errors,scrolls,get store(){return w.BritesSandboxStorefront;},ready:settle,cart:()=>JSON.parse(w.sessionStorage.getItem('brites-sandbox-cart')||'[]'),save:()=>Object.keys(w.sessionStorage).map(key=>[key,w.sessionStorage.getItem(key)]),async add(index=0,quantity=2){assert.equal((await this.store.execute({type:'open',handle:p.handle})).ok,true);assert.equal((await this.store.execute({type:'select-option',handle:p.handle,variantId:p.variants[index].id})).ok,true);assert.equal((await this.store.execute({type:'product-quantity',handle:p.handle,quantity})).ok,true);assert.equal((await this.store.execute({type:'add',handle:p.handle},{requestId:'add-'+this.cart().length})).ok,true);}};
}
const bagRow=(f,id)=>[...f.d.querySelectorAll('[data-bag-line]')].find(row=>row.dataset.bagLine===id);
function native(t,{note='PRIVATE50 old note',onFetch,commerceControls=false,discountDelay=25}={}){
 const state={currency:'USD',item_count:3,note,attributes:{'gift-note':'PRIVATE50 attribute'},token:'PRIVATE50 cart token',items:[{key:'5001:alpha',product_id:500,variant_id:5001,product_title:'Fern Necklace',variant_title:'Silver / 16 inches',quantity:2,final_price:4000,properties:{Engraving:'PRIVATE50 words'}},{key:'5003:beta',product_id:500,variant_id:5003,product_title:'Fern Necklace',variant_title:'Gold / 16 inches',quantity:1,final_price:6000}]},markup=`<main id="MainContent"><form id="bjCartForm" action="/cart" method="post"><div id="bjCartItems">${state.items.map(item=>`<article class="bj-cp__row" data-key="${item.key}" data-title="${item.product_title}"><a class="cart__product-name">${item.product_title}</a><div data-bjcp-qtywrap><button type="button">–</button><input class="cart__product-qty" name="updates[]" data-id="${item.key}" value="${item.quantity}"><button type="button">+</button></div><span data-bjcp-linetotal>Checked subtotal</span><a data-bjcp-remove href="/cart/change?id=${item.key}&quantity=0">Remove</a><button class="edit_cart_option" style="display:none">Edit options</button></article>`).join('')}</div><details id="bjGiftNote"><summary>Add a free gift note</summary><textarea name="note" id="CartSpecialInstructions"></textarea><span data-bjcp-notesaved></span></details>${commerceControls?'<input id="bjcpDiscIn"><button type="button" id="bjcpDiscApply">Apply</button><p id="bjcpDiscMsg"></p><p><input type="checkbox" id="CartPageAgree"><label for="CartPageAgree">I agree to the <a href="/policies/terms-of-service">terms and conditions</a></label></p>':''}<button type="submit" name="checkout">Checkout</button></form></main>`;
 const dom=new JSDOM(markup,{url:'https://britesjewelry.com/cart',pretendToBeVisual:true}),w=dom.window,d=w.document,calls=[],nav=[],reveals=[];d.querySelector('#CartSpecialInstructions').value=note;w.HTMLElement.prototype.scrollIntoView=function(){reveals.push(this);};let writes=0,checkout=0,discountClicks=0;if(commerceControls)d.querySelector('#bjcpDiscApply').addEventListener('click',()=>{discountClicks++;const button=d.querySelector('#bjcpDiscApply'),input=d.querySelector('#bjcpDiscIn'),message=d.querySelector('#bjcpDiscMsg'),code=input.value.trim().toUpperCase();button.disabled=true;w.setTimeout(()=>{button.disabled=false;message.className='ok';message.textContent='✓ Code '+code+' will be applied at checkout';w.sessionStorage.setItem('bjcpDisc',code);},discountDelay);});d.querySelector('[name=checkout]').addEventListener('click',()=>checkout++);d.querySelector('#CartSpecialInstructions').addEventListener('input',()=>w.setTimeout(()=>{state.note=d.querySelector('#CartSpecialInstructions').value;d.querySelector('[data-bjcp-notesaved]').textContent='Saved';writes++;},25));
 const fetch=async(url,init={})=>{calls.push({url,init});const handled=await onFetch?.({url,init,state,calls,w,d});if(handled)return handled;if(init.method==='POST'){const body=JSON.parse(init.body);assert.deepEqual(Object.keys(body),['updates']);state.items=state.items.filter(item=>body.updates[item.key]!==0);state.item_count=state.items.reduce((sum,item)=>sum+item.quantity,0);}return {ok:true,json:async()=>clone(state)};};const store=Shopify.create({window:w,root:'/',theme:'brites-v1',fetch,navigate:url=>nav.push(url)});t.after(()=>{store.destroy();w.close();});return {w,d,state,store,calls,nav,reveals,writes:()=>writes,checkout:()=>checkout,discountClicks:()=>discountClicks,run:(action,id='native50',signal)=>store.execute(action,{requestId:id,signal})};
}

test('actual bag menus reveal literal choices and preserve open state plus selected readback through rerender',async t=>{const f=sandbox(t);await f.ready();await f.add(0,2);await f.add(2,1);await f.store.execute({type:'bag'});const [first,second]=f.store.snapshot().bagControls.lines,untouched=f.cart()[1];assert.equal((await f.store.execute({type:'bag-options',lineId:first.lineId,optionName:'Length'})).ok,true);let row=bagRow(f,first.lineId),menu=row.querySelector('[data-bag-menu="Length"]');assert.equal(menu.hidden,false);assert.equal(menu.previousElementSibling.getAttribute('aria-expanded'),'true');assert.equal(f.store.snapshot().bagControls.focusedLineId,first.lineId);assert.equal(f.store.snapshot().bagControls.focusedOptionName,'Length');[...menu.querySelectorAll('button')].find(button=>button.textContent==='18 inches').click();await settle();row=bagRow(f,first.lineId);assert.equal(row.querySelector('[data-bag-option="Length"]').value,'18 inches');assert.equal(row.querySelector('[data-bag-menu="Length"]').hidden,false);assert.equal(row.querySelector('[data-bag-menu="Length"] [aria-selected="true"]').textContent,'18 inches');assert.equal(f.cart()[0].variantId,'5002');assert.equal(f.cart()[0].quantity,2);assert.deepEqual(f.cart()[1],untouched);assert.equal(f.store.snapshot().bagControls.lines[0].openedOption,'Length');assert.equal(bagRow(f,second.lineId).querySelector('[data-bag-menu="Length"]').hidden,true);assert.deepEqual(f.errors,[]);});

test('manual cart focus and voice highlight target the exact actual line without replacing notes or other choices',async t=>{const f=sandbox(t);await f.ready();await f.add();await f.store.execute({type:'bag'});const id=f.store.snapshot().bagControls.lines[0].lineId,row=bagRow(f,id),quantity=row.querySelector('.bag-quantity input');quantity.focus();assert.equal(f.store.snapshot().bagControls.quantityFocused,true);assert.equal((await f.store.execute({type:'bag-highlight',lineId:id,section:'quantity'})).ok,true);assert(row.querySelector('.bag-quantity').classList.contains('store-highlight'));assert.equal((await f.store.execute({type:'bag-highlight',lineId:id,section:'options',optionName:'Unknown'})).ok,false);assert.equal((await f.store.execute({type:'bag-options',lineId:id,optionName:'Length'})).ok,true);assert.equal((await f.store.execute({type:'close-options'})).ok,true);assert.equal(row.querySelector('[data-bag-menu="Length"]').hidden,true);assert.equal(f.cart()[0].quantity,2);assert(f.scrolls.length);});

test('exact line identity, open menu and selected options survive a same-tab reload with fresh product checks',async t=>{const f=sandbox(t);await f.ready();await f.add(2,3);await f.store.execute({type:'bag'});const id=f.store.snapshot().bagControls.lines[0].lineId;await f.store.execute({type:'bag-options',lineId:id,optionName:'Length'});const next=sandbox(t,{saved:f.save(),cart:true});await next.ready();assert.equal(next.store.snapshot().bagControls.lines[0].lineId,id);assert.equal(bagRow(next,id).querySelector('[data-bag-option="Metal"]').value,'Gold');assert.equal(bagRow(next,id).querySelector('[data-bag-menu="Length"]').hidden,false);assert.equal(next.cart()[0].quantity,3);assert.ok(next.requests.some(request=>request.url.includes('/product?')));assert.deepEqual(next.errors,[]);});

test('bulk local clear rejects a subset or cancelled request, preserves preferences and can undo exact private rows',async t=>{const f=sandbox(t);await f.ready();await f.add();await f.add(2,1);await f.store.execute({type:'bag'});await f.store.execute({type:'bag-note',text:'PRIVATE50 gift literal'});const before=f.cart(),ids=f.store.snapshot().bagControls.lines.map(line=>line.lineId),cancel=new AbortController();cancel.abort();assert.equal((await f.store.execute({type:'bag-clear',lineIds:ids},{signal:cancel.signal})).ok,false);assert.equal((await f.store.execute({type:'bag-clear',lineIds:ids.slice(0,1)})).ok,false);assert.deepEqual(f.cart(),before);const cleared=await f.store.execute({type:'bag-clear',lineIds:ids});assert.equal(cleared.ok,true);assert.deepEqual(f.cart(),[]);assert.equal(f.d.querySelector('[name=note]').value,'PRIVATE50 gift literal');assert.doesNotMatch(JSON.stringify(cleared),/PRIVATE50/);assert.equal((await f.store.execute({type:'undo'})).ok,true);assert.deepEqual(f.cart(),before);assert.deepEqual(f.store.snapshot().bagControls.lines.map(line=>line.lineId),ids);assert.equal(f.requests.some(request=>request.init.method&&request.init.method!=='GET'),false);});

test('clear and fresh undo retain original published option order and stable exact identities',async t=>{const p=product(),v=p.variants[0],original=[{productId:p.id,title:p.title,variantId:'5001',variant:v.title,price:v.price,currency:p.currency,quantity:2,variantOptions:clone(v.options)}],f=sandbox(t,{cart:true,saved:[['brites-sandbox-cart',JSON.stringify(original)],['brites-sandbox-product-identities',JSON.stringify([[p.id,p.handle]])]]});await f.ready();const ids=f.store.snapshot().bagControls.lines.map(line=>line.lineId);assert.deepEqual(f.cart(),original);const cleared=await f.store.execute({type:'bag-clear',lineIds:ids});assert.equal(cleared.ok,true,cleared.message);const undone=await f.store.execute({type:'undo'});assert.equal(undone.ok,true,undone.message);assert.deepEqual(f.cart(),original);assert.deepEqual(f.store.snapshot().bagControls.lines.map(line=>line.lineId),ids);const reloaded=sandbox(t,{cart:true,saved:f.save()});await reloaded.ready();assert.deepEqual(reloaded.cart(),original);assert.deepEqual(clone(reloaded.store.snapshot().bagControls.lines.map(line=>line.lineId)),clone(ids));assert.equal(bagRow(reloaded,ids[0]).querySelector('[data-bag-option="Metal"]').value,'Silver');});

test('actual local design brief submit retains literal private words and clear leaves gift preferences intact',async t=>{const f=sandbox(t);await f.ready();await f.store.execute({type:'gift-preferences',wrapping:true,giftNote:'PRIVATE50 gift'});let submissions=0;f.d.querySelector('form[data-store-section=customize]').addEventListener('submit',()=>submissions++);const result=await f.store.execute({type:'customize-brief',text:'PRIVATE50 — a fern for Zoë'});assert.equal(result.ok,true);assert.equal(submissions,1);assert.equal(f.d.querySelector('[name=idea]').value,'PRIVATE50 — a fern for Zoë');assert.doesNotMatch(JSON.stringify(result),/PRIVATE50|Zoë/);assert.equal(result.snapshot.customizeBriefControls.savedKnown,true);assert.equal((await f.store.execute({type:'customize-brief',text:''})).ok,true);assert.equal(f.d.querySelector('[name=idea]').value,'');assert.equal(f.d.querySelector('[name=note]').value,'PRIVATE50 gift');});

test('native complete cart clear updates only exact keys and verifies preserved private notes and attributes',async t=>{const f=native(t);assert.equal(await f.store.refresh(),true);assert(f.store.capabilities.actions.includes('bag-clear'));assert(!f.store.capabilities.actions.includes('bag-options'));assert(!f.store.capabilities.actions.includes('bag-select-option'));const ids=f.store.snapshot().bagControls.lines.map(line=>line.lineId);assert.equal((await f.run({type:'bag-clear',lineIds:ids.slice(0,1)},'subset')).ok,false);assert.equal(f.calls.some(call=>call.init.method==='POST'),false);const result=await f.run({type:'bag-clear',lineIds:ids},'clear');assert.equal(result.ok,true,result.reason);assert.equal(f.state.item_count,0);assert.equal(f.state.note,'PRIVATE50 old note');assert.equal(f.state.attributes['gift-note'],'PRIVATE50 attribute');assert.equal(f.calls.filter(call=>call.init.method==='POST').length,1);assert.deepEqual(JSON.parse(f.calls.find(call=>call.init.method==='POST').init.body),{updates:{'5001:alpha':0,'5003:beta':0}});assert.deepEqual(f.nav,['https://britesjewelry.com/cart']);assert.doesNotMatch(JSON.stringify(result),/PRIVATE50/);assert.equal(f.checkout(),0);});

test('native cart clear refuses a newly changed bag during fresh precheck before any POST',async t=>{let drift=false;const f=native(t,{onFetch:({state,init})=>{if(drift&&init.method==='GET'){state.items[0].quantity++;state.item_count++;drift=false;}}});await f.store.refresh();const ids=f.store.snapshot().bagControls.lines.map(line=>line.lineId);drift=true;const result=await f.run({type:'bag-clear',lineIds:ids});assert.equal(result.ok,false);assert.equal(f.calls.some(call=>call.init.method==='POST'),false);assert.deepEqual(f.nav,[]);});

test('native clear abort during its held fresh precheck never writes or navigates',async t=>{let hold=false,release;const f=native(t,{onFetch:({state})=>hold?new Promise(resolve=>release=()=>resolve({ok:true,json:async()=>clone(state)})):undefined});await f.store.refresh();const ids=f.store.snapshot().bagControls.lines.map(line=>line.lineId),cancel=new AbortController();hold=true;const pending=f.run({type:'bag-clear',lineIds:ids},'abort',cancel.signal);await settle();cancel.abort();release();const result=await pending;assert.equal(result.ok,false);assert.equal(result.cancelled,true);assert.equal(f.calls.some(call=>call.init.method==='POST'),false);assert.deepEqual(f.nav,[]);});

test('native note actuates actual input autosave and verifies exact private saved readback without checkout',async t=>{const f=native(t);await f.store.refresh();const before=clone(f.state.items),result=await f.run({type:'bag-note',text:'PRIVATE50 — Forever, Zoë'});assert.equal(result.ok,true,result.reason);assert.equal(f.writes(),1);assert.equal(f.d.querySelector('#bjGiftNote').open,true);assert.equal(f.d.querySelector('#CartSpecialInstructions').value,'PRIVATE50 — Forever, Zoë');assert.equal(f.state.note,'PRIVATE50 — Forever, Zoë');assert.deepEqual(f.state.items,before);assert.equal(result.snapshot.bagNoteControls.savedKnown,true);assert.doesNotMatch(JSON.stringify(result),/PRIVATE50|Zoë|cart token/);assert.equal(f.checkout(),0);assert.deepEqual(f.nav,[]);assert.equal((await f.run({type:'bag-note',text:''},'clear-note')).ok,true);assert.equal(f.state.note,'');});

test('native cart note and line highlights advertise only current checked controls and reject stale literal overwrite',async t=>{const f=native(t);await f.store.refresh();const id=f.store.snapshot().bagControls.lines[1].lineId;assert.equal((await f.run({type:'bag-highlight',lineId:id,section:'quantity'},'highlight')).ok,true);assert(f.d.querySelectorAll('[data-bjcp-qtywrap]')[1].style.outline.includes('2px'));assert.equal((await f.run({type:'bag-highlight',lineId:id,section:'engraving'},'private-field')).ok,false);f.state.note='Different saved note';assert.equal((await f.run({type:'bag-note',text:'PRIVATE50 overwrite'},'stale')).ok,false);assert.equal(f.writes(),0);assert.equal(f.d.querySelector('#CartSpecialInstructions').value,'PRIVATE50 old note');f.d.querySelector('#CartSpecialInstructions').disabled=true;assert(!f.store.capabilities.actions.includes('bag-note'));});

test('an initially blank closed native note disclosure opens for explicit wording and gift reveal',async t=>{const f=native(t,{note:''});await f.store.refresh();assert.equal(f.d.querySelector('#bjGiftNote').open,false);assert(f.store.capabilities.actions.includes('bag-note'));const result=await f.run({type:'bag-note',text:'PRIVATE50 blank disclosure'},'blank-note');assert.equal(result.ok,true,result.reason);assert.equal(f.d.querySelector('#bjGiftNote').open,true);assert.equal(f.state.note,'PRIVATE50 blank disclosure');f.d.querySelector('#bjGiftNote').open=false;assert.equal((await f.run({type:'gift',section:'gifts'},'reveal-note')).ok,true);assert.equal(f.d.querySelector('#bjGiftNote').open,true);f.d.querySelector('#bjGiftNote').hidden=true;assert(!f.store.capabilities.actions.includes('bag-note'));});

test('native clear preservation accepts equivalent reordered attributes without sending them back',async t=>{const f=native(t,{onFetch:({state,init})=>{if(init.method==='POST')state.attributes={wrapping:'yes','gift-note':'PRIVATE50 attribute'};}});f.state.attributes={'gift-note':'PRIVATE50 attribute',wrapping:'yes'};await f.store.refresh();const result=await f.run({type:'bag-clear',lineIds:f.store.snapshot().bagControls.lines.map(line=>line.lineId)});assert.equal(result.ok,true,result.reason);assert.deepEqual(Object.keys(JSON.parse(f.calls.find(call=>call.init.method==='POST').init.body)),['updates']);});

test('manual note input retires an older autosave proof even if the same literal text is restored',async t=>{let reads=0,held,release;const f=native(t,{onFetch:({state,init})=>{if(init.method==='GET'&&++reads===3){held=true;return new Promise(resolve=>release=()=>resolve({ok:true,json:async()=>clone(state)}));}}});await f.store.refresh();const pending=f.run({type:'bag-note',text:'PRIVATE50 newer literal'});await settle();assert.equal(held,true);const input=f.d.querySelector('#CartSpecialInstructions');input.value='PRIVATE50 manual';input.dispatchEvent(new f.w.Event('input',{bubbles:true}));input.value='PRIVATE50 newer literal';input.dispatchEvent(new f.w.Event('input',{bubbles:true}));release();const result=await pending;assert.equal(result.ok,false);assert.equal(result.cancelled,true);assert.notEqual(f.store.snapshot().bagNoteControls.savedKnown,true);assert.doesNotMatch(JSON.stringify(result),/PRIVATE50/);});

const Bridge50=require('../../brites-storefront-bridge.js');
function listing50(n){const p=product();p.id='gid://shopify/Product/'+(600+n);p.handle='fern-necklace-'+n;p.url='https://britesjewelry.com/products/'+p.handle;p.title='Fern Necklace '+n;return p;}
function response50(data){return {ok:true,json:async()=>clone(data)};}

test('catalogue continuation clicks its actual mounted button and refuses phantom repeated cursors',async t=>{let page=0;const initial=Array.from({length:24},(_,i)=>listing50(i)),f=sandbox(t,{onFetch:({url})=>url.includes('/catalogue')?response50({live:true,checkedAt:Date.now(),products:page++? [listing50(24)]:initial,pageInfo:{hasNextPage:true,endCursor:'same-cursor50'}}):undefined});await f.ready();assert.equal(f.d.querySelectorAll('.piece-card').length,24);const button=f.d.querySelector('[data-catalogue-more]');assert(button);let clicks=0;button.addEventListener('click',()=>clicks++);const result=await f.store.execute({type:'catalogue-more'});assert.equal(result.ok,false);assert.equal(clicks,1);assert.equal(f.d.querySelectorAll('.piece-card').length,24);assert.equal(f.store.snapshot().catalogueControls.loadedCount,24);assert.equal(f.requests.filter(r=>r.url.includes('cursor=same-cursor50')).length,1);});

test('catalogue continuation renders one checked next page then removes the unavailable continuation',async t=>{let page=0;const f=sandbox(t,{onFetch:({url})=>url.includes('/catalogue')?response50({live:true,checkedAt:Date.now(),products:page++?[listing50(24)]:Array.from({length:24},(_,i)=>listing50(i)),pageInfo:page===1?{hasNextPage:true,endCursor:'next50'}:{hasNextPage:false,endCursor:null}}):undefined});await f.ready();const result=await f.store.execute({type:'catalogue-more'});assert.equal(result.ok,true,result.message);assert.equal(f.d.querySelectorAll('.piece-card').length,25);assert.equal(f.store.snapshot().catalogueControls.moreAvailable,false);assert.equal((await f.store.execute({type:'catalogue-more'})).ok,false);assert.equal(f.requests.filter(r=>r.url.includes('cursor=next50')).length,1);});

test('aborted catalogue continuation cannot append its delayed page or change the current loaded identity',async t=>{let release;const f=sandbox(t,{onFetch:({url})=>url.includes('/catalogue')?url.includes('cursor=')?new Promise(resolve=>release=()=>resolve(response50({live:true,products:[listing50(24)],pageInfo:{hasNextPage:false}}))):response50({live:true,checkedAt:Date.now(),products:Array.from({length:24},(_,i)=>listing50(i)),pageInfo:{hasNextPage:true,endCursor:'abort50'}}):undefined});await f.ready();const controller=new AbortController(),before=clone(f.store.snapshot().loadedPieces),pending=f.store.execute({type:'catalogue-more'},{signal:controller.signal});await settle();controller.abort();release();const result=await pending;assert.equal(result.ok,false);assert.deepEqual(clone(f.store.snapshot().loadedPieces),before);assert.equal(f.d.querySelectorAll('.piece-card').length,24);});

test('story opening clicks the current reviewed-story button and renders only its approved cited interpretation',async t=>{const f=sandbox(t,{onFetch:({url,p})=>url.includes('/knowledge?')?response50({products:[{productId:p.id,kind:'interpretation',text:'Synthetic reviewed interpretation.',context:'Synthetic cultural context',sources:[{title:'Synthetic museum source',url:'https://example.org/museum/fern',checkedAt:Date.now()}]},{productId:'gid://shopify/Product/999',kind:'interpretation',text:'FOREIGN50',context:'Foreign',sources:[]}]}):undefined});await f.ready();await f.store.execute({type:'open',handle:f.p.handle});const button=f.d.querySelector('[data-story-open]');let clicks=0;button.addEventListener('click',()=>clicks++);const result=await f.store.execute({type:'story-open',handle:f.p.handle});assert.equal(result.ok,true,result.message);assert.equal(clicks,1);assert.equal(f.store.snapshot().storyControls.loaded,true);assert.match(f.d.querySelector('.reviewed-story').textContent,/Synthetic reviewed interpretation/);assert.doesNotMatch(f.d.querySelector('[data-store-section=story]').textContent,/FOREIGN50/);assert.equal((await f.store.execute({type:'story-open',handle:'foreign-product'})).ok,false);});

test('cancelled reviewed story preserves the visible product and cannot render a late interpretation',async t=>{let release;const f=sandbox(t,{onFetch:({url,p})=>url.includes('/knowledge?')?new Promise(resolve=>release=()=>resolve(response50({products:[{productId:p.id,kind:'interpretation',text:'LATE50 story.',context:'Synthetic',sources:[{title:'Museum',url:'https://example.org/museum',checkedAt:Date.now()}]}]}))):undefined});await f.ready();await f.store.execute({type:'open',handle:f.p.handle});const controller=new AbortController(),pending=f.store.execute({type:'story-open',handle:f.p.handle},{signal:controller.signal});await settle();controller.abort();const result=await pending;release();await settle();assert.equal(result.ok,false);assert.equal(result.cancelled,true);assert.equal(f.d.querySelector('.reviewed-story'),null);assert.equal(f.store.snapshot().currentHandle,f.p.handle);});

test('cancel review clicks only its current cancel control and preserves exact selection quantity and cart',async t=>{const f=sandbox(t);await f.ready();await f.add();await f.store.execute({type:'open',handle:f.p.handle});await f.store.execute({type:'select-option',handle:f.p.handle,variantId:f.p.variants[1].id});await f.store.execute({type:'product-quantity',handle:f.p.handle,quantity:3});assert.equal((await f.store.execute({type:'review-add',handle:f.p.handle})).ok,true);const before=f.cart(),selection=clone(f.store.snapshot().productControls.selectedVariant),button=f.d.querySelector('[data-cancel-review]');let clicks=0;button.addEventListener('click',()=>clicks++);assert.equal((await f.store.execute({type:'cancel-review'})).ok,true);assert.equal(clicks,1);assert.equal(f.d.querySelector('[data-cancel-review]'),null);assert.deepEqual(f.cart(),before);assert.deepEqual(clone(f.store.snapshot().productControls.selectedVariant),selection);assert.equal((await f.store.execute({type:'cancel-review'})).ok,false);});

test('actual native discount control stages literal code without savings validity checkout or receipt leakage',async t=>{const f=native(t,{commerceControls:true});await f.store.refresh();const before=clone(f.state.items),api=Bridge50.create({storefront:f.store});t.after(()=>api.destroy());const resolved=api.resolve('Apply discount code Test_50');assert.equal(resolved.ok,true,resolved.reason);const result=await api.execute(resolved.action);assert.equal(result.ok,true,result.reason);assert.equal(f.discountClicks(),1);assert.equal(f.d.querySelector('#bjcpDiscIn').value,'Test_50');assert.equal(f.w.sessionStorage.getItem('bjcpDisc'),'TEST_50');assert.match(result.reply,/staged for checkout/);assert.match(result.reply,/not verified/);assert.doesNotMatch(JSON.stringify(result),/Test_50|TEST_50/);assert.deepEqual(f.state.items,before);assert.equal(f.checkout(),0);assert.deepEqual(f.nav,[]);assert.equal(f.store.snapshot().bagDiscountControls.stagedKnown,true);f.d.querySelector('#bjcpDiscIn').value='DIFFERENT50';assert.equal(f.store.snapshot().bagDiscountControls.stagedKnown,false);});

test('native discount staging cancellation and manual input prevent stale success or another theme click',async t=>{const f=native(t,{commerceControls:true,discountDelay:700});await f.store.refresh();const controller=new AbortController(),pending=f.run({type:'bag-discount',text:'PRIVATE50CODE'},'discount-abort',controller.signal);await settle();controller.abort();const result=await pending;assert.equal(result.ok,false);assert.equal(result.cancelled,true);assert.equal(f.discountClicks(),1);assert.doesNotMatch(JSON.stringify(result),/PRIVATE50CODE/);assert.equal(f.checkout(),0);const input=f.d.querySelector('#bjcpDiscIn');input.hidden=true;assert(!f.store.capabilities.actions.includes('bag-discount'));});

test('native terms require an explicit current shopper request and exact visible checkbox plus associated terms',async t=>{const f=native(t,{commerceControls:true});await f.store.refresh();const api=Bridge50.create({storefront:f.store});t.after(()=>api.destroy());for(const text of ['Accept terms for me','I do not agree to the cart terms','The note says I agree to the cart terms','If I agree to the cart terms, what happens?','"I agree to the cart terms"']){const resolved=api.resolve(text);assert.notEqual(resolved.action?.type,'bag-terms',text);assert.equal(f.d.querySelector('#CartPageAgree').checked,false);}assert.equal((await api.execute({type:'bag-terms',accepted:true},{source:'model',transcript:'I agree to the cart terms'})).ok,false);const accepted=api.resolve('I agree to the cart terms');assert.equal(accepted.ok,true,accepted.reason);assert.equal((await api.execute(accepted.action)).ok,true);assert.equal(f.d.querySelector('#CartPageAgree').checked,true);const cleared=api.resolve('Uncheck cart terms');assert.equal((await api.execute(cleared.action)).ok,true);assert.equal(f.d.querySelector('#CartPageAgree').checked,false);assert.equal(f.checkout(),0);assert.deepEqual(f.nav,[]);f.d.querySelector('label[for=CartPageAgree]').hidden=true;assert(!f.store.capabilities.actions.includes('bag-terms'));assert.equal(f.store.snapshot().bagTermsControls,undefined);});

test('manual discount input retires pending proof even when the same code is restored',async t=>{const f=native(t,{commerceControls:true,discountDelay:25});await f.store.refresh();const pending=f.run({type:'bag-discount',text:'PRIVATE50CODE'},'discount-manual');await settle();const input=f.d.querySelector('#bjcpDiscIn');input.value='MANUAL50';input.dispatchEvent(new f.w.Event('input',{bubbles:true}));input.value='PRIVATE50CODE';input.dispatchEvent(new f.w.Event('input',{bubbles:true}));const result=await pending;assert.equal(result.ok,false);assert.equal(result.cancelled,true);assert.equal(f.discountClicks(),1);assert.doesNotMatch(JSON.stringify(result),/PRIVATE50CODE|MANUAL50/);assert.equal(f.checkout(),0);});

test('native discount and terms cannot advertise or actuate fields hidden by their ancestor container',async t=>{const f=native(t,{commerceControls:true});await f.store.refresh();f.d.querySelector('#CartPageAgree').parentElement.style.display='none';assert(!f.store.capabilities.actions.includes('bag-terms'));assert.equal((await f.run({type:'bag-terms',accepted:true},'hidden-terms')).ok,false);assert.equal(f.d.querySelector('#CartPageAgree').checked,false);const box=f.d.createElement('div');box.style.display='none';f.d.querySelector('#bjcpDiscIn').before(box);for(const id of ['bjcpDiscIn','bjcpDiscApply','bjcpDiscMsg'])box.append(f.d.getElementById(id));assert(!f.store.capabilities.actions.includes('bag-discount'));assert.equal((await f.run({type:'bag-discount',text:'PRIVATE50'},'hidden-discount')).ok,false);assert.equal(f.discountClicks(),0);assert.equal(f.checkout(),0);});
