'use strict';
// Native transport and historical money helpers use synthetic atomic fixtures.
const test=require('node:test'),assert=require('node:assert/strict');
const core=require('../../netlify/functions/_britesGrowth.js'),voice=require('../../netlify/functions/_britesConciergeVoice.js');
const {fixture,AT,SDP,clone}=require('./voice-fixture36.cjs');
const ALLOWANCE='VoiceAllowances/native-sandbox';
function freshAllowance(f){const row={...f.rows.get(ALLOWANCE),reservedCents:0,calls:0,lastStartedAt:null};f.rows.set(ALLOWANCE,row);return clone(row);}
const reserve=(f,extra={})=>voice.createDemoBudgetReservationResult(f.service,{capUsd:10,now:f.now,allowContinuation:true,provenance:true,...extra});
for(const operator of [false,true])test((operator?'operator':'guest')+' direct OpenAI voice ignores exhausted historical allowance and research switch',async()=>{
  const f=fixture(),before=f.protectedBytes(),answer=await f.start(undefined,{operator});assert.equal(answer.response.status,200);assert.equal(f.protectedBytes(),before);assert.equal(f.journal()[0].stage,'call_verified');assert.equal(f.counts.starts,1);assert.equal(f.rows.get('State/control').aiEnabled,false);assert.equal(f.rows.get('State/control').aiDailyUsdCap,0);
});
test('simultaneous distinct native API tokens are journalled without the obsolete five-session money ceiling',async()=>{
  const f=fixture(),before=f.protectedBytes(),tokens=await Promise.all(Array.from({length:6},()=>f.token())),answers=await Promise.all(tokens.map(token=>f.start(token)));assert.ok(answers.every(row=>row.response.status===200));assert.equal(f.counts.starts,6);assert.equal(f.deadlines.length,6);assert.equal(f.journal().length,6);assert.equal(f.protectedBytes(),before);assert.ok(f.journal().every(row=>row.stage==='call_verified'&&row.allocatedCents===undefined&&row.fundingSource===undefined));
});
test('same-token concurrent starts and replays cannot dispatch twice or rewrite completed evidence',async()=>{
  const f=fixture(),before=f.protectedBytes(),token=await f.token(),answers=await Promise.all([f.start(token),f.start(token)]);assert.deepEqual(answers.map(row=>row.response.status).sort(),[200,401]);assert.equal(f.counts.starts,1);assert.equal(f.journal().length,1);assert.equal(f.protectedBytes(),before);const saved=JSON.stringify([...f.rows]),writes=f.db.counts.writes,answer=await f.start(token);assert.equal(answer.response.status,401);assert.equal(answer.value.code,'VOICE_SESSION_REUSED');assert.equal(JSON.stringify([...f.rows]),saved);assert.equal(f.db.counts.writes,writes);
});
test('retired persistent authorization cannot create, replenish or extend a historical allowance',async()=>{
  const f=fixture(),before=f.protectedBytes(),answers=await Promise.all(Array.from({length:8},()=>f.call({action:'authorize-voice',owner:'PRIVATE_CONTROLLER',token:'d'.repeat(64),expectedUpdatedAt:AT-1000},{operator:true})));assert.ok(answers.every(row=>row.response.status===410));assert.equal(f.protectedBytes(),before);assert.equal(f.db.counts.reads,0);assert.equal(f.db.counts.writes,0);assert.equal(f.provider.length,0);assert.doesNotMatch(JSON.stringify(answers.map(row=>row.value)),/PRIVATE_|tokenHash|d{64}|allocatedCents/);
});
test('historical allowance helper still protects five exact slots atomically without changing the original ledger',async()=>{
  const f=fixture();freshAllowance(f);const budget=clone(f.rows.get('VoiceUsage/preview-budget')),old=clone(f.rows.get('VoiceUsage/session-'+'a'.repeat(64))),results=await Promise.all(Array.from({length:6},(_,i)=>reserve(f)(1,'historical-allowance-session-'+i)));assert.equal(results.filter(row=>row.granted).length,5);assert.equal(results.find(row=>!row.granted).reason,'ALLOCATION_EXHAUSTED');assert.equal(f.rows.get(ALLOWANCE).reservedCents,500);assert.equal(f.rows.get(ALLOWANCE).spentCents,0);assert.equal(f.rows.get(ALLOWANCE).calls,5);assert.deepEqual(f.rows.get('VoiceUsage/preview-budget'),budget);assert.deepEqual(f.rows.get('VoiceUsage/session-'+'a'.repeat(64)),old);assert.equal(f.provider.length,0);
  const attempts=[...f.rows].filter(([key,value])=>key.startsWith('VoiceUsage/session-')&&value.fundingSource==='native_allowance');assert.equal(attempts.length,5);assert.ok(attempts.every(([,row])=>row.allowanceId==='native-sandbox'&&row.allocatedCents===100&&row.stage==='reserved'&&row.reconcile==='provider_evidence_required'));
});
test('typed and non-provenance legacy helpers cannot spend a native-only historical allowance',async()=>{
  const f=fixture({rows:[['VoiceUsage/preview-budget',{reservedCents:900,spentCents:100,calls:10}]]});freshAllowance(f);const before=f.protectedBytes();assert.equal(await voice.createDemoBudgetReservation(f.service,{capUsd:10,now:f.now})(.05,'synthetic-typed-session-id'),null);assert.deepEqual(await reserve(f,{provenance:false})(1,'synthetic-unlinked-native-id'),{granted:false,reason:'ALLOCATION_EXHAUSTED'});assert.equal(f.protectedBytes(),before);assert.equal(f.db.counts.writes,0);assert.equal(f.provider.length,0);
});
for(const outcome of ['provider-rejection','transport-uncertainty','deadline-uncertainty','deadline-and-hangup-uncertainty'])test('native '+outcome+' preserves historical money and one-start evidence',async()=>{
  const options=outcome==='provider-rejection'?{provider:async()=>Response.json({error:{code:'insufficient_quota',message:'PRIVATE_PROVIDER'}},{status:429,headers:{'x-request-id':'req_rejected'}})}:outcome==='transport-uncertainty'?{provider:async()=>{throw Error('PRIVATE_TRANSPORT');}}:{deadlineFailure:true,hangupThrows:outcome==='deadline-and-hangup-uncertainty'};
  const f=fixture(options),before=f.moneyBytes(),token=await f.token(),answer=await f.start(token);assert.equal(answer.response.status,503);assert.doesNotMatch(JSON.stringify(answer.value),/PRIVATE_|synthetic-only-provider-key/);assert.equal(f.counts.starts,1);assert.equal(f.moneyBytes(),before);assert.equal(f.journal()[0].stage,outcome==='provider-rejection'?'provider_rejected':outcome==='transport-uncertainty'?'unknown':'deadline_failed');const saved=JSON.stringify([...f.rows]),writes=f.db.counts.writes;assert.equal((await f.start(token)).response.status,401);assert.equal(JSON.stringify([...f.rows]),saved);assert.equal(f.db.counts.writes,writes);assert.equal(f.counts.starts,1);
});
for(const boundary of ['control','hard'])test(boundary+' stop bounds capability, start and the actual provider deadline',async()=>{
  const at=boundary==='hard'?core.STOP_AT-60000:AT,stopAt=boundary==='hard'?core.STOP_AT+86400000:at+60000,f=fixture({at,control:{stopAt}}),expected=boundary==='hard'?core.STOP_AT:stopAt,before=f.moneyBytes(),answer=await f.start();assert.equal(answer.response.status,200);assert.equal(answer.value.expiresAt,expected);assert.equal(answer.value.maxDurationMs,60000);assert.equal(f.deadlines[0].expiresAt,expected);assert.equal(f.moneyBytes(),before);const token=await f.token();f.setAt(expected);const writes=f.db.counts.writes,calls=f.provider.length;assert.equal((await f.call({action:'capabilities'})).response.status,503);assert.equal((await f.start(token)).response.status,503);assert.equal(f.db.counts.writes,writes);assert.equal(f.provider.length,calls);assert.equal(f.moneyBytes(),before);
});
test('shortening stored control stop blocks starts with an already valid token before dispatch',async()=>{
  const f=fixture(),token=await f.token();f.rows.set('State/control',{...f.rows.get('State/control'),stopAt:f.now()+1000});f.advance(1000);const before=f.protectedBytes();assert.equal((await f.start(token)).response.status,503);assert.equal((await f.call({action:'capabilities'})).response.status,503);assert.equal(f.protectedBytes(),before);assert.equal(f.provider.length,0);assert.equal(f.db.counts.writes,0);
});
for(const boundary of ['hard-stop','disabled-control'])test(boundary+' during provider acceptance closes the exact call before SDP release',async()=>{
  let f;f=fixture({provider:async()=>{if(boundary==='hard-stop')f.setAt(core.STOP_AT);else f.rows.set('State/control',{...f.rows.get('State/control'),enabled:false});return new Response(SDP,{status:201,headers:{Location:'/v1/realtime/calls/rtc_stop','x-request-id':'req_stop'}});}});const before=f.moneyBytes(),answer=await f.start();assert.equal(answer.response.status,503);assert.equal(answer.value.code,'VOICE_RUNTIME_DISABLED');assert.equal(answer.value.sdp,undefined);assert.equal(f.counts.starts,1);assert.equal(f.counts.hangups,1);assert.equal(f.deadlines.length,0);assert.equal(f.moneyBytes(),before);const row=f.journal()[0];assert.equal(row.providerCode,'SANDBOX_STOP_REACHED');assert.equal(row.hangupConfirmed,true);assert.equal(row.allocatedCents,undefined);
});
for(const patch of [{reservedCents:'100'},{spentCents:1},{calls:'0'},{reservedCents:501},{reservedCents:100,calls:0},{allocatedCents:600},{provider:'untrusted'},{reservationCents:'100'},{lastStartedAt:AT},{expiresAt:core.STOP_AT+1},{issuedAt:0}])test('malformed historical allowance remains a strict helper denial, independent of native voice '+JSON.stringify(patch),async()=>{
  const f=fixture();freshAllowance(f);f.rows.set(ALLOWANCE,{...f.rows.get(ALLOWANCE),...patch});const before=f.moneyBytes(),writes=f.db.counts.writes;assert.deepEqual(await reserve(f)(1,'historical-invalid-allowance-session'),{granted:false,reason:'INVALID_LEDGER'});assert.equal(f.moneyBytes(),before);assert.equal(f.db.counts.writes,writes);assert.equal(f.provider.length,0);const answer=await f.start();assert.equal(answer.response.status,200);assert.equal(f.moneyBytes(),before);
});
test('historical allocation remains read-only, private and explicitly separate from native API sessions',async()=>{
  const f=fixture({env:{BRITES_CONCIERGE_REALTIME_DEMO_USD_CAP:'10',BRITES_CONCIERGE_REALTIME_RESERVE_USD:'1'}}),answer=await f.start();assert.equal(answer.response.status,200);const before=JSON.stringify([...f.rows]),writes=f.db.counts.writes,calls=f.provider.length,result=await f.call({action:'allocation'},{operator:true});assert.equal(result.response.status,200);const value=result.value;assert.equal(value.historical,true);assert.equal(value.nativeVoiceUsesAllocation,false);assert.equal(value.readOnly,true);assert.equal(value.financialWrites,0);assert.equal(value.providerCalls,0);assert.equal(value.refunds,0);assert.equal(value.evidenceComplete,false);assert.equal(value.nativeAllowance.valid,true);assert.equal(value.nativeAllowance.state,'exhausted');assert.equal(value.nativeAllowance.reservedCents,500);assert.equal(value.nativeAllowance.calls,5);assert.equal(value.budget.reservedCents,950);assert.equal(value.records.length,1);assert.equal(value.records[0].kind,'unattributed');assert.equal(JSON.stringify([...f.rows]),before);assert.equal(f.db.counts.writes,writes);assert.equal(f.provider.length,calls);assert.doesNotMatch(JSON.stringify(value),/PRIVATE_|synthetic-only|tokenHash|authorizedBy|checkpointUpdatedAt/);
});

test('native co-selection uses the exact selected piece approved story, qualified meanings and neutral evidence without unsolicited hover speech',()=>{
  const config=voice.sessionConfig({});assert.ok(config.tools.some(tool=>tool.name==='find_jewellery'));assert.ok(config.tools.some(tool=>tool.name==='inspect_jewellery'));
  assert.match(config.instructions,/after find_jewellery returns its checked approved public story/);assert.match(config.instructions,/one short interesting connection about that exact motif/);assert.match(config.instructions,/find_jewellery with its checked owned product URL and the shopper/);assert.match(config.instructions,/inspect_jewellery verifies live options and does not supply a researched story/);
  assert.match(config.instructions,/neutral citations and cultural context/);assert.match(config.instructions,/can represent/);assert.match(config.instructions,/never invent a universal meaning/);assert.match(config.instructions,/do not turn a hover into unsolicited speech/);assert.match(config.instructions,/When a tool cannot verify something, say so/);
});
