'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {createShopify}=require('../../netlify/functions/_britesGrowth.js');
const NOW=Date.parse('2026-10-03T12:00:00Z');
const reply=(data,status=200)=>({ok:status>=200&&status<300,status,json:async()=>data});
const pub=(id=1)=>({id,title:'Bunny Charm Necklace',handle:'bunny-'+id,description:'<p>A bunny necklace.</p>',product_type:'Necklace',tags:['bunny'],featured_image:'//cdn.shopify.com/bunny.jpg',options:[{name:'Metal',values:['Sterling Silver']}],variants:[{id:101+id,title:'Sterling Silver',sku:'BUNNY-'+id,price:5400,available:true,options:['Sterling Silver']}]});
function publicAdapter(handler){const calls=[];const shop=createShopify({env:{},now:()=>NOW,fetch:async(url,options)=>{calls.push({url,options});return handler(new URL(url),options,calls);}});return {shop,calls};}

test('public search verifies each exact published product and current currency with bounded requests',async()=>{const {shop,calls}=publicAdapter(async u=>{if(u.pathname==='/search/suggest.json')return reply({resources:{results:{products:[{handle:'bunny-1'},{url:'/products/bunny-2'},{url:'https://evil.example/products/private'}]}}});if(u.pathname==='/cart.js')return reply({currency:'CAD'});if(u.pathname==='/products/bunny-1.js')return reply(pub(1));if(u.pathname==='/products/bunny-2.js')return reply(pub(2));throw Error('Unexpected route');});const d=await shop.search('Bunny');assert.equal(d.products.length,2);assert.equal(d.products[0].currency,'CAD');assert.equal(d.products[0].variants[0].price,54);assert.equal(d.products[0].variants[0].sku,'BUNNY-1');assert.equal(d.products[0].updatedAt,null);assert.equal(d.products[0].source,'published_product_ajax');assert.ok(d.products[0].variantsComplete);assert.equal(calls.filter(x=>x.url.includes('/cart.js')).length,1);assert.ok(calls.every(x=>x.url.startsWith('https://britesjewelry.com/')));assert.equal(calls.find(x=>x.url.includes('/search/suggest')).options.redirect,'error');});
test('public metadata contains no undefined Firestore values or invented modification time',async()=>{const {shop}=publicAdapter(async u=>u.pathname==='/cart.js'?reply({currency:'USD'}):reply(pub()));const p=await shop.byHandle('bunny-1');function inspect(v){if(v&&typeof v==='object')for(const [k,x] of Object.entries(v)){assert.notEqual(x,undefined,k);inspect(x);}}inspect(p);assert.equal(p.updatedAt,null);assert.equal(p.checkedAt,NOW);});
test('public product list prices are dollars while product Ajax prices are cents',async()=>{const {shop}=publicAdapter(async u=>{if(u.pathname==='/products.json')return reply({products:[{...pub(),variants:[{...pub().variants[0],price:'54.00'}]}]});if(u.pathname==='/cart.js')return reply({currency:'USD'});return reply(pub());});const list=await shop.products('');const exact=await shop.byHandle('bunny-1');assert.equal(list.products[0].variants[0].price,54);assert.equal(exact.variants[0].price,54);assert.equal(list.access,'public_catalogue');});
test('mirror pages persist a separate cursor and finish only at the end',async()=>{const {shop,calls}=publicAdapter(async u=>u.pathname==='/cart.js'?reply({currency:'USD'}):reply({products:u.searchParams.get('page')==='1'?Array.from({length:250},(_,i)=>({...pub(i+1),variants:[]})):[]}));const first=await shop.products('');assert.equal(first.products.length,250);assert.equal(first.pageInfo.hasNextPage,true);assert.equal(first.pageInfo.endCursor,'public:2');const end=await shop.products('',first.pageInfo.endCursor);assert.equal(end.pageInfo.hasNextPage,false);assert.equal(end.pageInfo.endCursor,null);assert.equal(calls.length,3);assert.equal(new URL(calls[2].url).searchParams.get('page'),'2');});
test('maximum documented Ajax variant count never claims a complete selection',async()=>{const {shop}=publicAdapter(async u=>u.pathname==='/cart.js'?reply({currency:'USD'}):reply({...pub(),variants:Array.from({length:250},(_,i)=>({...pub().variants[0],id:i+1}))}));assert.equal((await shop.byHandle('bunny-1')).variantsComplete,false);});
test('unavailable or unreported inventory is never turned into available stock',async()=>{const {shop}=publicAdapter(async u=>u.pathname==='/cart.js'?reply({currency:'USD'}):reply({...pub(),variants:[{...pub().variants[0],available:undefined}]}));assert.equal((await shop.byHandle('bunny-1')).variants[0].available,false);});
test('invalid handles and mismatched product identities fail before persisting a false match',async()=>{const {shop,calls}=publicAdapter(async u=>u.pathname==='/cart.js'?reply({currency:'USD'}):reply(pub(2)));await assert.rejects(shop.byHandle('../admin'),/Invalid product handle/);assert.equal(calls.length,0);await assert.rejects(shop.byHandle('bunny-1'),/does not match/);});
test('404 published product returns null rather than an invented unavailable product',async()=>{const {shop}=publicAdapter(async u=>u.pathname==='/cart.js'?reply({currency:'USD'}):reply(null,404));assert.equal(await shop.byHandle('bunny-1'),null);});
test('failed or invalid currency verification prevents an unlabelled price',async()=>{const {shop}=publicAdapter(async u=>u.pathname==='/cart.js'?reply({currency:'unknown'}):reply(pub()));await assert.rejects(shop.byHandle('bunny-1'),/currency could not be verified/);});
test('multi-interest fallback searches a bounded subset and deduplicates products',async()=>{const {shop,calls}=publicAdapter(async u=>{if(u.pathname==='/search/suggest.json')return reply({resources:{results:{products:u.searchParams.get('q').includes(' ')?[]:[{handle:'bunny-1'}]}}});if(u.pathname==='/cart.js')return reply({currency:'USD'});return reply(pub());});const d=await shop.search('bunny cat dog whale dolphin fox');assert.equal(d.products.length,1);assert.equal(calls.filter(x=>x.url.includes('/search/suggest')).length,4);assert.equal(calls.filter(x=>x.url.includes('/products/bunny-1.js')).length,1);});
test('missing credentials and redacted placeholders never invoke Admin authorization',async()=>{const calls=[];const shop=createShopify({env:{SHOPIFY_STORE:'test.myshopify.com',SHOPIFY_CLIENT_ID:'fixture',SHOPIFY_CLIENT_SECRET:'********************'},now:()=>NOW,fetch:async u=>{calls.push(u);return reply(u.endsWith('/cart.js')?{currency:'USD'}:{products:[]});}});await shop.products('');assert.ok(calls.every(u=>!u.includes('/admin/')));});
test('configured Admin search uses safe prefixes and normalizes published product records',async()=>{const calls=[];const shop=createShopify({env:{SHOPIFY_STORE:'test.myshopify.com',SHOPIFY_CLIENT_ID:'fixture',SHOPIFY_CLIENT_SECRET:'SYNTHETIC_TEST_SECRET'},now:()=>NOW,fetch:async(u,o)=>{calls.push({u,o});if(u.includes('/oauth/'))return reply({access_token:'TEST_ACCESS',expires_in:3600});return reply({data:{products:{nodes:[{id:'gid://shopify/Product/1',handle:'bunny-1',title:'Bunny Necklace',status:'ACTIVE',onlineStoreUrl:'https://britesjewelry.com/products/bunny-1',options:[],tags:[],variants:{nodes:[],pageInfo:{hasNextPage:false}}}],pageInfo:{hasNextPage:false,endCursor:null}},shop:{currencyCode:'USD'}}});}});const d=await shop.search('Ballet " OR title:*');assert.equal(d.access,'admin');const query=JSON.parse(calls[1].o.body).variables.query;assert.ok(query.includes('title:ballet*'));assert.ok(!query.includes('title:"'));assert.ok(!query.includes('title:*'));assert.equal(d.products[0].updatedAt,null);});
test('a failed Admin credential defers to published catalogue without exposing its error',async()=>{const calls=[];const shop=createShopify({env:{SHOPIFY_STORE:'test.myshopify.com',SHOPIFY_CLIENT_ID:'fixture',SHOPIFY_CLIENT_SECRET:'SYNTHETIC_TEST_SECRET'},now:()=>NOW,fetch:async u=>{calls.push(u);if(u.includes('/admin/'))return reply({error:'PRIVATE_SECRET_ERROR'},401);return reply(u.endsWith('/cart.js')?{currency:'USD'}:{products:[]});}});const d=await shop.products('');assert.equal(d.access,'public_catalogue');assert.ok(!JSON.stringify(d).includes('PRIVATE'));assert.equal(calls.length,3);});
test('public cursor stays public until the mirror cycle ends even after credential reconnect',async()=>{const calls=[];const shop=createShopify({env:{SHOPIFY_STORE:'test.myshopify.com',SHOPIFY_CLIENT_ID:'fixture',SHOPIFY_CLIENT_SECRET:'SYNTHETIC_TEST_SECRET'},now:()=>NOW,fetch:async u=>{calls.push(u);return reply(u.endsWith('/cart.js')?{currency:'USD'}:{products:[]});}});await shop.products('','public:3');assert.equal(calls.length,2);assert.ok(calls[0].includes('page=3'));assert.ok(calls.every(u=>!u.includes('/admin/')));});
test('published underscore handles work in mirror, suggestions and exact current product fetches',async()=>{const rows=[{...pub(8582328942755),handle:'greek-goddess-earrings_2',title:'Greek Goddess Stud Earrings',type:'Earrings'},{...pub(8582328746147),handle:'greek-goddess-earrings_1',title:'Female Symbol Huggie Earrings',type:'Earrings'}];const {shop}=publicAdapter(async u=>{if(u.pathname==='/cart.js')return reply({currency:'USD'});if(u.pathname==='/products.json')return reply({products:rows});if(u.pathname==='/search/suggest.json')return reply({resources:{results:{products:rows.map(p=>({handle:p.handle}))}}});return reply(rows.find(p=>u.pathname==='/products/'+p.handle+'.js'));});assert.equal((await shop.products('')).products.length,2);assert.equal((await shop.search('Goddess')).products.length,2);for(const row of rows)assert.equal((await shop.byHandle(row.handle)).handle,row.handle);});
test('mirror currency is observed from the live storefront and never inferred from an environment default',async()=>{const shop=createShopify({env:{SHOPIFY_CURRENCY:'USD'},now:()=>NOW,fetch:async u=>reply(u.endsWith('/cart.js')?{currency:'CAD'}:{products:[pub()]})});assert.equal((await shop.products('')).products[0].currency,'CAD');});
test('mirror cannot persist price labels when storefront currency verification fails',async()=>{const {shop}=publicAdapter(async u=>u.pathname==='/cart.js'?reply({currency:'unknown'}):reply({products:[pub()]}));await assert.rejects(shop.products(''),/currency could not be verified/);});
