'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const core=require('../../netlify/functions/_britesGrowth.js');
const NOW=Date.parse('2026-10-03T12:00:00Z'),copy=value=>value==null?value:structuredClone(value);
class Store {
  constructor(){this.values=new Map();this.tail=Promise.resolve();}
  collection(name){return {doc:id=>{const key=name+'/'+id;return {get:async()=>{const value=this.values.get(key);return {exists:value!==undefined,data:()=>copy(value)};},set:async(value,options={})=>this.values.set(key,copy(options.merge?{...this.values.get(key),...value}:value))};}};}
  batch(){const pending=[];return {set:(ref,value)=>pending.push(()=>ref.set(value)),commit:async()=>{for(const task of pending)await task();}};}
  runTransaction(callback){const run=this.tail.then(async()=>{const pending=[];const result=await callback({get:ref=>ref.get(),set:(ref,value,options)=>pending.push(()=>ref.set(value,options))});for(const task of pending)await task();return result;});this.tail=run.catch(()=>{});return run;}
}
const product={id:'gid://shopify/Product/8499912868003',handle:'wolf-necklace',url:'https://britesjewelry.com/products/wolf-necklace',title:'Wolf Necklace',type:'Necklace',description:'Wolf design with an included chain.',tags:['wolf'],currency:'USD',image:null,imageAlt:'Wolf necklace',options:[{name:'Necklace Length',values:['18 Inches']}],variants:[{id:'gid://shopify/ProductVariant/101',numericId:'101',title:'Sterling Silver / 18 Inches',sku:'OWNER_ONLY_SKU',price:54,available:true,options:[]}],variantsComplete:true,checkedAt:NOW};
const issue=(overrides={})=>({id:'wolf-legacy-bear',kind:'identity',status:'open',detail:'OWNER_ONLY_REVIEW: title is wolf while description says bear.',reviewed:true,evidence:[{url:product.url,quote:'Bear design',checkedAt:NOW}],...overrides});
const record=(issues=[issue()])=>({productId:product.id,issues,ownerSecret:'OWNER_ONLY_SECRET'});
const fixture=()=>({service:core.createGrowthService({db:new Store(),now:()=>NOW})});
const meaning=()=>({productId:product.id,status:'approved',sources:[{id:'museum',url:'https://example.org/museum/wolf',title:'Museum interpretation',excerpt:'OWNER_ONLY_EXCERPT',reviewed:true,checkedAt:NOW}],meanings:[{text:'A wolf may evoke a personal sense of companionship.',context:'A personal interpretation in the cited collection.',kind:'interpretation',sourceIds:['museum']}]});

test('critical reviewed issues force cart and recommendation holds even when blocks are omitted',()=>{for(const kind of ['identity','style','options','material','matching']){const holds=core.productIssueHolds(record([issue({kind,blocks:[]})]));assert.equal(holds.cartHold,true);assert.equal(holds.recommendationHold,true);}assert.equal(core.productIssueHolds(record([issue({status:'resolved'})])).cartHold,false);});
test('history and content issues hold meaning only and preserve otherwise verified shopping',()=>{for(const kind of ['history','content']){const holds=core.productIssueHolds(record([issue({kind})]));assert.equal(holds.meaningHold,true);assert.equal(holds.cartHold,false);assert.equal(holds.recommendationHold,false);const products=core.applyProductIssues([product],[record([issue({kind})])]);assert.equal(core.rankProducts(products,core.intentFrom('Wolf silver necklace'),NOW).length,1);assert.equal(core.publicMeanings([meaning()],[product.id],NOW,[record([issue({kind})])]).length,0);}});
test('product issue projection exports only hold booleans and never owner diagnosis or evidence',()=>{const projected=core.applyProductIssues([product],[record()]).map(core.productProjection);assert.equal(projected[0].cartHold,true);assert.equal(projected[0].recommendationHold,true);assert.ok(!JSON.stringify(projected).includes('OWNER_ONLY'));assert.equal(core.rankProducts(core.applyProductIssues([product],[record()]),core.intentFrom('Wolf necklace'),NOW).length,0);});
test('holds bind to the exact current product and cannot leak onto another motif',()=>{const another={...product,id:'gid://shopify/Product/8499905396899'};const projected=core.applyProductIssues([another],[record()]);assert.equal(projected[0].cartHold,false);assert.equal(core.publicMeanings([meaning()],[product.id],NOW,[{...record(),productId:another.id}]).length,1);});
test('catalogue refresh cannot erase independently persisted reviewed holds',async()=>{const {service}=fixture();await service.saveProducts([product]);await service.recordProductIssue(record());await service.saveProducts([{...product,checkedAt:NOW+1000,description:'Fresh published description',cartHold:false}]);const current=await service.getProduct(product.id),issues=await service.productIssues([product.id]);assert.equal(current.description,'Fresh published description');assert.equal(core.applyProductIssues([current],issues)[0].cartHold,true);assert.equal(issues[0].issues[0].detail,issue().detail);});
test('concurrent reviewers preserve both issues and resolving one cannot discard a remaining hold',async()=>{const {service}=fixture();await Promise.all([service.recordProductIssue(record()),service.recordProductIssue(record([issue({id:'second-option-conflict',kind:'options'})]))]);let issues=await service.productIssues([product.id]);assert.equal(issues[0].issues.length,2);const result=await service.recordProductIssue(record([issue({status:'resolved'})]));assert.equal(result.holds.cartHold,true);issues=await service.productIssues([product.id]);assert.equal(issues[0].issues.find(x=>x.id==='wolf-legacy-bear').status,'resolved');assert.equal(issues[0].issues.find(x=>x.id==='second-option-conflict').status,'open');await service.recordProductIssue(record([issue({id:'second-option-conflict',kind:'options',status:'resolved'})]));assert.equal(core.productIssueHolds((await service.productIssues([product.id]))[0]).cartHold,false);});
test('issue lookups cover every product in a full Admin search page beyond the first twenty',async()=>{const {service}=fixture(),ids=Array.from({length:50},(_,i)=>'gid://shopify/Product/'+(i+1));await service.recordProductIssue({productId:ids[49],issues:[issue()]});const issues=await service.productIssues(ids);assert.equal(issues.length,1);assert.equal(issues[0].productId,ids[49]);});
test('duplicate issue IDs and malformed product binding cannot overwrite the issue archive',async()=>{const {service}=fixture();await service.recordProductIssue(record());await assert.rejects(service.recordProductIssue(record([issue(),issue()])),/unique/);await assert.rejects(service.recordProductIssue({...record(),productId:'arbitrary-product'}),/exact product ID/);assert.equal((await service.productIssues([product.id]))[0].issues.length,1);});
test('concierge suppresses held product recommendations and meanings while keeping healthy live matches',async()=>{const healthy={...product,id:'gid://shopify/Product/2',handle:'wolf-2',url:'https://britesjewelry.com/products/wolf-2'};const answer=await core.concierge({message:'Wolf silver necklace',now:()=>NOW,shopify:{search:async()=>({products:[product,healthy]})},service:{saveProducts:async()=>{},productIssues:async()=>[record()],research:async()=>[meaning()]}});assert.equal(answer.products.length,1);assert.equal(answer.products[0].id,healthy.id);assert.equal(answer.meanings.length,0);assert.ok(!JSON.stringify(answer).includes('OWNER_ONLY'));});
test('a failed hold lookup prevents advice instead of bypassing reviewed product safety',async()=>{await assert.rejects(core.concierge({message:'Wolf silver necklace',now:()=>NOW,shopify:{search:async()=>({products:[product]})},service:{saveProducts:async()=>{},productIssues:async()=>{throw Error('Issue storage unavailable');},research:async()=>[]}}),/Issue storage unavailable/);});
