'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const core=require('../../netlify/functions/_britesGrowth.js');
const NOW=Date.parse('2026-10-03T03:00:00Z');
// Synthetic catalogue fixtures: these tests do not contact a shop or provider.
function piece(id=1,extra={}){return {id:'gid://shopify/Product/'+id,handle:'synthetic-bunny-'+id,title:'Synthetic Bunny Necklace '+id,url:'https://britesjewelry.com/products/synthetic-bunny-'+id,currency:'USD',type:'Necklace',description:'A bunny design on an included chain.',tags:['rabbit'],options:[{name:'Necklace Length',values:['18 Inch']}],variants:[{id:'gid://shopify/ProductVariant/'+(id*100+1),numericId:String(id*100+1),title:'Sterling Silver / 18 Inch / None',price:54,available:true,options:[{name:'Metal',value:'Sterling Silver'},{name:'Necklace Length',value:'18 Inch'},{name:'Engraving',value:'None'}]}],variantsComplete:true,checkedAt:NOW,...extra};}
function dossier(p){return {productId:p.id,handle:p.handle,status:'approved',sources:[{id:'neutral',url:'https://example.edu/museum/interpretation',title:'Synthetic neutral interpretation',excerpt:'A rabbit may suggest renewal in this synthetic fixture.',reviewed:true,checkedAt:NOW}],meanings:[{kind:'interpretation',text:'A rabbit may personally suggest renewal.',context:'A qualified synthetic interpretation, not a universal meaning.',sourceIds:['neutral']}]};}
function fixture(products=[piece()],research=products.map(dossier),issues=[]){const calls={search:[],handles:[]};return {calls,service:{saveProducts:async()=>{},productIssues:async()=>issues,research:async()=>research},shopify:{search:async query=>{calls.search.push(query);return {products};},byHandle:async handle=>{calls.handles.push(handle);return products.find(p=>p.handle===handle)||null;}},now:()=>NOW};}
async function run(message,preferences=core.intentFrom('Bunny silver necklace under 60 USD'),extra={}){const f=fixture(extra.products,extra.research,extra.issues),answer=await core.concierge({...f,message,preferences,context:{productHandles:['synthetic-bunny-1'],...extra.context}});return {answer,calls:f.calls};}
for(const message of ['What do these mean?','What does this design mean?','What could these mean to someone?','Tell me the meanings of these','Tell me the meaning of this','What do these symbolize?','What is the symbolism?'])test('ordinary semantic follow-up preserves exact displayed motif and reviewed knowledge: '+message,async()=>{const {answer,calls}=await run(message);assert.equal(answer.preferences.query,'bunny');assert.deepEqual(answer.preferences.interests,['bunny']);assert.deepEqual(calls.search,[]);assert.deepEqual(calls.handles,['synthetic-bunny-1']);assert.equal(answer.products.length,1);assert.equal(answer.meanings.length,1);assert.match(answer.reply,/reviewed interpretations/);assert.equal(answer.requestedAction,undefined);assert.equal(answer.aiUsed,false);});
test('meaning follow-up still declines unsupported knowledge and recommendation holds',async()=>{const absent=await run('What do these mean?',undefined,{research:[]});assert.equal(absent.answer.products.length,1);assert.deepEqual(absent.answer.meanings,[]);assert.match(absent.answer.reply,/don’t yet have reviewed/);const held=await run('Tell me the meanings of these',undefined,{issues:[{productId:piece().id,issues:[{kind:'identity',status:'open',blocks:['recommendation','cart']}]}]});assert.deepEqual(held.answer.products,[]);assert.deepEqual(held.answer.meanings,[]);});
test('meaning follow-up refuses stale catalogue data rather than accepting context alone',async()=>{const p=piece(1,{checkedAt:NOW-6*60000});const {answer}=await run('What do these mean?',undefined,{products:[p],research:[dossier(p)]});assert.deepEqual(answer.products,[]);assert.deepEqual(answer.meanings,[]);});
test('discourse correction changes metal without replacing saved motif or entering meaning presentation',async()=>{const before=core.intentFrom('Bunny gold necklace under $60');const {answer,calls}=await run('I mean silver instead',before);assert.equal(answer.preferences.query,'bunny');assert.deepEqual(answer.preferences.interests,['bunny']);assert.equal(answer.preferences.metal,'silver');assert.deepEqual(calls.search,['bunny']);assert.deepEqual(calls.handles,[]);assert.doesNotMatch(answer.reply,/reviewed interpretations|don’t yet have reviewed/);assert.equal(answer.products.length,1);});
test('discourse correction can still replace an explicit motif and excludes a negated prior motif',()=>{const before=core.intentFrom('Bunny gold necklace under $60');const next=core.intentFrom('I mean a cat in silver instead, not a bunny',[],before);assert.equal(next.query,'cat');assert.deepEqual(next.interests,['cat']);assert.ok(next.excludedInterests.includes('bunny'));assert.equal(next.metal,'silver');});
for(const message of ['What do these mean?','Tell me the meanings of these','What do these symbolize?','Compare the first and second','Bunny necklace with engraving'])test('reply override retains foreign item-budget disclosure without invented FX: '+message,async()=>{const products=[piece(1),piece(2)],before=core.intentFrom('Bunny silver necklace under 40 CAD');const {answer}=await run(message,before,{products,context:{productHandles:products.map(p=>p.handle)}});assert.equal(answer.currencyMismatch,true);assert.ok(answer.products.length);assert.ok(answer.products.every(p=>p.currency==='USD'&&p.budgetApplied===false&&p.minPrice===54));assert.match(answer.reply,/Catalogue prices are shown in USD/);assert.match(answer.reply,/haven’t applied your CAD budget/);assert.equal((answer.reply.match(/haven’t applied your CAD budget/g)||[]).length,1);assert.doesNotMatch(answer.reply,/converted|conversion rate|within your CAD/);});
test('a singular material question with two unselected prior pieces asks which identity rather than inventing exact facts',async()=>{const products=[piece(1),piece(2)],before=core.intentFrom('Bunny silver necklace under 40 CAD'),{answer,calls}=await run('Does this piece contain nickel?',before,{products,context:{productHandles:products.map(p=>p.handle)}});assert.deepEqual(answer.products,[]);assert.equal(answer.productFacts.status,'unconfirmed');assert.equal(answer.live,false);assert.match(answer.reply,/choose one exact|which piece/i);assert.deepEqual(calls.search,[]);assert.deepEqual(calls.handles,[]);assert.equal(answer.preferences.budgetCurrency,'CAD');});
test('current exact product prices retain native currency and an unapplied foreign item budget',async()=>{const p=piece(1,{options:[{name:'Metal',values:['Sterling Silver']},{name:'Necklace Length',values:['18 Inch']},{name:'Engraving',values:['None']}]}),before=core.intentFrom('Bunny silver necklace under 40 CAD'),{answer,calls}=await run('Does this piece contain nickel, and what is its price?',before,{products:[p],context:{productHandles:[p.handle],currentHandle:p.handle}});assert.equal(answer.productFacts.status,'verified');assert.equal(answer.currencyMismatch,true);assert.equal(answer.productFacts.priceRange.currency,'USD');assert.equal(answer.productFacts.priceRange.min,54);assert.match(answer.reply,/USD/);assert.match(answer.reply,/haven’t applied your CAD budget/);assert.equal((answer.reply.match(/haven’t applied your CAD budget/g)||[]).length,1);assert.doesNotMatch(answer.reply,/converted|conversion rate|within your CAD|nickel.free/i);assert.deepEqual(calls.search,[]);});
test('selected product quote retains native subtotal and warns once when both storefront and budget currency differ',async()=>{const p=piece(1,{options:[{name:'Metal',values:['Sterling Silver']},{name:'Necklace Length',values:['18 Inch']},{name:'Engraving',values:['None']}]}),{answer,calls}=await run('How much is my selected option?',core.intentFrom('Bunny silver necklace under 40 CAD'),{products:[p],context:{currentHandle:p.handle,currency:'CAD',productControls:{handle:p.handle,productId:p.id,variantId:p.variants[0].id,quantity:3}}});assert.equal(answer.currencyMismatch,true);assert.equal(answer.productFacts.selectedVariant.price,54);assert.equal(answer.productFacts.selectedVariant.currency,'USD');assert.equal(answer.productFacts.itemTotalPrice,162);assert.match(answer.reply,/USD 54\.00 per item.*USD 162\.00/);assert.match(answer.reply,/local storefront pricing may differ/);assert.equal((answer.reply.match(/haven’t applied your CAD budget/g)||[]).length,1);assert.doesNotMatch(answer.reply,/converted|conversion rate|within your CAD/);assert.deepEqual(calls.search,[]);});
test('materials-only exact facts do not announce a budget mismatch without quoting prices',async()=>{const p=piece(1,{options:[{name:'Metal',values:['Sterling Silver']},{name:'Necklace Length',values:['18 Inch']},{name:'Engraving',values:['None']}]}),{answer}=await run('What materials is this piece available in?',core.intentFrom('Bunny silver necklace under 40 CAD'),{products:[p],context:{currentHandle:p.handle,currency:'CAD'}});assert.equal(answer.productFacts.status,'verified');assert.equal(answer.currencyMismatch,undefined);assert.equal(answer.preferences.budgetCurrency,'CAD');assert.match(answer.reply,/Sterling Silver/);assert.doesNotMatch(answer.reply,/haven’t applied|local storefront pricing may differ|USD 54/);});
for(const message of ['Open the first one','Add the first one to my bag'])test('requested exact action keeps currency disclosure and no new clarification question: '+message,async()=>{const {answer}=await run(message,core.intentFrom('Bunny silver necklace under 40 CAD'));assert.equal(answer.currencyMismatch,true);assert.match(answer.reply,/haven’t applied your CAD budget/);assert.equal(answer.question,null);assert.equal(answer.requestedAction.productId,piece().id);assert.equal(answer.requestedAction.type,message.startsWith('Open')?'navigate':'choose');});
test('same-currency semantic follow-up retains actual item cap and no foreign-budget warning',async()=>{const {answer}=await run('What do these mean?',core.intentFrom('Bunny silver necklace under 60 USD'));assert.equal(answer.currencyMismatch,undefined);assert.equal(answer.products[0].budgetApplied,true);assert.equal(answer.question,null);assert.doesNotMatch(answer.reply,/haven’t applied|Catalogue prices are shown/);});
