'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const server=require('../../netlify/functions/_britesConciergeVoice');
const client=require('../../brites-concierge-voice');
const {fixture:atomicFixture,request:req}=require('./voice-fixture36.cjs');
const SDP='v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\na=candidate:1 1 UDP 2122260223 192.0.2.10 50000 typ host\r\n';
const env={BRITES_GROWTH_SANDBOX:'1',BRITES_GROWTH_NAMESPACE:'Brites_Growth_Sandbox',BRITES_CONCIERGE_REALTIME_ENABLED:'1',BRITES_CONCIERGE_REALTIME_PUBLIC_DEMO:'0',OPENAI_API_KEY:'test-only-secret'};
function fixture(options={}){const f=atomicFixture({at:100000,env:{...env,...options.env},callId:'rtc_example',handler:{authorize:async()=>true,...options,...(options.env?{env:{...env,...options.env}}:{})}});return {...f,startRequest:()=>req({action:'start',sdp:SDP,demoToken:server.demoToken(env.OPENAI_API_KEY,100000)})};}
const start=f=>f.handler(f.startRequest());
test('disabled voice returns availability without provider/auth or inference',async()=>{let n=0;const f=fixture({env:{BRITES_CONCIERGE_REALTIME_ENABLED:'0'},authorize:async()=>{n++;return true;}});const r=await f.handler(req({action:'capabilities'}));assert.equal(r.status,200);assert.equal((await r.json()).enabled,false);assert.equal(n,0);assert.equal(f.calls.length,0);assert.equal(f.journal().length,0);});
test('invalid origin and methods cannot reach provider',async()=>{const f=fixture();assert.equal((await f.handler(req({action:'start',sdp:SDP},{origin:'https://evil.test'}))).status,403);assert.equal((await f.handler(new Request('https://preview.test/api/concierge-voice'))).status,405);assert.equal(f.calls.length,0);});
test('operator authentication required for enabled non-public actions',async()=>{const f=fixture({authorize:async()=>false});for(const action of ['capabilities','start','stop'])assert.equal((await f.handler(req({action,sdp:SDP}))).status,401);assert.equal(f.calls.length,0);});
test('provider credential, exact namespace and durable session guard fail closed',async()=>{for(const change of [{env:{OPENAI_API_KEY:''}},{env:{BRITES_GROWTH_NAMESPACE:'Live'}},{scheduleHangup:null},{service:{namespace:'Brites_Growth_Sandbox',setup:async()=>({enabled:false}),col:()=>({})}},{service:{namespace:'Brites_Growth_Sandbox',setup:async()=>({enabled:true})}}]){const f=fixture(change),r=await start(f);assert.equal(r.status,503);assert.equal(f.calls.length,0);assert.equal(f.journal().length,0);}});
test('SDP and action schema reject unknown configuration and oversized requests',async()=>{for(const body of [{action:'start',sdp:'not-sdp'},{action:'start',sdp:SDP,model:'unsafe'},{action:'start',sdp:'v=0\n'+'x'.repeat(66000)},{action:'delete'},{action:'start',sdp:'v=0\n'}]){const f=fixture(),r=await f.handler(req(body));assert.ok([400,413].includes(r.status));assert.equal(f.calls.length,0);}});
test('bounded journalled session sends unified config and never browser provider keys',async()=>{const f=fixture(),before=f.moneyBytes(),r=await start(f),value=await r.json();assert.equal(r.status,200);assert.equal(value.sdp,require('./voice-fixture36.cjs').SDP);assert.equal(value.maxDurationMs,120000);assert.equal(value.expiresAt,220000);assert.equal(JSON.stringify(value).includes(env.OPENAI_API_KEY),false);assert.equal(f.moneyBytes(),before);assert.deepEqual(f.deadlines,[{callId:'rtc_example',expiresAt:220000}]);assert.equal(f.journal()[0].stage,'call_verified');const conf=JSON.parse(f.calls[0].init.body.get('session'));assert.equal(conf.type,'realtime');assert.equal(conf.model,'gpt-realtime-2.1');assert.equal(conf.tools.length,6);assert.deepEqual(conf.tools.map(tool=>tool.name),['find_jewellery','inspect_jewellery','prepare_jewellery_action','read_storefront_services','control_storefront','set_avatar_performance']);assert.equal(conf.audio.output.voice,'marin');assert.equal(conf.max_output_tokens,1200);assert.equal(conf.tool_choice,'auto');assert.equal(conf.audio.input.turn_detection.interrupt_response,true);});
test('valid opaque stop token hangs up only the exact session; tampered tokens are rejected',async()=>{const f=fixture(),value=await (await start(f)).json();assert.equal((await f.handler(req({action:'stop',stopToken:value.stopToken+'x'}))).status,400);const result=await (await f.handler(req({action:'stop',stopToken:value.stopToken}))).json();assert.equal(result.stopped,true);assert.equal(f.calls.at(-1).url,'https://api.openai.com/v1/realtime/calls/rtc_example/hangup');assert.equal(server.readStopToken(value.stopToken,'different'),null);assert.equal(server.readStopToken(value.stopToken,env.OPENAI_API_KEY,1000000),null);});
test('deadline enqueue failure immediately hangs up instead of returning live SDP',async()=>{const f=fixture({scheduleHangup:async()=>false});assert.equal((await start(f)).status,503);assert.equal(f.calls.at(-1).url.endsWith('/rtc_example/hangup'),true);assert.equal(f.journal()[0].stage,'deadline_failed');});
test('obsolete reserveBudget injection is not consulted and provider failures remain private',async()=>{let reserves=0;const f=fixture({reserveBudget:async()=>{reserves++;return null;}}),before=f.moneyBytes();assert.equal((await start(f)).status,200);assert.equal(reserves,0);assert.equal(f.moneyBytes(),before);const failed=fixture({fetch:async()=>new Response('provider secret details',{status:429})});const result=await (await start(failed)).json();assert.equal(JSON.stringify(result).includes('secret'),false);assert.equal(failed.journal()[0].stage,'provider_rejected');});
test('tool contract only permits bounded jewellery query; meaning guidance covers occasion context',()=>{for(const implementation of [client,server]){assert.deepEqual(implementation.validateToolArguments({message:' A graduation gift '}),{message:'A graduation gift'});for(const value of [{message:'x',url:'https://evil.test'},{message:'x',action:'cart'},{message:''},{message:'x'.repeat(2001)},null,[]])assert.equal(implementation.validateToolArguments(value),null);}for(const word of ['graduation','weddings','birth','grief','seasons','Christmas','Before naming','qualified personal interpretations','Do not create a cart'])assert.ok(server.instructions.includes(word));});
test('RMS uses real signed audio samples and zero maps to zero',()=>{assert.equal(client.rms(new Float32Array(512)),0);assert.equal(client.rms(Float32Array.of(0.125,-0.125)),0.5);assert.equal(client.rms(Float32Array.of(1,-1)),1);});
function runtimeFixture({disabled=false,tool}={}){
 const events=[],transcripts=[],levels=[],errors=[],fetches=[],tracks=[],listeners=new Map(),audioNodes=[],contexts=[],sent=[],rafCalls=[];
 let channel,peer,hidden=false;
 function track(){const t={stopped:0,stop(){this.stopped++;}};tracks.push(t);return t;}
 const stream={getTracks:()=>tracks,getAudioTracks:()=>tracks};track();
 const doc={get hidden(){return hidden;},body:{appendChild(){}},createElement(){const a={autoplay:false,hidden:false,setAttribute(){},play:async()=>{},pause(){this.paused=true;},remove(){this.removed=true;},srcObject:null};audioNodes.push(a);return a;},addEventListener(k,f){listeners.set(k,f);},removeEventListener(k){listeners.delete(k);}};
 class Peer{constructor(){peer=this;this.connectionState='new';this.iceGatheringState='complete';}addTrack(){}createDataChannel(){channel={readyState:'connecting',send(raw){sent.push(JSON.parse(raw));if(JSON.parse(raw).type==='session.close')setImmediate(()=>this.onmessage?.({data:JSON.stringify({type:'session.closed'})}));},close(){this.readyState='closed';this.closed=true;}};return channel;}async createOffer(){return {sdp:SDP,type:'offer'};}async setLocalDescription(x){this.localDescription=x;}async setRemoteDescription(x){this.remoteDescription=x;setImmediate(()=>{channel.readyState='open';channel.onopen?.();});}close(){this.closed=true;}}
 class AudioContext{constructor(){contexts.push(this);}resume(){return Promise.resolve();}createMediaStreamSource(){return {connect(){},disconnect(){this.disconnected=true;}};}createAnalyser(){return {fftSize:512,disconnect(){this.disconnected=true;},getFloatTimeDomainData(samples){samples.fill(0.125);}};}close(){this.closed=true;return Promise.resolve();}}
 const runtime={document:doc,navigator:{mediaDevices:{getUserMedia:async()=>stream}},location:{origin:'https://preview.test'},RTCPeerConnection:Peer,AudioContext,AbortController,setTimeout,clearTimeout,requestAnimationFrame(f){rafCalls.push(f);return rafCalls.length;},cancelAnimationFrame(){},addEventListener(k,f){listeners.set(k,f);},removeEventListener(k){listeners.delete(k);},fetch:async(url,init)=>{const body=JSON.parse(init.body);fetches.push(body);if(body.action==='capabilities')return Response.json(disabled?{enabled:false,message:'Disabled for now.'}:{enabled:true});if(body.action==='start')return Response.json({sdp:SDP,stopToken:'opaque-token',maxDurationMs:120000});return Response.json({stopped:true});}};
 const voice=client.create({runtime,greeting:false,onState:x=>events.push(x),onTranscript:x=>transcripts.push(x),onLevel:x=>levels.push(x),onError:x=>errors.push(x),onTool:tool|| (async()=>({verified:true,reply:'Checked current catalogue.',products:[]}))});
 return {runtime,voice,events,transcripts,levels,errors,fetches,tracks,listeners,audioNodes,contexts,sent,rafCalls,channel:()=>channel,peer:()=>peer,stream,hide:()=>{hidden=true;listeners.get('visibilitychange')?.();},emit:x=>channel.onmessage?.({data:JSON.stringify(x)})};
}
test('adapter construction does not access microphone or provider; disabled capability stops before mic',async()=>{const f=runtimeFixture({disabled:true});assert.equal(f.fetches.length,0);assert.equal(f.voice.state,'idle');assert.equal(await f.voice.start(),false);assert.equal(f.fetches.length,1);assert.equal(f.audioNodes.length,0);assert.equal(f.peer(),undefined);await f.voice.dispose();assert.equal(f.listeners.size,0);});
test('actual media lifecycle, transcripts, tool call dedup, interrupt and graceful close cleanup',async()=>{let tools=0;const f=runtimeFixture({tool:async()=>{tools++;return {verified:true,reply:'A checked piece',products:[]};}});assert.equal(await f.voice.start(),true);assert.equal(f.voice.state,'listening');assert.equal(f.levels[0].input,0.5);f.emit({type:'output_audio_buffer.started'});assert.equal(f.voice.state,'speaking');f.emit({type:'response.output_audio_transcript.delta',delta:'Hello'});assert.equal(f.transcripts[0].delta,'Hello');f.emit({type:'input_audio_buffer.speech_started'});assert.equal(f.voice.state,'listening');assert.ok(f.sent.some(x=>x.type==='response.cancel'));assert.ok(f.sent.some(x=>x.type==='output_audio_buffer.clear'));f.emit({type:'input_audio_buffer.speech_stopped'});const call={type:'response.function_call_arguments.done',name:'find_jewellery',call_id:'call_1',arguments:'{"message":"Graduation gift"}'};f.emit(call);f.emit(call);await new Promise(resolve=>setImmediate(resolve));assert.equal(tools,1);assert.ok(f.sent.some(x=>x.type==='conversation.item.create'));assert.ok(f.sent.some(x=>x.type==='response.create'));await f.voice.stop();assert.equal(f.voice.state,'idle');assert.ok(f.tracks.every(x=>x.stopped>0));assert.equal(f.peer().closed,true);assert.equal(f.channel().closed,true);assert.equal(f.contexts[0].closed,true);assert.equal(f.audioNodes[0].paused,true);assert.equal(f.audioNodes[0].srcObject,null);assert.equal(f.fetches.at(-1).action,'stop');await f.voice.dispose();assert.equal(f.listeners.size,0);});
test('hidden page stops microphone and context; invalid tool cannot perform actions',async()=>{let calls=0;const f=runtimeFixture({tool:async()=>{calls++;return {};}});await f.voice.start();f.emit({type:'response.function_call_arguments.done',name:'navigate',call_id:'evil',arguments:'{"message":"Go"}'});await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,0);assert.ok(f.sent.some(x=>x.item?.output?.includes('verified')));f.hide();await f.voice.stop();assert.equal(f.voice.state,'idle');assert.ok(f.tracks[0].stopped);await f.voice.dispose();});
test('foreign browser endpoint is rejected before any fetch',()=>{assert.throws(()=>client.create({endpoint:'https://evil.test/voice',runtime:{location:{origin:'https://preview.test'}}}),/must be on this website/);});
test('cancel while microphone permission is pending settles start and stops late tracks',async()=>{const f=runtimeFixture();let grant;f.runtime.navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>{grant=resolve;});const starting=f.voice.start();await new Promise(resolve=>setImmediate(resolve));assert.equal(typeof grant,'function');await f.voice.stop();assert.equal(await starting,false);assert.equal(f.voice.state,'idle');grant(f.stream);await new Promise(resolve=>setImmediate(resolve));assert.ok(f.tracks[0].stopped);assert.equal(f.peer(),undefined);await f.voice.dispose();});
test('microphone refusal cleans up and preserves text fallback without session creation',async()=>{const f=runtimeFixture();f.runtime.navigator.mediaDevices.getUserMedia=async()=>{throw Error('Microphone denied.');};assert.equal(await f.voice.start(),false);assert.equal(f.voice.state,'idle');assert.equal(f.fetches.some(x=>x.action==='start'),false);assert.ok(f.errors.includes('Your microphone could not be opened. You can still type.'));await f.voice.dispose();});
test('atomic reservation respects existing disabled flag and daily cap; unverified usage stays reserved',async()=>{let data={spentUsd:0.2,reservedUsd:0.4,calls:2},sets=0;const db={runTransaction:async task=>task({get:async()=>({exists:true,data:()=>({...data})}),set(ref,next){sets++;data=next;}})},collection={firestore:db,doc:()=>({})};let enabled=true;const service={setup:async()=>({aiEnabled:enabled,aiDailyUsdCap:1}),col:()=>collection};const reserve=server.createBudgetReservation(service,{now:()=>100000});assert.equal(await reserve(0.5),null);assert.equal(sets,0);assert.deepEqual(await reserve(0.3),{allocatedUsd:0.3,reconcile:'provider_evidence_required'});assert.equal(data.reservedUsd,0.7);assert.equal(data.calls,3);enabled=false;assert.equal(await reserve(0.1),null);assert.equal(sets,1);assert.equal(await reserve(NaN),null);});
