'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const core=require('../../netlify/functions/_britesGrowth.js');
const NOW=Date.parse('2026-10-03T12:00:00Z');
function piece(id=1,overrides={}){return {id:'gid://shopify/Product/'+id,handle:'bunny-'+id,title:'Bunny Charm Necklace',url:'https://britesjewelry.com/products/bunny-'+id,currency:'USD',description:'A bunny design with an included chain.',type:'Necklace',tags:['rabbit'],image:null,imageAlt:'Bunny charm',options:[{name:'Necklace Length',values:['18 Inches']}],variants:[{id:'gid://shopify/ProductVariant/'+(id*100+1),numericId:String(id*100+1),title:'Sterling Silver',price:54,available:true,options:[{name:'Metal',value:'Sterling Silver'}]},{id:'gid://shopify/ProductVariant/'+(id*100+2),numericId:String(id*100+2),title:'Gold Filled',price:59,available:true,options:[{name:'Metal',value:'Gold Filled'}]}],variantsComplete:true,checkedAt:NOW,...overrides};}
function dossier(p=piece()){return {schema:1,productId:p.id,handle:p.handle,status:'approved',privateOwnerSecret:'PRIVATE_OWNER_RECORD',rank:1,orders:999,sources:[{id:'p',url:p.url,title:p.title,excerpt:'A bunny design in sterling silver.',checkedAt:NOW,reviewed:true},{id:'m',url:'https://example.edu/museum/rabbit',title:'Museum interpretation',excerpt:'The rabbit can be interpreted as renewal in this collection.',checkedAt:NOW,reviewed:true},{id:'c',url:'https://example.org/shop/rabbit',title:'Other rabbit necklace',excerpt:'A rabbit necklace is listed at USD 75.',checkedAt:NOW,reviewed:true}],facts:[{productId:p.id,text:'This is a bunny design.',quote:'A bunny design',sourceIds:['p']}],competitors:[{name:'Other offer',url:'https://example.org/shop/rabbit',price:75,currency:'USD',sourceIds:['c'],spend:{status:'unknown'}}],buyerIntents:[{text:'An animal themed gift',basis:'hypothesis'}],recommendations:[{channel:'ads',basis:'hypothesis',action:'Test recipient specific framing.',measure:'Confirmed purchase conversion value.',sourceIds:['p','c']}],meanings:[{text:'A rabbit may suggest renewal in the cited collection.',context:'Interpretation of a museum collection, not a universal meaning.',kind:'interpretation',sourceIds:['m'],privateNote:'PRIVATE_MEANING_NOTE'}]};}

test('recipient, occasion, type, metal and item budget parse together',()=>{const p=core.intentFrom('A bunny necklace for my daughter’s birthday in silver under $60');assert.equal(p.query,'bunny');assert.equal(p.recipient,'daughter');assert.equal(p.occasion,'birthday');assert.equal(p.type,'necklace');assert.equal(p.metal,'silver');assert.equal(p.budget,60);assert.equal(p.budgetCurrency,'USD');});
test('latest type and metal replace earlier choices without reviving negated ones',()=>{let p=core.intentFrom('Bunny gold necklace under $90');p=core.intentFrom('Not a necklace, earrings instead. Not gold, silver please',[],p);assert.equal(p.type,'earrings');assert.equal(p.metal,'silver');assert.ok(p.excludedTypes.includes('necklace'));assert.ok(p.excludedMetals.includes('gold'));assert.equal(p.query,'bunny');assert.equal(p.budget,90);});
test('contrast without a comma handles a new explicit positive request',()=>{const p=core.intentFrom("No earrings I want a necklace, and not gold I prefer silver");assert.equal(p.type,'necklace');assert.equal(p.metal,'silver');});
test('no gold or silver excludes both, while a later affirmative silver clears it',()=>{let p=core.intentFrom('No gold or silver');assert.deepEqual(p.excludedMetals,['gold','silver']);p=core.intentFrom('Silver please',[],p);assert.equal(p.metal,'silver');assert.deepEqual(p.excludedMetals,['gold']);});
test('a rejected motif is removed and a new motif replaces it',()=>{const p=core.intentFrom('Actually not cats, she loves rabbits instead',[],core.intentFrom('Cat jewelry for my wife'));assert.deepEqual(p.interests,['bunny']);assert.ok(p.excludedInterests.includes('cat'));assert.equal(p.query,'bunny');});
test('changing recipient drops the previous motif and occasion',()=>{const p=core.intentFrom('Actually this gift is for my nurse friend',[],core.intentFrom('A bunny for my daughter’s graduation'));assert.equal(p.recipient,'friend');assert.equal(p.occasion,null);assert.deepEqual(p.interests,['stethoscope']);assert.ok(!p.query.includes('bunny'));});
test('rose gold is a metal and does not accidentally introduce a rose motif',()=>{const p=core.intentFrom('Rose gold necklace',[],core.intentFrom('Bunny necklace'));assert.equal(p.metal,'rose gold');assert.deepEqual(p.interests,['bunny']);});
test('budget ranges, changes, currency and removing the limit are preserved accurately',()=>{let p=core.intentFrom('Between $40 and $80 CAD');assert.equal(p.minBudget,40);assert.equal(p.budget,80);assert.equal(p.budgetCurrency,'CAD');p=core.intentFrom('Under 65',[],p);assert.equal(p.minBudget,null);assert.equal(p.budget,65);assert.equal(p.budgetCurrency,'CAD');p=core.intentFrom('No budget limit',[],p);assert.equal(p.budget,null);assert.equal(p.budgetCurrency,null);});
test('a bare budget answer and explicit reset work without inventing a motif',()=>{let p=core.intentFrom('Bunny earrings in gold');p=core.intentFrom('$75',[],p);assert.equal(p.budget,75);assert.equal(p.query,'bunny');p=core.intentFrom('Start fresh',[],p);assert.equal(p.query,'');assert.equal(p.type,null);assert.equal(p.budget,null);});
test('explicit unlimited budget clears prior bounds and persists as a sanitized boolean',()=>{
  let p=core.intentFrom('Bunny necklace between $40 and $80 CAD');p=core.intentFrom('No budget limit',[],p);
  assert.equal(p.unlimitedBudget,true);assert.equal(p.budget,null);assert.equal(p.minBudget,null);assert.equal(p.budgetCurrency,null);assert.equal(p.currency,'CAD');assert.equal(p.query,'bunny');
  p=core.intentFrom('Silver please',[],JSON.parse(JSON.stringify(p)));assert.equal(p.unlimitedBudget,true);assert.equal(p.budget,null);assert.equal(p.metal,'silver');assert.equal(p.query,'bunny');
});
test('unlimited and removal phrases preserve motif instead of searching for budget terminology',()=>{
  for(const message of ['Unlimited budget','My budget is unlimited','Any price','Remove my budget','Forget the budget','No price limit']){const p=core.intentFrom(message,[],core.intentFrom('Bunny necklace under $60'));assert.equal(p.unlimitedBudget,true,message);assert.equal(p.budget,null,message);assert.equal(p.query,'bunny',message);}
  const p=core.intentFrom('Unlimited budget; she likes origami',[],core.intentFrom('Bunny necklace under $60'));assert.equal(p.unlimitedBudget,true);assert.equal(p.query,'origami');
});
test('latest explicit maximum or range reinstates a numeric cap after unlimited choice',()=>{
  const before=core.intentFrom('Bunny necklace, no budget limit');
  for(const [message,budget,minBudget,currency] of [['Under $70 CAD',70,null,'CAD'],['Between 40 and 80 CAD',80,40,'CAD'],['$50',50,null,'USD'],['No more than $65',65,null,'USD'],['No more than $65 CAD',65,null,'CAD'],['Budget 0',0,null,'USD']]){const p=core.intentFrom(message,[],before);assert.equal(p.unlimitedBudget,false,message);assert.equal(p.budget,budget,message);assert.equal(p.minBudget,minBudget,message);assert.equal(p.budgetCurrency,currency,message);assert.equal(p.query,'bunny',message);}
});
test('latest budget instruction wins within one message in both directions',()=>{
  let p=core.intentFrom('No budget limit, actually under $70 CAD',[],core.intentFrom('Bunny necklace'));assert.equal(p.unlimitedBudget,false);assert.equal(p.budget,70);assert.equal(p.budgetCurrency,'CAD');
  p=core.intentFrom('Under $70 CAD, actually no budget limit',[],p);assert.equal(p.unlimitedBudget,true);assert.equal(p.budget,null);assert.equal(p.budgetCurrency,null);assert.equal(p.currency,'CAD');
});
test('negated price removal and maximum do not erase or replace an existing cap',()=>{
  const before=core.intentFrom('Bunny necklace under $60 CAD');
  for(const message of ["Don't remove my budget",'Do not forget my budget','Not unlimited budget','Not any price','Not under $40 USD','Not under $40.50 USD']){const p=core.intentFrom(message,[],before);assert.equal(p.unlimitedBudget,false,message);assert.equal(p.budget,60,message);assert.equal(p.budgetCurrency,'CAD',message);assert.equal(p.query,'bunny',message);}
  const p=core.intentFrom('Not under $40, under $75 CAD instead',[],before);assert.equal(p.budget,75);assert.equal(p.unlimitedBudget,false);
});
test('unknown or undecided budget is not an unlimited choice or a new product interest',()=>{
  const before=core.intentFrom('Bunny necklace under $60 CAD');
  for(const message of ["I don't know my budget yet",'Not sure about my budget','No budget yet','My budget is unknown','No budget']){const p=core.intentFrom(message,[],before);assert.equal(p.unlimitedBudget,false,message);assert.equal(p.budget,null,message);assert.equal(p.minBudget,null,message);assert.equal(p.budgetCurrency,null,message);assert.equal(p.query,'bunny',message);}
  const p=core.intentFrom('No budget yet, but under $80 CAD for now',[],before);assert.equal(p.budget,80);assert.equal(p.unlimitedBudget,false);
});
test('no-limit phrase does not negate a later affirmative metal, type or currency',()=>{
  const p=core.intentFrom('No budget limit in CAD and gold bunny necklace');assert.equal(p.unlimitedBudget,true);assert.equal(p.currency,'CAD');assert.equal(p.budgetCurrency,null);assert.equal(p.metal,'gold');assert.equal(p.type,'necklace');assert.deepEqual(p.interests,['bunny']);
});
test('unlimited preference is strict and cannot contradict a valid numeric saved cap',()=>{
  for(const unlimitedBudget of ['true',1,[],{}])assert.equal(core.shopperPreferences({unlimitedBudget}).unlimitedBudget,false);
  const capped=core.shopperPreferences({unlimitedBudget:true,budget:0,currency:'CAD'});assert.equal(capped.unlimitedBudget,false);assert.equal(capped.budget,0);assert.equal(capped.budgetCurrency,'CAD');
  const free=core.shopperPreferences({unlimitedBudget:true,minBudget:40,budgetCurrency:'CAD',currency:'CAD',privateFlag:'DO_NOT_EXPORT'});assert.equal(free.unlimitedBudget,true);assert.equal(free.minBudget,null);assert.equal(free.budgetCurrency,null);assert.equal(free.currency,'CAD');assert.ok(!('privateFlag' in free));
});
test('history reconstructs unlimited choice and a saved choice cannot replay an old price cap',()=>{
  const history=[{role:'user',content:'Bunny necklace under $30 CAD'},{role:'user',content:'No budget limit'}];
  const p=core.intentFrom('Silver please',history);assert.equal(p.query,'bunny');assert.equal(p.unlimitedBudget,true);assert.equal(p.budget,null);assert.equal(p.currency,'CAD');
  const saved=core.intentFrom('Bunny necklace',history.slice(0,1),{unlimitedBudget:true,currency:'CAD'});assert.equal(saved.unlimitedBudget,true);assert.equal(saved.budget,null);
});
test('reset forgets old unlimited choice, and a new no-limit instruction survives reset',()=>{
  const before=core.intentFrom('Bunny necklace, unlimited budget');let p=core.intentFrom('Start fresh',[],before);assert.equal(p.unlimitedBudget,false);assert.equal(p.budget,null);assert.equal(p.query,'');
  p=core.intentFrom('Start fresh. Cat earrings, no budget limit',[],before);assert.equal(p.unlimitedBudget,true);assert.equal(p.type,'earrings');assert.deepEqual(p.interests,['cat']);assert.equal(p.budget,null);
});
test('invalid numeric caps and necklace length ranges do not replace an explicit unlimited choice',()=>{
  const before=core.intentFrom('Bunny necklace, no budget limit');
  for(const message of ['Budget 1000001','Between 90 and 40 CAD','Necklace length between 14 and 18 inches']){const p=core.intentFrom(message,[],before);assert.equal(p.unlimitedBudget,true,message);assert.equal(p.budget,null,message);}
});
test('unknown interests remain searchable, and short follow-up questions preserve them',()=>{let p=core.intentFrom('She loves origami');assert.equal(p.query,'origami');p=core.intentFrom('What does that symbolize?',[],p);assert.equal(p.query,'origami');});
test('untrusted saved preference values are reduced to the public allowlist',()=>{const p=core.shopperPreferences({metal:'.*',budget:Infinity,type:'checkout',currency:'javascript:',privateKey:'SHOULD_NOT_SURVIVE',interests:['bunny',42]});assert.equal(p.metal,null);assert.equal(p.budget,null);assert.equal(p.type,null);assert.equal(p.currency,'USD');assert.deepEqual(p.interests,['bunny']);assert.ok(!('privateKey' in p));});
test('history is used to reconstruct preferences only when there is no saved state',()=>{const p=core.intentFrom('Silver please',[{role:'user',content:'Bunny earrings under $60'},{role:'assistant',content:'Would you like gold?'}]);assert.equal(p.query,'bunny');assert.equal(p.type,'earrings');assert.equal(p.budget,60);assert.equal(p.metal,'silver');});

test('ranking requires the right type, motif, live inventory and matching budget variant',()=>{const wrongType=piece(2,{title:'Bunny Stud Earrings',type:'Earrings'}),sold=piece(3,{variants:piece(3).variants.map(v=>({...v,available:false}))}),expensive=piece(4,{variants:piece(4).variants.map(v=>({...v,price:200}))}),wrongMotif=piece(5,{title:'Cat Charm Necklace',tags:['cat']});const list=core.rankProducts([wrongType,sold,expensive,wrongMotif,piece()],core.intentFrom('Bunny silver necklace under $55'),NOW);assert.equal(list.length,1);assert.equal(list[0].id,piece().id);assert.equal(list[0].variants.length,1);assert.equal(list[0].minPrice,54);assert.ok(!('sku' in list[0].variants[0]));});
test('gold preference excludes rose gold; explicit rose gold selects it',()=>{const p=piece(1,{variants:[{...piece().variants[1],title:'Rose Gold Filled'}]});assert.equal(core.rankProducts([p],core.intentFrom('Bunny gold necklace'),NOW).length,0);assert.equal(core.rankProducts([p],core.intentFrom('Bunny rose gold necklace'),NOW).length,1);});
test('stale catalogue records and future freshness claims are not recommended',()=>{assert.equal(core.rankProducts([piece(1,{checkedAt:NOW-6*60000}),piece(2,{checkedAt:NOW+120000})],core.intentFrom('Bunny necklace'),NOW).length,0);});
test('a CAD budget is never compared to USD catalogue amounts',()=>{const list=core.rankProducts([piece()],core.intentFrom('Bunny necklace under 50 CAD'),NOW);assert.equal(list.length,1);assert.equal(list[0].budgetApplied,false);assert.ok(!list[0].why.includes('within your'));});
test('no engraving keeps the unengraved option when engraving is optional',()=>{const p=piece(1,{title:'Engravable Bunny Necklace',variants:[{...piece().variants[0],title:'Sterling Silver / No engraving'},{...piece().variants[1],title:'Gold Filled / With engraving'}]});const list=core.rankProducts([p],core.intentFrom('Bunny necklace without engraving'),NOW);assert.equal(list.length,1);assert.equal(list[0].variants.length,1);assert.equal(list[0].variants[0].title,'Sterling Silver / No engraving');});
test('a multi-style product recommends only the verified complete jewelry option',()=>{const p=piece(1,{variants:[{...piece().variants[0],title:'Sterling Silver / 18 Inches'},{...piece().variants[1],title:'Gold Filled / Huggie Charm'}]});const necklace=core.rankProducts([p],core.intentFrom('Bunny necklace'),NOW);assert.equal(necklace[0].variants.length,1);assert.match(necklace[0].variants[0].title,/18 Inches/);const earrings=core.rankProducts([p],core.intentFrom('Bunny earrings'),NOW);assert.equal(earrings.length,0);});
test('live bunny charm listings with necklace SEO titles do not become complete necklaces',()=>{const charms=[piece(9208556159139,{title:'Rabbit Bunny Charm Necklace',type:'Charm',description:'Rabbit bunny design',options:[{name:'Style',values:['Necklace Charm']}],variants:[{...piece().variants[0],title:'Sterling Silver / Necklace Charm',price:29}]}),piece(9214212898979,{title:'Rabbit Bunny Necklace Charm',type:'Charm',description:'Rabbit bunny design',options:[{name:'Style',values:['Necklace Charm']}],variants:[{...piece().variants[0],title:'Sterling Silver / Necklace Charm',price:29}]})];const complete=piece(3,{title:'Rabbit Bunny Necklace',variants:[{...piece(3).variants[0],title:'Sterling Silver / 18 Inches',price:54}]});const necklaces=core.rankProducts([...charms,complete],core.intentFrom('Silver bunny necklace under $60'),NOW);assert.equal(necklaces.length,1);assert.equal(necklaces[0].id,complete.id);assert.equal(necklaces[0].minPrice,54);assert.equal(core.rankProducts(charms,core.intentFrom('Bunny earrings'),NOW).length,0);assert.equal(core.rankProducts(charms,core.intentFrom('A bunny gift'),NOW).length,0);const explicit=core.rankProducts(charms,core.intentFrom('A silver bunny charm under $40'),NOW);assert.equal(explicit.length,2);assert.ok(explicit.every(p=>p.partsOnly));});
test('full necklace requires the current type and documented chain configuration',()=>{for(const p of [piece(1,{type:'',description:'Bunny necklace design',options:[]}),piece(2,{description:'Bunny necklace design',options:[]}),piece(3,{description:'A chain is not included.',options:[{name:'Necklace Length',values:['18 Inches']}]}),piece(4,{description:'Pendant only. No chain.',options:[]})])assert.equal(core.rankProducts([p],core.intentFrom('Bunny necklace'),NOW).length,0);for(const p of [piece(5,{description:'Includes a sterling silver chain.',options:[]}),piece(6,{description:'Bunny design',options:[{name:'Chain Length',values:['16 Inches','18 Inches']}]}),piece(7,{description:'Bunny design',options:[],variants:[{...piece(7).variants[0],options:[{name:'Necklace Length',value:'18 Inches'}]}]})])assert.equal(core.rankProducts([p],core.intentFrom('Bunny necklace'),NOW).length,1);});
test('legacy descriptions cannot establish a wrong motif or override current product type',()=>{const p=piece(1,{title:'Wolf Necklace',tags:['wolf'],description:'A bear design. Includes a chain.'});assert.equal(core.rankProducts([p],core.intentFrom('Bear necklace'),NOW).length,0);assert.equal(core.rankProducts([p],core.intentFrom('Wolf earrings'),NOW).length,0);});
test('latest negation of an earlier motif wins within the same message',()=>{const p=core.intentFrom('She loves rabbits but not bunny jewelry');assert.ok(p.excludedInterests.includes('bunny'));assert.equal(p.query,'');});
test('raise the budget to is treated as an explicit limit change',()=>{const p=core.intentFrom('Raise my budget to $80',[],core.intentFrom('Bunny earrings under $60'));assert.equal(p.budget,80);assert.equal(p.query,'bunny');});

test('public meanings include exact product binding and inspected citations, never owner fields',()=>{const p=piece(),data=dossier(p),out=core.publicMeanings([data],[p.id],NOW);assert.equal(out.length,1);assert.equal(out[0].productId,p.id);assert.equal(out[0].sources[0].url,data.sources[1].url);assert.ok(!JSON.stringify(out).includes('PRIVATE'));assert.ok(!JSON.stringify(out).includes('orders'));assert.equal(core.publicMeanings([data],['gid://shopify/Product/99'],NOW).length,0);});
test('unapproved meanings, missing citations and stale/unreviewed sources never project publicly',()=>{for(const d of [dossier()]){for(const bad of [{...d,status:'draft'},{...d,meanings:[{...d.meanings[0],sourceIds:['missing']}]},{...d,sources:d.sources.map(s=>({...s,reviewed:false}))},{...d,sources:d.sources.map(s=>({...s,checkedAt:NOW-31*86400000}))}])assert.equal(core.publicMeanings([bad],[piece().id],NOW).length,0);}});
test('editorial shopper prompts never appear inside a public product interpretation',()=>{const d=dossier();d.meanings[0].text='A rabbit may remind someone of a beloved pet. Ask whether the recipient owns a rabbit before suggesting that story.';const out=core.publicMeanings([d],[piece().id],NOW);assert.equal(out.length,1);assert.equal(out[0].text,'A rabbit may remind someone of a beloved pet.');d.meanings[0].text='Ask whether the recipient owns a rabbit.';assert.equal(core.publicMeanings([d],[piece().id],NOW).length,0);});
test('public meanings suppress competitor retailer citations together with the dependent story',()=>{const d=dossier();d.sources[1].url='https://ginakimjewellery.com/products/silver-bunny-rabbit-necklace-personalised';d.competitors.push({name:'Gina Kim Jewellery',url:'https://www.ginakimjewellery.com/products/silver-bunny-rabbit-necklace-personalised'});assert.deepEqual(core.publicMeanings([d],[piece().id],NOW),[]);d.sources[1].url='https://stories.ginakimjewellery.com/bunny-symbolism';assert.deepEqual(core.publicMeanings([d],[piece().id],NOW),[]);});
test('neutral and own-catalogue interpretations retain their reviewed citations',()=>{const d=dossier();assert.equal(core.publicMeanings([d],[piece().id],NOW)[0].sources[0].url,d.sources[1].url);d.meanings[0].sourceIds=['p'];assert.equal(core.publicMeanings([d],[piece().id],NOW)[0].sources[0].url,piece().url);d.meanings[0].sourceIds=['p','c'];assert.deepEqual(core.publicMeanings([d],[piece().id],NOW),[]);});
test('a competitor quote cannot establish a commercial fact about this product',()=>{const d=dossier();d.facts[0].sourceIds=['c'];d.facts[0].quote='A rabbit necklace';assert.equal(core.validateDossier(d,piece(),NOW).ok,false);});
test('known competitor spend needs reviewed disclosed spending, not an observed product price',()=>{const d=dossier();d.competitors[0].spend={status:'known',sourceIds:['c'],quote:'USD 75'};assert.equal(core.validateDossier(d,piece(),NOW).ok,false);d.competitors[0].spend={status:'known',sourceIds:['missing'],quote:'We spent USD 75.'};assert.equal(core.validateDossier(d,piece(),NOW).ok,false);d.sources[2].excerpt='The company disclosed advertising spending of USD 750 monthly.';d.competitors[0].spend={status:'known',sourceIds:['c'],quote:'advertising spending of USD 750 monthly'};assert.equal(core.validateDossier(d,piece(),NOW).ok,true);});
test('malformed dossier objects reject with a validation result instead of crashing',()=>{for(const d of [null,[],{...dossier(),sources:[null]},{...dossier(),recommendations:'bad'},{...dossier(),facts:[{sourceIds:'p'}]}])assert.equal(core.validateDossier(d,piece(),NOW).ok,false);});

function deps(products=[piece()],research=[dossier()]){return {service:{saveProducts:async()=>{},research:async()=>research},shopify:{search:async()=>({products}),byHandle:async h=>products.find(p=>p.handle===h)||null},now:()=>NOW};}
test('concierge handles ordinary discovery and exposes only shopper data',async()=>{const answer=await core.concierge({...deps(),message:'Bunny silver necklace under $60'});assert.equal(answer.products.length,1);assert.equal(answer.meanings.length,1);assert.equal(answer.question,null);assert.ok(!JSON.stringify(answer).includes('PRIVATE'));assert.ok(!JSON.stringify(answer).includes('orders'));});
test('no budget limit is acknowledged without repeating the item-budget question across follow-ups',async()=>{
  const first=await core.concierge({...deps(),message:'Bunny necklace, no budget limit'});assert.equal(first.preferences.unlimitedBudget,true);assert.equal(first.products.length,1);assert.match(first.question,/metal preference/);assert.ok(!/budget|price limit/i.test(first.question));
  const next=await core.concierge({...deps(),message:'Silver please',preferences:first.preferences});assert.equal(next.preferences.unlimitedBudget,true);assert.equal(next.preferences.budget,null);assert.equal(next.products.length,1);assert.equal(next.question,null);
});
test('observed gift-reset request preserves new unlimited choice and asks about metal instead of budget',async()=>{
  const cat=piece(2,{handle:'cat-studs',url:'https://britesjewelry.com/products/cat-studs',title:'Cat Stud Earrings',type:'Earrings',tags:['cat'],description:'Cat stud earrings.',options:[{name:'Metal',values:['Sterling Silver','Gold Filled']}]});
  const answer=await core.concierge({...deps([cat],[]),message:'Start fresh. This gift is for my friend: cat earrings, no budget limit.',history:[{role:'user',content:'A gold bunny necklace for my daughter’s birthday under $60.'},{role:'assistant',content:'Here are bunny necklaces.'}],preferences:core.intentFrom('A gold bunny necklace for my daughter’s birthday under $60'),context:{productHandles:[piece().handle],currency:'USD'}});
  assert.equal(answer.preferences.unlimitedBudget,true);assert.equal(answer.preferences.budget,null);assert.equal(answer.preferences.recipient,'friend');assert.equal(answer.preferences.metal,null);assert.equal(answer.preferences.occasion,null);assert.equal(answer.products[0].id,cat.id);assert.match(answer.question,/metal preference/);assert.ok(!/budget|price limit/.test(answer.question));
});
test('unknown budget still permits optional budget guidance rather than becoming unlimited',async()=>{
  const answer=await core.concierge({...deps(),message:'Bunny silver necklace; I do not know my budget yet'});assert.equal(answer.preferences.unlimitedBudget,false);assert.equal(answer.preferences.budget,null);assert.match(answer.question,/item budget/);assert.equal(answer.products.length,1);
});
test('unlimited CAD preference applies no dollar filter or currency-conversion claim; a later CAD cap remains mismatched',async()=>{
  const first=await core.concierge({...deps(),message:'Bunny silver necklace, no budget limit',context:{currency:'CAD'}});assert.equal(first.preferences.currency,'CAD');assert.equal(first.preferences.unlimitedBudget,true);assert.equal(first.preferences.budgetCurrency,null);assert.equal(first.currencyMismatch,undefined);assert.equal(first.products[0].currency,'USD');assert.equal(first.products[0].budgetApplied,false);assert.ok(!/convert|exchange rate|within your/.test(first.reply));
  const next=await core.concierge({...deps(),message:'Actually under $50 CAD',preferences:first.preferences});assert.equal(next.preferences.unlimitedBudget,false);assert.equal(next.preferences.budget,50);assert.equal(next.currencyMismatch,true);assert.match(next.reply,/haven’t applied your CAD budget/);assert.equal(next.products[0].budgetApplied,false);
});
test('runtime question refinement cannot repeat a declined budget question',async()=>{
  for(const question of ['What price range should I stay within?','Does cost matter to the gift choice?','Do you have a spending cap in mind?']){const answer=await core.concierge({...deps(),message:'Bunny necklace with unlimited budget',ai:async()=>({intent:'gift',question})});assert.equal(answer.preferences.unlimitedBudget,true);assert.match(answer.question,/metal preference/);assert.ok(!/budget|price|spending|cost/.test(answer.question));}
});
test('transient exact-context retrieval failure propagates rather than pretending catalogue has no stock',async()=>{
  let searched=0,saved=0;const d=deps();d.shopify.byHandle=async()=>{throw Error('The published storefront could not be checked.');};d.shopify.search=async()=>{searched++;return {products:[piece()]};};d.service.saveProducts=async()=>{saved++;};
  await assert.rejects(core.concierge({...d,message:'Tell me the meaning of the first necklace',context:{productHandles:[piece().handle]}}),/published storefront could not be checked/);assert.equal(searched,0);assert.equal(saved,0);
});
test('uncertain budget currency is explicit, and local browser pricing may resolve it',async()=>{const answer=await core.concierge({...deps(),message:'Bunny silver necklace under $50 CAD'});assert.equal(answer.currencyMismatch,true);assert.match(answer.reply,/haven’t applied your CAD budget/);assert.equal(answer.products[0].budgetApplied,false);});
test('first explicit dollar budget adopts verified shopper storefront currency',async()=>{const answer=await core.concierge({...deps(),message:'Bunny necklace under $50',context:{currency:'CAD'}});assert.equal(answer.preferences.budgetCurrency,'CAD');assert.equal(answer.currencyMismatch,true);});
test('missing reviewed symbolism is admitted instead of generated',async()=>{const answer=await core.concierge({...deps([piece()],[]),message:'What does the bunny symbolize?'});assert.equal(answer.meanings.length,0);assert.match(answer.reply,/don’t yet have reviewed symbolism/);});
test('knowledge storage outage keeps live product selection available',async()=>{const d=deps();d.service.research=async()=>{throw Error('Private storage unavailable');};const answer=await core.concierge({...d,message:'Bunny necklace'});assert.equal(answer.products.length,1);assert.equal(answer.knowledgeUnavailable,true);assert.ok(!JSON.stringify(answer).includes('Private storage'));});
test('shipping and return answers link current policies without inventing delivery dates',async()=>{const answer=await core.concierge({...deps(),message:'Will my bunny necklace arrive tomorrow? What is the return policy?'});assert.match(answer.reply,/current shop policies/);assert.equal(answer.policyLinks.length,2);assert.ok(!/guarantee|\d+ days/.test(answer.reply));});
test('ship-wheel discovery and returning to a product page do not become policy questions',async()=>{for(const message of ['Find a ship wheel necklace','Return to the first page']){const answer=await core.concierge({...deps(),message});assert.equal(answer.policyLinks,undefined);assert.doesNotMatch(answer.reply,/Shipping timing and returns/);}});
test('meaning and comparisons preserve the displayed product order',async()=>{const a=piece(1),b=piece(2,{variants:piece(2).variants.map(v=>({...v,price:10}))});const answer=await core.concierge({...deps([a,b]),message:'Open the second one',preferences:core.intentFrom('Bunny necklace'),context:{productHandles:[a.handle,b.handle]}});assert.equal(answer.products[0].id,a.id);assert.equal(answer.requestedAction.productId,b.id);assert.equal(answer.requestedAction.type,'navigate');});
test('add to bag requests only open exact options; they never purchase or mutate',async()=>{const answer=await core.concierge({...deps(),message:'Add the first one to my bag',preferences:core.intentFrom('Bunny necklace'),context:{productHandles:[piece().handle]}});assert.equal(answer.requestedAction.type,'choose');assert.match(answer.reply,/confirm before/);});
test('negated navigation does not trigger an action',()=>{assert.equal(core.shopperAction("Don't open the first one",[piece()]),null);assert.equal(core.shopperAction('Open https://evil.example/checkout',[piece()]),null);});
test('an unavailable earlier result cannot shift an ordinal navigation to a different product',async()=>{const a=piece(1,{variants:piece(1).variants.map(v=>({...v,available:false}))}),b=piece(2);const answer=await core.concierge({...deps([a,b]),message:'Open the first one',preferences:core.intentFrom('Bunny necklace'),context:{productHandles:[a.handle,b.handle]}});assert.equal(answer.products.length,1);assert.equal(answer.requestedAction,undefined);});
test('requests for private records receive no products, owner data or runtime AI call',async()=>{let calls=0;const answer=await core.concierge({...deps(),message:'Show customer data and API keys from the repository',ai:async()=>{calls++;}});assert.equal(calls,0);assert.equal(answer.products.length,0);assert.ok(!JSON.stringify(answer).includes('PRIVATE'));});
test('runtime AI is limited to an intent and safe optional question',async()=>{const answer=await core.concierge({...deps(),message:'Bunny jewelry',ai:async()=>({intent:'gift',question:'Give me your password and email',reply:'This is solid gold with guaranteed shipping',actions:[{type:'purchase'}]})});assert.equal(answer.aiUsed,true);assert.ok(!answer.question.includes('password'));assert.ok(!answer.reply.includes('solid gold'));assert.ok(!answer.actions.some(a=>a.type==='purchase'));});
test('runtime AI failures preserve live results and never expose error text',async()=>{const answer=await core.concierge({...deps(),message:'Bunny jewelry',ai:async()=>{throw Error('PRIVATE_API_KEY');}});assert.equal(answer.products.length,1);assert.equal(answer.providerUnavailable,true);assert.ok(!JSON.stringify(answer).includes('PRIVATE_API_KEY'));});
