'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const Shopify=require('../../brites-shopify-storefront-adapter.js');
const html=fs.readFileSync(require.resolve('../../concierge-sandbox.html'),'utf8'),source=fs.readFileSync(require.resolve('../../concierge-sandbox.js'),'utf8');
const clone=value=>JSON.parse(JSON.stringify(value)),settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
function piece(){
  const variants=[];for(const metal of ['Sterling Silver','14k Solid Gold'])for(const length of ['16 inches','18 inches'])for(const engraving of ['No Engraving','Engraved'])variants.push({id:'gid://shopify/ProductVariant/'+(4501+variants.length),title:[metal,length,engraving].join(' / '),price:50+variants.length*20,available:true,availabilityKnown:true,options:[{name:'Metal Choice',value:metal},{name:'Chain Length',value:length},{name:'Engraving',value:engraving}]});
  return {id:'gid://shopify/Product/450',handle:'fern-necklace',title:'Fern Necklace',type:'Necklace',description:'An exact published fern necklace.',url:'https://britesjewelry.com/products/fern-necklace',currency:'USD',variantsComplete:true,options:[{name:'Metal Choice',values:['Sterling Silver','14k Solid Gold']},{name:'Chain Length',values:['16 inches','18 inches']},{name:'Engraving',values:['No Engraving','Engraved']}],variants};
}
function fixture(t){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',error=>errors.push(error));const dom=new JSDOM(html,{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document,p=piece();let lookup=async()=>p;const requests=[],scrolls=[];
  delete d.body.dataset.catalogueSeed;delete d.body.dataset.inventoryPreload;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=value=>scrolls.push(value);
  w.fetch=async(url,init={})=>{requests.push({url,init});if(url.startsWith('/api/growth/product'))return {ok:true,json:async()=>({live:true,checkedAt:Date.now(),product:clone(await lookup(init))})};if(url.startsWith('/api/growth/catalogue'))return {ok:true,json:async()=>({live:true,checkedAt:Date.now(),products:[clone(p)],pageInfo:{hasNextPage:false,endCursor:null}})};if(url.startsWith('/api/growth/storefront-services'))return {ok:true,json:async()=>({schema:1,guidance:{},conflicts:[],offers:{items:[]}})};throw Error('Unexpected fixture request');};
  w.eval(source);t.after(()=>w.close());return {w,d,p,errors,requests,scrolls,ready:settle,get store(){return w.BritesSandboxStorefront;},lookup:fn=>lookup=fn,cart:()=>JSON.parse(w.sessionStorage.getItem('brites-sandbox-cart')||'[]'),async add(variant=0,quantity=1,words){assert.equal((await this.store.execute({type:'open',handle:p.handle})).ok,true);assert.equal((await this.store.execute({type:'select-option',handle:p.handle,variantId:p.variants[variant].id})).ok,true);if(words!==undefined)assert.equal((await this.store.execute({type:'set-engraving',handle:p.handle,text:words})).ok,true);assert.equal((await this.store.execute({type:'product-quantity',handle:p.handle,quantity})).ok,true);const result=await this.store.execute({type:'add',handle:p.handle},{requestId:'add-'+this.cart().length});assert.equal(result.ok,true,result.message);return result;}};
}
function bagLine(f,index=0){return f.store.snapshot().bagControls.lines[index];}
function bagRow(f,index=0){return [...f.d.querySelectorAll('[data-bag-line]')][index];}

test('homepage action restores the original intro, all filters, default order and actual top of the page',async t=>{const f=fixture(t);await f.ready();await f.add();await f.store.execute({type:'bag'});const result=await f.store.execute({type:'home'});assert.equal(result.ok,true);assert(f.store.capabilities.actions.includes('home'));assert.equal(result.action,'home');assert.equal(result.snapshot.currentHandle,'');assert.equal(result.snapshot.search,'');assert.equal(result.snapshot.filter,'all');assert.equal(result.snapshot.sort,'featured');assert(f.d.querySelector('.collection-intro'));assert.equal(f.d.querySelector('.product-layout'),null);assert.equal(f.w.location.search,'');assert.deepEqual(clone(f.scrolls.at(-1)),{top:0,behavior:'instant'});assert.equal(f.cart().length,1);assert.deepEqual(f.errors,[]);});

test('exact configured local engraving addition preserves literal wording privately and cannot check out',async t=>{const f=fixture(t);await f.ready();const result=await f.add(5,2,'PRIVATE45 — Forever');assert.equal(f.cart()[0].variantId,f.p.variants[5].id.split('/').pop());assert.equal(f.cart()[0].quantity,2);assert.equal(f.cart()[0].engravingPreview,'PRIVATE45 — Forever');assert.equal(f.cart()[0].customizationPreview,true);assert.doesNotMatch(JSON.stringify(result),/PRIVATE45/);assert.match(result.message,/local preview/i);await f.store.execute({type:'bag'});assert.equal(bagRow(f).querySelector('[data-bag-engraving]').value,'PRIVATE45 — Forever');assert.doesNotMatch(JSON.stringify(f.store.snapshot()),/PRIVATE45/);const checkout=await f.store.execute({type:'checkout'});assert.equal(checkout.ok,false);assert.match(checkout.message,/shop must review customization/i);assert.equal(f.store.snapshot().pageKind,'bag');assert.equal(f.cart()[0].engravingPreview,'PRIVATE45 — Forever');});

test('cart option edit actuates its actual dropdown and preserves exact unrelated lines and quantity',async t=>{const f=fixture(t);await f.ready();await f.add(4,2);await f.add(0,3);await f.store.execute({type:'bag'});const before=f.cart(),ids=f.store.snapshot().bagControls.lines.map(line=>line.lineId),result=await f.store.execute({type:'bag-select-option',lineId:ids[0],optionName:'Chain Length',optionValue:'18 inches'});assert.equal(result.ok,true,result.message);assert.equal(result.cartChanged,true);assert.equal(f.cart()[0].variantId,f.p.variants[6].id.split('/').pop());assert.equal(f.cart()[0].quantity,2);assert.deepEqual(f.cart()[1],before[1]);assert.deepEqual(f.store.snapshot().bagControls.lines.map(line=>line.lineId),ids);assert.equal(bagRow(f).querySelector('[data-bag-option="Chain Length"]').value,'18 inches');assert.equal(bagRow(f).querySelector('[data-bag-option="Metal Choice"]').value,'14k Solid Gold');assert.equal(bagLine(f).subtotal,f.p.variants[6].price*2);assert.equal(bagLine(f).optionGroups.length,3);assert.deepEqual(f.errors,[]);});

test('manual native cart dropdown and quantity controls follow the same fresh exact edit path',async t=>{const f=fixture(t);await f.ready();await f.add(0,2);await f.store.execute({type:'bag'});let row=bagRow(f),select=row.querySelector('[data-bag-option="Metal Choice"]');select.value='14k Solid Gold';select.dispatchEvent(new f.w.Event('change',{bubbles:true}));await settle();assert.equal(f.cart()[0].variantId,f.p.variants[4].id.split('/').pop());row=bagRow(f);const quantity=row.querySelector('.bag-quantity input');quantity.value='4';quantity.dispatchEvent(new f.w.Event('change',{bubbles:true}));await settle();assert.equal(f.cart()[0].quantity,4);assert.equal(bagRow(f).querySelector('.bag-quantity input').value,'4');assert.deepEqual(f.errors,[]);});

test('cart words survive other choices, explicit no engraving clears them, and exact fresh undo restores both',async t=>{const f=fixture(t);await f.ready();await f.add(5,2,'PRIVATE45');await f.add(0,1);await f.store.execute({type:'bag'});const untouched=clone(f.cart()[1]),id=bagLine(f).lineId;assert.equal((await f.store.execute({type:'bag-select-option',lineId:id,optionName:'Chain Length',optionValue:'18 inches'})).ok,true);assert.equal(f.cart()[0].engravingPreview,'PRIVATE45');assert.equal(f.cart()[0].variantId,f.p.variants[7].id.split('/').pop());const clear=await f.store.execute({type:'bag-select-option',lineId:id,optionName:'Engraving',optionValue:'No Engraving'});assert.equal(clear.ok,true,clear.message);assert.match(clear.message,/wording was cleared/);assert.equal(f.cart()[0].engravingPreview,undefined);assert.equal(f.cart()[0].customizationPreview,undefined);assert.equal(bagRow(f).querySelector('[data-bag-engraving]').value,'');const restored=await f.store.execute({type:'undo'});assert.equal(restored.ok,true,restored.message);assert.equal(f.cart()[0].engravingPreview,'PRIVATE45');assert.equal(f.cart()[0].variantId,f.p.variants[7].id.split('/').pop());assert.equal(f.cart()[0].quantity,2);assert.deepEqual(f.cart()[1],untouched);assert.equal(bagRow(f).querySelector('[data-bag-option="Engraving"]').value,'Engraved');assert.doesNotMatch(JSON.stringify(f.store.snapshot()),/PRIVATE45/);});

test('cart engraving field is saved and cleared through actual controls without disclosing text in receipts',async t=>{const f=fixture(t);await f.ready();await f.add(1,2,'ORIGINAL45');await f.store.execute({type:'bag'});const id=bagLine(f).lineId,result=await f.store.execute({type:'bag-set-engraving',lineId:id,text:'PRIVATE45 replacement'});assert.equal(result.ok,true,result.message);assert.doesNotMatch(JSON.stringify(result),/PRIVATE45|ORIGINAL45/);assert.equal(bagRow(f).querySelector('[data-bag-engraving]').value,'PRIVATE45 replacement');let field=bagRow(f).querySelector('[data-bag-engraving]');field.value='SECOND_PRIVATE45';[...bagRow(f).querySelectorAll('button')].find(button=>button.textContent==='Save engraving preview').click();await settle();assert.equal(f.cart()[0].engravingPreview,'SECOND_PRIVATE45');[...bagRow(f).querySelectorAll('button')].find(button=>button.textContent==='Clear engraving preview').click();await settle();assert.equal(f.cart()[0].engravingPreview,undefined);assert.equal(bagRow(f).querySelector('[data-bag-engraving]').value,'');assert.deepEqual(f.errors,[]);});

for(const [label,change] of [['old price changed',p=>p.variants[0].price++],['old literal options changed',p=>p.variants[0].options[1].value='17 inches'],['new exact option unavailable',p=>p.variants[2].available=false],['new exact option price changed',p=>p.variants[2].price+=19],['new exact option title changed',p=>p.variants[2].title+=' changed'],['new exact option identity changed',p=>p.variants[2].id='gid://shopify/ProductVariant/99999'],['incomplete variant list',p=>p.variantsComplete=false],['product held',p=>p.cartHold=true],['wrong product identity',p=>p.id='gid://shopify/Product/999']])test('fresh cart edit refuses '+label+' and preserves every saved line',async t=>{const f=fixture(t);await f.ready();await f.add(0,2);await f.add(4,3);await f.store.execute({type:'bag'});const before=f.cart(),id=bagLine(f).lineId,changed=clone(f.p);change(changed);f.lookup(async()=>changed);const result=await f.store.execute({type:'bag-select-option',lineId:id,optionName:'Chain Length',optionValue:'18 inches'});assert.equal(result.ok,false);assert.deepEqual(f.cart(),before);assert.equal(bagRow(f).querySelector('[data-bag-option="Chain Length"]').value,'16 inches');});

test('cancelled or superseded fresh cart edits preserve the newer actual bag choices',async t=>{const f=fixture(t);await f.ready();await f.add(0,2);await f.store.execute({type:'bag'});const before=f.cart(),id=bagLine(f).lineId,c=new AbortController();let release;f.lookup(()=>new Promise(resolve=>release=()=>resolve(f.p)));const older=f.store.execute({type:'bag-select-option',lineId:id,optionName:'Chain Length',optionValue:'18 inches'},{signal:c.signal});await settle();c.abort();release();assert.equal((await older).ok,false);assert.deepEqual(f.cart(),before);f.lookup(async()=>f.p);assert.equal((await f.store.execute({type:'bag-select-option',lineId:id,optionName:'Chain Length',optionValue:'18 inches'})).ok,true);assert.equal(f.cart()[0].variantId,f.p.variants[2].id.split('/').pop());});

test('unsupported custom upload pieces remain held and never enter the local engraving preview bag',async t=>{const f=fixture(t);await f.ready();f.p.title='Handwriting Photo Upload Necklace';await f.store.execute({type:'open',handle:f.p.handle});await f.store.execute({type:'select-option',handle:f.p.handle,variantId:f.p.variants[1].id});assert.equal(f.store.snapshot().productControls.selectionStatus,'held');const result=await f.store.execute({type:'add',handle:f.p.handle});assert.equal(result.ok,false);assert.deepEqual(f.cart(),[]);});

for(const base of ['/','/en-ca/'])test('production homepage navigation stays at its validated locale root '+base,async t=>{const dom=new JSDOM('<main id="MainContent"></main>',{url:'https://britesjewelry.com'+base+'products/fern-necklace'}),nav=[],adapter=Shopify.create({window:dom.window,document:dom.window.document,location:dom.window.location,root:base,theme:'brites-v1',fetch:async()=>{throw Error('Navigation must not read or submit cart');},navigate:url=>nav.push(url)});t.after(()=>{adapter.destroy();dom.window.close();});assert(adapter.capabilities.actions.includes('home'));const result=await adapter.execute({type:'home'},{requestId:'home45'});assert.equal(result.ok,true,result.reason);assert.equal(result.navigationRequested,true);assert.deepEqual(nav,['https://britesjewelry.com'+base]);assert.equal((await adapter.execute({type:'home',url:'https://evil.example'},{requestId:'injected45'})).ok,false);assert.equal(nav.length,1);});
