'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),bridge=require('../../brites-storefront-bridge.js');
const clone=value=>JSON.parse(JSON.stringify(value));
function page50(kind='bag'){return {controlVersion:1,contextRevision:50,discoveryRevision:1,pageKind:kind,currentHandle:kind==='product'?'fern-necklace':'',visiblePieces:[{id:'gid://shopify/Product/500',handle:'fern-necklace',title:'Fern Necklace'}],catalogueControls:{moreAvailable:true,moreEnabled:true,visibleCount:24,loadedCount:30,hasNextPage:true},storyControls:{handle:'fern-necklace',available:true,enabled:true,loaded:false},bagDiscountControls:{available:true,enabled:true,maxLength:80,hasText:false,stagedKnown:false},bagTermsControls:{available:true,enabled:true,accepted:false,termsAvailable:true},productControls:kind==='product'?{handle:'fern-necklace',productId:'gid://shopify/Product/500',variantId:'gid://shopify/ProductVariant/5001',quantity:2,optionGroups:[{name:'Metal',values:['Silver']}],selectedOptions:[{name:'Metal',value:'Silver'}],reviewReady:true,selectedVariant:{id:'gid://shopify/ProductVariant/5001',title:'Silver',price:40,currency:'USD',available:true,options:[{name:'Metal',value:'Silver'}]}}:null};}
function harness50(kind='bag',actions=['catalogue-more','story-open','cancel-review','bag-discount','bag-terms','review-add']){let page=page50(kind);const calls=[],host={snapshot:()=>clone(page),capabilities:{controlVersion:1,mode:kind==='bag'?'shopify':'sandbox',actions,notesMode:'native-form'},execute:async action=>{calls.push(clone(action));page.contextRevision++;return {ok:true,message:'Current visible control confirmed.',snapshot:page};}};return {api:bridge.create({storefront:host}),calls,get page(){return page;},set:value=>{page=clone(value);}};}

test('remaining mounted control phrases resolve only against their actual scoped public fields',()=>{assert.deepEqual(bridge.resolve('Explore more pieces',page50('collection')).action,{type:'catalogue-more'});assert.deepEqual(bridge.resolve('Open its reviewed story',page50('product')).action,{type:'story-open',handle:'fern-necklace'});assert.deepEqual(bridge.resolve('Cancel this review',page50('product')).action,{type:'cancel-review'});assert.deepEqual(bridge.resolve('Apply discount code Mixed_50',page50()).action,{type:'bag-discount',text:'Mixed_50'});assert.deepEqual(bridge.resolve('I accept the cart terms',page50()).action,{type:'bag-terms',accepted:true});assert.deepEqual(bridge.resolve('Uncheck cart terms',page50()).action,{type:'bag-terms',accepted:false});});

test('terms acceptance cannot be inferred from a model argument quote negation hypothetical or plan',async()=>{const f=harness50();for(const text of ['Agree to cart terms','Accept terms for me','The customer agrees to cart terms','"I agree to the cart terms"','I do not agree to the cart terms','If I agree to the cart terms, what happens?','I agree to the cart terms then checkout']){const result=await f.api.execute({type:'bag-terms',accepted:true},{source:'typed',transcript:text,context:f.page,requestId:text});assert.equal(result.ok,false,text);}assert.equal((await f.api.execute({type:'bag-terms',accepted:true},{source:'model',transcript:'I agree to the cart terms',context:f.page})).ok,false);assert.deepEqual(f.calls,[]);assert.equal(bridge.resolvePlan('I agree to the cart terms then open checkout',page50()).ok,false);});

test('current explicit terms choice is exact and mismatched accepted value or stale visible terms is denied',async()=>{const f=harness50(),yes=f.api.resolve('I agree to the cart terms');assert.equal((await f.api.execute({...yes.action,accepted:false},{transcript:'I agree to the cart terms',context:f.page,source:'typed'})).ok,false);const before=clone(f.page),request=f.api.resolve('I agree to the cart terms');f.set({...before,contextRevision:51,bagTermsControls:{...before.bagTermsControls,enabled:false}});assert.equal((await f.api.execute(request.action)).ok,false);assert.deepEqual(f.calls,[]);const g=harness50(),accepted=g.api.resolve('I accept cart terms');assert.equal((await g.api.execute(accepted.action)).ok,true);assert.deepEqual(g.calls,[{type:'bag-terms',accepted:true}]);});

test('literal discount code is bounded private and cannot borrow unsupported capabilities or accept an action suffix',async()=>{const f=harness50();for(const text of ['Apply discount code SAVE50 then checkout','Apply discount code <script>','Apply discount code '+('A'.repeat(81))])assert.notEqual(bridge.resolve(text,f.page).action?.type,'bag-discount',text);assert.doesNotMatch(bridge.redactRequestText('Apply discount code PRIVATE50'),/PRIVATE50/);const request=f.api.resolve('Apply discount code Case-50'),result=await f.api.execute(request.action);assert.equal(result.ok,true);assert.match(result.reply,/staged for checkout/);assert.match(result.reply,/not verified/);assert.doesNotMatch(JSON.stringify(result),/Case-50/);assert.deepEqual(f.calls,[{type:'bag-discount',text:'Case-50'}]);const absent=harness50('bag',[]),blocked=absent.api.resolve('Apply discount code TEST50');assert.equal((await absent.api.execute(blocked.action)).ok,false);assert.deepEqual(absent.calls,[]);});

test('story continuation and cancellation fail closed for unavailable fields foreign handles and stale cursors',async()=>{const more=page50('collection');more.catalogueControls.moreEnabled=false;assert.equal(bridge.resolve('Explore more pieces',more).ok,false);const story=page50('product');story.storyControls.handle='foreign';assert.equal(bridge.resolve('Open its reviewed story',story).ok,false);story.productControls.reviewReady=false;assert.equal(bridge.resolve('Cancel this review',story).ok,false);const f=harness50('collection'),request=f.api.resolve('Explore more pieces');f.set({...f.page,catalogueControls:{...f.page.catalogueControls,hasNextPage:false,moreAvailable:false}});assert.equal((await f.api.execute(request.action)).ok,false);assert.deepEqual(f.calls,[]);});

test('the actual Review before adding button wording preserves full current selection guards',()=>{const page=page50('product'),result=bridge.resolve('Review before adding',page);assert.equal(result.ok,true,result.reason);assert.deepEqual(result.action,{type:'review-add',handle:'fern-necklace',variantId:'gid://shopify/ProductVariant/5001'});page.productControls.selectedOptions=[];assert.equal(bridge.resolve('Review before adding',page).ok,false);});

test('explicit negative cart consent is handled locally while private note words remain opaque',()=>{const page=page50();for(const text of ['Do not accept the cart terms.','Do not agree to the cart terms.',"Don't accept cart terms.","Don't agree to the cart terms."]){const result=bridge.resolve(text,page);assert.equal(result.ok,false,text);assert.equal(result.handled,true,text);assert.equal(result.recognized,true,text);assert.equal(result.action,undefined,text);assert.match(result.reason,/leave the website/i);}page.bagNoteControls={available:true,enabled:true,maxLength:300,hasText:false,savedKnown:true};const literal=bridge.resolve('Write cart note: Do not accept the cart terms.',page);assert.equal(literal.ok,true,literal.reason);assert.deepEqual(literal.action,{type:'bag-note',text:'Do not accept the cart terms.'});});
