'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture,publishedProduct,settle}=require('./native-continuity48-fixture.cjs');
const savedSession=f=>Object.fromEntries(Array.from({length:f.w.sessionStorage.length},(_,i)=>{const key=f.w.sessionStorage.key(i);return [key,f.w.sessionStorage.getItem(key)];}));
function catalogue(){const rows=Array.from({length:120},(_,i)=>publishedProduct(i));const p=rows[10];p.options=[{name:'Metal Choice',values:['Sterling Silver','14k Solid Gold']},{name:'Length',values:['16 inches','18 inches']}];p.variants=p.options[0].values.flatMap((metal,i)=>p.options[1].values.map((length,j)=>({id:'gid://shopify/ProductVariant/'+(480000+i*10+j),numericId:String(480000+i*10+j),title:metal+' / '+length,price:100+i*200+j*5,available:true,options:[{name:'Metal Choice',value:metal},{name:'Length',value:length}]})));return rows;}
test('native short answer selects the real touched option group without guessing another menu',async t=>{
 const f=await fixture(t,{customProducts:catalogue()});await f.store.execute({type:'open',handle:f.products[10].handle});await f.store.execute({type:'options',handle:f.products[10].handle});
 const button=[...f.d.querySelectorAll('[data-option-name="Length"] button')].find(b=>b.textContent==='16 inches');button.dispatchEvent(new f.w.Event('pointerdown',{bubbles:true}));
 await f.say('16 inches, please');assert.equal(f.choices().Length,'16 inches');assert.equal(f.choices()['Metal Choice'],undefined);assert.match(f.lastSpoken(),/16/);f.assertNativeOnly();
});
test('native pointing survives moving into concierge but expires when pointing elsewhere',async t=>{
 const f=await fixture(t);const card=f.d.querySelector('[data-product-handle="cat-stud-earrings"]');card.dispatchEvent(new f.w.MouseEvent('pointerover',{bubbles:true}));card.dispatchEvent(new f.w.MouseEvent('pointerout',{bubbles:true,relatedTarget:f.root.host}));f.root.host.dispatchEvent(new f.w.Event('focusin',{bubbles:true}));await new Promise(r=>f.w.setTimeout(r,130));
 await f.say('Open the piece I am pointing at');assert.equal(f.store.snapshot().currentHandle,'cat-stud-earrings');f.assertNativeOnly();
});
test('native restart receives older conversation and current page without a second greeting',async t=>{
 const f=await fixture(t,{greetingEnabled:true});const end=[...f.root.querySelectorAll('button')].find(b=>b.textContent==='End voice');end.click();await settle();
 for(let i=0;i<12;i++){await f.store.execute({type:'open',handle:f.products[i].handle});await settle();}
 [...f.root.querySelectorAll('button')].find(b=>b.textContent==='Talk to me').click();await settle();
 const greetings=f.responses().filter(p=>/Greet the shopper/.test(p.response.instructions||''));assert.equal(greetings.length,1);
 const memory=f.packets.filter(p=>p.item?.content?.[0]?.text?.startsWith('Historical same-tab'));assert.ok(memory.length);assert.match(memory.at(-1).item.content[0].text,/cat-stud-earrings/);
 const page=f.packets.filter(p=>p.item?.content?.[0]?.text?.startsWith('Public website UI'));assert.match(page.at(-1).item.content[0].text,new RegExp(f.products[11].handle));f.assertNativeOnly();
});
test('closing and reopening does not repeat the visual greeting',async t=>{const f=await fixture(t);f.w.BritesConcierge.close();await settle();f.w.BritesConcierge.open({focus:false});await settle();assert.equal(f.greetings.length,1);});
test('native dropdown phrasing sets length and metal, then quantity and an exact checked bag addition',async t=>{
 const f=await fixture(t,{customProducts:catalogue()});await f.say('Open Elephant Necklace');await f.say('Open the Length menu');await f.say('Select 16 inches from this dropdown');assert.equal(f.choices().Length,'16 inches');await f.say('Open the Metal Choice menu');await f.say('14k Solid Gold, please');assert.equal(f.choices()['Metal Choice'],'14k Solid Gold');await f.say('Set quantity to 2');await f.say('Add this piece to my bag');assert.equal(f.cart().length,1);assert.equal(f.cart()[0].quantity,2);assert.match(f.cart()[0].variant,/14k Solid Gold.*16 inches/);assert.equal(f.client.state,'thinking');f.assertNativeOnly();
});
test('native touched quantity accepts a short number and refuses an out of range number',async t=>{const f=await fixture(t);await f.store.execute({type:'open',handle:f.products[10].handle});const field=f.d.querySelector('input[aria-label="Quantity of this exact piece"]');field.dispatchEvent(new f.w.Event('pointerdown',{bubbles:true}));await f.say('two');assert.equal(f.store.snapshot().productControls.quantity,2);await f.say('21');assert.equal(f.store.snapshot().productControls.quantity,2);f.assertNativeOnly();});
test('native touch topic and SPA navigation stay connected and avoid per-pointer API work',async t=>{const f=await fixture(t);const before=f.requests.length,start=f.packets.length;const card=f.d.querySelector('[data-product-handle="cat-stud-earrings"]');for(let i=0;i<30;i++)card.dispatchEvent(new f.w.Event('pointerdown',{bubbles:true}));await settle();assert.equal(f.requests.length,before);assert.equal(f.packets.length,start);await f.say('Open this piece');assert.equal(f.store.snapshot().currentHandle,'cat-stud-earrings');assert.notEqual(f.client.state,'idle');await f.say('Go to the homepage');assert.notEqual(f.client.state,'idle');f.assertNativeOnly();});
test('a same-tab reload restores earlier preferences past 16 messages and initial current page grounding',async t=>{
 const history=[{role:'user',content:'A butterfly gift for my mother, for her graduation.'},{role:'assistant',content:'Let’s look for a butterfly.'},...Array.from({length:24},(_,i)=>({role:i%2?'assistant':'user',content:'Ordinary chat '+i}))];
 const savedSession={'brites-concierge-v1':JSON.stringify({updatedAt:Date.now(),history:history.slice(-16),open:true}), 'brites-concierge-v1-memory':JSON.stringify({schema:1,transcript:history,highlights:[history[0]],journey:[{pageKind:'product',handle:'butterfly-stud-earrings',search:''}],greeted:true,voiceGreeted:true})};
 const f=await fixture(t,{savedSession,query:'?product=cat-stud-earrings',greetingEnabled:true});const packets=f.packets.filter(p=>p.item?.content?.[0]?.text?.startsWith('Historical same-tab'));assert.match(packets[0].item.content[0].text,/mother.*graduation/);assert.equal(f.responses().filter(p=>/Greet/.test(p.response.instructions||'')).length,0);const page=f.packets.find(p=>p.item?.content?.[0]?.text?.startsWith('Public website UI'));assert.match(page.item.content[0].text,/cat-stud-earrings/);f.assertNativeOnly();
});
test('private engraving text remains absent from archived memory and provider restart packets',async t=>{const f=await fixture(t);await f.say('Set engraving wording to PRIVATE WORDS48 then open the cart');const held=JSON.stringify(Object.fromEntries(Array.from({length:f.w.sessionStorage.length},(_,i)=>{const k=f.w.sessionStorage.key(i);return [k,f.w.sessionStorage.getItem(k)];})));assert.doesNotMatch(held,/PRIVATE WORDS48/);const end=[...f.root.querySelectorAll('button')].find(b=>b.textContent==='End voice');end.click();await settle();[...f.root.querySelectorAll('button')].find(b=>b.textContent==='Talk to me').click();await settle();const text=f.packets.filter(p=>p.item?.content?.[0]?.text?.startsWith('Historical same-tab')).map(p=>p.item.content[0].text).join('');assert.doesNotMatch(text,/PRIVATE WORDS48/);f.assertNativeOnly();});
test('same-tab page reload preserves actual exact product choices and quantity through fresh product reads',async t=>{const a=await fixture(t,{customProducts:catalogue()});await a.say('Open Elephant Necklace');await a.say('Select 14k Solid Gold');await a.say('Select 16 inches');await a.say('Set quantity to 2');const b=await fixture(t,{customProducts:catalogue(),query:'?product=elephant-necklace',savedSession:savedSession(a)});assert.deepEqual(b.choices(),{'Metal Choice':'14k Solid Gold',Length:'16 inches'});assert.equal(b.store.snapshot().productControls.quantity,2);assert.equal(b.cart().length,0);b.assertNativeOnly();});
test('same-tab page reload preserves the shown animal search and continues with unseen matches',async t=>{const a=await fixture(t);await a.say('Show a short list of animal listings');const first=a.store.snapshot().visiblePieces.map(p=>p.handle);const b=await fixture(t,{savedSession:savedSession(a)});assert.equal(b.store.snapshot().search,'animal');assert.deepEqual(JSON.parse(JSON.stringify(b.store.snapshot().visiblePieces.map(p=>p.handle))),JSON.parse(JSON.stringify(first)));await b.say('Show more');const next=b.store.snapshot().visiblePieces.map(p=>p.handle);assert.equal(next.length,6);assert.ok(next.every(handle=>!first.includes(handle)));b.assertNativeOnly();});
test('native deictic follow-up uses the touched menu and section rather than an unrelated product',async t=>{const f=await fixture(t,{customProducts:catalogue()});await f.say('Open Elephant Necklace');await f.store.execute({type:'options',handle:'elephant-necklace',optionName:'Length'});const row=f.d.querySelector('[data-option-name="Length"]');row.dispatchEvent(new f.w.Event('pointerdown',{bubbles:true}));await f.say('Set that to 16 inches');assert.equal(f.choices().Length,'16 inches');f.d.querySelector('[data-store-section=description]').dispatchEvent(new f.w.Event('pointerdown',{bubbles:true}));await f.say('Go to this section');assert.equal(f.controls.at(-1).action.section,'description');assert.equal(f.store.snapshot().currentHandle,'elephant-necklace');f.assertNativeOnly();});
for(const permissionState of ['granted','prompt','denied'])test('same-tab voice resumes only with existing microphone permission: '+permissionState,async t=>{const history=[{role:'user',content:'We are looking at an animal necklace.'}],session={'brites-concierge-v1':JSON.stringify({updatedAt:Date.now(),history,open:true}),'brites-concierge-v1-voice-resume':String(Date.now())};const f=await fixture(t,{autoResume:true,permissionState,savedSession:session});assert.equal(f.microphoneCalls,permissionState==='granted'?1:0);assert.equal(f.requests.filter(r=>r.body?.action==='start').length,permissionState==='granted'?1:0);assert.equal(f.responses().filter(p=>/Greet/.test(p.response.instructions||'')).length,0);f.assertNativeOnly();});
test('native compound literal necklace choice does not borrow the similarly named charm-only metal',async t=>{const rows=catalogue(),p=rows[10],metals=['Sterling Silver','14k Gold Filled','10k Solid Gold','14k Solid Gold'],charmMetals=metals.map(m=>m+'-Charm Only');p.options=[{name:'Metal Choice',values:metals.concat(charmMetals)},{name:'Engraving',values:['No','Yes']},{name:'Chain Length',values:['14"','16"','18"','Charm Only-No Chain']}];let serial=0;p.variants=metals.concat(charmMetals).flatMap(metal=>(metal.includes('Charm Only')?['Charm Only-No Chain']:['14"','16"','18"']).flatMap(length=>['No','Yes'].map(engraving=>{const id=481000+(++serial);return {id:'gid://shopify/ProductVariant/'+id,numericId:String(id),title:[metal,engraving,length].join(' / '),available:true,price:100+serial,options:[{name:'Metal Choice',value:metal},{name:'Engraving',value:engraving},{name:'Chain Length',value:length}]};})));assert.equal(p.variants.length,32);const f=await fixture(t,{customProducts:rows});await f.say('Open Elephant Necklace');await f.say('Select 14k solid gold with 16 inches');assert.equal(f.choices()['Metal Choice'],'14k Solid Gold');assert.equal(f.choices()['Chain Length'],'16"');assert.equal(f.choices().Engraving,undefined);await f.say('Without engraving');await f.say('Add this piece to my bag');assert.equal(f.cart().length,1);assert.match(f.cart()[0].variant,/^14k Solid Gold \/ No \/ 16"$/);f.assertNativeOnly();});
test('native short spoken number uses a uniquely matching published inch length in the actual open menu',async t=>{const f=await fixture(t,{customProducts:catalogue()});await f.say('Open Elephant Necklace');await f.say('Open the Length menu');await f.say('sixteen');assert.equal(f.choices().Length,'16 inches');f.assertNativeOnly();});
test('restored oversized local transcripts are trimmed once to the same archive byte budget',async t=>{const transcript=Array.from({length:160},(_,i)=>({role:i%2?'assistant':'user',content:'語'.repeat(3750)}));const f=await fixture(t,{savedSession:{'brites-concierge-v1-memory':JSON.stringify({schema:1,transcript,journey:[],highlights:[]})}});const held=JSON.parse(f.w.sessionStorage.getItem('brites-concierge-v1-memory'));assert.ok(Buffer.byteLength(JSON.stringify(held.transcript))<=262144);assert.ok(held.transcript.length>16);f.assertNativeOnly();});
test('native current choices question survives restart and never becomes product discovery',async t=>{const a=await fixture(t,{customProducts:catalogue()});await a.say('Open Elephant Necklace');await a.say('Select 14k Solid Gold then select 16 inches then set quantity to 2');const f=await fixture(t,{customProducts:catalogue(),query:'?product=elephant-necklace',savedSession:savedSession(a)});const before=f.requests.length,controls=f.controls.length;await f.say('What have I selected?');assert.match(f.lastSpoken(),/14k Solid Gold/);assert.match(f.lastSpoken(),/16 inches/);assert.match(f.lastSpoken(),/Quantity 2/);assert.ok(f.lastSpoken().split(/\s+/).length<=30);assert.equal(f.requests.length,before);assert.equal(f.controls.length,controls);assert.equal(f.cart().length,0);f.assertNativeOnly();});
test('native current choices question reports partial choices and short confirmations without reading private fields',async t=>{const f=await fixture(t,{customProducts:catalogue()});await f.say('Open Elephant Necklace');await f.say('Open the Length menu');assert.equal(f.lastSpoken(),'The Length menu is open.');await f.say('sixteen');assert.equal(f.lastSpoken(),'Selected 16 inches. Next, choose Metal Choice.');const before=f.requests.length;await f.say('Which options have I chosen?');assert.match(f.lastSpoken(),/Length: 16 inches/);assert.doesNotMatch(f.lastSpoken(),/Sterling|Solid Gold|PRIVATE/);await f.say('What quantity have I selected?');assert.equal(f.lastSpoken(),'Quantity 1.');assert.equal(f.requests.length,before);assert.equal(f.cart().length,0);f.assertNativeOnly();});
test('native focused exact selector survives pointer transit into the concierge, while a deliberate outside focus clears it',async t=>{const f=await fixture(t,{customProducts:catalogue()});await f.say('Open Elephant Necklace');const picker=f.d.querySelector('#piece-variant');picker.focus();f.d.body.dispatchEvent(new f.w.MouseEvent('pointerover',{bubbles:true}));[...f.root.querySelectorAll('button')].find(button=>button.textContent==='End voice').focus();f.d.body.dispatchEvent(new f.w.MouseEvent('pointerover',{bubbles:true}));f.root.host.dispatchEvent(new f.w.MouseEvent('pointerover',{bubbles:true}));f.root.host.dispatchEvent(new f.w.Event('focusin',{bubbles:true}));await f.say('Sterling Silver');assert.equal(f.choices()['Metal Choice'],'Sterling Silver');assert.match(f.lastSpoken(),/Selected Sterling Silver/);await f.store.execute({type:'close-options',handle:'elephant-necklace'});f.d.querySelector('#guide-request').focus();assert.equal(f.store.snapshot().productControls.variantPickerFocused===true,false);const before=f.controls.length;await f.say('14k Solid Gold');assert.equal(f.controls.length,before);assert.equal(f.choices()['Metal Choice'],'Sterling Silver');f.assertNativeOnly();});
