'use strict';
// Actual client, bridge and sandbox host; public responses/native callbacks are
// synthetic. No microphone, provider, paid inference or real cart is used.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const Voice=require('../../brites-concierge-voice.js'),Actions=require('../../brites-concierge-voice-actions.js'),Widget=require('../../brites-concierge.js');
const source=Object.fromEntries(['concierge-sandbox.html','concierge-sandbox.js','brites-storefront-bridge.js','brites-concierge.js'].map(name=>[name,fs.readFileSync(require.resolve('../../'+name),'utf8')]));
const clone=value=>JSON.parse(JSON.stringify(value)),settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
const categories=['regular-necklaces','beady-necklaces','stud-earrings','hoop-earrings','charm-only'];
function piece(n,category='beady-necklaces',title){
  const noun={'regular-necklaces':'Necklace','beady-necklaces':'Beady Necklace','stud-earrings':'Stud Earrings','hoop-earrings':'Hoop Earrings','charm-only':'Charm'}[category],options=[{name:'Metal Choice',values:['Sterling Silver','Gold Filled']},{name:'Chain Length',values:['16 inches','18 inches']}],id=38000+n;
  return {id:'gid://shopify/Product/'+id,handle:'understanding-'+n,title:title||'Piece '+n+' '+noun,type:category==='charm-only'?'Charm':category.includes('necklaces')?'Necklace':'Earrings',description:'Published sterling silver and gold filled choices. Each exact option has its own listed price.',currency:'USD',url:'https://britesjewelry.com/products/understanding-'+n,image:'https://cdn.shopify.com/understanding-'+n+'.jpg',images:[{url:'https://cdn.shopify.com/understanding-'+n+'.jpg',altText:'Front view'}],minPrice:50,partsOnly:category==='charm-only',storeCategories:[category],options,variantsComplete:true,privateNotes:'PRIVATE_INVENTORY_NOTE',variants:options[0].values.flatMap((metal,m)=>options[1].values.map((length,l)=>({id:'gid://shopify/ProductVariant/'+(id*10+m*2+l+1),numericId:String(id*10+m*2+l+1),title:metal+' / '+length,price:50+m*20+l*5,available:true,options:[{name:'Metal Choice',value:metal},{name:'Chain Length',value:length}],properties:{_private:'PRIVATE_VARIANT_PROPERTY'}})))};
}
function catalogue(){let n=0;const products=categories.flatMap((category,g)=>Array.from({length:[28,28,27,10,27][g]},()=>piece(++n,category)));products[28].title='Strawberry Beady Necklace';products[119].title='Moon Orbit Charm';return products;}
async function fixture(t,options={}){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));const dom=new JSDOM(source['concierge-sandbox.html'],{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document,products=clone(options.products||catalogue());let config,turn=0;
  const checkedAt=options.checkedAt||Date.now(),calls={requests:[],starts:0,contexts:[]};w.matchMedia=()=>({matches:false,addEventListener(){}});w.HTMLElement.prototype.scrollIntoView=function(){};
  w.fetch=async(raw,init={})=>{const url=new URL(raw,w.location.href),body=init.body?JSON.parse(init.body):null;calls.requests.push({url,body,method:init.method||'GET'});let data;
    if(url.pathname==='/api/growth/inventory'){const offset=Number(url.searchParams.get('offset')||0),rows=clone(products.slice(offset,offset+24)).map(p=>{delete p.minPrice;p.checkedAt=checkedAt;p.detailState=p.variants.some(v=>v.availabilityKnown===false)?'unconfirmed':'checked';return p;});data={live:true,checkedAt,products:rows,inventory:{schema:1,total:products.length,offset},pageInfo:{hasNextPage:offset+24<products.length,nextOffset:offset+24<products.length?offset+24:null}};}
    else if(url.pathname==='/api/growth/catalogue'){const categoryCounts=Object.fromEntries(categories.map(c=>[c,products.filter(p=>p.storeCategories.includes(c)).length])),unfilledCategories=categories.filter(c=>!categoryCounts[c]);data={live:true,checkedAt,products:clone(products),seed:{schema:1,target:120,minimum:100,loaded:products.length,complete:products.length>=100&&!unfilledCategories.length,partial:false,sourcePages:2,categoryCounts,unfilledCategories},pageInfo:{hasNextPage:false,endCursor:null}};}
    else if(url.pathname==='/api/growth/product'){const p=products.find(p=>p.handle===url.searchParams.get('handle'));data={live:true,product:clone(p),checkedAt:Date.now()};}
    else if(url.pathname==='/api/growth/storefront-services')data={schema:1,guidance:{},conflicts:[],offers:{items:[],status:'published_not_checkout_validated'}};
    else if(url.pathname==='/api/concierge-voice')data={enabled:true,nativeAudio:true,publicDemo:true};
    else if(url.pathname==='/api/growth/events')data={ok:true};
    else if(url.pathname==='/api/concierge')data=options.answer||{live:true,reply:'Synthetic checked fallback.',preferences:{},products:[],meanings:[],preserveSelection:true};
    else throw Error('Unexpected synthetic route '+url.pathname);
    return {ok:true,json:async()=>clone(data)};
  };
  w.BritesConciergeAvatar={create(){return {setState(){},setEmotion(){},setVisible(){},setPaused(){},triggerGreeting(){},clearFocus(){},focusProduct(){},clearProduct(){},setLevel(){},setSpeechSignal(){},showProduct(){},cancelPerformance(){},setFloating(){},cue(){},destroy(){}};}};
  w.BritesConciergeVoiceActions=Actions;w.BritesConciergeVoice={...Voice,create(value){config=value;return {state:'listening',outputMeterState:'ready',playbackBlocked:false,start:async()=>{calls.starts++;return true;},stop:async()=>{},dispose:async()=>{},updateContext:v=>calls.contexts.push(clone(v))};}};
  w.eval(source['brites-storefront-bridge.js']);w.eval(source['concierge-sandbox.js']);await w.BritesSandboxStorefront.preloadInventory();await settle();
  if(options.restored)w.sessionStorage.setItem('brites-concierge-v1',JSON.stringify({updatedAt:Date.now(),history:[],products:options.restored,preferences:{},selectedVariants:{}}));
  const script=d.createElement('script');script.src='/brites-concierge.js';script.dataset.sandbox='true';Object.defineProperty(d,'currentScript',{get:()=>script});w.eval(source['brites-concierge.js']);const root=d.querySelector('brites-concierge').shadowRoot;
  const send=text=>w.BritesConcierge.sendShopperCommand(text),button=label=>[...root.querySelectorAll('button')].find(b=>b.textContent.trim()===label||b.getAttribute('aria-label')===label);
  async function activate(){w.BritesConcierge.open();button('Talk to me').click();await settle();root.querySelector('script[src$="brites-concierge-voice.js"]')?.dispatchEvent(new w.Event('load'));await settle();assert.equal(calls.starts,1);}
  function speak(text){const itemId='understanding38-'+(++turn);config.onSpeechStarted({itemId,turnVersion:turn});config.onTranscript({role:'user',itemId,turnVersion:turn,currentTurn:true,text,final:true});return {inputItemId:itemId,turnVersion:turn,currentTurn:true,responseId:'understanding38-response-'+turn};}
  t.after(()=>{w.BritesConcierge.close();w.close();});return {w,d,root,products,calls,errors,checkedAt,send,activate,speak,context:()=>config.getContext(),tool:(name,args,context)=>config.onTool(args,{name,...context}),get store(){return w.BritesSandboxStorefront;},cart:()=>JSON.parse(w.sessionStorage.getItem('brites-sandbox-cart')||'[]')};
}
const productReads=h=>h.calls.requests.filter(r=>r.url.pathname==='/api/growth/product').length,turnReads=h=>h.calls.requests.filter(r=>r.url.pathname==='/api/concierge'&&r.body?.message).length;
async function selectCurrent(h,p){assert.equal((await h.send('Open '+p.title)).ok,true);assert.equal((await h.send('Select Gold Filled')).ok,true);assert.equal((await h.send('Select 18 inches')).ok,true);assert.equal((await h.send('Set quantity to two')).ok,true);}

test('exact inventory rows without legacy minPrice become safe checked product facts',()=>{const p=piece(1);delete p.minPrice;const result=Widget.checkedProductFacts(p,p,Date.now());assert.equal(result.product.minPrice,50);assert.equal(result.product.variants.length,4);assert.deepEqual(result.product.storeCategories,['beady-necklaces']);assert.doesNotMatch(JSON.stringify(result),/PRIVATE_/);});
for(const [name,patch] of [['identity mismatch',p=>p.id='gid://shopify/Product/999'],['negative price',p=>p.variants[0].price=-1],['unknown stock marked available',p=>p.variants[0].availabilityKnown=false],['duplicate variant',p=>p.variants[1]=clone(p.variants[0])],['foreign URL',p=>p.url='https://example.com/products/'+p.handle]])test('checked fact projection rejects '+name,()=>{const identity=piece(1),p=clone(identity);patch(p);assert.equal(Widget.checkedProductFacts(p,identity,Date.now()),null);});
test('future provenance cannot become checked product evidence',()=>{const p=piece(1);assert.equal(Widget.checkedProductFacts(p,p,Date.now()+120000),null);});

test('the reproduced material-and-price question answers from the actual cached product without a highlight or new HTTP turn',async t=>{const h=await fixture(t),p=h.products[28];assert.equal(h.store.getInventory().length,120);assert.equal(h.store.getInventory()[28].minPrice,undefined,'real inventory projection does not carry legacy minPrice');await selectCurrent(h,p);const before=h.store.snapshot(),reads=productReads(h),turns=turnReads(h),r=await h.send('What materials is this piece available in, and what are its prices?');assert.equal(r.ok,true,r.error);assert.match(r.reply,/Strawberry Beady Necklace/);assert.match(r.reply,/Sterling Silver.*USD 50\.00.*55\.00/);assert.match(r.reply,/Gold Filled.*USD 70\.00.*75\.00/);assert.equal(r.productFacts.selectedVariant.price,75);assert.equal(r.productFacts.quantity,2);assert.equal(r.productFacts.itemTotalPrice,150);assert.equal(r.productFacts.checkedAt,h.checkedAt);assert.equal(r.productFacts.fromCache,true);assert.equal(productReads(h),reads);assert.equal(turnReads(h),turns);assert.deepEqual(clone(h.store.snapshot().productControls),clone(before.productControls));assert.equal(h.d.querySelectorAll('.store-highlight').length,0);assert.deepEqual(h.cart(),[]);assert.doesNotMatch(JSON.stringify(r),/PRIVATE_/);assert.equal(h.errors.length,0);});
test('earlier widget cards never replace current-page facts and selected quantity',async t=>{const old=piece(1,'regular-necklaces','Old Widget Necklace'),h=await fixture(t,{restored:[old]}),p=h.products[28];await selectCurrent(h,p);const r=await h.send('Tell me about the current piece and its prices');assert.equal(r.productFacts.handle,p.handle);assert.match(r.reply,/Strawberry/);assert.doesNotMatch(r.reply,/Old Widget/);assert.equal(r.productFacts.selectedVariant.title,'Gold Filled / 18 inches');assert.equal(r.productFacts.itemTotalPrice,150);});
test('current public voice context contains bounded timestamped page facts and no private inventory columns',async t=>{const h=await fixture(t),p=h.products[28];await selectCurrent(h,p);await h.activate();const full=h.context(),context=Voice.publicContext(full);assert.equal(full.inventoryPieces.length,120);assert.equal(context.currentProduct.handle,p.handle);assert.equal(context.currentProduct.checkedAt,h.checkedAt);assert.equal(context.currentProduct.fromCache,true);assert.equal(context.currentProduct.selectedVariant.price,75);assert.equal(context.currentProduct.itemTotalPrice,150);assert.ok(context.inventoryPieces.length>=100&&context.inventoryPieces.length<=120);if(context.inventoryPieces.length<120)assert.equal(context.inventoryPiecesTruncated,true);assert.doesNotMatch(JSON.stringify(context),/PRIVATE_/);assert.ok(Buffer.byteLength(JSON.stringify(context))<=18000);});
test('named questions can inspect the last inventory record while another actual product stays selected',async t=>{const h=await fixture(t),current=h.products[28],last=h.products[119];await selectCurrent(h,current);const reads=productReads(h),r=await h.send('What materials and prices does '+last.title+' have?');assert.equal(r.ok,true,r.error);assert.equal(r.productFacts.handle,last.handle);assert.equal(r.productFacts.partsOnly,true);assert.equal(r.productFacts.selectedVariant,null);assert.equal(h.store.snapshot().currentHandle,current.handle);assert.equal(h.store.snapshot().productControls.selectedVariant.price,75);assert.equal(productReads(h),reads);});
test('unknown and conflicting product names cannot borrow the open page for an answer',async t=>{const h=await fixture(t),p=h.products[28];await selectCurrent(h,p);for(const question of ['What materials and prices does Hidden Pendant have?','What materials does Hidden '+p.title+' have?','Compare the prices of '+p.title+' and '+h.products[119].title]){const r=await h.send(question);assert.equal(r.ok,false,question);assert.equal(r.productFacts,undefined);assert.equal(h.store.snapshot().currentHandle,p.handle);}assert.deepEqual(h.cart(),[]);});
test('native inspection of a named offscreen inventory product reads cache rather than requiring a widget card or network',async t=>{const h=await fixture(t),p=h.products[119];await h.activate();const reads=productReads(h),r=await h.tool('inspect_jewellery',{handle:p.handle},h.speak('What materials and prices does '+p.title+' have?'));assert.equal(r.live,true,r.error);assert.equal(r.cached,true);assert.equal(r.checkedAt,h.checkedAt);assert.equal(r.product.handle,p.handle);assert.equal(r.productFacts.priceRange.max,75);assert.equal(productReads(h),reads);assert.equal(h.root.querySelector('.card'),null);assert.deepEqual(h.cart(),[]);});
test('native find answers the actual current-product question even when the model argument names an unrelated search',async t=>{const h=await fixture(t),p=h.products[28];await selectCurrent(h,p);await h.activate();const turns=turnReads(h),reads=productReads(h),r=await h.tool('find_jewellery',{message:'Find moon charms'},h.speak('What materials is this piece available in, and what are its prices?'));assert.equal(r.productFacts.handle,p.handle,r.error);assert.equal(r.productFacts.selectedVariant.price,75);assert.equal(r.productFacts.quantity,2);assert.equal(turnReads(h),turns);assert.equal(productReads(h),reads);assert.deepEqual(clone(r.products),[]);});
test('native exact inspection cannot substitute another inventory piece for a current-page pronoun question',async t=>{const h=await fixture(t),p=h.products[28];await selectCurrent(h,p);await h.activate();const r=await h.tool('inspect_jewellery',{handle:h.products[119].handle},h.speak('What is the price of this piece?'));assert.match(r.error,/exact current or named piece/);assert.equal(h.store.snapshot().currentHandle,p.handle);assert.deepEqual(h.cart(),[]);});
test('native discovery searches the complete checked loaded dictionary and qualifies matching variant prices',async t=>{const h=await fixture(t);await h.activate();const turns=turnReads(h),reads=productReads(h),r=await h.tool('find_jewellery',{message:'Find moon charms under $60'},h.speak('Find moon charms under $60'));assert.equal(r.verified,true,r.error);assert.equal(r.cached,true);assert.equal(r.inventory.loaded,120);assert.equal(r.inventory.catalogueComplete,false);assert.equal(r.products.length,1);assert.equal(r.products[0].handle,h.products[119].handle);assert.equal(r.products[0].matchingPriceRange.max,55);assert.equal(r.products[0].matchingVariantIds.length,2);assert.equal(turnReads(h),turns);assert.equal(productReads(h),reads);assert.doesNotMatch(JSON.stringify(r),/PRIVATE_/);});
test('native prepared view and options operate the exact real host controls from full cache',async t=>{const h=await fixture(t),p=h.products[119];await h.activate();let turn=h.speak('Open '+p.title),r=await h.tool('prepare_jewellery_action',{handle:p.handle,action:'view'},turn);assert.equal(r.prepared,true,r.error);assert.equal(h.d.querySelector('.product-copy h1').textContent,p.title);turn=h.speak('Open the metal menu');r=await h.tool('prepare_jewellery_action',{handle:p.handle,action:'options'},turn);assert.equal(r.prepared,true,r.error);assert.equal(h.d.querySelector('.option-menu').hidden,false);assert.equal(productReads(h),0);assert.equal(h.root.querySelector('.options'),null);assert.deepEqual(h.cart(),[]);});
test('held product cache retains descriptive identity without verified commercial facts or recommendations',async t=>{
  const products=catalogue();products[119].cartHold=true;const h=await fixture(t,{products});await h.activate();
  let r=await h.tool('inspect_jewellery',{handle:products[119].handle},h.speak('What materials does '+products[119].title+' have?'));
  assert.equal(r.cached,true,r.error);assert.equal(r.product.cartHold,true);assert.equal(r.product.id,products[119].id);assert.equal(r.product.handle,products[119].handle);assert.equal(r.product.title,products[119].title);assert.equal(r.product.description,products[119].description);
  assert.equal(r.product.status,'under_review');assert.equal(r.product.verified,false);assert.equal(r.product.factsSource.verified,false);assert.deepEqual(clone(r.productFacts),{status:'unconfirmed'});assert.deepEqual(clone(r.product.variants),[]);assert.deepEqual(clone(r.actions),[]);assert.doesNotMatch(JSON.stringify(r.product),/"(?:minPrice|price|selectedVariant|itemTotalPrice|available)":/);
  r=await h.tool('find_jewellery',{message:'Find moon charms under $90'},h.speak('Find moon charms under $90'));assert.equal(r.verified,true,r.error);assert.equal(r.products.length,0);assert.deepEqual(h.cart(),[]);
});
test('unavailable known stock can be explained without converting it to a recommendation or bag review',async t=>{const products=catalogue();products[119].variants.forEach(v=>v.available=false);const h=await fixture(t,{products});await h.activate();const r=await h.tool('inspect_jewellery',{handle:products[119].handle},h.speak('What materials and prices does '+products[119].title+' have?'));assert.equal(r.cached,true,r.error);assert.equal(r.productFacts.availability.status,'unavailable');assert.equal(r.productFacts.priceRange.basis,'checked_published_options');assert.ok(r.product.variants.every(v=>v.available===false));assert.deepEqual(h.cart(),[]);});
test('unknown stock remains unconfirmed on exact read and never becomes available authority',async t=>{const products=catalogue();products[119].variants.forEach(v=>{v.available=false;v.availabilityKnown=false;});const h=await fixture(t,{products});await h.activate();const r=await h.tool('inspect_jewellery',{handle:products[119].handle},h.speak('What materials and prices does '+products[119].title+' have?'));assert.equal(r.live,true,r.error);assert.equal(r.cached,false);assert.equal(r.productFacts.availability.status,'unconfirmed');assert.ok(r.product.variants.every(v=>v.available===false&&v.availabilityKnown===false));assert.deepEqual(h.cart(),[]);});
test('expired native cache does not become current stock or a recommendation',async t=>{const h=await fixture(t,{checkedAt:Date.now()-301000}),p=h.products[119];await h.activate();const reads=productReads(h),r=await h.tool('inspect_jewellery',{handle:p.handle},h.speak('What materials and prices does '+p.title+' have?'));assert.equal(r.live,true,r.error);assert.equal(r.cached,false);assert.ok(r.checkedAt>h.checkedAt);assert.equal(productReads(h),reads+1);assert.equal(h.store.getInventory().length,0);assert.deepEqual(h.cart(),[]);});
test('fresh cached price drift cannot quote an older on-page choice as current',async t=>{const h=await fixture(t),p=h.products[28];await selectCurrent(h,p);p.variants.at(-1).price+=10;await h.store.preloadInventory({retry:true});await settle();await h.activate();const r=await h.tool('inspect_jewellery',{handle:p.handle},h.speak('What is the current selected price?'));assert.equal(r.cached,true,r.error);const pc=h.store.snapshot().productControls;if(pc.selectedVariant?.price===85){assert.equal(r.product.selectedVariant.price,85);assert.equal(r.productFacts.itemTotalPrice,170);}else{assert.equal(r.product.selectionNeedsRefresh,true);assert.equal(r.product.selectedVariant,undefined);}assert.deepEqual(h.cart(),[]);});
test('optional reviewed Confirm add still makes a fresh exact stock and price check after cached information',async t=>{const h=await fixture(t),p=h.products[28];await selectCurrent(h,p);await h.send('What materials and prices does this piece have?');assert.equal((await h.send('Review adding this piece to my bag')).ok,true);assert.deepEqual(h.cart(),[]);const reads=productReads(h);p.variants.at(-1).price+=10;h.d.querySelector('.product-review .primary').click();await settle();assert.ok(productReads(h)>reads,'shopper Confirm must recheck authoritative exact product');assert.deepEqual(h.cart(),[]);assert.equal(h.d.querySelector('.product-review'),null,'A changed-price review must be retired');assert.match(h.d.querySelector('#storefront-status').textContent,/price.*changed|changed.*price/i);assert.equal(h.store.snapshot().productControls.selectedVariant.id,p.variants.at(-1).id);assert.equal(h.store.snapshot().productControls.selectedVariant.price,85);assert.equal(h.store.snapshot().productControls.quantity,2);assert.match(h.d.querySelector('.product-price').textContent,/85\.00/);});
test('unsupported product questions retain actual current identity in the backend context rather than old widget handles',async t=>{const h=await fixture(t,{restored:[piece(1,'regular-necklaces','Old Widget Necklace')]}),p=h.products[28];await selectCurrent(h,p);await h.send('What does this piece symbolize?');const request=h.calls.requests.filter(r=>r.url.pathname==='/api/concierge'&&r.body?.message).at(-1);assert.equal(request.body.context.currentHandle,p.handle);assert.deepEqual(request.body.context.productHandles,[p.handle]);assert.equal(request.body.context.currentProduct.handle,p.handle);assert.doesNotMatch(JSON.stringify(request.body.context),/PRIVATE_/);});
test('new native page controls validate exact schemas and public gallery/navigation context',()=>{for(const value of [{type:'back'},{type:'forward'},{type:'gallery',handle:'understanding-1',index:2},{type:'scroll',direction:'down'},{type:'highlight',handle:'understanding-1',section:'materials'}])assert.deepEqual(Voice.validateToolArguments(value,'control_storefront'),value);for(const value of [{type:'back',handle:'understanding-1'},{type:'gallery',handle:'understanding-1',index:0},{type:'scroll',direction:'down',section:'price'},{type:'scroll',direction:'top',handle:'understanding-1'}])assert.equal(Voice.validateToolArguments(value,'control_storefront'),null);const context=Voice.publicContext({controlVersion:1,pageKind:'product',currentHandle:'understanding-1',navigationControls:{canGoBack:true,canGoForward:false,privateNotes:'PRIVATE_NAV'},galleryControls:{handle:'understanding-1',imageCount:3,selectedIndex:2,privateNotes:'PRIVATE_IMAGE'}});assert.deepEqual(context.navigationControls,{canGoBack:true,canGoForward:false});assert.deepEqual(context.galleryControls,{handle:'understanding-1',imageCount:3,selectedIndex:2});assert.doesNotMatch(JSON.stringify(context),/PRIVATE_/);});
function facts(p,checkedAt=Date.now()){return {status:'verified',productId:p.id,handle:p.handle,title:p.title,type:p.type,partsOnly:p.partsOnly,description:p.description,dimensions:[],options:p.options.map(g=>({...g,availableValues:g.values})),priceRange:{min:50,max:75,currency:'USD',basis:'checked_available_options'},availability:{status:'available',checkedVariants:4,availableVariants:4,variantsComplete:true},selectedVariant:{...p.variants.at(-1),currency:'USD',availabilityKnown:true},quantity:2,itemTotalPrice:150,checkedAt,fromCache:true,sources:[{title:'Published Brites product details',url:p.url,checkedAt}],privateNotes:'PRIVATE_FACTS_NOTE'};}
test('public backend facts keep checked provenance and exact values while dropping caller notes and malformed totals',()=>{const p=piece(1),value=facts(p);value.selectedVariant.privateNotes='PRIVATE_SELECTED_NOTE';value.selectedVariant.options[0].privateNotes='PRIVATE_OPTION_NOTE';value.itemTotalPrice=999;const projected=Widget.publicProductFacts(value);assert.equal(projected.selectedVariant.price,75);assert.equal(projected.quantity,2);assert.equal(projected.itemTotalPrice,null);assert.equal(projected.sources[0].checkedAt,value.checkedAt);assert.doesNotMatch(JSON.stringify(projected),/PRIVATE_/);value.sources[0].url='https://example.com/products/'+p.handle;assert.equal(Widget.publicProductFacts(value),null);});
test('unconfirmed backend facts cannot carry invented product, selected price or private fields',()=>{assert.deepEqual(Widget.publicProductFacts({status:'unconfirmed',productId:'gid://shopify/Product/123',selectedVariant:{price:999},privateNotes:'PRIVATE_UNCONFIRMED'}),{status:'unconfirmed'});});
test('native backend fallback retains only whitelisted exact product facts with source time',async t=>{const p=piece(29,'beady-necklaces','Strawberry Beady Necklace'),value=facts(p),h=await fixture(t,{answer:{live:true,reply:'Checked exact product facts.',preferences:{},products:[],meanings:[],preserveSelection:true,productFacts:value}});await selectCurrent(h,h.products[28]);const original=h.store;h.w.BritesSandboxStorefront={...original,getInventory:()=>[],readProduct:async()=>null};await h.activate();const r=await h.tool('find_jewellery',{message:'What materials and prices does this piece have?'},h.speak('What materials and prices does this piece have?'));assert.equal(r.verified,true,r.error);assert.equal(r.productFacts.handle,p.handle);assert.equal(r.productFacts.selectedVariant.price,75);assert.equal(r.productFacts.checkedAt,value.checkedAt);assert.equal(r.productFacts.fromCache,true);assert.doesNotMatch(JSON.stringify(r),/PRIVATE_/);assert.equal(turnReads(h),1);assert.deepEqual(h.cart(),[]);});
test('a backend fallback cannot answer a current-product question with unrelated inventory facts',async t=>{const other=piece(120,'charm-only','Moon Orbit Charm'),h=await fixture(t,{answer:{live:true,reply:'Unrelated moon facts.',preferences:{},products:[],meanings:[],preserveSelection:true,productFacts:facts(other)}}),current=h.products[28];await selectCurrent(h,current);const original=h.store;h.w.BritesSandboxStorefront={...original,getInventory:()=>[],readProduct:async()=>null};await h.activate();const r=await h.tool('find_jewellery',{message:'What materials and prices does this piece have?'},h.speak('What materials and prices does this piece have?'));assert.ok(r.error);assert.equal(r.productFacts,undefined);assert.equal(h.store.snapshot().currentHandle,current.handle);assert.equal(h.store.snapshot().productControls.selectedVariant.price,75);assert.deepEqual(h.cart(),[]);});
