'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const core=require('../../netlify/functions/_britesGrowth');
const clone=v=>v===undefined?undefined:structuredClone(v);
class Store {
  constructor(){this.docs=new Map();this.tail=Promise.resolve();}
  collection(name){return new Query(this,name);}
  batch(){const jobs=[];return {set:(r,v)=>jobs.push(()=>r.set(v)),update:(r,v)=>jobs.push(()=>r.update(v)),commit:async()=>{for(const j of jobs)await j();}};}
  runTransaction(fn){const run=this.tail.then(async()=>{const changes=[];const value=await fn({get:r=>r.get(),set:(r,v,opt)=>changes.push(()=>r.set(v,opt)),update:(r,v)=>changes.push(()=>r.update(v))});for(const c of changes)await c();return value;});this.tail=run.catch(()=>{});return run;}
}
class Ref {
  constructor(db,col,id){this.db=db;this.col=col;this.id=id;this.path=col+'/'+id;}
  async get(){const value=this.db.docs.get(this.path);return {id:this.id,ref:this,exists:value!==undefined,data:()=>clone(value)};}
  async set(v,opt={}){this.db.docs.set(this.path,clone(opt.merge?{...this.db.docs.get(this.path),...v}:v));}
  async update(v){assert(this.db.docs.has(this.path),'update missing document');await this.set(v,{merge:true});}
}
class Query {
  constructor(db,name,filters=[]){this.db=db;this.name=name;this.filters=filters;}
  doc(id){return new Ref(this.db,this.name,id);}
  where(k,op,v){assert.equal(op,'==');return new Query(this.db,this.name,[...this.filters,[k,v]]);}
  async get(){const docs=[];for(const [path,value] of this.db.docs)if(path.startsWith(this.name+'/')&&this.filters.every(([k,v])=>value[k]===v))docs.push(await this.doc(path.slice(this.name.length+1)).get());return {docs,size:docs.length};}
  async add(v){const r=this.doc('auto-'+this.db.docs.size);await r.set(v);return r;}
}
const product={id:'gid://shopify/Product/101',handle:'test-bunny',url:'https://britesjewelry.com/products/test-bunny',title:'Bunny necklace',description:'A sterling silver bunny.',currency:'USD',image:null,imageAlt:'',options:[],variants:[{id:'gid://shopify/ProductVariant/102',numericId:'102',title:'Silver',sku:'Bunny5',price:32,available:true,options:[]}],variantsComplete:true,checkedAt:Date.parse('2026-10-02T02:00:00Z')};
function fixture(){const db=new Store();let time=product.checkedAt;return {db,advance:ms=>time+=ms,now:()=>time,service:core.createGrowthService({db,now:()=>time})};}
function dossier(){return {schema:1,productId:product.id,handle:product.handle,sources:[{id:'product',url:product.url,title:product.title,excerpt:product.description,checkedAt:product.checkedAt,reviewed:true},{id:'offer',url:'https://example.com/products/rabbit',title:'Rabbit offer',excerpt:'A rabbit pendant offered for 40 USD.',checkedAt:product.checkedAt,reviewed:true}],facts:[{productId:product.id,claim:'Sterling silver',quote:'sterling silver',sourceIds:['product']}],buyerIntents:[{intent:'Gift for a bunny owner'}],competitors:[{name:'Example jeweller',url:'https://example.com/products/rabbit',price:40,currency:'USD',spend:{status:'unknown'},sourceIds:['offer']}],meanings:[],recommendations:[{channel:'ads',basis:'hypothesis',action:'Test rabbit-owner gift intent against broad animal intent.',measure:'Compare qualified clicks and verified purchases over the same period.',sourceIds:['product','offer']}]};}
async function seed(f,count=1){await f.service.saveProducts([product]);await f.service.importRanks(Array.from({length:count},(_,i)=>({rank:i+1,title:'Bunny Etsy item '+(i+1),handle:product.handle,sku:'Bunny5'})));}
test('parallel workers receive distinct transactional work leases',async()=>{const f=fixture();await seed(f,3);const claims=await Promise.all(Array.from({length:8},(_,i)=>f.service.claim('research','worker-'+i)));const got=claims.filter(x=>x.id);assert.equal(got.length,3);assert.equal(new Set(got.map(x=>x.id)).size,3);assert.equal(new Set(got.map(x=>x.leaseToken)).size,3);});
test('expired writer cannot release or overwrite a reassigned rank',async()=>{const f=fixture();await seed(f);const a=await f.service.claim();f.advance(46*60000);await assert.rejects(f.service.release(a.id,a.leaseToken,{error:'old worker'}),/lease|expired/i);const b=await f.service.claim('research','replacement');assert.equal(b.id,a.id);await assert.rejects(f.service.release(a.id,a.leaseToken,{error:'old worker'}),/lease|writer/i);assert.equal((await f.service.status()).queue[0].leaseToken,b.leaseToken);});
test('a match needs the current exact product and inspected evidence',async()=>{const f=fixture();await seed(f);const a=await f.service.claim();await assert.rejects(f.service.release(a.id,a.leaseToken,{productId:product.id,handle:'wrong',match:{method:'manual',evidence:'Checked the current product',checkedAt:f.now()}}),/match|product|handle/i);await assert.rejects(f.service.release(a.id,a.leaseToken,{productId:product.id,handle:product.handle,match:{private:'arbitrary'}}),/match|evidence/i);await f.service.release(a.id,a.leaseToken,{productId:product.id,handle:product.handle,match:{method:'exact_sku',evidence:'Current published variant retains Bunny5 SKU and necklace type.',checkedAt:f.now()}});assert.equal((await f.service.status()).counts.matched,1);});
test('approved research survives partial rewrites and keeps version history',async()=>{const f=fixture();await seed(f);const a=dossier();const saved=await f.service.saveDossier(a);assert.equal(saved.validation.status,'approved');const draft={...a,competitors:[]};await assert.rejects(f.service.saveDossier(draft),/partial draft/i);assert.equal((await f.service.research([product.id]))[0].version,saved.version);const b={...a,buyerIntents:[{intent:'Birthday gift for a bunny owner'}]};const next=await f.service.saveDossier(b);assert.notEqual(next.version,saved.version);assert.equal((await f.service.col('ResearchVersions').get()).size,1);});
test('commercial facts cannot use a competitor quote and unreviewed/stale evidence fails',()=>{const bad=dossier();bad.facts=[{productId:product.id,claim:'Rabbit pendant',quote:'rabbit pendant',sourceIds:['offer']}];assert.equal(core.validateDossier(bad,product,product.checkedAt).ok,false);const stale=dossier();stale.sources[0].checkedAt-=31*86400000;assert.equal(core.validateDossier(stale,product,product.checkedAt).ok,false);const unseen=dossier();unseen.sources[0].reviewed=false;assert.equal(core.validateDossier(unseen,product,product.checkedAt).ok,false);});
test('arbitrary competitor spending states are rejected',()=>{const value=dossier();value.competitors[0].spend={status:'fabricated'};const checked=core.validateDossier(value,product,product.checkedAt);assert.equal(checked.ok,false);assert.match(checked.errors.join(' '),/explicitly labelled unknown, known or estimate/);});
test('foreign product knowledge and private fields never appear in public interpretations',()=>{const a={...dossier(),status:'approved',orders:999,meanings:[{text:'A personal interpretation',context:'Individual preference',kind:'interpretation',sourceIds:['product'],privateNote:'owner-only'}]};const projected=JSON.stringify(core.publicMeanings([a],[product.id],product.checkedAt));assert(!projected.includes('999'));assert(!projected.includes('owner-only'));assert.deepEqual(core.publicMeanings([a],['gid://shopify/Product/999'],product.checkedAt),[]);});
test('changed ranked identity invalidates a previously completed rank',async()=>{const f=fixture();await seed(f);await f.service.importRanks([{rank:1,title:'Bunny',handle:product.handle,productId:product.id}]);await f.service.saveDossier(dossier());assert.equal((await f.service.status()).counts.complete,1);await f.service.importRanks([{rank:1,title:'Changed item',handle:'other',productId:'gid://shopify/Product/999'}]);const s=await f.service.status();assert.equal(s.counts.complete,0);assert.equal(s.queue[0].dossierVersion,null);assert.equal(s.queue[0].leaseToken,null);});
test('hard stop prevents both claims and catalogue work',async()=>{const f=fixture();await seed(f);f.advance(15*86400000);assert.deepEqual(await f.service.claim(),{stopped:true});assert.deepEqual(await f.service.syncCatalogue(),{stopped:true});});
