'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const Memory=require('../../netlify/functions/_britesConciergeMemory.js');
const NS='Brites_Growth_Sandbox',NOW=Date.parse('2026-10-10T12:00:00Z'),clone=value=>value===undefined?undefined:JSON.parse(JSON.stringify(value)),hash=value=>crypto.createHash('sha256').update(value).digest('hex');
function fixture(){const data=new Map(),operations=[],clock={now:NOW};let tail=Promise.resolve(),onRead=null;
 class Ref{constructor(path){this.path=path;this.id=path.split('/').pop();}collection(name){return new Query(this.path+'/'+name);}async get(){operations.push(['read',this.path]);if(onRead)await onRead(this.path);const value=data.get(this.path);return {exists:value!==undefined,data:()=>clone(value),ref:this,id:this.id};}async set(value,options){data.set(this.path,options?.merge?{...data.get(this.path),...clone(value)}:clone(value));}}
 class Query{constructor(path,count=Infinity){this.path=path;this.count=count;}doc(id){return new Ref(this.path+'/'+id);}limit(count){return new Query(this.path,count);}async get(){operations.push(['query',this.path,this.count]);return {docs:[...data].filter(([path])=>path.startsWith(this.path+'/')&&!path.slice(this.path.length+1).includes('/')).slice(0,this.count).map(([path,value])=>({ref:new Ref(path),data:()=>clone(value)}))};}}
 const db={collection:path=>new Query(path),runTransaction(fn){const result=tail.catch(()=>{}).then(async()=>{const writes=[],tx={get:ref=>ref.get(),set:(ref,value,options)=>writes.push(['set',ref,value,options]),delete:ref=>writes.push(['delete',ref])};const result=await fn(tx);for(const [kind,ref,value,options]of writes){operations.push([kind,ref.path]);if(kind==='delete')data.delete(ref.path);else await ref.set(value,options);}return result;});tail=result;return result;},batch(){const rows=[];return {delete:ref=>rows.push(ref),async commit(){for(const ref of rows){data.delete(ref.path);operations.push(['delete',ref.path]);}}};}};
 return {db,data,operations,clock,identity:uid=>({uid,scope:hash(uid),emailVerified:true,email:uid+'@fixture.example'}),service:Memory.createMemoryService({db,env:{BRITES_GROWTH_NAMESPACE:NS},now:()=>clock.now}),readHook:fn=>{onRead=fn;}};
}
function draft(id='set52'){return {schema:1,id,revision:4,currency:'CAD',marketKey:'CA:CAD',totalBudget:90,size:2,motif:'butterfly',rows:[1,2].map(n=>({rowId:'piece-'+n,productId:'gid://shopify/Product/'+n,handle:'butterfly-'+n,variantId:'gid://shopify/ProductVariant/'+n+'01',quantity:1,price:40,checkedAt:NOW,choiceStatus:'confirmed',engraving:'PRIVATE_ENGRAVING'})),actions:[{type:'add'}],personalContext:{reason:'PRIVATE_REASON'}};}
const save=(value,version=0,generation='0')=>({action:'draft-save',consent:true,generation,expectedVersion:version,draft:value});
const read=(generation='0')=>({action:'draft-read',consent:true,generation});

test('draft request shape and consent fail before auth, Firestore connection or estimated budget reservation',async()=>{const f=fixture();let authReads=0;const handler=Memory.createRequestHandler({db:f.db,now:()=>f.clock.now,auth:{async verifyIdToken(){authReads++;return {uid:'alice',email:'alice@fixture.example',exp:2e10};}}});for(const body of [{...read(),consent:false},{...save(draft()),generation:null},{...save(draft()),expectedVersion:0.5},{...save(draft()),draft:{...draft(),rows:Array(4).fill(draft().rows[0])}}]){const response=await handler(new Request('https://preview.example/api/concierge-memory',{method:'POST',headers:{Authorization:'Bearer existing-token'},body:JSON.stringify(body)}));assert([400,403].includes(response.status));}assert.equal(authReads,0);assert.deepEqual(f.operations,[]);});
test('authenticated owner scopes saved-set IDs and strips all private data and restored authority',async()=>{const f=fixture(),owner=f.identity('alice'),saved=await f.service.execute(owner,{...save(draft()),uid:'bob',email:'bob@fixture.example'});assert.equal(saved.version,1);assert.equal(saved.requiresFreshCheck,true);const records=[...f.data].filter(([key])=>key.includes('/SetDrafts_'));assert.equal(records.length,1);assert(records[0][0].includes(hash('alice')));assert.doesNotMatch(JSON.stringify(records),/PRIVATE|price|checkedAt|confirmed|actions|engraving|bob/);assert.deepEqual((await f.service.execute(f.identity('bob'),read())).drafts,[]);const result=await f.service.execute(owner,read());assert.equal(result.version,1);assert.equal(result.drafts[0].draft.status,'needs_revalidation');assert.equal(result.drafts[0].draft.totalBudget,90);});
test('per-account draft write throttle is separate from history sync and idempotence does not mutate versions',async()=>{const f=fixture(),owner=f.identity('alice'),first=await f.service.execute(owner,save(draft()));const duplicate=await f.service.execute(owner,save(draft(),first.version));assert.equal(duplicate.duplicate,true);assert.equal(duplicate.version,first.version);assert.equal([...f.data.keys()].filter(key=>key.includes('/SetDrafts_')).length,1);await assert.rejects(f.service.execute(owner,save({...draft(),revision:5},first.version)),error=>error.status===429&&error.extra.retryAfterMs===60000);f.clock.now+=60000;const updated=await f.service.execute(owner,save({...draft(),revision:5},first.version));assert.equal(updated.version,2);});
test('parallel expected-version writes commit one draft only and stale clear cannot delete a later correction',async()=>{const f=fixture(),owner=f.identity('alice'),results=await Promise.allSettled([f.service.execute(owner,save(draft('tab-a'))),f.service.execute(owner,save(draft('tab-b')))]);assert.equal(results.filter(row=>row.status==='fulfilled').length,1);assert.equal(results.filter(row=>row.status==='rejected'&&row.reason.status===409).length,1);f.clock.now+=60000;await assert.rejects(f.service.execute(owner,{action:'draft-clear',consent:true,generation:'0',expectedVersion:0,id:'tab-a'}),error=>error.extra.conflictRequired);assert.equal((await f.service.execute(owner,read())).drafts.length,1);});
test('explicit single-draft clear frees capacity while the collection version prevents stale recreation',async()=>{const f=fixture(),owner=f.identity('alice');let version=0;for(let i=0;i<5;i++){f.clock.now+=60000;version=(await f.service.execute(owner,save(draft('set-'+i),version))).version;}f.clock.now+=60000;await assert.rejects(f.service.execute(owner,save(draft('sixth'),version)),error=>error.extra.draftLimit);const cleared=await f.service.execute(owner,{action:'draft-clear',consent:true,generation:'0',expectedVersion:version,id:'set-0'});assert.equal(cleared.version,version+1);f.clock.now+=60000;await assert.rejects(f.service.execute(owner,save(draft('set-0'),version)),error=>error.extra.conflictRequired);assert.equal((await f.service.execute(owner,save(draft('sixth'),cleared.version))).version,cleared.version+1);assert.equal((await f.service.execute(owner,read())).drafts.length,5);});
test('full history forget physically cleans old-generation draft docs and denies late reads/writes',async()=>{const f=fixture(),owner=f.identity('alice');await f.service.execute(owner,save(draft()));const cleared=await f.service.clear(owner,{});assert.equal(cleared.cleanupPending,false);assert.equal([...f.data.keys()].some(key=>key.includes('/SetDrafts_0/')),false);await assert.rejects(f.service.execute(owner,save(draft('late'),1)),error=>error.status===409&&error.extra.resetRequired);await assert.rejects(f.service.execute(owner,read()),error=>error.extra.resetRequired);assert.deepEqual((await f.service.execute(owner,read(cleared.generation))).drafts,[]);});
test('a read held across a generation reset never returns the old draft',async()=>{const f=fixture(),owner=f.identity('alice');await f.service.execute(owner,save(draft()));let release,entered;const gate=new Promise(resolve=>release=resolve),seen=new Promise(resolve=>entered=resolve);f.readHook(async path=>{if(path.includes('/SetDrafts_0/')){f.readHook(null);entered();await gate;}});const pending=f.service.execute(owner,read());await seen;await f.service.clear(owner,{});release();await assert.rejects(pending,error=>error.extra.resetRequired);});
test('delivery preference enums persist only supported explicit values and direct archive credential strings are redacted',()=>{assert.deepEqual(Memory.preferences({voicePace:'slow',voiceDetail:'expanded',suggestions:'off',emotion:'grief',voiceSpeed:0.6}),{voicePace:'slow',voiceDetail:'expanded',suggestions:'off'});assert.deepEqual(Memory.preferences({voicePace:'frantic',voiceDetail:'huge',suggestions:true}),{});const sanitized=Memory.chunk({id:'direct52',kind:'conversation',at:NOW,messages:[{role:'user',content:'password=SECRET52 refresh_token is REFRESH52 api_key:API52 passcode is CODE52. I enjoy the garden.'}],preferences:{intent:'api key = PRIVATE52',recipient:'sister'}},NOW);assert.doesNotMatch(JSON.stringify(sanitized),/SECRET52|REFRESH52|API52|CODE52|PRIVATE52/);assert.match(sanitized.messages[0].content,/I enjoy the garden/);assert.equal(sanitized.preferences.recipient,'sister');});
test('shared owner daily allowance bounds draft reads/writes using estimates and never changes aiEnabled',async()=>{const f=fixture();f.data.set(NS+'_State/control',{aiEnabled:false,aiDailyUsdCap:0.0005});await assert.rejects(f.service.execute(f.identity('alice'),save(draft())),error=>error.status===429);assert.equal([...f.data.keys()].some(key=>key.includes('_ConciergeCustomers/')),false);assert.equal(f.data.get(NS+'_State/control').aiEnabled,false);await f.service.execute(f.identity('alice'),read());const usage=f.data.get(NS+'_Usage/2026-10-10');assert.equal(usage.memoryCostBasis,'conservative_firestore_estimate');assert.equal(usage.memoryEstimatedUsd,0.0005);});
