'use strict';
// Actual migration adapter with the browser-observed Brites cart DOM.
// Native event handlers and cart GET responses are synthetic. No real cart,
// checkout, provider or microphone acceptance is claimed by these tests.
const test=require('node:test'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const Adapter=require('../../brites-shopify-storefront-adapter.js');
const clone=v=>JSON.parse(JSON.stringify(v));
function fixture(t,{root='/',afterNative,fetchWait,collectionHandles=[]}={}){
  const items=[{key:'3701:exact-a',product_id:3700,variant_id:3701,product_title:'Bunny Necklace',variant_title:'Sterling Silver / 18 inch',quantity:1,final_price:5400,properties:{engraving:'PRIVATE-ENGRAVING'}},{key:'3801:exact-b',product_id:3800,variant_id:3801,product_title:'Flower Stud Earrings',variant_title:'14k Gold Filled',quantity:2,final_price:4500}];
  const dom=new JSDOM(`<main id="MainContent"><form id="bjCartForm" action="${root}cart" method="post"><div id="bjCartItems">${items.map(i=>`<div class="bj-cp__row" data-key="${i.key}" data-title="${i.product_title}"><a class="cart__product-name">${i.product_title}</a><div data-bjcp-qtywrap><input type="number" class="cart__product-qty" name="updates[]" data-id="${i.key}" value="${i.quantity}"><button type="button">–</button><b>${i.quantity}</b><button type="button">+</button></div><a data-bjcp-remove href="${root}cart/change?id=${i.key}&quantity=0">Remove</a></div>`).join('')}</div><div id="is-a-gift"><label><input id="gift-wrapping" type="checkbox" name="attributes[gift-wrapping]">For $2.00 gift wrap my order.</label><textarea id="gift-note" name="attributes[gift-note]">PRIVATE-GIFT-NOTE</textarea></div><button name="checkout" type="submit">Check out</button></form></main>`,{url:'https://britesjewelry.com'+root+'cart'});
  const w=dom.window,d=w.document,reads=[],native=[],submits=[],nav=[],reveals=[];
  w.HTMLElement.prototype.scrollIntoView=function(){reveals.push(this);};d.querySelector('#bjCartForm').requestSubmit=button=>submits.push(button.name);
  const state={cart:{currency:'USD',item_count:3,items,token:'PRIVATE-CART-TOKEN',note:'PRIVATE-ORDER-NOTE',attributes:{'gift-note':'PRIVATE-GIFT-NOTE'}},wait:null};
  const changed=(row,quantity)=>{const key=row.dataset.key;native.push({key,quantity});queueMicrotask(()=>{const item=state.cart.items.find(i=>i.key===key);if(quantity===0){state.cart.items=state.cart.items.filter(i=>i.key!==key);row.remove();}else{item.quantity=quantity;row.querySelector('input').value=String(quantity);row.querySelector('b').textContent=String(quantity);}state.cart.item_count=state.cart.items.reduce((n,i)=>n+i.quantity,0);afterNative?.({state,row,key,quantity});d.dispatchEvent(new w.CustomEvent('cart:updated'));});};
  for(const row of d.querySelectorAll('.bj-cp__row')){const steps=row.querySelectorAll('button');steps[0].addEventListener('click',()=>changed(row,Number(row.querySelector('input').value)-1));steps[1].addEventListener('click',()=>changed(row,Number(row.querySelector('input').value)+1));row.querySelector('[data-bjcp-remove]').addEventListener('click',e=>{e.preventDefault();row.classList.add('bjcp-removing');changed(row,0);});}
  const adapter=Adapter.create({window:w,theme:'brites-v1',root,currency:'USD',collectionHandles,fetch:async(url,options)=>{reads.push({url,options});if(state.wait)await state.wait();if(fetchWait)await fetchWait();return {ok:true,json:async()=>clone(state.cart)};},navigate:url=>nav.push(url)});
  t.after(()=>{adapter.destroy();w.close();});return {adapter,w,d,state,reads,native,submits,nav,reveals};
}
const run=(f,action,extra={})=>f.adapter.execute(action,{requestId:'current-shopper-'+Math.random(),...extra});
test('public cart context binds visible exact live rows and prices, excludes all private cart fields',async t=>{const f=fixture(t,{root:'/en-ca/'});assert.equal(await f.adapter.refresh(),true);const s=f.adapter.snapshot();assert.equal(s.bagControls.lines.length,2);assert.equal(s.bagControls.lines[0].price,54);assert.equal(s.bagControls.lines[1].currency,'USD');assert.equal(s.bagControls.itemCount,3);assert.equal(JSON.stringify(s).includes('PRIVATE'),false);assert(f.adapter.capabilities.actions.includes('bag-quantity'));assert(f.adapter.capabilities.actions.includes('bag-remove'));assert(f.reads.every(r=>r.url==='/en-ca/cart.js'&&r.options.method==='GET'&&r.options.credentials==='same-origin'));});
test('an absolute quantity uses existing native steppers and checks every result before another step',async t=>{const f=fixture(t);await f.adapter.refresh();const r=await run(f,{type:'bag-quantity',lineId:'3701:exact-a',quantity:3});assert.equal(r.ok,true,r.reason);assert.equal(r.cartChanged,true);assert.deepEqual(f.native,[{key:'3701:exact-a',quantity:2},{key:'3701:exact-a',quantity:3}]);assert.equal(r.snapshot.bagControls.lines[0].quantity,3);assert.equal(r.snapshot.bagControls.lines[1].quantity,2);assert(f.reads.every(read=>read.options.method==='GET'));assert.equal(f.submits.length,0);});
test('already selected quantity has no native write',async t=>{const f=fixture(t);await f.adapter.refresh();const r=await run(f,{type:'bag-quantity',lineId:'3701:exact-a',quantity:1});assert.equal(r.ok,true);assert.equal(r.cartChanged,false);assert.deepEqual(f.native,[]);});
test('removal uses only the exact current native remove link, keeps unrelated lines',async t=>{const f=fixture(t);await f.adapter.refresh();const r=await run(f,{type:'bag-remove',lineId:'3701:exact-a'});assert.equal(r.ok,true,r.reason);assert.deepEqual(f.native,[{key:'3701:exact-a',quantity:0}]);assert.equal(r.snapshot.bagControls.lines.length,1);assert.equal(r.snapshot.bagControls.lines[0].lineId,'3801:exact-b');assert.equal(f.state.cart.items[0].quantity,2);});
test('a concurrent cart change fails before any native write',async t=>{const f=fixture(t);await f.adapter.refresh();f.state.cart.items[0].quantity=2;f.state.cart.item_count=4;const r=await run(f,{type:'bag-quantity',lineId:'3701:exact-a',quantity:3});assert.equal(r.ok,false);assert.equal(r.stale,true);assert.deepEqual(f.native,[]);});
for(const [label,damage] of [['foreign exact key',f=>f.d.querySelector('input').dataset.id='9999:foreign'],['changed visible title',f=>f.d.querySelector('.cart__product-name').textContent='Another piece'],['stale visible quantity',f=>f.d.querySelector('input').value='2'],['unsupported stepper',f=>f.d.querySelector('button').textContent='Buy now'],['foreign remove endpoint',f=>f.d.querySelector('[data-bjcp-remove]').href='https://evil.example/cart/change']])test('changed native binding refuses '+label,async t=>{const f=fixture(t);await f.adapter.refresh();damage(f);const r=await run(f,{type:'bag-remove',lineId:'3701:exact-a'});assert.equal(r.ok,false);assert.deepEqual(f.native,[]);});
test('unrelated identity or quantity changes stop a multi-step action after the first native result',async t=>{const f=fixture(t,{afterNative:({state})=>{state.cart.items[1].quantity=4;state.cart.item_count=state.cart.items.reduce((n,i)=>n+i.quantity,0);}});await f.adapter.refresh();const r=await run(f,{type:'bag-quantity',lineId:'3701:exact-a',quantity:4});assert.equal(r.ok,false);assert.equal(f.native.length,1);assert.match(r.reason,/bag changed/);});
test('cancelled preflight cannot actuate native cart controls',async t=>{const f=fixture(t);await f.adapter.refresh();const c=new AbortController();let release;f.state.wait=()=>new Promise(resolve=>{release=resolve;});const pending=run(f,{type:'bag-remove',lineId:'3701:exact-a'},{signal:c.signal});await Promise.resolve();c.abort();release();const r=await pending;assert.equal(r.ok,false);assert.equal(r.cancelled,true);assert.deepEqual(f.native,[]);});
test('paid gift wrapping exposes the real native section and leaves personal input and charges to the shopper',async t=>{const f=fixture(t);await f.adapter.refresh();const r=await run(f,{type:'gift',section:'gifts'});assert.equal(r.ok,true,r.reason);assert(f.reveals.includes(f.d.querySelector('#is-a-gift')));assert.equal(f.d.querySelector('#gift-wrapping').checked,false);assert.equal(f.d.querySelector('#gift-note').value,'PRIVATE-GIFT-NOTE');assert.deepEqual(f.native,[]);assert.equal(JSON.stringify(r.snapshot).includes('PRIVATE'),false);assert.equal(f.adapter.capabilities.notesMode,'unavailable');});
test('explicit checkout request hands off through the verified native form, never places an order or touches payment',async t=>{const f=fixture(t);await f.adapter.refresh();const r=await run(f,{type:'checkout'});assert.equal(r.ok,true,r.reason);assert.equal(r.navigationRequested,true);assert.equal(r.orderPlaced,false);assert.deepEqual(f.submits,['checkout']);assert.deepEqual(f.native,[]);assert.equal(f.adapter.capabilities.finalOrder,false);assert.equal(Adapter.validateAction({type:'checkout-complete'}),null);});
test('changed cart blocks checkout before native form submission',async t=>{const f=fixture(t);await f.adapter.refresh();f.state.cart.items[0].quantity=2;f.state.cart.item_count=4;const r=await run(f,{type:'checkout'});assert.equal(r.ok,false);assert.deepEqual(f.submits,[]);});
for(const [filter,handle] of [['beady-necklaces','beady-chain-necklaces'],['stud-earrings','charm-studs'],['hoop-earrings','huggie-hoops'],['charm-only','charms-only']])test('theme-confirmed real collection route '+filter,async t=>{const f=fixture(t,{root:'/en-ca/',collectionHandles:[handle]});const r=await run(f,{type:'filter',filter});assert.equal(r.ok,true,r.reason);assert.deepEqual(f.nav,['https://britesjewelry.com/en-ca/collections/'+handle]);});
test('unconfirmed collection cannot be invented from a model request',async t=>{const f=fixture(t);const r=await run(f,{type:'filter',filter:'hoop-earrings'});assert.equal(r.ok,false);assert.deepEqual(f.nav,[]);});
