'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const Adapter=require('../../brites-shopify-storefront-adapter.js');
const Bridge=require('../../brites-storefront-bridge.js');
const clone=value=>JSON.parse(JSON.stringify(value));
function product(){
  const variants=[];for(const metal of ['Sterling Silver','Gold Filled'])for(const length of ['16 inches','18 inches'])for(const engraving of ['None','Engraved'])variants.push({id:3901+variants.length,title:[metal,length,engraving].join(' / '),options:[metal,length,engraving],price:5000+variants.length*500,available:true});
  return {id:390,handle:'test-leaf',title:'Test Leaf Necklace',type:'Necklace',options:['Metal Choice','Chain Length','Engraving'],variants};
}
function fixture(t,{cart=false,engraving=true,maxLength=20,url,savedJourney,historyState,historyLength=1,referrer}={}){
  const raw=product(),image='https://cdn.shopify.com/s/files/1/test-leaf.jpg';
  const markup=cart?`<main id="MainContent"><form id="bjCartForm" action="/cart" method="post"><div id="bjCartItems"><div class="bj-cp__row" data-key="3901:exact" data-title="Test Leaf Necklace"><a class="cart__product-name">Test Leaf Necklace</a><div data-bjcp-qtywrap><input type="number" class="cart__product-qty" name="updates[]" data-id="3901:exact" value="2"><button type="button">–</button><b>2</b><button type="button">+</button></div><a data-bjcp-remove href="/cart/change?id=3901:exact&quantity=0">Remove</a></div></div><div id="is-a-gift"><label><input id="gift-wrapping" type="checkbox" name="attributes[gift-wrapping]">Gift wrapping $2.00</label><textarea id="gift-note" name="attributes[gift-note]" maxlength="30">PRIVATE_OLD_NOTE</textarea></div><button name="checkout" type="submit">Checkout</button></form></main>`:`<main id="MainContent"><div id="shopify-section-product-template"><h1 class="pi__title">Test Leaf Necklace</h1><span id="bjPrice">$50.00</span><div id="bjMedia"><figure class="m"><img src="${image}"></figure><div id="mDots"><i class="on"></i></div></div><form id="bjForm"><div id="bjMetals" data-idx="1"><button data-vi="0" type="button" class="on">Sterling Silver</button><button data-vi="1" type="button">Gold Filled</button></div><div class="bjselx"><select class="bjOptSel" data-idx="2"><option>16 inches</option><option>18 inches</option></select><button class="bjselx__btn" type="button" aria-haspopup="listbox" aria-expanded="false">Length</button></div><div id="bjEngr" data-idx="3"><input type="checkbox" id="bjEngrChk">${engraving?`<input type="text" id="bjEngrTxt" maxlength="${maxLength}" value="PRIVATE_OLD_TEXT">`:''}</div><button type="button" data-q="-1">–</button><input id="bjQty" value="1" readonly><button type="button" data-q="1">+</button><button type="button" id="bjAdd">Add</button></form></div></main>`;
  const dom=new JSDOM(markup,{url:url||'https://britesjewelry.com/'+(cart?'cart':'products/test-leaf'),...(referrer?{referrer}:{})}),w=dom.window,d=w.document,calls=[],clicks=[],privateEvents=[],nav=[];
  Object.defineProperty(w.history,'length',{configurable:true,value:historyLength});if(historyState!==undefined)w.history.replaceState(historyState,'');if(savedJourney)w.sessionStorage.setItem('brites:storefront-history:v1:/',JSON.stringify(savedJourney));
  let quantity=1,addClicks=0;
  w.HTMLElement.prototype.scrollIntoView=function(){};
  d.querySelectorAll('#bjMetals button').forEach(button=>button.addEventListener('click',()=>{clicks.push(button.textContent);d.querySelectorAll('#bjMetals button').forEach(node=>node.classList.toggle('on',node===button));}));
  d.querySelector('.bjselx__btn')?.addEventListener('click',event=>{const button=event.currentTarget;button.setAttribute('aria-expanded',String(button.getAttribute('aria-expanded')!=='true'));});
  d.querySelectorAll('button[data-q]').forEach(button=>button.addEventListener('click',()=>{quantity+=Number(button.dataset.q);d.querySelector('#bjQty').value=String(quantity);}));
  d.querySelector('#bjAdd')?.addEventListener('click',()=>{addClicks++;});
  const state={raw,cart:{currency:'USD',item_count:cart?2:0,items:cart?[{key:'3901:exact',product_id:390,variant_id:3901,product_title:raw.title,variant_title:raw.variants[0].title,quantity:2,final_price:5000,properties:{Engraving:'PRIVATE_CART_TEXT'}}]:[],attributes:{'gift-note':'PRIVATE_OLD_NOTE'},token:'PRIVATE_CART_TOKEN'}};
  const row=d.querySelector('.bj-cp__row');if(row){const change=value=>{clicks.push({lineId:row.dataset.key,quantity:value});queueMicrotask(()=>{if(value===0){state.cart.items=[];row.remove();}else{state.cart.items[0].quantity=value;row.querySelector('input').value=String(value);row.querySelector('b').textContent=String(value);}state.cart.item_count=value;d.dispatchEvent(new w.CustomEvent('cart:updated'));});};row.querySelectorAll('button')[0].addEventListener('click',()=>change(Number(row.querySelector('input').value)-1));row.querySelectorAll('button')[1].addEventListener('click',()=>change(Number(row.querySelector('input').value)+1));row.querySelector('[data-bjcp-remove]').addEventListener('click',e=>{e.preventDefault();row.classList.add('bjcp-removing');change(0);});}
  for(const node of d.querySelectorAll('#bjEngrTxt,#gift-note,#gift-wrapping'))for(const event of ['input','change'])node.addEventListener(event,()=>privateEvents.push({id:node.id,event}));
  const instance=Adapter.create({window:w,root:'/',theme:'brites-v1',currency:'USD',product:raw,variantCount:raw.variants.length,fetch:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>clone(url.endsWith('cart.js')?state.cart:state.raw)};},navigate:url=>nav.push(url)});
  t.after(()=>{instance.destroy();w.close();});let seq=0;
  return {w,d,instance,state,calls,clicks,privateEvents,nav,image,get quantity(){return quantity;},get adds(){return addClicks;},run:action=>instance.execute(action,{requestId:'commerce-'+(++seq)})};
}
test('one native undo restores the exact prior material, preserving length and closure-backed quantity without reads',async t=>{
  const f=fixture(t);await f.run({type:'select-option',handle:'test-leaf',optionName:'Chain Length',optionValue:'18 inches'});await f.run({type:'product-quantity',handle:'test-leaf',quantity:3});await f.run({type:'select-option',handle:'test-leaf',optionName:'Metal Choice',optionValue:'Gold Filled'});
  assert.deepEqual(f.instance.snapshot().changeControls,{canUndo:true,kind:'select-option'});assert.equal((await f.run({type:'undo'})).ok,true);const pc=f.instance.snapshot().productControls;assert.equal(pc.selectedVariant.id,'gid://shopify/ProductVariant/3903');assert.equal(pc.quantity,3);assert.equal(f.quantity,3);assert.equal(f.calls.length,0);assert.equal(f.adds,0);assert.equal(f.instance.snapshot().changeControls.canUndo,false);assert.equal((await f.run({type:'undo'})).ok,false);
});
test('native product quantity undo operates its steppers rather than only changing the displayed input',async t=>{const f=fixture(t);await f.run({type:'product-quantity',handle:'test-leaf',quantity:5});assert.equal(f.quantity,5);assert.equal((await f.run({type:'undo'})).ok,true);assert.equal(f.quantity,1);assert.equal(f.d.querySelector('#bjQty').value,'1');assert.equal(f.calls.length,0);});
test('manual newer choices withdraw old undo without switching a different exact choice',async t=>{const f=fixture(t);await f.run({type:'select-option',handle:'test-leaf',optionName:'Metal Choice',optionValue:'Gold Filled'});const select=f.d.querySelector('select');select.value='18 inches';select.dispatchEvent(new f.w.Event('change',{bubbles:true}));assert.equal(f.instance.snapshot().changeControls.canUndo,false);assert.equal((await f.run({type:'undo'})).ok,false);assert.equal(f.d.querySelector('#bjMetals .on').textContent,'Gold Filled');assert.equal(select.value,'18 inches');});
test('changed checked stock invalidates rather than reviving the old reversible choice',async t=>{const f=fixture(t);await f.run({type:'select-option',handle:'test-leaf',optionName:'Metal Choice',optionValue:'Gold Filled'});f.state.raw.variants[0].available=false;await f.instance.refresh();assert.equal(f.instance.snapshot().changeControls.canUndo,false);assert.equal((await f.run({type:'undo'})).ok,false);assert.equal(f.d.querySelector('#bjMetals .on').textContent,'Gold Filled');});
test('native listbox closing confirms the actual collapsed attribute and retains all selections',async t=>{const f=fixture(t);await f.run({type:'options',handle:'test-leaf',optionName:'Chain Length'});const prior=clone(f.instance.snapshot().productControls.selectedOptions),r=await f.run({type:'close-options'});assert.equal(r.ok,true);assert.equal(f.d.querySelector('.bjselx__btn').getAttribute('aria-expanded'),'false');assert.equal(r.snapshot.productControls.optionsOpen,false);assert.deepEqual(r.snapshot.productControls.selectedOptions,prior);assert.equal(f.calls.length,0);});
test('manually opened and closed native menus are reflected in current context without a conversational shortcut',t=>{const f=fixture(t),button=f.d.querySelector('.bjselx__btn');button.click();assert.equal(f.instance.snapshot().productControls.optionsOpen,true);assert.equal(f.instance.snapshot().productControls.openedOption,'Chain Length');button.click();assert.equal(f.instance.snapshot().productControls.optionsOpen,false);assert.equal(f.calls.length,0);});
test('a menu that ignores its native close is reported as an unconfirmed change',async t=>{const f=fixture(t);await f.run({type:'options',handle:'test-leaf',optionName:'Chain Length'});const button=f.d.querySelector('.bjselx__btn');button.addEventListener('click',()=>button.setAttribute('aria-expanded','true'));const r=await f.run({type:'close-options'});assert.equal(r.ok,false);assert.match(r.reason,/not confirmed/);assert.equal(button.getAttribute('aria-expanded'),'true');});
test('only an actual open native image dialog tied to the current gallery can close',async t=>{
  const f=fixture(t),media=f.d.querySelector('#bjMedia'),dialog=f.d.createElement('dialog');dialog.setAttribute('open','');dialog.innerHTML='<img src="'+f.image+'">';media.append(dialog);let closes=0;dialog.close=()=>{closes++;dialog.removeAttribute('open');};assert.equal(f.instance.snapshot().imageControls.open,true);assert.equal((await f.run({type:'close-image'})).ok,true);assert.equal(closes,1);assert.equal(f.instance.snapshot().imageControls.open,false);assert.equal(f.adds,0);
  const unrelated=f.d.createElement('dialog');unrelated.setAttribute('open','');unrelated.innerHTML='<img src="https://cdn.shopify.com/s/files/1/another.jpg">';unrelated.close=()=>assert.fail('unrelated modal cannot close');media.append(unrelated);assert.equal(f.instance.capabilities.actions.includes('close-image'),false);assert.equal((await f.run({type:'close-image'})).ok,false);
});
test('engraving text edits require the selected real writable field and keep raw text private',async t=>{
  const f=fixture(t);assert.equal(f.instance.capabilities.actions.includes('set-engraving'),false);assert.equal((await f.run({type:'set-engraving',handle:'test-leaf',text:'PRIVATE_NEW_TEXT'})).ok,false);assert.equal(f.d.querySelector('#bjEngrTxt').value,'PRIVATE_OLD_TEXT');
  await f.run({type:'select-option',handle:'test-leaf',optionName:'Engraving',optionValue:'Engraved'});assert.equal(f.instance.capabilities.actions.includes('set-engraving'),true);const r=await f.run({type:'set-engraving',handle:'test-leaf',text:'PRIVATE <3 EVA'});assert.equal(r.ok,true);assert.equal(f.d.querySelector('#bjEngrTxt').value,'PRIVATE <3 EVA');assert.equal(r.snapshot.engravingControls.enabled,true);assert.equal(r.snapshot.engravingControls.hasText,true);assert.equal(r.snapshot.engravingControls.maxLength,20);assert.doesNotMatch(JSON.stringify(r),/PRIVATE|<3 EVA/);assert.equal(f.calls.length,0);assert.equal(f.adds,0);assert.deepEqual(f.privateEvents.map(e=>e.event),['input','change']);assert.equal((await f.run({type:'undo'})).ok,true);assert.equal(f.d.querySelector('#bjEngrTxt').value,'PRIVATE_OLD_TEXT');assert.equal(f.d.querySelector('#bjEngrChk').checked,true);
});
test('engraving text cannot exceed the merchant limit or toggle engraving on by itself',async t=>{const f=fixture(t,{maxLength:8});await f.run({type:'select-option',handle:'test-leaf',optionName:'Engraving',optionValue:'Engraved'});for(const text of ['x'.repeat(9),'hidden\u0000text','hidden\u202etext'])assert.equal((await f.run({type:'set-engraving',handle:'test-leaf',text})).ok,false);assert.equal(f.d.querySelector('#bjEngrTxt').value,'PRIVATE_OLD_TEXT');f.d.querySelector('#bjEngrTxt').readOnly=true;assert.equal(f.instance.capabilities.actions.includes('set-engraving'),false);});
test('missing and duplicate engraving fields never expose a fabricated editing capability',async t=>{const f=fixture(t,{engraving:false});await f.run({type:'select-option',handle:'test-leaf',optionName:'Engraving',optionValue:'Engraved'});assert.equal(f.instance.capabilities.actions.includes('set-engraving'),false);const input=f.d.createElement('input');input.id='bjEngrTxt';input.type='text';f.d.querySelector('#bjEngr').append(input,input.cloneNode());assert.equal(f.instance.capabilities.actions.includes('set-engraving'),false);});
test('private nonempty text changes still invalidate native request context without projecting the value',async t=>{const f=fixture(t);await f.run({type:'select-option',handle:'test-leaf',optionName:'Engraving',optionValue:'Engraved'});const before=f.instance.snapshot(),field=f.d.querySelector('#bjEngrTxt');field.value='PRIVATE_EDIT';field.dispatchEvent(new f.w.Event('input',{bubbles:true}));const after=f.instance.snapshot();assert(after.contextRevision>before.contextRevision);assert.doesNotMatch(JSON.stringify(after),/PRIVATE_EDIT/);});
test('actual gift form fields receive exact literal values through native events with truthful persistence limits',async t=>{
  const f=fixture(t,{cart:true});await f.instance.refresh();assert.equal(f.instance.capabilities.notesMode,'native-form');const r=await f.run({type:'gift-preferences',wrapping:true,giftNote:'PRIVATE <3 GIFT'});assert.equal(r.ok,true);assert.equal(f.d.querySelector('#gift-wrapping').checked,true);assert.equal(f.d.querySelector('#gift-note').value,'PRIVATE <3 GIFT');assert.equal(r.snapshot.giftControls.wrapping,true);assert.equal(r.snapshot.giftControls.savedKnown,false);assert.doesNotMatch(JSON.stringify(r),/PRIVATE|<3 GIFT/);assert(f.calls.every(call=>call.options.method==='GET'));assert.equal(f.nav.length,0);assert.equal((await f.run({type:'undo'})).ok,true);assert.equal(f.d.querySelector('#gift-wrapping').checked,false);assert.equal(f.d.querySelector('#gift-note').value,'PRIVATE_OLD_NOTE');
});
test('unsupported gift package or changed property bindings reject the whole request before any toggle',async t=>{const f=fixture(t,{cart:true});for(const action of [{type:'gift-preferences',wrapping:true,giftPackage:true},{type:'gift-preferences',wrapping:true,giftNote:'x'.repeat(31)}])assert.equal((await f.run(action)).ok,false);assert.equal(f.d.querySelector('#gift-wrapping').checked,false);f.d.querySelector('#gift-note').name='attributes[unrelated]';assert.equal((await f.run({type:'gift-preferences',wrapping:true,giftNote:'Hello'})).ok,false);assert.equal(f.d.querySelector('#gift-wrapping').checked,false);});
test('undoing real cart quantity preserves its stable line and private properties using existing handlers and fresh checks',async t=>{const f=fixture(t,{cart:true});await f.instance.refresh();assert.equal((await f.run({type:'bag-quantity',lineId:'3901:exact',quantity:4})).ok,true);assert.equal(f.instance.snapshot().changeControls.kind,'bag-quantity');const r=await f.run({type:'undo'});assert.equal(r.ok,true,r.reason);assert.equal(f.state.cart.items[0].quantity,2);assert.deepEqual(f.state.cart.items[0].properties,{Engraving:'PRIVATE_CART_TEXT'});assert.equal(f.state.cart.items[0].key,'3901:exact');assert(f.calls.every(call=>call.options.method==='GET'));assert.doesNotMatch(JSON.stringify(r),/PRIVATE/);});
test('native cart removal cannot offer an undo that would re-add a line without its exact properties',async t=>{const f=fixture(t,{cart:true});await f.instance.refresh();await f.run({type:'bag-quantity',lineId:'3901:exact',quantity:3});assert.equal((await f.run({type:'bag-remove',lineId:'3901:exact'})).ok,true);assert.equal(f.instance.snapshot().changeControls.canUndo,false);assert.equal((await f.run({type:'undo'})).ok,false);assert.deepEqual(f.state.cart.items,[]);assert(f.calls.every(call=>call.options.method==='GET'));});
test('the shared current-request bridge edits detected native gift fields and redacts its action result',async t=>{const f=fixture(t,{cart:true});await f.instance.refresh();const bridge=Bridge.create({storefront:f.instance});t.after(()=>bridge.destroy());const intent=bridge.resolve('Save my gift note PRIVATE_NEW_GIFT');assert.equal(intent.ok,true,intent.reason);const r=await bridge.execute(intent.action,{requestId:'real-gift-request'});assert.equal(r.ok,true,r.reason);assert.equal(f.d.querySelector('#gift-note').value,'PRIVATE_NEW_GIFT');assert.equal(r.snapshot.giftControls.noteAvailable,true);assert.equal(r.snapshot.giftControls.savedKnown,false);assert.doesNotMatch(JSON.stringify(r),/PRIVATE_NEW_GIFT|giftNote/);assert(f.calls.every(call=>call.options.method==='GET'));});
test('the shared bridge fills native engraving and rejects an older request after a private manual edit',async t=>{
  const f=fixture(t);await f.run({type:'select-option',handle:'test-leaf',optionName:'Engraving',optionValue:'Engraved'});const bridge=Bridge.create({storefront:f.instance});t.after(()=>bridge.destroy());let intent=bridge.resolve('Set engraving text to PRIVATE_NEW');assert.equal(intent.ok,true,intent.reason);let r=await bridge.execute(intent.action,{requestId:'native-engraving-request'});assert.equal(r.ok,true,r.reason);assert.equal(f.d.querySelector('#bjEngrTxt').value,'PRIVATE_NEW');assert.doesNotMatch(JSON.stringify(r),/PRIVATE_NEW/);
  intent=bridge.resolve('Set engraving text to PRIVATE_NEXT');const input=f.d.querySelector('#bjEngrTxt');input.value='PRIVATE_MANUAL';input.dispatchEvent(new f.w.Event('input',{bubbles:true}));r=await bridge.execute(intent.action,{requestId:'stale-native-engraving-request'});assert.equal(r.ok,false);assert.equal(r.stale,true);assert.equal(input.value,'PRIVATE_MANUAL');assert.equal(f.adds,0);
});
test('silent native theme or autofill text changes invalidate older engraving and gift requests without projecting private values',async t=>{
  for(const cart of [false,true]){const f=fixture(t,{cart});if(cart)await f.instance.refresh();else{const check=f.d.querySelector('#bjEngrChk');check.checked=true;check.dispatchEvent(new f.w.Event('change',{bubbles:true}));}assert.equal(f.instance.snapshot().changeControls.canUndo,false);const bridge=Bridge.create({storefront:f.instance});t.after(()=>bridge.destroy());const intent=bridge.resolve(cart?'Set my gift note to PRIVATE_REQUESTED':'Set engraving text to PRIVATE_REQUESTED');assert.equal(intent.ok,true,intent.reason);const before=f.instance.snapshot().contextRevision,field=f.d.querySelector(cart?'#gift-note':'#bjEngrTxt');field.value='PRIVATE_NEWER';const fresh=f.instance.snapshot();assert(fresh.contextRevision>before);assert.doesNotMatch(JSON.stringify(fresh),/PRIVATE_NEWER|PRIVATE_REQUESTED/);const r=await bridge.execute(intent.action,{requestId:cart?'autofill-gift':'autofill-engraving'});assert.equal(r.ok,false);assert.equal(r.stale,true);assert.equal(field.value,'PRIVATE_NEWER');assert.doesNotMatch(JSON.stringify(r),/PRIVATE_NEWER|PRIVATE_REQUESTED/);assert(f.calls.every(call=>call.options.method==='GET'));assert.equal(f.adds,0);}
});
test('native full-page navigation disables the old product controls before another command can use them',async t=>{const f=fixture(t);f.d.querySelector('main').insertAdjacentHTML('beforeend','<a class="bjc-pcard" href="/products/test-other"><span class="bjc-t">Test Other Necklace</span></a>');const r=await f.run({type:'open',handle:'test-other'});assert.equal(r.ok,true);assert.equal(r.navigationRequested,true);assert.equal(r.snapshot.loading,true);assert.equal(r.snapshot.currentHandle,'');assert.equal(r.snapshot.productControls,null);assert.deepEqual(f.instance.capabilities.actions,[]);assert.equal((await f.run({type:'product-quantity',handle:'test-leaf',quantity:5})).ok,false);assert.equal(f.quantity,1);assert.deepEqual(f.nav,['https://britesjewelry.com/products/test-other']);});
test('a shared plan cannot open a new native page and then change the previous product',async t=>{const f=fixture(t);f.d.querySelector('main').insertAdjacentHTML('beforeend','<a class="bjc-pcard" href="/products/test-other"><span class="bjc-t">Test Other Necklace</span></a>');const bridge=Bridge.create({storefront:f.instance});t.after(()=>bridge.destroy());const p=bridge.resolvePlan('Open Test Other Necklace then select Gold Filled');assert.equal(p.ok,true);const r=await bridge.executePlan(p.plan,{requestId:'native-page-sequence'});assert.equal(r.ok,false);assert.equal(r.partial,true);assert.deepEqual(r.completedActions,[{type:'open',handle:'test-other'}]);assert.equal(f.d.querySelector('#bjMetals .on').textContent,'Sterling Silver');assert.equal(f.adds,0);assert.deepEqual(f.nav,['https://britesjewelry.com/products/test-other']);});
const historyKey='brites:storefront-history:v1:/',historyStateKey='__britesStorefrontJourneyV1';
const savedHistory=f=>JSON.parse(f.w.sessionStorage.getItem(historyKey));
async function twoNativePages(t){
  const a=fixture(t,{historyState:{theme:{tab:'details'},scroll:120}}),aState=clone(a.w.history.state);await a.run({type:'bag'});
  const b=fixture(t,{cart:true,historyLength:2,savedJourney:savedHistory(a),referrer:a.w.location.href});return {a,b,aState};
}
test('browser Back preserves the forward entry and avatar Forward traverses native history without inserting a new page',async t=>{
  const {a,b,aState}=await twoNativePages(t),back=fixture(t,{savedJourney:savedHistory(b),historyState:aState,historyLength:2}),moves=[];back.w.history.go=delta=>moves.push(delta);
  assert.deepEqual(back.instance.snapshot().navigationControls,{canGoBack:false,canGoForward:true});assert.deepEqual(savedHistory(back).entries,[a.w.location.href,b.w.location.href]);assert.equal(savedHistory(back).index,0);assert.deepEqual(back.w.history.state.theme,{tab:'details'});assert.equal(back.w.history.state.scroll,120);
  const r=await back.run({type:'forward'});assert.equal(r.ok,true,r.reason);assert.equal(r.navigationRequested,true);assert.equal(r.snapshot.loading,true);assert.deepEqual(moves,[1]);assert.deepEqual(back.nav,[]);assert.equal(back.w.history.state[historyStateKey].key,aState[historyStateKey].key);assert.equal(savedHistory(back).index,1);assert.equal((await back.run({type:'back'})).ok,false);assert.equal(back.calls.length,0);
});
test('avatar Back traverses the exact bound previous browser entry and does not call location.assign',async t=>{
  const {b}=await twoNativePages(t),moves=[];b.w.history.go=delta=>moves.push(delta);assert.deepEqual(b.instance.snapshot().navigationControls,{canGoBack:true,canGoForward:false});
  const r=await b.run({type:'back'});assert.equal(r.ok,true,r.reason);assert.deepEqual(moves,[-1]);assert.deepEqual(b.nav,[]);assert.equal(savedHistory(b).index,0);assert.equal(b.w.history.state[historyStateKey].url,b.w.location.href);assert.equal(b.calls.length,0);
});
test('BFCache restoration clears the old full-page handoff and preserves native choices plus forward history',async t=>{
  const a=fixture(t);await a.run({type:'select-option',handle:'test-leaf',optionName:'Metal Choice',optionValue:'Gold Filled'});await a.run({type:'product-quantity',handle:'test-leaf',quantity:3});await a.run({type:'bag'});
  const b=fixture(t,{cart:true,historyLength:2,savedJourney:savedHistory(a),referrer:a.w.location.href});a.w.sessionStorage.setItem(historyKey,JSON.stringify(savedHistory(b)));Object.defineProperty(a.w.history,'length',{configurable:true,value:2});a.w.dispatchEvent(new a.w.PageTransitionEvent('pageshow',{persisted:true}));
  const snap=a.instance.snapshot();assert.equal(snap.loading,false);assert.equal(snap.currentHandle,'test-leaf');assert.equal(snap.productControls.quantity,3);assert.equal(snap.productControls.selectedVariant.options[0].value,'Gold Filled');assert.deepEqual(snap.navigationControls,{canGoBack:false,canGoForward:true});assert.equal(snap.changeControls.canUndo,false);assert(a.instance.capabilities.actions.includes('product-quantity'));assert.equal((await a.run({type:'product-quantity',handle:'test-leaf',quantity:2})).ok,true);assert.equal(a.quantity,2);assert.equal(a.adds,0);
});
test('popstate reconciles the restored entry key instead of appending the earlier URL to the end',async t=>{
  const {a,b}=await twoNativePages(t);a.w.sessionStorage.setItem(historyKey,JSON.stringify(savedHistory(b)));Object.defineProperty(a.w.history,'length',{configurable:true,value:2});a.w.dispatchEvent(new a.w.PopStateEvent('popstate',{state:a.w.history.state}));
  assert.equal(a.instance.snapshot().loading,false);assert.deepEqual(a.instance.snapshot().navigationControls,{canGoBack:false,canGoForward:true});assert.deepEqual(savedHistory(a).entries,[a.w.location.href,b.w.location.href]);assert.equal(savedHistory(a).index,0);assert.equal(a.calls.length,0);
});
test('native same-origin link arrival extends only the checked immediate browser entry',async t=>{
  const a=fixture(t),b=fixture(t,{cart:true,historyLength:2,savedJourney:savedHistory(a),referrer:a.w.location.href});assert.deepEqual(savedHistory(b).entries,[a.w.location.href,b.w.location.href]);assert.equal(b.instance.snapshot().navigationControls.canGoBack,true);
  const outside=fixture(t,{cart:true,historyLength:3,savedJourney:savedHistory(a),referrer:'https://outside.example/intervening'});assert.deepEqual(outside.instance.snapshot().navigationControls,{canGoBack:false,canGoForward:false});assert.deepEqual(savedHistory(outside).entries,[outside.w.location.href]);
});
test('a stale predicted navigation or unknown restored marker cannot authorize guessed native traversal',async t=>{
  const {a,b,aState}=await twoNativePages(t),stale=fixture(t,{cart:true,historyLength:4,savedJourney:savedHistory(a),referrer:a.w.location.href});assert.deepEqual(stale.instance.snapshot().navigationControls,{canGoBack:false,canGoForward:false});
  aState[historyStateKey].key='shop-view-unknown';const unknown=fixture(t,{historyLength:2,savedJourney:savedHistory(b),historyState:aState});assert.deepEqual(unknown.instance.snapshot().navigationControls,{canGoBack:false,canGoForward:false});assert.equal((await unknown.run({type:'back'})).ok,false);assert.deepEqual(unknown.nav,[]);assert.deepEqual(unknown.w.history.state.theme,{tab:'details'});
  b.w.history.replaceState({theme:{tab:'newer'},[historyStateKey]:{key:'shop-view-corrupt',url:b.w.location.href}},'');assert.deepEqual(b.instance.snapshot().navigationControls,{canGoBack:false,canGoForward:false});assert.equal((await b.run({type:'back'})).ok,false);
});
test('legacy unbound URL ledgers and primitive theme history state cannot fabricate browser destinations',async t=>{
  const legacy={entries:['https://britesjewelry.com/products/test-leaf','https://britesjewelry.com/cart'],index:1},f=fixture(t,{savedJourney:legacy});assert.deepEqual(f.instance.snapshot().navigationControls,{canGoBack:false,canGoForward:false});assert.deepEqual(savedHistory(f).entries,[f.w.location.href]);
  for(const historyState of [7,['theme','tab']]){const locked=fixture(t,{historyState,savedJourney:savedHistory(f)});assert.deepEqual(locked.w.history.state,historyState);assert.deepEqual(locked.instance.snapshot().navigationControls,{canGoBack:false,canGoForward:false});assert.equal((await locked.run({type:'back'})).ok,false);}
});
test('failed native history traversal keeps the mounted page available and its checked direction intact',async t=>{
  const {b}=await twoNativePages(t);b.w.history.go=()=>{throw Error('Native traversal unavailable');};const r=await b.run({type:'back'});assert.equal(r.ok,false);assert.match(r.reason,/Native traversal unavailable/);assert.equal(b.instance.snapshot().loading,false);assert.equal(b.instance.snapshot().navigationControls.canGoBack,true);assert.equal(savedHistory(b).index,1);assert.deepEqual(b.nav,[]);
});
