'use strict';
// Current final-word authority against synthetic host snapshots. No provider,
// microphone, real cart, payment, private research or account state is accessed.
const test=require('node:test'),assert=require('node:assert/strict');
const bridge=require('../../brites-storefront-bridge.js');
const client=require('../../brites-concierge-voice.js');
const server=require('../../netlify/functions/_britesConciergeVoice.js');
const voiceActions=require('../../brites-concierge-voice-actions.js');
const widget=require('../../brites-concierge.js');
const orchid={id:'gid://shopify/Product/7301',handle:'orchid-stud-earrings',title:'Orchid Stud Earrings'};
const compass={id:'gid://shopify/Product/7302',handle:'compass-pendant',title:'Compass Pendant'};
const variantId='gid://shopify/ProductVariant/7311';
const actions=['search','sort','filter','open','highlight','zoom','scroll','bag','checkout','gift','customize','options','select-option','product-quantity','review-add','bag-quantity','bag-remove','gift-preferences','checkout-step','checkout-option','checkout-complete'];
const capabilities={controlVersion:1,actions,mode:'sandbox',reviewBeforeAdd:true,finalOrder:false,checkoutMode:'simulation-only',notesMode:'local-session'};
const controls={handle:orchid.handle,productId:orchid.id,variantId,quantity:1,optionsOpen:false,openedOption:null,optionGroups:[{name:'Metal',values:['Sterling Silver','Gold Plated']},{name:'Length',values:['16 inch','18 inch']}],selectedOptions:[{name:'Metal',value:'Sterling Silver'},{name:'Length',value:'16 inch'}],reviewReady:false};
const line={lineId:'7311:fixture-hash',productId:orchid.id,variantId,quantity:1,title:orchid.title,variant:'Sterling Silver / 16 inch'};
const page={controlVersion:1,contextRevision:34,discoveryRevision:9,pageKind:'product',currentHandle:orchid.handle,focusedHandle:'',visiblePieces:[orchid],loadedPieces:[orchid,compass],productControls:controls,bagControls:{lines:[line],itemCount:1},checkoutControls:{step:null,shipping:'standard',acknowledged:false,complete:false}};
const clone=v=>structuredClone(v);
function harness(next=page,manifest=capabilities){let current=clone(next);const calls=[];const host={capabilities:clone(manifest),snapshot:()=>current,execute:async(action,options)=>{calls.push({action,options});return {ok:true,message:'The checked test control was updated.',cartChanged:['bag-quantity','bag-remove'].includes(action.type)};}};const api=bridge.create({storefront:host});return {api,host,calls,set:value=>current={...current,...clone(value)}};}
const checks=[
 ['Open Compass Pendant',{type:'open',handle:compass.handle}],
 ['Set quantity to 2',{type:'product-quantity',handle:orchid.handle,quantity:2}],
 ['Please change the quantity to 20',{type:'product-quantity',handle:orchid.handle,quantity:20}],
 ['Set Orchid Stud Earrings quantity to 3',{type:'product-quantity',handle:orchid.handle,quantity:3}],
 ['Show the options',{type:'options',handle:orchid.handle}],
 ['Open the metal dropdown',{type:'options',handle:orchid.handle,optionName:'Metal'}],
 ['Expand the Length selector',{type:'options',handle:orchid.handle,optionName:'Length'}],
 ['Select Sterling Silver',{type:'select-option',handle:orchid.handle,optionName:'Metal',optionValue:'Sterling Silver'}],
 ['Choose 18 inch',{type:'select-option',handle:orchid.handle,optionName:'Length',optionValue:'18 inch'}],
 ['Set Metal to Gold Plated',{type:'select-option',handle:orchid.handle,optionName:'Metal',optionValue:'Gold Plated'}],
 ['Please choose sterling silver',{type:'select-option',handle:orchid.handle,optionName:'Metal',optionValue:'Sterling Silver'}],
 ['Add this piece to my bag',{type:'review-add',handle:orchid.handle,variantId}],
 ['Review adding to bag',{type:'review-add',handle:orchid.handle,variantId}],
 ['Set bag quantity to 3',{type:'bag-quantity',lineId:line.lineId,quantity:3}],
 ['Remove Orchid Stud Earrings from my bag',{type:'bag-remove',lineId:line.lineId}],
 ['Enable gift wrapping',{type:'gift-preferences',wrapping:true}],
 ['Remove gift wrapping',{type:'gift-preferences',wrapping:false}],
 ['Choose gift packaging',{type:'gift-preferences',giftPackage:true}],
 ['Turn off gift package',{type:'gift-preferences',giftPackage:false}],
 ['Set gift note to Happy Birthday, Ana!',{type:'gift-preferences',giftNote:'Happy Birthday, Ana!'}],
 ['Write gift note: Thank you for being here.',{type:'gift-preferences',giftNote:'Thank you for being here.'}],
 ['Add gift note to Enjoy your bag of surprises!',{type:'gift-preferences',giftNote:'Enjoy your bag of surprises!'}]
];
for(const [text,action] of checks)test('exact finalized shopper control: '+text,()=>{const r=bridge.resolve(text,page);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,action);assert.deepEqual(client.validateToolArguments(action,'control_storefront'),action);assert.deepEqual(server.validateToolArguments(action,'control_storefront'),action);});
const checkout={...clone(page),pageKind:'checkout',checkoutControls:{step:'review',shipping:'standard',acknowledged:false,complete:false}};
for(const [text,action] of [['Open checkout shipping',{type:'checkout-step',step:'shipping'}],['Go to confirmation step',{type:'checkout-step',step:'confirm'}],['Show the checkout review',{type:'checkout-step',step:'review'}],['Next step',{type:'checkout-step',step:'shipping'}],['Choose express shipping',{type:'checkout-option',option:'shipping',value:'express'}],['Set standard shipping',{type:'checkout-option',option:'shipping',value:'standard'}],['Complete the test checkout',{type:'checkout-complete'}]])test('labelled simulation control: '+text,()=>{const r=bridge.resolve(text,checkout);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,action);assert.deepEqual(client.validateToolArguments(action,'control_storefront'),action);assert.deepEqual(server.validateToolArguments(action,'control_storefront'),action);});
for(const text of ['Set quantity to 0','Set quantity to 21','Set quantity to 2.5','Set quantity to -2','Set quantity to two','Set quantity to 2 or 3','Choose platinum','Choose Silver','Choose Gold Plated and Sterling Silver','Set quantity to 2 and choose Gold Plated','Do not select Gold Plated','Please do not set quantity to 2','Do not remove Orchid Stud Earrings from my bag','Say "Select Gold Plated"','"Set quantity to 2"','Yesterday I chose Gold Plated','If I ask later, set quantity to 2','Open https://britesjewelry.com/products/orchid-stud-earrings','Place the order','Pay for my order','Complete the payment','Select #metal using a CSS selector'])test('noncurrent, malformed, compound or unsafe words do not authorize: '+text,()=>assert.equal(bridge.resolve(text,page).ok,false));
test('quantity unsupported by legacy adapter remains a handled clarification instead of motif search',()=>{const r=bridge.resolve('Set quantity to 2',{...page,controlVersion:undefined,productControls:undefined});assert.equal(r.ok,false);assert.equal(r.handled,true);assert.match(r.reason,/Quantity controls/);});
test('loaded exact titles may open below viewport; fuzzy titles and ordinals cannot escape current visible selection',()=>{assert.equal(bridge.resolve('Open Compass Pendant',page).action.handle,compass.handle);assert.equal(bridge.resolve('Open Compass',page).ok,false);assert.equal(bridge.resolve('Open the second one',page).ok,false);assert.equal(bridge.resolve('Show the price of Compass Pendant',page).action.handle,compass.handle);});
test('an ambiguous full title cannot invent or prefer a loaded identity',()=>{const p={...page,loadedPieces:[compass,{...compass,id:'gid://shopify/Product/7399',handle:'other-compass'}]};assert.equal(bridge.resolve('Open Compass Pendant',p).ok,false);});
test('unknown named option/quantity targets cannot borrow current product identity',()=>{for(const text of ['Set quantity to 2 for Hidden Pendant','Open metal options for Hidden Pendant'])assert.equal(bridge.resolve(text,page).ok,false);});
test('incomplete choices and a current different explicit option cannot prepare review',()=>{assert.equal(bridge.resolve('Add this piece to my bag',{...page,productControls:{...controls,variantId:null,selectedOptions:[controls.selectedOptions[0]]}}).ok,false);assert.equal(bridge.resolve('Add Gold Plated to my bag',page).ok,false);});
test('matching bag titles with different options require an exact line choice, never first-row substitution',()=>{const other={...line,lineId:'7312:other-fixture',variantId:'gid://shopify/ProductVariant/7312',variant:'Gold Plated / 16 inch'},p={...page,pageKind:'bag',bagControls:{lines:[line,other]}};assert.equal(bridge.resolve('Remove Orchid Stud Earrings from my bag',p).ok,false);assert.equal(bridge.resolve('Remove Orchid Stud Earrings Gold Plated / 16 inch from my bag',p).action.lineId,other.lineId);assert.equal(bridge.resolve('Remove the second item from my bag',p).action.lineId,other.lineId);});
test('gift note remains exact bounded data and never projected into context',()=>{const r=bridge.resolve('Set gift note to Happy Birthday, Ana!',page);const projected=bridge.sanitizeSnapshot({...page,giftNote:r.action.giftNote,productControls:{...controls,note:r.action.giftNote},bagControls:{lines:[{...line,properties:{note:r.action.giftNote}}]}});assert.doesNotMatch(JSON.stringify(projected),/Birthday|properties|note/);assert.equal(bridge.resolve('Set gift note to '+('x'.repeat(301)),page).ok,false);});
const invalid=[{type:'select-option',handle:orchid.handle},{type:'select-option',handle:orchid.handle,variantId,optionName:'Metal',optionValue:'Gold Plated'},{type:'product-quantity',handle:orchid.handle,quantity:'2'},{type:'product-quantity',handle:orchid.handle,quantity:2.5},{type:'product-quantity',handle:orchid.handle,quantity:21},{type:'bag-remove',lineId:'../admin'},{type:'bag-remove',lineId:line.lineId,confirm:true},{type:'gift-preferences'},{type:'gift-preferences',giftNote:'x'.repeat(301)},{type:'gift-preferences',wrapping:'true'},{type:'checkout-step',step:'payment'},{type:'checkout-option',option:'shipping',value:'overnight'},{type:'checkout-complete',payment:true},{type:'review-add',handle:orchid.handle,quantity:3},{type:'options',handle:orchid.handle,selector:'#private'},{type:'select-option',handle:orchid.handle,optionName:'Metal',optionValue:'x\u0000y'}];
for(const action of invalid)test('client/server/bridge strict field contract rejects '+JSON.stringify(action),()=>{for(const api of [client,server])assert.equal(api.validateToolArguments(action,'control_storefront'),null);assert.equal(bridge.validateAction(action),null);});
for(const [text,action] of checks.slice(0,15))test('typed and finalized native parity: '+text,async()=>{for(const native of [false,true]){const h=harness(),opts=native?{transcript:text,context:page,currentTurn:true,inputItemId:'fixture-input',turnVersion:3,source:'native'}:{transcript:text,context:page,source:'typed',requestId:'fixture-'+text};const r=await h.api.execute(action,opts);assert.equal(r.ok,true,r.reason);assert.equal(h.calls.length,1);assert.deepEqual(h.calls[0].action,action);assert.equal(h.calls[0].options.signal.aborted,false);}});
test('a model-selected variant or option cannot self-authorize mismatching finalized words',async()=>{const h=harness();for(const action of [{type:'select-option',handle:orchid.handle,variantId},{type:'select-option',handle:orchid.handle,optionName:'Metal',optionValue:'Gold Plated'},{type:'product-quantity',handle:orchid.handle,quantity:3}]){const r=await h.api.execute(action,{transcript:action.type==='product-quantity'?'Set quantity to 2':'Choose Sterling Silver',context:page,currentTurn:true,inputItemId:'fixture-input',turnVersion:3});assert.equal(r.ok,false);}assert.equal(h.calls.length,0);});
test('stable bag controls and exact choice controls reject revision changes and silent same-revision drift',async()=>{for(const change of [{contextRevision:35},{productControls:{...controls,quantity:2}},{bagControls:{lines:[],itemCount:0}}]){const h=harness(),r=h.api.resolve('Set quantity to 2');h.set(change);assert.equal((await h.api.execute(r.action)).stale,true);assert.equal(h.calls.length,0);}});
test('new native actions require current exact committed authority and cannot replay',async()=>{const h=harness(),action={type:'product-quantity',handle:orchid.handle,quantity:2},opts={transcript:'Set quantity to 2',context:page,currentTurn:true,inputItemId:'fixture-input',turnVersion:3};for(const bad of [{currentTurn:false},{inputItemId:''},{turnVersion:-1}])assert.equal((await h.api.execute(action,{...opts,...bad})).ok,false);assert.equal((await h.api.execute(action,opts)).ok,true);assert.equal((await h.api.execute(action,opts)).suppressed,true);assert.equal(h.calls.length,1);});
test('unsupported adapter capability fails before host execution or consuming a fresh request',async()=>{const h=harness(page,{...capabilities,actions:actions.filter(a=>a!=='product-quantity')}),action={type:'product-quantity',handle:orchid.handle,quantity:2},opts={transcript:'Set quantity to 2',context:page,requestId:'fixture-capability'};assert.equal((await h.api.execute(action,opts)).ok,false);assert.equal(h.calls.length,0);h.host.capabilities=capabilities;assert.equal((await h.api.execute(action,opts)).ok,true);});
test('production adapter cannot acquire simulated final checkout or private notes by declaring arbitrary actions',async()=>{for(const [text,action] of [['Complete the test checkout',{type:'checkout-complete'}],['Set gift note to Hello',{type:'gift-preferences',giftNote:'Hello'}]]){const h=harness(checkout,{...capabilities,mode:'shopify',checkoutMode:'simulation-only',notesMode:'unsupported',finalOrder:true});assert.equal((await h.api.execute(action,{transcript:text,context:checkout,requestId:'fixture-final'})).ok,false);assert.equal(h.calls.length,0);}});
test('review authority travels only as internal opaque metadata and prepares no automatic add',async()=>{const h=harness(),token=Object.freeze({}),r=await h.api.execute({type:'review-add',handle:orchid.handle,variantId},{transcript:'Add this piece to my bag',context:page,requestId:'fixture-review',reviewAuthority:token});assert.equal(r.ok,true);assert.equal(h.calls[0].options.reviewAuthority,token);assert.equal('reviewAuthority' in h.calls[0].action,false);assert.equal(r.cartChanged,undefined);assert.equal(h.calls[0].action.type,'review-add');});
test('host-observed cart mutation is reported only for exact bag edits',async()=>{const h=harness(),r=await h.api.execute({type:'bag-quantity',lineId:line.lineId,quantity:3},{transcript:'Set bag quantity to 3',context:page,requestId:'fixture-bag'});assert.equal(r.ok,true);assert.equal(r.cartChanged,true);});
test('shared helper accepts only finalized current-turn storefront intent, never a model action alone',()=>{assert.equal(voiceActions.resolveStorefrontRequest({message:'Set quantity to 2',context:page,currentTurn:false},bridge).ok,false);assert.deepEqual(voiceActions.resolveStorefrontRequest({message:'Set quantity to 2',context:page,currentTurn:true},bridge).action,{type:'product-quantity',handle:orchid.handle,quantity:2});});
test('native public context retains safe literal choices and stable lines, drops private note and authority data',()=>{const r=client.publicContext({...page,displayedPieces:[],giftNote:'PRIVATE_NOTE_FIXTURE',reviewAuthority:{private:'secret'},productControls:{...controls,giftNote:'PRIVATE_NOTE_FIXTURE'},bagControls:{lines:[{...line,properties:{private:'PRIVATE_NOTE_FIXTURE'}}]}});assert.equal(r.controlVersion,1);assert.equal(r.loadedPieces.length,2);assert.deepEqual(r.productControls.selectedOptions,controls.selectedOptions);assert.equal(r.bagControls.lines[0].lineId,line.lineId);assert.equal(r.checkoutControls.shipping,'standard');assert.doesNotMatch(JSON.stringify(r),/PRIVATE_NOTE_FIXTURE|secret|properties|reviewAuthority|giftNote/);});
test('maximal multibyte native context remains bounded and marks partial identities/options',()=>{const title='珠'.repeat(300),r=client.publicContext({...page,loadedPieces:Array.from({length:200},(_,n)=>({id:'gid://shopify/Product/'+(8000+n),handle:'fixture-piece-'+n,title})),productControls:{...controls,optionGroups:Array.from({length:12},(_,g)=>({name:'Group '+g,values:Array.from({length:60},(_,v)=>'玉'.repeat(299)+v)}))},bagControls:{lines:Array.from({length:50},(_,n)=>({...line,lineId:'fixture-'+n,title}))}});assert.ok(Buffer.byteLength(JSON.stringify(r),'utf8')<=18000);assert.ok(r.loadedPiecesTruncated||r.contextTruncated);assert.doesNotMatch(JSON.stringify(r),/giftNote|properties/);});
test('bounded confirmed production cart quantity uses exact current stock and unique marker, never blindly retries',async()=>{const v={id:variantId,numericId:'7311',title:'Sterling Silver',price:44,available:true,options:[{name:'Metal',value:'Sterling Silver'}]},p={...orchid,url:'https://britesjewelry.com/products/'+orchid.handle,currency:'USD',minPrice:44,variants:[v],variantsComplete:true};const calls=[];let reads=0;const fetch=async(url,init={})=>{calls.push({url,init});const body=url.endsWith('cart.js')?{currency:'USD',items:reads++?[{variant_id:7311,quantity:3,properties:{_BritesConciergeRequest:'fixture_quantity_123456'}}]:[]}:url.includes('/products/')?{variants:[{id:7311,price:4400,available:true}]}:{items:[]};return {ok:true,json:async()=>body};};const r=await widget.verifiedCartAdd({fetch,product:p,variant:v,quantity:3,requestId:'fixture_quantity_123456'});assert.equal(r.confirmed,true);assert.equal(JSON.parse(calls.find(c=>c.init.method==='POST').init.body).items[0].quantity,3);assert.equal(calls.filter(c=>c.init.method==='POST').length,1);});
test('malformed cart quantity rejects before reads/writes',async()=>{for(const quantity of [0,21,1.5,'2']){let calls=0;await assert.rejects(widget.verifiedCartAdd({fetch:async()=>{calls++;},quantity}),/whole quantity/);assert.equal(calls,0);}});

// Browser-observed Rhino title/group/values regression. IDs and quantities here
// are synthetic; these tests never claim current stock or call the storefront.
const rhinoFixture={id:'gid://shopify/Product/7401',handle:'rhino-profile-stud-earrings',title:'Rhino Profile Stud Earrings'};
const rhinoControls={...clone(controls),handle:rhinoFixture.handle,productId:rhinoFixture.id,variantId:'gid://shopify/ProductVariant/7411',quantity:2,optionGroups:[{name:'Metal Choice',values:['Sterling Silver','14k Gold Filled','14k Rose Gold Filled','10k Solid Gold','14k Solid Gold']}],selectedOptions:[{name:'Metal Choice',value:'14k Gold Filled'}]};
const rhinoPage={...clone(page),currentHandle:rhinoFixture.handle,visiblePieces:[rhinoFixture],loadedPieces:[rhinoFixture],productControls:rhinoControls};
for(const text of ['Open metal options','Open material options','Open metals menu','Show the material dropdown','Open Metal Choice options'])test('actual published Metal Choice label resolves unique natural alias: '+text,()=>{const r=bridge.resolve(text,rhinoPage);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,{type:'options',handle:rhinoFixture.handle,optionName:'Metal Choice'});});
for(const text of ['Select material Sterling Silver','Choose metal 14k Gold Filled','Select 14k Rose Gold Filled'])test('natural metal alias retains actual literal published value: '+text,()=>{const r=bridge.resolve(text,rhinoPage);assert.equal(r.ok,true,r.reason);assert.equal(r.action.type,'select-option');assert.equal(r.action.optionName,'Metal Choice');assert.ok(rhinoControls.optionGroups[0].values.includes(r.action.optionValue));assert.equal(rhinoPage.productControls.quantity,2);assert.deepEqual(rhinoPage.productControls.selectedOptions,[{name:'Metal Choice',value:'14k Gold Filled'}]);});
for(const second of ['Metal','Material','Finish'])test('multiple published metal-family groups cannot select a generic alias: '+second,()=>{const p={...clone(rhinoPage),productControls:{...clone(rhinoControls),optionGroups:[...clone(rhinoControls.optionGroups),{name:second,values:['Oxidized']}],selectedOptions:[...clone(rhinoControls.selectedOptions),{name:second,value:'Oxidized'}]}};for(const text of ['Open metal options','Open material options','Select material Sterling Silver']){const r=bridge.resolve(text,p);assert.equal(r.ok,false);assert.equal(r.handled,true);assert.match(r.reason,/More than one published option group/);}const explicit=bridge.resolve('Open Metal Choice options',p);assert.equal(explicit.ok,true);assert.equal(explicit.action.optionName,'Metal Choice');});
test('actual-title alias follows fresh controls only and never restores a previous product selection',async()=>{const h=harness(rhinoPage),request=h.api.resolve('Open metal options');h.set({contextRevision:35,currentHandle:compass.handle,productControls:{...controls,handle:compass.handle,productId:compass.id}});const r=await h.api.execute(request.action);assert.equal(r.stale,true);assert.equal(h.calls.length,0);});

test('explicit overlapping group names still clarify when both are requested separately',()=>{const p={...clone(rhinoPage),productControls:{...clone(rhinoControls),optionGroups:[...clone(rhinoControls.optionGroups),{name:'Metal',values:['Oxidized']}]}};assert.equal(bridge.resolve('Open Metal Choice and Metal options',p).ok,false);});

const hoopFixture={...rhinoFixture,id:'gid://shopify/Product/7501',handle:'gold-hoop-earrings',title:'Gold Huggie Hoop Earrings'};
const hoopPage={...clone(rhinoPage),currentHandle:hoopFixture.handle,visiblePieces:[hoopFixture],loadedPieces:[hoopFixture],productControls:{...clone(rhinoControls),handle:hoopFixture.handle,productId:hoopFixture.id,optionGroups:[rhinoControls.optionGroups[0],{name:'Hoop Size',values:['8.5mm','11mm']}],selectedOptions:[{name:'Metal Choice',value:'14k Gold Filled'},{name:'Hoop Size',value:'8.5mm'}]}};
for(const text of ['Open size options','Open sizes menu','Open Hoop Size options'])test('actual published Hoop Size retains the unique natural size group: '+text,()=>{const r=bridge.resolve(text,hoopPage);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,{type:'options',handle:hoopFixture.handle,optionName:'Hoop Size'});});
for(const label of ['Chain Length','Necklace Length'])test('observed published length label supports a unique natural length request: '+label,()=>{const p={...clone(hoopPage),productControls:{...clone(hoopPage.productControls),optionGroups:[{name:label,values:['16 inch','18 inch']}],selectedOptions:[{name:label,value:'16 inch'}]}};assert.deepEqual(bridge.resolve('Open length options',p).action,{type:'options',handle:hoopFixture.handle,optionName:label});assert.deepEqual(bridge.resolve('Select length 18 inch',p).action,{type:'select-option',handle:hoopFixture.handle,optionName:label,optionValue:'18 inch'});});
for(const family of [['size','Hoop Size','Size'],['length','Chain Length','Necklace Length']])test('multiple published '+family[0]+' groups refuse generic alias',()=>{const p={...clone(hoopPage),productControls:{...clone(hoopPage.productControls),optionGroups:[{name:family[1],values:['Small']},{name:family[2],values:['Large']}]}};assert.equal(bridge.resolve('Open '+family[0]+' options',p).ok,false);assert.equal(bridge.resolve('Select '+family[0]+' Small',p).ok,false);assert.equal(bridge.resolve('Open '+family[1]+' options',p).ok,true);});
test('two differently requested published option groups do not silently choose one',()=>assert.equal(bridge.resolve('Open metal and size options',hoopPage).ok,false));
const rhinoSilverLine={lineId:'7411:silver-fixture',productId:rhinoFixture.id,variantId:'gid://shopify/ProductVariant/7411',quantity:1,title:rhinoFixture.title,variant:'Sterling Silver'};
const rhinoGoldLine={lineId:'7412:gold-fixture',productId:rhinoFixture.id,variantId:'gid://shopify/ProductVariant/7412',quantity:2,title:rhinoFixture.title,variant:'14k Gold Filled'};
const rhinoBag={...clone(rhinoPage),pageKind:'bag',bagControls:{lines:[rhinoSilverLine,rhinoGoldLine],itemCount:3}};
for(const text of ['Set the quantity of the 14k Gold Filled Rhino Profile Stud Earrings to 3','Set the quantity of the 14k Gold Filled Rhino Profile Stud Earrings to 3.','Change quantity for 14k Gold Filled Rhino Profile Stud Earrings to 3','Set quantity to 3 for the 14k Gold Filled Rhino Profile Stud Earrings'])test('actual reversed quantity grammar binds requested3, not material14k: '+text,()=>{const r=bridge.resolve(text,rhinoBag);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,{type:'bag-quantity',lineId:rhinoGoldLine.lineId,quantity:3});assert.equal(rhinoBag.bagControls.lines[0].quantity,1);assert.equal(rhinoBag.bagControls.lines[1].quantity,2);});
for(const text of ['Set the quantity of Rhino Profile Stud Earrings to 3','Set the quantity of the 14k Gold Filled Rhino Profile Stud Earrings to 3 or 4','Set quantity to 2 and quantity to 3','Set quantity to 2 and 3','Set quantity of the 14k Gold Filled Rhino Profile Stud Earrings to 3.5','Set quantity of the 14k Gold Filled Rhino Profile Stud Earrings to -3'])test('ambiguous line or repeated/malformed quantity remains unchanged: '+text,()=>assert.equal(bridge.resolve(text,rhinoBag).ok,false));
test('same-title same-option lines cannot borrow the first line for a quantity request',()=>{const p={...clone(rhinoBag),bagControls:{lines:[rhinoGoldLine,{...rhinoGoldLine,lineId:'7412:other-gold-fixture'}]}};assert.equal(bridge.resolve('Set quantity of the 14k Gold Filled Rhino Profile Stud Earrings to 3',p).ok,false);});

for(const label of ['bag','test bag','mock bag','demo cart','sandbox basket'])test('named bag removal retains the exact published material line: '+label,()=>{const text='Remove the 14k Gold Filled Rhino Profile Stud Earrings from my '+label,r=bridge.resolve(text,rhinoBag);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,{type:'bag-remove',lineId:rhinoGoldLine.lineId});assert.equal(rhinoBag.bagControls.lines[0].quantity,1);assert.equal(rhinoBag.bagControls.lines[1].quantity,2);});
test('bag page permits only a qualified exact named removal without an explicit bag suffix',()=>{assert.deepEqual(bridge.resolve('Delete the 14k Gold Filled Rhino Profile Stud Earrings',rhinoBag).action,{type:'bag-remove',lineId:rhinoGoldLine.lineId});assert.equal(bridge.resolve('Delete the Rhino Profile Stud Earrings',rhinoBag).ok,false);});
for(const text of ['Remove Hidden Stud Earrings from my test bag','Remove the Rhino Profile Stud Earrings from my test bag','Remove the Platinum Rhino Profile Stud Earrings from my test bag','Remove the Gold Rhino Profile Stud Earrings from my test bag','Remove the second Hidden Stud Earrings from my test bag'])test('unmatched or ambiguous line removal is a handled halt: '+text,()=>{const r=bridge.resolve(text,rhinoBag);assert.equal(r.ok,false);assert.equal(r.handled,true);assert.equal(r.delegated,undefined);});
test('an unknown named option cannot borrow the single available bag line',()=>{const single={...clone(rhinoBag),bagControls:{lines:[rhinoSilverLine]}};for(const text of ['Remove the 14k Gold Filled Rhino Profile Stud Earrings from my test bag','Remove Hidden Stud Earrings from my bag','Set quantity of the 14k Gold Filled Rhino Profile Stud Earrings to 3']){const r=bridge.resolve(text,single);assert.equal(r.ok,false);assert.equal(r.handled,true);}});
test('repeated same-option line identities still clarify rather than choosing the first removal',()=>{const p={...clone(rhinoBag),bagControls:{lines:[rhinoGoldLine,{...rhinoGoldLine,lineId:'7412:another-gold-fixture'}]}};assert.equal(bridge.resolve('Remove the 14k Gold Filled Rhino Profile Stud Earrings from my test bag',p).ok,false);});
test('legacy bag removal retains its existing review delegation without acquiring line authority',()=>{const r=bridge.resolve('Remove the 14k Gold Filled Rhino Profile Stud Earrings from my test bag',{...rhinoBag,controlVersion:undefined});assert.equal(r.ok,false);assert.equal(r.handled,false);assert.equal(r.delegated,'review');assert.equal(r.action,undefined);});
for(const text of ['Add gift wrapping and a gift package','Enable gift wrapping and gift package','Choose a gift package and gift wrapping','Add gift wrapping and a gift package to my test bag'])test('combined positive gift choice is one exact preferences action before product-add: '+text,()=>{const r=bridge.resolve(text,rhinoBag);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,{type:'gift-preferences',wrapping:true,giftPackage:true});assert.deepEqual(client.validateToolArguments(r.action,'control_storefront'),r.action);assert.deepEqual(server.validateToolArguments(r.action,'control_storefront'),r.action);});
for(const text of ['Remove gift wrapping and gift package','Disable a gift package and gift wrapping','Turn off gift wrapping and gift packaging','Remove gift wrapping and gift package from my test bag'])test('combined negative gift choice updates both requested booleans: '+text,()=>{const r=bridge.resolve(text,rhinoBag);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,{type:'gift-preferences',wrapping:false,giftPackage:false});});
for(const text of ['Add gift wrapping and remove gift package','Remove gift wrapping and add gift package','Add gift wrapping without gift package','Add gift wrapping and gift package or not','Add gift wrapping and gift package and a necklace','Add gift wrapping and gift note Happy Birthday','Add gift wrapping and wrapping'])test('mixed or unclear gift choice cannot partially update or prepare a product review: '+text,()=>{const r=bridge.resolve(text,rhinoBag);assert.equal(r.ok,false);assert.equal(r.handled,true);assert.equal(r.action,undefined);assert.equal(r.delegated,undefined);});
test('unavailable gift capability remains a handled halt, not product-add',()=>{const r=bridge.resolve('Add gift wrapping and a gift package',{...rhinoBag,controlVersion:undefined});assert.equal(r.ok,false);assert.equal(r.handled,true);assert.match(r.reason,/Gift preferences/);});
test('combined gift preferences retain current native final-word and exact-argument authority',async()=>{const text='Add gift wrapping and a gift package',action={type:'gift-preferences',wrapping:true,giftPackage:true},h=harness(rhinoBag),opts={transcript:text,context:rhinoBag,currentTurn:true,inputItemId:'fixture-gift-input',turnVersion:34};assert.equal((await h.api.execute({...action,giftPackage:false},opts)).ok,false);assert.equal(h.calls.length,0);assert.equal((await h.api.execute(action,opts)).ok,true);assert.equal(h.calls.length,1);assert.equal((await h.api.execute(action,opts)).suppressed,true);assert.equal(h.calls.length,1);});
test('exact bag removal rejects stale line state before execution',async()=>{const h=harness(rhinoBag),r=h.api.resolve('Remove the 14k Gold Filled Rhino Profile Stud Earrings from my test bag');h.set({bagControls:{lines:[rhinoSilverLine],itemCount:1}});assert.equal((await h.api.execute(r.action)).stale,true);assert.equal(h.calls.length,0);});

for(const text of ['Set quantity to 3','Set this piece quantity to 3','Set the quantity of the current product to 3','Set quantity to 3 for this product','Set Rhino Profile Stud Earrings quantity to 3','Set the quantity of the 14k Gold Filled Rhino Profile Stud Earrings to 3'])test('quantity binds bare/current or exact selected named product: '+text,()=>{const r=bridge.resolve(text,rhinoPage);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,{type:'product-quantity',handle:rhinoFixture.handle,quantity:3});});
for(const text of ['Set Hidden Pendant quantity to 2','Set the quantity of Hidden Pendant to 2','Set quantity to 2 for Hidden Pendant','Set Hidden Rhino Pendant quantity to 2','Set Hidden Rhino Profile Stud Earrings quantity to 2','Set Sterling Silver Rhino Profile Stud Earrings quantity to 2','Set Hidden Pendant quantity to 2 for the current product'])test('unknown or mismatching named product cannot borrow current quantity scope: '+text,()=>{const r=bridge.resolve(text,rhinoPage);assert.equal(r.ok,false);assert.equal(r.handled,true);assert.equal(r.action,undefined);assert.equal(rhinoPage.productControls.quantity,2);});
test('another checked loaded product still cannot change the current product quantity',()=>{const p={...clone(rhinoPage),loadedPieces:[rhinoFixture,compass]};assert.equal(bridge.resolve('Set Compass Pendant quantity to 3',p).ok,false);});
test('a model cannot bypass a refused unknown named quantity with the current exact handle',async()=>{const h=harness(rhinoPage),r=await h.api.execute({type:'product-quantity',handle:rhinoFixture.handle,quantity:2},{transcript:'Set Hidden Pendant quantity to 2',context:rhinoPage,currentTurn:true,inputItemId:'fixture-unknown-quantity',turnVersion:35});assert.equal(r.ok,false);assert.equal(h.calls.length,0);});

const migrationVariant={id:'gid://shopify/ProductVariant/8611',title:'Sterling Silver',price:51,available:true,options:[{name:'Metal Choice',value:'Sterling Silver'}]};
const migrationProduct={id:'gid://shopify/Product/8601',handle:'migration-fixture-studs',title:'Migration Fixture Stud Earrings',url:'https://britesjewelry.com/products/migration-fixture-studs',currency:'USD',minPrice:51,variants:[migrationVariant],variantsComplete:true};
for(const prefix of ['','en/','fr/','en-us/','fr-CA/'])for(const slash of ['', '/'])test('strict own exact product URL preserves optional Shopify locale '+prefix+slash,()=>{const url='https://britesjewelry.com/'+prefix+'products/'+migrationProduct.handle+slash,p=bridge.projectLiveProducts([{...clone(migrationProduct),url}]);assert.equal(p.length,1);assert.equal(p[0].url,url);assert.equal(p[0].handle,migrationProduct.handle);});
for(const url of ['http://britesjewelry.com/products/migration-fixture-studs','https://other.example/products/migration-fixture-studs','https://britesjewelry.com.evil.example/products/migration-fixture-studs','https://user@britesjewelry.com/products/migration-fixture-studs','https://britesjewelry.com:443/products/migration-fixture-studs','https://britesjewelry.com:8443/products/migration-fixture-studs','https://britesjewelry.com/en/products/migration-fixture-studs?variant=8611','https://britesjewelry.com/en/products/migration-fixture-studs#price','https://britesjewelry.com/eng/products/migration-fixture-studs','https://britesjewelry.com/en-USA/products/migration-fixture-studs','https://britesjewelry.com/en/us/products/migration-fixture-studs','https://britesjewelry.com/en/collections/all/products/migration-fixture-studs','https://britesjewelry.com/products/migration-fixture-studs/extra','https://britesjewelry.com/en/products/../products/migration-fixture-studs','https://britesjewelry.com/en/products/%6digration-fixture-studs','https://britesjewelry.com/en/products/another-fixture','https://britesjewelry.com/en//products/migration-fixture-studs'])test('migration product URL rejects authority/route drift '+url,()=>assert.deepEqual(bridge.projectLiveProducts([{...clone(migrationProduct),url}]),[]));
function variantCountProduct(count){return {...clone(migrationProduct),variants:Array.from({length:count},(_,i)=>({...clone(migrationVariant),id:'gid://shopify/ProductVariant/'+(8700+i),title:'Exact option '+i,options:[{name:'Fixture Option',value:'Option '+i}]}))};}
for(const count of [60,61,249,250])test('bridge preserves the adapter complete variant boundary '+count,()=>{const p=bridge.projectLiveProducts([variantCountProduct(count)]);assert.equal(p.length,1);assert.equal(p[0].variants.length,count);assert.equal(new Set(p[0].variants.map(v=>v.id)).size,count);assert.equal(p[0].variantsComplete,true);assert.deepEqual(p[0].variants[count-1].options,[{name:'Fixture Option',value:'Option '+(count-1)}]);});
test('bridge refuses more than250 variants and leaves product response bound60 unchanged',()=>{assert.deepEqual(bridge.projectLiveProducts([variantCountProduct(251)]),[]);assert.deepEqual(bridge.projectLiveProducts(Array.from({length:61},()=>clone(migrationProduct))),[]);assert.equal(bridge.projectLiveProducts(Array.from({length:60},()=>clone(migrationProduct))).length,60);});
test('duplicate or malformed variant IDs and nonliteral titles cannot be marked complete',()=>{for(const mutate of [p=>p.variants[249].id=p.variants[0].id,p=>p.variants[249].id='../admin',p=>p.variants[249].title='Bad\u0001title']){const p=variantCountProduct(250);mutate(p);assert.deepEqual(bridge.projectLiveProducts([p]),[]);}});
test('incomplete250 variant response remains incomplete and cannot start a confirmed cart review',async()=>{const p=bridge.projectLiveProducts([{...variantCountProduct(250),variantsComplete:false}])[0];assert.equal(p.variants.length,250);assert.equal(p.variantsComplete,false);let reads=0;await assert.rejects(widget.verifiedCartAdd({fetch:async()=>{reads++;},product:p,variant:p.variants[249],quantity:1,requestId:'fixture_migration_123456'}),/complete options/);assert.equal(reads,0);});
test('downstream native context remains bounded with a complete250 variant source response',()=>{const p=bridge.projectLiveProducts([variantCountProduct(250)])[0],context=client.publicContext({...page,displayedPieces:Array.from({length:20},(_,i)=>({...p,id:'gid://shopify/Product/'+(8900+i),handle:'migration-fixture-'+i})),productControls:{...clone(controls),optionGroups:[{name:'Fixture Option',values:p.variants.map(v=>v.options[0].value)}]}});assert.ok(Buffer.byteLength(JSON.stringify(context),'utf8')<=18000);assert.ok(context.displayedPieces.length<=6);assert.equal('variants' in context.displayedPieces[0],false);assert.doesNotMatch(JSON.stringify(context),/numericId|giftNote|reviewAuthority/);});

function helperCountProduct(count){const p=variantCountProduct(count);p.variants=p.variants.map(v=>({...v,numericId:v.id.split('/').pop()}));return p;}
function helperReview(product,index,text){return voiceActions.resolveRequest({action:'review',handle:product.handle,variantId:product.variants[index].id,message:text||'Add '+product.title+' '+product.variants[index].title+' to my bag',products:[product],selectedProductId:product.id});}
for(const count of [60,61,249,250])test('actual live-review helper preserves complete bound and authorizes only the last exact variant: '+count,()=>{const source=helperCountProduct(count),p=voiceActions.projectProduct(source,migrationProduct);assert.ok(p);assert.equal(p.variants.length,count);assert.equal(p.variantsComplete,true);assert.equal(helperReview(p,count-1).ok,true);const wrong=voiceActions.resolveRequest({action:'review',handle:p.handle,variantId:p.variants[0].id,message:'Add '+p.title+' '+p.variants[count-1].title+' to my bag',products:[p],selectedProductId:p.id});assert.equal(wrong.ok,false);assert.equal(wrong.reason,'EXACT_OPTIONS_REQUIRED');});
test('actual helper caps morethan250 as incomplete and never authorizes an exact review of the truncated source',()=>{const p=voiceActions.projectProduct(helperCountProduct(251),migrationProduct);assert.ok(p);assert.equal(p.variants.length,250);assert.equal(p.variantsComplete,false);assert.equal(helperReview(p,249).ok,false);assert.equal(helperReview(p,249).reason,'EXACT_OPTIONS_REQUIRED');});
test('actual helper preserves independently incomplete250 and refuses final-word review',()=>{const source={...helperCountProduct(250),variantsComplete:false},p=voiceActions.projectProduct(source,migrationProduct);assert.ok(p);assert.equal(p.variantsComplete,false);assert.equal(helperReview(p,249).ok,false);});
for(const label of ['duplicate','numeric mismatch','invalid options','identity drift','currency drift'])test('actual helper250 preserves its identity, numeric and literal guards: '+label,()=>{const p=helperCountProduct(250);if(label==='duplicate')p.variants[249]=clone(p.variants[0]);if(label==='numeric mismatch')p.variants[249].numericId='9999';if(label==='invalid options')p.variants[249].options[0].value='Bad\u0001value';if(label==='identity drift')p.id='gid://shopify/Product/8699';if(label==='currency drift')p.currency='US';assert.equal(voiceActions.projectProduct(p,migrationProduct),null);});
test('larger helper catalogue preserves unavailable, customizer, negative and payment authority gates',()=>{const source=helperCountProduct(250);source.variants[249].available=false;let p=voiceActions.projectProduct(source,migrationProduct);assert.ok(p);assert.equal(helperReview(p,249).ok,false);source.variants[249].available=true;source.variants[249].title='Engraved exact option249';source.variants[249].options=[{name:'Engraving',value:'Yes'}];p=voiceActions.projectProduct(source,migrationProduct);assert.equal(helperReview(p,249).reason,'PERSONALIZATION_REQUIRES_PRODUCT_PAGE');p=voiceActions.projectProduct(helperCountProduct(250),migrationProduct);assert.equal(helperReview(p,249,'Do not add '+p.title+' '+p.variants[249].title+' to my bag').reason,'NEGATED_REQUEST');assert.equal(helperReview(p,249,'Pay for '+p.title+' '+p.variants[249].title).reason,'CHECKOUT_REQUIRES_CUSTOMER');assert.equal(helperReview(p,249,'Which '+p.title+' should I choose?').reason,'NO_ACTION_AUTHORITY');});
