'use strict';
// Real mobile helper iframe, sandbox, bridge and manually submitted guide form.
// Synthetic checked inventory; dialog/avatar APIs are spies, not pixel checks.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole,requestInterceptor}=require('jsdom');
const bridge=require('../../brites-storefront-bridge.js');
const source=Object.fromEntries(['concierge-layout-qa.html','concierge-sandbox.html','concierge-sandbox.js','brites-storefront-bridge.js','brites-concierge.js'].map(file=>[file,fs.readFileSync(require.resolve('../../'+file),'utf8')]));
const clone=v=>JSON.parse(JSON.stringify(v)),settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
function piece(i){const handle=i===0?'strawberry-charm-beady-necklace':i===1?'watermelon-stud-earrings':'relative-image-'+i;return {id:'gid://shopify/Product/'+(40100+i),handle,title:i===0?'Strawberry Beady Necklace':i===1?'Watermelon Stud Earrings':'Relative Image '+i+' Necklace',type:i===1?'Earrings':'Necklace',url:'https://britesjewelry.com/products/'+handle,description:'Published synthetic piece.',currency:'USD',minPrice:55,checkedAt:Date.now(),detailState:'checked',variantsComplete:true,image:'https://cdn.shopify.com/'+handle+'-1.jpg',images:[1,2,3].map(n=>({url:'https://cdn.shopify.com/'+handle+'-'+n+'.jpg'})),options:[{name:'Metal Choice',values:['Sterling Silver']}],variants:[{id:'gid://shopify/ProductVariant/'+(401000+i),numericId:String(401000+i),title:'Sterling Silver',price:55,available:true,options:[{name:'Metal Choice',value:'Sterling Silver'}]}]};}
async function fixture(t){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',error=>errors.push(error));const rows=Array.from({length:120},(_,i)=>piece(i)),requests=[],frameRequests=[];
  const frameHTML=source['concierge-sandbox.html'].replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*>/gi,'');
  const imagePNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
  const resources={interceptors:[requestInterceptor(request=>{const url=new URL(request.url),frame=url.pathname==='/concierge-sandbox.html',image=url.hostname==='cdn.shopify.com'&&/\.jpg$/.test(url.pathname);if(frame)frameRequests.push(request.url);return new Response(frame?frameHTML:image?imagePNG:'',{headers:{'Content-Type':frame?'text/html':image?'image/png':'text/css'}});})]};
  const dom=new JSDOM(source['concierge-layout-qa.html'],{url:'https://preview.example/concierge-layout-qa.html?viewport=mobile&product=strawberry-charm-beady-necklace',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,resources});await settle();
  const frame=dom.window.document.querySelector('iframe'),w=frame.contentWindow,d=w.document;w.innerWidth=360;w.innerHeight=720;d.body.dataset.inventoryPreload='complete';
  w.matchMedia=()=>({matches:false,addEventListener(){}});w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=()=>{};w.HTMLDialogElement.prototype.show=function(){this.setAttribute('open','');};
  w.fetch=async(raw,init={})=>{const url=new URL(raw,w.location.href);requests.push({url,init});let body;
    if(url.pathname==='/api/growth/inventory'){const offset=Number(url.searchParams.get('offset')),products=rows.slice(offset,offset+24);body={live:true,checkedAt:Date.now(),products,inventory:{schema:1,total:120,offset,limit:24,loaded:products.length,detailsLoaded:products.length,ready:false,partial:false,expiresAt:Date.now()+300000},pageInfo:{hasNextPage:offset+24<120,nextOffset:offset+24<120?offset+24:null}};}
    else if(url.pathname==='/api/growth/catalogue')body={live:true,checkedAt:Date.now(),products:rows,pageInfo:{hasNextPage:false,endCursor:null}};
    else if(url.pathname==='/api/growth/product')body={live:true,checkedAt:Date.now(),product:rows.find(p=>p.handle===url.searchParams.get('handle'))};
    else if(url.pathname==='/api/growth/storefront-services')body={schema:1,guidance:{},conflicts:[],offers:{items:[]}};
    else if(url.pathname==='/api/growth/events'||url.pathname==='/api/concierge-voice')body={ok:true,enabled:false,nativeAudio:false};
    else if(url.pathname==='/api/concierge'){if(init.body&&JSON.parse(init.body).event)body={ok:true};else body={live:true,reply:'These available pieces connect with image.',products:[rows[1]],meanings:[],preferences:{}};}
    else throw Error('Unexpected '+url.pathname);return {ok:true,json:async()=>clone(body)};
  };
  w.eval(source['brites-storefront-bridge.js']);w.eval(source['concierge-sandbox.js']);await settle();await w.BritesSandboxStorefront.preloadInventory();
  w.BritesConciergeAvatar={create(){return {setState(){},setEmotion(){},setVisible(){},setPaused(){},retry(){},triggerGreeting(){},clearFocus(){},focusProduct(){},setLevel(){},setSpeechSignal(){},clearProduct(){},showProduct(){},cancelPerformance(){},setFloating(){},cue(){},destroy(){}};}};
  const script=d.createElement('script');script.src='/brites-concierge.js';script.dataset.sandbox='true';Object.defineProperty(d,'currentScript',{get:()=>script});w.eval(source['brites-concierge.js']);await settle();const host=d.querySelector('brites-concierge'),root=host.shadowRoot;
  t.after(()=>{w.BritesConcierge?.close();dom.window.close();});
  async function consoleCommand(text){const form=d.querySelector('#guide-request-form');d.querySelector('#guide-request').value=text;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));for(let i=0;i<60;i++){await settle();if(form.getAttribute('aria-busy')==='false')return;}throw Error('The actual console request did not settle.');}
  async function message(text){const input=root.querySelector('[aria-label="Message the gift concierge"]');input.value=text;root.querySelector('.composer button[type="submit"]').click();for(let i=0;i<60;i++){await settle();if(!input.disabled)return;}throw Error('The actual composer request did not settle.');}
  return {w,d,dom,frame,frameRequests,root,host,errors,requests,rows,consoleCommand,message,store:w.BritesSandboxStorefront,providers:()=>requests.filter(r=>r.url.pathname==='/api/concierge'&&r.init.body&&typeof JSON.parse(r.init.body).message==='string')};
}
test('bare relative image commands bind only the current checked gallery and keep target and range guards',()=>{
  const p=piece(0),page={controlVersion:1,contextRevision:1,pageKind:'product',currentHandle:p.handle,visiblePieces:[p],loadedPieces:[p],galleryControls:{handle:p.handle,imageCount:3,selectedIndex:2}};
  assert.deepEqual(bridge.resolve('Next image',page).action,{type:'gallery',handle:p.handle,index:3});assert.deepEqual(bridge.resolve('Previous image',page).action,{type:'gallery',handle:p.handle,index:1});
  for(const text of ['Next image of Unicorn Necklace','Next image if I ask','Next image tomorrow','Next image and buy it','Next image magically','The next image is beautiful','I like the next image','"Next image"'])assert.equal(bridge.resolve(text,page).ok,false,text);
  assert.equal(bridge.resolve('Next image',{...page,galleryControls:{...page.galleryControls,selectedIndex:3}}).recognized,true);assert.equal(bridge.resolve('Next image',{...page,galleryControls:{...page.galleryControls,selectedIndex:3}}).ok,false);
  assert.equal(bridge.resolve('Previous image',{...page,galleryControls:{...page.galleryControls,selectedIndex:1}}).ok,false);const absent=bridge.resolve('Next image',{...page,currentHandle:null,galleryControls:null});assert.equal(absent.ok,false);assert.equal(absent.recognized,true);assert.match(absent.reason,/piece|image/i);
});
test('the actual manual composer reports a missing gallery locally without a provider search or changed collection',async t=>{
  const f=await fixture(t);await f.consoleCommand('Open my bag');const before=clone(f.store.snapshot()),providers=f.providers().length;
  for(const text of ['Next image','Previous image']){await f.message(text);assert.equal(f.store.snapshot().pageKind,'bag');assert.equal(f.store.snapshot().contextRevision,before.contextRevision);assert.equal(f.d.querySelector('#storefront-image-dialog'),null);assert.equal(f.providers().length,providers);assert.match(f.root.textContent,/Choose a listing or give its exact title so I can use the correct piece/);assert.equal(f.root.querySelector('.composer input').disabled,false);}
  assert.deepEqual(JSON.parse(f.w.sessionStorage.getItem('brites-sandbox-cart')||'[]'),[]);assert.deepEqual(f.errors.map(error=>error.message),[],'Manual gallery commands must not cause DOM runtime errors');
});
test('a closed mobile iframe guide opened by its real console keeps bare Next image local when the shopper submits the manual composer',async t=>{
  const f=await fixture(t);assert.equal(f.frame.getAttribute('width'),'360');assert.equal(f.frame.getAttribute('height'),'720');assert.equal(f.w.top,f.dom.window);assert.equal(f.dom.window.document.querySelectorAll('iframe').length,1);assert.equal(f.frameRequests.length,1);assert.equal(f.host.getAttribute('data-open'),'false');assert.equal(f.store.snapshot().inventory.ready,true);assert.equal(f.store.snapshot().inventory.loaded,120);
  await f.consoleCommand('Show image 2 then enlarge the image');assert.equal(f.host.getAttribute('data-open'),'true');assert.equal(f.store.snapshot().currentHandle,f.rows[0].handle);assert.equal(f.store.snapshot().galleryControls.selectedIndex,2);const dialog=f.d.querySelector('#storefront-image-dialog');assert(dialog?.open);assert.match(dialog.querySelector('img').src,/-2\.jpg$/);const providers=f.providers().length,requests=f.requests.length;
  await f.message('Next image');assert.equal(f.store.snapshot().pageKind,'product');assert.equal(f.store.snapshot().currentHandle,f.rows[0].handle);assert.equal(f.store.snapshot().galleryControls.selectedIndex,3);assert.equal(f.d.querySelector('#storefront-image-dialog'),dialog);assert.match(dialog.querySelector('img').src,/-3\.jpg$/);assert.match(dialog.querySelector('p').textContent,/image 3 of 3/);assert.equal(f.providers().length,providers);assert.equal(f.requests.length,requests);assert.doesNotMatch(f.root.textContent,/available pieces connect with image/);assert.equal(f.root.querySelector('.composer input').disabled,false);
  await f.message('Next image');assert.equal(f.store.snapshot().galleryControls.selectedIndex,3);assert.match(f.root.textContent,/Choose a published image from 1 to 3/);assert.equal(f.providers().length,providers);await f.message('Previous image');assert.equal(f.store.snapshot().galleryControls.selectedIndex,2);assert.equal(f.d.querySelector('#storefront-image-dialog'),dialog);assert.match(dialog.querySelector('img').src,/-2\.jpg$/);assert.equal(f.providers().length,providers);assert.deepEqual(f.errors.map(error=>error.message),[],'Mobile gallery commands must not cause DOM runtime errors');
});
