'use strict';
// Runs the actual widget, intent bridge and sandbox controls together. Native
// callbacks and public catalogue responses are synthetic; this is not browser,
// microphone, provider or real checkout acceptance.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const Bridge=require('../../brites-storefront-bridge.js'),Voice=require('../../brites-concierge-voice.js'),Actions=require('../../brites-concierge-voice-actions.js'),Widget=require('../../brites-concierge.js');
const sources=Object.fromEntries(['concierge-sandbox.html','concierge-sandbox.js','brites-concierge.js','brites-storefront-bridge.js'].map(file=>[file,fs.readFileSync(require.resolve('../../'+file),'utf8')]));
const clone=value=>JSON.parse(JSON.stringify(value)),settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
function shopperControlReceipt(result){
  assert.equal(typeof result.reply,'string');assert.ok(result.reply.trim());
  assert.equal(result.customerMessage,result.reply);
  assert.equal(typeof result.ok,'boolean');assert.equal(typeof result.cartChanged,'boolean');
  for(const key of ['publicContext','snapshot','action','actions','completedActions','stepResults','reason','error','storefrontAction','requestId','responseId','turnVersion','authority'])assert.equal(Object.hasOwn(result,key),false,key+' must remain outside the spoken receipt');
  assert.doesNotMatch(result.reply,/\b(?:backend|adapter|postcondition|precondition|metadata|authority|control_storefront|NO_ACTION_AUTHORITY|EXACT_OPTIONS_REQUIRED)\b|\bmotif\s*[:=]|\bno further actions?\b/i);
  assert.doesNotMatch(JSON.stringify(result),/PRIVATE_|privateNotes|giftNote|properties/);
  return result;
}
const categories=['regular-necklaces','beady-necklaces','stud-earrings','hoop-earrings','charm-only'];
function product(index,category='regular-necklaces'){
  const id=3700+index,noun={'regular-necklaces':'Necklace','beady-necklaces':'Beady Necklace','stud-earrings':'Stud Earrings','hoop-earrings':'Hoop Earrings','charm-only':'Charm'}[category],handle='fixture-'+index+'-'+category,title='Fixture '+index+' '+noun;
  const second=category==='charm-only'?{name:'Charm Format',values:['Necklace charm only','Huggie charm set']}:category==='hoop-earrings'?{name:'Hoop Size',values:['8.5mm','11mm']}:category==='stud-earrings'?null:{name:'Chain Length',values:['16 inches','18 inches']};
  const options=[{name:'Metal Choice',values:['Sterling Silver','Gold Filled']},...(second?[second]:[])],choices=options.reduce((rows,g)=>rows.flatMap(row=>g.values.map(value=>[...row,{name:g.name,value}])) ,[[]]);
  return {id:'gid://shopify/Product/'+id,handle,title,type:category==='charm-only'?'Charm':category.includes('necklaces')?'Necklace':'Earrings',description:category==='charm-only'?'A published charm-only listing. Chain not included.':'Published sterling silver and gold filled options with exact size choices.',url:'https://britesjewelry.com/products/'+handle,currency:'USD',image:'https://cdn.shopify.com/'+handle+'.jpg',storeCategories:[category],options,variantsComplete:true,partsOnly:category==='charm-only',minPrice:50,variants:choices.map((selected,n)=>({id:'gid://shopify/ProductVariant/'+(id*10+n+1),numericId:String(id*10+n+1),title:selected.map(o=>o.value).join(' / '),price:50+n*7.25,available:true,options:selected}))};
}
function catalogue(){let n=0;return categories.flatMap((category,g)=>Array.from({length:[28,28,27,10,27][g]},()=>product(++n,category)));}
function seed(products){const categoryCounts=Object.fromEntries(categories.map(c=>[c,products.filter(p=>p.storeCategories.includes(c)).length])),unfilledCategories=categories.filter(c=>!categoryCounts[c]);return {live:true,checkedAt:Date.now(),products,seed:{schema:1,target:120,minimum:100,loaded:products.length,complete:products.length>=100&&!unfilledCategories.length,partial:false,sourcePages:2,categoryCounts,unfilledCategories},pageInfo:{hasNextPage:false,endCursor:null}};}
async function fixture(t,options={}){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));const dom=new JSDOM(sources['concierge-sandbox.html'],{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document,products=clone(options.products||catalogue());let config,turn=0,hidden=false,waitRead=null;
  const calls={requests:[],scrolls:[],contexts:[],controls:[],nativeStarts:0,nativeStops:0};
  Object.defineProperty(d,'hidden',{get:()=>hidden});w.matchMedia=()=>({matches:false,addEventListener(){}});w.HTMLElement.prototype.scrollIntoView=function(value){calls.scrolls.push({node:this,value});};
  w.fetch=async(raw,init={})=>{const url=new URL(raw,w.location.href),body=init.body?JSON.parse(init.body):null;calls.requests.push({url,body,method:init.method||'GET'});let data;
    if(url.pathname==='/api/growth/catalogue')data=url.searchParams.has('seed')?seed(products):{live:true,products:clone(products),checkedAt:Date.now(),pageInfo:{hasNextPage:false,endCursor:null}};
    else if(url.pathname==='/api/growth/inventory'&&options.checkedInventory===true){const offset=Number(url.searchParams.get('offset')),rows=products.slice(offset,offset+24).map(p=>({...p,detailState:'checked'}));data={live:true,checkedAt:Date.now(),products:rows,inventory:{schema:1,total:products.length,offset,limit:24,loaded:rows.length,detailsLoaded:rows.length,ready:false,partial:false,expiresAt:Date.now()+300000},pageInfo:{hasNextPage:offset+24<products.length,nextOffset:offset+24<products.length?offset+24:null}};}
    else if(url.pathname==='/api/growth/product'){if(waitRead)await waitRead();const p=products.find(p=>p.handle===url.searchParams.get('handle'));data={live:true,product:p&&clone(p)};}
    else if(url.pathname==='/api/growth/storefront-services')data={schema:1,guidance:{},conflicts:[],offers:{items:[],status:'published_not_checkout_validated'}};
    else if(url.pathname==='/api/concierge-voice')data={enabled:true,nativeAudio:true,publicDemo:true};
    else if(url.pathname==='/api/growth/events')data={ok:true};
    else if(url.pathname==='/api/concierge')data=body?.message&&options.conciergeAnswer?options.conciergeAnswer:{live:true,reply:'Synthetic catalogue reply.',preferences:{},products:[],meanings:[],preserveSelection:true};
    else throw Error('Unexpected synthetic route '+url.pathname);
    return {ok:true,json:async()=>clone(data)};
  };
  w.BritesConciergeAvatar={create(){return {setState(){},setEmotion(){},setVisible(){},setPaused(){},retry(){},triggerGreeting(){},clearFocus(){},focusProduct(){},setLevel(){},setSpeechSignal(){},clearProduct(){},showProduct(){},cancelPerformance(){},setFloating(){},cue(){},destroy(){}};}};
  w.BritesConciergeVoiceActions=Actions;w.BritesConciergeVoice={...Voice,create(value){config=value;return {state:'listening',outputMeterState:'ready',playbackBlocked:false,start:async()=>{calls.nativeStarts++;return true;},stop:async()=>{calls.nativeStops++;},dispose:async()=>{},updateContext:v=>calls.contexts.push(clone(v))};}};
  w.eval(sources['brites-storefront-bridge.js']);w.eval(sources['concierge-sandbox.js']);await settle();
  if(options.checkedInventory===true){await w.BritesSandboxStorefront.preloadInventory();await settle();assert.equal(w.BritesSandboxStorefront.inventoryStatus().ready,true);}
  // Capture the real host result before the widget narrows it for speech.
  // This observes actual execution and never creates shopper authority.
  const host=w.BritesSandboxStorefront;w.BritesSandboxStorefront=Object.freeze({...host,async execute(action,options){const result=await host.execute(action,options);calls.controls.push({action:clone(action),result:clone(result)});return result;}});
  const script=d.createElement('script');script.src='/brites-concierge.js';script.dataset.sandbox='true';Object.defineProperty(d,'currentScript',{get:()=>script});w.eval(sources['brites-concierge.js']);const root=d.querySelector('brites-concierge').shadowRoot;
  const button=label=>[...root.querySelectorAll('button')].find(b=>b.textContent.trim()===label||b.getAttribute('aria-label')===label);
  const send=text=>w.BritesConcierge.sendShopperCommand(text);
  async function activate(){w.BritesConcierge.open();button('Talk to me').click();await settle();root.querySelector('script[src$="brites-concierge-voice.js"]')?.dispatchEvent(new w.Event('load'));await settle();assert.equal(calls.nativeStarts,1);}
  function speak(text){const itemId='shopping37-input-'+(++turn);config.onSpeechStarted({itemId,turnVersion:turn});config.onTranscript({role:'user',itemId,turnVersion:turn,currentTurn:true,text,final:true});return {inputItemId:itemId,turnVersion:turn,currentTurn:true,responseId:'shopping37-response-'+turn};}
  const tool=(name,args,context)=>config.onTool(args,{name,...context});
  t.after(()=>{w.BritesConcierge.close();w.close();});return {w,d,root,products,calls,errors,button,send,activate,speak,tool,get store(){return w.BritesSandboxStorefront;},cart:()=>JSON.parse(w.sessionStorage.getItem('brites-sandbox-cart')||'[]'),hide(){hidden=true;},waitProductRead(fn){waitRead=fn;}};
}
const pageFor=p=>({controlVersion:1,contextRevision:37,discoveryRevision:2,pageKind:'product',currentHandle:p.handle,visiblePieces:[p],loadedPieces:[p],productControls:{handle:p.handle,productId:p.id,productTitle:p.title,productType:p.type,variantId:p.variants.at(-1).id,quantity:2,optionsOpen:true,optionGroups:p.options,selectedOptions:p.variants.at(-1).options,selectedVariant:{...p.variants.at(-1),currency:p.currency},itemTotalPrice:p.variants.at(-1).price*2,reviewReady:false}});

for(const [text,filter] of [['Show regular necklaces','regular-necklaces'],['Browse beady necklaces','beady-necklaces'],['Can I see beaded necklaces?','beady-necklaces'],['Show stud earrings','stud-earrings'],['View hoop earrings','hoop-earrings'],['Open huggie earrings','hoop-earrings'],['Show charm-only pieces','charm-only']])test('exact supported collection command '+text,()=>{const resolved=Bridge.resolve(text,{contextRevision:1,pageKind:'collection',visiblePieces:[]});assert.equal(resolved.ok,true,resolved.reason);assert.deepEqual(resolved.action,{type:'filter',filter});assert.deepEqual(Voice.validateToolArguments(resolved.action,'control_storefront'),resolved.action);assert.equal(Voice.publicContext({filter,displayedPieces:[]}).filter,filter);});

test('selected price, material, quantity and subtotal come from the matching current variant',()=>{const p=product(1),page=pageFor(p);for(const projected of [Bridge.sanitizeSnapshot(page),Voice.publicContext(page)]){assert.equal(projected.productControls.selectedVariant.price,71.75);assert.equal(projected.productControls.itemTotalPrice,143.5);assert.equal(projected.productControls.selectedVariant.options[0].value,'Gold Filled');assert.equal(projected.productControls.productTitle,p.title);assert.equal(projected.productControls.productType,p.type);assert.notEqual(projected.productControls.selectedVariant.price,p.minPrice);}});
for(const [label,damage] of [['different variant identity',pc=>pc.selectedVariant.id='gid://shopify/ProductVariant/99'],['different literal choice',pc=>pc.selectedVariant.options[0].value='Platinum'],['nonfinite price',pc=>pc.selectedVariant.price=Infinity],['invalid currency',pc=>pc.selectedVariant.currency='usd'],['duplicate option group',pc=>pc.selectedVariant.options[1]=clone(pc.selectedVariant.options[0])]])test('current selection projection rejects '+label,()=>{const page=pageFor(product(1));damage(page.productControls);for(const api of [Bridge.sanitizeSnapshot,Voice.publicContext])assert.equal(api(page).productControls.selectedVariant,undefined);});
test('a wrong host subtotal is not echoed as the current item subtotal',()=>{const page=pageFor(product(1));page.productControls.itemTotalPrice=999;for(const api of [Bridge.sanitizeSnapshot,Voice.publicContext]){const pc=api(page).productControls;assert.equal(pc.selectedVariant.price,71.75);assert.equal(pc.itemTotalPrice,undefined);}});
test('a current last-of-250 option survives bounded native context without claiming the option list is complete',()=>{const p=product(1),values=Array.from({length:250},(_,n)=>'Choice '+n),page=pageFor(p),pc=page.productControls;pc.optionGroups=[{name:'Exact size',values}];pc.selectedOptions=[{name:'Exact size',value:values.at(-1)}];pc.selectedVariant.options=clone(pc.selectedOptions);const bridge=Bridge.sanitizeSnapshot(page),native=Voice.publicContext(bridge);assert.equal(bridge.productControls.optionGroups[0].values.length,250);assert.deepEqual(native.productControls.selectedOptions,pc.selectedOptions);assert.deepEqual(native.productControls.selectedVariant.options,pc.selectedOptions);assert.equal(native.productControls.selectedVariant.price,71.75);assert.equal(native.productControls.optionsTruncated,true);assert.ok(Buffer.byteLength(JSON.stringify(native),'utf8')<=18000);});
test('option setters cannot borrow the current product for unknown, foreign, ambiguous or conditional targets',()=>{const p=product(1),other=product(2),page={...pageFor(p),loadedPieces:[p,other]};for(const text of ['Select Sterling Silver for Hidden Pendant','Choose Hidden Pendant Sterling Silver','Select Sterling Silver for '+other.title,'Select Sterling Silver for '+p.title+' and '+other.title,'Select Sterling Silver if it is cheaper','Do not select Sterling Silver','Select Platinum']){const r=Bridge.resolve(text,page);assert.equal(r.ok,false,text);assert.equal(r.handled,true,text);assert.equal(r.action,undefined,text);}assert.deepEqual(Bridge.resolve('Choose material Sterling Silver for the current piece',page).action,{type:'select-option',handle:p.handle,optionName:'Metal Choice',optionValue:'Sterling Silver'});});
test('spoken quantities are exact whole numbers and keep malformed or conflicting changes refused',()=>{const p=product(1),page=pageFor(p);for(const [word,quantity] of [['one',1],['two',2],['twenty',20]])assert.deepEqual(Bridge.resolve('Set quantity to '+word,page).action,{type:'product-quantity',handle:p.handle,quantity});for(const value of ['twenty-one','two point five','-2','0','21','2.5','2 or 3'])assert.equal(Bridge.resolve('Set quantity to '+value,page).ok,false,value);});
test('ordinary pronoun price and details requests have bounded page-action framing and retain unknown-name refusal',()=>{const p=product(1),page=pageFor(p);for(const [message,type,section] of [['Highlight the price of this piece','highlight','price'],['Highlight the details of this piece','highlight','details'],['Scroll to the materials of the current product','scroll','materials'],['Show the selected price now','highlight','price']])assert.deepEqual(Bridge.resolve(message,page).action,{type,handle:p.handle,section});for(const message of ['Highlight the price of Hidden Pendant','Highlight details for Hidden Pendant','Scroll to Unknown Piece materials'])assert.equal(Bridge.resolve(message,page).ok,false,message);});
test('native menu targeting cannot borrow a known title contained inside an unknown title',()=>{const p=product(1),page=pageFor(p);for(const text of ['Open the metal menu for Hidden '+p.title,'Open the menu for '+p.title+' if it is cheaper','Open Platinum options']){const r=Bridge.resolve(text,page);assert.equal(r.ok,false,text);assert.equal(r.handled,true,text);}assert.deepEqual(Bridge.resolve('Open the Metal Choice menu for '+p.title,page).action,{type:'options',handle:p.handle,optionName:'Metal Choice'});});
test('a published product title cannot masquerade as an option group or an option choice',()=>{const p={...product(1),title:'Gold Filled Necklace'},page=pageFor(p);assert.deepEqual(Bridge.resolve('Select Sterling Silver for Gold Filled Necklace',page).action,{type:'select-option',handle:p.handle,optionName:'Metal Choice',optionValue:'Sterling Silver'});assert.equal(Bridge.resolve('Select Gold Filled Necklace',page).ok,false,'an option value inside the product title is not a setter request');const named={...p,title:'Metal Choice Necklace'},namedPage=pageFor(named);assert.deepEqual(Bridge.resolve('Open options for Metal Choice Necklace',namedPage).action,{type:'options',handle:p.handle});assert.deepEqual(Bridge.resolve('Open the Metal Choice menu for Metal Choice Necklace',namedPage).action,{type:'options',handle:p.handle,optionName:'Metal Choice'});});
test('unknown stock remains explicitly unconfirmed in bridge, spoken product and current selection projections',()=>{const p=product(1);p.variants.forEach(v=>{v.available=false;v.availabilityKnown=false;});const projected=Bridge.projectLiveProducts([p])[0],inspected=Actions.projectProduct(p,p,{readOnly:true}),page=pageFor(p);assert.ok(projected.variants.every(v=>v.available===false&&v.availabilityKnown===false));assert.ok(inspected.variants.every(v=>v.available===false&&v.availabilityKnown===false));for(const api of [Bridge.sanitizeSnapshot,Voice.publicContext]){const current=api(page).productControls.selectedVariant;assert.equal(current.available,false);assert.equal(current.availabilityKnown,false);}assert.equal(Actions.projectProduct(p,p),null,'unknown catalogue stock cannot become add/review authority');});
test('public current-price and bag totals project only bounded facts, never private notes or request properties',()=>{const p=product(1),page=pageFor(p);page.productControls.privateNotes='PRIVATE_NOTE_FIXTURE';page.productControls.selectedVariant.giftNote='PRIVATE_GIFT_FIXTURE';page.bagControls={lines:[{lineId:'fixture-line-37',productId:p.id,variantId:p.variants[0].id,quantity:2,title:p.title,variant:p.variants[0].title,price:50,currency:'USD',properties:{_request:'PRIVATE_REQUEST_FIXTURE'},note:'PRIVATE_NOTE_FIXTURE'}]};for(const api of [Bridge.sanitizeSnapshot,Voice.publicContext]){const result=api(page);assert.equal(result.bagControls.lines[0].lineTotalPrice,100);assert.equal(result.bagControls.lines[0].currency,'USD');assert.doesNotMatch(JSON.stringify(result),/PRIVATE_|properties|privateNotes|giftNote/);}});
test('discovery counts stay a qualified public sample and reject unsupported totals or private fields',()=>{const value={schema:1,source:'public_catalogue_sample',sampledListings:120,predictiveListings:10,candidateListings:123,exactListingsChecked:6,catalogueComplete:false,partial:true,privateNotes:'PRIVATE_FIXTURE'},projected=Widget.publicDiscovery(value);assert.equal(projected.sampledListings,120);assert.equal(projected.catalogueComplete,false);assert.equal(projected.partial,true);assert.doesNotMatch(JSON.stringify(projected),/PRIVATE|privateNotes/);for(const patch of [{catalogueComplete:true},{candidateListings:220},{exactListingsChecked:124},{sampledListings:999},{partial:'false'},{source:'admin_inventory'}])assert.equal(Widget.publicDiscovery({...value,...patch}),null);});
test('native occasion discovery preserves qualified checked-sample metadata in the real onTool response',async t=>{
  const p=product(1),discovery={schema:1,source:'public_catalogue_sample',sampledListings:120,predictiveListings:10,candidateListings:121,exactListingsChecked:1,catalogueComplete:false,partial:false,privateNotes:'PRIVATE_DISCOVERY_FIXTURE'},h=await fixture(t,{conciergeAnswer:{live:true,reply:'One exact available match from the checked catalogue sample.',preferences:{storeCategory:'regular-necklaces'},products:[p],meanings:[],discovery}});
  await h.activate();const text='Find a regular necklace for graduation',r=await h.tool('find_jewellery',{message:text},h.speak(text));
  assert.equal(r.verified,true,r.error);assert.equal(r.discovery.sampledListings,120);assert.equal(r.discovery.exactListingsChecked,1);assert.equal(r.discovery.catalogueComplete,false);
  assert.doesNotMatch(JSON.stringify(r),/PRIVATE_DISCOVERY_FIXTURE|privateNotes/);assert.equal(h.calls.requests.filter(request=>request.url.pathname==='/api/concierge'&&request.body?.message===text).length,1);
  assert.equal(h.d.querySelector('.piece-card h3').textContent,p.title);assert.deepEqual(h.cart(),[]);
});
test('native category discovery retains checked cached facts and qualified coverage while hiding control internals',async t=>{
  const h=await fixture(t,{checkedInventory:true});await h.activate();const r=shopperControlReceipt(await h.tool('find_jewellery',{message:'Find a regular necklace'},h.speak('Find a regular necklace')));
  assert.equal(r.ok,true,r.reply);assert.equal(r.verified,true,JSON.stringify({receiptKeys:Object.keys(r),loaded:h.store.getInventory().length,status:h.store.inventoryStatus()}));assert.equal(r.live,true);assert.equal(r.cached,true);assert.ok(Number.isSafeInteger(r.checkedAt)&&r.checkedAt>0);
  assert.equal(r.inventory.loaded,120);assert.equal(r.inventory.catalogueComplete,false);assert.equal(r.products.length,6);
  for(const p of r.products){const actual=h.products.find(item=>item.handle===p.handle);assert.ok(actual);assert.ok(Number.isSafeInteger(p.checkedAt)&&p.checkedAt>0);assert.equal(p.currency,'USD');assert.equal(p.matchingPriceRange.min,actual.minPrice);assert.ok(p.variants.every(v=>actual.variants.some(published=>published.id===v.id&&published.price===v.price&&published.available===v.available)));}
  assert.equal(h.d.querySelectorAll('.piece-card').length,6);assert.deepEqual(clone(h.store.snapshot().visiblePieces.map(p=>p.handle)),clone(r.products.map(p=>p.handle)));assert.deepEqual(h.cart(),[]);
});
test('typed subtype plus budget discovery uses the checked seed path and presents its exact matches in the real shopping grid',async t=>{const p=product(30,'beady-necklaces'),h=await fixture(t,{conciergeAnswer:{live:true,reply:'One exact beady necklace within the requested item budget.',preferences:{type:'necklace',storeCategory:'beady-necklaces',budget:80,budgetCurrency:'USD'},products:[p],meanings:[]}});const r=await h.send('Show beady necklaces under $80');assert.equal(r.ok,true,r.error);assert.equal(r.verified,true);assert.equal(h.calls.requests.filter(r=>r.body?.message==='Show beady necklaces under $80').length,1);assert.equal(h.calls.requests.some(r=>r.url.pathname==='/api/growth/catalogue'&&r.url.searchParams.has('q')),false);assert.equal(h.d.querySelectorAll('.piece-card').length,1);assert.equal(h.d.querySelector('.piece-card h3').textContent,p.title);assert.equal(JSON.parse(h.w.sessionStorage.getItem('brites-concierge-v1')).preferences.storeCategory,'beady-necklaces');assert.deepEqual(h.cart(),[]);assert.equal(h.calls.nativeStarts,0);});

test('the public command path opens an exact listing beyond the visible 24 and operates the real menu and selected price',async t=>{const h=await fixture(t),p=h.products[95];assert.equal(h.store.snapshot().loadedPieces.length,120);assert.equal(h.d.querySelectorAll('.piece-card').length,24);const opened=await h.send('Open '+p.title);assert.equal(opened.ok,true,opened.reply);assert.equal(h.d.querySelector('.product-copy h1').textContent,p.title);assert.equal(opened.snapshot.currentHandle,p.handle);assert.equal((await h.send('Highlight the price of this piece')).ok,true);assert.equal(h.d.querySelector('[data-store-section=price]').classList.contains('store-highlight'),true);assert.equal((await h.send('Highlight the details of this piece')).ok,true);assert.equal(h.d.querySelector('[data-store-section=details]').classList.contains('store-highlight'),true);assert.equal(h.root.querySelector('.composer').hidden,false);assert.equal(h.calls.nativeStarts,0);assert.equal((await h.send('Open the metal dropdown')).ok,true);assert.equal(h.d.querySelector('.option-menu').hidden,false);assert.equal((await h.send('Select Gold Filled')).ok,true);const group=p.options[1];assert.equal((await h.send('Select '+group.values[1])).ok,true);const current=h.store.snapshot().productControls;assert.equal(current.variantId,p.variants.at(-1).id);assert.equal(current.selectedVariant.price,p.variants.at(-1).price);assert.match(h.d.querySelector('.product-price').textContent,/71\.75/);assert.deepEqual(h.cart(),[]);assert.equal(h.calls.requests.filter(r=>r.url.pathname==='/api/concierge'&&r.body?.message).length,0);assert.equal(h.errors.length,0);});
test('public commands use collection filters and preserve exact storeCategory for the next conversation',async t=>{const h=await fixture(t);for(const [text,filter] of [['Show beady necklaces','beady-necklaces'],['Show stud earrings','stud-earrings'],['Show charm-only pieces','charm-only'],['Go back to the full collection','all']]){const r=await h.send(text);assert.equal(r.ok,true,r.reply);assert.equal(h.store.snapshot().filter,filter);if(filter!=='all')assert.ok([...h.d.querySelectorAll('.piece-card')].every(card=>h.products.find(p=>p.handle===card.dataset.productHandle).storeCategories.includes(filter)));const saved=JSON.parse(h.w.sessionStorage.getItem('brites-concierge-v1'));assert.equal(saved.preferences.storeCategory,filter==='all'?null:filter);}assert.deepEqual(h.cart(),[]);assert.equal(h.calls.requests.filter(r=>r.url.pathname==='/api/concierge'&&r.body?.message).length,0);});
test('native prepare view and options share the actual host controls even without an existing widget card',async t=>{
  const h=await fixture(t),p=h.products[2];await h.activate();assert.equal(h.root.querySelector('.card'),null);
  let turn=h.speak('Open '+p.title),r=shopperControlReceipt(await h.tool('prepare_jewellery_action',{handle:p.handle,action:'view'},turn));
  assert.equal(r.ok,true,r.reply);assert.equal(r.prepared,true);assert.equal(h.calls.controls.at(-1).action.type,'open');assert.equal(h.calls.controls.at(-1).action.handle,p.handle);assert.equal(h.calls.controls.at(-1).result.ok,true);
  assert.equal(h.store.snapshot().currentHandle,p.handle);assert.equal(h.d.querySelector('.product-copy h1').textContent,p.title);
  turn=h.speak('Open the metal dropdown');r=shopperControlReceipt(await h.tool('prepare_jewellery_action',{handle:p.handle,action:'options'},turn));
  assert.equal(r.ok,true,r.reply);assert.equal(r.prepared,true);assert.equal(h.calls.controls.at(-1).action.type,'options');assert.equal(h.calls.controls.at(-1).result.ok,true);
  assert.equal(h.store.snapshot().productControls.optionsOpen,true);assert.equal(h.d.querySelector('.option-menu').hidden,false);assert.equal(h.d.querySelector('[data-option-name="Metal Choice"]').hidden,false);
  assert.equal(h.root.querySelector('.options'),null,'no duplicate widget selector may stand in for the native menu');assert.equal(h.calls.nativeStops,0);assert.deepEqual(h.cart(),[]);assert.equal(h.errors.length,0);
});
test('native option controls change exact host selections while inspected facts retain selected material and price, with separate bag confirmation',async t=>{
  const h=await fixture(t),p=h.products[0];await h.activate();let turn=h.speak('Open '+p.title);
  assert.equal(shopperControlReceipt(await h.tool('control_storefront',{type:'open',handle:p.handle},turn)).ok,true);
  turn=h.speak('Select Gold Filled');let r=shopperControlReceipt(await h.tool('control_storefront',{type:'select-option',handle:p.handle,optionName:'Metal Choice',optionValue:'Gold Filled'},turn));
  assert.equal(r.ok,true,r.reply);assert.equal(h.calls.controls.at(-1).result.ok,true);assert.equal(h.store.snapshot().productControls.selectedVariant,null);assert.deepEqual(clone(h.store.snapshot().productControls.selectedOptions),[{name:'Metal Choice',value:'Gold Filled'}]);
  turn=h.speak('Select 18 inches');r=shopperControlReceipt(await h.tool('control_storefront',{type:'select-option',handle:p.handle,optionName:'Chain Length',optionValue:'18 inches'},turn));
  assert.equal(r.ok,true,r.reply);assert.equal(h.calls.controls.at(-1).result.ok,true);assert.equal(h.store.snapshot().productControls.selectedVariant.price,71.75);assert.deepEqual(clone(h.store.snapshot().productControls.selectedVariant.options),p.variants.at(-1).options);
  turn=h.speak('Set quantity to two');r=shopperControlReceipt(await h.tool('control_storefront',{type:'product-quantity',handle:p.handle,quantity:2},turn));
  assert.equal(r.ok,true,r.reply);assert.equal(h.calls.controls.at(-1).result.ok,true);assert.equal(h.store.snapshot().productControls.quantity,2);assert.equal(h.store.snapshot().productControls.itemTotalPrice,143.5);
  turn=h.speak('What is the price of my selected choice?');const inspected=await h.tool('inspect_jewellery',{handle:p.handle},turn);
  assert.equal(inspected.live,true,inspected.error);assert.equal(inspected.product.minPrice,50);assert.equal(inspected.product.selectedVariant.price,71.75);assert.equal(inspected.product.quantity,2);assert.equal(inspected.product.itemTotalPrice,143.5);assert.deepEqual(clone(inspected.product.selectedVariant.options),p.variants.at(-1).options);
  turn=h.speak('Review adding this piece to my bag');r=shopperControlReceipt(await h.tool('prepare_jewellery_action',{action:'review',handle:p.handle,variantId:p.variants.at(-1).id},turn));
  assert.equal(r.ok,true,r.reply);assert.equal(r.prepared,true);assert.equal(r.requiredCustomerClick,'Confirm add to test bag');assert.equal(h.store.snapshot().productControls.reviewReady,true);assert.equal(h.calls.controls.at(-1).result.snapshot.productControls.reviewReady,true);
  assert.match(h.d.querySelector('.product-review').textContent,/143\.50/);assert.deepEqual(h.cart(),[]);assert.equal(h.root.querySelector('.review'),null);
  h.d.querySelector('.product-review .primary').click();await settle();assert.equal(h.cart().length,1);assert.equal(h.cart()[0].quantity,2);assert.equal(h.cart()[0].variantId,p.variants.at(-1).numericId);assert.equal(h.calls.nativeStops,0);assert.equal(h.calls.requests.some(r=>/cart\/add|payment|\/checkout/.test(r.url.pathname)),false);
});
test('the actual final-of-250 native variant stays current in inspected facts and host review despite bounded option narration',async t=>{
  const p=product(1),values=Array.from({length:250},(_,n)=>'Size '+(n+1));p.options=[{name:'Published size',values}];p.variants=values.map((value,n)=>({id:'gid://shopify/ProductVariant/'+(370001+n),numericId:String(370001+n),title:value,price:50+n,available:true,options:[{name:'Published size',value}]}));
  const h=await fixture(t,{products:[p]});await h.send('Open '+p.title);const select=h.d.querySelector('#piece-variant'),last=p.variants.at(-1);select.value=last.id;select.dispatchEvent(new h.w.Event('change'));
  assert.equal(h.store.snapshot().productControls.optionGroups[0].values.length,250);assert.deepEqual(clone(h.store.snapshot().productControls.selectedOptions),last.options);await h.activate();
  let turn=h.speak('Tell me about the selected piece'),r=await h.tool('inspect_jewellery',{handle:p.handle},turn);
  assert.equal(r.product.selectedVariant.id,last.id,r.error);assert.equal(r.product.selectedVariant.price,299);assert.equal(r.product.variants.length,24);assert.equal(r.product.optionsTruncated,true);
  turn=h.speak('Review adding this piece to my bag');r=shopperControlReceipt(await h.tool('prepare_jewellery_action',{action:'review',handle:p.handle,variantId:last.id},turn));
  assert.equal(r.ok,true,r.reply);assert.equal(r.prepared,true);assert.equal(h.store.snapshot().productControls.selectedVariant.id,last.id);assert.equal(h.store.snapshot().productControls.reviewReady,true);assert.equal(h.calls.controls.at(-1).action.variantId,last.id);assert.equal(h.calls.controls.at(-1).result.snapshot.productControls.reviewReady,true);
  assert.ok(Buffer.byteLength(JSON.stringify(r),'utf8')<=20000);assert.match(h.d.querySelector('.product-review').textContent,/Size 250/);assert.deepEqual(h.cart(),[]);
});
test('a fresh inspection cannot quote a stale host selection price as current after exact price drift',async t=>{const h=await fixture(t),p=h.products[0];await h.send('Open '+p.title);await h.send('Select Gold Filled');await h.send('Select 18 inches');const old=h.store.snapshot().productControls.selectedVariant.price;p.variants.at(-1).price+=5;h.w.BritesSandboxStorefront=Object.freeze({...h.store,readProduct:async()=>null});await h.activate();const r=await h.tool('inspect_jewellery',{handle:p.handle},h.speak('What is the current selected price?'));assert.equal(r.live,true,r.error);assert.equal(r.product.selectionNeedsRefresh,true);assert.equal(r.product.selectedVariant,undefined);assert.equal(r.product.variants.at(-1).price,old+5);assert.deepEqual(h.cart(),[]);});
test('model preparation arguments cannot replace the finalized spoken target or replay the same action',async t=>{
  const h=await fixture(t),p=h.products[0],other=h.products[1];await h.activate();const turn=h.speak('Open '+p.title),before=h.calls.controls.length;
  const first=shopperControlReceipt(await h.tool('prepare_jewellery_action',{action:'view',handle:other.handle},turn));
  assert.equal(first.ok,true,first.reply);assert.equal(h.store.snapshot().currentHandle,p.handle);assert.equal(h.d.querySelector('.product-copy h1').textContent,p.title);assert.equal(h.calls.controls.length,before+1);assert.equal(h.calls.controls.at(-1).action.handle,p.handle);assert.notEqual(h.calls.controls.at(-1).action.handle,other.handle);
  for(const args of [{action:'view',handle:p.handle},{action:'view',handle:other.handle}]){const repeated=shopperControlReceipt(await h.tool('prepare_jewellery_action',args,turn));assert.equal(repeated.ok,false,repeated.reply);assert.equal(h.calls.controls.length,before+1);assert.equal(h.store.snapshot().currentHandle,p.handle);}
  assert.deepEqual(h.cart(),[]);
});
test('a manual option change after speech starts invalidates the native setter rather than switching a newer choice',async t=>{
  const h=await fixture(t),p=h.products[0];await h.send('Open '+p.title);await h.activate();const turn=h.speak('Select Gold Filled');
  const metal=h.d.querySelector('[data-option-name="Metal Choice"] [data-option-value="Sterling Silver"]');metal.click();const before=h.calls.controls.length;
  const r=shopperControlReceipt(await h.tool('control_storefront',{type:'select-option',handle:p.handle,optionName:'Metal Choice',optionValue:'Gold Filled'},turn));
  assert.equal(r.ok,false,r.reply);assert.equal(h.calls.controls.length,before);assert.deepEqual(clone(h.store.snapshot().productControls.selectedOptions),[{name:'Metal Choice',value:'Sterling Silver'}]);assert.deepEqual(h.cart(),[]);
});
test('pointer scope opens the actual attended listing and never falls back to another piece when no focus exists',async t=>{const h=await fixture(t),p=h.products[4],card=h.d.querySelector('[data-product-handle="'+p.handle+'"]');card.dispatchEvent(new h.w.Event('pointerover',{bubbles:true}));assert.equal(h.store.snapshot().focusedHandle,p.handle);assert.equal((await h.send('Open the piece I am pointing at')).ok,true);assert.equal(h.store.snapshot().currentHandle,p.handle);await h.send('Go back');const count=h.calls.requests.length,r=await h.send('Open the piece I am pointing at');assert.equal(r.ok,false);assert.equal(h.store.snapshot().currentHandle,'');assert.equal(h.calls.requests.filter(r=>r.url.pathname==='/api/concierge'&&r.body?.message).length,0);assert.ok(h.calls.requests.length>=count);});
test('an explicit review request supports a labelled charm-only review and requires its actual shopper confirmation',async t=>{const h=await fixture(t),p=h.products[95];assert.equal(p.type,'Charm');await h.send('Open '+p.title);await h.send('Select Sterling Silver');await h.send('Select Necklace charm only');const r=await h.send('Review adding this piece to my bag');assert.equal(r.ok,true,r.reply);assert.match(h.d.querySelector('.product-review').textContent,/Necklace charm only/);assert.deepEqual(h.cart(),[]);h.d.querySelector('.product-review .primary').click();await settle();assert.equal(h.cart().length,1);assert.equal(h.cart()[0].variantId,p.variants[0].numericId);assert.equal(h.errors.length,0);});
test('charm-only shared cart policy allows an exact reviewed published format while refusing components, holds and personalization',()=>{const p=product(1,'charm-only'),v=p.variants[0];assert.equal(Widget.needsCustomizer(p,v),false);assert.equal(Actions.projectProduct(p,p).partsOnly,true);assert.equal(Actions.resolveRequest({message:'Review adding '+p.title+' in Sterling Silver Necklace charm only to my bag',action:'review',handle:p.handle,variantId:v.id,products:[p]}).ok,true);for(const patch of [{type:'Components'},{type:'Add-ons'},{cartHold:true},{recommendationHold:true},{title:'Custom Charm'},{title:'Engraving Charm'},{title:'Personalized Charm'}]){const held={...p,...patch};assert.equal(Widget.needsCustomizer(held,v),true,JSON.stringify(patch));assert.equal(Actions.resolveRequest({message:'Review adding '+held.title+' in Sterling Silver Necklace charm only to my bag',action:'review',handle:p.handle,variantId:v.id,products:[held]}).ok,false,JSON.stringify(patch));}assert.equal(Widget.needsCustomizer(p,{...v,title:'Engraved',options:[{name:'Engraving',value:'Yes'}]}),true);});
test('declared-host held and unavailable inspection remains read-only and preserves the current flags',async t=>{const p=product(1);p.cartHold=true;p.variants.forEach(v=>v.available=false);const h=await fixture(t,{products:[p]});await h.send('Open '+p.title);await h.activate();const turn=h.speak('Tell me about this piece'),r=await h.tool('inspect_jewellery',{handle:p.handle},turn);assert.equal(r.live,true,r.error);assert.equal(r.product.cartHold,true);assert.ok(r.product.variants.every(v=>v.available===false));assert.deepEqual(h.cart(),[]);assert.equal(h.d.querySelector('.product-review'),null);});
test('explicit direct add starts checkout guidance while final simulation completion still needs acknowledgement and a separate click',async t=>{const h=await fixture(t),p=h.products[0];for(const text of ['Open '+p.title,'Select Sterling Silver','Select 16 inches','Add this piece to my bag'])assert.equal((await h.send(text)).ok,true,text);assert.equal(h.d.querySelector('.product-review'),null);assert.equal(h.cart().length,1);assert.equal(h.cart()[0].variantId,p.variants[0].numericId);await settle();for(const text of ['Open my bag','Open checkout','Show checkout shipping step','Choose express shipping','Show checkout confirmation step','Complete test checkout'])assert.equal((await h.send(text)).ok,true,text);const pc=h.store.snapshot().checkoutControls;assert.equal(pc.shipping,'express');assert.equal(pc.step,'confirm');assert.equal(pc.complete,false);assert.equal(h.d.querySelector('.receipt'),null);const check=h.d.querySelector('#confirm-test-checkout'),complete=[...h.d.querySelectorAll('button')].find(b=>b.textContent==='Complete test checkout');assert.equal(complete.disabled,true);check.checked=true;check.dispatchEvent(new h.w.Event('change'));complete.click();await settle();assert.ok(h.d.querySelector('.receipt'));assert.equal(h.store.snapshot().checkoutControls.complete,true);assert.equal(h.calls.requests.some(r=>/cart\/add|payment|\/checkout/.test(r.url.pathname)),false);});
test('the demo command entry rejects malformed input and blocked turns without opening or bypassing the host',async t=>{const h=await fixture(t);for(const text of [null,'','x'.repeat(2001),'Open\u0000 piece','Open\u202e piece']){const r=await h.send(text);assert.equal(r.ok,false);assert.equal(h.d.querySelector('brites-concierge').getAttribute('data-open'),'false');}h.hide();assert.equal((await h.send('Open '+h.products[0].title)).ok,false);assert.equal(h.store.snapshot().currentHandle,'');assert.equal(h.calls.nativeStarts,0);assert.deepEqual(h.cart(),[]);});
