'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),bridge=require('../../brites-storefront-bridge.js');
const clone=value=>JSON.parse(JSON.stringify(value)),piece={id:'gid://shopify/Product/3941',handle:'strawberry-charm-beady-necklace',title:'Strawberry Beady Necklace'};
function page(){return {contextRevision:1,controlVersion:1,pageKind:'product',currentHandle:piece.handle,visiblePieces:[piece],loadedPieces:[piece],inventoryPieces:[piece],engravingControls:{available:true,enabled:true,hasText:false,maxLength:300},productControls:{handle:piece.handle,productId:piece.id,variantId:'gid://shopify/ProductVariant/39411',quantity:1,optionGroups:[{name:'Metal Choice',values:['Sterling Silver','14k Gold Filled','14k Solid Gold']},{name:'Chain Length',values:['14"','16"','18"','20"']},{name:'Engraving',values:['None','Add Engraving']}],selectedOptions:[{name:'Metal Choice',value:'Sterling Silver'},{name:'Chain Length',value:'16"'},{name:'Engraving',value:'None'}]}};}
for(const suffix of ['18 inch','18 inches','18 in','18inch','18in','18"','18″','18”'])test('an explicit inch unit resolves to the exact published length: '+suffix,()=>{const p=page(),before=clone(p),r=bridge.resolve('Select '+suffix,p);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,{type:'select-option',handle:piece.handle,optionName:'Chain Length',optionValue:'18"'});assert.deepEqual(p,before);});
test('the exact published group can qualify an inch-unit alias without changing other options',()=>{for(const text of ['Select Chain Length 18 inch','Choose length 18 inches','Set Chain Length to 18 in','Select 18 inches for Strawberry Beady Necklace']){const r=bridge.resolve(text,page());assert.equal(r.ok,true,text+': '+r.reason);assert.equal(r.action.optionName,'Chain Length');assert.equal(r.action.optionValue,'18"');}});
test('bare numbers, metal fineness, metric values and malformed precision cannot guess an inch length',()=>{for(const text of ['Select 18','Select 18k','Select 18 karat','Select 18 cm','Select 18mm','Select 18 feet','Select 18.5 inch','Select 18.0 inch','Select length 14k','Select 118 inches','Select -18 inch','Select 18 inches and 20 inches','Select 18 inches or 20 inches','Select 18 inches if I ask','Select 18 inches for Unicorn Necklace']){const p=page(),before=clone(p),r=bridge.resolve(text,p);assert.equal(r.ok,false,text);assert.deepEqual(p,before,text);}});
test('equivalent published aliases remain ambiguous and multiple groups require an exact published label',()=>{const p=page();p.productControls.optionGroups[1].values.push('18 in');assert.equal(bridge.resolve('Select 18 inches',p).ok,false);const groups=page();groups.productControls.optionGroups.push({name:'Pendant Length',values:['18"']});assert.equal(bridge.resolve('Select 18 inch',groups).ok,false);assert.deepEqual(bridge.resolve('Select Chain Length 18 inch',groups).action,{type:'select-option',handle:piece.handle,optionName:'Chain Length',optionValue:'18"'});const size=page();size.productControls.optionGroups.push({name:'Size',values:['18"']});assert.equal(bridge.resolve('Select 18 inch',size).ok,false);const metal=page();metal.productControls.optionGroups=[{name:'Metal Choice',values:['18"']}];assert.equal(bridge.resolve('Select 18 inch',metal).ok,false);});
test('inch normalization never changes literal engraving or gift-note text',()=>{for(const [text,field] of [['Set engraving text to PRIVATE 18 inch and 14k','text'],['Set gift note to PRIVATE 18 inches and 14k','giftNote']]){const r=bridge.resolve(text,page());assert.equal(r.ok,true,r.reason);assert.equal(r.action[field],text.replace(/^Set (?:engraving text|gift note) to /,''));assert.equal(bridge.redactRequestText(text).includes('PRIVATE'),false);}});
