'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(require.resolve('../../concierge-sandbox.html'),'utf8'),source=fs.readFileSync(require.resolve('../../concierge-sandbox.js'),'utf8'),catalogueSource=fs.readFileSync(require.resolve('../../brites-catalogue-intents.js'),'utf8');
const clone=value=>JSON.parse(JSON.stringify(value)),settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
function deferred(){let resolve;const promise=new Promise(done=>{resolve=done;});return {promise,resolve};}
function piece(){return {id:'gid://shopify/Product/4301',handle:'butterfly-earrings',title:'Butterfly Earrings',type:'Earrings',description:'Published synthetic butterfly earrings. Charm size: 12 mm.',url:'https://britesjewelry.com/products/butterfly-earrings',currency:'USD',image:'https://cdn.shopify.com/butterfly-one.jpg',images:[{url:'https://cdn.shopify.com/butterfly-one.jpg'},{url:'https://cdn.shopify.com/butterfly-two.jpg'}],options:[{name:'Metal Choice',values:['Sterling Silver','Gold Filled']},{name:'Hoop Size',values:['10 mm','12 mm']}],variantsComplete:true,variants:[['Sterling Silver','10 mm',43011,51.25],['Gold Filled','10 mm',43012,65.50],['Sterling Silver','12 mm',43013,53.75],['Gold Filled','12 mm',43014,68.25]].map(([metal,size,id,price])=>({id:'gid://shopify/ProductVariant/'+id,title:metal+' / '+size,price,available:true,options:[{name:'Metal Choice',value:metal},{name:'Hoop Size',value:size}]}))};}
function response(data){return {ok:true,json:async()=>clone(data)};}
function fixture(t,patch={},extras=[]){
  const errors=[],requests=[],console=new VirtualConsole();console.on('jsdomError',error=>errors.push(error));const dom=new JSDOM(html,{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:console}),w=dom.window,d=w.document,p={...piece(),...patch};let lookup=null;
  delete d.body.dataset.catalogueSeed;delete d.body.dataset.inventoryPreload;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=function(){};
  w.fetch=async(raw,init={})=>{const url=new URL(raw,w.location.href);requests.push({url,init});if(url.pathname==='/api/growth/catalogue')return response({live:true,products:[p,...extras],pageInfo:{hasNextPage:false,endCursor:null}});if(url.pathname==='/api/growth/product')return lookup?lookup(url,init):response({live:true,product:p});if(url.pathname==='/api/growth/storefront-services')return response({schema:1,guidance:{},conflicts:[],offers:{items:[],status:'published_not_checkout_validated'}});throw Error('Unexpected route '+url.pathname);};
  w.eval(catalogueSource);w.eval(source);t.after(()=>w.close());return {w,d,p,requests,errors,ready:settle,get store(){return w.BritesSandboxStorefront;},lookup:next=>{lookup=next;},cart:()=>JSON.parse(w.sessionStorage.getItem('brites-sandbox-cart')||'[]'),async open(){assert.equal((await this.store.execute({type:'open',handle:p.handle})).ok,true);},async choose(index=0){assert.equal((await this.store.execute({type:'select-option',handle:p.handle,variantId:p.variants[index].id})).ok,true);}};
}

test('guided options open the next exact group, quote its choices and keep the shopper in control',async t=>{
  const h=fixture(t);await h.ready();await h.open();const initial=h.store.snapshot().productControls;assert.equal(initial.selectionStatus,'choosing');assert.deepEqual(clone(initial.requiredOptions),['Metal Choice','Hoop Size']);
  await h.store.execute({type:'options',optionName:'Metal Choice'});const metal=await h.store.execute({type:'select-option',optionName:'Metal Choice',optionValue:'Sterling Silver'});
  assert.equal(metal.ok,true);assert.equal(metal.snapshot.productControls.openedOption,'Hoop Size');assert.deepEqual(clone(metal.snapshot.productControls.requiredOptions),['Hoop Size']);assert.match(metal.message,/Hoop Size.*10 mm.*12 mm/);assert.equal(h.d.querySelector('[data-option-name="Hoop Size"]').hidden,false);assert.equal(h.d.querySelector('[data-option-name="Metal Choice"]').hidden,true);assert.deepEqual(h.cart(),[]);
  const size=await h.store.execute({type:'select-option',optionName:'Hoop Size',optionValue:'12 mm'});assert.equal(size.snapshot.productControls.selectionStatus,'ready');assert.equal(size.snapshot.productControls.selectedVariant.id,h.p.variants[2].id);assert.match(size.message,/53\.75 USD.*add it to my bag/);assert.deepEqual(h.cart(),[]);assert.equal(h.errors.length,0);
});

test('incomplete direct add visibly opens only the remaining option and never invents a variant',async t=>{
  const h=fixture(t);await h.ready();await h.open();await h.store.execute({type:'select-option',optionName:'Metal Choice',optionValue:'Gold Filled'});const reads=h.requests.length,r=await h.store.execute({type:'add',handle:h.p.handle},{requestId:'missing-1'});
  assert.equal(r.ok,false);assert.equal(r.reason,'missing-options');assert.equal(r.cartChanged,false);assert.equal(r.snapshot.productControls.openedOption,'Hoop Size');assert.equal(r.snapshot.productControls.variantId,null);assert.match(r.message,/Hoop Size.*10 mm.*12 mm/);assert.equal(h.requests.length,reads);assert.deepEqual(h.cart(),[]);
});

test('an explicit configured add checks fresh identity, quantity, price and options without a redundant confirmation click',async t=>{
  const h=fixture(t);await h.ready();await h.open();await h.choose(1);await h.store.execute({type:'product-quantity',quantity:2});const reads=h.requests.filter(r=>r.url.pathname==='/api/growth/product').length,r=await h.store.execute({type:'add',handle:h.p.handle,variantId:h.p.variants[1].id},{requestId:'direct-1'});
  assert.equal(r.ok,true);assert.equal(r.cartChanged,true);assert.equal(r.added.quantity,2);assert.equal(r.added.subtotal,131);assert.equal(r.added.currency,'USD');assert.equal(r.orderPlaced,false);assert.equal(r.paymentTaken,false);assert.equal(r.requiredCustomerClick,undefined);assert.equal(h.cart().length,1);assert.equal(h.cart()[0].quantity,2);assert.equal(h.cart()[0].variantId,'43012');assert.deepEqual(h.cart()[0].variantOptions,clone(h.p.variants[1].options).sort((a,b)=>a.name.localeCompare(b.name)));assert.equal(h.d.querySelector('#bag-count').textContent,'2');assert.equal(h.requests.filter(r=>r.url.pathname==='/api/growth/product').length,reads+1);assert.equal(h.d.querySelector('.product-review'),null);assert.equal(r.snapshot.productControls.busy,false);assert.equal(h.requests.some(r=>/cart\/add|checkout\//.test(r.url.pathname)),false);
  await h.store.execute({type:'bag'});const bag=h.store.snapshot().bagControls;assert.equal(bag.lines[0].subtotal,131);assert.equal(bag.total,131);assert.equal(bag.currency,'USD');assert.equal(bag.lines[0].lineId,r.added.lineId);const changed=await h.store.execute({type:'bag-quantity',lineId:bag.lines[0].lineId,quantity:3});assert.equal(changed.ok,true);assert.equal(changed.snapshot.bagControls.total,196.50);assert.equal(changed.snapshot.bagControls.lines[0].lineId,r.added.lineId);const removed=await h.store.execute({type:'bag-remove',lineId:bag.lines[0].lineId});assert.equal(removed.ok,true);assert.deepEqual(h.cart(),[]);assert.equal(h.errors.length,0);
});

test('same add request is idempotent while pending and on retry; a new explicit request adds once more',async t=>{
  const h=fixture(t);await h.ready();await h.open();await h.choose();const gate=deferred();let checks=0;h.lookup(()=>{checks++;return gate.promise;});const first=h.store.execute({type:'add'},{requestId:'same-1'}),duplicate=h.store.execute({type:'add'},{requestId:'same-1'});gate.resolve(response({live:true,product:h.p}));const results=await Promise.all([first,duplicate]);assert.equal(results.every(r=>r.ok),true);assert.equal(results[1].deduplicated,true);assert.equal(checks,1);assert.equal(h.cart().length,1);const retry=await h.store.execute({type:'add'},{requestId:'same-1'});assert.equal(retry.deduplicated,true);assert.equal(retry.cartChanged,false);assert.equal(checks,1);assert.equal(h.cart().length,1);
  h.lookup(null);assert.equal((await h.store.execute({type:'add'},{requestId:'new-2'})).ok,true);assert.equal(h.cart().length,2);await h.choose(1);assert.equal((await h.store.execute({type:'add'},{requestId:'same-1'})).ok,false);assert.equal(h.cart().length,2);
});

for(const drift of ['price','currency','availability','option','identity','partial','held','duplicate'])test('direct add rejects fresh '+drift+' drift without changing the test bag',async t=>{
  const h=fixture(t);await h.ready();await h.open();await h.choose();const changed=clone(h.p);
  if(drift==='price')changed.variants[0].price+=1;if(drift==='currency')changed.currency='CAD';if(drift==='availability')changed.variants[0].available=false;if(drift==='option')changed.variants[0].options[1].value='20 mm';if(drift==='identity')changed.id='gid://shopify/Product/999';if(drift==='partial')changed.variantsComplete=false;if(drift==='held')changed.cartHold=true;if(drift==='duplicate')changed.variants.push(clone(changed.variants[0]));h.lookup(()=>response({live:true,product:changed}));const r=await h.store.execute({type:'add'},{requestId:'drift-1'});assert.equal(r.ok,false);assert.equal(r.cartChanged,false);assert.deepEqual(h.cart(),[]);assert.equal(h.store.snapshot().productControls.variantId,drift==='option'?null:h.p.variants[0].id);if(drift==='price')assert.equal(h.store.snapshot().productControls.selectedVariant.price,changed.variants[0].price);if(drift==='availability')assert.equal(h.store.snapshot().productControls.selectionStatus,'unavailable');
});

for(const cancel of ['signal','navigation'])test('a delayed direct add cancels on '+cancel+' and a later response cannot revive it',async t=>{
  const h=fixture(t);await h.ready();await h.open();await h.choose();const gate=deferred(),controller=new h.w.AbortController();h.lookup(()=>gate.promise);const pending=h.store.execute({type:'add'},{signal:controller.signal,requestId:'cancel-1'});if(cancel==='signal')controller.abort();else await h.store.execute({type:'bag'});const result=await pending;assert.equal(result.ok,false);assert.equal(result.reason,'cancelled');assert.deepEqual(h.cart(),[]);gate.resolve(response({live:true,product:h.p}));await settle();assert.deepEqual(h.cart(),[]);if(cancel==='navigation')assert.equal(h.store.snapshot().pageKind,'bag');
});

test('missing, foreign and unsupported choices preserve actual options; incompatible combinations offer a concrete correction',async t=>{
  const p=piece(),h=fixture(t,{variants:p.variants.slice(0,3)});await h.ready();await h.open();await h.choose(2);const before=clone(h.store.snapshot().productControls);for(const action of [{type:'select-option',optionName:'Metal Choice',optionValue:'Platinum'},{type:'add',handle:'other-earrings'},{type:'add',variantId:p.variants[0].id},{type:'add',quantity:2}])assert.equal((await h.store.execute(action,{requestId:'unsupported-1'})).ok,false);assert.deepEqual(clone(h.store.snapshot().productControls),before);assert.deepEqual(h.cart(),[]);
  await h.store.execute({type:'select-option',optionName:'Metal Choice',optionValue:'Gold Filled'});const invalid=h.store.snapshot().productControls;assert.equal(invalid.variantId,null);assert.equal(invalid.selectionStatus,'unavailable');assert.ok(invalid.requiredOptionGroups.some(g=>g.name==='Hoop Size'&&g.values.includes('10 mm')));const r=await h.store.execute({type:'add'});assert.equal(r.ok,false);assert.match(r.message,/unavailable.*Adjust/);assert.deepEqual(h.cart(),[]);assert.equal((await h.store.execute({type:'select-option',optionName:'Hoop Size',optionValue:'10 mm'})).snapshot.productControls.variantId,p.variants[1].id);
});

test('a full bounded bag cannot silently discard earlier lines on an additional add',async t=>{
  const h=fixture(t);await h.ready();await h.open();await h.choose();const item={productId:h.p.id,title:h.p.title,variantId:'43011',variant:h.p.variants[0].title,price:51.25,currency:'USD'},saved=Array.from({length:50},()=>clone(item));h.w.sessionStorage.setItem('brites-sandbox-cart',JSON.stringify(saved));const before=JSON.stringify(h.cart()),reads=h.requests.length,r=await h.store.execute({type:'add'},{requestId:'full-1'});assert.equal(r.ok,false);assert.equal(r.reason,'bag-full');assert.equal(JSON.stringify(h.cart()),before);assert.equal(h.requests.length,reads);
});

test('checkout stays a labelled simulation with exact totals, visible acknowledgement and no real order',async t=>{
  const h=fixture(t);await h.ready();await h.open();await h.choose();assert.equal((await h.store.execute({type:'add'},{requestId:'checkout-1'})).ok,true);const start=await h.store.execute({type:'checkout'});assert.equal(start.ok,true);assert.equal(start.snapshot.checkoutControls.mode,'simulation-only');assert.equal(start.snapshot.checkoutControls.orderPlaced,false);await h.store.execute({type:'checkout-step',step:'shipping'});await h.store.execute({type:'checkout-option',option:'shipping',value:'express'});const review=await h.store.execute({type:'checkout-complete'});assert.equal(review.requiredCustomerClick,'Complete test checkout');assert.equal(h.d.querySelector('.receipt'),null);const acknowledgement=h.d.querySelector('#confirm-test-checkout');acknowledgement.checked=true;acknowledgement.dispatchEvent(new h.w.Event('change',{bubbles:true}));[...h.d.querySelectorAll('button')].find(b=>b.textContent==='Complete test checkout').click();await settle();assert.ok(h.d.querySelector('.receipt'));assert.equal(h.store.snapshot().checkoutControls.complete,true);assert.equal(h.store.snapshot().checkoutControls.paymentTaken,false);assert.equal(h.cart().length,1);assert.equal(h.requests.some(r=>r.init.method&&r.init.method!=='GET'),false);
});

test('host searches use shared butterfly and animal semantics with correct product type and same-variant budgets',async t=>{
  const product=(title,type,id)=>{const p=piece(),handle=title.toLowerCase().replace(/ /g,'-');return {...p,id:'gid://shopify/Product/'+id,handle,title,type,url:'https://britesjewelry.com/products/'+handle,description:'A published piece. Compare our butterfly earrings or animal necklaces too.'};},cat=product('Cat Stud Earrings','Earrings',4302),butterflyNecklace=product('Butterfly Necklace','Necklace',4303),moon=product('Moon Earrings','Earrings',4304),h=fixture(t,{},[cat,butterflyNecklace,moon]);await h.ready();
  let r=await h.store.execute({type:'search',query:'Do you have butterfly earrings?'});assert.equal(r.ok,true);assert.deepEqual(clone(r.products.map(p=>p.handle)),['butterfly-earrings']);
  r=await h.store.execute({type:'search',query:'What animal earrings do you have?'});assert.deepEqual(clone(r.products.map(p=>p.handle)),['butterfly-earrings','cat-stud-earrings']);
  r=await h.store.execute({type:'search',query:'What do you have?'});assert.equal(r.products.length,4);assert.equal(r.snapshot.inventory.catalogueComplete,false);
  r=await h.store.execute({type:'search',query:'Gold filled butterfly earrings under USD 60'});assert.deepEqual(clone(r.products),[]);
  r=await h.store.execute({type:'search',query:'Gold filled butterfly earrings under USD 70'});assert.deepEqual(clone(r.products.map(p=>p.handle)),['butterfly-earrings']);assert.deepEqual(clone(r.products[0].matchingVariantIds),[h.p.variants[1].id,h.p.variants[3].id]);
});
