'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const bridge=require('../../brites-storefront-bridge.js');
const clone=value=>JSON.parse(JSON.stringify(value));
const pieces=[{id:'gid://shopify/Product/3901',handle:'strawberry-charm',title:'Strawberry Charm'},{id:'gid://shopify/Product/3902',handle:'strawberry-charm-beady-necklace',title:'Strawberry Charm Beady Necklace'},{id:'gid://shopify/Product/3903',handle:'moon-charm',title:'Moon Charm'}];
const chosen=pieces[1],variantId='gid://shopify/ProductVariant/3911';
function page(){return {contextRevision:1,controlVersion:1,pageKind:'product',currentHandle:chosen.handle,focusedHandle:pieces[2].handle,visiblePieces:pieces,loadedPieces:pieces,inventoryPieces:pieces,navigationControls:{canGoBack:true,canGoForward:true},galleryControls:{handle:chosen.handle,imageCount:12,selectedIndex:1},imageControls:{open:false},changeControls:{canUndo:true,kind:'select-option'},engravingControls:{available:true,enabled:true,hasText:false,maxLength:300},productControls:{handle:chosen.handle,productId:chosen.id,variantId,quantity:1,optionsOpen:false,optionGroups:[{name:'Metal Choice',values:['Sterling Silver','14k Gold Filled','14k Solid Gold']},{name:'Chain Length',values:['16 inches','18 inches']}],selectedOptions:[{name:'Metal Choice',value:'Sterling Silver'},{name:'Chain Length',value:'16 inches'}],selectedVariant:{id:variantId,title:'Sterling Silver / 16 inches',price:50,currency:'USD',available:true,options:[{name:'Metal Choice',value:'Sterling Silver'},{name:'Chain Length',value:'16 inches'}]}},bagControls:{lines:[]}};}
const capabilities={controlVersion:1,mode:'sandbox',actions:['open','highlight','zoom','scroll','bag','checkout','back','forward','gallery','options','close-options','close-image','undo','set-engraving','select-option','product-quantity','review-add','gift-preferences','bag-quantity','bag-remove','sort','filter'],reviewBeforeAdd:true,checkoutMode:'simulation-only',notesMode:'local-session'};
function harness({failure,waitFor,after}={}){let state=page(),privateText='';const calls=[];const host={capabilities,snapshot:()=>clone(state),async execute(action,options){calls.push({action:clone(action),options});if(waitFor&&action.type===waitFor.type)await waitFor.promise;if(options.signal.aborted)return {ok:false,cancelled:true};if(failure?.type===action.type)return {ok:false,message:failure.message};switch(action.type){case 'open':state.currentHandle=action.handle;state.pageKind='product';state.productControls.handle=action.handle;state.galleryControls.handle=action.handle;break;case 'options':state.productControls.optionsOpen=true;break;case 'close-options':state.productControls.optionsOpen=false;break;case 'close-image':state.imageControls.open=false;break;case 'zoom':state.imageControls.open=true;break;case 'gallery':state.galleryControls.selectedIndex=action.index;break;case 'product-quantity':state.productControls.quantity=action.quantity;break;case 'select-option':state.productControls.selectedOptions.find(v=>v.name===action.optionName).value=action.optionValue;state.productControls.selectedVariant=null;break;case 'review-add':state.productControls.reviewReady=true;break;case 'set-engraving':privateText=action.text;state.engravingControls.hasText=!!privateText;break;case 'bag':state.pageKind='bag';break;case 'checkout':state.pageKind='checkout';break;case 'gift-preferences':privateText=action.giftNote||'';break;}state.contextRevision++;if(after)after(action,state);return {ok:true,message:'Completed '+action.type,prepared:action.type==='review-add'};}};return {api:bridge.create({storefront:host}),calls,read:()=>clone(state),edit(fn){fn(state);},text:()=>privateText};}
for(const [message,expected] of [
 ['Open Strawberry Charm Beady Necklace',{type:'open',handle:chosen.handle}],
 ['Navigate to Strawberry Charm Beady Necklace',{type:'open',handle:chosen.handle}],
 ['I want to see Strawberry Charm Beady Necklace',{type:'open',handle:chosen.handle}],
 ['Let me see Strawberry Charm Beady Necklace',{type:'open',handle:chosen.handle}],
 ['Show cart',{type:'bag'}],['Go to cart',{type:'bag'}],['Show me my bag',{type:'bag'}],
 ['Proceed to checkout',{type:'checkout'}],['Continue to checkout',{type:'checkout'}],
 ['Scroll down the page',{type:'scroll',direction:'down'}],['Scroll up a little',{type:'scroll',direction:'up'}],
 ['Back to results',{type:'back'}],['Go back to my search results',{type:'back'}],['Take me back to the previous collection',{type:'back'}],
 ['Undo that',{type:'undo'}],['Reverse that',{type:'undo'}],['Revert the last change',{type:'undo'}],
 ['Close the menu',{type:'close-options'}],['Hide the metal dropdown',{type:'close-options'}],['Close the image',{type:'close-image'}],
 ['Highlight the dropdown',{type:'highlight',handle:chosen.handle,section:'options'}],
 ['Open the listing I am hovering over',{type:'open',handle:pieces[2].handle}],
 ['Show me the one my mouse is over',{type:'open',handle:pieces[2].handle}],
 ['What earrings do you have?',{type:'filter',filter:'earrings'}]
])test('current command resolves exact controls: '+message,()=>assert.deepEqual(bridge.resolve(message,page()).action,expected));
test('ordinary product question delegates knowledge without highlighting or changing the page',()=>{const r=bridge.resolve('What materials is this piece available in, and what are its prices?',page());assert.equal(r.delegated,'knowledge');assert.equal(r.targetHandle,chosen.handle);assert.equal(r.action,undefined);});
test('natural fact and advice vocabulary scopes the current piece while unseen names stay unresolved',()=>{for(const text of ['What are its dimensions?','How much does the gold filled version cost?','Can I get this in gold filled?','What material is cheapest?','What does solid gold cost compared with silver?','Which material would you recommend for everyday wear?'])assert.equal(bridge.resolveKnowledgeTarget(text,page()).handle,chosen.handle,text);for(const text of ['What are the dimensions of Unicorn Necklace?','How much does the Unicorn gold filled version cost?','Compare this with Unicorn Necklace'])assert.equal(bridge.resolveKnowledgeTarget(text,page()).handle,undefined,text);});
test('unseen review target cannot borrow the current exact product',()=>{for(const message of ['Add unicorn to my cart','Add Silver unicorn necklace to my cart','Add Moon Charm to my cart'])assert.equal(bridge.resolve(message,page()).ok,false,message);});
test('explicit quantity and indexed zoom cannot silently collapse to an existing quantity or image',()=>{assert.equal(bridge.resolve('Add two of this to my cart',page()).ok,false);assert.equal(bridge.resolve('Zoom image 2',page()).ok,false);const add=bridge.resolvePlan('Add two of this to my cart',page()),zoom=bridge.resolvePlan('Zoom image 2',page());assert.equal(add.ok,true);assert.deepEqual(add.plan.steps.map(s=>s.text),['Set quantity to 2 for '+chosen.handle,'Add this to my bag']);assert.equal(zoom.ok,true);assert.deepEqual(zoom.plan.steps.map(s=>s.text),['Show image 2','Enlarge this piece']);});
test('quantity then review uses fresh actual controls and terminal separate review authority',async()=>{const h=harness(),plan=h.api.resolvePlan('Add two of this to my cart'),tokens=[];const r=await h.api.executePlan(plan.plan,{requestId:'qty-review',reviewAuthority(action,id,current){const token={};tokens.push({action,id,current,token});return token;}});assert.equal(r.ok,true);assert.deepEqual(h.calls.map(c=>c.action.type),['product-quantity','review-add']);assert.equal(h.read().productControls.quantity,2);assert.equal(h.read().productControls.reviewReady,true);assert.equal(tokens[0].current.productControls.quantity,2);assert.equal(tokens[0].id,'qty-review-step-2');assert.equal(h.calls[1].options.reviewAuthority,tokens[0].token);assert.equal(r.stepResults[1].prepared,true);assert.equal(r.cartChanged,undefined);});
test('indexed enlargement selects the requested image before opening its actual viewer',async()=>{const h=harness(),resolved=h.api.resolvePlan('Enlarge the third image'),r=await h.api.executePlan(resolved.plan);assert.equal(r.ok,true);assert.equal(h.read().galleryControls.selectedIndex,3);assert.equal(h.read().imageControls.open,true);assert.deepEqual(r.completedActions,[{type:'gallery',handle:chosen.handle,index:3},{type:'zoom',handle:chosen.handle}]);});
test('up to four ordered explicit commands run sequentially against current snapshots',async()=>{const h=harness(),resolved=h.api.resolvePlan('Open Strawberry Charm Beady Necklace then open the metal menu and select 14k Gold Filled and highlight the price');assert.equal(resolved.ok,true);const r=await h.api.executePlan(resolved.plan);assert.equal(r.ok,true,r.reason);assert.deepEqual(h.calls.map(c=>c.action.type),['open','options','select-option','highlight']);assert.equal(h.read().productControls.selectedOptions[0].value,'14k Gold Filled');assert.equal(r.partial,false);});
test('a compound price display preserves both opening and highlighting',async()=>{const h=harness(),r=await h.api.executePlan(h.api.resolvePlan('Open Strawberry Charm Beady Necklace then show its price').plan);assert.equal(r.ok,true);assert.deepEqual(h.calls.map(c=>c.action.type),['open','highlight']);});
test('an unsupported next step reports partial completion and never claims the rest succeeded',async()=>{const h=harness(),p=h.api.resolvePlan('Open Strawberry Charm Beady Necklace then select Platinum then show my cart');assert.equal(p.ok,true);const r=await h.api.executePlan(p.plan);assert.equal(r.ok,false);assert.equal(r.partial,true);assert.equal(r.completedActions.length,1);assert.doesNotMatch(r.reply,/Completed \d+ of \d+|remaining website actions/i);assert.match(r.reply,/published option value/);assert.equal(h.calls.length,1);assert.equal(h.read().pageKind,'product');});
test('a failed host step stops subsequent commands and gives its concrete friendly reason',async()=>{const h=harness({failure:{type:'gallery',message:'That published image is unavailable.'}}),r=await h.api.executePlan(h.api.resolvePlan('Zoom image 2').plan);assert.equal(r.ok,false);assert.equal(r.partial,false);assert.match(r.reply,/published image is unavailable/);assert.equal(h.calls.length,1);});
test('native transcript authority is consumed once for the whole plan and cannot replay its steps',async()=>{const h=harness(),p=h.api.resolvePlan('Open the metal menu then select 14k Gold Filled'),opts={source:'native',transcript:'Open the metal menu then select 14k Gold Filled',context:page(),inputItemId:'input-39',turnVersion:7,currentTurn:true,requestId:'native-39'},r=await h.api.executePlan(p.plan,opts);assert.equal(r.ok,true,r.reason);const duplicate=await h.api.executePlan(p.plan,opts);assert.equal(duplicate.suppressed,true);assert.equal(h.calls.length,2);const action=bridge.resolve('Open my cart',h.read());assert.equal((await h.api.execute(action.action,{...opts,transcript:'Open my cart',context:h.read()})).suppressed,true);assert.equal(h.calls.length,2);});
test('a copied or forged plan has no execution capability, and transcript substitution is rejected',async()=>{const h=harness(),p=h.api.resolvePlan('Open the metal menu then select 14k Gold Filled');assert.equal((await h.api.executePlan(clone(p.plan))).ok,false);assert.equal((await h.api.executePlan(p.plan,{transcript:'Open my cart'})).ok,false);assert.equal(h.calls.length,0);});
test('changed source selection and declined native current-turn authority cannot start a sequence',async()=>{const h=harness(),p=h.api.resolvePlan('Open the metal menu then select 14k Gold Filled');h.edit(s=>s.contextRevision++);assert.equal((await h.api.executePlan(p.plan)).stale,true);assert.equal(h.calls.length,0);const fresh=h.api.resolvePlan('Open the metal menu then select 14k Gold Filled');assert.equal((await h.api.executePlan(fresh.plan,{source:'native',inputItemId:'old',turnVersion:1,currentTurn:false})).ok,false);assert.equal(h.calls.length,0);});
test('cancelling an in-flight sequence prevents its remaining image or option step',async()=>{let release;const promise=new Promise(r=>release=r),h=harness({waitFor:{type:'gallery',promise}}),resolved=h.api.resolvePlan('Zoom image 2'),pending=h.api.executePlan(resolved.plan);await new Promise(setImmediate);h.api.cancel();release();const r=await pending;assert.equal(r.ok,false);assert.equal(r.cancelled,true);assert.equal(h.calls.length,1);assert.equal(h.read().imageControls.open,false);});
test('new explicit singleton control interrupts old remaining sequence work',async()=>{let release;const promise=new Promise(r=>release=r),h=harness({waitFor:{type:'gallery',promise}}),pending=h.api.executePlan(h.api.resolvePlan('Zoom image 2').plan);await new Promise(setImmediate);const action=h.api.resolve('Open my cart'),changed=h.api.execute(action.action);release();assert.equal((await changed).ok,true);assert.equal((await pending).ok,false);assert.equal(h.read().pageKind,'bag');assert.equal(h.calls.some(c=>c.action.type==='zoom'),false);});
test('unsafe, quoted, hypothetical and excessive command sequences never authorize execution',()=>{for(const text of ['"Open my cart then select Gold"','If I ask, open the metal menu then select 14k Gold Filled','Open the metal menu then do not select 14k Gold Filled','Open the metal menu then select 14k Gold Filled if I ask','Open the metal menu then open https://example.com','Open the menu then select Gold then show cart then open checkout then scroll down'])assert.equal(bridge.resolvePlan(text,page()).ok,false,text);});
test('gift notes and engraving literals are opaque one-field data, not nested command plans',async()=>{const h=harness(),literal='Eva & Paul and open my cart then select Gold';for(const command of ['Set engraving text to '+literal,'Fill my engraving with '+literal,'Set gift note to '+literal]){const resolved=h.api.resolve(command);assert.equal(resolved.ok,true,command);assert.equal(h.api.resolvePlan(command).handled,false);const r=await h.api.execute(resolved.action);assert.equal(r.ok,true);assert.equal(h.text(),literal);assert.equal(JSON.stringify(r).includes(literal),false);assert.equal(h.read().pageKind,'product');}assert.equal(h.api.resolvePlan('Open my cart then set gift note to '+literal).ok,false);});
test('engraving setter requires a declared enabled field, rejects overflow and extra authority fields',()=>{const p=page();delete p.engravingControls;assert.equal(bridge.resolve('Set engraving text to Eva',p).ok,false);assert.equal(bridge.resolve('Set engraving text to '+'x'.repeat(301),page()).ok,false);assert.equal(bridge.validateAction({type:'set-engraving',handle:chosen.handle,text:'Eva',selector:'#password'}),null);assert.equal(bridge.validateAction({type:'close-image',handle:chosen.handle}),null);assert.equal(bridge.validateAction({type:'undo',purchase:true}),null);});
test('snapshots expose reversible and field states without actual private text',()=>{const p=page();p.engravingControls.text='PRIVATE39';p.imageControls.url='PRIVATE39';p.changeControls.previous={text:'PRIVATE39'};const result=bridge.sanitizeSnapshot(p);assert.deepEqual(result.changeControls,{canUndo:true,kind:'select-option'});assert.deepEqual(result.imageControls,{open:false});assert.deepEqual(result.engravingControls,{available:true,enabled:true,hasText:false,maxLength:300});assert.equal(JSON.stringify(result).includes('PRIVATE39'),false);});
test('private literal history redaction also applies when the requested field is unavailable',()=>{for(const value of ['Fill my engraving with PRIVATE39','Write engraving text: PRIVATE39','Set gift note to PRIVATE39','Could you please change my engraved message to PRIVATE39'])assert.equal(bridge.redactRequestText(value).includes('PRIVATE39'),false);assert.equal(bridge.redactRequestText('Open my cart'),'Open my cart');const p=page();delete p.engravingControls;assert.equal(bridge.resolve('Fill my engraving with PRIVATE39',p).ok,false);});
test('clear text is an explicit empty private-field action and incomplete setters do not invent text',async()=>{const h=harness();for(const message of ['Clear engraving text','Erase my engraving field']){const resolved=h.api.resolve(message);assert.deepEqual(resolved.action,{type:'set-engraving',handle:chosen.handle,text:''});assert.equal((await h.api.execute(resolved.action)).ok,true);}assert.equal(bridge.resolve('Set engraving text to',page()).ok,false);assert.equal(bridge.resolve('Set engraving text to Eva\u0085Paul',page()).ok,false);assert.deepEqual(bridge.resolve('Clear the gift note',page()).action,{type:'gift-preferences',giftNote:''});});
test('connected production note fields require declared native form capability',async()=>{const h=harness();h.api=bridge.create({storefront:{capabilities:{...capabilities,mode:'shopify',notesMode:'native-form'},snapshot:()=>page(),execute:async()=>({ok:true,message:'Visible field changed; saving is unconfirmed.'})}});const action=h.api.resolve('Set gift note to A private message');assert.equal((await h.api.execute(action.action)).ok,true);assert.equal(bridge.sanitizeCapabilities({...capabilities,mode:'shopify',notesMode:'local-session'}).notesMode,'unsupported');});
