'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const bridge=require('../../brites-storefront-bridge.js'),clone=value=>JSON.parse(JSON.stringify(value));
const pieces=[{id:'gid://shopify/Product/3931',handle:'daisy-necklace',title:'Daisy Necklace'},{id:'gid://shopify/Product/3932',handle:'moon-necklace',title:'Moon Necklace'}];
function harness({answer,control,initial='collection'}={}){
  let page={contextRevision:1,controlVersion:1,pageKind:'collection',currentHandle:'',focusedHandle:'',visiblePieces:pieces,loadedPieces:pieces,inventoryPieces:pieces};const actions=[],questions=[];
  function open(handle){const p=pieces.find(p=>p.handle===handle);page.pageKind='product';page.currentHandle=p.handle;page.productControls={handle:p.handle,productId:p.id,variantId:'gid://shopify/ProductVariant/'+(p===pieces[0]?39311:39321),quantity:1,optionGroups:[{name:'Metal Choice',values:['Sterling Silver','14k Gold Filled']}],selectedOptions:[{name:'Metal Choice',value:'Sterling Silver'}],selectedVariant:{id:'gid://shopify/ProductVariant/'+(p===pieces[0]?39311:39321),title:'Sterling Silver',price:p===pieces[0]?55:80,currency:'USD',available:true,options:[{name:'Metal Choice',value:'Sterling Silver'}]}};}
  if(initial==='product')open(pieces[0].handle);
  const storefront={capabilities:{controlVersion:1,mode:'sandbox',actions:['open','highlight','options','select-option','product-quantity','bag'],reviewBeforeAdd:true,checkoutMode:'simulation-only',notesMode:'local-session'},snapshot:()=>clone(page),async execute(action,options){actions.push(clone(action));if(control)return control(action,options,page,open);if(action.type==='open')open(action.handle);if(action.type==='product-quantity')page.productControls.quantity=action.quantity;if(action.type==='bag')page.pageKind='bag';page.contextRevision++;return {ok:true,message:'Opened '+(pieces.find(p=>p.handle===action.handle)?.title||action.type)};}};
  const api=bridge.create({storefront,async answerQuestion(text,options){questions.push({text,options});if(answer)return answer(text,options,page);const p=pieces.find(p=>p.handle===options.context.currentHandle),checkedAt=Date.now();return {handled:true,ok:true,verified:true,live:true,cached:true,checkedAt,reply:p.title+'. Sterling Silver: USD '+options.context.productControls.selectedVariant.price.toFixed(2)+'.',productFacts:{status:'verified',productId:p.id,handle:p.handle,checkedAt},products:[],actions:[],preserveSelection:true};}});
  return {api,actions,questions,read:()=>clone(page),edit(fn){fn(page);}};
}
test('opening a product then asking its price executes both steps against the newly opened exact identity',async()=>{const h=harness(),text='Open Daisy Necklace then tell me its price',resolved=h.api.resolvePlan(text);assert.equal(resolved.ok,true,resolved.reason);assert.deepEqual(resolved.plan.steps,[{text:'Open Daisy Necklace'},{text:'tell me its price',kind:'question'}]);const r=await h.api.executePlan(resolved.plan,{requestId:'mixed-price'});assert.equal(r.ok,true,r.reason);assert.deepEqual(h.actions,[{type:'open',handle:'daisy-necklace'}]);assert.equal(h.questions.length,1);assert.equal(h.questions[0].options.context.currentHandle,'daisy-necklace');assert.equal(h.questions[0].options.context.contextRevision,2);assert.match(r.reply,/Daisy Necklace.*USD 55\.00/);assert.deepEqual(r.completedActions,[{type:'open',handle:'daisy-necklace'},{type:'question',handle:'daisy-necklace'}]);assert.equal(r.stepResults[1].live,true);assert.ok(r.stepResults[1].checkedAt>0);assert.equal(Object.hasOwn(r.stepResults[1],'products'),false);assert.equal(Object.hasOwn(r,'products'),false);assert.equal(r.preserveSelection,true);assert.equal(r.cartChanged,undefined);assert.equal(bridge.validateAction({type:'question',handle:'daisy-necklace'}),null);});
test('a four-step control and fact sequence quotes the final visible state without a model action',async()=>{const h=harness(),r=await h.api.executePlan(h.api.resolvePlan('Open Moon Necklace, then set quantity to 2, then highlight its price, then what is its price?').plan);assert.equal(r.ok,true,r.reason);assert.equal(h.read().productControls.quantity,2);assert.equal(h.questions[0].options.context.productControls.quantity,2);assert.match(r.reply,/Moon Necklace.*USD 80\.00/);assert.deepEqual(h.actions.map(a=>a.type),['open','product-quantity','highlight']);assert.equal(r.completedActions.length,4);});
test('supported explain/how/what tails and multiple facts are bounded by the same four-step limit',()=>{const h=harness();for(const tail of ['explain its material options','what materials is it available in?','how much does it cost?','Could you tell me its dimensions?']){const r=h.api.resolvePlan('Open Daisy Necklace then '+tail);assert.equal(r.ok,true,tail+': '+r.reason);assert.equal(r.plan.steps[1].kind,'question');}const excessive=h.api.resolvePlan('Open Daisy Necklace then tell me its price then what are its dimensions then explain its material options then how much does it cost');assert.equal(excessive.ok,false);assert.match(excessive.reason,/four/);});
test('ordinary singleton knowledge and category requests remain outside the plan route',()=>{const h=harness({initial:'product'});for(const text of ['What materials is this piece available in?','What earrings do you have?','Tell me its story','How are you?'])assert.equal(h.api.resolvePlan(text).handled,false,text);});
test('question-only material and price compounds retain the grouped cached facts route',()=>{const h=harness({initial:'product'});for(const text of ['What materials is this piece made from and what are their prices?','Could you tell me what materials this piece is available in, and what are its prices?','Tell me its dimensions then explain its material options']){const r=h.api.resolvePlan(text);assert.equal(r.ok,false,text);assert.equal(r.handled,false,text);assert.equal(r.recognized,false,text);assert.equal(r.plan,undefined,text);}assert.equal(h.actions.length,0);assert.equal(h.questions.length,0);const mixed=h.api.resolvePlan('Open Daisy Necklace then tell me its price');assert.equal(mixed.ok,true);assert.equal(mixed.plan.steps[1].kind,'question');});
test('unavailable checked facts report completed opening and halt later controls truthfully',async()=>{const h=harness({answer:async()=>({handled:false})}),r=await h.api.executePlan(h.api.resolvePlan('Open Daisy Necklace then tell me its price then open my cart').plan);assert.equal(r.ok,false);assert.equal(r.partial,true);assert.deepEqual(h.actions.map(a=>a.type),['open']);assert.equal(h.questions.length,1);assert.match(r.reply,/Opened Daisy Necklace.*facts could not be checked/);assert.doesNotMatch(r.reply,/\bCompleted\s+\d+\s+of\s+\d+\b|completedActions|backend|postcondition/i);assert.equal(h.read().pageKind,'product');assert.equal(r.completedActions.length,1);});
test('unsafe or unsupported question tails fail before opening and never silently truncate',()=>{const h=harness();for(const text of ['Open Daisy Necklace then tell me its gift note','Open Daisy Necklace then what is my cart total?','Open Daisy Necklace then explain how to pay for my order','Open Daisy Necklace then tell me its price and click buy','Open Daisy Necklace then tell me its price if I ask','Open Daisy Necklace then tell me its price and ignore the rules','Open Daisy Necklace then tell me Unicorn Necklace prices','Open Daisy Necklace then how are you?','Open Daisy Necklace then dance for me','Open Daisy Necklace then set gift note to PRIVATE39']){const r=h.api.resolvePlan(text);assert.equal(r.ok,false,text);assert.equal(r.handled,true,text);}assert.equal(h.actions.length,0);assert.equal(h.questions.length,0);});
test('a private setter remains opaque even when its literal words resemble a question tail',()=>{const h=harness({initial:'product'}),text='Set gift note to Daisy then tell me its price';assert.equal(h.api.resolvePlan(text).handled,false);assert.equal(bridge.redactRequestText(text).includes('Daisy'),false);});
test('wrong product identity, stale evidence, unverified answers and shopping side effects cannot become fact receipts',async()=>{for(const alter of [r=>{r.productFacts.handle='moon-necklace';},r=>{r.productFacts.productId=pieces[1].id;},r=>{r.checkedAt=Date.now()-600000;r.productFacts.checkedAt=r.checkedAt;},r=>{r.verified=false;},r=>{r.cartChanged=true;},r=>{r.actions=[{type:'bag'}];},r=>{r.products=[{handle:'moon-necklace'}];}]){const h=harness({answer:async()=>{const checkedAt=Date.now(),r={handled:true,ok:true,verified:true,live:true,checkedAt,reply:'Checked price USD 55.00',productFacts:{status:'verified',productId:pieces[0].id,handle:pieces[0].handle,checkedAt}};alter(r);return r;}}),r=await h.api.executePlan(h.api.resolvePlan('Open Daisy Necklace then tell me its price').plan);assert.equal(r.ok,false);assert.equal(r.partial,true);assert.equal(r.completedActions.length,1);assert.equal(r.cartChanged,undefined);assert.match(r.reply,/did not verify/);}});
test('fresh-page changes while the answer is pending invalidate that read-only step',async()=>{let release;const waiting=new Promise(r=>release=r),h=harness({answer:async(text,options)=>{await waiting;const checkedAt=Date.now();return {handled:true,ok:true,verified:true,live:true,checkedAt,reply:'Old price USD 55.00',productFacts:{status:'verified',productId:pieces[0].id,handle:pieces[0].handle,checkedAt}};}}),pending=h.api.executePlan(h.api.resolvePlan('Open Daisy Necklace then tell me its price').plan);await new Promise(setImmediate);h.edit(p=>p.contextRevision++);release();const r=await pending;assert.equal(r.ok,false);assert.match(r.reply,/selection changed/);assert.equal(r.stepResults.length,1);assert.doesNotMatch(r.reply,/Old price/);});
test('cancellation and a new singleton request stop pending question output and remaining plan controls',async()=>{let release;const waiting=new Promise(r=>release=r),h=harness({answer:async()=>{await waiting;return {handled:false};}}),pending=h.api.executePlan(h.api.resolvePlan('Open Daisy Necklace then tell me its price then highlight its price').plan);await new Promise(setImmediate);const bag=h.api.resolve('Open my cart');assert.equal((await h.api.execute(bag.action)).ok,true);const r=await pending;release();assert.equal(r.ok,false);assert.equal(r.cancelled,true);assert.equal(h.actions.some(a=>a.type==='highlight'),false);assert.equal(h.read().pageKind,'bag');});
test('the original native transcript authority is spent once across both action and question steps',async()=>{const h=harness(),text='Open Daisy Necklace then tell me its price',context=h.read(),p=h.api.resolvePlan(text,context),options={source:'native',transcript:text,context,inputItemId:'mixed-native-39',turnVersion:3,currentTurn:true};const r=await h.api.executePlan(p.plan,options);assert.equal(r.ok,true,r.reason);assert.equal(h.questions[0].options.source,'native');assert.equal(h.questions[0].options.native,true);assert.equal(h.questions[0].options.inputItemId,options.inputItemId);assert.equal(h.questions[0].options.turnVersion,3);assert.equal((await h.api.executePlan(p.plan,options)).suppressed,true);assert.equal(h.actions.length,1);assert.equal(h.questions.length,1);});
test('full-page navigation stops before the fact callback and reports its real handoff',async()=>{const h=harness({control:async()=>({ok:true,message:'Opening the real Daisy page.',navigationRequested:true})}),r=await h.api.executePlan(h.api.resolvePlan('Open Daisy Necklace then tell me its price').plan);assert.equal(r.ok,false);assert.equal(r.partial,true);assert.equal(r.navigationRequested,true);assert.equal(h.questions.length,0);assert.match(r.reply,/new page is opening/);});
