'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(require.resolve('../../concierge-sandbox.html'),'utf8'),source=fs.readFileSync(require.resolve('../../concierge-sandbox.js'),'utf8');
const clone=x=>JSON.parse(JSON.stringify(x)),settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
function piece(){return {id:'gid://shopify/Product/34',handle:'daisy-necklace',title:'Daisy Necklace',type:'Necklace',description:'Synthetic published sterling silver necklace.',url:'https://britesjewelry.com/products/daisy-necklace',currency:'USD',image:'https://cdn.shopify.com/daisy-necklace.jpg',options:[{name:'Metal Choice',values:['Sterling Silver','Gold Filled']},{name:'Chain Length',values:['16 inches','18 inches']}],variantsComplete:true,variants:[['Sterling Silver','16 inches',3401,50],['Gold Filled','16 inches',3402,60],['Sterling Silver','18 inches',3403,55],['Gold Filled','18 inches',3404,65]].map(([metal,length,id,price])=>({id:'gid://shopify/ProductVariant/'+id,numericId:String(id),title:metal+' / '+length,price,available:true,options:[{name:'Metal Choice',value:metal},{name:'Chain Length',value:length}]}))};}
function response(data,ok=true){return {ok,json:async()=>clone(data)};}
function fixture(t,options={}){
  const errors=[],requests=[],scrolls=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));const dom=new JSDOM(html,{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document,p={...piece(),...(options.patch||{})};let lookup=null;
  if(options.seed)d.body.dataset.catalogueSeed='balanced';else delete d.body.dataset.catalogueSeed;
  delete d.body.dataset.inventoryPreload; // This fixture isolates the original seed/browse path; preload is covered by fast-storefront38.
  w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=function(value){scrolls.push({node:this,value});};
  w.fetch=async(raw,init={})=>{const url=new URL(raw,w.location.href);requests.push({url,init});if(url.pathname==='/api/growth/catalogue'){if(url.searchParams.has('seed'))return typeof options.seed==='function'?options.seed(url,init):response(options.seed);if(options.browse)return options.browse(url,init);return response({live:true,products:[p],pageInfo:{hasNextPage:false,endCursor:null}});}if(url.pathname==='/api/growth/product')return lookup?lookup(url,init):response({live:true,product:p});if(url.pathname==='/api/growth/storefront-services')return response({schema:1,guidance:{},conflicts:[],offers:{items:[],status:'published_not_checkout_validated'}});throw Error('Unexpected route '+url.pathname);};
  w.eval(source);t.after(()=>w.close());return {w,d,p,requests,scrolls,errors,get store(){return w.BritesSandboxStorefront;},ready:settle,lookup:fn=>lookup=fn,cart:()=>JSON.parse(w.sessionStorage.getItem('brites-sandbox-cart')||'[]'),async open(){assert.equal((await this.store.execute({type:'open',handle:p.handle})).ok,true);},async choose(id=p.variants[0].id){return this.store.execute({type:'select-option',handle:p.handle,variantId:id});},async add(){await this.open();assert.equal((await this.choose()).ok,true);assert.equal((await this.store.execute({type:'review-add',handle:p.handle})).ok,true);d.querySelector('.product-review .primary').click();await settle();}};
}

function composerFocus34(h){const host=h.d.body.appendChild(h.d.createElement('brites-concierge')),shadow=host.attachShadow({mode:'open'}),composer=h.d.createElement('input'),newer=h.d.createElement('button');composer.setAttribute('aria-label','Synthetic shopper request');newer.textContent='A newer deliberate choice';shadow.append(composer,newer);composer.focus();return {host,shadow,composer,newer};}
// JSDOM retains a disabled input's focus; Chromium's observed transition is BODY.
// Model that native self blur without focusing a different shopper control.
function disableComposer34(h,focus){focus.composer.disabled=true;h.d.body.tabIndex=-1;h.d.body.focus();}

for(const timing of ['before','during'])test('requested product arrival survives only the application-disabled composer self blur '+timing+' its read',async t=>{
  const h=fixture(t);await h.ready();const focus=composerFocus34(h),gate=deferred();h.lookup(()=>gate.promise);
  if(timing==='before')disableComposer34(h,focus);
  const pending=h.store.execute({type:'open',handle:h.p.handle});
  if(timing==='during')disableComposer34(h,focus);
  assert.equal(h.d.activeElement,h.d.body);gate.resolve(response({live:true,product:h.p}));const result=await pending,layout=h.d.querySelector('.product-layout');
  assert.equal(result.ok,true);assert.equal(result.snapshot.currentHandle,h.p.handle);assert.equal(h.d.activeElement,h.d.body);assert.ok(h.scrolls.some(s=>s.node===layout&&s.value.block==='start'&&s.value.behavior==='instant'),'a requested checked piece must arrive independently of throttled smooth frames');assert.deepEqual(h.cart(),[]);
});

test('a deliberate newer deep focus cancels requested product arrival even after disabled self blur and a return',async t=>{
  const h=fixture(t);await h.ready();const focus=composerFocus34(h),gate=deferred();h.lookup(()=>gate.promise);const pending=h.store.execute({type:'open',handle:h.p.handle});disableComposer34(h,focus);focus.newer.focus();focus.composer.disabled=false;focus.composer.focus();gate.resolve(response({live:true,product:h.p}));assert.equal((await pending).ok,true);assert.equal(focus.shadow.activeElement,focus.composer);assert.equal(h.scrolls.length,0,'self blur cannot revive a reveal withdrawn by an actual new focus choice');
});

test('requested current price highlight arrives without waiting for smooth scroll animation or moving focus',async t=>{
  const h=fixture(t);await h.ready();await h.open();h.scrolls.length=0;const focus=composerFocus34(h);disableComposer34(h,focus);const r=await h.store.execute({type:'highlight',handle:h.p.handle,section:'price'}),price=h.d.querySelector('[data-store-section=price]');assert.equal(r.ok,true);assert.equal(price.classList.contains('store-highlight'),true);assert.ok(h.scrolls.some(s=>s.node===price&&s.value.behavior==='instant'&&s.value.block==='center'));assert.equal(h.d.activeElement,h.d.body);assert.deepEqual(h.cart(),[]);
});

for(const mode of ['pointer','keyboard'])test(mode+' product opening arrives immediately after its own collection link is replaced',async t=>{
  const h=fixture(t);await h.ready();const anchor=h.d.querySelector('.piece-card a');anchor.focus();anchor.dispatchEvent(new h.w.MouseEvent('click',{bubbles:true,cancelable:true,button:0,detail:mode==='pointer'?1:0}));await settle();const heading=h.d.querySelector('.product-copy h1'),target=mode==='pointer'?h.d.querySelector('.product-layout'):heading;assert.equal(anchor.isConnected,false);assert.equal(heading.textContent,h.p.title);assert.ok(h.scrolls.some(s=>s.node===target&&s.value.block==='start'&&s.value.behavior==='instant'),'own view replacement cannot revoke the requested exact product arrival');assert.equal(h.d.activeElement===heading,mode==='keyboard');assert.deepEqual(h.cart(),[]);
});

test('moving the current test checkout step removes its preceding visual highlight',async t=>{
  const h=fixture(t);await h.ready();await h.add();await h.store.execute({type:'checkout'});await h.store.execute({type:'checkout-step',step:'shipping'});const shipping=h.d.querySelector('[data-checkout-step=shipping]'),confirm=h.d.querySelector('[data-checkout-step=confirm]');assert.equal(shipping.classList.contains('store-highlight'),true);await h.store.execute({type:'checkout-step',step:'confirm'});assert.equal(shipping.classList.contains('store-highlight'),false);assert.equal(confirm.classList.contains('store-highlight'),true);assert.equal(h.d.querySelectorAll('.checkout-step.store-highlight').length,1);assert.equal(h.d.querySelector('[data-checkout-step-button=confirm]').getAttribute('aria-current'),'step');assert.equal(h.d.querySelector('.receipt'),null);assert.equal(h.cart().length,1);
});

for(const interruption of ['focus','hidden','superseded'])test('a delayed exact price reveal respects '+interruption+' during its product read',async t=>{
  const h=fixture(t);await h.ready();const focus=composerFocus34(h),gate=deferred();h.lookup(()=>gate.promise);const pending=h.store.execute({type:'highlight',handle:h.p.handle,section:'price'});
  if(interruption==='focus'){focus.newer.focus();focus.composer.focus();}else if(interruption==='hidden')Object.defineProperty(h.d,'hidden',{get:()=>true});else await h.store.execute({type:'filter',filter:'all'});
  const before=h.scrolls.length;gate.resolve(response({live:true,product:h.p}));const r=await pending;assert.equal(r.ok,false);assert.equal(h.scrolls.length,before,'a cancelled section reveal must not displace the newer or hidden viewport');assert.equal(h.d.querySelector('.product-price')?.classList.contains('store-highlight')||false,false);assert.deepEqual(h.cart(),[]);
});

test('versioned reusable controls expose only concrete capabilities and no arbitrary evaluator',async t=>{const h=fixture(t);await h.ready();assert.equal(h.store.capabilities.controlVersion,1);assert.equal(h.store.capabilities.mode,'sandbox');assert.equal(h.store.capabilities.finalOrder,false);assert.ok(h.store.capabilities.actions.includes('select-option'));const before=h.requests.length;assert.equal((await h.store.execute({type:'javascript',code:'window.anything=true'})).ok,false);assert.equal(h.w.anything,undefined);assert.equal(h.requests.length,before);});

test('opening a named published option menu is visible and makes no implicit exact selection or cart change',async t=>{const h=fixture(t);await h.ready();await h.open();const r=await h.store.execute({type:'options',handle:h.p.handle,optionName:'Chain Length'}),menu=h.d.querySelector('.option-menu');assert.equal(r.ok,true);assert.equal(menu.hidden,false);assert.equal(menu.querySelector('[data-option-name="Chain Length"]').hidden,false);assert.equal(menu.querySelector('[data-option-name="Metal Choice"]').hidden,true);assert.equal(h.store.snapshot().productControls.variantId,null);assert.deepEqual(h.cart(),[]);assert.ok(h.scrolls.some(s=>s.node===h.d.querySelector('[data-store-section=options]')));});

test('literal named choices preserve the other group and resolve a variant only after all options are chosen',async t=>{const h=fixture(t);await h.ready();await h.open();assert.equal((await h.store.execute({type:'select-option',handle:h.p.handle,optionName:'Metal Choice',optionValue:'Sterling Silver'})).ok,true);assert.equal(h.store.snapshot().productControls.variantId,null);assert.deepEqual(clone(h.store.snapshot().productControls.selectedOptions),[{name:'Metal Choice',value:'Sterling Silver'}]);await h.store.execute({type:'select-option',handle:h.p.handle,optionName:'Chain Length',optionValue:'18 inches'});assert.equal(h.store.snapshot().productControls.variantId,h.p.variants[2].id);await h.store.execute({type:'select-option',handle:h.p.handle,optionName:'Metal Choice',optionValue:'gold filled'});const s=h.store.snapshot().productControls;assert.equal(s.variantId,h.p.variants[3].id);assert.deepEqual(clone(s.selectedOptions),[{name:'Metal Choice',value:'Gold Filled'},{name:'Chain Length',value:'18 inches'}]);assert.match(h.d.querySelector('.product-price').textContent,/65/);assert.deepEqual(h.cart(),[]);});

test('unsupported, foreign and conflicting option forms leave the real current selection intact',async t=>{const h=fixture(t);await h.ready();await h.open();await h.choose();const before=clone(h.store.snapshot().productControls);for(const action of [{type:'select-option',handle:h.p.handle,optionName:'Metal Choice',optionValue:'Platinum'},{type:'select-option',handle:'another-piece',variantId:h.p.variants[1].id},{type:'select-option',handle:h.p.handle,variantId:'gid://shopify/ProductVariant/999'},{type:'select-option',handle:h.p.handle,variantId:h.p.variants[1].id,optionName:'Metal Choice',optionValue:'Gold Filled'}])assert.equal((await h.store.execute(action)).ok,false);assert.deepEqual(clone(h.store.snapshot().productControls),before);});

test('ambiguous published option combinations never silently choose one variant',async t=>{const p=piece(),duplicate={...p.variants[0],id:'gid://shopify/ProductVariant/3499',numericId:'3499'};const h=fixture(t,{patch:{variants:[...p.variants,duplicate]}});await h.ready();await h.open();await h.store.execute({type:'select-option',handle:h.p.handle,optionName:'Metal Choice',optionValue:'Sterling Silver'});await h.store.execute({type:'select-option',handle:h.p.handle,optionName:'Chain Length',optionValue:'16 inches'});assert.equal(h.store.snapshot().productControls.variantId,null);assert.equal((await h.store.execute({type:'review-add',handle:h.p.handle})).ok,false);assert.deepEqual(h.cart(),[]);});

test('review and product quantity controls prepare the exact visible choice without adding until the shopper confirms',async t=>{const h=fixture(t);await h.ready();await h.open();await h.choose();for(const q of [0,21,1.5,'2'])assert.equal((await h.store.execute({type:'product-quantity',handle:h.p.handle,quantity:q})).ok,false);assert.equal((await h.store.execute({type:'product-quantity',handle:h.p.handle,quantity:3})).ok,true);const r=await h.store.execute({type:'review-add',handle:h.p.handle,variantId:h.p.variants[0].id});assert.equal(r.ok,true);assert.equal(r.requiredCustomerClick,'Confirm add to test bag');assert.match(h.d.querySelector('.product-review').textContent,/quantity 3/);assert.match(h.d.querySelector('.product-review').textContent,/150/);assert.deepEqual(h.cart(),[]);h.d.querySelector('.product-review .primary').click();await settle();assert.equal(h.cart().length,1);assert.equal(h.cart()[0].quantity,3);assert.equal(h.cart()[0].variantId,'3401');assert.equal(h.d.querySelector('#bag-count').textContent,'3');assert.ok(h.requests.filter(r=>r.url.pathname==='/api/growth/product').length>=2);assert.equal(h.store.snapshot().productControls.reviewReady,false);});

test('changing selection invalidates a prepared review instead of confirming an obsolete option',async t=>{const h=fixture(t);await h.ready();await h.open();await h.choose();await h.store.execute({type:'review-add',handle:h.p.handle});const old=h.d.querySelector('.product-review .primary');await h.choose(h.p.variants[1].id);assert.equal(old.isConnected,false);old.click();await settle();assert.equal(h.store.snapshot().productControls.reviewReady,false);assert.deepEqual(h.cart(),[]);});

for(const reason of ['held','partial','unavailable','custom'])test(reason+' exact pieces cannot prepare an unchecked test-bag addition',async t=>{const p=piece(),patch=reason==='held'?{cartHold:true}:reason==='partial'?{variantsComplete:false}:reason==='unavailable'?{variants:p.variants.map(v=>({...v,available:false}))}:{title:'Custom Monogram Necklace'};const h=fixture(t,{patch});await h.ready();await h.open();await h.choose();assert.equal((await h.store.execute({type:'review-add',handle:h.p.handle})).ok,false);assert.deepEqual(h.cart(),[]);});

test('price drift after review blocks the confirmation add and preserves the chosen exact option',async t=>{const h=fixture(t);await h.ready();await h.open();await h.choose();await h.store.execute({type:'review-add',handle:h.p.handle});h.lookup(()=>response({live:true,product:{...h.p,variants:h.p.variants.map(v=>({...v,price:v.price+2}))}}));h.d.querySelector('.product-review .primary').click();await settle();assert.deepEqual(h.cart(),[]);assert.equal(h.store.snapshot().productControls.variantId,h.p.variants[0].id);assert.match(h.d.querySelector('#storefront-status').textContent,/changed/);});

test('late confirmation rechecks cannot add after navigation or a newer exact quantity',async t=>{const h=fixture(t);await h.ready();await h.open();await h.choose();await h.store.execute({type:'review-add',handle:h.p.handle});const gate=deferred();h.lookup(()=>gate.promise);h.d.querySelector('.product-review .primary').click();await h.store.execute({type:'filter',filter:'all'});gate.resolve(response({live:true,product:h.p}));await settle();assert.deepEqual(h.cart(),[]);assert.equal(h.store.snapshot().pageKind,'collection');});

test('visible stable bag lines support exact quantity and removal without array-index or stale-line authority',async t=>{const h=fixture(t);await h.ready();await h.add();await h.store.execute({type:'review-add',handle:h.p.handle});h.d.querySelector('.product-review .primary').click();await settle();await h.store.execute({type:'bag'});const first=h.store.snapshot().bagControls.lines[0],second=h.store.snapshot().bagControls.lines[1];assert.notEqual(first.lineId,second.lineId);assert.equal((await h.store.execute({type:'bag-quantity',lineId:second.lineId,quantity:4})).ok,true);let lines=h.store.snapshot().bagControls.lines;assert.equal(lines[0].lineId,first.lineId);assert.equal(lines[1].lineId,second.lineId);assert.equal(lines[1].quantity,4);assert.equal(h.d.querySelector('#bag-count').textContent,'5');assert.equal((await h.store.execute({type:'bag-remove',lineId:first.lineId})).ok,true);lines=h.store.snapshot().bagControls.lines;assert.equal(lines.length,1);assert.equal(lines[0].lineId,second.lineId);assert.equal((await h.store.execute({type:'bag-remove',lineId:first.lineId})).ok,false);assert.equal((await h.store.execute({type:'bag-remove',lineId:'0'})).ok,false);assert.equal(h.cart().length,1);});

test('external bag replacement invalidates all old line identities instead of retargeting duplicates',async t=>{const h=fixture(t);await h.ready();await h.add();await h.store.execute({type:'bag'});const old=h.store.snapshot().bagControls.lines[0].lineId;h.w.sessionStorage.setItem('brites-sandbox-cart',JSON.stringify([...h.cart(),...h.cart()]));h.d.dispatchEvent(new h.w.CustomEvent('brites:cart-updated',{detail:{sandbox:true}}));assert.equal((await h.store.execute({type:'bag-remove',lineId:old})).ok,false);assert.equal(h.cart().length,2);});

test('bag quantity recheck cancels when the bag or page changes during the read',async t=>{const h=fixture(t);await h.ready();await h.add();await h.store.execute({type:'bag'});const line=h.store.snapshot().bagControls.lines[0],gate=deferred();h.lookup(()=>gate.promise);const pending=h.store.execute({type:'bag-quantity',lineId:line.lineId,quantity:5});await h.store.execute({type:'filter',filter:'all'});gate.resolve(response({live:true,product:h.p}));assert.equal((await pending).ok,false);assert.equal(h.cart()[0].quantity,undefined);});

test('gift preferences stay local and their text never enters control snapshots or network requests',async t=>{const h=fixture(t);await h.ready();const before=h.requests.length,r=await h.store.execute({type:'gift-preferences',wrapping:true,giftPackage:true,giftNote:'For Sam\nWith love.'});assert.equal(r.ok,true);await settle();const saved=JSON.parse(h.w.sessionStorage.getItem('brites-sandbox-gift-preferences'));assert.equal(saved.giftNote,'For Sam\nWith love.');assert.equal(saved.giftPackage,true);assert.equal(h.d.querySelector('[name=wrapping]').checked,true);assert.equal(JSON.stringify(h.store.snapshot()).includes('For Sam'),false);assert.equal(JSON.stringify(h.requests.map(r=>r.init)).includes('For Sam'),false);assert.equal(h.requests.length,before);assert.equal((await h.store.execute({type:'gift-preferences',giftNote:'x'.repeat(301)})).ok,false);assert.equal((await h.store.execute({type:'gift-preferences',wrapping:'yes'})).ok,false);});

test('checkout controls select labelled demo steps and shipping while completion still requires shopper acknowledgement and click',async t=>{const h=fixture(t);await h.ready();await h.add();assert.equal((await h.store.execute({type:'checkout'})).ok,true);assert.equal(h.store.snapshot().checkoutControls.step,'review');assert.equal((await h.store.execute({type:'checkout-step',step:'shipping'})).ok,true);assert.equal(h.store.snapshot().checkoutControls.step,'shipping');assert.equal((await h.store.execute({type:'checkout-option',option:'shipping',value:'express'})).ok,true);assert.equal(h.store.snapshot().checkoutControls.shipping,'express');assert.match(h.d.querySelector('.demo-shipping').textContent,/not live services, rates or delivery promises/);const r=await h.store.execute({type:'checkout-complete'});assert.equal(r.ok,true);assert.equal(r.completed,false);assert.equal(h.d.querySelector('.receipt'),null);assert.equal(h.d.querySelector('#confirm-test-checkout').checked,false);const complete=[...h.d.querySelectorAll('button')].find(b=>b.textContent==='Complete test checkout');assert.equal(complete.disabled,true);complete.click();await settle();assert.equal(h.d.querySelector('.receipt'),null);const ack=h.d.querySelector('#confirm-test-checkout');ack.checked=true;ack.dispatchEvent(new h.w.Event('change'));complete.click();await settle();assert.match(h.d.querySelector('.receipt').textContent,/No order was placed, no payment was taken/);assert.equal(h.store.snapshot().checkoutControls.complete,true);assert.equal(h.cart().length,1);assert.ok(h.requests.every(r=>r.init.method===undefined&&!r.init.body));assert.equal(h.d.querySelector('input[type=email],input[autocomplete=cc-number]'),null);});

test('checkout completion cannot materialize after a newer navigation during exact recheck',async t=>{const h=fixture(t);await h.ready();await h.add();await h.store.execute({type:'checkout'});const ack=h.d.querySelector('#confirm-test-checkout');ack.checked=true;ack.dispatchEvent(new h.w.Event('change'));const gate=deferred();h.lookup(()=>gate.promise);[...h.d.querySelectorAll('button')].find(b=>b.textContent==='Complete test checkout').click();await h.store.execute({type:'filter',filter:'all'});gate.resolve(response({live:true,product:h.p}));await settle();assert.equal(h.store.snapshot().pageKind,'collection');assert.equal(h.d.querySelector('.receipt'),null);assert.equal(h.cart().length,1);});

test('the loaded checked cohort is separate from the viewport identities and carries no prices or private notes',async t=>{const h=fixture(t);await h.ready();const s=h.store.snapshot();assert.equal(s.controlVersion,1);assert.deepEqual(s.loadedPieces.map(p=>p.id),[h.p.id]);assert.deepEqual(Object.keys(s.loadedPieces[0]).sort(),['handle','id','title']);assert.equal('price' in s.loadedPieces[0],false);assert.equal(s.productControls,null);assert.deepEqual(clone(s.bagControls.lines),[]);assert.equal(s.checkoutControls,null);});

test('same-fact product refresh keeps the real option control and quantity but withdraws the obsolete confirmation review',async t=>{const h=fixture(t);await h.ready();await h.open();await h.choose();await h.store.execute({type:'product-quantity',handle:h.p.handle,quantity:4});await h.store.execute({type:'review-add',handle:h.p.handle});const select=h.d.querySelector('#piece-variant'),oldConfirm=h.d.querySelector('.product-review .primary');select.focus();const result=h.store.presentProducts([{...clone(h.p),checkedAt:Date.now()}]);assert.equal(result.ok,true);assert.equal(h.d.querySelector('#piece-variant'),select);assert.equal(h.d.activeElement,select);assert.equal(result.snapshot.productControls.variantId,h.p.variants[0].id);assert.equal(result.snapshot.productControls.quantity,4);assert.equal(result.snapshot.productControls.reviewReady,false);assert.equal(oldConfirm.isConnected,false);oldConfirm.click();await settle();assert.deepEqual(h.cart(),[]);assert.equal((await h.choose(h.p.variants[1].id)).ok,true);});

test('compatible fresh description renders truthfully while preserving only the exact option and focused quantity control',async t=>{const h=fixture(t);await h.ready();await h.open();await h.choose();await h.store.execute({type:'product-quantity',handle:h.p.handle,quantity:2});const old=h.d.querySelector('.product-quantity input');old.focus();const result=h.store.presentProducts([{...clone(h.p),description:'A new exact published material description.'}]);assert.equal(result.ok,true);assert.notEqual(h.d.querySelector('.product-quantity input'),old);assert.equal(h.d.activeElement,h.d.querySelector('.product-quantity input'));assert.match(h.d.querySelector('.product-description').textContent,/new exact published material/);assert.equal(result.snapshot.productControls.quantity,2);assert.equal(result.snapshot.productControls.variantId,h.p.variants[0].id);assert.deepEqual(h.cart(),[]);});

test('changed holds or exact prices preserve literal choices but invalidate an earlier review',async t=>{const h=fixture(t);await h.ready();await h.open();await h.choose();await h.store.execute({type:'product-quantity',handle:h.p.handle,quantity:3});await h.store.execute({type:'review-add',handle:h.p.handle});const held={...clone(h.p),cartHold:true,variants:h.p.variants.map(v=>({...v,price:v.price+1}))};const result=h.store.presentProducts([held]);assert.equal(result.ok,true);assert.equal(result.snapshot.productControls.variantId,h.p.variants[0].id);assert.equal(result.snapshot.productControls.quantity,3);assert.equal(result.snapshot.productControls.selectedVariant.price,h.p.variants[0].price+1);assert.equal(result.snapshot.productControls.reviewReady,false);await h.store.execute({type:'select-option',handle:h.p.handle,variantId:h.p.variants[0].id});assert.equal((await h.store.execute({type:'review-add',handle:h.p.handle})).ok,false);assert.deepEqual(h.cart(),[]);});

test('a newer deep guide focus permanently suppresses a delayed cross-product option-menu reveal',async t=>{const h=fixture(t);await h.ready();const host=h.d.body.appendChild(h.d.createElement('brites-concierge')),shadow=host.attachShadow({mode:'open'}),initial=h.d.createElement('input'),newer=h.d.createElement('button');shadow.append(initial,newer);initial.focus();const gate=deferred();h.lookup(()=>gate.promise);const before=h.scrolls.length,pending=h.store.execute({type:'options',handle:h.p.handle,optionName:'Metal Choice'});newer.focus();initial.focus();gate.resolve(response({live:true,product:h.p}));assert.equal((await pending).ok,true);assert.equal(shadow.activeElement,initial);assert.equal(h.d.querySelector('.option-menu').hidden,false);assert.equal(h.scrolls.length,before);});

test('saved local gift preferences update the visible checkout summary while note text stays out of context',async t=>{const h=fixture(t);await h.ready();await h.add();await h.store.execute({type:'checkout'});await h.store.execute({type:'gift-preferences',wrapping:true,giftPackage:true,giftNote:'A very private test greeting.'});assert.equal(h.d.querySelector('[data-checkout-gift=wrapping]').textContent,'Gift wrapping enquiry saved.');assert.equal(h.d.querySelector('[data-checkout-gift=package]').textContent,'Gift package enquiry saved.');assert.match(h.d.querySelector('[data-checkout-gift=note]').textContent,/very private test greeting/);assert.equal(JSON.stringify(h.store.snapshot()).includes('private test greeting'),false);assert.equal(h.store.snapshot().checkoutControls.complete,false);});

test('invalid manual bag quantity restores the exact saved value and exposes a useful failure status',async t=>{const h=fixture(t);await h.ready();await h.add();await h.store.execute({type:'bag'});const input=h.d.querySelector('.bag-quantity input');input.value='0';input.dispatchEvent(new h.w.Event('change',{bubbles:true}));await settle();assert.equal(input.value,'1');assert.equal(h.cart()[0].quantity,undefined);assert.match(h.d.querySelector('#storefront-status').textContent,/quantity from 1 to 20/);});

const seedCategories=['regular-necklaces','beady-necklaces','stud-earrings','hoop-earrings','charm-only'];
function seedProduct(index){const p=piece(),category=seedCategories[index%5],id=1000+index,title=['Cable Necklace','Beady Necklace','Daisy Stud Earrings','Daisy Hoop Earrings','Daisy Charm'][index%5]+' '+index;return {...p,id:'gid://shopify/Product/'+id,handle:'checked-piece-'+index,title,type:['Necklace','Necklace','Earrings','Earrings','Charm'][index%5],url:'https://britesjewelry.com/products/checked-piece-'+index,storeCategories:[category],variants:p.variants.map((v,j)=>({...v,id:'gid://shopify/ProductVariant/'+(id*10+j+1),numericId:String(id*10+j+1)}))};}
function seedData(products=Array.from({length:120},(_,i)=>seedProduct(i))){const counts=Object.fromEntries(seedCategories.map(c=>[c,products.filter(p=>p.storeCategories.includes(c)).length])),absent=seedCategories.filter(c=>counts[c]===0);return {live:true,checkedAt:Date.now(),products,pageInfo:{hasNextPage:false,endCursor:null},seed:{schema:1,target:120,minimum:100,loaded:products.length,complete:products.length>=100&&!absent.length,categoryCounts:counts,unfilledCategories:absent,sourcePages:5,partial:products.length<100}};}

// Controlled option values and IDs remain synthetic. This public-title case
// reproduces the observed finished Earrings / Metal Choice / Hoop Size axes.
test('a finished pendant huggie stays an earring and never becomes a necklace from its pendant descriptor',async t=>{
  const p=piece(),h=fixture(t,{patch:{title:'Hawk Pendant Huggie Hoop Earrings',type:'Earrings',options:[clone(p.options[0]),{name:'Hoop Size',values:[]}]}});await h.ready();
  const before=h.requests.length,necklaces=await h.store.execute({type:'filter',filter:'necklaces'});assert.equal(necklaces.ok,true);assert.equal(necklaces.snapshot.loadedPieces.length,0);assert.equal(h.d.querySelectorAll('.piece-card').length,0);assert.deepEqual(h.cart(),[]);
  const earrings=await h.store.execute({type:'filter',filter:'earrings'});assert.deepEqual(earrings.snapshot.loadedPieces.map(p=>p.id),[h.p.id]);assert.equal(earrings.products[0].type,'Earrings');assert.deepEqual(earrings.products[0].variants,h.p.variants);assert.deepEqual(earrings.products[0].options,h.p.options);assert.equal(h.requests.length,before);assert.equal(earrings.snapshot.discoveryRevision,necklaces.snapshot.discoveryRevision+1);assert.deepEqual(h.errors,[]);
});

for(const [title,type] of [['Halo Hoop Necklace','Necklaces'],['Star Stud Pendant','Pendant']])test('finished source '+type+' takes precedence over a motif word in '+title,async t=>{
  const h=fixture(t,{patch:{title,type,tags:['category:Earrings']}});await h.ready();const necklaces=await h.store.execute({type:'filter',filter:'necklaces'});assert.deepEqual(necklaces.snapshot.loadedPieces.map(p=>p.id),[h.p.id]);assert.equal(necklaces.products[0].title,title);const earrings=await h.store.execute({type:'filter',filter:'earrings'});assert.equal(earrings.snapshot.loadedPieces.length,0);assert.equal(h.d.querySelectorAll('.piece-card').length,0);assert.deepEqual(h.cart(),[]);
});

for(const type of ['','Custom Charm Studio','Charm'])test('explicit finished earring title overrides only a pendant descriptor with generic type '+(type||'(missing)'),async t=>{
  const h=fixture(t,{patch:{title:'Moon Pendant Stud Earrings',type}});await h.ready();await h.store.execute({type:'filter',filter:'necklaces'});assert.equal(h.store.snapshot().loadedPieces.length,0);await h.store.execute({type:'filter',filter:'earrings'});assert.deepEqual(h.store.snapshot().loadedPieces.map(p=>p.id),[h.p.id]);await h.store.execute({type:'filter',filter:'stud-earrings'});assert.deepEqual(h.store.snapshot().loadedPieces.map(p=>p.id),[h.p.id]);await h.store.execute({type:'filter',filter:'regular-necklaces'});assert.equal(h.store.snapshot().loadedPieces.length,0);assert.deepEqual(h.cart(),[]);
});

test('generic pendants, finished Charm-type necklaces and necklace charms retain their structural routes',async t=>{
  const products=[seedProduct(300),seedProduct(301),seedProduct(302),seedProduct(303),seedProduct(304)].map(p=>{const c=clone(p);delete c.storeCategories;return c;});
  Object.assign(products[0],{title:'Crescent Moon Pendant',type:''});Object.assign(products[1],{title:'Cable Chain Necklace',type:'Charm'});Object.assign(products[2],{title:'Heart Flame Necklace Charm',type:'Charm'});Object.assign(products[3],{title:'Necklace and Stud Earrings Gift Set',type:'Set'});Object.assign(products[4],{title:'Moon Charm',type:'Charm'});
  const h=fixture(t,{browse:()=>response({live:true,products,pageInfo:{hasNextPage:false,endCursor:null}})});await h.ready();await h.store.execute({type:'filter',filter:'necklaces'});assert.deepEqual(h.store.snapshot().loadedPieces.map(p=>p.id),products.slice(0,4).map(p=>p.id));await h.store.execute({type:'filter',filter:'charms'});assert.deepEqual(h.store.snapshot().loadedPieces.map(p=>p.id),[products[1].id,products[2].id,products[4].id]);await h.store.execute({type:'filter',filter:'earrings'});assert.deepEqual(h.store.snapshot().loadedPieces.map(p=>p.id),[products[3].id]);await h.store.execute({type:'filter',filter:'all'});assert.deepEqual(h.store.snapshot().loadedPieces.map(p=>p.id),products.map(p=>p.id));assert.deepEqual(h.cart(),[]);assert.deepEqual(h.errors,[]);
});

test('pendant hoop titles and hoop/stud necklace motifs preserve the five approved seed groups and isolated legacy categories',async t=>{
  const products=Array.from({length:120},(_,i)=>seedProduct(i));products.forEach((p,i)=>{if(i%5===0)p.title='Halo Hoop Necklace '+i;if(i%5===1)p.title='Star Stud Beady Necklace '+i;if(i%5===3)p.title='Hawk Pendant Huggie Hoop Earrings '+i;});
  const h=fixture(t,{seed:seedData(products)});await h.ready();for(const c of seedCategories){const r=await h.store.execute({type:'filter',filter:c});assert.equal(r.ok,true);assert.deepEqual(r.snapshot.loadedPieces.map(p=>p.id),products.filter(p=>p.storeCategories.includes(c)).map(p=>p.id));}
  for(const [filter,wanted] of [['necklaces',['regular-necklaces','beady-necklaces']],['earrings',['stud-earrings','hoop-earrings']]]){const r=await h.store.execute({type:'filter',filter});assert.deepEqual(r.snapshot.loadedPieces.map(p=>p.id),products.filter(p=>p.storeCategories.some(c=>wanted.includes(c))).map(p=>p.id));assert.equal(r.snapshot.loadedPieces.length,48);}
  await h.store.execute({type:'filter',filter:'all'});assert.equal(h.store.snapshot().loadedPieces.length,120);assert.match(h.d.querySelector('.catalogue-coverage').textContent,/120 distinct live pieces checked/);assert.deepEqual(h.cart(),[]);assert.deepEqual(h.errors,[]);
});

test('balanced bootstrap checks 120 distinct identities, exposes the loaded cohort, and shows actual group coverage without inventing equal-category promises',async t=>{const h=fixture(t,{seed:seedData()});await h.ready();const s=h.store.snapshot();assert.equal(s.loadedPieces.length,120);assert.equal(new Set(s.loadedPieces.map(p=>p.id)).size,120);assert.equal(h.d.querySelectorAll('.piece-card').length,24);assert.match(h.d.querySelector('.catalogue-coverage').textContent,/120 distinct live pieces checked/);assert.match(h.d.querySelector('.catalogue-coverage').textContent,/stud earrings: 24/);assert.equal(h.requests[0].url.search,'?seed=1');assert.equal(h.requests.some(r=>r.url.searchParams.has('browse')),false);for(const c of seedCategories){assert.equal((await h.store.execute({type:'filter',filter:c})).ok,true);assert.equal(h.store.snapshot().loadedPieces.length,24);assert.ok(h.store.snapshot().loadedPieces.every(p=>p.storeCategories.includes(c)));}});

test('a partial seed is labelled with actual loaded counts rather than claiming 100 products are complete',async t=>{const h=fixture(t,{seed:seedData(Array.from({length:40},(_,i)=>seedProduct(i*5)))});await h.ready();const text=h.d.querySelector('.catalogue-coverage').textContent;assert.match(text,/40 distinct live pieces checked/);assert.match(text,/partial starting collection/);assert.match(text,/hoop earrings: 0/);assert.equal(h.store.snapshot().loadedPieces.length,40);});

test('duplicate identities or unproven seed coverage fall back to the ordinary checked browse cohort',async t=>{const bad=seedData();bad.products[1]=clone(bad.products[0]);const h=fixture(t,{seed:bad});await h.ready();assert.equal(h.store.snapshot().loadedPieces.length,1);assert.deepEqual(h.requests.filter(r=>r.url.pathname==='/api/growth/catalogue').map(r=>r.url.search),['?seed=1','?browse=1']);assert.match(h.d.querySelector('.catalogue-coverage').textContent,/balanced start could not be checked/);assert.doesNotMatch(h.d.querySelector('.catalogue-coverage').textContent,/All five/);});

test('seed continuation deliberately starts ordinary browse page one, deduplicates, then uses only its returned cursor',async t=>{const seed=seedData(),first=seedProduct(160),second=seedProduct(161),h=fixture(t,{seed,browse:url=>url.searchParams.has('cursor')?response({live:true,products:[second],pageInfo:{hasNextPage:false,endCursor:null}}):response({live:true,products:[...seed.products.slice(0,60),first],pageInfo:{hasNextPage:true,endCursor:'actual-browse-cursor'}})});await h.ready();for(let i=0;i<4;i++){h.d.querySelector('#collection-more button').click();await settle();}assert.equal(h.d.querySelectorAll('.piece-card').length,120);h.d.querySelector('#collection-more button').click();await settle();assert.equal(h.store.snapshot().loadedPieces.length,121);assert.equal(new Set(h.store.snapshot().loadedPieces.map(p=>p.id)).size,121);h.d.querySelector('#collection-more button').click();await settle();assert.equal(h.store.snapshot().loadedPieces.length,122);assert.deepEqual(h.requests.filter(r=>r.url.searchParams.has('browse')).map(r=>r.url.search),['?browse=1','?browse=1&cursor=actual-browse-cursor']);assert.equal(h.requests.filter(r=>r.url.searchParams.has('seed')).length,1);});

test('clearing a query restores the cached checked balanced cohort and retains all five requested categories',async t=>{const h=fixture(t,{seed:seedData()});await h.ready();await h.store.execute({type:'search',query:'daisy'});assert.equal(h.store.snapshot().loadedPieces.length,1);await h.store.execute({type:'search',query:'',filter:'all'});assert.equal(h.store.snapshot().loadedPieces.length,120);assert.equal(h.store.snapshot().filter,'all');assert.equal(h.requests.filter(r=>r.url.searchParams.has('seed')).length,1);assert.equal(h.store.snapshot().search,'');});
