'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const bridge=require('../../brites-storefront-bridge.js');
const product={id:'gid://shopify/Product/39001',handle:'checked-leaf-necklace',title:'Checked Leaf Necklace',description:'Published leaf necklace.',url:'https://britesjewelry.com/products/checked-leaf-necklace',currency:'USD',variantsComplete:true,options:[{name:'Metal',values:['Gold Filled']}],images:[{url:'https://cdn.shopify.com/leaf.jpg',alt:'Leaf'}],variants:[{id:'gid://shopify/ProductVariant/39002',title:'Gold Filled',price:60,available:true,options:[{name:'Metal',value:'Gold Filled'}]}]};
function harness({handoff=false}={}){let page={contextRevision:1,controlVersion:1,pageKind:'collection',visiblePieces:[product],loadedPieces:[product],inventoryPieces:[product]},calls=[];const host={snapshot:()=>page,capabilities:{controlVersion:1,mode:'sandbox',actions:['open','highlight','search'],reviewBeforeAdd:true},execute:async(action)=>{calls.push(action.type);if(action.type==='open')page={...page,contextRevision:2,pageKind:'product',currentHandle:product.handle};return {ok:true,message:'Opened checked piece.',navigationRequested:handoff};},presentProducts:async(products,options)=>{calls.push({products,options});page={...page,contextRevision:2,visiblePieces:products};return {ok:true,live:true,checkedAt:options.checkedAt,products,message:'Checked matches displayed.'};}};return {api:bridge.create({storefront:host}),calls,page:()=>page};}
test('native document navigation halts the remaining plan and preserves the handoff receipt',async()=>{const h=harness({handoff:true}),p=h.api.resolvePlan('Open Checked Leaf Necklace then highlight its price'),r=await h.api.executePlan(p.plan);assert.equal(r.ok,false);assert.equal(r.partial,true);assert.equal(r.navigationRequested,true);assert.equal(r.completedActions.length,1);assert.deepEqual(h.calls,['open']);assert.match(r.reply,/new page is opening/i);});
test('comma before then is consumed in a real multi-action request',async()=>{const h=harness(),p=h.api.resolvePlan('Open Checked Leaf Necklace, then highlight its price'),r=await h.api.executePlan(p.plan);assert.equal(r.ok,true,r.reason);assert.deepEqual(h.calls,['open','highlight']);});
for(const verb of ['Recommend','Suggest'])test(verb+' checked search displays complete host facts once under the shopper turn',async()=>{const h=harness(),text=verb+' gold filled necklaces under $60',action=h.api.resolve(text).action,options={transcript:text,context:h.page(),requestId:'checked-39',checkedSelection:{products:[product],checkedAt:Date.now(),searchQuery:'gold filled necklaces under $60'}};const r=await h.api.execute(action,options);assert.equal(r.ok,true,r.reason);assert.equal(h.calls.length,1);assert.deepEqual(h.calls[0].products[0].images,product.images);assert.deepEqual(h.calls[0].products[0].options,product.options);assert.equal(h.calls[0].options.query,'gold filled necklaces under $60');assert.equal(h.calls[0].options.searchQuery,'gold filled necklaces under $60');assert.equal((await h.api.execute(action,options)).suppressed,true);assert.equal(h.calls.length,1);});
test('checked empty selection returns an explicit empty product list',async()=>{const h=harness(),a=h.api.resolve('Find platinum necklaces'),r=await h.api.execute(a.action,{checkedSelection:{products:[],checkedAt:Date.now()}});assert.equal(r.ok,true,r.reason);assert.deepEqual(r.products,[]);assert.equal(h.calls.length,1);});
test('expired or incomplete checked host facts never dispatch a search or presentation',async()=>{for(const selection of [{products:[product],checkedAt:Date.now()-300001},{products:[{...product,variantsComplete:false}],checkedAt:Date.now()}]){const h=harness(),a=h.api.resolve('Find gold filled necklaces'),r=await h.api.execute(a.action,{checkedSelection:selection});assert.equal(r.ok,false);assert.equal(h.calls.length,0);}});
test('failed compound private field requests redact literal text',()=>{assert.equal(bridge.redactRequestText('Open my cart then set gift note to PRIVATE39'), 'Fill the exact private text in the requested visible shop field.');});
