'use strict';
// Exercise the mounted shop DOM. No microphone, model, production cart or orders.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(require.resolve('../../concierge-sandbox.html'),'utf8'),source=fs.readFileSync(require.resolve('../../concierge-sandbox.js'),'utf8');
const clone=value=>JSON.parse(JSON.stringify(value)),settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
function product(index=0,{engraving=false}={}){
  const handle=index?'maple-earrings':'daisy-necklace',options=[{name:'Metal Choice',values:['Sterling Silver','Gold Filled']},{name:'Chain Length',values:['16 inches','18 inches']}];
  if(engraving)options.push({name:'Engraving',values:['No engraving','With engraving']});
  return {id:'gid://shopify/Product/'+(3900+index),handle,title:index?'Maple Earrings':'Daisy Necklace',type:index?'Earrings':'Necklace',url:'https://britesjewelry.com/products/'+handle,description:'Published synthetic listing.',currency:'USD',image:'https://cdn.shopify.com/'+handle+'-1.jpg',images:[1,2,3].map(n=>({url:'https://cdn.shopify.com/'+handle+'-'+n+'.jpg'})),options,variantsComplete:true,checkedAt:Date.now(),detailState:'checked',variants:options[0].values.flatMap((metal,m)=>options[1].values.map((length,l)=>({id:'gid://shopify/ProductVariant/'+(39000+index*10+m*2+l),numericId:String(39000+index*10+m*2+l),title:metal+' / '+length+(engraving?' / No engraving':''),price:50+m*20+l*5,available:true,options:[{name:'Metal Choice',value:metal},{name:'Chain Length',value:length},...(engraving?[{name:'Engraving',value:'No engraving'}]:[])]})))};
}
async function fixture(t,options={}){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
  const dom=new JSDOM(html,{url:'https://preview.example/concierge-sandbox.html'+(options.query||''),runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document,rows=[product(0,options),product(1)],requests=[],reveals=[];let lookup=null,browse=null,scroll=0;
  delete d.body.dataset.inventoryPreload;delete d.body.dataset.catalogueSeed;
  w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=function(value){reveals.push({node:this,value});};w.scrollTo=value=>{scroll=value.top||0;};Object.defineProperty(w,'scrollY',{get:()=>scroll});
  w.fetch=async(raw,init={})=>{const url=new URL(raw,w.location.href);requests.push({url,init});const data=url.pathname==='/api/growth/product'?await (lookup?lookup(url,init):{live:true,product:rows.find(p=>p.handle===url.searchParams.get('handle'))}):url.pathname==='/api/growth/catalogue'?await (browse?browse(url,init):{live:true,products:rows,pageInfo:{hasNextPage:false,endCursor:null}}):{schema:1,guidance:{},conflicts:[],offers:{items:[]}};return {ok:data?.ok!==false,json:async()=>clone(data)};};
  w.eval(source);await settle();t.after(()=>w.close());const store=w.BritesSandboxStorefront;
  return {w,d,rows,requests,reveals,errors,store,lookup(fn){lookup=fn;},browse(fn){browse=fn;},cart:()=>JSON.parse(w.sessionStorage.getItem('brites-sandbox-cart')||'[]'),async open(index=0){assert.equal((await store.execute({type:'open',handle:rows[index].handle})).ok,true);},async choose(index=0,variant=0){assert.equal((await store.execute({type:'select-option',handle:rows[index].handle,variantId:rows[index].variants[variant].id})).ok,true);},async add(index=0,variant=0){await this.open(index);await this.choose(index,variant);await store.execute({type:'review-add',handle:rows[index].handle});d.querySelector('.product-review .primary').click();await settle();}};
}

test('spoken-style literal selection opens its actual option group and visibly marks the changed choice',async t=>{
  const f=await fixture(t);await f.open();const before=f.requests.length;
  const r=await f.store.execute({type:'select-option',handle:f.rows[0].handle,optionName:'Metal Choice',optionValue:'Gold Filled'}),menu=f.d.querySelector('.option-menu'),choice=menu.querySelector('[data-option-value="Gold Filled"]');
  assert.equal(r.ok,true);assert.equal(menu.hidden,false);assert.equal(menu.querySelector('[data-option-name="Metal Choice"]').hidden,false);assert.equal(menu.querySelector('[data-option-name="Chain Length"]').hidden,true);assert.equal(choice.getAttribute('aria-pressed'),'true');assert(choice.classList.contains('choice-changed'));assert(f.reveals.some(r=>r.node===choice&&r.value.behavior==='instant'));assert.equal(f.requests.length,before);assert.equal(r.snapshot.productControls.variantId,null);assert.deepEqual(f.cart(),[]);
});
test('closing an option menu preserves exact price, quantity and choices and its trigger opens it again',async t=>{
  const f=await fixture(t);await f.open();await f.choose(0,3);await f.store.execute({type:'product-quantity',handle:f.rows[0].handle,quantity:3});const before=clone(f.store.snapshot().productControls);
  assert.equal((await f.store.execute({type:'close-options'})).ok,true);assert.equal(f.d.querySelector('.option-menu').hidden,true);assert.equal(f.d.querySelector('.option-menu-trigger').getAttribute('aria-expanded'),'false');const after=f.store.snapshot().productControls;assert.equal(after.variantId,before.variantId);assert.equal(after.quantity,3);assert.equal(after.itemTotalPrice,225);f.d.querySelector('.option-menu-trigger').click();assert.equal(f.d.querySelector('.option-menu').hidden,false);
});
test('an enlarged gallery shows the new selected image immediately and provides working image controls',async t=>{
  const f=await fixture(t);await f.open();await f.choose(0,3);await f.store.execute({type:'zoom',handle:f.rows[0].handle});const before=f.requests.length;
  await f.store.execute({type:'gallery',handle:f.rows[0].handle,index:2});assert.match(f.d.querySelector('#storefront-image-dialog img').src,/-2\.jpg$/);assert.match(f.d.querySelector('.product-image-button img').src,/-2\.jpg$/);assert.match(f.d.querySelector('#storefront-image-dialog p').textContent,/image 2 of 3/);
  f.d.querySelector('[data-zoom-direction=next]').click();await settle();assert.equal(f.store.snapshot().galleryControls.selectedIndex,3);assert.match(f.d.querySelector('#storefront-image-dialog img').src,/-3\.jpg$/);assert.equal(f.d.querySelector('[data-zoom-direction=next]').disabled,true);assert.equal(f.requests.length,before);assert.equal(f.store.snapshot().productControls.variantId,f.rows[0].variants[3].id);
});
test('close enlarged image preserves selection and all accepted navigation retires the old overlay',async t=>{
  const f=await fixture(t);await f.open();await f.choose(0,1);await f.store.execute({type:'gallery',handle:f.rows[0].handle,index:2});await f.store.execute({type:'zoom',handle:f.rows[0].handle});assert.equal(f.store.snapshot().imageControls.open,true);assert.equal((await f.store.execute({type:'close-image'})).ok,true);assert.equal(f.d.querySelector('#storefront-image-dialog'),null);assert.equal(f.store.snapshot().galleryControls.selectedIndex,2);assert.equal(f.store.snapshot().productControls.variantId,f.rows[0].variants[1].id);
  for(const next of [{type:'bag'},{type:'filter',filter:'all'},{type:'open',handle:f.rows[1].handle}]){await f.open();await f.store.execute({type:'zoom',handle:f.rows[0].handle});assert.equal((await f.store.execute(next)).ok,true);assert.equal(f.d.querySelector('#storefront-image-dialog'),null);assert.equal(f.store.snapshot().imageControls.open,false);}
});
test('last literal choice and quantity can be undone in place without an HTTP read or stale review',async t=>{
  const f=await fixture(t);await f.open();await f.choose(0,1);await f.store.execute({type:'review-add',handle:f.rows[0].handle});const oldConfirm=f.d.querySelector('.product-review .primary');await f.store.execute({type:'select-option',handle:f.rows[0].handle,optionName:'Metal Choice',optionValue:'Gold Filled'});const before=f.requests.length;assert.equal(f.store.snapshot().productControls.variantId,f.rows[0].variants[3].id);assert.equal(f.store.snapshot().changeControls.canUndo,true);
  assert.equal((await f.store.execute({type:'undo'})).ok,true);assert.equal(f.store.snapshot().productControls.variantId,f.rows[0].variants[1].id);assert.equal(f.store.snapshot().productControls.reviewReady,false);assert.equal(oldConfirm.isConnected,false);oldConfirm.click();await settle();assert.deepEqual(f.cart(),[]);assert.equal(f.store.snapshot().changeControls.canUndo,false);
  await f.store.execute({type:'product-quantity',handle:f.rows[0].handle,quantity:4});await f.store.execute({type:'undo'});assert.equal(f.d.querySelector('.product-quantity input').value,'1');assert.equal(f.store.snapshot().productControls.itemTotalPrice,55);assert.equal(f.requests.length,before);
});
test('manual quantity changes receive their own reversible record rather than undoing a different older choice',async t=>{
  const f=await fixture(t);await f.open();await f.choose();const input=f.d.querySelector('.product-quantity input');input.value='3';input.dispatchEvent(new f.w.Event('change'));assert.equal(f.store.snapshot().changeControls.kind,'product-quantity');await f.store.execute({type:'undo'});assert.equal(input.value,'1');assert.equal(f.store.snapshot().productControls.variantId,f.rows[0].variants[0].id);
});
test('undo cannot replay a product mutation after a foreign page or changed exact price',async t=>{
  const f=await fixture(t);await f.open();await f.choose(0,1);await f.store.execute({type:'product-quantity',handle:f.rows[0].handle,quantity:3});await f.open(1);assert.equal((await f.store.execute({type:'undo'})).ok,false);assert.equal(f.store.snapshot().currentHandle,f.rows[1].handle);
  await f.open();await f.store.execute({type:'product-quantity',handle:f.rows[0].handle,quantity:4});f.store.presentProducts([{...f.rows[0],checkedAt:Date.now()+1,variants:f.rows[0].variants.map(v=>({...v,price:v.price+2}))}]);assert.equal((await f.store.execute({type:'undo'})).ok,false);assert.equal(f.store.snapshot().productControls.quantity,4);assert.equal(f.store.snapshot().productControls.selectedVariant.price,57);
});
test('undoing a confirmed test-bag addition removes only that exact recent line without another check',async t=>{
  const f=await fixture(t);await f.add();const before=f.requests.length;assert.equal(f.cart().length,1);assert.equal(f.store.snapshot().changeControls.kind,'bag-add');assert.equal((await f.store.execute({type:'undo'})).ok,true);assert.deepEqual(f.cart(),[]);assert.equal(f.d.querySelector('#bag-count').textContent,'0');assert.equal(f.requests.length,before);assert.equal(f.store.snapshot().productControls.variantId,f.rows[0].variants[0].id);
});
test('bag quantity and removal undo restore stable exact line identities after required fresh checks',async t=>{
  const f=await fixture(t);await f.add();await f.store.execute({type:'bag'});const line=f.store.snapshot().bagControls.lines[0];await f.store.execute({type:'bag-quantity',lineId:line.lineId,quantity:4});await f.store.execute({type:'undo'});assert.equal(f.store.snapshot().bagControls.lines[0].quantity,1);assert.equal(f.store.snapshot().bagControls.lines[0].lineId,line.lineId);
  await f.store.execute({type:'bag-remove',lineId:line.lineId});const reads=f.requests.length;assert.deepEqual(f.cart(),[]);assert.equal((await f.store.execute({type:'undo'})).ok,true);assert.equal(f.store.snapshot().bagControls.lines[0].lineId,line.lineId);assert.equal(f.cart().length,1);assert.equal(f.requests.length,reads+1);
});
test('restoring a removed bag line refuses current price drift and newer bag edits during its check',async t=>{
  const f=await fixture(t);await f.add();await f.store.execute({type:'bag'});await f.store.execute({type:'bag-remove',lineId:f.store.snapshot().bagControls.lines[0].lineId});f.lookup(()=>({live:true,product:{...f.rows[0],variants:f.rows[0].variants.map(v=>({...v,price:v.price+1}))}}));assert.equal((await f.store.execute({type:'undo'})).ok,false);assert.deepEqual(f.cart(),[]);
  const gate=deferred();f.lookup(()=>gate.promise);const pending=f.store.execute({type:'undo'});f.w.sessionStorage.setItem('brites-sandbox-cart',JSON.stringify([{productId:f.rows[1].id,title:f.rows[1].title,variantId:f.rows[1].variants[0].numericId,variant:f.rows[1].variants[0].title,price:50,currency:'USD'}]));f.d.dispatchEvent(new f.w.CustomEvent('brites:cart-updated',{detail:{sandbox:true}}));gate.resolve({live:true,product:f.rows[0]});assert.equal((await pending).ok,false);assert.equal(f.cart().length,1);assert.equal(f.cart()[0].productId,f.rows[1].id);
});
test('gift preference undo updates visible controls but never returns local note text',async t=>{
  const f=await fixture(t),wording='PRIVATE_NOTE_FOR_TEST';await f.store.execute({type:'gift-preferences',wrapping:true,giftPackage:true,giftNote:wording});const result=await f.store.execute({type:'undo'});assert.equal(result.ok,true);assert.equal(f.d.querySelector('[name=wrapping]').checked,false);assert.equal(f.d.querySelector('[name=package]').checked,false);assert.equal(f.d.querySelector('[name=note]').value,'');assert.doesNotMatch(JSON.stringify(result),/PRIVATE_NOTE_FOR_TEST/);assert.doesNotMatch(JSON.stringify(f.requests),/PRIVATE_NOTE_FOR_TEST/);
});
test('checkout history restores visible step and shipping but never restores acknowledgement or completion',async t=>{
  const f=await fixture(t);await f.add();await f.store.execute({type:'checkout'});await f.store.execute({type:'checkout-step',step:'shipping'});await f.store.execute({type:'checkout-option',option:'shipping',value:'express'});const ack=f.d.querySelector('#confirm-test-checkout');ack.checked=true;ack.dispatchEvent(new f.w.Event('change'));await f.store.execute({type:'bag'});assert.equal((await f.store.execute({type:'back'})).ok,true);await settle();const current=f.store.snapshot().checkoutControls;assert.equal(current.step,'shipping');assert.equal(current.shipping,'express');assert.equal(current.acknowledged,false);assert.equal(current.complete,false);assert.equal(f.d.querySelector('[data-demo-shipping=express]').getAttribute('aria-pressed'),'true');assert.equal(f.d.querySelector('[data-checkout-step-button=shipping]').getAttribute('aria-current'),'step');assert.equal(f.d.querySelector('.receipt'),null);
});
test('undo checkout choices restores the real buttons and never checks or completes the final acknowledgement',async t=>{
  const f=await fixture(t);await f.add();await f.store.execute({type:'checkout'});await f.store.execute({type:'checkout-option',option:'shipping',value:'express'});await f.store.execute({type:'undo'});assert.equal(f.store.snapshot().checkoutControls.shipping,'standard');await f.store.execute({type:'checkout-step',step:'confirm'});await f.store.execute({type:'undo'});assert.equal(f.store.snapshot().checkoutControls.step,'review');assert.equal(f.d.querySelector('#confirm-test-checkout').checked,false);assert.equal(f.d.querySelector('.receipt'),null);assert(f.requests.every(r=>r.init.method===undefined&&!r.init.body));
});
test('engraving uses a literal local preview and undo without exposing wording or enabling custom checkout',async t=>{
  const f=await fixture(t,{engraving:true});await f.open();const text='PRIVATE_PERSONAL_WORDS\nFor you.',before=f.requests.length,r=await f.store.execute({type:'set-engraving',handle:f.rows[0].handle,text});assert.equal(r.ok,true);assert.equal(f.d.querySelector('[name=test-engraving-preview]').value,text);assert.equal(r.snapshot.engravingControls.hasText,true);assert.doesNotMatch(JSON.stringify(r),/PRIVATE_PERSONAL_WORDS/);assert.doesNotMatch(JSON.stringify(f.w.history.state),/PRIVATE_PERSONAL_WORDS/);assert.equal(r.snapshot.productControls.variantId,null);assert.deepEqual(f.cart(),[]);assert.equal((await f.store.execute({type:'undo'})).ok,true);assert.equal(f.d.querySelector('[name=test-engraving-preview]').value,'');assert.equal(f.requests.length,before);assert.equal((await f.store.execute({type:'set-engraving',handle:f.rows[0].handle,text:'x'.repeat(301)})).ok,false);await f.open(1);assert.equal((await f.store.execute({type:'set-engraving',handle:f.rows[1].handle,text:'Hello'})).ok,false);
});
test('last collection filter and sort undo restore prior loaded scope and scroll without refetching',async t=>{
  const f=await fixture(t);f.w.scrollTo({top:420});await f.store.execute({type:'filter',filter:'earrings'});const before=f.requests.length;assert.equal((await f.store.execute({type:'undo'})).ok,true);assert.equal(f.store.snapshot().filter,'all');assert.equal(f.w.scrollY,420);await f.store.execute({type:'sort',sort:'price-desc'});await f.store.execute({type:'undo'});assert.equal(f.store.snapshot().sort,'featured');assert.equal(f.requests.length,before);
});
test('a pending failed exact read preserves the old DOM, keyboard focus, gallery dialog and navigation ledger',async t=>{
  const f=await fixture(t);const anchor=f.d.querySelector('.piece-card a');anchor.focus();const gate=deferred();f.lookup(()=>gate.promise);const pending=f.store.execute({type:'open',handle:f.rows[1].handle});assert.equal(anchor.isConnected,true);assert.equal(f.d.activeElement,anchor);assert.equal(f.store.snapshot().pageKind,'collection');assert.equal(f.store.snapshot().navigationControls.canGoBack,false);gate.resolve({ok:false});assert.equal((await pending).ok,false);assert.equal(anchor.isConnected,true);assert.equal(f.d.activeElement,anchor);assert.equal(f.store.snapshot().navigationControls.canGoBack,false);
  f.lookup(null);await f.open();await f.store.execute({type:'zoom',handle:f.rows[0].handle});const dialog=f.d.querySelector('#storefront-image-dialog');f.lookup(()=>({ok:false}));assert.equal((await f.store.execute({type:'open',handle:f.rows[1].handle})).ok,false);assert.equal(f.d.querySelector('#storefront-image-dialog'),dialog);assert.equal(f.store.snapshot().currentHandle,f.rows[0].handle);
});
test('a cold deep product returning to its unverified collection performs the missing catalogue read',async t=>{
  const f=await fixture(t,{query:'?product=daisy-necklace'});assert.equal(f.store.snapshot().pageKind,'product');assert.equal(f.requests.filter(r=>r.url.pathname==='/api/growth/catalogue').length,0);f.d.querySelector('.back-link').click();await settle();assert.equal(f.requests.filter(r=>r.url.pathname==='/api/growth/catalogue').length,1);assert.equal(f.store.snapshot().pageKind,'collection');assert.equal(f.d.querySelectorAll('.piece-card').length,2);assert.equal(f.errors.length,0);
});
test('failed cold collection navigation preserves the existing product DOM, focus and URL',async t=>{
  const f=await fixture(t,{query:'?product=daisy-necklace'}),productNode=f.d.querySelector('.product-layout'),back=f.d.querySelector('.back-link'),url=f.w.location.href,gate=deferred();back.focus();f.browse(()=>gate.promise);back.click();assert.equal(productNode.isConnected,true);assert.equal(f.d.activeElement,back);assert.equal(f.w.location.href,url);gate.resolve({ok:false});await settle();assert.equal(f.d.querySelector('.product-layout'),productNode);assert.equal(f.store.snapshot().currentHandle,f.rows[0].handle);assert.equal(f.d.activeElement,back);assert.equal(f.w.location.href,url);assert.equal(f.store.snapshot().loading,false);
});
