'use strict';
// Current final-word authority against synthetic host snapshots. No provider,
// microphone, real cart, payment, private research or account state is accessed.
const test=require('node:test'),assert=require('node:assert/strict');
const bridge=require('../../brites-storefront-bridge.js');
const client=require('../../brites-concierge-voice.js');
const server=require('../../netlify/functions/_britesConciergeVoice.js');
const voiceActions=require('../../brites-concierge-voice-actions.js');
const widget=require('../../brites-concierge.js');
const orchid={id:'gid://shopify/Product/7301',handle:'orchid-stud-earrings',title:'Orchid Stud Earrings'};
const compass={id:'gid://shopify/Product/7302',handle:'compass-pendant',title:'Compass Pendant'};
const variantId='gid://shopify/ProductVariant/7311';
const actions=['search','sort','filter','open','highlight','zoom','scroll','bag','checkout','gift','customize','options','select-option','product-quantity','review-add','bag-quantity','bag-remove','gift-preferences','checkout-step','checkout-option','checkout-complete'];
const capabilities={controlVersion:1,actions,mode:'sandbox',reviewBeforeAdd:true,finalOrder:false,checkoutMode:'simulation-only',notesMode:'local-session'};
const controls={handle:orchid.handle,productId:orchid.id,variantId,quantity:1,optionsOpen:false,openedOption:null,optionGroups:[{name:'Metal',values:['Sterling Silver','Gold Plated']},{name:'Length',values:['16 inch','18 inch']}],selectedOptions:[{name:'Metal',value:'Sterling Silver'},{name:'Length',value:'16 inch'}],reviewReady:false};
const line={lineId:'7311:fixture-hash',productId:orchid.id,variantId,quantity:1,title:orchid.title,variant:'Sterling Silver / 16 inch'};
const page={controlVersion:1,contextRevision:34,discoveryRevision:9,pageKind:'product',currentHandle:orchid.handle,focusedHandle:'',visiblePieces:[orchid],loadedPieces:[orchid,compass],productControls:controls,bagControls:{lines:[line],itemCount:1},checkoutControls:{step:null,shipping:'standard',acknowledged:false,complete:false}};
const clone=v=>structuredClone(v);
function harness(next=page,manifest=capabilities){let current=clone(next);const calls=[];const host={capabilities:clone(manifest),snapshot:()=>current,execute:async(action,options)=>{calls.push({action,options});return {ok:true,message:'The checked test control was updated.',cartChanged:['bag-quantity','bag-remove'].includes(action.type)};}};const api=bridge.create({storefront:host});return {api,host,calls,set:value=>current={...current,...clone(value)}};}
const checks=[
 ['Open Compass Pendant',{type:'open',handle:compass.handle}],
 ['Set quantity to 2',{type:'product-quantity',handle:orchid.handle,quantity:2}],
 ['Please change the quantity to 20',{type:'product-quantity',handle:orchid.handle,quantity:20}],
 ['Set Orchid Stud Earrings quantity to 3',{type:'product-quantity',handle:orchid.handle,quantity:3}],
 ['Show the options',{type:'options',handle:orchid.handle}],
 ['Open the metal dropdown',{type:'options',handle:orchid.handle,optionName:'Metal'}],
 ['Expand the Length selector',{type:'options',handle:orchid.handle,optionName:'Length'}],
 ['Select Sterling Silver',{type:'select-option',handle:orchid.handle,optionName:'Metal',optionValue:'Sterling Silver'}],
 ['Choose 18 inch',{type:'select-option',handle:orchid.handle,optionName:'Length',optionValue:'18 inch'}],
 ['Set Metal to Gold Plated',{type:'select-option',handle:orchid.handle,optionName:'Metal',optionValue:'Gold Plated'}],
 ['Please choose sterling silver',{type:'select-option',handle:orchid.handle,optionName:'Metal',optionValue:'Sterling Silver'}],
 ['Add this piece to my bag',{type:'review-add',handle:orchid.handle,variantId}],
 ['Review adding to bag',{type:'review-add',handle:orchid.handle,variantId}],
 ['Set bag quantity to 3',{type:'bag-quantity',lineId:line.lineId,quantity:3}],
 ['Remove Orchid Stud Earrings from my bag',{type:'bag-remove',lineId:line.lineId}],
 ['Enable gift wrapping',{type:'gift-preferences',wrapping:true}],
 ['Remove gift wrapping',{type:'gift-preferences',wrapping:false}],
 ['Choose gift packaging',{type:'gift-preferences',giftPackage:true}],
 ['Turn off gift package',{type:'gift-preferences',giftPackage:false}],
 ['Set gift note to Happy Birthday, Ana!',{type:'gift-preferences',giftNote:'Happy Birthday, Ana!'}],
 ['Write gift note: Thank you for being here.',{type:'gift-preferences',giftNote:'Thank you for being here.'}],
 ['Add gift note to Enjoy your bag of surprises!',{type:'gift-preferences',giftNote:'Enjoy your bag of surprises!'}]
];
for(const [text,action] of checks)test('exact finalized shopper control: '+text,()=>{const r=bridge.resolve(text,page);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,action);assert.deepEqual(client.validateToolArguments(action,'control_storefront'),action);assert.deepEqual(server.validateToolArguments(action,'control_storefront'),action);});
const checkout={...clone(page),pageKind:'checkout',checkoutControls:{step:'review',shipping:'standard',acknowledged:false,complete:false}};
for(const [text,action] of [['Open checkout shipping',{type:'checkout-step',step:'shipping'}],['Go to confirmation step',{type:'checkout-step',step:'confirm'}],['Show the checkout review',{type:'checkout-step',step:'review'}],['Next step',{type:'checkout-step',step:'shipping'}],['Choose express shipping',{type:'checkout-option',option:'shipping',value:'express'}],['Set standard shipping',{type:'checkout-option',option:'shipping',value:'standard'}],['Complete the test checkout',{type:'checkout-complete'}]])test('labelled simulation control: '+text,()=>{const r=bridge.resolve(text,checkout);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,action);assert.deepEqual(client.validateToolArguments(action,'control_storefront'),action);assert.deepEqual(server.validateToolArguments(action,'control_storefront'),action);});
for(const text of ['Set quantity to 0','Set quantity to 21','Set quantity to 2.5','Set quantity to -2','Set quantity to two','Set quantity to 2 or 3','Choose platinum','Choose Silver','Choose Gold Plated and Sterling Silver','Set quantity to 2 and choose Gold Plated','Do not select Gold Plated','Please do not set quantity to 2','Do not remove Orchid Stud Earrings from my bag','Say "Select Gold Plated"','"Set quantity to 2"','Yesterday I chose Gold Plated','If I ask later, set quantity to 2','Open https://britesjewelry.com/products/orchid-stud-earrings','Place the order','Pay for my order','Complete the payment','Select #metal using a CSS selector'])test('noncurrent, malformed, compound or unsafe words do not authorize: '+text,()=>assert.equal(bridge.resolve(text,page).ok,false));
test('quantity unsupported by legacy adapter remains a handled clarification instead of motif search',()=>{const r=bridge.resolve('Set quantity to 2',{...page,controlVersion:undefined,productControls:undefined});assert.equal(r.ok,false);assert.equal(r.handled,true);assert.match(r.reason,/Quantity controls/);});
test('loaded exact titles may open below viewport; fuzzy titles and ordinals cannot escape current visible selection',()=>{assert.equal(bridge.resolve('Open Compass Pendant',page).action.handle,compass.handle);assert.equal(bridge.resolve('Open Compass',page).ok,false);assert.equal(bridge.resolve('Open the second one',page).ok,false);assert.equal(bridge.resolve('Show the price of Compass Pendant',page).action.handle,compass.handle);});
test('an ambiguous full title cannot invent or prefer a loaded identity',()=>{const p={...page,loadedPieces:[compass,{...compass,id:'gid://shopify/Product/7399',handle:'other-compass'}]};assert.equal(bridge.resolve('Open Compass Pendant',p).ok,false);});
test('unknown named option/quantity targets cannot borrow current product identity',()=>{for(const text of ['Set quantity to 2 for Hidden Pendant','Open metal options for Hidden Pendant'])assert.equal(bridge.resolve(text,page).ok,false);});
test('incomplete choices and a current different explicit option cannot prepare review',()=>{assert.equal(bridge.resolve('Add this piece to my bag',{...page,productControls:{...controls,variantId:null,selectedOptions:[controls.selectedOptions[0]]}}).ok,false);assert.equal(bridge.resolve('Add Gold Plated to my bag',page).ok,false);});
test('matching bag titles with different options require an exact line choice, never first-row substitution',()=>{const other={...line,lineId:'7312:other-fixture',variantId:'gid://shopify/ProductVariant/7312',variant:'Gold Plated / 16 inch'},p={...page,pageKind:'bag',bagControls:{lines:[line,other]}};assert.equal(bridge.resolve('Remove Orchid Stud Earrings from my bag',p).ok,false);assert.equal(bridge.resolve('Remove Orchid Stud Earrings Gold Plated / 16 inch from my bag',p).action.lineId,other.lineId);assert.equal(bridge.resolve('Remove the second item from my bag',p).action.lineId,other.lineId);});
test('gift note remains exact bounded data and never projected into context',()=>{const r=bridge.resolve('Set gift note to Happy Birthday, Ana!',page);const projected=bridge.sanitizeSnapshot({...page,giftNote:r.action.giftNote,productControls:{...controls,note:r.action.giftNote},bagControls:{lines:[{...line,properties:{note:r.action.giftNote}}]}});assert.doesNotMatch(JSON.stringify(projected),/Birthday|properties|note/);assert.equal(bridge.resolve('Set gift note to '+('x'.repeat(301)),page).ok,false);});
const invalid=[{type:'select-option',handle:orchid.handle},{type:'select-option',handle:orchid.handle,variantId,optionName:'Metal',optionValue:'Gold Plated'},{type:'product-quantity',handle:orchid.handle,quantity:'2'},{type:'product-quantity',handle:orchid.handle,quantity:2.5},{type:'product-quantity',handle:orchid.handle,quantity:21},{type:'bag-remove',lineId:'../admin'},{type:'bag-remove',lineId:line.lineId,confirm:true},{type:'gift-preferences'},{type:'gift-preferences',giftNote:'x'.repeat(301)},{type:'gift-preferences',wrapping:'true'},{type:'checkout-step',step:'payment'},{type:'checkout-option',option:'shipping',value:'overnight'},{type:'checkout-complete',payment:true},{type:'review-add',handle:orchid.handle,quantity:3},{type:'options',handle:orchid.handle,selector:'#private'},{type:'select-option',handle:orchid.handle,optionName:'Metal',optionValue:'x\u0000y'}];
for(const action of invalid)test('client/server/bridge strict field contract rejects '+JSON.stringify(action),()=>{for(const api of [client,server])assert.equal(api.validateToolArguments(action,'control_storefront'),null);assert.equal(bridge.validateAction(action),null);});
for(const [text,action] of checks.slice(0,15))test('typed and finalized native parity: '+text,async()=>{for(const native of [false,true]){const h=harness(),opts=native?{transcript:text,context:page,currentTurn:true,inputItemId:'fixture-input',turnVersion:3,source:'native'}:{transcript:text,context:page,source:'typed',requestId:'fixture-'+text};const r=await h.api.execute(action,opts);assert.equal(r.ok,true,r.reason);assert.equal(h.calls.length,1);assert.deepEqual(h.calls[0].action,action);assert.equal(h.calls[0].options.signal.aborted,false);}});
test('a model-selected variant or option cannot self-authorize mismatching finalized words',async()=>{const h=harness();for(const action of [{type:'select-option',handle:orchid.handle,variantId},{type:'select-option',handle:orchid.handle,optionName:'Metal',optionValue:'Gold Plated'},{type:'product-quantity',handle:orchid.handle,quantity:3}]){const r=await h.api.execute(action,{transcript:action.type==='product-quantity'?'Set quantity to 2':'Choose Sterling Silver',context:page,currentTurn:true,inputItemId:'fixture-input',turnVersion:3});assert.equal(r.ok,false);}assert.equal(h.calls.length,0);});
test('stable bag controls and exact choice controls reject revision changes and silent same-revision drift',async()=>{for(const change of [{contextRevision:35},{productControls:{...controls,quantity:2}},{bagControls:{lines:[],itemCount:0}}]){const h=harness(),r=h.api.resolve('Set quantity to 2');h.set(change);assert.equal((await h.api.execute(r.action)).stale,true);assert.equal(h.calls.length,0);}});
test('new native actions require current exact committed authority and cannot replay',async()=>{const h=harness(),action={type:'product-quantity',handle:orchid.handle,quantity:2},opts={transcript:'Set quantity to 2',context:page,currentTurn:true,inputItemId:'fixture-input',turnVersion:3};for(const bad of [{currentTurn:false},{inputItemId:''},{turnVersion:-1}])assert.equal((await h.api.execute(action,{...opts,...bad})).ok,false);assert.equal((await h.api.execute(action,opts)).ok,true);assert.equal((await h.api.execute(action,opts)).suppressed,true);assert.equal(h.calls.length,1);});
test('unsupported adapter capability fails before host execution or consuming a fresh request',async()=>{const h=harness(page,{...capabilities,actions:actions.filter(a=>a!=='product-quantity')}),action={type:'product-quantity',handle:orchid.handle,quantity:2},opts={transcript:'Set quantity to 2',context:page,requestId:'fixture-capability'};assert.equal((await h.api.execute(action,opts)).ok,false);assert.equal(h.calls.length,0);h.host.capabilities=capabilities;assert.equal((await h.api.execute(action,opts)).ok,true);});
test('production adapter cannot acquire simulated final checkout or private notes by declaring arbitrary actions',async()=>{for(const [text,action] of [['Complete the test checkout',{type:'checkout-complete'}],['Set gift note to Hello',{type:'gift-preferences',giftNote:'Hello'}]]){const h=harness(checkout,{...capabilities,mode:'shopify',checkoutMode:'simulation-only',notesMode:'unsupported',finalOrder:true});assert.equal((await h.api.execute(action,{transcript:text,context:checkout,requestId:'fixture-final'})).ok,false);assert.equal(h.calls.length,0);}});
test('review authority travels only as internal opaque metadata and prepares no automatic add',async()=>{const h=harness(),token=Object.freeze({}),r=await h.api.execute({type:'review-add',handle:orchid.handle,variantId},{transcript:'Add this piece to my bag',context:page,requestId:'fixture-review',reviewAuthority:token});assert.equal(r.ok,true);assert.equal(h.calls[0].options.reviewAuthority,token);assert.equal('reviewAuthority' in h.calls[0].action,false);assert.equal(r.cartChanged,undefined);assert.equal(h.calls[0].action.type,'review-add');});
test('host-observed cart mutation is reported only for exact bag edits',async()=>{const h=harness(),r=await h.api.execute({type:'bag-quantity',lineId:line.lineId,quantity:3},{transcript:'Set bag quantity to 3',context:page,requestId:'fixture-bag'});assert.equal(r.ok,true);assert.equal(r.cartChanged,true);});
test('shared helper accepts only finalized current-turn storefront intent, never a model action alone',()=>{assert.equal(voiceActions.resolveStorefrontRequest({message:'Set quantity to 2',context:page,currentTurn:false},bridge).ok,false);assert.deepEqual(voiceActions.resolveStorefrontRequest({message:'Set quantity to 2',context:page,currentTurn:true},bridge).action,{type:'product-quantity',handle:orchid.handle,quantity:2});});
test('native public context retains safe literal choices and stable lines, drops private note and authority data',()=>{const r=client.publicContext({...page,displayedPieces:[],giftNote:'PRIVATE_NOTE_FIXTURE',reviewAuthority:{private:'secret'},productControls:{...controls,giftNote:'PRIVATE_NOTE_FIXTURE'},bagControls:{lines:[{...line,properties:{private:'PRIVATE_NOTE_FIXTURE'}}]}});assert.equal(r.controlVersion,1);assert.equal(r.loadedPieces.length,2);assert.deepEqual(r.productControls.selectedOptions,controls.selectedOptions);assert.equal(r.bagControls.lines[0].lineId,line.lineId);assert.equal(r.checkoutControls.shipping,'standard');assert.doesNotMatch(JSON.stringify(r),/PRIVATE_NOTE_FIXTURE|secret|properties|reviewAuthority|giftNote/);});
test('maximal multibyte native context remains bounded and marks partial identities/options',()=>{const title='珠'.repeat(300),r=client.publicContext({...page,loadedPieces:Array.from({length:200},(_,n)=>({id:'gid://shopify/Product/'+(8000+n),handle:'fixture-piece-'+n,title})),productControls:{...controls,optionGroups:Array.from({length:12},(_,g)=>({name:'Group '+g,values:Array.from({length:60},(_,v)=>'玉'.repeat(299)+v)}))},bagControls:{lines:Array.from({length:50},(_,n)=>({...line,lineId:'fixture-'+n,title}))}});assert.ok(Buffer.byteLength(JSON.stringify(r),'utf8')<=18000);assert.ok(r.loadedPiecesTruncated||r.contextTruncated);assert.doesNotMatch(JSON.stringify(r),/giftNote|properties/);});
test('bounded confirmed production cart quantity uses exact current stock and unique marker, never blindly retries',async()=>{const v={id:variantId,numericId:'7311',title:'Sterling Silver',price:44,available:true,options:[{name:'Metal',value:'Sterling Silver'}]},p={...orchid,url:'https://britesjewelry.com/products/'+orchid.handle,currency:'USD',minPrice:44,variants:[v],variantsComplete:true};const calls=[];let reads=0;const fetch=async(url,init={})=>{calls.push({url,init});const body=url.endsWith('cart.js')?{currency:'USD',items:reads++?[{variant_id:7311,quantity:3,properties:{_BritesConciergeRequest:'fixture_quantity_123456'}}]:[]}:url.includes('/products/')?{variants:[{id:7311,price:4400,available:true}]}:{items:[]};return {ok:true,json:async()=>body};};const r=await widget.verifiedCartAdd({fetch,product:p,variant:v,quantity:3,requestId:'fixture_quantity_123456'});assert.equal(r.confirmed,true);assert.equal(JSON.parse(calls.find(c=>c.init.method==='POST').init.body).items[0].quantity,3);assert.equal(calls.filter(c=>c.init.method==='POST').length,1);});
test('malformed cart quantity rejects before reads/writes',async()=>{for(const quantity of [0,21,1.5,'2']){let calls=0;await assert.rejects(widget.verifiedCartAdd({fetch:async()=>{calls++;},quantity}),/whole quantity/);assert.equal(calls,0);}});
