'use strict';
// Actual native adapter, synthetic transport only: no inference or microphone.
const test=require('node:test'),assert=require('node:assert/strict');
const client=require('../../brites-concierge-voice.js'),server=require('../../netlify/functions/_britesConciergeVoice.js');
const piece={id:'gid://shopify/Product/3100',handle:'compass-necklace',title:'Compass Necklace'};
const SDP='v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\na=candidate:1 1 UDP 2122260223 192.0.2.10 50000 typ host\r\n';
const settle=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(t,{onTool=async()=>({ok:true,live:true}),getContext}={}){
  let channel,serial=0;const sent=[],calls=[],timers=new Map();
  const track={stop(){}},stream={getTracks:()=>[track],getAudioTracks:()=>[track]};
  const document={hidden:false,body:{appendChild(){}},createElement:()=>({setAttribute(){},play:async()=>{},pause(){},remove(){}}),addEventListener(){},removeEventListener(){}};
  class Peer{constructor(){this.iceGatheringState='complete';}addTrack(){}close(){}createDataChannel(){channel={readyState:'connecting',send:v=>sent.push(JSON.parse(v)),close(){}};return channel;}async createOffer(){return {type:'offer',sdp:SDP};}async setLocalDescription(value){this.localDescription=value;}async setRemoteDescription(){channel.readyState='open';channel.onopen();}}
  const runtime={document,navigator:{mediaDevices:{getUserMedia:async()=>stream}},location:{origin:'https://preview.test'},RTCPeerConnection:Peer,AbortController,addEventListener(){},removeEventListener(){},setTimeout(fn,ms){const id=++serial;timers.set(id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id),fetch:async(url,init)=>Response.json(JSON.parse(init.body).action==='capabilities'?{enabled:true}:JSON.parse(init.body).action==='start'?{sdp:SDP,stopToken:'synthetic-token',maxDurationMs:120000}:{stopped:true})};
  const voice=client.create({runtime,greeting:false,getContext,onTool:async(args,context)=>{calls.push({args,context});return onTool(args,context);}});
  t.after(()=>voice.dispose());
  const emit=event=>channel.onmessage({data:JSON.stringify(event)}),responses=()=>sent.filter(e=>e.type==='response.create');
  function begin(item='input-current'){emit({type:'input_audio_buffer.speech_started',item_id:item});emit({type:'input_audio_buffer.speech_stopped',item_id:item});emit({type:'input_audio_buffer.committed',item_id:item});}
  function bind(id='response-current',metadata=responses().at(-1)?.response.metadata){emit({type:'response.created',response:{id,metadata}});}
  function tool(name,args,id='response-current',call_id='tool-current'){emit({type:'response.function_call_arguments.done',response_id:id,call_id,name,arguments:JSON.stringify(args)});}
  return {voice,sent,calls,emit,begin,bind,tool,responses,document};
}
const nativeActions=[{type:'options',handle:piece.handle,optionName:'Metal'},{type:'select-option',handle:piece.handle,optionName:'Metal',optionValue:'Sterling Silver'},{type:'product-quantity',handle:piece.handle,quantity:2},{type:'review-add',handle:piece.handle,variantId:'gid://shopify/ProductVariant/3111'},{type:'bag-quantity',lineId:'3111:fixture-hash',quantity:3},{type:'bag-remove',lineId:'3111:fixture-hash'},{type:'gift-preferences',wrapping:true},{type:'checkout-step',step:'shipping'},{type:'checkout-option',option:'shipping',value:'express'},{type:'checkout-complete'}];
for(const action of nativeActions)test('actual native adapter transports one bounded current action '+action.type,async t=>{const f=fixture(t,{onTool:async()=>({ok:true,cartChanged:['bag-quantity','bag-remove'].includes(action.type),publicContext:{controlVersion:1}})});await f.voice.start();f.begin();f.bind();f.tool('control_storefront',action);f.tool('control_storefront',action);await settle();assert.equal(f.calls.length,1);assert.deepEqual(f.calls[0].args,action);assert.equal(f.calls[0].context.currentTurn,true);assert.equal(f.calls[0].context.inputItemId,'input-current');assert.equal(f.responses().length,1);f.emit({type:'response.done',response:{id:'response-current',status:'completed'}});assert.equal(f.responses().at(-1).response.tool_choice,'none');});
test('actual native context keeps loaded exact identities and published controls, omits note/prompt/permission data and does not send every hover',async t=>{let page={pageKind:'product',contextRevision:1,currentHandle:piece.handle,controlVersion:1,visiblePieces:[piece],loadedPieces:[piece,{id:'gid://shopify/Product/3101',handle:'fixture-earrings',title:'Fixture Stud Earrings',instructions:'UNTRUSTED_FIXTURE'}],productControls:{handle:piece.handle,productId:piece.id,variantId:'gid://shopify/ProductVariant/3111',quantity:2,optionGroups:[{name:'Metal',values:['Sterling Silver']}],selectedOptions:[{name:'Metal',value:'Sterling Silver'}],optionsOpen:true,openedOption:'Metal',reviewReady:false,giftNote:'PRIVATE_NOTE_FIXTURE'},bagControls:{lines:[]},checkoutControls:{step:null,shipping:'standard',acknowledged:false,complete:false},permissions:['buy'],token:'SECRET_FIXTURE'};const f=fixture(t,{getContext:()=>page});await f.voice.start();const contexts=()=>f.sent.filter(e=>e.item?.content?.[0]?.text?.startsWith('Public website UI context'));const count=contexts().length;for(let n=2;n<52;n++)page={...page,contextRevision:n};assert.equal(contexts().length,count);f.begin();assert.equal(contexts().length,count+1);const message=contexts().at(-1).item.content[0].text;assert.match(message,/Fixture Stud Earrings/);assert.match(message,/"quantity":2/);assert.match(message,/"optionName"|"name":"Metal"/);assert.doesNotMatch(message,/PRIVATE_NOTE_FIXTURE|UNTRUSTED_FIXTURE|SECRET_FIXTURE|permissions|buy/);assert.equal(f.calls.length,0);});
test('new controls on unbound, interrupted or uncommitted native input cannot invoke host',async t=>{const f=fixture(t);await f.voice.start();f.begin('old-input');f.bind('old-response');f.begin('new-input');f.bind('unbound-response',{});f.tool('control_storefront',nativeActions[2],'old-response','old-call');f.tool('control_storefront',nativeActions[4],'unbound-response','unbound-call');f.emit({type:'input_audio_buffer.speech_started',item_id:'pending-input'});f.bind('pending-response',f.responses().at(-1).response.metadata);f.tool('control_storefront',nativeActions[3],'pending-response','pending-call');await settle();assert.equal(f.calls.length,0);});
