'use strict';
// Mount the real sandbox, bridge and guide. Dialog/native audio APIs are spies;
// this checks interaction and mode contracts, not browser pixel layout.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const source=Object.fromEntries(['concierge-sandbox.html','concierge-sandbox.js','concierge-sandbox.css','brites-storefront-bridge.js','brites-concierge.js','brites-concierge.css'].map(name=>[name,fs.readFileSync(require.resolve('../../'+name),'utf8')]));
const clone=value=>JSON.parse(JSON.stringify(value)),settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
function piece(index){const handle=index?'maple-earrings':'daisy-necklace';return {id:'gid://shopify/Product/'+(39400+index),handle,title:index?'Maple Earrings':'Daisy Necklace',type:index?'Earrings':'Necklace',description:'Published synthetic piece.',url:'https://britesjewelry.com/products/'+handle,currency:'USD',checkedAt:Date.now(),detailState:'checked',variantsComplete:true,image:'https://cdn.shopify.com/'+handle+'-1.jpg',images:[1,2,3].map(n=>({url:'https://cdn.shopify.com/'+handle+'-'+n+'.jpg'})),options:[{name:'Metal Choice',values:['Sterling Silver']}],variants:[{id:'gid://shopify/ProductVariant/'+(394000+index),numericId:String(394000+index),title:'Sterling Silver',price:50,available:true,options:[{name:'Metal Choice',value:'Sterling Silver'}]}]};}
async function fixture(t,{width=1440,height=900,nativeShow=true}={}){
  const errors=[],virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',error=>errors.push(error));const dom=new JSDOM(source['concierge-sandbox.html'],{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole}),w=dom.window,d=w.document,rows=[piece(0),piece(1)],requests=[],calls={show:0,modal:0,avatarCreates:0,avatarDestroys:0,starts:0,stops:0},media=[];let voiceConfig,turn=0;
  w.innerWidth=width;w.innerHeight=height;delete d.body.dataset.catalogueSeed;
  w.matchMedia=query=>{const item={matches:query.includes('1100px')?w.innerWidth>=1100:false,addEventListener(type,fn){this.listener=fn;}};media.push({query,item});return item;};
  w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=()=>{};
  // A mistaken showModal would reproduce browser inertness and fail the test.
  w.HTMLDialogElement.prototype.showModal=function(){calls.modal++;d.body.querySelectorAll('brites-concierge,main').forEach(node=>node.setAttribute('inert',''));this.setAttribute('open','');};
  if(nativeShow)w.HTMLDialogElement.prototype.show=function(){calls.show++;this.setAttribute('open','');};else w.HTMLDialogElement.prototype.show=undefined;
  const style=d.createElement('style');style.textContent=source['concierge-sandbox.css'];d.head.appendChild(style);
  w.fetch=async(raw,init={})=>{const url=new URL(raw,w.location.href);requests.push({url,init});let body;if(url.pathname==='/api/growth/catalogue')body={live:true,checkedAt:Date.now(),products:rows,pageInfo:{hasNextPage:false,endCursor:null}};else if(url.pathname==='/api/growth/inventory')body={live:true,checkedAt:Date.now(),products:rows,inventory:{schema:1,total:2,offset:0,limit:24,loaded:2,detailsLoaded:2,ready:true,partial:false,expiresAt:Date.now()+300000},pageInfo:{hasNextPage:false,nextOffset:null}};else if(url.pathname==='/api/growth/product')body={live:true,checkedAt:Date.now(),product:rows.find(p=>p.handle===url.searchParams.get('handle'))};else if(url.pathname==='/api/growth/storefront-services')body={schema:1,guidance:{},conflicts:[],offers:{items:[]}};else if(['/api/growth/events','/api/concierge-voice'].includes(url.pathname))body={ok:true,enabled:true,nativeAudio:true,publicDemo:true};else if(url.pathname==='/api/concierge')body={live:true,reply:'Welcome to the synthetic boutique.',products:[],meanings:[],preferences:{},preserveSelection:true};else throw Error('Unexpected viewer request '+url.pathname);return {ok:true,json:async()=>clone(body)};};
  w.eval(source['brites-storefront-bridge.js']);w.eval(source['concierge-sandbox.js']);await settle();await w.BritesSandboxStorefront.preloadInventory();
  const avatar={setState(){},setEmotion(){},setVisible(){},setPaused(){},retry(){},triggerGreeting(){},clearFocus(){},focusProduct(){},setLevel(){},setSpeechSignal(){},clearProduct(){},showProduct(){},cancelPerformance(){},setFloating(){},cue(){},destroy(){calls.avatarDestroys++;}};
  w.BritesConciergeAvatar={create(){calls.avatarCreates++;return avatar;}};
  const client={state:'listening',outputMeterState:'ready',playbackBlocked:false,start:async()=>{calls.starts++;return true;},stop:async()=>{calls.stops++;},dispose:async()=>{},updateContext(){},currentOutput:null};
  w.BritesConciergeVoice={create(config){voiceConfig=config;return client;}};
  const script=d.createElement('script');script.src='/brites-concierge.js';script.dataset.sandbox='true';Object.defineProperty(d,'currentScript',{get:()=>script});w.eval(source['brites-concierge.js']);await settle();const host=d.querySelector('brites-concierge'),root=host.shadowRoot;w.BritesConcierge.open({focus:false});await settle();
  t.after(()=>{w.BritesConcierge.close();w.close();});
  async function command(text){return w.BritesConcierge.sendShopperCommand(text);}
  async function voice(){root.querySelector('.voice-button').click();await settle();root.querySelector('script[src$="brites-concierge-voice.js"]')?.dispatchEvent(new w.Event('load'));await settle();assert(voiceConfig,'The real guide must establish its voice callbacks');}
  async function say(text){const itemId='viewer-input-'+(++turn);voiceConfig.onSpeechStarted({itemId,turnVersion:turn});voiceConfig.onTranscript({role:'user',itemId,turnVersion:turn,currentTurn:true,text,final:true});return voiceConfig.onFinalizedTurn({text,inputItemId:itemId,turnVersion:turn,currentTurn:true,finalized:true});}
  function resize(nextWidth,nextHeight){w.innerWidth=nextWidth;w.innerHeight=nextHeight;media.forEach(({query,item})=>{if(query.includes('1100px')){item.matches=nextWidth>=1100;item.listener?.();}});w.dispatchEvent(new w.Event('resize'));}
  return {w,d,root,host,rows,requests,calls,errors,store:w.BritesSandboxStorefront,command,voice,say,resize,dialog:()=>d.querySelector('#storefront-image-dialog')};
}
test('the actual viewer uses nonmodal dialog semantics and leaves the same guide interactive',async t=>{
  const f=await fixture(t);await f.command('Open Daisy Necklace');const host=f.host,stage=f.root.querySelector('.concierge-avatar-stage'),requests=f.requests.length;await f.command('Enlarge this piece');const dialog=f.dialog();
  assert(dialog.open);assert.equal(dialog.getAttribute('aria-modal'),'false');assert.equal(f.calls.show,1);assert.equal(f.calls.modal,0);assert.equal(f.host,f.d.querySelector('brites-concierge'));assert.equal(f.root.querySelector('.concierge-avatar-stage'),stage);assert.equal(f.calls.avatarCreates,1);assert.equal(f.calls.avatarDestroys,0);assert.equal(host.hasAttribute('inert'),false);assert.equal(host.closest('[inert]'),null);assert.equal(f.d.querySelector('main').hasAttribute('inert'),false);assert.equal(host.getAttribute('data-storefront-image-open'),'true');
  const input=f.root.querySelector('.composer input');input.focus();assert.equal(f.root.activeElement,input);assert.equal(input.disabled,false);
  const next=await f.command('Show the next image');assert.equal(next.ok,true,next.reply);assert.equal(f.dialog(),dialog);assert.match(dialog.querySelector('img').src,/-2\.jpg$/);assert.equal(next.snapshot.galleryControls.selectedIndex,2);
  input.focus();const closed=await f.command('Close the image');assert.equal(closed.ok,true,closed.reply);assert.equal(f.dialog(),null);assert.equal(host.getAttribute('data-storefront-image-open'),'false');assert.equal(f.root.activeElement,input,'A typed close must not steal focus back into the storefront');assert.equal(f.requests.length,requests);assert.equal(f.calls.modal,0);assert.equal(f.errors.length,0);
});
test('fallback dialog opening is still nonmodal and actual close and cancel controls retire the mode',async t=>{
  const f=await fixture(t,{nativeShow:false});await f.command('Open Daisy Necklace');await f.command('Enlarge this piece');assert(f.dialog().open);f.dialog().querySelector('.dialog-close').click();assert.equal(f.dialog(),null);assert.equal(f.host.getAttribute('data-storefront-image-open'),'false');assert.equal(f.d.activeElement,f.d.querySelector('.product-image-button'));
  await f.command('Enlarge this piece');const cancel=new f.w.Event('cancel',{cancelable:true});f.dialog().dispatchEvent(cancel);assert.equal(cancel.defaultPrevented,true);assert.equal(f.dialog(),null);assert.equal(f.host.getAttribute('data-storefront-image-open'),'false');assert.equal(f.calls.modal,0);
});
test('Escape from the guide closes the image before dismissing the guide or its current voice session',async t=>{
  const f=await fixture(t,{width:390,height:844});await f.command('Open Daisy Necklace');await f.voice();const opened=await f.say('Enlarge this piece');assert.equal(opened.ok,true,opened.reply);assert.equal(f.calls.starts,1);assert.equal(f.calls.stops,0);assert(f.dialog());
  const next=await f.say('Show the next image');assert.equal(next.ok,true,next.reply);assert.match(f.dialog().querySelector('img').src,/-2\.jpg$/);assert.equal(f.calls.stops,0);assert.equal(f.calls.avatarCreates,1);
  const input=f.root.querySelector('.composer input');input.focus();const escape=new f.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true,composed:true,cancelable:true});input.dispatchEvent(escape);assert.equal(escape.defaultPrevented,true);assert.equal(f.dialog(),null);assert.equal(f.host.getAttribute('data-open'),'true');assert.equal(f.host.getAttribute('data-storefront-image-open'),'false');assert.equal(f.calls.stops,0);assert.equal(f.root.activeElement,input);
  const reopened=await f.say('Enlarge this piece');assert.equal(reopened.ok,true,reopened.reply);const closed=await f.say('Close the image');assert.equal(closed.ok,true,closed.reply);assert.equal(f.calls.stops,0);assert.equal(f.calls.starts,1);assert.equal(f.calls.avatarDestroys,0);assert.equal(f.errors.length,0);
});
test('phone viewer mode follows actual state across typed gallery, resizing, navigation and dismissal without remounting',async t=>{
  const f=await fixture(t,{width:390,height:844});await f.command('Open Daisy Necklace');const host=f.host,stage=f.root.querySelector('.concierge-avatar-stage');await f.command('Enlarge this piece');assert.equal(host.getAttribute('data-storefront-docked'),'false');assert.equal(host.getAttribute('data-storefront-image-open'),'true');
  const next=await f.command('Show image 3');assert.equal(next.ok,true,next.reply);assert.match(f.dialog().querySelector('img').src,/-3\.jpg$/);const dialog=f.dialog();f.resize(1440,900);assert.equal(host.getAttribute('data-storefront-docked'),'true');assert.equal(f.dialog(),dialog);f.resize(390,844);assert.equal(host.getAttribute('data-storefront-docked'),'false');assert.equal(f.dialog(),dialog);assert.equal(host.getAttribute('data-storefront-image-open'),'true');assert.equal(f.root.querySelector('.concierge-avatar-stage'),stage);
  await f.command('Open Maple Earrings');assert.equal(f.dialog(),null);assert.equal(host.getAttribute('data-storefront-image-open'),'false');await f.command('Enlarge this piece');f.w.BritesConcierge.close();assert.equal(host.getAttribute('data-open'),'false');assert.equal(host.getAttribute('data-storefront-image-open'),'false');assert(f.dialog().open,'Closing the guide does not dismiss a separate page image');f.w.BritesConcierge.open({focus:false});assert.equal(host.getAttribute('data-storefront-image-open'),'true');await f.command('Close the image');assert.equal(host.getAttribute('data-storefront-image-open'),'false');assert.equal(f.d.querySelector('brites-concierge'),host);assert.equal(f.calls.avatarCreates,1);assert.equal(f.calls.modal,0);assert.equal(f.errors.length,0);
});
test('parsed layout rules reserve separate desktop and phone regions while keeping image controls and the guide mounted',async t=>{
  const f=await fixture(t,{width:390,height:844});await f.command('Open Daisy Necklace');await f.command('Enlarge this piece');const style=f.d.createElement('style');style.textContent=source['brites-concierge.css'];f.d.head.appendChild(style);
  function rules(sheet){return [...sheet.cssRules].flatMap(rule=>rule.cssRules?[...rule.cssRules].map(child=>({media:rule.conditionText||'',selector:child.selectorText||'',style:child.style})):[]);}
  const shopRules=rules(f.d.styleSheets[0]),guideRules=rules(style.sheet),desktop=shopRules.find(rule=>rule.media==='(min-width:1100px)'&&rule.selector.endsWith('.storefront-dialog')),phone=shopRules.find(rule=>rule.media==='(max-width:1099px)'&&rule.selector.endsWith('.storefront-dialog')),panel=guideRules.find(rule=>rule.media==='(max-width:1099px)'&&rule.selector.endsWith('.panel'));
  assert(desktop&&phone&&panel,'Responsive regions must parse as real CSS rules');assert.match(desktop.style.getPropertyValue('max-width'),/100vw - 440px/);assert.match(phone.style.getPropertyValue('height'),/40dvh/);assert.match(panel.style.getPropertyValue('top'),/40dvh/);assert.equal(panel.style.getPropertyValue('display'),'grid');assert.match(panel.style.getPropertyValue('grid-template-areas'),/avatar captions/);assert.match(panel.style.getPropertyValue('grid-template-areas'),/avatar voice/);assert.match(panel.style.getPropertyValue('grid-template-areas'),/composer composer/);
  assert(f.root.querySelector('.concierge-avatar-stage').isConnected);assert(f.root.querySelector('.avatar-controls').isConnected);assert(f.root.querySelector('.composer input').isConnected);assert(f.dialog().querySelector('.dialog-close').isConnected);assert(f.dialog().querySelector('[data-zoom-direction=next]').isConnected);assert.equal(f.errors.length,0);
});
