'use strict';
// Literal screenshot option labels and the real sandbox host. Native authority
// metadata is synthetic here; the independent native-flow tests drive ASR.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const Bridge=require('../../brites-storefront-bridge.js');
const clone=value=>JSON.parse(JSON.stringify(value));
const id='gid://shopify/Product/4601',handle='lowercase-initial-necklace',title='Lowercase Initial Necklace';
const groups=[{name:'Metal Choice',values:['Sterling Silver','14k Gold Filled','14k Rose Gold Filled','14k Solid Gold']},{name:'Necklace Length',values:['14 inch','16 inch','18 inch','20 inch']},{name:'Engraving',values:['None','Engraved']}];
function page(){return {contextRevision:1,controlVersion:1,pageKind:'product',currentHandle:handle,visiblePieces:[{id,handle,title}],productControls:{handle,productId:id,productTitle:title,productType:'Necklace',quantity:2,variantId:null,optionsOpen:false,openedOption:null,optionGroups:clone(groups),selectedOptions:[],selectionStatus:'choosing'},bagControls:{itemCount:0,lines:[]}};}
function choice(name,value){return {type:'select-option',handle,optionName:name,optionValue:value};}
for(const [text,name,value] of [['select the 16 inch option','Necklace Length','16 inch'],['Select 16 inches','Necklace Length','16 inch'],['Choose sixteen inches','Necklace Length','16 inch'],['choose gold filled','Metal Choice','14k Gold Filled'],['use 14k Gold Filled','Metal Choice','14k Gold Filled'],['Choose 14k Rose Gold Filled','Metal Choice','14k Rose Gold Filled'],['Select the None option','Engraving','None']])test('conversational command selects one literal screenshot choice: '+text,()=>{const p=page(),before=clone(p),r=Bridge.resolve(text,p);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,choice(name,value));assert.deepEqual(p,before);});
for(const text of ['No engraving','no engraving please','Please no engraving','No engraving.','No engraving, please.','No engraving for this necklace.','Without engraving','Unengraved','Select no engraving','Choose no engraving'])test('an explicit no-engraving choice selects published None without cancellation: '+text,()=>{const p=page(),before=clone(p),r=Bridge.resolve(text,p);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.action,choice('Engraving','None'));assert.deepEqual(p,before);});
test('a prior length question delegates checked facts and cannot choose an option',()=>{const p=page(),before=clone(p),r=Bridge.resolve('What length options are there for this necklace?',p);assert.equal(r.delegated,'knowledge');assert.equal(r.targetHandle,handle);assert.equal(r.action,undefined);assert.deepEqual(p,before);assert.deepEqual(Bridge.resolve('select the 16 inch option',p).action,choice('Necklace Length','16 inch'));});
test('a short answer uses the actual opened published group without guessing another choice',()=>{const p=page();p.productControls.optionsOpen=true;p.productControls.openedOption='Necklace Length';assert.deepEqual(Bridge.resolve('16 inches',p).action,choice('Necklace Length','16 inch'));assert.equal(Bridge.resolve('None',p).ok,false);p.productControls.openedOption='Engraving';assert.deepEqual(Bridge.resolve('None',p).action,choice('Engraving','None'));assert.deepEqual(Bridge.resolve('No engraving',p).action,choice('Engraving','None'));});
test('explicit no engraving is independent of which real option menu was last opened',()=>{const p=page();p.productControls.optionsOpen=true;p.productControls.openedOption='Metal Choice';assert.deepEqual(Bridge.resolve('No engraving',p).action,choice('Engraving','None'));});
for(const text of ['No','No thanks','Do not choose no engraving','No engraving if it costs less','No engraving for Hidden Necklace','Without engraving for another piece','"No engraving"','Yesterday no engraving','No engraving then open my cart','No engraving and select Gold Filled'])test('cancellation, unknown targets and conditional words cannot choose None: '+text,()=>{const p=page(),before=clone(p),r=Bridge.resolve(text,p);assert.equal(r.ok,false,text);assert.equal(r.action,undefined);assert.deepEqual(p,before);assert.equal(Bridge.resolvePlan(text,p).ok,false,text);});
for(const change of [p=>p.pageKind='collection',p=>p.currentHandle='different-necklace',p=>p.controlVersion=0,p=>p.productControls.optionGroups.pop(),p=>p.productControls.optionGroups[2].values=['Engraved'],p=>p.productControls.optionGroups.push({name:'Engraving Style',values:['None','Initial']})])test('no engraving requires one actual current published no-engraving choice: '+String(change),()=>{const p=page();change(p);const r=Bridge.resolve('No engraving',p);assert.equal(r.ok,false);assert.equal(r.action,undefined);});
test('unknown lengths, unavailable materials and multiple plain karats remain unresolved',()=>{for(const text of ['Select 17 inches','Choose gold plated','Use 10k Gold Filled','Select -16 inches','Select 16 cm'])assert.equal(Bridge.resolve(text,page()).ok,false,text);const p=page();p.productControls.optionGroups[0].values.push('18k Gold Filled');assert.equal(Bridge.resolve('Choose gold filled',p).ok,false);assert.deepEqual(Bridge.resolve('Use 14k Gold Filled',p).action,choice('Metal Choice','14k Gold Filled'));});
test('duplicate matching length groups still need the shopper to name the exact menu',()=>{const p=page();p.productControls.optionGroups.push({name:'Chain Length',values:['16 inch','18 inch']});assert.equal(Bridge.resolve('Select 16 inches',p).ok,false);assert.deepEqual(Bridge.resolve('Select Necklace Length 16 inches',p).action,choice('Necklace Length','16 inch'));});
for(const length of ['16','sixteen'])test('a conversational one beside a requested '+length+' inch length keeps exactly the two requested choices',()=>{const p=page(),before=clone(p),r=Bridge.resolvePlan('Can you choose the '+length+' inch one in solid gold?',p);assert.equal(r.ok,true,r.reason);assert.deepEqual(r.plan.steps.map(step=>Bridge.resolve(step.text,p).action),[choice('Metal Choice','14k Solid Gold'),choice('Necklace Length','16 inch')]);assert.deepEqual(p,before);assert.equal(r.plan.steps.some(step=>/Engraving/.test(step.text)),false);});
test('one in remains an actual one-inch unit when it does not describe an already stated length',()=>{const p=page();p.productControls.optionGroups[1].values=['1 inch','16 inch'];assert.deepEqual(Bridge.resolve('Choose one in',p).action,choice('Necklace Length','1 inch'));});
for(const text of ['Can you choose 16 inch solid gold for One Necklace?','Can you choose 16 inch solid gold One Necklace?','Can you choose the 16 inch one in solid gold if it is cheaper?','Can you choose the 16 inch one in solid gold or silver?','Can you choose the 16 inch one in solid gold then pay for my order?'])test('conversational one cannot consume an unknown target or additional condition: '+text,()=>assert.equal(Bridge.resolvePlan(text,page()).ok,false));
test('physical questions bind the actual current Initial piece without losing descriptive words',()=>{const p=page();for(const text of ['How long can this necklace be?','How big is the letter pendant?'])assert.equal(Bridge.resolveKnowledgeTarget(text,p).handle,handle,text);for(const text of ['How long can Long Necklace be?','How long can Hidden Necklace be?','How big is the Hidden Letter Pendant?'])assert.equal(Bridge.resolveKnowledgeTarget(text,p).handle,undefined,text);p.visiblePieces.push({id:'gid://shopify/Product/4602',handle:'other-necklace',title:'Other Necklace'});assert.equal(Bridge.resolveKnowledgeTarget('How long can Lowercase Initial Necklace and Other Necklace be?',p).handle,undefined);});
test('a letter component alias requires an actual current Letter or Initial title',()=>{const p=page();p.visiblePieces[0].title=p.productControls.productTitle='Leaf Pendant Necklace';assert.equal(Bridge.resolveKnowledgeTarget('How big is the letter pendant?',p).handle,undefined);p.visiblePieces[0].title=p.productControls.productTitle=title;p.pageKind='collection';assert.equal(Bridge.resolveKnowledgeTarget('How big is the letter pendant?',p).handle,undefined);});
test('only actual option ambiguity carries the face clarification signal',()=>{const p=page();p.productControls.optionGroups.push({name:'Chain Length',values:['16 inch','18 inch']});assert.equal(Bridge.resolve('Select 16 inches',p).needsClarification,true);const metal=page();metal.productControls.optionGroups[0].values.push('18k Gold Filled');assert.equal(Bridge.resolve('Choose gold filled',metal).needsClarification,true);metal.productControls.optionGroups[0].values.push('18k Solid Gold');assert.equal(Bridge.resolvePlan('Choose 16 inch solid gold',metal).needsClarification,true);assert.equal(Bridge.resolvePlan('Choose 16 inch solid gold if it is cheaper',metal).needsClarification,undefined);const engraving=page();engraving.productControls.optionGroups[2].values=['None','Unengraved'];assert.equal(Bridge.resolve('No engraving',engraving).needsClarification,true);engraving.productControls.optionGroups[2].values=['No Engraving','Engraved'];engraving.productControls.optionGroups.push({name:'Engraving Style',values:['No Engraving','Initial']});assert.equal(Bridge.resolve('No engraving',engraving).needsClarification,true);for(const text of ['Select 17 inches','Select Hidden Necklace','No'])assert.equal(Bridge.resolve(text,page()).needsClarification,undefined);});

function product(){const variants=[];for(const [m,metal] of groups[0].values.entries())for(const [l,length] of groups[1].values.entries())for(const engraving of groups[2].values){const numericId=String(460100+variants.length);variants.push({id:'gid://shopify/ProductVariant/'+numericId,numericId,title:[metal,length,engraving].join(' / '),price:44+m*15+l*0+(engraving==='Engraved'?10:0),available:true,availabilityKnown:true,options:[{name:'Metal Choice',value:metal},{name:'Necklace Length',value:length},{name:'Engraving',value:engraving}]});}return {id,handle,title,type:'Necklace',url:'https://britesjewelry.com/products/'+handle,currency:'USD',description:'Published initial necklace with exact metal, necklace length and engraving choices.',options:clone(groups),variantsComplete:true,variants,detailState:'checked',checkedAt:Date.now()};}
async function fixture(t){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',error=>errors.push(error));const dom=new JSDOM(fs.readFileSync(require.resolve('../../concierge-sandbox.html'),'utf8'),{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document,p=product();delete d.body.dataset.catalogueSeed;delete d.body.dataset.inventoryPreload;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=()=>{};w.fetch=async raw=>{const url=new URL(raw,w.location.href);if(url.pathname==='/api/growth/catalogue')return {ok:true,json:async()=>({live:true,checkedAt:Date.now(),products:[clone(p)],pageInfo:{hasNextPage:false,endCursor:null}})};if(url.pathname==='/api/growth/product')return {ok:true,json:async()=>({live:true,checkedAt:Date.now(),product:clone(p)})};if(url.pathname==='/api/growth/storefront-services')return {ok:true,json:async()=>({schema:1,guidance:{},conflicts:[],offers:{items:[]}})};throw Error('Unexpected request '+url.pathname);};w.eval(fs.readFileSync(require.resolve('../../concierge-sandbox.js'),'utf8'));await new Promise(setImmediate);await new Promise(setImmediate);const host=w.BritesSandboxStorefront;assert.equal((await host.execute({type:'open',handle})).ok,true);assert.equal((await host.execute({type:'product-quantity',handle,quantity:2})).ok,true);const calls=[],bridge=Bridge.create({storefront:{...host,execute:async(action,options)=>{calls.push(clone(action));return host.execute(action,options);}}});t.after(()=>{bridge.destroy();w.close();assert.deepEqual(errors,[]);});return {d,p,host,bridge,calls,cart:()=>JSON.parse(w.sessionStorage.getItem('brites-sandbox-cart')||'[]')};}
for(const source of ['typed','native'])test(source+' conversation updates actual three-group controls and adds precisely the chosen USD 59 option',async t=>{const f=await fixture(t);let turn=0;async function command(text){const context=f.bridge.snapshot(),r=f.bridge.resolve(text,context);assert.equal(r.ok,true,r.reason);return f.bridge.execute(r.action,{source,transcript:text,context,requestId:'language46-'+source+'-'+(++turn),...(source==='native'?{inputItemId:'language46-input-'+turn,turnVersion:turn,currentTurn:true}:{})});}const before=clone(f.host.snapshot());assert.equal(f.bridge.resolve('What length options are there for this necklace?').delegated,'knowledge');assert.deepEqual(clone(f.host.snapshot()),before);for(const text of ['select the 16 inch option','choose gold filled'])assert.equal((await command(text)).ok,true,text);let pc=f.host.snapshot().productControls;assert.deepEqual(clone(pc.selectedOptions).sort((a,b)=>a.name.localeCompare(b.name)),[{name:'Metal Choice',value:'14k Gold Filled'},{name:'Necklace Length',value:'16 inch'}]);assert.equal(pc.variantId,null);assert.equal(pc.quantity,2);assert.deepEqual(f.cart(),[]);assert.equal((await command('No engraving')).ok,true);pc=f.host.snapshot().productControls;const chosen=f.p.variants.find(variant=>variant.options.every(option=>({'Metal Choice':'14k Gold Filled','Necklace Length':'16 inch','Engraving':'None'})[option.name]===option.value));assert.equal(pc.variantId,chosen.id);assert.equal(pc.selectedVariant.price,59);assert.equal(f.d.querySelector('#piece-variant').value,chosen.id);assert.equal((await command('add this piece to my cart')).cartChanged,true);assert.equal(f.cart().length,1);assert.equal(f.cart()[0].variantId,chosen.numericId);assert.equal(f.cart()[0].variant,'14k Gold Filled / 16 inch / None');assert.equal(f.cart()[0].quantity,2);assert.equal(f.cart()[0].price,59);assert.equal(f.cart()[0].engravingPreview,undefined);assert.deepEqual(f.calls.map(action=>action.type),['select-option','select-option','select-option','add']);assert.equal(f.d.querySelector('#bag-count').textContent,'2');});
test('a fresh real native turn cannot reuse a no-engraving choice after a manual product change',async t=>{const f=await fixture(t),context=f.bridge.snapshot(),r=f.bridge.resolve('No engraving',context);assert.equal(r.ok,true,r.reason);await f.host.execute({type:'select-option',handle,optionName:'Necklace Length',optionValue:'18 inch'});const out=await f.bridge.execute(r.action,{source:'native',transcript:'No engraving',context,inputItemId:'46-old-no-engraving',turnVersion:1,currentTurn:true});assert.equal(out.ok,false);assert.equal(out.stale,true);assert.equal(f.calls.length,0);assert.equal(f.host.snapshot().productControls.selectedOptions.some(option=>option.name==='Engraving'),false);assert.deepEqual(f.cart(),[]);});
