'use strict';
// Real mounted sandbox, bridge and widget. Public product rows only; no model,
// microphone, production bag or checkout. A fence detects informational fetches.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const source=Object.fromEntries(['concierge-sandbox.html','concierge-sandbox.js','brites-concierge.js','brites-storefront-bridge.js','brites-concierge-shopping-guide.js'].map(file=>[file,fs.readFileSync(require.resolve('../../'+file),'utf8')]));
const clone=value=>JSON.parse(JSON.stringify(value)),settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
const categories=['regular-necklaces','beady-necklaces','stud-earrings','hoop-earrings','charm-only'];
function product(index){const category=categories[index%5],noun=category==='charm-only'?'Charm':category.includes('necklace')?'Necklace':'Earrings',handle='facts-piece-'+index,options=[{name:'Metal Choice',values:['Sterling Silver','14k Gold Filled','14k Solid Gold']},{name:'Chain Length',values:['16 inches','18 inches']}];return {id:'gid://shopify/Product/'+(3900+index),handle,title:'Facts '+index+' '+noun,type:noun,url:'https://britesjewelry.com/products/'+handle,description:'Published listing '+index+'. Sterling silver, 14k gold filled and 14k solid gold. The charm measures 14mm. Chain lengths are 16 and 18 inches.',currency:'USD',image:'https://cdn.shopify.com/'+handle+'.jpg',images:[{url:'https://cdn.shopify.com/'+handle+'.jpg',altText:'Front'},{url:'https://cdn.shopify.com/'+handle+'-back.jpg',altText:'Back'}],storeCategories:[category],options,variantsComplete:true,checkedAt:Date.now(),detailState:'checked',variants:options[0].values.flatMap((metal,m)=>options[1].values.map((length,l)=>({id:'gid://shopify/ProductVariant/'+(39000+index*10+m*2+l),numericId:String(39000+index*10+m*2+l),title:metal+' / '+length,price:50+m*100+l*5,available:true,options:[{name:'Metal Choice',value:metal},{name:'Chain Length',value:length}]})))};}
async function fixture(t,{preferences={},firstProduct=null}={}){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));const dom=new JSDOM(source['concierge-sandbox.html'],{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document,rows=Array.from({length:120},(_,i)=>product(i)),requests=[];let fenced=false;
  if(firstProduct)rows[0]=firstProduct;
  d.body.dataset.inventoryPreload='complete';w.matchMedia=()=>({matches:false,addEventListener(){}});w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=function(){};
  w.fetch=async(raw,init={})=>{const u=new URL(raw,w.location.href);requests.push({url:u,init});if(fenced&&['/api/growth/inventory','/api/growth/catalogue','/api/growth/product','/api/concierge'].includes(u.pathname))throw Error('Informational network fence: '+u.pathname);let body;
    if(u.pathname==='/api/growth/inventory'){const offset=Number(u.searchParams.get('offset')),products=rows.slice(offset,offset+24);body={live:true,checkedAt:Date.now(),products,inventory:{schema:1,total:120,offset,limit:24,loaded:products.length,detailsLoaded:products.length,ready:false,partial:false,expiresAt:Date.now()+300000},pageInfo:{hasNextPage:offset+24<120,nextOffset:offset+24<120?offset+24:null}};}
    else if(u.pathname==='/api/growth/catalogue')body={live:true,checkedAt:Date.now(),products:rows.map(p=>({...p,detailState:'unconfirmed',variants:p.variants.map(v=>({...v,available:false,availabilityKnown:false}))})),pageInfo:{hasNextPage:false,endCursor:null},seed:{schema:1,target:120,minimum:100,loaded:120,complete:true,partial:false,sourcePages:1,categoryCounts:Object.fromEntries(categories.map(c=>[c,24])),unfilledCategories:[]}};
    else if(u.pathname==='/api/growth/product')body={live:true,checkedAt:Date.now(),product:rows.find(p=>p.handle===u.searchParams.get('handle'))};
    else if(u.pathname==='/api/growth/storefront-services')body={schema:1,guidance:{},conflicts:[],offers:{items:[]}};
    else if(u.pathname==='/api/growth/events'||u.pathname==='/api/concierge-voice')body={ok:true,enabled:true,nativeAudio:true,publicDemo:true};
    else if(u.pathname==='/api/concierge')body={live:true,reply:'Synthetic narrative fallback.',products:[],meanings:[],preferences,preserveSelection:true};
    else throw Error('Unexpected '+u.pathname);return {ok:true,json:async()=>clone(body)};
  };
  w.eval(source['brites-concierge-shopping-guide.js']);w.eval(source['brites-storefront-bridge.js']);w.eval(source['concierge-sandbox.js']);await settle();const store=w.BritesSandboxStorefront;await store.preloadInventory();await store.execute({type:'open',handle:rows[0].handle});
  w.BritesConciergeAvatar={create(){return {setState(){},setEmotion(){},setVisible(){},setPaused(){},retry(){},triggerGreeting(){},clearFocus(){},focusProduct(){},setLevel(){},setSpeechSignal(){},clearProduct(){},showProduct(){},cancelPerformance(){},setFloating(){},cue(){},destroy(){}};}};
  w.sessionStorage.setItem('brites-concierge-v1',JSON.stringify({preferences,updatedAt:Date.now()}));const script=d.createElement('script');script.src='/brites-concierge.js';script.dataset.sandbox='true';Object.defineProperty(d,'currentScript',{get:()=>script});w.eval(source['brites-concierge.js']);w.BritesConcierge.open({focus:false});await settle();
  t.after(()=>{w.BritesConcierge?.close();w.close();});const informationalCount=()=>requests.filter(r=>['/api/growth/inventory','/api/growth/catalogue','/api/growth/product','/api/concierge'].includes(r.url.pathname)).length;
  return {w,d,store,rows,requests,errors,informationalCount,fence(){fenced=true;},async ask(text){const result=await w.BritesConcierge.sendShopperCommand(text);await settle();return result;}};
}
async function checkedAnswer(f,text){const count=f.informationalCount(),result=await f.ask(text);assert.equal(result.ok,true,text+': '+(result.reply||result.error));assert.equal(result.cached,true,text+': expected checked local facts');assert.equal(result.verified,true);assert.equal(f.informationalCount(),count,'No informational fetch: '+text);assert.equal(result.productFacts.handle,'facts-piece-0');assert.ok(result.reply.includes(result.productFacts.title),'Identify the exact product in the reply: '+text);assert.equal(result.productFacts.fromCache,true);assert.ok(result.checkedAt>0);assert.deepEqual(Array.from(result.actions),[]);return result;}
test('ordinary polite material, price and availability questions use immediate checked product facts',async t=>{const f=await fixture(t);f.fence();for(const text of ['Could you tell me what materials this piece is available in, and what are its prices?','What materials is this piece available in, and what are its prices?','Can I get this piece in gold filled?']){const answer=await checkedAnswer(f,text);assert.match(answer.reply,/14k Gold Filled/);assert.doesNotMatch(answer.reply,/Synthetic|please name|checked timestamp|Published stock and prices are as of/i);}assert.equal(f.errors.length,0);});
test('an explicitly requested material and length quote the exact alternative without changing the selection',async t=>{const f=await fixture(t);await f.store.execute({type:'select-option',handle:f.rows[0].handle,variantId:f.rows[0].variants[0].id});f.fence();const before=clone(f.store.snapshot()),answer=await checkedAnswer(f,'Could you tell me the price of the 14k Solid Gold version with 18 inches?');assert.match(answer.reply,/14k Solid Gold \/ 18 inches: USD 255\.00/);assert.doesNotMatch(answer.reply,/USD (?:50|55|150|155|250)\.00/);assert.deepEqual(Array.from(answer.requestedFacts.matchingVariantIds),[f.rows[0].variants[5].id]);assert.equal(f.store.snapshot().productControls.variantId,before.productControls.variantId);assert.equal(f.store.snapshot().productControls.itemTotalPrice,50);});
test('a requested material version uses the current published chain choice and discloses it',async t=>{const f=await fixture(t);await f.store.execute({type:'select-option',handle:f.rows[0].handle,variantId:f.rows[0].variants[1].id});f.fence();const answer=await checkedAnswer(f,'How much does the gold filled version cost?');assert.match(answer.reply,/14k Gold Filled \/ 18 inches: USD 155\.00/);assert.doesNotMatch(answer.reply,/USD (?:50|55|150|250|255)\.00/);assert.equal(answer.requestedFacts.options.find(o=>o.name==='Chain Length').source,'current_selection');assert.equal(f.store.snapshot().productControls.variantId,f.rows[0].variants[1].id);});
test('material ranges quote each real material while preserving the active quantity and image',async t=>{const f=await fixture(t);await f.store.execute({type:'select-option',handle:f.rows[0].handle,variantId:f.rows[0].variants[3].id});await f.store.execute({type:'product-quantity',handle:f.rows[0].handle,quantity:3});await f.store.execute({type:'gallery',handle:f.rows[0].handle,index:2});f.fence();const before=clone(f.store.snapshot()),answer=await checkedAnswer(f,'What materials is this made from and what are their prices?');assert.match(answer.reply,/Sterling Silver — USD 50\.00 to USD 55\.00/);assert.match(answer.reply,/14k Gold Filled — USD 150\.00 to USD 155\.00/);assert.match(answer.reply,/14k Solid Gold — USD 250\.00 to USD 255\.00/);assert.equal(f.store.snapshot().productControls.variantId,before.productControls.variantId);assert.equal(f.store.snapshot().productControls.quantity,3);assert.equal(f.store.snapshot().galleryControls.selectedIndex,2);});
test('the current price still quotes the exact variant and quantity subtotal',async t=>{const f=await fixture(t);await f.store.execute({type:'select-option',handle:f.rows[0].handle,variantId:f.rows[0].variants[3].id});await f.store.execute({type:'product-quantity',handle:f.rows[0].handle,quantity:3});f.fence();const answer=await checkedAnswer(f,'What is the price of this piece?');assert.match(answer.reply,/14k Gold Filled \/ 18 inches is USD 155\.00 each; quantity 3 totals USD 465\.00/);assert.equal(answer.productFacts.itemTotalPrice,465);});
test('unpublished metal, karat or length combinations receive a truthful limitation instead of another option price',async t=>{const f=await fixture(t);f.fence();for(const text of ['Can I get this in rose gold?','What is the price of the 18k Solid Gold version?','What is the price of gold filled with 24 inches?']){const answer=await checkedAnswer(f,text);assert.match(answer.reply,/not published/);assert.doesNotMatch(answer.reply,/USD \d/);assert.equal(answer.requestedFacts.matchingVariantIds.length,0);}});
test('the cheapest material question identifies the actual lowest checked variant',async t=>{const f=await fixture(t);f.fence();const answer=await checkedAnswer(f,'Which material is cheapest for this piece?');assert.match(answer.reply,/lowest checked item price is USD 50\.00 for Sterling Silver \/ 16 inches/);assert.doesNotMatch(answer.reply,/USD (?:150|250)\.00/);});
test('mixed literal and generic material names retain every requested price constraint',async t=>{const f=await fixture(t);f.fence();const answer=await checkedAnswer(f,'What are the prices of Sterling Silver and solid gold with 18 inches?');assert.match(answer.reply,/Sterling Silver — USD 55\.00/);assert.match(answer.reply,/14k Solid Gold — USD 255\.00/);assert.doesNotMatch(answer.reply,/Gold Filled|USD (?:50|150|155|250)\.00/);assert.equal(answer.requestedFacts.matchingVariantIds.length,2);const unavailable=await checkedAnswer(f,'What are the prices of Sterling Silver and 18k Solid Gold?');assert.match(unavailable.reply,/not published/);assert.doesNotMatch(unavailable.reply,/USD \d/);});
test('dimensions come only from published measurements, and a charm-size question separates the chain length',async t=>{const f=await fixture(t);f.fence();for(const text of ['Could you tell me the dimensions of this piece?','How big is the charm?','What size is the charm?']){const answer=await checkedAnswer(f,text);assert.match(answer.reply,/charm measures 14mm/);assert(answer.productFacts.dimensions.some(d=>/14mm/.test(d)));if(/charm/.test(text))assert.doesNotMatch(answer.reply,/Chain lengths/);assert.doesNotMatch(answer.reply,/USD \d/);}});
test('missing published dimensions are acknowledged while actual chain choices retain their label',async t=>{
  const f=await fixture(t),fresh={...f.rows[0],description:'Published metal choices only. Sterling silver, 14k gold filled and 14k solid gold.',checkedAt:Date.now()};f.store.presentProducts([fresh]);f.fence();
  const answer=await checkedAnswer(f,'What are the dimensions of this piece?');assert.match(answer.reply,/do not confirm.*measurements/);assert.equal(answer.productFacts.dimensions.length,0);assert.doesNotMatch(answer.reply,/14mm|Published measurements:/);assert.match(answer.reply,/Published size choices: Chain Length: 16 inches, 18 inches/);
  const charm=await checkedAnswer(f,'What size is the charm?');assert.match(charm.reply,/do not confirm the charm[’']s measurements/);assert.equal(charm.productFacts.dimensions.length,0);assert.doesNotMatch(charm.reply,/14mm|16|18|Chain Length/);
});
test('material advice gives useful construction differences with separate general evidence',async t=>{const f=await fixture(t);f.fence();const answer=await checkedAnswer(f,'Compare sterling silver, gold filled and solid gold for everyday wear. Which is better?');assert.match(answer.reply,/Sterling silver.*tarnish/);assert.match(answer.reply,/Gold filled.*base metal/);assert.match(answer.reply,/Solid gold.*throughout/);assert.match(answer.reply,/choose gold filled/);assert.equal(answer.materialGuidance.productSpecificGuarantees,false);assert.equal(answer.materialGuidance.basis,'general_material_information');assert.doesNotMatch(answer.reply,/waterproof|hypoallergenic|never tarnish/i);});
test('nickel and allergy answers acknowledge absent product evidence without safety guarantees',async t=>{const f=await fixture(t);f.fence();for(const text of ['Does this piece contain nickel?','Is sterling silver hypoallergenic?','Is gold filled safe for sensitive skin?']){const answer=await checkedAnswer(f,text);assert.match(answer.reply,/Nickel content and allergy suitability are not confirmed/);assert.match(answer.reply,/cannot guarantee allergy safety/);assert.doesNotMatch(answer.reply,/nickel.free|safe for.*skin|100% hypoallergenic/i);}});
test('care and tarnish questions give bounded care advice and no water or lifetime promise',async t=>{const f=await fixture(t);f.fence();for(const text of ['Does gold filled tarnish?','Can I shower with this piece?','How do I clean this piece?']){const answer=await checkedAnswer(f,text);assert.match(answer.reply,/soft cloth.*chlorine and harsh cleaners/);assert.match(answer.reply,/Waterproof use.*confirmation/);assert.doesNotMatch(answer.reply,/waterproof[.!]|never tarnish|lasts forever|safe to swim/i);}const silver=await checkedAnswer(f,'Does sterling silver tarnish?');assert.match(silver.reply,/Sterling silver can tarnish/);});
test('unknown exact listing names cannot borrow the current product or its quoted prices',async t=>{const f=await fixture(t);f.fence();for(const text of ['What is the price of Unicorn Charm?','Could you tell me what metals Unicorn Necklace comes in?']){const before=f.informationalCount(),answer=await f.ask(text);assert.equal(answer.ok,false);assert.match(answer.error,/name one exact loaded piece/);assert.equal(answer.productFacts,undefined);assert.equal(f.informationalCount(),before);assert.equal(f.store.snapshot().currentHandle,f.rows[0].handle);}});
test('a retained CAD budget is disclosed once when USD prices are quoted, without conversion or filtering',async t=>{const f=await fixture(t,{preferences:{budget:40,budgetCurrency:'CAD'}});await f.store.execute({type:'select-option',handle:f.rows[0].handle,variantId:f.rows[0].variants[3].id});await f.store.execute({type:'product-quantity',handle:f.rows[0].handle,quantity:3});f.fence();const answer=await checkedAnswer(f,'What is the price of this piece?');assert.match(answer.reply,/USD 155\.00.*USD 465\.00/);assert.match(answer.reply,/These prices are USD; your CAD item budget has not been applied/);assert.equal(answer.currencyMismatch,true);assert.equal((answer.reply.match(/CAD/g)||[]).length,1);assert.equal(answer.productFacts.itemTotalPrice,465);});
test('material-only facts do not append a budget warning or quote an unrelated selected price',async t=>{const f=await fixture(t,{preferences:{budget:40,budgetCurrency:'CAD'}});await f.store.execute({type:'select-option',handle:f.rows[0].handle,variantId:f.rows[0].variants[3].id});f.fence();const answer=await checkedAnswer(f,'Could you tell me what materials this piece is available in?');assert.match(answer.reply,/Sterling Silver.*14k Gold Filled.*14k Solid Gold/);assert.doesNotMatch(answer.reply,/USD|CAD|budget/);assert.equal(answer.currencyMismatch,false);});
test('occasion and story questions retain the narrative route instead of being replaced by material facts',async t=>{const f=await fixture(t),before=f.requests.filter(r=>r.url.pathname==='/api/concierge').length;const answer=await f.ask('Why is sterling silver a good choice for a remembrance gift?');assert.equal(answer.reply,'Synthetic narrative fallback.');assert.equal(f.requests.filter(r=>r.url.pathname==='/api/concierge').length,before+1);assert.equal(answer.cached,undefined);assert.equal(f.store.snapshot().currentHandle,f.rows[0].handle);});
test('the published beady-necklace shape selects Gold Filled and 18 inch, preserves explicit Engraving None and quotes quantity2 exactly',async t=>{
  const p=product(0);Object.assign(p,{id:'gid://shopify/Product/3941',handle:'strawberry-charm-beady-necklace',title:'Strawberry Beady Necklace',url:'https://britesjewelry.com/products/strawberry-charm-beady-necklace',description:'Published beady necklace. Choose a metal, chain length and engraving option.',storeCategories:['beady-necklaces'],options:[{name:'Metal Choice',values:['Sterling Silver','14k Gold Filled']},{name:'Chain Length',values:['14"','16"','18"','20"']},{name:'Engraving',values:['None','Add Engraving']}]});
  p.variants=p.options[0].values.flatMap((metal,m)=>p.options[1].values.flatMap((length,l)=>p.options[2].values.map((engraving,e)=>({id:'gid://shopify/ProductVariant/'+(39400+m*100+l*10+e),numericId:String(39400+m*100+l*10+e),title:metal+' / '+length+' / '+engraving,price:(m?90:50)+l*2+e*25,available:true,options:[{name:'Metal Choice',value:metal},{name:'Chain Length',value:length},{name:'Engraving',value:engraving}]}))));
  const f=await fixture(t,{firstProduct:p}),initial=p.variants.find(v=>v.options.every(o=>({ 'Metal Choice':'Sterling Silver','Chain Length':'16"','Engraving':'None'})[o.name]===o.value));assert.equal((await f.store.execute({type:'select-option',handle:p.handle,variantId:initial.id})).ok,true);assert.equal((await f.store.execute({type:'select-option',handle:p.handle,optionName:'Engraving',optionValue:'None'})).ok,true);f.fence();
  const before=f.informationalCount(),r=await f.ask('Select 14k Gold Filled then select 18 inch then set quantity to 2 then tell me the price');assert.equal(r.ok,true,r.reason||r.reply);assert.equal(r.completedActions.length,4);assert.deepEqual(Array.from(r.completedActions,a=>a.type),['select-option','select-option','product-quantity','question']);assert.equal(r.completedActions[1].optionName,'Chain Length');assert.equal(r.completedActions[1].optionValue,'18"');
  const pc=f.store.snapshot().productControls;assert.equal(pc.selectedOptions.find(o=>o.name==='Metal Choice').value,'14k Gold Filled');assert.equal(pc.selectedOptions.find(o=>o.name==='Chain Length').value,'18"');assert.equal(pc.selectedOptions.find(o=>o.name==='Engraving').value,'None');assert.equal(pc.selectedVariant.price,94);assert.equal(pc.quantity,2);assert.equal(pc.itemTotalPrice,188);assert.match(r.reply,/Strawberry Beady Necklace/);assert.match(r.reply,/USD 94\.00 each; quantity 2 totals USD 188\.00/);assert.equal(r.cartChanged,false);assert.deepEqual(JSON.parse(f.w.sessionStorage.getItem('brites-sandbox-cart')||'[]'),[]);assert.equal(f.informationalCount(),before);assert.equal(f.errors.length,0);
});
test('the mounted bag console generates a working exact-title quantity request and both scoped edit-undo forms restore its real line',async t=>{
  const p=product(0);Object.assign(p,{handle:'strawberry-charm-beady-necklace',title:'Strawberry Beady Necklace',url:'https://britesjewelry.com/products/strawberry-charm-beady-necklace'});const f=await fixture(t,{firstProduct:p}),v=p.variants[3],saved={productId:p.id,title:p.title,variantId:v.numericId,variant:v.title,price:v.price,currency:p.currency,quantity:1};f.w.sessionStorage.setItem('brites-sandbox-cart',JSON.stringify([saved]));assert.equal((await f.store.execute({type:'bag'})).ok,true);await settle();
  const command=Array.from(f.d.querySelectorAll('#guide-commands button')).find(b=>b.title==='Set Strawberry Beady Necklace quantity to 2 in my bag');assert.ok(command,'The actual console generated the reported command');const modelBefore=f.requests.filter(r=>r.url.pathname==='/api/concierge').length;assert.equal((await f.ask(command.title)).ok,true);assert.equal(JSON.parse(f.w.sessionStorage.getItem('brites-sandbox-cart'))[0].quantity,2);assert.equal(f.d.querySelector('.bag-quantity input').value,'2');
  for(const text of ['Set Strawberry Beady Necklace quantity to 3 in my bag then undo my last change','Set quantity to 3 for Strawberry Beady Necklace in my bag then undo my last change']){const result=await f.ask(text);assert.equal(result.ok,true,result.reason||result.reply);assert.deepEqual(Array.from(result.completedActions,a=>a.type),['bag-quantity','undo']);const cart=JSON.parse(f.w.sessionStorage.getItem('brites-sandbox-cart'));assert.equal(cart.length,1);assert.equal(cart[0].quantity,2);assert.equal(cart[0].variantId,v.numericId);assert.equal(cart[0].variant,v.title);assert.equal(f.d.querySelector('.bag-quantity input').value,'2');assert.equal(f.store.snapshot().bagControls.lines[0].quantity,2);}
  assert.equal(f.requests.filter(r=>r.url.pathname==='/api/concierge').length,modelBefore);assert.ok(f.requests.filter(r=>r.url.pathname==='/api/growth/product').length>=3,'Quantity edits still check current published stock and price');assert.equal(f.errors.length,0);
});
