'use strict';
// Real mounted widget, bridge and declared host with synthetic exact public
// inventory. No provider, microphone, paid model or real checkout is used.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const Voice=require('../../brites-concierge-voice.js'),Actions=require('../../brites-concierge-voice-actions.js');
const files=Object.fromEntries(['concierge-sandbox.html','concierge-sandbox.js','brites-storefront-bridge.js','brites-concierge.js'].map(name=>[name,fs.readFileSync(require.resolve('../../'+name),'utf8')]));
const clone=value=>JSON.parse(JSON.stringify(value)),settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
function piece(n,title,values,currency='USD'){
  const id=39000+n,rows=values.map((value,k)=>({id:'gid://shopify/ProductVariant/'+(id*10+k+1),numericId:String(id*10+k+1),title:value.metal+' / '+(value.length||'16 inches'),price:value.price,available:value.available!==false,...(value.availabilityKnown===false?{availabilityKnown:false}:{}),options:[{name:'Metal Choice',value:value.metal},{name:'Chain Length',value:value.length||'16 inches'}]}));
  return {id:'gid://shopify/Product/'+id,handle:'material-'+n,title,type:'Necklace',description:'Published exact metal choices and variant prices. Gold choices in promotional text do not establish available gold options.',currency,url:'https://britesjewelry.com/products/material-'+n,image:'https://cdn.shopify.com/material-'+n+'-1.jpg',images:Array.from({length:16},(_,k)=>({url:'https://cdn.shopify.com/material-'+n+'-'+(k+1)+'.jpg',altText:'Published image '+(k+1)})),minPrice:Math.min(...rows.map(v=>v.price)),partsOnly:false,storeCategories:['regular-necklaces'],options:[{name:'Metal Choice',values:[...new Set(values.map(v=>v.metal))]},{name:'Chain Length',values:[...new Set(values.map(v=>v.length||'16 inches'))]}],variantsComplete:true,variants:rows};
}
function catalogue(){
  const products=[
    piece(1,'Focus Silver Necklace',[{metal:'Sterling Silver',price:45}]),
    piece(2,'Focus Budget Necklace',[{metal:'Sterling Silver',price:40},{metal:'14k Gold Filled',price:55},{metal:'14k Gold Filled',price:57,length:'18 inches'}]),
    piece(3,'Focus Mixed Necklace',[{metal:'Sterling Silver',price:45},{metal:'14k Gold Filled',price:95}]),
    piece(4,'Focus Rose Necklace',[{metal:'14k Rose Gold Filled',price:52}]),
    piece(5,'Focus Solid Necklace',[{metal:'14k Solid Gold',price:145}]),
    piece(6,'Focus Ten Necklace',[{metal:'10k Gold Filled',price:58}]),
    piece(7,'Focus Sold Necklace',[{metal:'Sterling Silver',price:45},{metal:'14k Gold Filled',price:55,available:false}]),
    piece(8,'Focus Unknown Necklace',[{metal:'14k Gold Filled',price:54,available:false}]),
    piece(9,'Rose Flower Necklace',[{metal:'Sterling Silver',price:48}]),
    piece(10,'Focus Canadian Necklace',[{metal:'Sterling Silver',price:40},{metal:'14k Gold Filled',price:55}],'CAD'),
    piece(11,'Focus Carat Necklace',[{metal:'18K Gold',price:130}]),
    piece(12,'Focus Plated Necklace',[{metal:'10k Gold Plated',price:35}]),
    piece(13,'Focus Fraction Necklace',[{metal:'14/20 Gold-Filled',price:59}]),
    piece(14,'Focus White Necklace',[{metal:'14k White Gold',price:140}])
  ];
  while(products.length<120)products.push(piece(products.length+1,'Other Inventory '+(products.length+1)+' Necklace',[{metal:'Sterling Silver',price:500}]));
  return products;
}
async function fixture(t,options={}){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));const dom=new JSDOM(files['concierge-sandbox.html'],{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document,products=clone(options.products||catalogue()),checkedAt=Date.now(),requests=[];let config,turn=0;
  w.matchMedia=()=>({matches:false,addEventListener(){}});w.HTMLElement.prototype.scrollIntoView=function(){};
  w.fetch=async(raw,init={})=>{const url=new URL(raw,w.location.href);requests.push({url,body:init.body?JSON.parse(init.body):null});let data;
    if(url.pathname==='/api/growth/inventory'){const offset=Number(url.searchParams.get('offset')||0),rows=clone(products.slice(offset,offset+24)).map(p=>{delete p.minPrice;p.checkedAt=checkedAt;p.detailState=p.variants.some(v=>v.availabilityKnown===false)?'unconfirmed':'checked';return p;});data={live:true,checkedAt,products:rows,inventory:{schema:1,total:products.length,offset},pageInfo:{hasNextPage:offset+24<products.length,nextOffset:offset+24<products.length?offset+24:null}};}
    else if(url.pathname==='/api/growth/catalogue')data={live:true,checkedAt,products:clone(products),seed:{schema:1,target:120,minimum:100,loaded:products.length,complete:false,partial:false,categoryCounts:{'regular-necklaces':products.length},unfilledCategories:['beady-necklaces','stud-earrings','hoop-earrings','charm-only']},pageInfo:{hasNextPage:false,endCursor:null}};
    else if(url.pathname==='/api/growth/product')data={live:true,checkedAt:Date.now(),product:clone(products.find(p=>p.handle===url.searchParams.get('handle')))};
    else if(url.pathname==='/api/growth/storefront-services')data={schema:1,guidance:{},conflicts:[],offers:{items:[],status:'published_not_checkout_validated'}};
    else if(url.pathname==='/api/concierge-voice')data={enabled:true,nativeAudio:true,publicDemo:true};
    else if(url.pathname==='/api/growth/events')data={ok:true};
    else if(url.pathname==='/api/concierge')data={live:true,reply:'Synthetic model fallback.',preferences:{},products:[],meanings:[],preserveSelection:true};
    else throw Error('Unexpected synthetic route '+url.pathname);
    return {ok:true,json:async()=>clone(data)};
  };
  w.BritesConciergeAvatar={create(){return {setState(){},setEmotion(){},setVisible(){},setPaused(){},triggerGreeting(){},clearFocus(){},focusProduct(){},clearProduct(){},setLevel(){},setSpeechSignal(){},showProduct(){},cancelPerformance(){},setFloating(){},cue(){},destroy(){}};}};
  w.BritesConciergeVoiceActions=Actions;w.BritesConciergeVoice={...Voice,create(value){config=value;return {state:'listening',outputMeterState:'ready',playbackBlocked:false,start:async()=>true,stop:async()=>{},dispose:async()=>{},updateContext(){}};}};
  w.eval(files['brites-storefront-bridge.js']);w.eval(files['concierge-sandbox.js']);await w.BritesSandboxStorefront.preloadInventory();await settle();
  const script=d.createElement('script');script.src='/brites-concierge.js';script.dataset.sandbox='true';Object.defineProperty(d,'currentScript',{get:()=>script});w.eval(files['brites-concierge.js']);const root=d.querySelector('brites-concierge').shadowRoot;w.BritesConcierge.open();await settle();
  async function activate(){w.BritesConcierge.open();[...root.querySelectorAll('button')].find(b=>b.textContent.trim()==='Talk to me').click();await settle();root.querySelector('script[src$="brites-concierge-voice.js"]')?.dispatchEvent(new w.Event('load'));await settle();assert.ok(config);}
  async function nativeSearch(text){if(!config)await activate();const itemId='material39-'+(++turn);config.onSpeechStarted({itemId,turnVersion:turn});config.onTranscript({role:'user',itemId,turnVersion:turn,currentTurn:true,text,final:true});return config.onTool({message:text},{name:'find_jewellery',inputItemId:itemId,turnVersion:turn,currentTurn:true,responseId:'material39-response-'+turn});}
  t.after(()=>{w.BritesConcierge.close();w.close();});return {w,d,root,products,checkedAt,requests,errors,nativeSearch,store:w.BritesSandboxStorefront,send:text=>w.BritesConcierge.sendShopperCommand(text)};
}
const handles=result=>clone(result.products.map(p=>p.handle));
const networkReads=h=>h.requests.filter(r=>['/api/growth/product','/api/growth/catalogue'].includes(r.url.pathname)||r.url.pathname==='/api/concierge'&&r.body?.message).length;
async function search(h,query){const before=networkReads(h),result=await h.store.execute({type:'search',query,filter:'necklaces'});assert.equal(result.ok,true,result.message);assert.equal(networkReads(h),before,'checked material search must use loaded exact facts');return result;}

test('a gold budget must be satisfied by the same available gold option, never the cheaper silver option',async t=>{const h=await fixture(t),r=await search(h,'Focus gold necklaces under USD 60');assert.deepEqual(handles(r),['material-2','material-6','material-12','material-13']);assert.ok(!handles(r).includes('material-1'));assert.ok(!handles(r).includes('material-3'));assert.ok(!handles(r).includes('material-7'));assert.ok(!handles(r).includes('material-8'));const budget=r.products.find(p=>p.handle==='material-2');assert.equal(budget.minPrice,55);assert.equal(budget.matchingPriceRange.min,55);assert.equal(budget.matchingPriceRange.max,57);assert.equal(budget.matchingVariantIds.length,2);assert.equal(budget.variants.length,3,'complete native choices are retained');const card=h.d.querySelector('[data-product-handle="material-2"]');assert.match(card.textContent,/55\.00/);assert.doesNotMatch(card.textContent,/40\.00/);assert.match(card.textContent,/gold options/i);});
for(const [query,expected] of [
  ['Focus 14k gold filled necklaces under USD 60',['material-2','material-13']],
  ['Focus 10k gold filled necklaces under USD 60',['material-6']],
  ['Focus 14k rose gold filled necklaces under USD 60',['material-4']],
  ['Focus solid gold necklaces under USD 160',['material-5']],
  ['Focus 14k solid gold necklaces under USD 160',['material-5']],
  ['Focus 18k solid gold necklaces under USD 160',[]],
  ['Focus 14k white gold necklaces under USD 160',['material-14']],
  ['Focus sterling silver necklaces under USD 60',['material-1','material-2','material-3','material-7']]
])test('literal published material and fineness search: '+query,async t=>{const h=await fixture(t),r=await search(h,query);assert.deepEqual(handles(r),expected);for(const p of r.products)assert.equal(p.matchingPriceRange.currency,'USD');assert.equal(h.errors.length,0);});
test('karat-only published gold stays searchable but never establishes solid construction in the legacy fallback',async t=>{
  const h=await fixture(t),before=clone((await h.store.readProduct('material-11')).product),plain=await search(h,'Focus 18k gold necklaces under USD 160');
  assert.deepEqual(handles(plain),['material-11']);assert.equal(plain.products[0].matchingPriceRange.min,130);assert.deepEqual(clone(plain.products[0].matchingVariantIds),before.variants.map(v=>v.id));
  for(const query of ['Focus 18k solid gold necklaces under USD 160','Focus solid white gold necklaces under USD 160'])assert.deepEqual(handles(await search(h,query)),[],query);
  assert.deepEqual(clone((await h.store.readProduct('material-11')).product),before,'A stricter search cannot erase or relabel the unknown construction option');assert.equal(h.errors.length,0);
});
test('explicit 18k solid construction passes fallback search only on its available same-currency budget-matching variant',async t=>{
  const products=catalogue(),p=products.find(row=>row.handle==='material-11');p.options[0].values=['18K Solid Gold'];p.variants[0].title='18K Solid Gold / 16 inches';p.variants[0].options[0].value='18K Solid Gold';
  const h=await fixture(t,{products}),positive=await search(h,'Focus 18k solid gold necklaces under USD 160');assert.deepEqual(handles(positive),['material-11']);assert.deepEqual(clone(positive.products[0].options),p.options);assert.deepEqual(clone(positive.products[0].variants),p.variants);assert.equal(positive.products[0].matchingPriceRange.min,130);
  assert.deepEqual(handles(await search(h,'Focus solid gold necklaces under USD 160')),['material-5','material-11']);
  assert.deepEqual(handles(await search(h,'Focus 18k solid gold necklaces under USD 129')),[]);assert.deepEqual(handles(await search(h,'Focus 18k solid gold necklaces under CAD 160')),[]);assert.equal(h.errors.length,0);
});
test('an unavailable explicit 18k solid variant cannot borrow a cheap available silver variant in the fallback',async t=>{
  const products=catalogue(),p=piece(11,'Focus Carat Necklace',[{metal:'Sterling Silver',price:40},{metal:'18K Solid Gold',price:130,available:false}]);products[10]=p;
  const h=await fixture(t,{products}),result=await search(h,'Focus 18k solid gold necklaces under USD 160');assert.deepEqual(handles(result),[]);const exact=(await h.store.readProduct(p.handle)).product;assert.deepEqual(clone(exact.options),p.options);assert.deepEqual(clone(exact.variants),p.variants);assert.equal(h.errors.length,0);
});
test('standalone Rose remains a listing motif rather than an implied rose-gold choice',async t=>{const h=await fixture(t),r=await search(h,'Rose Flower necklaces under USD 60');assert.deepEqual(handles(r),['material-9']);assert.equal(r.products[0].matchingPriceRange.min,48);});
test('item-budget currency matches exact published currency without conversion',async t=>{const h=await fixture(t),r=await search(h,'Focus 14k gold filled necklaces under CAD 60');assert.deepEqual(handles(r),['material-10']);assert.equal(r.products[0].matchingPriceRange.currency,'CAD');assert.equal(r.products[0].minPrice,55);const conflict=await search(h,'Focus gold necklaces under CAD 60 over USD 20');assert.deepEqual(handles(conflict),[]);});
test('both price bounds apply to one available material choice',async t=>{const h=await fixture(t),r=await search(h,'Focus 14k gold filled necklaces at least USD 56 under USD 58');assert.deepEqual(handles(r),['material-2']);assert.equal(r.products[0].matchingPriceRange.min,57);assert.equal(r.products[0].matchingPriceRange.max,57);assert.equal(r.products[0].matchingVariantIds.length,1);});
test('native cache discovery retains complete identity while quoting only qualifying material prices',async t=>{const h=await fixture(t),before=networkReads(h),r=await h.nativeSearch('Find Focus 14k gold filled necklaces under USD 60');assert.equal(r.cached,true,r.error);assert.equal(r.verified,true);assert.deepEqual(handles(r),['material-2','material-13']);assert.equal(r.searchCriteria.material,'14k gold filled');assert.equal(r.searchCriteria.maxPrice,60);assert.equal(r.products[0].matchingPriceRange.min,55);assert.equal(r.products[0].matchingPriceRange.max,57);assert.equal(networkReads(h),before);assert.equal((await h.store.readProduct('material-2')).product.images.length,16);});
test('typed cache discovery binds the same metal option and budget before presenting visible matches',async t=>{const h=await fixture(t),before=networkReads(h),r=await h.send('Show Focus 14k gold filled necklaces under USD 60');assert.equal(r.ok,true,r.error);assert.deepEqual(handles(r),['material-2','material-13']);assert.equal(networkReads(h),before);assert.deepEqual(clone(h.store.snapshot().visiblePieces.map(p=>p.handle)),['material-2','material-13']);assert.match(h.d.querySelector('[data-product-handle="material-2"]').textContent,/55\.00/);});
test('native followups retain a confirmed item cap but explicit material and price changes override it',async t=>{const h=await fixture(t);let r=await h.nativeSearch('Find Focus sterling silver necklaces under USD 60');assert.equal(r.searchCriteria.material,'sterling silver');r=await h.nativeSearch('Recommend Focus 14k gold filled necklaces');assert.deepEqual(handles(r),['material-2','material-13']);assert.equal(r.searchCriteria.maxPrice,60);assert.equal(r.searchCriteria.material,'14k gold filled');r=await h.nativeSearch('Recommend Focus 14k gold filled necklaces under USD 100 instead');assert.equal(r.searchCriteria.maxPrice,100);assert.deepEqual(handles(r),['material-2','material-13','material-3']);r=await h.nativeSearch('Suggest Focus sterling silver necklaces');assert.equal(r.searchCriteria.material,'sterling silver');assert.equal(r.searchCriteria.maxPrice,100);assert.ok(handles(r).includes('material-1'));});
test('a cached recommendation cannot adopt a foreign currency for a prior confirmed item budget',async t=>{const h=await fixture(t);await h.nativeSearch('Find Focus 14k gold filled necklaces under USD 60');const r=await h.nativeSearch('Recommend Focus gold filled necklaces under CAD 60');assert.deepEqual(handles(r),['material-10']);assert.equal(r.searchCriteria.currency,'CAD');assert.equal(r.products[0].matchingPriceRange.currency,'CAD');const follow=await h.nativeSearch('Suggest Focus gold filled necklaces');assert.deepEqual(handles(follow),['material-10']);assert.equal(follow.searchCriteria.currency,'CAD');assert.equal(follow.searchCriteria.maxPrice,60);});
test('an unrepresented requested budget currency reports an exact empty checked selection without FX',async t=>{const h=await fixture(t),before=networkReads(h),r=await h.nativeSearch('Find Focus gold filled necklaces under EUR 60');assert.equal(r.cached,true,r.error);assert.equal(r.ok,true);assert.deepEqual(handles(r),[]);assert.equal(r.currencyMismatch,true);assert.match(r.reply,/not converted|another currency/);assert.equal(networkReads(h),before);});
test('unconfirmed stock cannot become a matching cached option even when its published price fits',async t=>{const products=catalogue();products[7].variants[0].available=true;products[7].variants[0].availabilityKnown=false;const h=await fixture(t,{products}),before=networkReads(h),r=await h.nativeSearch('Find Focus 14k gold filled necklaces under USD 60');assert.equal(r.cached,true,r.error);assert.deepEqual(handles(r),['material-2','material-13']);assert.equal(networkReads(h),before);assert.equal(h.store.inventoryStatus().ready,false);assert.equal(h.store.inventoryStatus().partial,true);});
test('presenting a bounded spoken projection preserves full native images, choices and checked search metadata',async t=>{const h=await fixture(t),full=(await h.store.readProduct('material-2')).product,stripped={...clone(full),variants:clone(full.variants.slice(0,1)),variantsComplete:false};delete stripped.images;delete stripped.options;delete stripped.image;const r=h.store.presentProducts([stripped],{query:'Show a nice gift for my friend',searchQuery:'Focus 14k gold filled necklaces under USD 60',filter:'necklaces',sort:'price-desc',checkedAt:h.checkedAt});assert.equal(r.ok,true,r.message);assert.equal(r.checkedAt,h.checkedAt);assert.equal(r.searchCriteria.material,'14k gold filled');assert.equal(r.searchCriteria.maxPrice,60);assert.equal(r.products[0].minPrice,55);const cached=await h.store.readProduct('material-2');assert.equal(cached.product.images.length,16);assert.equal(cached.product.variants.length,3);assert.equal(cached.product.options.length,2);assert.equal(cached.product.variantsComplete,true);const page=h.store.snapshot();assert.equal(page.search,'Focus 14k gold filled necklaces under USD 60');assert.equal(page.sort,'price-desc');assert.equal(page.filter,'necklaces');await h.store.execute({type:'open',handle:'material-2'});assert.equal(h.store.snapshot().galleryControls.imageCount,16);assert.equal((await h.store.execute({type:'gallery',handle:'material-2',index:16})).ok,true);assert.equal(h.store.snapshot().galleryControls.selectedIndex,16);});
