'use strict';
// Actual widget and intent bridge with synthetic storefront/native callbacks.
// These tests do not certify physical microphone, GPU, live checkout or offers.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const widget=fs.readFileSync(require.resolve('../../brites-concierge.js'),'utf8');
const bridge=fs.readFileSync(require.resolve('../../brites-storefront-bridge.js'),'utf8');
const clone=value=>JSON.parse(JSON.stringify(value));
const settle=async()=>{await new Promise(resolve=>setImmediate(resolve));await new Promise(resolve=>setImmediate(resolve));};
const piece={id:'gid://shopify/Product/301',handle:'compass-necklace',title:'Compass Necklace',type:'Necklace',url:'https://britesjewelry.com/products/compass-necklace',currency:'USD',minPrice:55,variantsComplete:true,suggestedVariantId:'gid://shopify/ProductVariant/3011',variants:[{id:'gid://shopify/ProductVariant/3011',numericId:'3011',title:'Sterling Silver / 18 inch',price:55,available:true,options:[{name:'Metal',value:'Sterling Silver'},{name:'Length',value:'18 inch'}]}]};
const bunny={...clone(piece),id:'gid://shopify/Product/302',handle:'bunny-necklace',url:'https://britesjewelry.com/products/bunny-necklace',title:'Bunny Necklace',minPrice:58,variants:piece.variants.map(v=>({...clone(v),id:'gid://shopify/ProductVariant/3021',numericId:'3021',price:58}))};
const services={schema:1,checkedAt:1791340000000,guidance:{source:{kind:'merchant_statement',title:'Brites studio guidance',statedAt:'2026-10-07'},production:{summary:'The studio states production takes 2–3 days.',needsConfirmation:true},sourcing:{summary:'The studio states its materials are ethically sourced from the United States.',needsConfirmation:true},shipping:{summary:'Shipping choices and current charges are shown at checkout.'},gifts:{summary:'Gift packaging, gift notes and gift wrapping are offered.'},customization:{summary:'The studio can review engraving, custom designs and a design you provide.'}},offers:{status:'published_not_checkout_validated',checkedAt:1791340000000,items:[{kind:'code',code:'DEMO10',percent:10,summary:'The synthetic shop advertises DEMO10 for 10% off.',source:{title:'Published test shop offer',url:'https://britesjewelry.com/'},newsletterSignupRequired:true}]},conflicts:[{topic:'production',merchantSummary:'The studio states 2–3 days.',publishedSummary:'A synthetic published policy lists a different standard processing range.',source:{title:'Published shipping policy',url:'https://britesjewelry.com/policies/shipping-policy'}}],policyLinks:[{title:'Shipping policy',url:'https://britesjewelry.com/policies/shipping-policy'}]};

function fixture(t,options={}){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',error=>errors.push(error));
  const dom=new JSDOM('<!doctype html><body><a id="first" href="/concierge-sandbox.html?product=compass-necklace">Compass</a><a id="second" href="/concierge-sandbox.html?product=bunny-necklace">Bunny</a></body>',{url:'https://growth-sandbox.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});
  const w=dom.window,d=w.document,script=d.createElement('script');Object.defineProperty(w,'innerWidth',{configurable:true,writable:true,value:options.width===undefined?1024:options.width});script.src='/brites-concierge.js';script.dataset.sandbox=options.live?'false':'true';Object.defineProperty(d,'currentScript',{get:()=>script});let hidden=false,config,turn=0;
  Object.defineProperty(d,'hidden',{get:()=>hidden});w.HTMLElement.prototype.scrollIntoView=function(){};
  const calls={network:[],controls:[],contexts:[],states:[],focus:[],clears:0,presented:[],signals:[],starts:0,stops:0};
  let page={contextRevision:1,pageKind:'collection',currentHandle:'',focusedHandle:piece.handle,visiblePieces:[piece,bunny].map(p=>({id:p.id,handle:p.handle,title:p.title})),search:'',sort:'featured',filter:'all',loading:false,activeSection:'catalogue'};
  page.controlVersion=1;page.loadedPieces=[piece,bunny].map(p=>({id:p.id,handle:p.handle,title:p.title}));page.productControls={handle:piece.handle,productId:piece.id,variantId:piece.variants[0].id,quantity:options.quantity||1,optionsOpen:false,openedOption:null,optionGroups:[{name:'Metal',values:['Sterling Silver']},{name:'Length',values:['18 inch']}],selectedOptions:clone(piece.variants[0].options),reviewReady:false};page.bagControls={lines:[{lineId:'3011:fixture-line',productId:piece.id,variantId:piece.variants[0].id,quantity:1,title:piece.title,variant:piece.variants[0].title}],itemCount:1};page.checkoutControls={step:'review',shipping:'standard',acknowledged:false,complete:false};
  let output=null,liveProducts=[clone(piece),clone(bunny)];
  w.BritesSandboxStorefront={snapshot:()=>clone(page),async execute(action,opts){calls.controls.push({action:clone(action),signal:opts?.signal});if(options.controlWait)await options.controlWait(action,opts);if(opts?.signal?.aborted)return {ok:false,reason:'Cancelled'};if(action.type==='review-add'&&options.hookReview){const prepared=await w.BritesConciergeShopifyControls.reviewAdd({product:clone(piece),variantId:action.variantId,quantity:page.productControls.quantity,signal:opts.signal,requestId:opts.requestId,reviewAuthority:opts.reviewAuthority});return {...prepared,message:prepared.ok?'Review the exact choices and quantity before confirming.':prepared.reason};}page={...page,contextRevision:page.contextRevision+1};if(action.type==='product-quantity')page.productControls.quantity=action.quantity;if(action.type==='options'){page.productControls.optionsOpen=true;page.productControls.openedOption=action.optionName||null;}if(action.type==='select-option')page.productControls.selectedOptions=page.productControls.selectedOptions.map(o=>o.name===action.optionName?{name:o.name,value:action.optionValue}:o);if(action.type==='gift-preferences')page.savedLocalGift=clone(action);if(action.type==='checkout-step'){page.pageKind='checkout';page.checkoutControls.step=action.step;}if(action.type==='checkout-option')page.checkoutControls.shipping=action.value;if(action.type==='open'||action.type==='highlight'||action.type==='zoom'){page.pageKind='product';page.currentHandle=action.handle||page.currentHandle;page.activeSection=action.section||'image';}if(action.type==='sort')page.sort=action.sort;if(action.type==='search')page.search=action.query;if(action.type==='filter')page.filter=action.filter;if(action.type==='bag'||action.type==='checkout')page.pageKind=action.type;d.dispatchEvent(new w.CustomEvent('brites-storefront:context'));const products=['open','highlight','zoom'].includes(action.type)?liveProducts.filter(p=>p.handle===action.handle):['sort','search','filter'].includes(action.type)?liveProducts:undefined;return {ok:true,cartChanged:['bag-quantity','bag-remove'].includes(action.type),checkedAt:1791340000000,live:options.staleProducts?false:!!products,products,reply:'The test shop is showing your requested '+action.type+'.',snapshot:clone(page)};},presentProducts(products,meta){calls.presented.push({products:clone(products),meta});page={...page,contextRevision:page.contextRevision+1,visiblePieces:products.map(p=>({id:p.id,handle:p.handle,title:p.title}))};d.dispatchEvent(new w.CustomEvent('brites-storefront:context'));return true;}};
  w.BritesSandboxStorefront.capabilities={controlVersion:1,mode:options.live?'shopify':'sandbox',actions:['search','sort','filter','open','highlight','zoom','scroll','bag','checkout','gift','customize','options','select-option','product-quantity','review-add','bag-quantity','bag-remove','gift-preferences','checkout-step','checkout-option','checkout-complete'],reviewBeforeAdd:true,finalOrder:false,checkoutMode:options.live?'handoff':'simulation-only',notesMode:'local-session'};if(options.live)w.BritesStorefrontAdapter=w.BritesSandboxStorefront;
  w.BritesConciergeAvatar={create(){return {setState:v=>calls.states.push(v),setEmotion(){},setVisible(){},setPaused(){},retry(){},triggerGreeting(){},clearFocus(){calls.clears++;},focusProduct:v=>calls.focus.push(clone(v)),setLevel(){},setSpeechSignal:v=>calls.signals.push(v?clone(v):null),clearProduct(){},showProduct(){},cancelPerformance(){},setFloating(){},cue(){}};}};
  const client={state:'listening',outputMeterState:'ready',playbackBlocked:false,start:async()=>{calls.starts++;return true;},stop:async()=>{calls.stops++;output=null;},dispose:async()=>{},updateContext:v=>calls.contexts.push(clone(v)),get currentOutput(){return output;}};
  w.BritesConciergeVoice={create(value){config=value;return client;}};
  let realCart=[];w.fetch=async(url,init={})=>{const body=init.body?JSON.parse(init.body):{};calls.network.push({url:String(url),body,signal:init.signal});if(String(url).endsWith('/cart/add.js')){realCart=body.items.map(i=>({variant_id:i.id,quantity:i.quantity,properties:i.properties}));return {ok:true,json:async()=>({items:realCart})};}if(String(url).endsWith('/cart.js'))return {ok:true,json:async()=>({currency:'USD',items:clone(realCart)})};if(/\/products\/[^/]+\.js$/.test(String(url)))return {ok:true,json:async()=>({variants:piece.variants.map(v=>({id:Number(v.numericId),price:v.price*100,available:v.available}))})};if(String(url).includes('/api/growth/storefront-services')){if(options.serviceWait)await options.serviceWait(init);return {ok:options.serviceOk!==false,json:async()=>clone(options.services||services)};}if(String(url).includes('/api/growth/product?'))return {ok:true,json:async()=>({live:true,product:clone(liveProducts.find(p=>String(url).endsWith(p.handle))||piece)})};return {ok:true,json:async()=>({live:true,reply:'A meaningful piece for your request.',preferences:{},products:clone(liveProducts),meanings:[],policyLinks:[]})};};
  if(options.noStorefront)delete w.BritesSandboxStorefront;if(options.restoredOpen||options.restoredProducts)w.sessionStorage.setItem('brites-concierge-v1',JSON.stringify({updatedAt:Date.now(),open:true,history:[],preferences:{},products:options.restoredProducts||[],meanings:[],policyLinks:[],productHandles:[],selectedVariants:options.restoredVariants||{},uncertainVariants:[]}));
  w.eval(bridge);w.eval(widget);const root=d.querySelector('brites-concierge').shadowRoot;
  function button(label){return [...root.querySelectorAll('button')].find(n=>n.textContent.trim()===label||n.getAttribute('aria-label')===label);}
  function submit(text){root.querySelector('.composer input').value=text;root.querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}
  async function open(){w.BritesConcierge.open();button('Type instead').click();await settle();}
  async function voice(){w.BritesConcierge.open();button('Talk to me').click();await settle();root.querySelector('script[src$="brites-concierge-voice.js"]')?.dispatchEvent(new w.Event('load'));await settle();}
  function speak(text){const itemId='input-'+(++turn);config.onSpeechStarted({itemId,turnVersion:turn});config.onTranscript({role:'user',itemId,turnVersion:turn,currentTurn:true,text,final:true});return {name:'control_storefront',inputItemId:itemId,turnVersion:turn,currentTurn:true,responseId:'response-'+turn};}
  const h={w,d,root,calls,errors,button,submit,open,voice,speak,get config(){return config;},get page(){return page;},setPage(next){page={...page,...clone(next)};d.dispatchEvent(new w.CustomEvent('brites-storefront:context'));},setProducts(value){liveProducts=clone(value);},setOutput(value){output=value;},resize(width){w.innerWidth=width;w.dispatchEvent(new w.Event('resize'));},hide(){hidden=true;d.dispatchEvent(new w.Event('visibilitychange'));}};
  t.after(()=>{try{w.BritesConcierge.close();}catch{}w.close();});return h;
}

test('an exact checked title below the viewport opens through loadedPieces without catalogue inference',async t=>{const h=fixture(t);await h.open();h.setPage({visiblePieces:[{id:piece.id,handle:piece.handle,title:piece.title}]});h.submit('Open Bunny Necklace');await settle();assert.equal(h.calls.controls.length,1);assert.equal(h.calls.controls[0].action.handle,bunny.handle);assert.equal(h.calls.network.filter(r=>r.body.message).length,0);});
test('Set quantity stays on the current product instead of querying motif set',async t=>{const h=fixture(t);await h.open();h.setPage({pageKind:'product',currentHandle:piece.handle});h.submit('Set quantity to 2');await settle();assert.deepEqual(h.calls.controls[0].action,{type:'product-quantity',handle:piece.handle,quantity:2});assert.equal(h.page.pageKind,'product');assert.equal(h.calls.network.filter(r=>r.body.message).length,0);assert.equal(h.page.productControls.quantity,2);});
test('literal options and material setter act locally without service/recommendation fallback',async t=>{const h=fixture(t);await h.open();h.setPage({pageKind:'product',currentHandle:piece.handle});for(const text of ['Open the metal dropdown','Select Sterling Silver']){h.submit(text);await settle();}assert.deepEqual(h.calls.controls.map(c=>c.action.type),['options','select-option']);assert.equal(h.page.productControls.optionsOpen,true);assert.equal(h.page.productControls.openedOption,'Metal');assert.equal(h.calls.network.filter(r=>r.body.message||r.url.includes('storefront-services')).length,0);});
test('gift note stays exact in local host session but is excluded from persisted conversational history and native context',async t=>{const h=fixture(t);await h.open();h.submit('Set gift note to Happy Birthday, private fixture recipient!');await settle();assert.equal(h.page.savedLocalGift.giftNote,'Happy Birthday, private fixture recipient!');assert.equal(h.calls.network.filter(r=>r.body.message||r.url.includes('storefront-services')).length,0);const saved=JSON.parse(h.w.sessionStorage.getItem('brites-concierge-v1'));assert.doesNotMatch(JSON.stringify(saved.history),/private fixture recipient/);assert.doesNotMatch(JSON.stringify(h.w.BritesConciergeShopifyControls),/private fixture/);});
test('test shipping setter and stage transition do not read policies or claim actual service selection',async t=>{const h=fixture(t);await h.open();h.setPage({pageKind:'checkout'});for(const text of ['Open checkout shipping','Choose express shipping']){h.submit(text);await settle();}assert.deepEqual(h.calls.controls.map(c=>c.action.type),['checkout-step','checkout-option']);assert.equal(h.page.checkoutControls.shipping,'express');assert.equal(h.calls.network.filter(r=>r.body.message||r.url.includes('storefront-services')).length,0);});
test('actual finalized native options/quantity callbacks preserve output playback and report only checked bag mutations',async t=>{const h=fixture(t);await h.voice();h.setPage({pageKind:'product',currentHandle:piece.handle});let turn=h.speak('Set quantity to 2');const result=await h.config.onTool({type:'product-quantity',handle:piece.handle,quantity:2},turn);assert.equal(result.ok,true);assert.equal(result.cartChanged,false);assert.equal(result.publicContext.productControls.quantity,2);turn=h.speak('Set bag quantity to 3');const changed=await h.config.onTool({type:'bag-quantity',lineId:'3011:fixture-line',quantity:3},turn);assert.equal(changed.ok,true);assert.equal(changed.cartChanged,true);assert.equal(h.calls.stops,0);});
test('production prepare-only review hook rejects guessed request IDs/tokens before live reads',async t=>{const h=fixture(t,{live:true,hookReview:true});await h.open();const count=h.calls.network.length,r=await h.w.BritesConciergeShopifyControls.reviewAdd({product:clone(piece),variantId:piece.variants[0].id,quantity:1,requestId:'typed-1',reviewAuthority:{}});assert.equal(r.ok,false);assert.equal(h.calls.network.length,count);assert.equal(h.root.querySelector('.review'),null);});
test('declared production adapter prepares exact bounded quantity review; only separate shopper click performs checked Ajax add',async t=>{const h=fixture(t,{live:true,hookReview:true,quantity:3});await h.open();h.setPage({pageKind:'product',currentHandle:piece.handle});h.submit('Add this piece to my bag');await settle();assert.equal(h.calls.controls.at(-1)?.action.type,'review-add');assert.match(h.root.querySelector('.review')?.textContent||'',/quantity 3/);assert.equal(h.calls.network.filter(r=>r.url.endsWith('/cart/add.js')).length,0);h.button('Confirm add to bag').click();await settle();await settle();const write=h.calls.network.find(r=>r.url.endsWith('/cart/add.js'));assert.equal(write.body.items[0].quantity,3);assert.equal(h.calls.network.filter(r=>r.url.endsWith('/cart/add.js')).length,1);assert.match(h.root.querySelector('.caption-text').textContent,/Added to your bag/);assert.equal(h.errors.length,0);});
test('new malformed/denied controls remain handled and cannot escape to recommendation inference',async t=>{const h=fixture(t);await h.open();h.setPage({pageKind:'product',currentHandle:piece.handle});for(const text of ['Set quantity to 2.5','Do not select Sterling Silver','Open the metal dropdown for Hidden Pendant']){h.submit(text);await settle();}assert.equal(h.calls.controls.length,0);assert.equal(h.calls.network.filter(r=>r.body.message).length,0);assert.equal(h.page.pageKind,'product');});

function manyOptions(count){const product=clone(piece);product.variants=Array.from({length:count},(_,index)=>({id:'gid://shopify/ProductVariant/'+(10001+index),numericId:String(10001+index),title:'Sterling Silver / '+(index+1)+' inch',price:55+index,available:true,options:[{name:'Metal',value:'Sterling Silver'},{name:'Length',value:(index+1)+' inch'}]}));product.suggestedVariantId=product.variants.at(-1)?.id;return product;}
function savedProducts(h){return JSON.parse(h.w.sessionStorage.getItem('brites-concierge-v1')).products;}
function exactSelect(h){return h.root.querySelector('select[aria-label="Choose an exact variant"]');}
function assertNoCartWrite(h){assert.equal(h.calls.network.filter(r=>/\/cart\/add\.js$/.test(r.url)).length,0);assert.equal(h.calls.controls.filter(c=>['bag-quantity','bag-remove'].includes(c.action.type)).length,0);}

// These persistence/validation cases exercise the standalone widget. A
// connected page owns its own option controls, covered by commerce44 instead.
for(const count of [61,250])test('standalone restored complete '+count+'-variant piece retains its exact last option and only prepares confirmation',async t=>{
  const product=manyOptions(count),last=product.variants.at(-1),h=fixture(t,{noStorefront:true,restoredProducts:[product],restoredVariants:{[product.id]:last.id}});await h.open();
  h.button('Choose options').click();const select=exactSelect(h);assert.equal(select.options.length,count);assert.equal(select.value,last.id);assert.equal(select.options[count-1].textContent,last.title+' · $'+last.price.toFixed(2));
  const saved=savedProducts(h)[0];assert.equal(saved.variants.length,count);assert.equal(saved.variantsComplete,true);assert.equal(new Set(saved.variants.map(v=>v.id)).size,count);assert.equal(saved.suggestedVariantId,last.id);
  assert.equal(h.button('Review adding to bag').disabled,false);h.button('Review adding to bag').click();assert.match(h.root.querySelector('.review')?.textContent||'',new RegExp(last.title.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.ok(h.button('Confirm add to bag'));assertNoCartWrite(h);assert.equal(h.calls.network.filter(r=>r.body.message).length,0);assert.equal(h.errors.length,0);
});

test('a standalone restored 251-variant piece is bounded to 250 and cannot claim or review a complete selection',async t=>{
  const product=manyOptions(251),last=product.variants.at(-1),h=fixture(t,{noStorefront:true,restoredProducts:[product],restoredVariants:{[product.id]:last.id}});await h.open();h.button('Choose options').click();
  const select=exactSelect(h),saved=savedProducts(h)[0];assert.equal(select.options.length,250);assert.equal(saved.variants.length,250);assert.equal(saved.variantsComplete,false);assert.equal([...select.options].some(o=>o.value===last.id),false);assert.notEqual(select.value,last.id);assert.notEqual(saved.suggestedVariantId,last.id);assert.equal(h.button('Review adding to bag').disabled,true);assert.match(h.root.querySelector('.options .note').textContent,/complete selection/);h.button('Review adding to bag').click();assert.equal(h.root.querySelector('.review'),null);assertNoCartWrite(h);
});

for(const [label,damage] of [
  ['mismatched exact numeric identity',p=>{p.variants[1].numericId='999999';}],
  ['invalid published variant identity',p=>{p.variants[1].id='not-a-shopify-variant';}],
  ['nonfinite variant price',p=>{p.variants[1].price=null;}],
  ['duplicate exact variant identity',p=>{p.variants[1]=clone(p.variants[0]);}]
])test('standalone restored '+label+' fails completeness and keeps only distinct checked option rows',async t=>{
  const product=manyOptions(3);damage(product);const h=fixture(t,{noStorefront:true,restoredProducts:[product]});await h.open();h.button('Choose options').click();const saved=savedProducts(h)[0];
  assert.equal(saved.variants.length,2);assert.equal(new Set(saved.variants.map(v=>v.id)).size,2);assert.equal(exactSelect(h).options.length,2);assert.equal(saved.variantsComplete,false);assert.equal(h.button('Review adding to bag').disabled,true);h.button('Review adding to bag').click();assert.equal(h.root.querySelector('.review'),null);assertNoCartWrite(h);assert.equal(h.errors.length,0);
});

test('an honestly incomplete standalone restored list stays incomplete and a wholly invalid list cannot restore a product',async t=>{
  const incomplete=manyOptions(61);incomplete.variantsComplete=false;const empty=clone(bunny);empty.variants=[{id:'invalid',numericId:'0',price:null}];
  const h=fixture(t,{noStorefront:true,restoredProducts:[incomplete,empty]});await h.open();h.button('Choose options').click();assert.equal(exactSelect(h).options.length,61);assert.equal(savedProducts(h).length,1);assert.equal(savedProducts(h)[0].variantsComplete,false);assert.equal(h.root.querySelectorAll('.card').length,1);assert.equal(h.button('Review adding to bag').disabled,true);assertNoCartWrite(h);
});

test('native opening of a complete 250-variant piece preserves saved options but keeps spoken and tool envelopes bounded',async t=>{
  const h=fixture(t),product=manyOptions(250);h.setProducts([product]);await h.voice();const turn=h.speak('Open Compass Necklace'),result=await h.config.onTool({type:'open',handle:piece.handle},turn);
  assert.equal(result.ok,true);assert.equal(savedProducts(h)[0].variants.length,250);assert.equal(savedProducts(h)[0].variantsComplete,true);assert.equal(result.products.length,1);assert.equal(result.products[0].variants.length,24);assert.equal(result.products[0].variantsComplete,false);assert.equal(result.products[0].optionsTruncated,true);assert.ok(Buffer.byteLength(JSON.stringify(result),'utf8')<=20000);assert.equal(h.calls.stops,0);assertNoCartWrite(h);assert.equal(h.errors.length,0);
});
