'use strict';
// Tests the visible command panel against the real local intent bridge/host;
// its concierge gateway is synthetic. The full widget gateway is tested by
// storefront-shopping37.test.cjs. No paid inference or voice starts here.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const Bridge=require('../../brites-storefront-bridge.js');
const categories=['regular-necklaces','beady-necklaces','stud-earrings','hoop-earrings','charm-only'];
const settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
function products(){return Array.from({length:120},(_,i)=>{const category=categories[i%5],name=category.includes('necklaces')?'Necklace':category.includes('earrings')?'Earrings':'Charm';const variants=['Sterling Silver','14k Gold Filled','14k Solid Gold'].flatMap((metal,m)=>['14 inch','18 inch'].map((length,l)=>({id:'gid://shopify/ProductVariant/'+(37000+i*10+m*2+l),title:metal+' / '+length,price:50+m*100+l*5,available:true,options:[{name:'Metal Choice',value:metal},{name:'Chain Length',value:length}]})));return {id:'gid://shopify/Product/'+(3700+i),handle:'sample-'+i,title:'Sample '+i+' '+name,type:name,currency:'USD',description:'Published exact listing details.',url:'https://britesjewelry.com/products/sample-'+i,options:[{name:'Metal Choice',values:['Sterling Silver','14k Gold Filled','14k Solid Gold']},{name:'Chain Length',values:['14 inch','18 inch']}],storeCategories:[category],variantsComplete:true,variants};});}
async function fixture(t,{gateway=true,stockUnknown=false}={}){
  const dom=new JSDOM(fs.readFileSync(require.resolve('../../concierge-sandbox.html'),'utf8'),{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,d=w.document,p=products(),requests=[];let n=0,hold=null;
  if(stockUnknown)p[0].variants.forEach(v=>{v.available=false;v.availabilityKnown=false;});
  w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=function(){};
  w.fetch=async path=>{const u=new URL(path,w.location.href);let body;if(u.pathname==='/api/growth/catalogue')body={live:true,checkedAt:Date.now(),products:p,pageInfo:{hasNextPage:false,endCursor:null},seed:{schema:1,target:120,minimum:100,loaded:120,complete:true,partial:false,sourcePages:1,categoryCounts:Object.fromEntries(categories.map(c=>[c,24])),unfilledCategories:[]}};else if(u.pathname==='/api/growth/product')body={live:true,product:p.find(x=>x.handle===u.searchParams.get('handle'))};else if(u.pathname==='/api/growth/storefront-services')body={guidance:{},offers:{items:[]}};else throw Error('Unexpected route '+u.pathname);return {ok:true,json:async()=>structuredClone(body)};};
  const bridge=Bridge.create({storefront:()=>w.BritesSandboxStorefront});if(gateway)w.BritesConcierge={sendShopperCommand:async text=>{requests.push(text);if(hold)await hold();const resolved=bridge.resolve(text);return resolved.ok?bridge.execute(resolved.action,{source:'typed',transcript:text,requestId:'panel-current-'+(++n)}):resolved;}};
  w.eval(fs.readFileSync(require.resolve('../../concierge-sandbox.js'),'utf8'));await settle();t.after(()=>{bridge.destroy();w.close();});
  const click=async label=>{const b=[...d.querySelectorAll('#guide-commands button')].find(b=>b.textContent===label);assert(b,'Missing guide request '+label);b.click();await settle();};return {w,d,p,requests,click,setHold(fn){hold=fn;},store:()=>w.BritesSandboxStorefront};
}
test('each visible category request uses the concierge gateway and changes the real checked host filter',async t=>{const f=await fixture(t);for(const [label,filter] of [['Regular necklaces','regular-necklaces'],['Beady necklaces','beady-necklaces'],['Stud earrings','stud-earrings'],['Hoop earrings','hoop-earrings'],['Charm-only','charm-only']]){await f.click(label);assert.equal(f.store().snapshot().filter,filter);assert.equal(f.requests.at(-1),'Show me '+label.toLowerCase());}assert.equal(f.requests.length,5);});
test('product demo commands open the actual menus, resolve an exact selection and show its current total',async t=>{const f=await fixture(t);await f.click('Open Sample 0 Necklace');assert.equal(f.store().snapshot().currentHandle,'sample-0');await f.click('Open Metal Choice');assert.equal(f.d.querySelector('.option-menu').hidden,false);await f.click('Choose 14k Gold Filled');await f.click('Open Chain Length');await f.click('Choose 18 inch');let pc=f.store().snapshot().productControls;assert.equal(pc.selectedVariant.price,155);assert.equal(pc.selectedVariant.options[0].value,'14k Gold Filled');await f.click('Quantity 2');pc=f.store().snapshot().productControls;assert.equal(pc.itemTotalPrice,310);assert.match(f.d.querySelector('#guide-selection').textContent,/310\.00 USD item subtotal/);await f.click('Highlight price');assert(f.d.querySelector('.product-price').classList.contains('store-highlight'),JSON.stringify({command:f.requests.at(-1),resolved:Bridge.resolve(f.requests.at(-1),f.store().snapshot()),status:f.d.querySelector('#guide-request-status').textContent}));assert.equal(f.w.sessionStorage.getItem('brites-sandbox-cart'),null);});
test('a request stays disabled while the concierge gateway is busy and cannot be repeated',async t=>{const f=await fixture(t);let release;f.setHold(()=>new Promise(resolve=>{release=resolve;}));const b=f.d.querySelector('#guide-commands button');b.click();assert.equal(f.requests.length,1);assert([...f.d.querySelectorAll('#guide-commands button')].every(b=>b.disabled));assert.equal(f.d.querySelector('#guide-request').disabled,true);f.d.querySelector('#guide-commands button').click();assert.equal(f.requests.length,1);release();await settle();assert.equal(f.d.querySelector('#guide-request').disabled,false);});
test('a missing concierge gateway makes no direct host change',async t=>{const f=await fixture(t,{gateway:false});await f.click('Hoop earrings');assert.equal(f.store().snapshot().filter,'all');assert.match(f.d.querySelector('#guide-request-status').textContent,/still loading/);});
test('unconfirmed catalogue stock has a published starting price and an explicit pending availability label',async t=>{const f=await fixture(t,{stockUnknown:true}),card=f.d.querySelector('[data-product-handle="sample-0"]');assert.match(card.textContent,/From \$50\.00 USD/);assert.match(card.textContent,/Availability checked when you open/);assert.doesNotMatch(card.textContent,/Currently unavailable/);});
