'use strict';
// Mount the real request panel, intent bridge and widget over checked public
// fixtures. No provider, microphone, production bag or payment calls.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM,VirtualConsole}=require('jsdom');
const files=['concierge-sandbox.html','concierge-sandbox.js','brites-storefront-bridge.js','brites-concierge.js'],source=Object.fromEntries(files.map(name=>[name,fs.readFileSync(require.resolve('../../'+name),'utf8')]));
const clone=value=>JSON.parse(JSON.stringify(value)),settle=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
function piece(index){const handle=index?'maple-earrings':'daisy-necklace';return {id:'gid://shopify/Product/'+(39100+index),handle,title:index?'Maple Earrings':'Daisy Necklace',type:index?'Earrings':'Necklace',description:'Exact published synthetic silver and gold filled piece.',url:'https://britesjewelry.com/products/'+handle,currency:'USD',image:'https://cdn.shopify.com/'+handle+'-1.jpg',images:[1,2,3].map(n=>({url:'https://cdn.shopify.com/'+handle+'-'+n+'.jpg'})),options:[{name:'Metal Choice',values:['Sterling Silver','Gold Filled']},{name:'Chain Length',values:['16 inch','18 inch']}],variantsComplete:true,detailState:'checked',checkedAt:Date.now(),variants:['Sterling Silver','Gold Filled'].flatMap((metal,m)=>['16 inch','18 inch'].map((length,l)=>({id:'gid://shopify/ProductVariant/'+(391000+index*10+m*2+l),numericId:String(391000+index*10+m*2+l),title:metal+' / '+length,price:50+m*20+l*5,available:true,options:[{name:'Metal Choice',value:metal},{name:'Chain Length',value:length}]})))};}
async function fixture(t){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',error=>errors.push(error));const dom=new JSDOM(source['concierge-sandbox.html'],{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document,rows=[piece(0),piece(1)],requests=[];t.after(()=>{w.BritesConcierge?.close();w.close();});delete d.body.dataset.catalogueSeed;
  w.matchMedia=()=>({matches:false,addEventListener(){}});w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=()=>{};
  w.fetch=async(raw,init={})=>{const url=new URL(raw,w.location.href);requests.push({url,init});let body;if(url.pathname==='/api/growth/catalogue')body={live:true,checkedAt:Date.now(),products:rows,pageInfo:{hasNextPage:false,endCursor:null}};else if(url.pathname==='/api/growth/inventory')body={live:true,checkedAt:Date.now(),products:rows,inventory:{schema:1,total:2,offset:0,limit:24,loaded:2,detailsLoaded:2,ready:true,partial:false,expiresAt:Date.now()+300000},pageInfo:{hasNextPage:false,nextOffset:null}};else if(url.pathname==='/api/growth/product')body={live:true,checkedAt:Date.now(),product:rows.find(p=>p.handle===url.searchParams.get('handle'))};else if(url.pathname==='/api/growth/storefront-services')body={schema:1,guidance:{},conflicts:[],offers:{items:[]}};else if(url.pathname==='/api/growth/events'||url.pathname==='/api/concierge-voice')body={ok:true,enabled:true,nativeAudio:true,publicDemo:true};else if(url.pathname==='/api/concierge')body={live:true,reply:'Welcome to the test boutique.',products:[],meanings:[],preferences:{},preserveSelection:true};else throw Error('An immediate panel control tried an unexpected commerce route: '+url.pathname);return {ok:true,json:async()=>clone(body)};};
  w.eval(source['brites-storefront-bridge.js']);w.eval(source['concierge-sandbox.js']);await settle();await w.BritesSandboxStorefront.preloadInventory();
  w.BritesConciergeAvatar={create(){return {setState(){},setEmotion(){},setVisible(){},setPaused(){},retry(){},triggerGreeting(){},clearFocus(){},focusProduct(){},setLevel(){},setSpeechSignal(){},clearProduct(){},showProduct(){},cancelPerformance(){},setFloating(){},cue(){},destroy(){}};}};const script=d.createElement('script');script.src='/brites-concierge.js';script.dataset.sandbox='true';Object.defineProperty(d,'currentScript',{get:()=>script});w.eval(source['brites-concierge.js']);await settle();
  const host=d.querySelector('brites-concierge'),root=host.shadowRoot;w.BritesConcierge.open({focus:false});await settle();
  async function done(){for(let turn=0;turn<50;turn++){await settle();if(d.querySelector('#guide-request-form').getAttribute('aria-busy')==='false')return;}throw Error('The guided request did not settle.');}
  async function click(label){const button=[...d.querySelectorAll('#guide-commands button')].find(b=>b.textContent===label);assert(button,'Missing contextual request '+label);assert.equal(button.disabled,false,label+' should be available');button.click();assert.equal(d.querySelector('#guide-request-form').getAttribute('aria-busy'),'true');await done();return d.querySelector('#guide-request-status').textContent;}
  return {w,d,root,rows,requests,errors,host,store:w.BritesSandboxStorefront,click,done};
}
test('the visible four-step collection example goes through the real widget and shows all requested page effects',async t=>{
  const f=await fixture(t),before=f.requests.length,observed=[];f.d.addEventListener('brites-storefront:context',()=>{const s=f.store.snapshot();observed.push({handle:s.currentHandle,open:s.productControls?.optionsOpen,choices:s.productControls?.selectedOptions});});const reply=await f.click('Try four steps');assert.equal(f.store.snapshot().currentHandle,f.rows[0].handle,reply);assert.equal(f.store.snapshot().productControls.optionsOpen,true);assert.deepEqual(clone(f.store.snapshot().productControls.selectedOptions),[{name:'Metal Choice',value:'Sterling Silver'}]);assert(f.d.querySelector('.product-price').classList.contains('store-highlight'));assert(observed.some(s=>s.handle===f.rows[0].handle));assert(observed.some(s=>s.open));assert(observed.some(s=>s.choices?.some(o=>o.value==='Sterling Silver')));assert.match(reply,/open|selected|highlighted/);assert.match(f.d.querySelector('#guide-request').value,/ then /);assert.match(f.d.querySelector('#guide-sequence').textContent,/set quantity to 2/);assert.equal(f.requests.length,before);assert.equal(f.d.querySelector('brites-concierge'),f.host);assert.equal(f.errors.length,0);
});
test('product request examples expose exact menus and prices, image closing and real undo through the same mounted guide',async t=>{
  const f=await fixture(t),providerCalls=f.requests.filter(r=>r.url.pathname==='/api/concierge').length;await f.click('Open Daisy Necklace');await f.click('Try four steps');assert.equal(f.store.snapshot().productControls.quantity,2);await f.click('Open Chain Length');assert.equal(f.d.querySelector('[data-option-name="Chain Length"]').hidden,false);await f.click('Choose 18 inch');const priceReply=await f.click('Ask the price');assert.match(priceReply,/(?:\$55|USD 55\.00)/);assert.match(priceReply,/(?:\$110|USD 110\.00)/);assert.equal(f.store.snapshot().productControls.itemTotalPrice,110);assert.match(f.d.querySelector('#guide-selection').textContent,/110\.00 USD item subtotal/);
  await f.click('Next image');assert.equal(f.store.snapshot().galleryControls.selectedIndex,2);await f.click('Enlarge image');assert.equal(f.store.snapshot().imageControls.open,true);await f.click('Close enlarged image');assert.equal(f.store.snapshot().imageControls.open,false);await f.click('Undo last change');assert.equal(f.store.snapshot().galleryControls.selectedIndex,1);assert.equal(f.store.snapshot().productControls.variantId,f.rows[0].variants[1].id);assert.equal(f.requests.filter(r=>r.url.pathname==='/api/concierge').length,providerCalls);assert.equal(f.errors.length,0);
});
test('bag and checkout examples remain contextual and complete their four steps without checking final purchase acknowledgement',async t=>{
  const f=await fixture(t);await f.click('Open Daisy Necklace');await f.click('Choose Sterling Silver');await f.click('Open Chain Length');await f.click('Choose 18 inch');await f.click('Review for my bag');const confirm=f.d.querySelector('.product-review .primary');assert(confirm,'The mounted request must present a separate exact-choice confirmation on the real page');assert.equal(confirm.textContent,'Confirm add to test bag');assert.equal(f.store.snapshot().bagControls.itemCount,0);confirm.click();await settle();await settle();await f.click('Open my bag');assert.equal(f.store.snapshot().pageKind,'bag');assert.match(f.d.querySelector('#guide-sequence').textContent,/Enable gift wrapping then open checkout/);const reply=await f.click('Try four steps');assert.equal(f.store.snapshot().pageKind,'checkout',reply);assert.equal(f.store.snapshot().checkoutControls.step,'shipping');assert.equal(f.store.snapshot().checkoutControls.shipping,'express');assert.equal(f.d.querySelector('[name=wrapping]').checked,true);assert.equal(f.store.snapshot().checkoutControls.acknowledged,false);assert.equal(f.store.snapshot().checkoutControls.complete,false);assert.equal(f.d.querySelector('.receipt'),null);assert.match(f.d.querySelector('#guide-sequence').textContent,/show checkout confirmation step/);await f.click('Try four steps');assert.equal(f.store.snapshot().checkoutControls.step,'confirm');assert.equal(f.d.querySelector('#confirm-test-checkout').checked,false);assert.equal(f.d.querySelector('.receipt'),null);assert.equal(f.errors.length,0);
});
