'use strict';
// Production widget, synthetic server responses. No microphone/provider calls.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM, VirtualConsole} = require('jsdom');
const widget = fs.readFileSync(require.resolve('../../brites-concierge.js'), 'utf8');
const actions = fs.readFileSync(require.resolve('../../brites-concierge-voice-actions.js'), 'utf8');
const Bridge=require('../../brites-storefront-bridge.js');
const Storefront=require('../../netlify/functions/_britesStorefront.js');
const NOW = 1791340000000;
const clone = value => JSON.parse(JSON.stringify(value));
const settle = async () => {await new Promise(resolve => setImmediate(resolve)); await new Promise(resolve => setImmediate(resolve));};
const piece = {id:'gid://shopify/Product/31',handle:'studio-pendant',url:'https://britesjewelry.com/products/studio-pendant',title:'Studio pendant',type:'Necklace',currency:'USD',minPrice:54,variantsComplete:true,variants:[{id:'gid://shopify/ProductVariant/31',numericId:'31',title:'Silver',price:54,available:true,options:[{name:'Metal',value:'Silver'}]}]};
function guidance() {return {schema:1,policyOnly:true,live:false,aiUsed:false,products:[],meanings:[],actions:[],preferences:{},reply:'The studio offers gift packages, gift notes and gift wrapping. Confirm the package, availability and any charge for the selected order.',policyKnowledge:{status:'merchant_guidance',sources:[],checkedAt:null},policyUnavailable:false,serviceKnowledge:{schema:1,readCompleted:true,checkedAt:NOW,status:'merchant_provided',independentlyVerified:false,source:{kind:'merchant_statement',title:'Brites studio guidance',statedAt:'2026-10-07'},topics:['gifts'],conflicts:[],offers:[],publishedStatus:'checked'}};}
const services={schema:1,checkedAt:NOW,guidance:Storefront.merchantGuidance(),offers:{status:'none_observed',checkedAt:NOW,partial:false,items:[]},conflicts:[],policyLinks:[]};
function fixture(t, answer = guidance(), options={}) {
  const errors = [], vc = new VirtualConsole(); vc.on('jsdomError', error => errors.push(error));
  const dom = new JSDOM('<!doctype html><body></body>', {url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});
  const w = dom.window, d = w.document, script = d.createElement('script'); script.src = '/brites-concierge.js'; script.dataset.sandbox = 'true';
  Object.defineProperty(d, 'currentScript', {get:() => script}); w.Date.now = () => NOW; w.HTMLElement.prototype.scrollIntoView = function() {};
  let config, current = clone(answer); const calls = [];
  w.BritesConciergeAvatar = {create:() => ({setState(){},setEmotion(){},setVisible(){},setPaused(){},setLevel(){},setExpression(){},cancelPerformance(){},triggerGreeting(){},destroy(){}})};
  w.BritesConciergeVoice = {create:value => {config = value; return {start:async()=>true,stop:async()=>{},dispose:async()=>{},updateContext(){}};}};
  const controls=[],presented=[];if(options.connected){w.BritesStorefrontBridge=Bridge;w.BritesSandboxStorefront={snapshot:()=>({contextRevision:1,pageKind:'collection',currentHandle:'',focusedHandle:'',visiblePieces:[],search:'',sort:'featured',filter:'all',loading:false,activeSection:'catalogue'}),execute:async action=>{controls.push(clone(action));return {ok:true,reply:'The requested service section is shown.'};},presentProducts:value=>{presented.push(clone(value));return true;}};}
  w.fetch = async (url, init = {}) => {const body = init.body ? JSON.parse(init.body) : {}; calls.push({url:String(url),body}); if(body.message&&options.respond)return options.respond(body);return {ok:true,json:async()=>clone(String(url).includes('/storefront-services')?services:body.message ? current : {})};};
  w.eval(actions); w.eval(widget); const root = d.querySelector('brites-concierge').shadowRoot;
  const button = label => [...root.querySelectorAll('button')].find(b => b.textContent.trim() === label || b.getAttribute('aria-label') === label);
  t.after(() => {w.BritesConcierge.close(); w.close(); assert.deepEqual(errors, []); assert.equal(calls.some(c => c.body.action === 'start' || c.url.endsWith('/concierge-demo-turn')), false);});
  return {w,root,calls,controls,presented,setAnswer:v=>{current=clone(v);},async ask(text) {w.BritesConcierge.open(); await settle(); const input=root.querySelector('input[aria-label="Message the gift concierge"]'); input.value=text; root.querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true})); await settle();},async native(text='Do you offer gift wrapping?') {w.BritesConcierge.open(); await settle(); if(button('Talk to me')) {button('Talk to me').click(); await settle(); root.querySelector('script[src$="brites-concierge-voice.js"]')?.dispatchEvent(new w.Event('load')); await settle();} config.onSpeechStarted({itemId:'guidance-input',turnVersion:1,reason:'speech'}); config.onTranscript({role:'user',itemId:'guidance-input',turnVersion:1,currentTurn:true,final:true,text}); return clone(await config.onTool({message:text},{name:'find_jewellery',inputItemId:'guidance-input',turnVersion:1,currentTurn:true,responseId:'guidance-response'}));}};
}
test('typed merchant gift guidance uses an attributed status instead of claiming a failed or verified policy read', async t => {
  const h=fixture(t); await h.ask('Do you offer gift wrapping?'); assert.equal(h.root.querySelector('.status').textContent,'Studio guidance checked; piece-specific options need confirmation.'); assert.match(h.root.querySelector('.caption-text').textContent,/studio offers gift/); assert.equal(h.root.querySelectorAll('.card').length,0);
});
test('native gift guidance is fresh attributed evidence with no product facts or fabricated action', async t => {
  const h=fixture(t),out=await h.native(); assert.equal(out.verified,false); assert.equal(out.productsVerified,false); assert.equal(out.guidanceReadCompleted,true); assert.equal(out.serviceKnowledge.independentlyVerified,false); assert.equal(out.serviceKnowledge.pieceSpecificOptionsConfirmed,false); assert.deepEqual(out.products,[]); assert.deepEqual(out.meanings,[]); assert.deepEqual(out.actions,[]); assert.equal(h.w.sessionStorage.getItem('brites-sandbox-cart'),null);
});
const invalid = [
  ['incomplete read',v=>{v.serviceKnowledge.readCompleted=false;}],
  ['unknown schema',v=>{v.serviceKnowledge.schema=2;}],
  ['partial public source',v=>{v.policyKnowledge.status='partial';}],
  ['unavailable policy',v=>{v.policyUnavailable=true;}],
  ['stale timestamp',v=>{v.serviceKnowledge.checkedAt=NOW-300001;}],
  ['future timestamp',v=>{v.serviceKnowledge.checkedAt=NOW+60001;}],
  ['missing timestamp',v=>{delete v.serviceKnowledge.checkedAt;}],
  ['wrong provenance',v=>{v.serviceKnowledge.source.kind='model_statement';}],
  ['forged verification',v=>{v.serviceKnowledge.independentlyVerified=true;}],
  ['unrecognized topics',v=>{v.serviceKnowledge.topics=['private_accounts'];}],
  ['malformed date',v=>{v.serviceKnowledge.source.statedAt='yesterday';}],
  ['unavailable published read',v=>{v.serviceKnowledge.publishedStatus='unavailable';}]
];
for(const [name,change] of invalid) test(name+' cannot authorize an attributed completed native read',async t=>{const value=guidance();change(value);const h=fixture(t,value),out=await h.native();assert.equal(out.verified,false);assert.equal(Object.hasOwn(out,'guidanceReadCompleted'),false);assert.equal(Object.hasOwn(out,'serviceKnowledge'),false);assert.match(h.root.querySelector('.status').textContent,/could not be checked/);});
test('merchant read does not export arbitrary internal fields, offers or unsafe conflict links',async t=>{
  const value=guidance();value.serviceKnowledge.token='DO NOT EXPORT';value.serviceKnowledge.offers=[{code:'FAKE'}];value.serviceKnowledge.topics=['gifts','private_accounts'];value.serviceKnowledge.conflicts=[{topic:'sourcing',merchantSummary:'The studio states domestic sourcing.',publishedSummary:'Published sourcing needs clarification.',source:{title:'Brites published guidance',url:'https://britesjewelry.com/pages/about'}},{topic:'sourcing',merchantSummary:'a',publishedSummary:'b',source:{title:'Private',url:'https://other.example/account'}}];const h=fixture(t,value),out=await h.native();assert.equal(out.serviceKnowledge.conflicts.length,1);assert.equal(out.serviceKnowledge.conflicts[0].needsConfirmation,true);assert.deepEqual(out.serviceKnowledge.topics,['gifts']);assert.doesNotMatch(JSON.stringify(out),/DO NOT EXPORT|FAKE|other\.example|private_accounts/);
});
test('mixed response keeps fresh product verification separate from merchant policy attribution',async t=>{
  const value=guidance();Object.assign(value,{policyOnly:false,live:true,products:[piece],reply:'The current pendant costs USD 54. The studio offers gift notes; confirm options and any charge.'});const h=fixture(t,value),out=await h.native();assert.equal(out.verified,false);assert.equal(out.productsVerified,true);assert.equal(out.products.length,1);assert.equal(out.products[0].id,piece.id);assert.equal(out.products[0].minPrice,54);assert.equal(out.serviceKnowledge.independentlyVerified,false);
});
test('nonlive response cannot relabel retained card prices as fresh product evidence',async t=>{
  const h=fixture(t,{live:true,reply:'A piece is available.',preferences:{},products:[piece],meanings:[]});await h.ask('Show a pendant');const card=h.root.querySelector('.card');h.setAnswer(guidance());const out=await h.native();assert.equal(h.root.querySelector('.card'),card);assert.equal(out.productsVerified,false);assert.deepEqual(out.products,[]);assert.equal(out.displayedPieces[0].id,piece.id);assert.deepEqual(Object.keys(out.displayedPieces[0]).sort(),['handle','id','title']);assert.doesNotMatch(JSON.stringify(out.displayedPieces),/minPrice|currency|url/);
});
test('existing independently verified public policy status remains unchanged',async t=>{const value=guidance();Object.assign(value,{live:true,policyKnowledge:{status:'verified'}});delete value.serviceKnowledge;const h=fixture(t,value),out=await h.native('Explain shipping policy');assert.equal(out.verified,true);assert.equal(Object.hasOwn(out,'guidanceReadCompleted'),false);assert.equal(h.root.querySelector('.status').textContent,'Shop policy checked just now.');});
for(const text of ['Find a silver bunny necklace under $50 CAD and tell me about gift wrapping','Show me a gold ring under $60 USD and explain sourcing','Silver instead, under $60 each and gift wrapping','Tell me the story behind this bunny and explain gift notes','Open the second piece and explain sourcing'])test('connected typed mixed request reaches the core API with the complete original words: '+text,async t=>{const h=fixture(t,guidance(),{connected:true});await h.ask(text);assert.equal(h.calls.filter(v=>v.body.message).length,1);assert.equal(h.calls.find(v=>v.body.message).body.message,text);assert.equal(h.calls.some(v=>v.url.includes('/storefront-services')),false);assert.deepEqual(h.controls,[]);assert.equal(h.w.sessionStorage.getItem('brites-sandbox-cart'),null);});
for(const [text,type]of [['Show me gift wrapping for a silver necklace','gift'],['Scroll to shipping options','scroll'],['Highlight shipping options','highlight']])test('pure requested service section remains a local checked control: '+text,async t=>{const h=fixture(t,guidance(),{connected:true});await h.ask(text);assert.equal(h.calls.some(v=>v.body.message),false);assert.equal(h.calls.filter(v=>v.url.includes('/storefront-services')).length,1);assert.equal(h.controls.length,1);assert.equal(h.controls[0].type,type);assert.match(h.root.querySelector('.caption-text').textContent,/gift packages|Shipping options|shipping rates/i);});
function endpoint(){
  const Core=require('../../netlify/functions/_britesGrowth.js'),Policy=require('../../netlify/functions/_britesConcierge.js'),Diagnostics=require('../../netlify/functions/_britesConciergeDiagnostics.js'),source=fs.readFileSync(require.resolve('../../netlify/functions/britesConcierge.js'),'utf8').replace(/^import \w+ from .*;\s*$/gm,'').replace('export default async (req,context) => {','return async (req,context) => {').replace(/export const config = [\s\S]*$/,'');
  const counts={catalogue:0,model:0,services:0},p={...clone(piece),handle:'bunny-test',url:'https://britesjewelry.com/products/bunny-test',title:'Silver Bunny Necklace',description:'Includes a sterling silver chain.',tags:['bunny'],options:[{name:'Metal',values:['Silver']}],checkedAt:Date.now()};
  const service={namespace:'Brites_Growth_Sandbox',col:()=>({doc:()=>({set:async()=>{}})}),rateLimit:async()=>true,event:async()=>({ok:true}),setup:async()=>({aiEnabled:false}),saveProducts:async()=>{},productIssues:async()=>[],research:async()=>[]};
  const core={...Core,makeDb:()=>({}),createGrowthService:()=>service,createShopify:()=>({search:async()=>{counts.catalogue++;return {products:[p]};},byHandle:async()=>p}),readStorefrontServices:async()=>{counts.services++;return {...clone(services),checkedAt:Date.now(),offers:{...services.offers,checkedAt:Date.now()}};}};
  const handler=new Function('core','claude','policy','diagnostics','Netlify',source)(core,{createClaudeClient(){counts.model++;throw Error('Paid inference is forbidden.');}},{...Policy,createPolicyGuide:()=>Policy.createPolicyGuide({fetch:async()=>new Response('<main>Shipping choices and charges are shown at checkout.</main>',{headers:{'content-type':'text/html'}})})},Diagnostics,{env:{get:()=>undefined}});
  return {counts,p,call:body=>handler(new Request('https://preview.example/api/concierge',{method:'POST',headers:{Origin:'https://preview.example','Content-Type':'application/json'},body:JSON.stringify(body)}),{ip:'synthetic'})};
}
for(const [currency,budget,expectedProducts]of [['CAD',50,1],['USD',60,1],['USD',50,0]])test('connected mixed '+currency+' budget '+budget+' goes through the actual endpoint currency and item-budget gates',async t=>{
  const e=endpoint(),text='Find a silver bunny necklace under $'+budget+' '+currency+' and tell me about gift wrapping',h=fixture(t,guidance(),{connected:true,respond:e.call});await h.ask(text);await settle();const saved=JSON.parse(h.w.sessionStorage.getItem('brites-concierge-v1'));assert.equal(h.calls.find(v=>v.body.message).body.message,text);assert.equal(e.counts.catalogue,1);assert.equal(e.counts.services,1);assert.equal(e.counts.model,0);assert.equal(saved.preferences.metal,'silver');assert.match(saved.preferences.query,/bunny/);assert.equal(saved.preferences.budget,budget);assert.equal(saved.preferences.budgetCurrency,currency);assert.equal(saved.products.length,expectedProducts);assert.match(h.root.querySelector('.caption-text').textContent,/gift notes and gift wrapping/);if(currency==='CAD')assert.match(h.root.querySelector('.caption-text').textContent,/haven’t applied your CAD budget/);if(expectedProducts){assert.equal(saved.products[0].id,e.p.id);assert.equal(h.presented.length,1);}assert.deepEqual(h.controls,[]);assert.equal(h.w.sessionStorage.getItem('brites-sandbox-cart'),null);
});
