'use strict';
// Historical schema2 accounting stays strict; direct native API has no allowance policy.
const test=require('node:test'),assert=require('node:assert/strict');
const core=require('../../netlify/functions/_britesGrowth.js'),voice=require('../../netlify/functions/_britesConciergeVoice.js');
const {fixture,AT,clone}=require('./voice-fixture36.cjs');
const NATIVE='VoiceAllowances/native-sandbox';
function policy(options={}){const f=fixture({env:{BRITES_CONCIERGE_REALTIME_DEMO_USD_CAP:'10',BRITES_CONCIERGE_REALTIME_RESERVE_USD:'1',...options.env},...options});f.rows.set(NATIVE,{...f.rows.get(NATIVE),schema:2,limitCents:1000,continuationCents:500,continuationCount:1,continuationPolicy:'configured-preview-ceiling-once-v1',continuedAt:AT-5000,continuationAuthorizedBy:'synthetic-prior-owner',continuationCheckpointUpdatedAt:AT-6000,accountingVersion:1,accountedCalls:0,accountedAllocationCents:0});return f;}
const reserve=f=>voice.createDemoBudgetReservationResult(f.service,{capUsd:Number(f.env.BRITES_CONCIERGE_REALTIME_DEMO_USD_CAP),now:f.now,provenance:true,allowContinuation:true});
const inspect=f=>f.call({action:'allocation'},{operator:true});
test('historical schema2 helper retains exact accounting ceiling and five additional atomic slots',async()=>{
  const f=policy(),legacy=clone(f.rows.get('VoiceUsage/preview-budget')),original=clone(f.rows.get(NATIVE)),answers=await Promise.all(Array.from({length:6},(_,i)=>reserve(f)(1,'historical-schema2-session-'+i)));assert.equal(answers.filter(row=>row.granted).length,5);assert.equal(answers.find(row=>!row.granted).reason,'ALLOCATION_EXHAUSTED');const row=f.rows.get(NATIVE);assert.equal(row.schema,2);assert.equal(row.allocatedCents,500);assert.equal(row.limitCents,1000);assert.equal(row.continuationCents,500);assert.equal(row.continuationCount,1);assert.equal(row.reservedCents,1000);assert.equal(row.spentCents,0);assert.equal(row.calls,10);for(const key of ['issuedAt','expiresAt','authorizedBy','checkpointUpdatedAt','continuedAt','accountingVersion','accountedCalls','accountedAllocationCents'])assert.equal(row[key],original[key]);assert.deepEqual(f.rows.get('VoiceUsage/preview-budget'),legacy);assert.equal(f.provider.length,0);
});
test('retired native continuation requests cannot migrate schema1 or refill schema2',async()=>{
  for(const schema of [1,2]){const f=schema===1?fixture():policy(),before=f.protectedBytes(),answers=await Promise.all(Array.from({length:8},()=>f.call({action:'authorize-voice',continueToConfiguredCeiling:true,owner:'PRIVATE_CONTROLLER',token:'d'.repeat(64),expectedUpdatedAt:AT-1000},{operator:true})));assert.ok(answers.every(row=>row.response.status===410));assert.equal(f.protectedBytes(),before);assert.equal(f.db.counts.reads,0);assert.equal(f.db.counts.writes,0);assert.equal(f.provider.length,0);assert.doesNotMatch(JSON.stringify(answers.map(row=>row.value)),/PRIVATE_|d{64}|tokenHash|continuationCents|refund/);}
});
test('same historical helper session cannot reserve twice under schema2',async()=>{
  const f=policy(),results=await Promise.all([reserve(f)(1,'historical-schema2-same-session'),reserve(f)(1,'historical-schema2-same-session')]);assert.equal(results.filter(row=>row.granted).length,1);assert.equal(results.find(row=>!row.granted).reason,'SESSION_ALREADY_USED');assert.equal(f.rows.get(NATIVE).reservedCents,600);assert.equal(f.rows.get(NATIVE).calls,6);const before=f.protectedBytes(),writes=f.db.counts.writes;assert.deepEqual(await reserve(f)(1,'historical-schema2-same-session'),{granted:false,reason:'SESSION_ALREADY_USED'});assert.equal(f.protectedBytes(),before);assert.equal(f.db.counts.writes,writes);assert.equal(f.provider.length,0);
});
test('direct native API starts and explicit stop preserve every schema2 money field',async()=>{
  const f=policy(),before=f.protectedBytes(),answer=await f.start();assert.equal(answer.response.status,200);assert.equal(f.protectedBytes(),before);assert.equal((await f.call({action:'stop',stopToken:answer.value.stopToken})).value.stopped,true);assert.equal(f.protectedBytes(),before);assert.equal(f.rows.get('VoiceDeadlines/'+f.journal()[0].callId).state,'closed');assert.equal(f.journal()[0].allocatedCents,undefined);
});
for(const patch of [
  {schema:3},{limitCents:1001},{limitCents:500},{limitCents:'1000'},{continuationCents:499},{continuationCount:2},{continuationPolicy:'unproved-refill'},
  {continuedAt:AT-600001},{continuedAt:core.STOP_AT},{continuationAuthorizedBy:'invalid owner'},{continuationCheckpointUpdatedAt:'0'},
  {accountingVersion:2},{accountedCalls:1},{accountedAllocationCents:100},{spentCents:1},{reservedCents:400},{calls:6},{reservedCents:1100,calls:11},{allocatedCents:1000},{expiresAt:core.STOP_AT+1},{reservationCents:99}
])test('historical schema2 malformed accounting remains a strict helper denial '+JSON.stringify(patch),async()=>{
  const f=policy();f.rows.set(NATIVE,{...f.rows.get(NATIVE),...patch});const before=f.moneyBytes();assert.deepEqual(await reserve(f)(1,'historical-schema2-invalid-session'),{granted:false,reason:'INVALID_LEDGER'});assert.equal(f.moneyBytes(),before);assert.equal(f.db.counts.writes,0);assert.equal(f.provider.length,0);const projection=await inspect(f);assert.equal(projection.response.status,200);assert.equal(projection.value.nativeAllowance.valid,false);assert.equal(projection.value.historical,true);assert.equal(f.moneyBytes(),before);const answer=await f.start();assert.equal(answer.response.status,200);assert.equal(f.moneyBytes(),before);
});
test('partial schema1 extension data cannot be reinterpreted by historical helpers',async()=>{
  const f=fixture();f.rows.set(NATIVE,{...f.rows.get(NATIVE),limitCents:1000});const before=f.protectedBytes();assert.deepEqual(await voice.createDemoBudgetReservationResult(f.service,{capUsd:10,now:f.now,provenance:true,allowContinuation:true})(1,'historical-partial-schema-session'),{granted:false,reason:'INVALID_LEDGER'});assert.equal(f.protectedBytes(),before);assert.equal(f.db.counts.writes,0);assert.equal(f.provider.length,0);
});
test('future-dated historical continuation is pending for helpers without gating direct voice',async()=>{
  const f=policy();f.rows.set(NATIVE,{...f.rows.get(NATIVE),continuedAt:AT+1000});const before=f.moneyBytes(),projection=await inspect(f);assert.equal(projection.response.status,200);assert.equal(projection.value.nativeAllowance.state,'pending');assert.equal(projection.value.nativeAllowance.effective,false);assert.equal(projection.value.nativeAllowance.nextReservationFits,false);assert.deepEqual(await reserve(f)(1,'historical-future-schema-session'),{granted:false,reason:'ALLOCATION_EXHAUSTED'});assert.equal(f.moneyBytes(),before);assert.equal(f.db.counts.writes,0);assert.equal((await f.start()).response.status,200);assert.equal(f.moneyBytes(),before);f.advance(1000);assert.equal((await reserve(f)(1,'historical-current-schema-session')).granted,true);assert.equal(f.rows.get(NATIVE).reservedCents,600);
});
for(const change of ['ceiling','reservation'])test('historical schema2 '+change+' drift does not reinterpret stored continuation authority',async()=>{
  const f=policy();if(change==='ceiling')f.env.BRITES_CONCIERGE_REALTIME_DEMO_USD_CAP='9';else f.env.BRITES_CONCIERGE_REALTIME_RESERVE_USD='2';const before=f.moneyBytes(),cents=change==='reservation'?2:1;assert.deepEqual(await reserve(f)(cents,'historical-config-drift-session'),{granted:false,reason:'INVALID_LEDGER'});assert.equal(f.moneyBytes(),before);assert.equal(f.db.counts.writes,0);assert.equal(f.provider.length,0);assert.equal((await f.start()).response.status,200);assert.equal(f.moneyBytes(),before);
});
test('historical operator inspection cannot expose authority or imply measured invoice cost',async()=>{
  const f=policy(),before=f.protectedBytes(),answer=await inspect(f);assert.equal(answer.response.status,200);assert.equal(answer.value.historical,true);assert.equal(answer.value.nativeVoiceUsesAllocation,false);assert.equal(answer.value.nativeAllowance.usageSettled,false);assert.equal(answer.value.nativeAllowance.accountedCalls,0);assert.equal(answer.value.nativeAllowance.spentCents,0);assert.equal(answer.value.refunds,0);assert.equal(answer.value.providerCalls,0);assert.equal(f.protectedBytes(),before);assert.equal(f.db.counts.writes,0);assert.doesNotMatch(JSON.stringify(answer.value),/synthetic-only|PRIVATE_|tokenHash|AuthorizedBy|authorizedBy|CheckpointUpdatedAt|checkpointUpdatedAt|originalHistory/);
});
