'use strict';
// Authored QA controls run against the production widget/planner and SVG rig.
// Output samples and clocks are explicitly synthetic. No microphone, provider,
// physical audio, word-timing or GPU acceptance follows from these tests.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const Expression=require('../../brites-concierge-expression.js'),Avatar=require('../../brites-concierge-avatar.js');
const qa=fs.readFileSync(require.resolve('../../concierge-actions-qa.js'),'utf8'),html=fs.readFileSync(require.resolve('../../concierge-actions-qa.html'),'utf8');
const widget=fs.readFileSync(require.resolve('../../brites-concierge.js'),'utf8'),actions=fs.readFileSync(require.resolve('../../brites-concierge-voice-actions.js'),'utf8');
const settle=async()=>{await new Promise(r=>setImmediate(r));await new Promise(r=>setImmediate(r));};
function fixture(t,{pathname='/concierge-actions-qa.html'}={}){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
  const dom=new JSDOM(html,{url:'https://preview.example'+pathname,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document;
  let clock=1791340000000,serial=0,hidden=false,microphones=0;const timers=new Map(),frames=new Map(),requests=[],guides=[],planners=[];
  const script=[...d.querySelectorAll('script')].find(s=>s.src.endsWith('/brites-concierge.js'));Object.defineProperty(d,'currentScript',{get:()=>script});Object.defineProperty(d,'hidden',{get:()=>hidden});Object.defineProperty(w.performance,'now',{value:()=>clock});w.Date.now=()=>clock;
  w.setTimeout=(fn,ms=0)=>{const id=++serial;timers.set(id,{fn,at:clock+Number(ms),ms:Number(ms)});return id;};w.clearTimeout=id=>timers.delete(id);
  w.requestAnimationFrame=fn=>{const id=++serial;frames.set(id,fn);return id;};w.cancelAnimationFrame=id=>frames.delete(id);w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});w.HTMLElement.prototype.scrollIntoView=function(){};
  Object.defineProperty(w.navigator,'mediaDevices',{value:{getUserMedia(){microphones++;throw Error('No microphone is permitted by this fixture.');}}});
  w.BritesConciergeExpression={...Expression,create(options){const planner=Expression.create({...options,now:()=>clock});planners.push(planner);return planner;}};
  w.BritesConciergeAvatar={create(options){const guide=Avatar.create({...options,loadScene:async()=>{throw Error('Explicit synthetic fixture: WebGL unavailable');}});guides.push(guide);return guide;}};
  w.fetch=async(url,init={})=>{const body=init.body?JSON.parse(init.body):{};requests.push({url:String(url),body});if(body.action==='start')throw Error('Provider start is forbidden.');return {ok:true,json:async()=>({enabled:true,live:true,reply:'Checked selection.',preferences:{},products:[],meanings:[]})};};
  w.eval(actions);w.eval(qa);if(pathname==='/concierge-actions-qa.html')w.eval(widget);
  const root=()=>d.querySelector('brites-concierge')?.shadowRoot,button=label=>[...(root()?.querySelectorAll('button')||[])].find(b=>b.textContent.trim()===label||b.getAttribute('aria-label')===label);
  function facts(){return JSON.parse(d.querySelector('#diagnostics').textContent||'{}');}
  function frame(ms=50){clock+=ms;for(const[id,value]of[...timers].sort((a,b)=>a[1].at-b[1].at))if(value.at<=clock&&timers.delete(id))value.fn();for(const[id,fn]of[...frames])if(frames.delete(id))fn(clock);return facts();}
  function advance(ms){for(let n=ms;n>0;n-=50)frame(Math.min(50,n));return facts();}
  const h={w,d,requests,timers,frames,errors,button,root,facts,frame,advance,get guide(){return guides.at(-1);},get planner(){return planners.at(-1);},async click(id){d.querySelector('#'+id).click();await settle();return facts();},async start(){await h.click('open-guide');button('Talk to me').click();await settle();assert.ok(button('End voice'));await guides.at(-1)?.ready;},async enable(){button('Enable audio').click();await settle();return facts();},hide(value){hidden=value;d.dispatchEvent(new w.Event('visibilitychange'));}};
  t.after(async()=>{try{w.BritesConcierge?.close();}catch{}for(const p of planners)p.destroy();for(const g of guides)g.destroy();timers.clear();frames.clear();w.close();await settle();assert.equal(microphones,0);assert.equal(requests.some(r=>r.body.action==='start'||r.url.includes('api.openai.com')),false);assert.deepEqual(errors,[]);});return h;
}
test('QA declares synthetic clocks and samples and loads the real planner before the adapter and widget',()=>{
  assert.match(html,/requests no microphone, sends no OpenAI calls/);assert.match(html,/authored output amplitude and frequency-band samples plus synthetic media timestamps/);assert.match(html,/does not test native sound, spoken latency, word alignment or GPU rendering/);assert.ok(html.indexOf('/brites-concierge-expression.js')<html.indexOf('/concierge-actions-qa.js'));assert.ok(html.indexOf('/concierge-actions-qa.js')<html.indexOf('/brites-concierge.js"'));assert.doesNotMatch(qa,/getUserMedia|RTCPeerConnection|api\.openai\.com|AudioContext|speechSynthesis/);
});
test('synthetic adapter is absent away from its exact QA route',async t=>{const h=fixture(t,{pathname:'/concierge-sandbox.html'});assert.equal(h.w.BritesConciergeVoiceActionTestAdapter,undefined);assert.equal(h.d.querySelector('#audio-recovery').onclick,null);assert.equal(h.requests.length,0);});
test('recovery is inert before an explicit guide Talk click',async t=>{const h=fixture(t);await h.click('audio-recovery');assert.match(h.facts().error,/Activate the adapter/);assert.equal(h.planner,undefined);assert.equal(h.requests.filter(r=>r.body.message).length,0);});
test('actual Enable audio resumes the held response at its consumed estimate and continues to the final question',async t=>{
  const h=fixture(t);await h.start();await h.click('audio-recovery');const playing=h.advance(500);assert.equal(playing.phase,'playing');assert.equal(h.guide.snapshot().speechVisual.curveClosed,true);assert.equal(h.guide.snapshot().facePose.mouthOpen,0);assert.ok(h.guide.snapshot().speechVisual.amplitude>0);
  const held=h.advance(600);assert.equal(held.phase,'held');assert.equal(held.holdClockMs,1000);assert.equal(h.planner.snapshot().playbackHeld,true);assert.equal(h.planner.snapshot().cue,null);assert.equal(h.guide.snapshot().speechVisual.rippleActive,false);assert.equal(h.button('Enable audio').hidden,false);
  h.advance(5000);assert.equal(h.planner.snapshot().clockMs,1000);const resumed=await h.enable();assert.equal(resumed.phase,'recovered');assert.equal(resumed.heldIntervalIgnored,true);assert.equal(resumed.firstSampleOnlyAnchored,true);assert.equal(resumed.firstFreshClockMs,1000);assert.equal(resumed.starts,1);assert.equal(resumed.resumes,1);assert.equal(resumed.stops,0);assert.equal(h.root().querySelector('.voice-recovery').hidden,true);
  const complete=h.advance(6000);assert.equal(complete.phase,'complete');assert.equal(complete.passed,true);assert.deepEqual(complete.cueSequence,['appreciate','reflect','inquiry']);assert.equal(complete.finalBeforeDrain.cue.kind,'inquiry');assert.equal(complete.finalBeforeDrain.responseId,complete.responseId);assert.equal(complete.providerCalls,0);assert.equal(complete.microphoneRequests,0);assert.equal(complete.physicalAudioTested,false);assert.equal(complete.gpuTested,false);assert.equal(h.guide.snapshot().speechVisual.rippleActive,false);assert.equal(h.guide.snapshot().facePose.mouthOpen,0);assert.equal(h.button('End voice').hidden,false);
});
test('a fresh synthetic run does not replay a previous run or start another voice session',async t=>{
  const h=fixture(t);await h.start();await h.click('audio-recovery');const old=h.advance(1000);await h.enable();h.advance(6000);await h.click('audio-recovery');const next=h.advance(1000);assert.equal(next.starts,1);assert.notEqual(next.responseId,old.responseId);assert.notEqual(next.inputItemId,old.inputItemId);assert.equal(next.holdClockMs,1000);await h.enable();assert.equal(h.advance(6000).passed,true);assert.equal(h.facts().resumes,2);assert.equal(h.facts().starts,1);
});
test('the authored new-input and End control rejects delayed transcript, buffer, levels and recovery callbacks',async t=>{
  const h=fixture(t);await h.start();const out=await h.click('audio-recovery-late');assert.equal(out.check,'new-input-and-End-reject-delayed-recovery');assert.equal(out.passed,true);assert.equal(out.newInputRejected,true);assert.equal(out.endRejected,true);assert.equal(out.captionRejected,true);assert.equal(out.historyRejected,true);assert.equal(out.starts,1);assert.equal(out.stops,1);assert.equal(out.afterNewInput.clockMs,0);assert.equal(out.afterEnd.active,false);assert.equal(out.afterEnd.cue,null);assert.equal(h.guide.snapshot().speechVisual.rippleActive,false);assert.ok(h.button('Talk to me'));assert.doesNotMatch(h.root().querySelector('.caption-text').textContent,/Delayed .*content must not return/);const text=h.d.querySelector('#diagnostics').textContent;h.advance(5000);assert.equal(h.d.querySelector('#diagnostics').textContent,text);
});
test('held recovery expires after one bounded minute and ends the synthetic session',async t=>{
  const h=fixture(t);await h.start();await h.click('audio-recovery');h.advance(1000);const expired=h.advance(61000);await settle();assert.equal(expired.phase,'expired');assert.equal(expired.passed,false);assert.equal(h.planner.snapshot().active,false);assert.ok(h.button('Talk to me'));assert.equal(h.button('Enable audio').hidden,true);assert.equal(h.guide.snapshot().speechVisual.rippleActive,false);
});
test('End voice before recovery cancels the loop without a later revive or provider restart',async t=>{const h=fixture(t);await h.start();await h.click('audio-recovery');h.advance(400);h.button('End voice').click();await settle();const text=h.d.querySelector('#diagnostics').textContent;h.advance(7000);assert.equal(h.d.querySelector('#diagnostics').textContent,text);assert.equal(h.planner.snapshot().active,false);assert.equal(h.guide.snapshot().speechVisual.rippleActive,false);assert.ok(h.button('Talk to me'));});
test('new input and hidden document stop the authored recovery stream',async t=>{const h=fixture(t);await h.start();await h.click('audio-recovery');h.advance(400);await h.click('invalidate');const text=h.d.querySelector('#diagnostics').textContent;h.advance(5000);assert.equal(h.d.querySelector('#diagnostics').textContent,text);assert.equal(h.planner.snapshot().responseId,'');await h.click('audio-recovery');h.advance(1000);h.hide(true);await settle();assert.equal(h.planner.snapshot().active,false);assert.equal(h.guide.snapshot().speechVisual.rippleActive,false);assert.equal(h.button('Enable audio').hidden,true);});
test('cancel control clears current speech and leaves no queued synthetic signal',async t=>{const h=fixture(t);await h.start();await h.click('audio-recovery');h.advance(1000);await h.click('audio-recovery-cancel');assert.equal(h.facts().phase,'cancelled');assert.equal(h.planner.snapshot().active,false);assert.equal(h.guide.snapshot().speechVisual.rippleActive,false);const text=h.d.querySelector('#diagnostics').textContent;h.advance(3000);assert.equal(h.d.querySelector('#diagnostics').textContent,text);});
