'use strict';
// The real sandbox, widget, bridge and native voice client. All audio tracks,
// WebRTC events and HTTP responses below are synthetic: no microphone, provider,
// production cart, payment or deployment is accessed.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const native=require('../../brites-concierge-voice.js'),server=require('../../netlify/functions/_britesConciergeVoice.js');
const source=Object.fromEntries(['concierge-sandbox.html','concierge-sandbox.js','brites-storefront-bridge.js','brites-concierge.js'].map(name=>[name,fs.readFileSync(require.resolve('../../'+name),'utf8')]));
const SDP='v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\na=candidate:1 1 UDP 2122260223 192.0.2.10 50000 typ host\r\n';
const clone=value=>JSON.parse(JSON.stringify(value)),settle=async()=>{for(let n=0;n<4;n++)await new Promise(setImmediate);};
const categories=['regular-necklaces','beady-necklaces','stud-earrings','hoop-earrings','charm-only'];
function piece(index){const handle='voice-fast-'+index,type=index%5===4?'Charm':index%5<2?'Necklace':'Earrings',values=['Sterling Silver','14k Gold Filled','14k Solid Gold'];return {id:'gid://shopify/Product/'+(3900+index),handle,title:'Voice Fast '+index+' '+type,type,url:'https://britesjewelry.com/products/'+handle,description:'Published berry jewellery '+index+' measures 14mm and offers sterling silver, gold filled and solid gold.',currency:'USD',image:'https://cdn.shopify.com/'+handle+'.jpg',images:Array.from({length:16},(_,n)=>({url:'https://cdn.shopify.com/'+handle+'-'+n+'.jpg',altText:'Published photo '+n})),storeCategories:[categories[index%5]],options:[{name:'Metal Choice',values},{name:'Chain Length',values:['16 inches','18 inches']}],variantsComplete:true,checkedAt:Date.now(),detailState:'checked',variants:values.flatMap((metal,m)=>['16 inches','18 inches'].map((length,l)=>({id:'gid://shopify/ProductVariant/'+(39000+index*10+m*2+l),numericId:String(39000+index*10+m*2+l),title:metal+' / '+length,price:50+100*m+5*l,available:true,options:[{name:'Metal Choice',value:metal},{name:'Chain Length',value:length}]})))};}
async function fixture(t,{engraving=false}={}){
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
  const dom=new JSDOM(source['concierge-sandbox.html'],{url:'https://preview.example/concierge-sandbox.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document,products=Array.from({length:120},(_,i)=>piece(i)),requests=[],sent=[],hostResults=[],controls=[],presentations=[],tracks=[];let channel,config,client,hidden=false,turn=0,scroll=0;
  t.after(async()=>{w.BritesConcierge?.close();await client?.dispose();w.close();});
  if(engraving){const p=products[0];p.options.push({name:'Engraving',values:['None','Engraved']});p.variants=p.variants.flatMap(v=>[{...v,options:v.options.concat({name:'Engraving',value:'None'}),title:v.title+' / None'},{...v,id:'gid://shopify/ProductVariant/'+(Number(v.numericId)+90000),numericId:String(Number(v.numericId)+90000),options:v.options.concat({name:'Engraving',value:'Engraved'}),title:v.title+' / Engraved',price:v.price+10}]);}
  Object.defineProperty(d,'hidden',{get:()=>hidden});d.body.dataset.inventoryPreload='complete';w.matchMedia=()=>({matches:false,addEventListener(){}});w.HTMLElement.prototype.scrollIntoView=function(){};Object.defineProperty(w,'scrollY',{get:()=>scroll});w.scrollTo=x=>{scroll=x.top;};Object.defineProperty(d.documentElement,'scrollHeight',{get:()=>4000});
  w.HTMLMediaElement.prototype.play=async function(){};w.HTMLMediaElement.prototype.pause=function(){};
  const fetch=async(raw,init={})=>{const url=new URL(raw,w.location.href);requests.push({url,init});let value;
    if(url.pathname==='/api/growth/catalogue')value={live:true,checkedAt:Date.now(),products:products.map(p=>({...p,detailState:'unconfirmed',variants:p.variants.map(v=>({...v,available:false,availabilityKnown:false}))})),pageInfo:{hasNextPage:false,endCursor:null},seed:{schema:1,target:120,minimum:100,loaded:120,complete:true,partial:false,sourcePages:1,categoryCounts:Object.fromEntries(categories.map(c=>[c,24])),unfilledCategories:[]}};
    else if(url.pathname==='/api/growth/inventory'){const offset=Number(url.searchParams.get('offset')),rows=products.slice(offset,offset+24);value={live:true,checkedAt:Date.now(),products:rows,inventory:{schema:1,total:120,offset,limit:24,loaded:rows.length,detailsLoaded:rows.length,ready:false,partial:false,expiresAt:Date.now()+300000},pageInfo:{hasNextPage:offset+24<120,nextOffset:offset+24<120?offset+24:null}};}
    else if(url.pathname==='/api/growth/product')value={live:true,checkedAt:Date.now(),product:products.find(p=>p.handle===url.searchParams.get('handle'))};
    else if(url.pathname==='/api/concierge-voice'){const action=JSON.parse(init.body).action;value=action==='capabilities'?{enabled:true,nativeAudio:true,publicDemo:true}:action==='start'?{sdp:SDP,stopToken:'synthetic-only',maxDurationMs:120000}:{stopped:true};}
    else if(url.pathname==='/api/growth/events')value={ok:true};
    else if(url.pathname==='/api/concierge')value={live:true,reply:'Synthetic ordinary conversation.',products:[],meanings:[],preferences:{},preserveSelection:true};
    else throw Error('Unexpected synthetic route '+url.pathname);
    return {ok:true,status:200,json:async()=>clone(value)};
  };w.fetch=fetch;
  class Peer{constructor(){this.iceGatheringState='complete';}addTrack(){}close(){}createDataChannel(){channel={readyState:'connecting',send:value=>sent.push(JSON.parse(value)),close(){}};return channel;}async createOffer(){return {type:'offer',sdp:SDP};}async setLocalDescription(value){this.localDescription=value;}async setRemoteDescription(){channel.readyState='open';channel.onopen();}}
  const runtime={document:d,location:w.location,navigator:{mediaDevices:{getUserMedia:async()=>{const track={readyState:'live',stop(){this.readyState='ended';},addEventListener(){},removeEventListener(){}};tracks.push(track);return {getTracks:()=>[track],getAudioTracks:()=>[track]};}}},RTCPeerConnection:Peer,AbortController:w.AbortController,fetch,setTimeout:w.setTimeout.bind(w),clearTimeout:w.clearTimeout.bind(w),addEventListener:w.addEventListener.bind(w),removeEventListener:w.removeEventListener.bind(w)};
  w.BritesConciergeVoice={publicContext:native.publicContext,create(options){config=options;client=native.create({...options,onFinalizedTurn:async value=>{const result=await options.onFinalizedTurn(value);hostResults.push(clone(result));return result;},runtime,greeting:false});return client;}};
  w.BritesConciergeAvatar={create(){return {setState(){},setEmotion(){},setVisible(){},setPaused(){},triggerGreeting(){},clearFocus(){},focusProduct(){},setLevel(){},setSpeechSignal(){},clearProduct(){},showProduct(){},cancelPerformance(){},setFloating(){},cue(){}};}};
  w.eval(source['brites-storefront-bridge.js']);w.eval(source['concierge-sandbox.js']);await settle();const store=w.BritesSandboxStorefront;await store.preloadInventory();
  const execute=store.execute,present=store.presentProducts;w.BritesSandboxStorefront={...store,async execute(action,opts){controls.push(clone(action));return execute(action,opts);},presentProducts(products,opts){presentations.push(clone(products.map(p=>p.handle)));return present(products,opts);}};
  const script=d.createElement('script');script.src='/brites-concierge.js';script.dataset.sandbox='true';Object.defineProperty(d,'currentScript',{get:()=>script});w.eval(source['brites-concierge.js']);const root=d.querySelector('brites-concierge').shadowRoot;
  w.BritesConcierge.open({focus:false});[...root.querySelectorAll('button')].find(b=>b.textContent==='Talk to me').click();await settle();root.querySelector('script[src$="brites-concierge-voice.js"]')?.dispatchEvent(new w.Event('load'));await settle();assert.equal(client.state,'listening');
  const emit=event=>channel.onmessage({data:JSON.stringify(event)}),responses=()=>sent.filter(e=>e.type==='response.create'),receipts=()=>sent.filter(e=>/^(?:Host-completed result|Customer reply for this finalized shopper request)/.test(e.item?.content?.[0]?.text||''));
  function begin(){const itemId='synthetic-input-'+(++turn);emit({type:'input_audio_buffer.speech_started',item_id:itemId});emit({type:'input_audio_buffer.speech_stopped',item_id:itemId});return {itemId,version:turn+1};}
  const commit=value=>emit({type:'input_audio_buffer.committed',item_id:value.itemId}),final=(value,text)=>emit({type:'conversation.item.input_audio_transcription.completed',item_id:value.itemId,transcript:text});
  async function say(text){const input=begin();commit(input);final(input,text);await settle();return input;}
  return {w,d,root,store,products,requests,sent,hostResults,controls,presentations,tracks,errors,emit,responses,receipts,begin,commit,final,say,get config(){return config;},get client(){return client;},hide(){hidden=true;d.dispatchEvent(new w.Event('visibilitychange'));}};
}
test('finalized spoken title opens any indexed listing before model routing, with no fresh product or concierge request',async t=>{const f=await fixture(t);await f.store.execute({type:'bag'});const before=f.requests.length,input=f.begin();f.commit(input);assert.equal(f.responses().length,0);assert.equal(f.controls.length,0);f.final(input,'Open Voice Fast 119 Charm');await settle();assert.equal(f.store.snapshot().currentHandle,'voice-fast-119');assert.equal(f.controls.filter(a=>a.type==='open').length,1);assert.equal(f.responses().length,1);assert.equal(f.responses()[0].response.tool_choice,'none');assert.equal(f.receipts().length,1);assert.equal(f.requests.slice(before).filter(r=>['/api/growth/product','/api/concierge'].includes(r.url.pathname)).length,0);assert.equal(f.errors.length,0);});
test('the actual voice hook answers published material and price facts directly from complete loaded inventory',async t=>{const f=await fixture(t);await f.store.execute({type:'open',handle:'voice-fast-0'});const before=f.requests.length,revision=f.store.snapshot().contextRevision;await f.say('What materials is this piece made from and what are their prices?');assert.equal(f.store.snapshot().contextRevision,revision);assert.equal(f.controls.length,0);const receipt=JSON.stringify(f.hostResults.at(-1));assert.match(receipt,/productFacts/);assert.match(receipt,/Sterling Silver/);assert.match(receipt,/14k Gold Filled/);assert.match(receipt,/14k Solid Gold/);assert.equal(f.responses().at(-1).response.tool_choice,'none');assert.equal(f.requests.slice(before).filter(r=>['/api/growth/product','/api/concierge'].includes(r.url.pathname)).length,0);});
test('spoken menu, exact choice, quantity and gallery changes execute locally and repeated ASR/model events cannot execute again',async t=>{const f=await fixture(t);await f.store.execute({type:'open',handle:'voice-fast-0'});for(const text of ['Open the metal menu','Select 14k Gold Filled','Select 18 inches','Set quantity to 3','Show image 12'])await f.say(text);assert.equal(f.store.snapshot().productControls.itemTotalPrice,465);assert.equal(f.store.snapshot().galleryControls.selectedIndex,12);const count=f.controls.length,last={itemId:'synthetic-input-5',version:5};f.final(last,'Show image 12');await settle();const response=f.responses().at(-1);f.emit({type:'response.created',response:{id:'synthetic-final-response',metadata:response.response.metadata}});f.emit({type:'response.function_call_arguments.done',response_id:'synthetic-final-response',call_id:'duplicate-model-control',name:'control_storefront',arguments:JSON.stringify({type:'gallery',handle:'voice-fast-0',index:12})});await settle();assert.equal(f.controls.length,count);assert.equal(f.receipts().length,5);});
test('transcription arriving before native commit is delivered and executed once after commit',async t=>{const f=await fixture(t),input=f.begin();f.final(input,'Open Voice Fast 0 Necklace');await settle();assert.equal(f.controls.length,0);assert.equal(f.responses().length,0);f.commit(input);await settle();assert.equal(f.controls.filter(a=>a.type==='open').length,1);assert.equal(f.receipts().length,1);f.final(input,'Open Voice Fast 0 Necklace');f.commit(input);await settle();assert.equal(f.controls.filter(a=>a.type==='open').length,1);});
test('a host tool arriving before final ASR waits for that exact input and shares its completed local result',async t=>{const f=await fixture(t),input=f.begin();f.commit(input);const context={name:'control_storefront',inputItemId:input.itemId,turnVersion:input.version,currentTurn:true,responseId:'synthetic-early-response'},pending=f.config.onTool({type:'open',handle:'voice-fast-0'},context);await settle();assert.equal(f.controls.length,0);f.final(input,'Open Voice Fast 0 Necklace');const result=await pending;await settle();assert.equal(result.ok,true,JSON.stringify(result));assert.equal(f.controls.filter(a=>a.type==='open').length,1);assert.equal(f.store.snapshot().currentHandle,'voice-fast-0');});
test('new speech cancels an unfinished local hook and its late result cannot become a completed receipt',async t=>{const f=await fixture(t);let release,entered;const waiting=new Promise(resolve=>release=resolve),started=new Promise(resolve=>entered=resolve),host=f.w.BritesSandboxStorefront;f.w.BritesSandboxStorefront={...host,async execute(action,opts){entered();await waiting;if(opts.signal.aborted)return {ok:false,reason:'Cancelled'};return host.execute(action,opts);}};const input=f.begin();f.commit(input);f.final(input,'Open Voice Fast 0 Necklace');await started;f.emit({type:'input_audio_buffer.speech_started',item_id:'synthetic-next-input'});release();await settle();assert.equal(f.store.snapshot().pageKind,'collection');assert.equal(f.receipts().length,0);assert.equal(f.responses().length,0);});
test('failed native transcription cannot be revived by a delayed final control transcript',async t=>{const f=await fixture(t),input=f.begin();f.commit(input);f.emit({type:'conversation.item.input_audio_transcription.failed',item_id:input.itemId});f.final(input,'Open Voice Fast 0 Necklace');await settle();assert.equal(f.controls.length,0);assert.equal(f.receipts().length,0);assert.equal(f.responses().length,0);assert.equal(f.client.state,'listening');});
test('one finalized spoken sequence opens and changes four real controls using fresh step snapshots',async t=>{const f=await fixture(t);await f.say('Open Voice Fast 0 Necklace then select 14k Gold Filled then select 18 inches then set quantity to 2');const page=f.store.snapshot();assert.equal(page.currentHandle,'voice-fast-0');assert.equal(page.productControls.itemTotalPrice,310);assert.equal(f.controls.length,4);assert.equal(f.responses().length,1);assert.equal(f.responses()[0].response.tool_choice,'none');const result=f.hostResults.at(-1);assert.equal(result.action,'plan');assert.equal(result.completedActions.length,4);assert.doesNotMatch(f.receipts()[0].item.content[0].text,/completedActions|publicContext|\"action\":\"plan\"/);});
test('a finalized spoken open-then-price plan uses its new page and returns a checked local quote exactly once',async t=>{const f=await fixture(t);await f.store.execute({type:'bag'});const before=f.requests.length,input=await f.say('Open Voice Fast 119 Charm then tell me its price');assert.equal(f.store.snapshot().currentHandle,'voice-fast-119');assert.deepEqual(f.controls.map(a=>a.type),['open']);assert.equal(f.requests.slice(before).filter(r=>['/api/growth/product','/api/growth/catalogue','/api/concierge'].includes(r.url.pathname)).length,0);const text=f.receipts().at(-1).item.content[0].text,result=f.hostResults.at(-1);assert.equal(result.ok,true);assert.equal(result.action,'plan');assert.deepEqual(result.completedActions.map(a=>a.type),['open','question']);assert.equal(result.completedActions[1].handle,'voice-fast-119');assert.match(result.reply,/Voice Fast 119 Charm/);assert.match(result.reply,/Published option prices: USD 50\.00 to USD 255\.00/);assert.equal(f.responses().length,1);assert.equal(f.responses()[0].response.tool_choice,'none');f.final(input,'Open Voice Fast 119 Charm then tell me its price');const repeated=await f.config.onTool({type:'open',handle:'voice-fast-119'},{name:'control_storefront',inputItemId:input.itemId,turnVersion:input.version,currentTurn:true,responseId:'synthetic-replay-open-price'});assert.equal(repeated.alreadyCompleted,true);await settle();assert.equal(f.controls.length,1);assert.equal(f.receipts().length,1);assert.equal(f.responses().length,1);});
test('a finalized four-step spoken selection and quantity plan quotes the exact fresh subtotal from the checked cache',async t=>{const f=await fixture(t);await f.store.execute({type:'open',handle:'voice-fast-0'});await f.store.execute({type:'select-option',handle:'voice-fast-0',optionName:'Chain Length',optionValue:'18 inches'});await f.store.execute({type:'bag'});const before=f.requests.length;await f.say('Open Voice Fast 0 Necklace then select 14k Gold Filled then set quantity to 3 then tell me its price');assert.deepEqual(f.controls.map(a=>a.type),['open','select-option','product-quantity']);const page=f.store.snapshot();assert.equal(page.productControls.itemTotalPrice,465);assert.equal(page.productControls.quantity,3);assert.equal(f.requests.slice(before).filter(r=>['/api/growth/product','/api/growth/catalogue','/api/concierge'].includes(r.url.pathname)).length,0);const text=f.receipts().at(-1).item.content[0].text,result=f.hostResults.at(-1);assert.equal(result.ok,true);assert.equal(result.action,'plan');assert.equal(result.completedActions.length,4);assert.equal(result.completedActions[3].type,'question');assert.equal(result.completedActions[3].handle,'voice-fast-0');assert.match(result.reply,/14k Gold Filled \/ 18 inches is USD 155\.00 each; quantity 3 totals USD 465\.00/);assert.equal(result.publicContext.productControls.itemTotalPrice,465);assert.equal(f.receipts().length,1);assert.equal(f.responses().length,1);assert.equal(f.responses()[0].response.tool_choice,'none');});
test('explicit multi-step price and material page commands keep priority over cached fact questions',async t=>{const f=await fixture(t);await f.say('Open Voice Fast 0 Necklace then highlight the materials then scroll to price');assert.equal(f.controls.length,3);assert.deepEqual(f.controls.map(a=>a.type),['open','highlight','scroll']);const text=f.receipts().at(-1).item.content[0].text,result=f.hostResults.at(-1);assert.equal(result.action,'plan');assert.equal(result.completedActions.length,3);assert.equal(f.responses().length,1);});
test('ordinary material and price questions keep their current page and avoid every page action',async t=>{const f=await fixture(t);await f.store.execute({type:'open',handle:'voice-fast-0'});const revision=f.store.snapshot().contextRevision;await f.say('Can you tell me the price and material of this piece?');assert.equal(f.store.snapshot().contextRevision,revision);assert.equal(f.controls.length,0);assert.equal(f.receipts().length,1);assert.equal(f.responses().at(-1).response.tool_choice,'none');assert.ok(f.hostResults.at(-1).productFacts);});
test('moving the shopper pointer updates local identity without speaking, searching or selecting products',async t=>{const f=await fixture(t),before=f.requests.length,card=f.d.querySelector('[data-product-handle="voice-fast-0"]');assert.ok(card);card.dispatchEvent(new f.w.MouseEvent('pointerover',{bubbles:true}));await settle();assert.equal(f.store.snapshot().focusedHandle,'voice-fast-0');assert.equal(f.responses().length,0);assert.equal(f.receipts().length,0);assert.equal(f.controls.length,0);assert.equal(f.presentations.length,0);assert.equal(f.requests.slice(before).filter(r=>['/api/growth/product','/api/growth/catalogue','/api/concierge'].includes(r.url.pathname)).length,0);});
test('an explicit spoken material-budget search displays checked cached matches once and preserves complete page facts',async t=>{const f=await fixture(t);await f.store.execute({type:'open',handle:'voice-fast-119'});const before=f.requests.length,input=await f.say('Show 14k gold filled necklaces under $160');assert.equal(f.presentations.length,1);assert.equal(f.controls.length,0);assert.equal(f.store.snapshot().pageKind,'collection');assert.equal(f.store.snapshot().visiblePieces.length,6);assert.deepEqual(clone(f.store.snapshot().visiblePieces.map(p=>p.handle)),f.presentations[0]);assert.equal(f.requests.slice(before).filter(r=>['/api/growth/product','/api/growth/catalogue','/api/concierge'].includes(r.url.pathname)).length,0);const text=f.receipts().at(-1).item.content[0].text,result=f.hostResults.at(-1);assert.equal(result.action,'search');assert.equal(result.cached,true);assert.equal(result.inventory.loaded,120);assert.equal(result.products.length,6);for(const product of result.products){assert.equal(product.matchingPriceRange.min,150);assert.equal(product.matchingPriceRange.max,155);assert.equal(product.matchingVariantIds.length,2);}const full=await f.store.readProduct('voice-fast-0');assert.equal(full.product.images.length,16);assert.equal(full.product.options.length,2);assert.equal(full.product.variants.length,6);const repeat=await f.config.onTool({type:'search',query:'14k gold filled necklaces under $160',filter:'necklaces'},{name:'control_storefront',inputItemId:input.itemId,turnVersion:input.version,currentTurn:true,responseId:'synthetic-replay-search'});assert.equal(repeat.alreadyCompleted,true);f.final(input,'Show 14k gold filled necklaces under $160');await settle();assert.equal(f.presentations.length,1);assert.equal(f.responses().length,1);assert.equal(f.responses()[0].response.tool_choice,'none');});
test('explicit spoken recommendations retain confirmed item budget and report exact empty matches',async t=>{const f=await fixture(t);await f.say('Show sterling silver necklaces under $60');assert.equal(f.presentations.length,1);await f.say('Recommend 14k gold filled necklaces');assert.equal(f.presentations.length,2);assert.deepEqual(f.presentations[1],[]);const text=f.receipts().at(-1).item.content[0].text,result=f.hostResults.at(-1);assert.equal(result.ok,true);assert.equal(result.cached,true);assert.equal(result.products.length,0);assert.equal(result.searchCriteria.maxPrice,60);assert.equal(result.searchCriteria.material,'14k gold filled');assert.match(result.reply,/No available match/);assert.equal(f.controls.length,0);assert.equal(f.responses().length,2);});
test('a partial spoken sequence reports exactly the finished step without inventing an unavailable material',async t=>{const f=await fixture(t);await f.say('Open Voice Fast 0 Necklace then select Platinum');assert.equal(f.store.snapshot().currentHandle,'voice-fast-0');assert.equal(f.controls.length,1);const text=f.receipts()[0].item.content[0].text,result=f.hostResults.at(-1);assert.equal(result.ok,false);assert.equal(result.partial,true);assert.equal(result.completedActions.length,1);assert.equal(result.completedActions[0].type,'open');assert.equal(f.responses().at(-1).response.tool_choice,'none');});
test('native sequences stop after an external page navigation and retain the unfinished-control receipt',async t=>{const f=await fixture(t),host=f.w.BritesSandboxStorefront;f.w.BritesSandboxStorefront={...host,execute(action,opts){if(action.type==='open'){f.controls.push(clone(action));return {ok:true,navigationRequested:true,message:'The requested product page is opening.'};}return host.execute(action,opts);}};await f.say('Open Voice Fast 0 Necklace then select 14k Gold Filled');assert.equal(f.controls.length,1);assert.equal(f.store.snapshot().pageKind,'collection');const text=f.receipts().at(-1).item.content[0].text,result=f.hostResults.at(-1);assert.equal(result.ok,false);assert.equal(result.partial,true);assert.equal(result.navigationRequested,true);assert.equal(result.completedActions.length,1);assert.match(result.error,/page is opening/);assert.equal(f.responses().length,1);assert.equal(f.responses()[0].response.tool_choice,'none');});
test('private spoken engraving fills only the field and never appears in stored history or completed native receipts',async t=>{const f=await fixture(t,{engraving:true});await f.say('Open Voice Fast 0 Necklace');await f.say('Select Engraved');await f.say('Fill my engraving with PRIVATE_LITERAL_39');const field=f.d.querySelector('textarea[name="test-engraving-preview"]');assert.equal(field?.value,'PRIVATE_LITERAL_39');assert.doesNotMatch(f.w.sessionStorage.getItem('brites-concierge-v1'),/PRIVATE_LITERAL_39/);assert.doesNotMatch(JSON.stringify(f.receipts()),/PRIVATE_LITERAL_39/);assert.doesNotMatch(JSON.stringify(native.publicContext(f.config.getContext())),/PRIVATE_LITERAL_39/);});
test('new safe control context retains declared booleans and drops literal private values',()=>{const value=native.publicContext({pageKind:'product',controlVersion:1,currentHandle:'voice-fast-0',changeControls:{canUndo:true,kind:'bag-quantity',private:'SECRET'},imageControls:{open:true,url:'SECRET'},engravingControls:{available:true,enabled:true,hasText:true,maxLength:300,text:'SECRET'},giftControls:{wrappingAvailable:true,noteAvailable:true,wrapping:true,hasNote:true,savedKnown:false,giftNote:'SECRET'}});assert.equal(value.changeControls.kind,'bag-quantity');assert.equal(value.imageControls.open,true);assert.equal(value.engravingControls.maxLength,300);assert.equal(value.giftControls.savedKnown,false);assert.doesNotMatch(JSON.stringify(value),/SECRET|giftNote|"text"/);});
test('undo, closing controls and exact literal engraving use the same strict browser/server schemas',()=>{const valid=[{type:'undo'},{type:'close-options'},{type:'close-image'},{type:'set-engraving',handle:'voice-fast-0',text:'Exact shopper words'}],invalid=[{type:'undo',handle:'voice-fast-0'},{type:'close-image',url:'https://private.example'},{type:'set-engraving',handle:'voice-fast-0',text:'x'.repeat(301)},{type:'set-engraving',handle:'voice-fast-0',text:'bad\u0000text'},{type:'set-engraving',text:'Missing identity'}];for(const value of valid){assert.deepEqual(native.validateToolArguments(value,'control_storefront'),value);assert.deepEqual(server.validateToolArguments(value,'control_storefront'),value);}for(const value of invalid){assert.equal(native.validateToolArguments(value,'control_storefront'),null);assert.equal(server.validateToolArguments(value,'control_storefront'),null);}});
