const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const E=require('../../charm-nest-engraving-seals.js'),A=require('../../charm-nest-activity.js');
const old={key:'old',state:'written',approvedBy:'Paul',approvedAt:1000,row:{engrave:{}}};
E.keep(old);old.approvedAt=null;old.state='words';assert.equal(E.list(old).length,1);E.add(old,'engraveApproved','Seth',2000);assert.deepEqual(E.list(old).map(s=>s.by),['Paul','Seth']);assert.equal(E.list(JSON.parse(JSON.stringify(old))).length,2,'history survives checkpoint serialization');
const source=fs.readFileSync('charm-nest-bridge.js','utf8');
let finish,finishCheck,pressed=false,moved=0,saved=0,removed=0,checks=0,verification={ok:true};
const wait=new Promise(r=>finish=r),checkWait=new Promise(r=>finishCheck=r);
const job={key:'order',copies:['piece'],row:{order:{receiptId:'3701000'},spec:{designSku:'FROG'},engrave:{}},fit:{size:1,capMm:1,glyphs:[]},view:{cx:0,cy:0,cutMembers:[]},verify:{geometry:{ok:true}},text:'A',state:'review'};
const ctx={Date,Promise,PT:72/25.4,P:{buildBackFile:async()=>({bytes:new Uint8Array([1])})},S:{settings:{}},B:{pool:{rows:new Map()}},charmFor:()=>({sourceId:'source'}),sheetFor:()=>({}),sourceOf:()=>({parsed:{}}),fitOpts:()=>({lineGap:.18}),verifyBackFile:async()=>{checks++;await checkWait;return verification;},EG:{cardKey:null,card:null},CNListActivity:A,CNEngravingSeals:{...E,press:async()=>{pressed=true;await wait;}},employeeName:()=> 'Paul',Review:{remove(){removed++;}},goes(){moved++;},EG_TAB:()=>'',agent(){},render(){},saveBacks:async()=>saved++,toast(){},askEmployee:()=> 'Paul'};
vm.createContext(ctx);const start=source.indexOf('  async function prepareApproval('),end=source.indexOf('  /** An approval',start);vm.runInContext(source.slice(start,end),ctx);
(async()=>{
 const p=ctx.approve(job,'Paul',{});
 for(let n=0;n<10 && !checks;n++)await Promise.resolve();
 assert.equal(checks,1);assert(!pressed,'the exported file is checked before a stamp is added');assert(job.approvalPreparing);assert.equal(E.list(job).length,0);assert.equal(job.state,'review');
 await ctx.approve(job,'Paul',{});assert.equal(checks,1,'double click during file verification does not start another approval');
 finishCheck();for(let n=0;n<10 && !pressed;n++)await Promise.resolve();
 assert(pressed);assert(job.stamping);assert.equal(job.state,'review','background pollers cannot observe an approval before its stamp finishes');assert(!job.row.engrave.approved);assert.equal(moved,0);assert.equal(saved,0);assert.equal(removed,0);
 await ctx.approve(job,'Paul',{});assert.equal(E.list(job).length,1,'double click during stamping cannot record another approval');
 finish();await p;assert(!job.stamping);assert(!job.approvalPreparing);assert.equal(job.state,'approved');assert.equal(moved,1);assert.equal(saved,1);assert.equal(removed,1);
 await ctx.approve(job,'Paul',{});assert.equal(E.list(job).length,1,'an already-decided card cannot add another stamp');assert.equal(saved,1);
 verification={ok:false,why:'engraving intersects a cut-out or cut-edge clearance'};
 const failed={...job,key:'failed',state:'review',approvedAt:null,approvedBy:null,engravingSeals:[{how:'engraveApproved',at:1000,by:'Seth'}],row:{...job.row,engrave:{}}};
 await ctx.approve(failed,'Paul',{});await ctx.approve(failed,'Paul',{});
 assert.equal(failed.state,'review','a failed export remains an editable placement');assert(!failed.row.engrave.approved);assert(!failed.approvalPreparing);assert.equal(E.list(failed).length,1,'failed exports never accumulate approval seals');assert.equal(E.list(failed)[0].by,'Seth','existing historical seals remain');assert.equal(moved,1);assert.equal(saved,1);assert.equal(removed,1);
 failed.state='blocked';const before=checks;await ctx.approve(failed,'Paul',{});assert.equal(checks,before,'the keyboard cannot approve a blocked card');
 console.log('PASS: export verification precedes stamping; successful approval leaves only after the stamp finishes; failed exports and repeat clicks add no seals; historical approvals remain');
})().catch(e=>{console.error(e);process.exitCode=1;});
