const assert=require('node:assert/strict'),Rose=require('../../charm-nest-rose'),create=require('../../netlify/functions/_charmNestRoseStock'),Readiness=require('../../charm-nest-readiness');
const store=new Map(),clone=x=>structuredClone(x);
function ref(path){return {path,id:path.split('/').at(-1),collection:n=>query(path+'/'+n),get:async()=>snap(path)};}
function snap(path){return {id:path.split('/').at(-1),ref:ref(path),exists:store.has(path),data:()=>clone(store.get(path))};}
function query(path,filters=[],order=null,limit=Infinity,after=null){return {doc:id=>ref(path+'/'+id),where:(...f)=>query(path,[...filters,f],order,limit,after),orderBy:(...o)=>query(path,filters,o,limit,after),limit:n=>query(path,filters,order,n,after),startAfter:n=>query(path,filters,order,limit,n),get:async()=>{let docs=[...store.keys()].filter(k=>k.startsWith(path+'/')&&!k.slice(path.length+1).includes('/')).map(snap);docs=docs.filter(d=>filters.every(([f,op,v])=>d.data()[f]===v));if(order)docs.sort((a,b)=>(a.data()[order[0]]-b.data()[order[0]])*(order[1]==='desc'?-1:1));if(after!==null)docs=docs.filter(d=>d.data()[order[0]]<after);docs=docs.slice(0,limit);return {docs,size:docs.length};}};}
let serial=Promise.resolve();const db={runTransaction:fn=>{const promise=serial.then(async()=>{const writes=[];let wrote=false;const result=await fn({get:async r=>{assert(!wrote,'Firestore requires all reads before writes');return r.get();},set:(r,v,opts)=>{wrote=true;writes.push(()=>store.set(r.path,opts?.merge?{...store.get(r.path),...clone(v)}:clone(v)));},update:(r,v)=>{wrote=true;writes.push(()=>store.set(r.path,{...store.get(r.path),...clone(v)}));},delete:r=>{wrote=true;writes.push(()=>store.delete(r.path));}});writes.forEach(f=>f());return result;});serial=promise.catch(()=>{});return promise;}};
const api=create({db,col:query,FV:{serverTimestamp:()=>123456},Readiness});
const shape=(id,x,y,w,h)=>({id,paths:[[[x,y],[x+w,y],[x+w,y+h],[x,y+h]]]});
const sheet=(id,shapes)=>({id,metal:'rose',verification:{ok:true},status:'complete',dirty:false,saving:false,draft:false,setId:'set-test',runId:'run-test',poolIds:shapes.map(s=>s.id),placedCount:shapes.length,placements:shapes.map(s=>({id:s.id,cxPt:20,cyPt:20,angle:0,scale:1})),outputs:{ai:{url:'saved.ai'},preview:{url:'saved.png'}},label:{files:[{path:'qr',url:'qr.png',payload:'test',orders:[]}]},orders:[]});
(async()=>{
 const shapes=[shape('pool-1',2,2,10,30)];
 store.set('Charm_Nest_Runs/run-test',{lines:{a:{poolIds:['pool-1','pool-2'],spec:{engraveCandidate:false}}}});
 // Use the same real readiness decisions format as production.
 const first=await api.roseClaim({sheetId:'sheet-first',wPt:100,hPt:50});assert.equal(first.stock.revision,0);
 const stockId=first.stock.id;
 await assert.rejects(()=>api.roseClaim({sheetId:'sheet-other',stockId,wPt:100,hPt:50}),/reserved/);
 assert.equal((await api.roseClaim({sheetId:'sheet-first',wPt:100,hPt:50})).stock.id,stockId,'reload recovers the same reservation');
 const saved=sheet('sheet-first',shapes);store.set('Charm_Nest_Sheets/sheet-first',saved);
 const planArgs={sheetId:saved.id,stockId,revision:0,fingerprint:create.fingerprint(saved),shapesJson:JSON.stringify(shapes),allowanceMm:.2};
 await assert.rejects(()=>api.rosePlan({...planArgs,fingerprint:'stale'}),/layout changed/);
 const p=await api.rosePlan(planArgs);assert(JSON.parse(p.planJson).lines.length);
 const cutArgs={sheetId:saved.id,stockId,revision:0,planHash:p.planHash};
 const actual=store.get('Charm_Nest_Sheets/sheet-first');
 assert(Readiness.sheet({...actual,engraving:Readiness.decisions(Object.values(store.get('Charm_Nest_Runs/run-test').lines))}).ready,'fixture passes actual production checks');
 const [cut,retry]=await Promise.all([api.roseRecordCut(cutArgs),api.roseRecordCut(cutArgs)]);
 assert.equal(cut.stock.revision,1);assert.equal(retry.cut.at,cut.cut.at);
 assert.equal((await api.roseGet({stockId})).cuts.length,1,'duplicate requests append one historical cut');
 assert.equal((await api.roseList()).stocks[0].id,stockId);
 const next=await api.roseClaim({sheetId:'sheet-next',wPt:100,hPt:50});assert.equal(next.stock.id,stockId,'future layouts automatically reuse the saved irregular stock');
 assert.equal(next.stock.profileJson,JSON.stringify(JSON.parse(p.planJson).profile));
 await assert.rejects(()=>api.roseClaim({sheetId:'sheet-next',stockId,revision:0,wPt:100,hPt:50}),/changed/);
 await assert.rejects(()=>api.roseClaim({sheetId:'sheet-next',stockId,wPt:120,hPt:50}),/size/);
 const laterShapes=[shape('pool-2',25,2,8,25)],later=sheet('sheet-next',laterShapes);store.set('Charm_Nest_Sheets/sheet-next',later);
 const p2=await api.rosePlan({sheetId:later.id,stockId,revision:1,fingerprint:create.fingerprint(later),shapesJson:JSON.stringify(laterShapes),allowanceMm:.2});
 const before=JSON.parse(next.stock.profileJson),after=JSON.parse(p2.planJson).profile;assert(after.values.every((v,i)=>v>=before.values[i]));
 await api.roseClaim({sheetId:'sheet-next',stockId,revision:1,wPt:100,hPt:50,nesting:true});
 await assert.rejects(()=>api.roseRecordCut({sheetId:'sheet-next',stockId,revision:1,planHash:p2.planHash}),/changed/,'re-nesting invalidates the old cut plan');
 await assert.rejects(()=>api.roseRelease({sheetId:'sheet-next',stockId}),/current set/);
 store.get('Charm_Nest_Sheets/sheet-next').draft=true;
 await assert.rejects(()=>api.roseRelease({sheetId:'sheet-next',stockId}),/planned or protected/,'draft sheets retain their planned contour');
 assert.equal((await api.roseList()).stocks.length,0,'the protected physical sheet stays reserved');
 const fresh=await api.roseClaim({sheetId:'sheet-fresh',wPt:100,hPt:50,fresh:true});assert.notEqual(fresh.stock.id,stockId);
 await api.roseRelease({sheetId:'sheet-fresh',stockId:fresh.stock.id});assert.equal((await api.roseList()).stocks.length,1,'an unplanned stock reservation can still be released');
 // A prepared (uncut) green contour survives intake and remains immutable.
 const plannedShapes=[shape('locked-1',2,2,8,30)],planned=sheet('sheet-guard',plannedShapes);
 const claim=await api.roseClaim({sheetId:planned.id,wPt:100,hPt:50,fresh:true});store.set('Charm_Nest_Sheets/'+planned.id,planned);
 const fs=require('node:fs'),vm=require('node:vm'),library=fs.readFileSync('netlify/functions/charmNestLibrary.js','utf8');
 const ctx={db,col:query,FV:{serverTimestamp:()=>123456},SHEETS:'Charm_Nest_Sheets',RUNS:'Charm_Nest_Runs',DELETE_CODE:'975311',isId:()=>true,require:()=>create};vm.createContext(ctx);
 vm.runInContext(library.slice(library.indexOf('async function op_putSheet('),library.indexOf('async function op_listSheets('))+';this.put=op_putSheet;',ctx);
 vm.runInContext(library.slice(library.indexOf('async function op_deleteSheet('),library.indexOf('/* A calibration row'))+';this.del=op_deleteSheet;',ctx);
 vm.runInContext(library.slice(library.indexOf('async function op_archiveEmptySheet('),library.indexOf('// ── arrival ledger'))+';this.archive=op_archiveEmptySheet;',ctx);
    const args={sheetId:planned.id,stockId:claim.stock.id,revision:0,fingerprint:create.fingerprint(planned),shapesJson:JSON.stringify(plannedShapes),allowanceMm:.2};
    const original=await api.rosePlan(args),originalPlan=JSON.parse(original.planJson);
    store.get('Charm_Nest_Sheets/'+planned.id).draft=true;
    await assert.rejects(()=>ctx.archive({id:planned.id,runId:planned.runId}),/planned or protected/,'intake cannot archive a saved green contour');
    await assert.rejects(()=>ctx.del({id:planned.id,code:'975311'}),/planned or protected/,'deleting a planned sheet cannot erase its contour or outputs');
    await assert.rejects(()=>api.roseRelease({sheetId:planned.id,stockId:claim.stock.id}),/planned or protected/,'releasing stock cannot discard an uncut green contour');
    const continuation=await api.roseClaim({...args,wPt:100,hPt:50,nesting:true}),guard=JSON.parse(continuation.protectedJson);
    await assert.rejects(()=>ctx.archive({id:planned.id,runId:planned.runId}),/planned or protected/,'intake cannot archive an append in progress');
    await assert.rejects(()=>ctx.del({id:planned.id,code:'975311'}),/planned or protected/,'deleting during append cannot erase protected contours');
    await assert.rejects(()=>api.roseRelease({sheetId:planned.id,stockId:claim.stock.id}),/planned or protected/,'the saved green contour stays attached during continued nesting');
 assert.deepEqual(guard.profile,originalPlan.profile);assert.deepEqual(guard.placements,planned.placements);
 assert.equal((await api.roseGet({stockId:claim.stock.id})).cuts.length,0,'protecting a planned contour never fabricates a physical cut');
 assert.throws(()=>create.assertProtected(guard,[]),/cannot be moved/);
 assert.throws(()=>create.assertProtected(guard,[{...planned.placements[0],cxPt:21}]),/cannot be moved/);
 const doc=store.get('Charm_Nest_Sheets/'+planned.id);doc.dirty=false;doc.placements.push({id:'new-1',cxPt:32,cyPt:12,angle:0,scale:1});
    const incoming=shape('new-1',28,8,8,8),nextArgs={...args,fingerprint:create.fingerprint(doc),shapesJson:JSON.stringify([...plannedShapes,incoming])};
    await assert.rejects(()=>api.rosePlan({...nextArgs,shapesJson:JSON.stringify([...plannedShapes,shape('new-1',2,2,3,3)])}),/crosses protected/);
    await assert.rejects(()=>api.rosePlan({...nextArgs,shapesJson:JSON.stringify([shape('locked-1',35,2,8,30),incoming])}),/protected Rose Gold charm outlines/,'the old charm cannot move by changing only its submitted vector');
 // A reloaded layout rebuilds its saved outline from 3-decimal positions.
 const nudged=plannedShapes.map(s=>({...s,paths:s.paths.map(path=>path.map(([x,y])=>[+(x+.0004).toFixed(4),+(y-.0003).toFixed(4)]))}));
 const reloaded=JSON.parse((await api.rosePlan({...nextArgs,shapesJson:JSON.stringify([...nudged,incoming])})).planJson);
 assert.deepEqual(reloaded.shapes[0],plannedShapes[0],'a reloaded layout keeps the stored protected outline');
 const added=JSON.parse((await api.rosePlan(nextArgs)).planJson);
 assert.deepEqual(added.lines.slice(0,originalPlan.lines.length),originalPlan.lines,'original green line is preserved exactly');
 assert(added.profile.values.every((v,i)=>v>=originalPlan.profile.values[i]));
 assert.equal(added.shapes.length,2);assert.equal(doc.roseProtectedJson,continuation.protectedJson);
    const savedBefore=JSON.stringify(store.get('Charm_Nest_Sheets/'+planned.id));
    await assert.rejects(()=>ctx.put({sheet:{id:planned.id,metal:'rose',placements:[doc.placements[1]],roseProtectedJson:null}}),/cannot be moved/);
    await assert.rejects(()=>ctx.put({sheet:{id:planned.id,metal:'rose',placements:null}}),/cannot be moved/,'null cannot erase placements while retaining the protected green line');
    await assert.rejects(()=>ctx.put({sheet:{id:planned.id,metal:'rose',placements:{}}}),/cannot be moved/,'invalid placement data cannot erase the protected layout');
    await assert.rejects(()=>ctx.put({sheet:{id:planned.id,charms:[]}}),/protected Rose Gold charms/,'a charm link update cannot empty the protected source list');
    await assert.rejects(()=>ctx.put({sheet:{id:planned.id,charms:[{id:'new-1'}]}}),/protected Rose Gold charms/,'a charm link update cannot omit the original artwork');
 assert.equal(JSON.stringify(store.get('Charm_Nest_Sheets/'+planned.id)),savedBefore,'a stale/destructive save cannot erase the protected layout');
 await ctx.put({sheet:{id:planned.id,metadataNote:'safe partial update'}});
 assert.equal(store.get('Charm_Nest_Sheets/'+planned.id).metadataNote,'safe partial update','partial metadata updates need not resend charm geometry');
 const again=await api.roseClaim({...args,wPt:100,hPt:50,nesting:true});assert.equal(JSON.parse(again.protectedJson).placements.length,2,'subsequent imports lock every prepared region');
 // A third upload after a reload adds a third green line and keeps both earlier ones.
 const third=store.get('Charm_Nest_Sheets/'+planned.id);third.dirty=false;
 third.placements=third.placements.map(p=>({...p,cxPt:+(p.cxPt+.0004).toFixed(3),cyPt:+(p.cyPt-.0004).toFixed(3)}));
 third.placements.push({id:'new-2',cxPt:50,cyPt:12,angle:0,scale:1});
 const shift=s=>({...s,paths:s.paths.map(path=>path.map(([x,y])=>[+(x+.0004).toFixed(4),+(y-.0004).toFixed(4)]))});
 const thirdPlan=JSON.parse((await api.rosePlan({...args,fingerprint:create.fingerprint(third),shapesJson:JSON.stringify([...plannedShapes.map(shift),shift(incoming),shape('new-2',46,8,8,8)])})).planJson);
 assert.deepEqual(thirdPlan.lines.slice(0,added.lines.length),added.lines,'both earlier green lines are preserved exactly');
 assert(thirdPlan.lines.length>added.lines.length,'the third upload adds its own green line');
 assert.deepEqual(thirdPlan.shapes.slice(0,2),added.shapes,'stored outlines stay authoritative');
 console.log('Rose stock OK: reservations, recovery, revision conflicts, durable history, idempotent cuts, automatic remnant reuse, re-nest invalidation and explicit new stock');
})().catch(e=>{console.error(e);process.exit(1)});
